### ISSUE TITLE
Blurry rendering in 0.80 and up, when using shaders (macOS)

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#2220] opened 2023-01-13 04:43 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Issue occurs in 0.80 release build through to latest version

### What Operating System are you using?

Mac OS

### Whats your question and how can we help?

I am using DOSBox Staging in macOS. Historically, I have used forced "normal3x" scaling under the render options to get a decent image on my retina display (5120x2880) when playing in fullscreen mode. I also specify the 5120x2880 resolution rather than using the 'desktop' setting.

Since 0.80 (release build) and up, I notice the scaling option has been removed from the config file. All games running in 320x200 or lower now look extremely blurry, and I do not know how to get back to a crisp image. I used an alpha build of 0.80 (24 September 2022) which was not affected, so the change took place after that date.

It appears the issue does not affect games running in 640x480 and up, but it might just be because the blur is less obvious at higher resolutions.

Importantly, the problem only occurs when using shaders. The image appears to be scaled normally and looks OK when I set the shader as 'none'.

Here are some before (0.79) and after (0.80.1) shots to illustrate the huge difference I am noticing. Note that in these screen caps, the ones using 'normal3x' scaling in 0.79 might look weird (i.e. hardly any visible scan lines) but in fullscreen mode on my 5k retina display they do look normal.

![0 79](https://user-images.githubusercontent.com/5726214/212238680-ecc4176c-d599-437b-821a-2d604af225da.jpg)

![0 80 1](https://user-images.githubusercontent.com/5726214/212239019-7065309c-c2dc-4941-9040-1b5c864c8d61.jpg)

Here it is again, with the in-built fake lottes shader, first is 0.79 and second is 0.80.1:

![0 79_fake_lottes](https://user-images.githubusercontent.com/5726214/212240789-1a45fc06-f350-4bc8-b536-92a3727077f9.jpg)

![0 80 1_fake_lottes](https://user-images.githubusercontent.com/5726214/212240816-fbe89853-4e96-4e44-9c1b-a4af8b3a14f6.jpg)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-01-13 05:55
Yes, I can see those differences. 

The fake lottes 0.80.1, each EGA/TGA row of pixels is converted to one shaded CRT row; essentially 1:1. 

Where as fake lottes 0.79 screenshot  shows three CRT rows per EGA/TGA row, due to the normal3x software scaling taking place prior to the image being handed over to the shader. 

For the long haul, @GranMinigun is refactoring the video pipeline to permit multiple shader passes. So you can stack a simple 2x or 3x scalar ahead of your CRT shader; and both will be efficiently performed in hardware (just like the current single-phase implementation does). 

In the meantime though, another option is to insert 2x and 3x prescaling right inside the current shaders.  

Because the shaders are text strings, deally the pre-scalar could be parameterized and read from a conf settings, prior to passing the shader over to opengl. Just some ideas.. I'm not familiar with shader code (help wanted!)

**Comment by almeath** [comment] 2023-01-13 06:19
Thanks for the explanation @kcgen. Unfortunately, I am not that skilled in manipulating the code in shader files, other than tweaking fixed output settings.

Is there any way to compile DOSBox Staging 0.80 and up, with the old renderer enabled in the config?

**Comment by kcgen** [comment] 2023-01-13 06:37
jmarsh's addition of glshaders the DOSBox SVN codebase ushered in hardware scaling, and replaced most of the software scalers with GL-accelerated equivalents. 

We want to continue going in this direction (more justification in my commit here: <https://github.com/dosbox-staging/dosbox-staging/pull/2101/commits/c73d8b22a1c73d89c48c6970beb3ac7a48d2a682>); so at least for me, I am not willing to pour hours into bringing back software scaling. It's just not where we want the project to go. Effort is best spent on the hardware accelerated route.

> Is there any way to compile DOSBox Staging 0.80 release build, and up, with the old renderer enabled

That said, you can definitely persue it for yourself, and it might be possible. I would suggest learning how to do git commit reverts. Once you can do a practice for revert, you need to revert the commits in reverse order here: https://github.com/dosbox-staging/dosbox-staging/pull/2101/commits

Start with the very bottom commit (lowered msvc warning count), work up reverting each of the deprecated flags, and then finally revert the software render drop commit. 

At that point, if the reverts worked, you will have it back and can compile locally.

**Comment by johnnovak** [comment] 2023-01-13 06:45
I'm not entirely sure what you were doing before, but I can tell you the shaders in 0.80.1 work 100% correctly and as intended on high DPI displays.

That screenshot about the lottes shader on 0.80.1 looks correct, and that's how it's supposed to look. That weird "sharp version" on 0.79.0 is totally broken...

Using the software scalers together with CRT shaders in particular is generally a bad idea and would just give you some bogus results that you might even like, but that has no basis in "reality", and it's not how these CRT shaders were designed to be used. Generally, CRT shaders expect the unscaled raw pixels as input, and that's the end of it. If you don't like the resulting "blurriness", you should look for a CRT shader that has a sharpness control and adjust to taste. Again, using some integer prescaling factor and then applying the CRT shader on top of that would just give you some bogus results... that's most definitely _not_ the way to go about increasing  the sharpness of CRT shaders!

First, I suggest to decide what you want exactly, then based on that do either of the following:

- If you simply want "crisp pixels", the either use the default `sharp` OpenGL shader, or the `openglpp` output mode for pixel-perfect integer scaling.
- If you want to use CRT shaders, find one that you like (there are lots of new ones included in 0.80.0), and then tweak the parameters to taste. You seem to dislike the "blurriness" of the lottes shader—find one that has sharpness controls and play around with it a bit. You can edit the parameters in the shader file, save, then reload it without having to restart DOSBox by pressing the Cmd+F2 shortcut (be aware that reloading works correctly with most shaders, but not all, unfortunately).

Below is a screenshot of Space Quest 3 using a custom-tweaked version of the `aperture` shader I'm using for all my EGA gaming needs.

This is the config I'm using:

``` ini
[sdl]
viewport_resolution = 1200x900

[render]
glshader = crt-aperture.ega-lores-retina.glsl
```

I've attached the shader as well:
[crt-aperture.ega-lores-retina.glsl.zip](https://github.com/dosbox-staging/dosbox-staging/files/10408779/crt-aperture.ega-lores-retina.glsl.zip)

You can play around with the sharpness settings on lines 108-109 (edit, save, then Cmd+F2 to see the changes while running a game):

```
#define SHARPNESS_IMAGE 3.0
#define SHARPNESS_EDGES 3.0
```

Good luck, and I hope you'll be able to come up with something you like using the correct pipeline! 😎 

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/698770/212251378-8ee56ff9-852b-4b9d-9ba9-ae0e5598ce13.png">

**Comment by kcgen** [comment] 2023-01-13 06:55
@almeath ⬆️ 

When @johnnovak's lighting the path ahead, there is no need to look back! 🕯️

**Comment by almeath** [comment] 2023-01-13 07:15
Thanks @kcgen and @johnnovak. I do understand the rationale for the removal of the software scaler going forward. It is not that I am wedded to the old way of doing things, rather that I had found the software scaler provided me with an easy way to take the edge off some of the CRT shaders that I found too rough on the eyes. I have been trying to develop the perfect settings to emulate a 90's shadow mask VGA CRT monitor, rather than earlier iterations from the 80's with very pronounced scan lines.

These changes just mean I will need to spend some time seeing if I can successfully tweak the settings on my favorite shaders to sharpen the image to my liking, while preserving the clarity of the shadow mask effect and keeping the scan lines subtle. My favorite shader is a tweaked version of 'CRT lots tweaked', so I will start there. Just brining across my favorite pre-sets into 0.80.1 without the extra software scaling just makes my eyes water.. I know shaders are very subjective, but I am not against a blur to the image per se .. I just like it more subtle.

**Comment by johnnovak** [comment] 2023-01-13 07:44
You'll definitely need to tweak your existing shaders for the new pipeline, @almeath. I'm finding myself creating two quite different versions of the shaders I'm using, one aimed for 1080p resolutions, and the other for high-res "Retina" displays.

Since you seem to be interested in emulating the double-scanned low-res VGA look, here's my setting that achieves exactly that. Note you'll need to use `machine = vgaonly` with this to enable double-scanning (and sadly this doesn't work with VESA games).

[crt-aperture.vga-retina.glsl.zip](https://github.com/dosbox-staging/dosbox-staging/files/10409263/crt-aperture.vga-retina.glsl.zip)

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/698770/212264174-55111497-e84a-4648-bd75-9e638d490c33.png">

**Comment by almeath** [comment] 2023-01-13 08:03
@johnnovak , thanks for the very helpful advice, and for the shader adjusted for use on retina displays. That has been my main problem with shaders for years, that most are adjusted to look great at the standard HD/1080p resolution (given it is basically the default in the PC world), but very few of them cater for high-res displays which are more common on Macs. I haven't used lower than quad HD since 2013 .. so I tried to formulate my own methods. I will certainly try out your shader and run some more tests. I am interested in both VGA and EGA-optimized looks, as my interest spans games from approximately 1984 to 1995, with some SVGA late DOS titles. 

By the way, I really enjoyed your blog post on CRT shaders for the Amiga, and I am looking forward to the sequel focusing on DOS gaming. :-)

**Comment by johnnovak** [comment] 2023-01-13 08:47
> By the way, I really enjoyed your blog post on CRT shaders for the Amiga, and I am looking forward to the sequel focusing on DOS gaming. :-)

Thanks man, I appreciate it 😎 I'm intending to write it in the next few months.

**Comment by almeath** [comment] 2023-01-14 07:48
@johnnovak , I've been playing around with both your shaders (attached above) and I am enjoying them a lot. I am not sure if these were developed with 4k as a reference point (being the most common hi-res screen size), but I have made some small adjustments (slight increases to SCANLINE_SIZE_MIN and SCANLINE_SIZE_MAX) in order to soften the scan lines to suit my tastes on my 5k display.

I was wondering if you had any similar tweaked shader (or could suggest any other) that is optimized for machinetype=tandy? I know you designed the above for VGA only, so I do notice a big difference when trying to use  them in Tandy mode.

**Comment by johnnovak** [comment] 2023-01-14 08:13
Cheers, glad you managed to come up with something you like!

The EGA shader I posted above (the one that goes with the Space Quest 3 screenshot) is suitable for all pre-VGA graphics modes. So CGA, EGA, TGA (Tandy), and maybe even Hercules. Pre-VGA graphics adapters use 15kHz line frequency in 200-line modes. There's physically 200 scanlines on the screen, so they need to be thick enough to minimise the black space between the lines. But if you increase the diameter of the electron beam to make the lines appear thicker, it becomes less focused too, which results in a blurrier picture (similar how Amiga displays and TVs from the 80s look). So, all pre-VGA monitors have visible scanlines, and you can never get as sharp a picture out of them as from the cheapest VGA monitor. (This is an extremely simplified explanation, mind you...)

VGA, on the other hand, fakes the 200-lines modes. VGA adapters always display 400 lines in 200-line modes because the lowest line frequency they support is 31kHz. That's right, 320x200 effectively becomes 640x400, that's how the monitor sees it! So every line is _doubled_, and with the much more tighly focused electron beam of the VGA monitors, plus the line doubling, the result is sharply delineated, chunky little rectangular pixels. If you zoom on the Gods screenshot, you'll  notice that there are _two_ scanlines going through every single pixel. That's the VGA line-doubling for you in 200 to 240 line low-res modes.

If you play any Tandy, EGA, CGA, etc. games on a VGA adapter, then you'll see the VGA adapter's _emulation_ (!) of these originally 200-lines modes. So if you grew up with a VGA, naturally all these pre-VGA monitor emulations will look blurry to you.

Basically, you have two choices: either emulate a "real" CGA, EGA, Tandy, etc. monitor, or the emulate how VGA adapters displayed these modes with line-doubling.

Now, `machine=vgaonly` will work with EGA game, but not with the Tandy, and I think that's your problem. Basically, what you're after is to emulate an imaginary setup where you hooked up a VGA monitor that line-doubles the TGA graphics. I don't think that physically possible, but whatever, why not. But you cannot do that with DOSBox right now either because you need to use `machine=tandy`.

Anyway, at least now you have an explanation :)

Below are some screenshots of real EGA monitor in action—notice the scanlines and the blurriness. Of course, not all pre-VGA monitors were created equal, there must have been some comparatively sharp ones. But now at least you should have a better understanding of what you're trying to achieve: a sharp "EGA monitor", or just the "VGA emulation" of pre-EGA games with double scanning.

Once we have a much more flexible shader pipeline, emulating double-scanned Tandy graphics would become a reality, but unfortunately not for now.


![image](https://user-images.githubusercontent.com/698770/212462399-c3b26bf7-4e6c-45bd-ae10-bb3915ea7254.png)

https://www.youtube.com/watch?v=fF51XYFNFWE

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/698770/212462437-d42aa59c-24f5-439c-b219-0c30e9456b68.png">

**Comment by almeath** [comment] 2023-01-14 09:07
@johnnovak , thanks for that very clear and useful explanation, which has definitely wetted my appetite for your next blog post when the time comes :-). The screen shots are particularly helpful as I continue to tweak the shaders to find the optimum effect I am seeking.

I do think my recollections are based around comparatively late-era VGA monitors of the 1990s and early 2000s. By the time I got into PC gaming, the EGA era had well and truly passed. I never had the privilege to see an original Tandy machine in action.

**Comment by johnnovak** [comment] 2023-02-16 04:56
Closing this as I don't consider it to be a technical issue or the shortcoming of DOSBox, more like a user expectation thing.

**Closed by johnnovak** 2023-02-16 04:56 UTC
Labels: question
