### ISSUE TITLE
Dosbox closed during emulator initialization.

### ISSUE THREAD

**Issue by F0xMcloud** [dosbox-staging/dosbox-staging#3669] opened 2024-05-12 15:26 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

Emulator is closed during initialization, console log don't show none system message error.

But on the contrary developed builds work fine, i have this issue from 0.81 release and now with latest stable version 0.81.1

This is log showed before closed:

G:\DOSBox Staging>dosbox.exe
date       time         |
2024-05-12 17:22:22.814 | arguments: dosbox.exe
2024-05-12 17:22:22.815 | Current dir: G:\DOSBox Staging
2024-05-12 17:22:22.815 | stderr verbosity: 0
2024-05-12 17:22:22.815 | -----------------------------------
2024-05-12 17:22:22.815 | dosbox-staging version 0.81.1
2024-05-12 17:22:22.815 | ---
2024-05-12 17:22:22.815 | LOG: Loguru version 2.1.0 initialised
2024-05-12 17:22:22.822 | CONFIG: Loaded primary config file 'C:\Users\aaron\AppData\Local\DOSBox\dosbox-staging.conf'
2024-05-12 17:22:22.840 | LANG: Loaded language file: resources\translations\es.lng
2024-05-12 17:22:22.856 | SDL: version 2.30.0 initialised (windows video and wasapi audio)
2024-05-12 17:22:22.857 | DISPLAY: Initialised 1067x800 windowed mode using bilinear scaling on display-0
2024-05-12 17:22:23.104 | OPENGL: Vendor: NVIDIA Corporation
2024-05-12 17:22:23.104 | OPENGL: Version: 4.6.0 NVIDIA 474.82
2024-05-12 17:22:23.105 | OPENGL: GLSL version: 4.60 NVIDIA
2024-05-12 17:22:23.105 | OPENGL: NPOT textures supported
2024-05-12 17:22:23.105 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2024-05-12 17:22:23.136 | RENDER: Auto-switched to shader 'crt/hercules'
2024-05-12 17:22:23.136 | VGA: Pixel doubling enabled

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment] 2024-05-15 17:20
Hi, please post your config file so i can reproduce this!

**Comment by F0xMcloud** [comment] 2024-05-15 19:51
[dosbox-staging.zip](https://github.com/dosbox-staging/dosbox-staging/files/15326271/dosbox-staging.zip)

hi, here is my config file, tested with last development build today (working), but when i use stable build from 0.81 to 0.81.1 emulator is closed.

**Comment by Burrito78** [comment] 2024-05-15 23:58
The config looks ok to me besides the autoexec part:
```
[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.

imgmount D ".\cd_image\cd1\Command & Conquer (USA, Europe) (Disc 1).cue" ".\cd_image\cd2\Command & Conquer (USA, Europe) (Disc 2).cue" ".\cd_image\cd3\Command & Conquer - The Covert Operations (Europe).cue" -t cdrom
c:
cd C&C
C&C
```

You need to mount a C drive too before opening it using "C:".

**Comment by Burrito78** [comment] 2024-05-15 23:59
Of course it shouldn't crash, thats a bug that is triggered by that config of yours.

**Comment by johnnovak** [comment] 2024-05-16 00:28
Are you using automounts? Is there ` drives/c` subfolder in the game folder?

**Comment by F0xMcloud** [comment] 2024-05-16 15:36
> Are you using automounts? Is there ` drives/c` subfolder in the game folder?

yes, i use automount drive c



> Also, can you add a 'pause' before the CD-ROM mounting and after it? I guess it's that huge mount parameter that crashes it.
> 
> Someone else on Windows can try to replicate with your config.

with development build work without problem all these cd images mounted, even with one autoexec section empty i have issue
when emulator is running

**Comment by LukasThyWalls** [comment] 2024-06-03 09:45
Hello.

I want to revamp this because I think this was misinterpreted. I think I have this exact same issue too, but to me the Config file doesn't matter: I tested with the default one, with no one and using _--noprimaryconf_: v0.81.1 crashes in initialisation without any error:

```
E:\Lukas ThyWalls\Escritorio\DOSBox Staging\dosbox-staging-v0.81.1>dosbox --noprimaryconf
date       time         |
2024-06-03 11:07:28.713 | arguments: dosbox --noprimaryconf
2024-06-03 11:07:28.714 | Current dir: E:\Lukas ThyWalls\Escritorio\DOSBox Staging\dosbox-staging-v0.81.1
2024-06-03 11:07:28.714 | stderr verbosity: 0
2024-06-03 11:07:28.715 | -----------------------------------
2024-06-03 11:07:28.715 | dosbox-staging version 0.81.1
2024-06-03 11:07:28.716 | ---
2024-06-03 11:07:28.717 | LOG: Loguru version 2.1.0 initialised
2024-06-03 11:07:28.730 | LANG: Loaded language file: resources\translations\es.lng
2024-06-03 11:07:28.755 | SDL: version 2.26.5 initialised (windows video and wasapi audio)
2024-06-03 11:07:28.756 | DISPLAY: Initialised 888x666 windowed mode using bilinear scaling on display-0
2024-06-03 11:07:29.053 | OPENGL: Vendor: NVIDIA Corporation
2024-06-03 11:07:29.053 | OPENGL: Version: 4.6.0 NVIDIA 536.23
2024-06-03 11:07:29.055 | OPENGL: GLSL version: 4.60 NVIDIA
2024-06-03 11:07:29.056 | OPENGL: NPOT textures supported
2024-06-03 11:07:29.057 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2024-06-03 11:07:29.088 | RENDER: Auto-switched to shader 'crt/hercules'
2024-06-03 11:07:29.089 | VGA: Pixel doubling enabled
```

What I was searching in the first place was a way to increase the stderr verbosity (but I realised that maybe you need to do that compiling it with the needed flags), because there is no error that could give a hint of what is happening. And doing that I found this issue reported, but I didn't find anything else pointing out what issue could be or a fixed issue related to that.

So, what i did is testing several DOSBox Staging versions, because the old one i have (0.79 or prior) worked fine:
- 0.80.0 -> Works.
- 0.80.1 -> Doesn't work.
- 0.81.0 -> Doesn't work.
- 0.81.1 -> Doesn't work.
- 0.82.0-alpha-25182 -> Works.

Like i said, I'm testing them with the default config file but using _--noprimaryconf_ in all cases, and the ones that don't work do the same thing posted above.

To me, the OP has the same issue, because the development build also works to him, but He hasn't done a proper testing with DOSBox Staging without the config file or with a default one.

Now, because It's working in the alpha versions, this issue is supposedly fixed in the future 0.82.0, but I want to test it more because It's not the first time I'm testing something and several main versions still don't work when the development ones work fine to me. **Is it a page here what explains what i need to do to increase the verbosity without compiling myself everything again?** (It's not I can't do it, but in my actual position It could add a lot of variables and maybe I can't do a proper testing, and then maybe the better thing would be to wait to see if 0.82.0 is fixed).

Thanks!

**Comment by johnnovak** [comment] 2024-06-03 10:03
@LukasThyWalls First of all, you saw `stderr verbosity: 0` in the logs and started to create theories based on that. That's just something our logger framework does by default, it has no significance. Ignore it. The logs contains all relevant info, and there's no way to instruct a release build to do more verbose logging.

Based on the logs, you seem to have a dedicated Nvidia card, so that can't be the issue (some Intel iGPUs are flaky with OpenGL). Still, you can try to start dosbox with `output = texture` in the `[dosbox]` section—does that improve anything?

I noticed you have `resources\translations\es.lng` in your config. We had reports where people got mysterious crashes then the pathnames contained non-English alphabet letters. Can you copy your whole Staging installation directory into a "safe" directory and test there, just starting it up from the console? E.g., `D:\DOSBox` or whatever.

Just take the portable install, extract it to `D:\DOSBox` and start it with `dosbox.exe --noprimaryconf` from the console. What do you get then? Still crashes?

**Comment by LukasThyWalls** [comment] 2024-06-03 11:09
> @LukasThyWalls First of all, you saw `stderr verbosity: 0` in the logs and started to create theories based on that. That's just something our logger framework does by default, it has no significance. Ignore it. The logs contains all relevant info, and there's no way to instruct a release build to do more verbose logging.

Ok, so there isn't any information relevant to the issue in the log. I was guessing that DOSBox Staging are also using log error levels like many other projects and there was other levels with more detailed info.

> Based on the logs, you seem to have a dedicated Nvidia card, so that can't be the issue (some Intel iGPUs are flaky with OpenGL). Still, you can try to start dosbox with `output = texture` in the `[dosbox]` section—does that improve anything?
> 
> I noticed you have `resources\translations\es.lng` in your config. We had reports where people got mysterious crashes then the pathnames contained non-English alphabet letters. Can you copy your whole Staging installation directory into a "safe" directory and test there, just starting it up from the console? E.g., `D:\DOSBox` or whatever.
>
> Just take the portable install, extract it to `D:\DOSBox` and start it with `dosbox.exe --noprimaryconf` from the console. What do you get then? Still crashes?

- DOSBox 0.81.1 in `D:\dosbox\`
- `--lang en`*
- `dosbox-staging.conf` in folder `D:\dosbox\` with only this content:
```
[sdl]
output              = texture
```

Same crash, same output:
```
D:\dosbox>dosbox.exe --lang en
date       time         |
2024-06-03 12:57:01.263 | arguments: dosbox.exe --lang en
2024-06-03 12:57:01.265 | Current dir: D:\dosbox
2024-06-03 12:57:01.265 | stderr verbosity: 0
2024-06-03 12:57:01.267 | -----------------------------------
2024-06-03 12:57:01.267 | dosbox-staging version 0.81.1
2024-06-03 12:57:01.268 | ---
2024-06-03 12:57:01.269 | LOG: Loguru version 2.1.0 initialised
2024-06-03 12:57:01.270 | CONFIG: Using portable configuration layout in 'D:\dosbox'
2024-06-03 12:57:01.272 | CONFIG: Loaded primary config file 'D:\dosbox\dosbox-staging.conf'
2024-06-03 12:57:01.272 | LANG: Using internal English language messages
2024-06-03 12:57:01.303 | SDL: version 2.26.5 initialised (windows video and wasapi audio)
2024-06-03 12:57:01.305 | DISPLAY: Initialised 888x666 windowed mode using bilinear scaling on display-0
2024-06-03 12:57:01.782 | VGA: Pixel doubling enabled
```

*NOTE: I also tried to interchange es.lng with en.lng in `D:\dosbox\resources\translations`, but It only shows some yellow errors in the logger with the same crash result in the end.

> I'm thinking this might be some localisation related issue. Also, our current alpha build is compiled on MSVC, but the 0.81.x was compiled on MinGW. Maybe @FeralChild64 and @shermp can also chime in about localisation/compiler issues when it come to path names containing non-English alphabet letters.

I was gonna to say that could be something about the spaces character in paths, because it's something that happened to me before, but with this test there isn't any spaces in paths but It also crashes.
About a language thing triggered by the compiler... maybe, but without any more info, I don't know what I can do to help you...

**Comment by johnnovak** [comment] 2024-06-03 11:36
Yeah I really don't know, man, sorry.

**Comment by interloper98** [comment] 2024-06-03 11:41
What's your CPU make and model? 
Try copying the dll's from the working alpha build, and overwrite then in the non-working 0.81.1 dir. 

Maybe there were buga fixed in the newer DLLs. That sometimes worked with the original dosbox, too.

**Comment by johnnovak** [comment] 2024-06-03 11:53
> What's your CPU make and model?
> 
> Try copying the dll's from the working alpha build, and overwrite those in the non-working 0.81.1 dir (just as a test).
> 
> Maybe there were bugs fixed in the newer DLLs. This trick sometimes worked with the original dosbox, too.

That won't work because of the MSVC vs MSYS2 differences I believe.

**Comment by LukasThyWalls** [comment] 2024-06-03 12:00
I redid my testings and I was wrong about what versions works and what versions wasn't.
This time also I tested the 0.81.0 Release Candidates (all are the portable zip versions from [here](https://github.com/dosbox-staging/dosbox-staging/releases/)):

- 0.80.0 -> Works.
- 0.80.1 32 bit -> Works.
- 0.80.1 64 bit -> Works.
- 0.81.0 RC1 -> Works.
- 0.81.0 RC2 -> Doesn't work.
- 0.81.0 -> Doesn't work.
- 0.81.1 -> Doesn't work.
- 0.82.0-alpha-25182 -> Works.

**Comment by johnnovak** [comment] 2024-06-03 12:27
Copy the DLLs from 0.81.0 RC1 into 0.81.1. Those are compatible. Do it one DLL at a time. My bet is SDL as the culprit.

**Comment by Grounded0** [comment] 2024-06-03 13:04
@johnnovak 

Did we bump SDL for 0.82.0-alpha and to which version?

**Comment by johnnovak** [comment] 2024-06-03 13:13
> @johnnovak
> 
> Did we bump SDL for 0.82.0-alpha and to which version?

Yes. 2.30.0.

https://github.com/dosbox-staging/dosbox-staging/pull/3606

**Comment by LukasThyWalls** [comment] 2024-06-03 16:57
> Copy the DLLs from 0.81.0 RC1 into 0.81.1. Those are compatible. Do it one DLL at a time. My bet is SDL is the culprit.

No dice. I tried putting all 0.81.0 RC1 DLLs into 0.81.1 folder and It does the same (also I tried first to put only the SDL libraries DLLs, but with only them also they don't work). I tried also the opposite thing (putting only the 0.81.1 EXEs in a 0.81.0 RC1 folder, so ALL the files are the 0.81.0 RC1 ones including the subfolders, but the result are the same). I tested too changing between 0.81.0 RC1 and 0.81.0 RC2, with exact same results: With 0.81.0 RC1 Exe works, with 0.81.0 RC2 or 081.01 Exes doesn't, no matter what other files are in the folder.

> @LukasThyWalls - what's your exact CPU model?

It's a _AMD Phenom II X4 B50_, which is in reality an _[AMD Athlon II X3 450](https://www.cpu-world.com/CPUs/K10/AMD-Athlon%20II%20X3%20450%20-%20ADX450WFK32GM%20(ADX450WFGMBOX).html)_ with the 4th core unlocked via motherboard using AsRock UCC Feature. (Looking for the info, I just realised that I didn't have the core unlocked since I reinstalled the motherboard a while back, so I did now). 
![imagen](https://github.com/dosbox-staging/dosbox-staging/assets/1467366/15b9901b-ffd4-4402-8935-b59097b7c225)

---

Also to note, I saw with 0.81.0 RC1 what should be the output compared with the ones with the crash:

<details>
<summary>Output from DOSBox Staging 0.81.0 RC1 (Added mark when 0.81.0 RC2, 0.81.0 and 0.81.1 stops because they crash)</summary>

```
E:\Lukas ThyWalls\Escritorio\DOSBox Staging\dosbox-staging-windows-msys2-x86_64-v0.81.0-rc1>dosbox --noprimaryconf
date       time         |
2024-06-03 18:47:10.109 | arguments: dosbox --noprimaryconf
2024-06-03 18:47:10.110 | Current dir: E:\Lukas ThyWalls\Escritorio\DOSBox Staging\dosbox-staging-windows-msys2-x86_64-v0.81.0-rc1
2024-06-03 18:47:10.110 | stderr verbosity: 0
2024-06-03 18:47:10.110 | -----------------------------------
2024-06-03 18:47:10.111 | dosbox-staging version 0.81.0-rc1
2024-06-03 18:47:10.111 | ---
2024-06-03 18:47:10.111 | LOG: Loguru version 2.1.0 initialised
2024-06-03 18:47:10.121 | LANG: Loaded language file: resources\translations\es.lng
2024-06-03 18:47:10.146 | SDL: version 2.28.5 initialised (windows video and wasapi audio)
2024-06-03 18:47:10.146 | DISPLAY: Initialised 888x666 windowed mode using bilinear scaling on display-0
2024-06-03 18:47:10.440 | OPENGL: Vendor: NVIDIA Corporation
2024-06-03 18:47:10.440 | OPENGL: Version: 4.6.0 NVIDIA 536.23
2024-06-03 18:47:10.441 | OPENGL: GLSL version: 4.60 NVIDIA
2024-06-03 18:47:10.441 | OPENGL: NPOT textures supported
2024-06-03 18:47:10.441 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2024-06-03 18:47:10.471 | RENDER: Auto-switched to shader 'crt/hercules'
2024-06-03 18:47:10.471 | VGA: Pixel doubling enabled
(0.81.0 RC2, 0.81.0 and 0.81.1 Crash)
2024-06-03 18:47:10.472 | VIDEO: Using the DOS video mode's frame rate
2024-06-03 18:47:10.490 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0000024484800040
2024-06-03 18:47:10.490 | VGA: Double scanning VGA video modes enabled
2024-06-03 18:47:10.493 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2024-06-03 18:47:10.501 | VOODOO: Initialized with 4 MB of RAM, multithreading, and no bilinear filtering
2024-06-03 18:47:10.502 | CAPTURE: Image capturer started
2024-06-03 18:47:10.536 | MIXER: Negotiated 2-channel 48000 Hz audio of 1024-frame blocks
2024-06-03 18:47:10.536 | MIXER: Master compressor enabled
2024-06-03 18:47:10.564 | MIDI: Opened device: win32
2024-06-03 18:47:10.567 | MPU-401: Running in intelligent mode on ports 330h and 331h
2024-06-03 18:47:10.567 | OPL: Operating at 48000 Hz without resampling
2024-06-03 18:47:10.568 | OPL: Running OPL3 on ports 220h and 388h
2024-06-03 18:47:10.569 | SB16: Sound Blaster 16 OPL output filter enabled
2024-06-03 18:47:10.569 | DMA: Initialised primary controller
2024-06-03 18:47:10.570 | DMA: Initialised secondary controller
2024-06-03 18:47:10.573 | SB: Operating at 22050 Hz and upsampling to the output rate
2024-06-03 18:47:10.574 | SB16: Modern DAC output filter enabled
2024-06-03 18:47:10.575 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2024-06-03 18:47:10.575 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2024-06-03 18:47:10.576 | PCSPEAKER: Operating at 48000 Hz without resampling
2024-06-03 18:47:10.577 | PCSPEAKER: Initialised discrete model
2024-06-03 18:47:10.577 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2024-06-03 18:47:10.578 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2024-06-03 18:47:10.579 | MOUSE: Will be captured after the first left or right button click
2024-06-03 18:47:10.580 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2024-06-03 18:47:10.580 | MOUSE (PS/2): Standard, 3 buttons
2024-06-03 18:47:10.590 | RENDER: Auto-switched to shader 'interpolation/sharp'
2024-06-03 18:47:10.590 | VGA: Forcing single scanning of double-scanned VGA video modes
2024-06-03 18:47:10.591 | VGA: Forcing no pixel doubling
2024-06-03 18:47:10.593 | SDL: Using standard SDI (auto) display refresh rate of 75 Hz
2024-06-03 18:47:10.671 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 888x666 pixels with 1:1.35 (20:27) pixel aspect ratio
2024-06-03 18:47:10.754 | DOS: Loaded codepage 858 for detected language 'es'
2024-06-03 18:47:10.768 | DOS: Loaded modern locale for country 34, 'Spain'
2024-06-03 18:47:10.768 | SLIRP: Slirp version: 4.7.0
2024-06-03 18:47:10.770 | SLIRP: Successfully initialized
2024-06-03 18:47:10.770 | NE2000: Initialised on port 300h and IRQ 3
2024-06-03 18:47:10.775 | CONFIG: Loaded auto-mounted drive config file 'resources\drives\y.conf'
2024-06-03 18:47:10.789 | MAPPER: No joysticks found
2024-06-03 18:47:10.790 | MAPPER: Loaded default key bindings
2024-06-03 18:47:10.794 | MOUNT: Path 'resources\drives\y' found
2024-06-03 18:47:13.432 | PCSPEAKER: Shutting down discrete model
2024-06-03 18:47:13.433 | OPL: Shutting down OPL3
2024-06-03 18:47:13.434 | SB16: Shutting down
2024-06-03 18:47:13.435 | MPU-401: Shutting down
2024-06-03 18:47:13.438 | CAPTURE: Image capturer shutting down
2024-06-03 18:47:13.438 | DMA: Shutting down primary controller
2024-06-03 18:47:13.439 | DMA: Shutting down secondary controller
2024-06-03 18:47:13.512 | atexit
```

</details>

**Comment by Grounded0** [comment] 2024-06-03 17:01
Which video card do you have an what is the driver version?

**Comment by interloper98** [comment] 2024-06-03 17:23
Great eye spotting that, @Grounded0. That's what I was worried about, but wasn't sure where to look.

I also don't see how Visual Studio can adjust fine-grained instructions here: https://learn.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170

Maybe the team can build a slower & compatible build? (MinGW, instead of Visual Studio?)

**Comment by Grounded0** [comment] 2024-06-03 17:27
If 0.82-alpha works then the user should continue using that until we hit 0.82.0 release. 2010 computers are unsupported from our end and we will not do anything to ameliorate the situation.

**Comment by Burrito78** [comment] 2024-06-03 17:45
That is a 14 year old budget CPU, the Phenom line was introduced in 2007.
DOSBox Stagings goal is to getting old stuff running on modern systems, not on vintage hardware.

**Comment by MasterO2** [comment] 2024-06-03 17:59
> I remember people opposing DOSBox moving to SDL2 due to them wanting to continue running DOSBox on Windows NT 4.0 from 1996... Closing before i go to sleep.

They can just use **Dosbox 0.74-3** instead.  (sarcasm)

**Comment by interloper98** [comment] 2024-06-03 18:01
> If 0.82.0-alpha works

This is the way :-) Looking down at my own CI build I'm running.

Worst case @LukasThyWalls , you can always setup your own build environment using the build guide and set your CPU type that way.

Looks pretty easy here - https://stackoverflow.com/questions/54610709/rationale-behind-making-any-cpu-prefer-32-bit-the-default-build-setting-in-vs

Could even select a 32-bit build.

**Comment by johnnovak** [comment] 2024-06-03 21:48
@LukasThyWalls zlib_ng is what requires SSSE3. We introduced it as it results in 3x faster video and PNG captures.

You can compile your own version with `Duse_zlib_ng` disabled. Old zlib will work on your aging computer 😄 

We won't support 14 year old budget CPUs, yeah... 😄 But maybe zlib_ng could be instructed to do the SSSE3 checknat runtimr. We might do that if it's simple.

**Closed by johnnovak** 2024-06-03 21:48 UTC
Labels: question, out of scope, not a bug

**Comment by interloper98** [comment] 2024-06-03 22:11
And with 0.82-alpha CI builds already working on @LukasThyWalls's system, I think that's got them 99% of the way already! (If @LukasThyWalls really needs 0.81.1, then they can get a build environment going with your tips about zlib_ng :factory_worker: )

**Comment by LukasThyWalls** [comment] 2024-06-03 22:47
> That CPU lacks SSSE3 support which results in hard crash:
> 
> https://www.dosbox-staging.org/releases/windows/#hardware-requirements
> 
> Not sure what was done in 0.82.0-alpha to sort this out but it's definitely a hard requirement for 0.81.x due to way our zlib-ng is configured.

That can put something in the right path. I know the CPU is old, in fact this could be the second thing I found in my normal day that doesn't work with this CPU (other one is the Firefox Translations things based in the Bergamont Project). It's ok, it's what it is. Also some libraries soon or later should rise those requeriments and make impossible to work in this CPU, I'm aware of that.

If only (like @Burrito78 said) there was an error, a message or something that tell something is missing, or something doesn't work because something, and searching about that lead me to find that It doesn't fit the requeriments, I didn't even ask about all of this here and waste all people time. Is what the Firefox Translations says directly, and long long time ago when some things like Firefox needed SSE2 says just when you launched them in non SSE2 CPUs.

But It's good that happened, because I want to talk about what you understand by _Required_.

Since when the SSSE3 is required? I just searched all the (detailed) Release Notes (between 0.75.0 RC1 and 0.81.1) and the only mention about I found about SSSE3 or SIMD is in the [Windows](https://www.dosbox-staging.org/releases/windows/#hardware-requirements) and [Linux](https://www.dosbox-staging.org/releases/linux/#hardware-requirements) download pages, so I don't know if It's since the beginning or not. But what I found is [this](https://www.dosbox-staging.org/releases/release-notes/0.75.1/?h=sse#provide-windows-x64-builds):

> **Provide Windows x64 builds** _(From 0.75.1 release notes, Release date: 2020-08-19)_
> 
> Windows 64-bit builds are now provided alongside 32-bit builds. Additional performance optimizations ([WPO](https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=vs-2019)) are enabled for both builds. Linux and macOS builds have been similarly optimized using [LTO](https://en.wikipedia.org/wiki/Interprocedural_optimization) since the 0.75.0 release.
> 
> **Both Windows builds now require SSE 4.2 instruction set**, which is now on par with the Linux and macOS builds that have required SSE 4.2 support since the 0.75.0 release.
> 
> Steam Hardware survey indicates that 97.45% users have CPUs supporting SSE 4.2, so your CPU is very likely good enough 😄

Which is funny, because asking about this issue began when I was updating my old DOSBox Staging 0.78.1 with a new one because I though it was old version (almost two years old, and I updated that one before). If you see, my CPU also lacks SSE 4.2, so DOSBox Staging should never worked (It worked).

I admit my main DOSBox I normally use is DOSBox-X (with their fancy menus to mount easily things), but I used DOSBox Staging too for testing specific things and using it with DBGL alongside DOSBox ECE and DOSBox 0.74-3. And when I used it, I didn't find any issues whatsoever, what I know It doesn't mean It could lead to crashes in some situations because the lack of the instruction sets. It can be said that It was not official supported, but, _Required_?

Also there is other question, because whatever had introduced this "thing" is [between 0.81.0 RC1 and 0.81.0 RC2](https://github.com/dosbox-staging/dosbox-staging/compare/v0.81.0-rc1...v0.81.0-rc2), what It could be wrong call it an issue, but effectively increasing the requeriments without any messages and info It is, and more strange doing it between Release Candidates, when there should only being fixes. It was probably something more common that triggered hard-requeriments, I guess the more culprits could be these two [[1]](https://github.com/dosbox-staging/dosbox-staging/commit/777ef3cf17c00889e53c4c4a6a90eda06f60054c) [[2]](https://github.com/dosbox-staging/dosbox-staging/commit/238fe01e0eaeb54a17f7e2736b2249ff9554f418), and the second one seems to be related with the building phase, so If the alphas are build with other thing instead that's why the alpha versions still work in my computer and the main versions doesn't, what also guess if there is a way to compile it without having this issue, maybe encircling it at least at the initialisation and try to make it work like before?

And It's your project and you can do whatever you want, and are very straight forward in the [Non-Goals about DOSBox Staging](https://www.dosbox-staging.org/about/#non-goals), with more reasons when there are others maybe-not-so-updated but working DOSBox builds out there (or maybe doing my own like some of you said), but if you increase the requeriments should be a good reason and an improve to the application behind it, and also a proper warning or error when happens, or you have this kind of strange reports without anything to begin with to debug. And It was always working with my CPU when It never had the _Required_ instructions sets, without any issues that I can tell, so the reason It's not working now It's because is missing SSSE3 now of maybe something else (related or not)?

I'm not talking about I want to use DOSBox Staging in my 486 with Windows 3.11 (WTF), I will stick with the last working version that could fit my requeriments, and that's it, but i fight a little bit this because this happened to me some time ago: With ScummVM Android, early versions worked in an old tabled and suddenly they stopped to work, [so I checked to test what happens or rise the requeriments in the Apk](https://bugs.scummvm.org/ticket/13067), but they somehow saw a fix so late versions also worked until now, although I admit is weird to see that you can still install ScummVM in Android 4.1.x, but if nothing breaks that, why not?

> @LukasThyWalls zlib_ng is what requires SSSE3. We introduced it as it results in 3x faster video and PNG captures.
> 
> You can compile your own version with `Duse_zlib_ng` disabled. Old zlib will work on your aging computer 😄
> 
> We won't support 14 year old budget CPUs, yeah... 😄 But maybe zlib_ng could be instructed to do the SSSE3 checknat runtimr. We might do that if it's simple.

I understand, and I want to summarise that if you don't want to look it up because anyway a CPU like mine is old is fine (The 0.000000001% or whatever), **but**: 0.81.0 RC2 and 0.81.1 doesn't have zlib-ng2.dll and crash, 0.82.0-alpha-25182 have it and works. Maybe If a try to do a capture It crashes...

... but no.
![image0002](https://github.com/dosbox-staging/dosbox-staging/assets/1467366/5a6d07a2-e564-448f-bb5e-f2724411e0b1)

¯\_(ツ)_/¯

---

Sorry for the big text, and thanks to all people for your work and for your tips, but I want to point out all these things that look a bit weird to me but for sure I don't understand everything and in some things I'm completely wrong! But I need to share them!

Thanks!

**Comment by Burrito78** [comment] 2024-06-03 23:17
Yeah, i think that it stopped working between 0.81.0 RC1 and RC2 part isn't explained yet. Must be a difference in how it was compiled? I don't think anything about zlib_ng was changed between these builds?

**Comment by johnnovak** [comment] 2024-06-04 00:36
@LukasThyWalls 

- 0.82.x and 0.81.x use a completely new compiler and toolchain on Windows—we've made significant changes to our build system. Stop comparing these two release branches at the DLL level, it's fruitless. 
- zlib-ng was introduced in 0.81.x, and that's where the SSSE3 requirement started. See here: https://www.dosbox-staging.org/releases/release-notes/0.81.0/#supercharged-image-and-video-capturing.
- Yes, issuing a warning about SSSE3 in the logs would be ideal. But what would be even more ideal is dropping the hard SSSE3 requirement, and optionally use SSSE3 only if available. This might be a possibility with zlib-ng, we'll see.
- 0.82.x might link zlib-ng statically, that's why you don't see a DLL. We'll investigate this, it confuses us too. Moreover, 0.82.x might already do the runtime SSSE3 check thing I mentioned in my previous point.

For you, the solution is simple: please use our latest dev builds if they run fine on your machine.

**Comment by LukasThyWalls** [comment] 2024-06-04 17:20
@johnnovak First, I don't want to look disrespectful or mean in any way at my previous posts, I only found this that look weird to me in my limited knowledge and I only shared it to all of you asking for some clarity. Maybe I was a bit more passionate than normal writing that big chunk of text It's a bit difficult to explain and in the same time as my first language It's not English (I think it's pretty obviously It isn't) made me be a bit harsh when It's not my intention at all.

> * 0.82.x and 0.81.x use a completely new compiler and toolchain on Windows—we've made significant changes to our build system. Stop comparing these two release branches at the DLL level, it's fruitless.

I see, that's the plausible explanation. The reason why I was vocal about that is because, that happened to me before, one project was building the daily builds somehow differently in relation with the main versions, introducing different bugs in the process. That I know sometimes It's inevitable, but having them identified is good. I saw know the [old builds were the MSYS2 builds](https://github.com/dosbox-staging/dosbox-staging/actions/workflows/windows-msys2.yml) and the newer ones are [the MSVC builds](https://github.com/dosbox-staging/dosbox-staging/actions/workflows/windows-msvc.yml), so If 0.82.0 still does the same thing as the daily builds, that's it (whatever it does differently).
 
> * zlib-ng was introduced in 0.81.x, and that's where the SSSE3 requirement started. See here: https://www.dosbox-staging.org/releases/release-notes/0.81.0/#supercharged-image-and-video-capturing.
> 
> * Yes, issuing a warning about SSSE3 in the logs would be ideal. But what would be even more ideal is dropping the hard SSSE3 requirement, and optionally use SSSE3 only if available. This might be a possibility with zlib-ng, we'll see.

An a lack of a note about that in the Release Notes (at least in the requirements with a note at the first version with that specific requirement) it would have been good too, but I know sometimes the libraries themselves don't have that either clear, in addition with something with many fallback implementations. This topic itself is about that, I guess you didn't even think of that DOSBox Staging was even starting in a very old CPU like this one, and It was crashing right away since the beginning.

---

Like I said, meanwhile is working It's good, when It stops doing it, that's life and I know It's fully unsupported in this old computer, It's not a big deal. The point of all of this is to know why, and more or less seems to be workout.

Thanks!

**Comment by Grounded0** [comment] 2024-06-04 17:55
I actually thought about AMD CPUs before Bulldozer knowing they lack SSSE3 support and advocated for going with SSE2 for zlib-ng because it would be simpler for everyone that all x86-64 CPUs are supported. Still don't know whats happening with 0.82.0-alpha but its good that it supports older systems and we can drop that hard SSSE3 requirement when 0.82.0 ships.

**Comment by LukasThyWalls** [comment] 2024-06-04 21:03
> What software did you use for the CPUID screenshot above? Can you share the raw CPUID dump? It seems strange for Phenom II to support APX...

I don't know why is lighted up in that screenshot, I looked at it again and It's not....
![imagen](https://github.com/dosbox-staging/dosbox-staging/assets/1467366/d4c72c28-eeac-4079-be6a-cf59d3d36493)

IDK...

**Comment by MasterO2** [comment] 2024-06-04 21:29
@LukasThyWalls, if you want another program that shows all the `características` of your CPU, use https://learn.microsoft.com/en-us/sysinternals/downloads/coreinfo.  Note that `coreinfo` must be run from the command line:

* [Windows 11, 10, 8, and 7 - How to Open Command Prompt / CMD](https://www.lifewire.com/how-to-open-command-prompt-2618089)

To see which SSE extensions your CPU supports, run: `coreinfo64.exe | findstr /c:sse /i`

**Comment by johnnovak** [comment] 2024-06-04 23:11
> Still don't know whats happening with 0.82.0-alpha but its good that it supports older AMD CPUs so we could drop that hard SSSE3 requirement when 0.82.0 ships.

We understood that with the guys in the meantime. zlib-ng uses runtime CPU feature detection by default if you build it as the author intended woth CMake. But the Meson build system can't build it like that; we had to specify a target CPU feature set.

The 0.82.0 Windows builds use the author-approved build method via vcpkg and CMake, so we have the nice runtime CPU feature detection. But on Windows only; Linux and macOS still use our homegrown Meson method.

Our goals for the 0.82.0 timeframe is to get rid of Meson completely, which will give us zlib-ng with runtime CPU detection on all three platforms.

@LukasThyWalls Thanks for raising this, we've all learned something and collectively understood the issue better. In the meantime, just use our dev 0.82.0 builds, they're generally very stable.

**Comment by LukasThyWalls** [comment] 2024-06-05 10:11
> @LukasThyWalls, if you want another program that shows all the `características` of your CPU, use https://learn.microsoft.com/en-us/sysinternals/downloads/coreinfo. Note that `coreinfo` must be run from the command line:
> 
>     * [Windows 11, 10, 8, and 7 - How to Open Command Prompt / CMD](https://www.lifewire.com/how-to-open-command-prompt-2618089)
> 
> 
> To see which SSE extensions your CPU supports, run: `coreinfo64.exe | findstr /c:sse /i`
> 
> To type a | character, press `Shift` and `\`.
> 
> Additionally, `coreinfo64.exe -f` will show all `características` of your CPU and nothing else.

Thanks for the tip! It looks like vaguely familiar to me, like I used it before, and It's very detailed, although on Windows I normally stick with HWINFO or CPU-Z instead of creating a dump of text information on CLI, as opposite when I use Linux what is what I usually do with one of the tons of ways to do it there.

> @LukasThyWalls Thanks for raising this, we've all learned something and collectively understood the issue better. In the meantime, please use our dev 0.82.0 builds, they're generally very stable. Enjoy Staging 😎

Not needed, thanks to you.

I will check and inform if 0.82.0 build works in this thing when it's done.
