### ISSUE TITLE
Investigate playability issues with RS-2 (1990)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2930] opened 2023-09-16 00:41 UTC
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `RS2/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment] 2023-09-23 10:05
Horizontal scrolling shooter with AdLib sound.

Not sure why it is setup with Daum, I could not notice a practical difference, but then my testing was very limited...

You can see the game play here: https://www.youtube.com/watch?v=Hma_bMIIxSc run in DOSBox.

Asks on startup for VGA, EGA, CGA or MGA

With VGA, EGA and CGA graphics, there is tons of flickering during the intro and gameplay with all the DOSBox variants.
With MCGA you end up with a corrupted text mode instead, but this even happened when starting the game with DOSBox-X set to `machine=mcga`.
![s_001](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/804861c1-1474-446b-87ac-efe2bf3f1f09)

I could not figure out how to shoot (joystick and mouse don't seem to work), and since there are a few enemies at the start that directly home-in on you, I could only test the game for 15-20 seconds before a game-over.

There are some messages on startup of the game about a "JOYMOUSE interface card"?
![s_000](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/b47f0e93-ebf9-4b2d-b3af-95aa4fbf916b)

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=63
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=5000
[pci]
[mixer]
prebuffer=25
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\RS2
c:
@cd RS2
@cls
@call rs2
exit
```
# RS2.BAT
```dos
ASMDRV
JGAME RS2
S
```

- Start the game without `ASMDRV`, and you cannot even select the video mode (no keyboard response)
- Starting the game without `JGAME` (which prints the JOYCARD messages), seems to make no difference.

**Comment by johnnovak** [comment] 2023-09-23 11:53
> Chinese horizontal scrolling shooter with AdLib sound.

All I'm hearing is "low priority" 😄

**Comment by kcgen** [comment] 2023-09-23 23:17
The game is extremely efficient; my guess is it was probably developed on an 8086, or a slow 286 with a very low-end video card.

And the developers (unknowingly) relied on this highly latent system. My guess is it will flicker on fast real hardware as well.

If that's the case, it's probably a good candidate for some kind of latency/throughput parameters to slow things down at the video or bus level.  Games like Wing Commander, Privateer, and Syndicate might benefit too. 

In the meantime, cranking up the DOS video rate and lowering cycles prevents the game from flickering (just a curiosity):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/9228e403-314f-40c0-b726-daaad0759f24

```ini
[dosbox]
dos_rate = 110

[cpu]
cycles = 500
```

**Comment by johnnovak** [comment] 2023-09-23 23:46
> If that's the case, it's probably a good candidate for some kind of latency/throughput parameters to slow things down at the video or bus level. Games like Wing Commander, Privateer, and Syndicate might benefit too.

I was wondering the same thing if that is the root cause behind all these weird "no single good cycles setting" games. The Dungeon Keeper 1 menu screen is in the same bucket, and from memory the Lands of Lore cutscenes too.

**Comment by kcgen** [comment] 2023-09-24 22:47
That's a good list of games for anyone wanting to investigate adding some kind of I/O or video throttling.  So the game is able to make video I/O requests (or writes), but the confirmation state doesn't come back until after the frame is drawn (or after some number of 1ms ticks).

That way, the game can still be fed a high cycle count, but the I/O delay acts as sludge to slow and throttle game's ability to run through lots of video frames, just like a cheap and slow ISA video card running in a fast 486 or Pentium system.

**Comment by Grounded0** [comment] 2023-09-29 23:56
The game seems to run well with low cycle count so closing. If in dispute please reopen.

**Closed by Grounded0** 2023-09-29 23:56 UTC
Labels: game compatibility
