### ISSUE TITLE
Might and Magic Book One: Secret of the Inner Sanctum - crash on exit

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#277] opened 2020-04-07 13:00 UTC
Game itself seems to work fine, but when I press Alt+Q to quit, DOSBox crashes:
`Exit to error: Corrupt MCB chain`
Tried with different CPU settings and even with default config. 0.74-3 exits normally, without crashing.
DOSBox built from source, latest commit. Linux platform.

**Comment by dreamer** [comment] 2020-04-07 15:13
Where did Alt-Q come from? Is it your own shortcut configured via sdlmapper? Alt-F4 or closing window via click also results in a crash?

Once I'll have some time, I will try to reproduce and bisect the commit, that introduced regression.

**Comment by GranMinigun** [comment] 2020-04-07 15:21
Alt+Q is internal game's shortcut and the only way to quit it without closing DOSBox. Closing DOSBox doesn't result in crash.

**Comment by GranMinigun** [comment] 2020-04-08 08:24
Crash happens during `DOS_FreeProcessMemory()` in `src/dos/dos_memory.cpp`. Relevant check was added in 5fef716 and isn't in stable release.

**Comment by Akuma-Git** [comment] 2020-09-06 14:59
Also present in SVN rev 4358
Please post a bug on 'sourceforge' and add external tag to track this against upstream.

**Comment by kcgen** [comment] 2020-09-06 16:45
Thanks to your post on Vogons @Akuma-Git and @ripsaw8080's response:

> M&M1 has a bug with its EGA display mode where it allocates a memory block that is too small for the data written into it, thus overwriting the following MCB header, and SVN catches it when the program terminates where 0.74 does not. In real DOS you get a message like "Memory allocation error, cannot load COMMAND.COM, system halted" -- SVN just has a different way of handling the situation, but 0.74 is left in an unstable state with a corrupt MCB chain.

> Searching for BB 34 08 in the main executable finds where the game allocates the memory block for Tandy graphics. Searching for BB 78 05 finds the equivalent code for EGA graphics. The amount of data for both types of graphics is the same, so changing the EGA size to the Tandy size fixes the bug.

**Comment by kcgen** [comment] 2020-09-06 16:46
@ripsaw8080: Neo in the DOS Matrix.

**Comment by GranMinigun** [comment] 2020-09-06 17:17
Nice. Though I think that DOSBox shouldn't just crash in such situations, but that probably could be discussed in #396.
Guess it's safe to close this issue. Maybe with relevant information added to wiki.

**Comment by kcgen** [comment] 2020-09-06 17:46
> Maybe with relevant information added to wiki.

Yes, ideally a file-patcher can be created to fix this game for good!

> I think that DOSBox shouldn't just crash in such situations

If we can track a given DOS allocation and its size (which I believe creates a given MCB chain), we could then detect when a write would spill beyond the chain length and block it from corrupting the next chain's values.

Then again, if the game really needs this "over-spill" area to operate properly, then blocking it from performing these writes (to protect dosbox), would move the problem back into the causer's court and (likely) cause the game to crash instead of dosbox. :-)

This would also slow down the code, so perhaps we'd only activate it debug-mode.  But the benefit would be being able to stop exactly when this overwrite occurs, and would probably simlify the job of someone try to do what ripsaw.

**Comment by dreamer** [comment] 2020-09-06 18:54
> Nice. Though I think that DOSBox shouldn't just crash in such situations (...)

It doesn't. This error means that DOSBox detected the problem and decided to exit to prevent any real problems (such as corrupting user data or something). When closing non-zero status is returned to indicate abnormal exit.

Interesting to know that it's a game bug and not a regression :) That being said, perhaps we should make the error message more informative.

**Comment by kcgen** [comment] 2020-09-06 19:09
> DOSBox detected the problem and decided to exit to prevent any real problems (such as corrupting user data or something

The detection happens not during the overwrite event, but instead when allocating, resizing, freeing, or freeing all process memory on termination.

It check if the next chain type is an illegal value (which presumably would have been clobbered at some prior time by the DOS program):  `if (mcb_next.GetType()!=0x4d && mcb_next.GetType()!=0x5a)`

So in this case, from ripsaw's explanation, the EGA allocation would have occurred very early on (and overwrite the next allocated structs destroying their chain type(s); but that clobbered memory probably isn't released until the program quits.. at which points finally dosbox scans the types and detects the clobbering.

**Comment by kcgen** [comment] 2020-09-06 19:20
@Akuma-Git - I know this is considered solved (or atleast understood) - are you able to help write a patch for this?

In ripsaw's answer, is my assumption correct that the "size of the allocation" sits in the byte(s?) directly after the hex address patterns he's provided? in which case, we just hex-edit the binary?  Or is this more involved?

**Comment by Akuma-Git** [comment] 2020-09-07 05:21
search  BB 78 05 (578) 
replace BB 34 08 (834) to increase

You can hexedit it, there is only one occurrence but multiple versions of the game.
I found two, but there could be more. I'll whip something up :crossed_fingers:

**Comment by Akuma-Git** [comment] 2020-09-07 18:11
Patch available ^^

**Comment by kcgen** [comment] 2020-09-07 18:25
Pass my thanks onto Akuma at the vogons forums   😉

**Comment by dreamer** [comment] 2020-09-08 08:32
Please upload the patch in here so I could close the issue :). (Some people - like me - can't access Vogons forum)

**Comment by kcgen** [comment] 2020-09-08 08:44
[mm1_mcbfix.zip](https://github.com/dosbox-staging/dosbox-staging/files/5187135/mm1_mcbfix.zip)

**Comment by dreamer** [comment] 2020-09-08 08:48
@GranMinigun @Akuma-Git @kcgen Thank you! I think we have no actionable follow-up in here.

**Closed by dreamer** 2020-09-08 08:48 UTC
Labels: bug, external, game compatibility
