### ISSUE TITLE
The window gains focus on every video mode change

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3433] opened 2024-02-22 11:35 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the DOSBox Staging window is unfocused, and there is a video mode change, the window gains focus every single time in main. This is a regression compared to 0.80.1.

This is pretty annoying when you want to run DOSBox in the background while doing something else in the foreground and there are frequent screen mode changes.

First I thought auto-CRT does this because of the shader switching, but nope; it can be reproduced with the "sharp" shader as well.

Only tested on macOS so far.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Start some program that switches frequently between video modes (e.g., Pinball Illusions & Pinball Fantasies intro, Show by Majic 12, Second Reality by Future Crew (after the intro)).
2. Switch focus to a different window.
3. Every time Staging logs a screen mode change, the emulation window becomes focused.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment] 2024-02-22 17:03
Happens on Linux as well:

```
97acb3294135b6946da64b1acfe128885bfaa319 is the first bad commit
commit 97acb3294135b6946da64b1acfe128885bfaa319
Author: kcgen <kcgen@users.noreply.github.com>
Date:   Mon Apr 3 22:47:00 2023 -0700

    Set the minimum window size on window changes

 src/gui/sdlmain.cpp | 7 +++++++
 1 file changed, 7 insertions(+)
```

**Comment by weirddan455** [comment] 2024-02-22 17:26
It's just this `SDL_SetWindowMinimumSize()` function call.  It's intended to both resize the window if it's below the minimum and also prevent the user from manually resizing below the minimum.  It also always raises the window for some reason, even if it's already above the minimum.  Quick and dirty SDL repro to confirm:

```c
#include <SDL2/SDL.h>
#include <unistd.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow("Test", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 200, 300, SDL_WINDOW_RESIZABLE);
    while (1) {
        SDL_Event event;
        SDL_WaitEvent(&event);
        if (event.type == SDL_QUIT) {
            return 0;
        }
        if (event.type == SDL_KEYDOWN) {
            sleep(5);
            puts("Setting minimum");
            SDL_SetWindowMinimumSize(window, 100, 200);
        }
    }
    return 0;
}
```

**Comment by johnnovak** [comment] 2024-02-22 21:44
Nice find @weirddan455. We only want to set this once after startup then, that's the fix I think.

**Comment by weirddan455** [comment] 2024-02-23 00:20
According to a comment, some other SDL function we call in `GFX_SetSize` invalidates the window minimums so they must be set every time.  Frustratingly, this does not seem to be consistent across platforms.  On X11 (current SDL default for Linux), SDL explicitly calls `X11_XRaiseWindow` for some reason.  It doesn't even make the window active, just brings it to the front.  Some other window can still have input focus.

However, on Wayland (launch with `SDL_VIDEODRIVER=wayland`), the window does not get raised at all.  Haven't tested in Windows but maybe something different.

**Comment by johnnovak** [comment] 2024-02-23 00:56
Well, I've commented out all three `SDL_SetWindowMinimumSize` invocations in `sdlmain.cpp`, and I'm still getting this behaviour on mode changes. Tested with `glshader = sharp` and `output = texture` as well, it's the same (on macOS).

**Comment by weirddan455** [comment] 2024-02-23 01:03
> Well, I've commented out all three `SDL_SetWindowMinimumSize` invocations in `sdlmain.cpp`, and I'm still getting this behaviour on mode changes. Tested with `glshader = sharp` and `output = texture` as well, it's the same (on macOS).

Same here on X11.  Probably some other SDL function call got added that also raises the window :roll_eyes:

**Comment by weirddan455** [comment] 2024-02-23 01:09
Oh, it's the a `SDL_RaiseWindow` call I added on line 1443.  It was supposed to fix a bug where the initial window was not raised on Windows when Dosbox gets restarted by hotkey.

Can you try commenting just that one line out on Mac?  `SDL_SetWindowMinimumSize` raising the window may be a quirk of X11.

**Comment by weirddan455** [comment] 2024-02-23 01:45
Cool, I just booted into Windows to test.  ` SDL_SetWindowMinimumSize` does not raise the window on Windows.  The `SDL_RaiseWindow` call just needs to be moved further up in that function so it only happens when a new window is created.  I'm about to push a PR.

As for X11, that's an SDL bug as far as I'm concerned.  That's some nonsense behavior that it raises the window.  I may raise a PR with them to not do that since it doesn't seem to happen on any other platform.

**Comment by johnnovak** [comment] 2024-02-23 01:55
> Cool, I just booted into Windows to test. ` SDL_SetWindowMinimumSize` does not raise the window on Windows. The `SDL_RaiseWindow` call just needs to be moved further up in that function so it only happens when a new window is created. I'm about to push a PR.
> 
> As for X11, that's an SDL bug as far as I'm concerned. That's some nonsense behavior that it raises the window. I may raise a PR with them to not do that since it doesn't seem to happen on any other platform.

Sounds like a plan, cheers.

**Comment by weirddan455** [comment] 2024-02-23 03:05
https://github.com/libsdl-org/SDL/issues/9117

https://github.com/libsdl-org/SDL/pull/9118

Confirmed this patch to SDL fixes the problem with X11.

**Comment by weirddan455** [comment] 2024-02-23 21:26
SDL has merged a fix in their SDL2 branch.  SDL3 had already corrected this behavior.  I suppose this can be closed as there's nothing else to do on our end.  Whenever 2.32 releases, it should have the fix.

**Closed by weirddan455** 2024-02-23 21:26 UTC
Labels: SDL, regression, video
