### ISSUE TITLE
Discworld 1 - installing from disc but there is no sound

### ISSUE THREAD

**Issue by Max833** [dosbox-staging/dosbox-staging#1848] opened 2022-08-13 00:01 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i73770k, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This bug is pretty old and the regular DOSBox has this problem as well. Basically, it's impossible to install the game with functionally sound with the cd image, because it skips "the copy to hard drive" part (and maybe more?). It's hard to explain, because of that I have made videos.

I have mounted my cd image with PCem and the install process is working perfectly:

https://user-images.githubusercontent.com/53529402/184457883-6da70338-ee16-45cb-9550-8222c34f9267.mp4

If I do the same with DOSBox-staging, though...:

https://user-images.githubusercontent.com/53529402/184457967-360a1135-c62e-46d5-9346-ed2e4139de4a.mp4

More sources: 
https://www.vogons.org/viewtopic.php?t=13629
https://www.vogons.org/viewtopic.php?t=14804
https://www.vogons.org/viewtopic.php?f=33&t=14790

![image](https://user-images.githubusercontent.com/53529402/184457729-ff2e0cb5-0430-4a5b-a0cb-d488402dc98e.png)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Max833** [comment] 2022-08-13 00:27
Yeah.., the reason for that should be the **xcopy** command...

https://www.vogons.org/viewtopic.php?t=14804

**Comment by Grounded0** [comment] 2022-08-13 07:34
Connected discussion are here:
https://github.com/dosbox-staging/dosbox-staging/issues/1296

**Comment by Grounded0** [comment] 2022-08-13 08:09
Connected discussion is here:
- #1296

Closed as duplicate of #1296.

**Closed by Grounded0** 2022-08-13 08:09 UTC
Labels: bug

**Comment by Grounded0** [comment] 2022-08-22 08:16
Changed closed type to completed.

**Comment by KainXVIII** [comment] 2026-07-13 22:00
Bundled Freedos (?) XCOPY doesn't work with Discworld 1 installation program by the way (probably because its use different commands).
