### ISSUE TITLE
Bard's Tale Construction Set, The (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3055] opened 2023-10-25 06:45 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In exodos we currently use ECE r4230. Using the Tandy choice (option 2) given to the user in exodos during start ECE works fine. If switched to Staging there is no sound using the Tandy choice.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game and choose Tandy sound option
2.
3.

### Download URL of affected game or software

exodos

### Your configuration

Default Staging config with tandy=on

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-10-26 08:09
Applied the v1.3 patch - https://bardstaleonline.com/btcs/downloads

Setup with VGA + Tandy (PSG) + Disney LPT DAC

![2023-10-26_01-01](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/25235f12-9171-4792-98a2-d94c083f9ca8)

This actually plays using the Tandy 3-voice, instead of DAC-like scratchy music. The Disney is smoother on the ears for the DAC effects (otherwise there are some clicks and pops at the start of each effect):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/6d4c56d8-564b-487a-9471-b3c1b145707b

This is also using the new fadeout mixer feature, because the game (usually) terminates its music with a 0xDF write instead of a 0xFF write to the Tandy PSG, leaving one of the channels stuck playing a tone.

```ini
[dosbox]
machine = svga_s3

[cpu]
cycles = 3000

[sblaster]
sbtype = none

[gus]
gus = off

[mixer]
chorus = on

[speaker]
lpt_dac = disney
lpt_dac_filter = on

tandy = on
tandy_fadeout = on
tandy_filter = on

pcspeaker = impulse

[ipx]
ipx = off

[ethernet]
ne2000 = off

[autoexec]
@mount c .
mount a install -t floppy
mixer tandy 33
c:
```

**Comment by johnnovak** [comment] 2023-10-26 22:54
> This is also using the new fadeout mixer feature, because the game (usually) terminates its music with a 0xDF write instead of a 0xFF write to the Tandy PSG, leaving one of the channels stuck playing a tone.

As I mentioned in your fadeout PR @kcgen, we need to confirm first that this is not a Tandy emulation bug. Maybe the good people of Vogons could help? There are many people who are happy owners of the new Tandy 3 Voice ISA soundcards over there.

**Comment by Burrito78** [comment] 2023-10-28 08:27
@Python-Exoproject Is this a working solution for you?

**Comment by Python-Exoproject** [comment] 2023-10-28 13:53
Yes, confirmed

**Comment by kcgen** [comment] 2023-10-28 15:02
Currently Staging will produce this:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/f17e374e-b2df-44fb-8696-acce424c864f

> As I mentioned in your fadeout PR @kcgen, we need to confirm first that this is not a Tandy emulation bug.

The desire and need for a _configurable fadeout after last port-write_ feature is independent of this issue.

... Even if the author of Bard's Tale Construction Set said _"Yes, this is exactly how it should work; we deliberately leave the card playing the trailing tone to set the mood!"_ ... I would still want a _configurable fadeout after last port-write_ feature.

- Can the game be patched to close out the PSG properly? That would be great!

- Can the emulation be improved? I'm doubtful; the Tandy PSG is a very simple device and I believe it's perfectly emulated now. ... but, if there are futher improvements to the circuitry /outside/ the chip, that would be great, too.

But those very welcome pursuits don't change the desire for a fadeout-after-last-port-write feature, specifically made available to fixed-waveform cards like OPL and Tandy's PSG.

Because no matter what, I don't want to hear any multi-second blasts from some of these old janky games, even if it was intended: I don't care if the game devs wanted it that way :-)  

And yes.. this happens to be a serviceable mitigation for this issue here.

> Maybe the good people of Vogons could help?

That's a good suggestion. Although I'm reluctant to post anything on vogons that has an indirect benefit to Staging, because I agreed to QBix's request never to post anything related to Staging on vogons with the consequence being that I would be "handled" like @dreamer was: with a (regional? country-wide?)'s IP block.

> There are many people who are happy owners of the new Tandy 3 Voice ISA soundcards over there.

:+1: , if any of them want to try the settings here: https://user-images.githubusercontent.com/1557255/278257887-25235f12-9171-4792-98a2-d94c083f9ca8.png , this will force the use of the PSG.

**Comment by Burrito78** [comment] 2023-10-28 17:10
Yeah, well, that prolonged tone sure isn't intended. :)

**Comment by Grounded0** [comment] 2023-10-28 20:22
Looks like we gonna need that fadeout PR. 😁

**Comment by johnnovak** [comment] 2023-10-28 22:21
At the very minimum you wanna makes this _opt-in_ @kcgen if you're determined to do this. So only enable it for problematic games. Otherwise you can screw up games that feature "valid" long held notes.

**Comment by Grounded0** [comment] 2023-10-28 22:40
Hate to segue into OPL3 but i definitely want to hear California Games II on a real Yamaha YMF262 chip and if it doesn't happen there then maybe The Bard's Tale Construction Set (1991) also triggers a hanging note bug in the TI SN76489 (Tandy PSG).

**Comment by johnnovak** [comment] 2023-10-28 22:53
Yeah I'm with @Grounded0 and I have a feeling we have jumped from the problem detection to the solution/workaround phase, skipping most of the research phase (behaviour on real HW and in PCem and other DOSBoxes). Your explanations and reasoning for the stuck note is sound @kcgen (pun intended), but we don't know what we don't know.

**Comment by Grounded0** [comment] 2023-10-28 22:56
TI SN76489 datasheet:

https://map.grauw.nl/resources/sound/texas_instruments_sn76489an.pdf

**Comment by kcgen** [comment] 2023-10-28 22:59
Working on trying to figure out how to setup 86Box or PCem, because it's worth characterizing this bug better - regardless how it's addressed.

I also wouldn't close this ticket, even with fadeout-after-last-write, just because that's a work around.

A patch / fixed driver / or emu-bug-fix is the more direct fix.


(But just in general, for fixed-tone synths, a fade-after-last-write is a desirable insurance policy against any "phone off the hook" game bug)

**Comment by kcgen** [comment] 2023-10-28 23:06
> I don't think anyone cares anymore 😄 I post about Staging regularly there.

I was given the two-for-one package deal, along w/ @dreamer :laughing:

**Comment by johnnovak** [comment] 2023-10-28 23:52
> (But just in general, a fade-after-last-write is a desirable insurance policy against any "phone off the hook" game bugs that use fixed-tone synths. As a kid, I had plenty of Adlib/SB games hang and play an endless tone.. and yeah: I had to power down the machine to stop the audio)

Just curious, in-game, or after exiting the game or after a crash? Haven't experienced such things on the GUS normally (on when something craashed and I had to reboot anyway).

**Comment by kcgen** [comment] 2023-10-28 23:59
It happened in-game w/ an SB2. When the game(s) crashed, the last fixed tone was left playing continuously. 

I didn't own a GUS, but at least we know it plays sequences of PCM samples from DMA'd chunks of memory, and it'll end/stop once the requested block is done playing (unless the block is set to loop), all async from the DOS side. So the crash scenario (if the DOS side goes out to lunch) probably isn't a dramatic.

**Comment by Grounded0** [comment] 2023-10-29 00:05
Definitely had hanging notes on OPL music on my Sound Blaster 32 if a game crashed and threw me back to `COMMAND.COM`.

**Comment by johnnovak** [comment] 2023-10-29 00:34
To be clear, I don't think we should do _anything_ for the game crashing hanging note scenarios. You can reset the OPL device manually if the game crashed to the DOS prompt.

But yeah, the in-game hanging note issue (if the game is still running fine otherwise), is a different kettle of fish 😄

**Comment by kcgen** [comment] 2023-10-29 02:28
The fish are still in the Bard's kettle :-)

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/bb4963c1-0ba0-444a-a694-8a6924190f2f

**Comment by johnnovak** [comment] 2023-10-29 02:35
> The fish are stinking up the Bard's kettle :-)
> 2023-10-28_19-23-23-encoded.mp4
> 
> Using:
> 
>     * the latest 86Box (Linux-x86_64-b5111) and corresponding ROMs
> 
>     * HW Configuration: 386 DX, 16 MHz, "TNDY" Audio Card, Disney LPT DAC
> 
>     * Original DOS 6.22

That's some compelling evidence, yeah 😄 The long-held note during boot is strange, probably an emulation bug (but not our problem).

**Comment by kcgen** [comment] 2023-10-29 03:17
It's intermittent, similar to in DOSBox (I also tried X and Daum).

86Box has their own implementations of the Tandy's PSG (TI SN74689 PSG and NCR8496 PSG), neither from MAME or DOSBox:

https://github.com/86Box/86Box/blob/master/src/sound/snd_sn76489.c

**Comment by johnnovak** [comment] 2023-10-29 03:51
> It's intermittent, similar to in DOSBox (I also tried X and Daum).
> 
> 86Box has their own implementations of the Tandy's PSG (TI SN74689 PSG and NCR8496 PSG), neither from MAME or DOSBox:
> 
> https://github.com/86Box/86Box/blob/master/src/sound/snd_sn76489.c

Probably a badly coded game then.

**Comment by kcgen** [comment] 2023-11-11 00:34
@Python-Exoproject,

I think we can wrap this up - the game's 'Tandy-only' option plays out of the Tandy's PC speaker, which is where `pcspeaker = impulse` comes into play. It sounds very rough, but matches recordings on YouTube (even on hardware).

The synth devices all sound great (Tandy 3-voice, OPL, and MT-32) and game's effects sound the best through the Disney DAC, so I added a couple options:

![2023-11-10_13-12](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/2a07232f-cb9f-4279-94c1-717796afb9ef)

The green are all recommended, where as the yellow have terrible pops in the sfx, so aren't really recommended.

Here's a pack with these options added to `run.bat`; should work great with your currrent Staging 1918 build (or newer):

[ :file_folder:  **`Bard's Tale Construction Set, The (1991)-MoreSettings.zip`**](https://github.com/dosbox-staging/dosbox-staging/files/13323215/Bard.s.Tale.Construction.Set.The.1991.-MoreSettings.zip)

**Comment by Python-Exoproject** [comment] 2023-11-14 05:46
Thanks @kcgen. I thought this was already closed as far as exodos was concerned back when you posted those new settings and I confirmed they worked. Appreciate the assist though with the new options, ill get this in my to do queue

**Closed** 2023-11-14 06:18 UTC
Labels: bug

**Comment by kcgen** [comment] 2023-11-14 06:23
Gladly, @Python-Exoproject !
