### ISSUE TITLE
Colour discrepancy between Staging and native display/other versions of DOSBox

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#2747] opened 2023-08-10 00:33 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Recently I noticed that DOSBox displays games with a slightly greenish tint compared to how they would be displayed in a native environment. In the example below, I've done a comparison of _The Ultimate Doom_ running in Chocolate Doom (left) and the latest version of staging (right). 
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/884d3fbf-5493-4d38-aeb8-f2f4e85507b7)

To be clear, this is not exclusive to Doom either, I also noticed this when playing Rise of the Triad. 

I discovered this issue here: https://www.doomworld.com/forum/topic/138953-why-do-people-use-dosbox-instead-of-chocolate-doom/

### Steps to reproduce the behaviour.

Explain how to reproduce
(like my example above)
1. Run Ultimate Doom in both Staging and Chocolate Doom
2. Compare the colors

### Your configuration

```ini
https://gist.github.com/OpenRift412/712cce0c52a2908d06ca0fc00f85f4cd
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-08-10 22:08
Yes I can see the green tint even on my phone. Although I would not treat any DOOM source port as the "definitive" source of truth...

We're not doing any colour transforms on our side, we're just passing through unaltered RGB values, except for the `vgaonly` mode. In the latest stable release in `machine=vgaonly` mode 18-bit VGA colours are truncated to 16-bit. But in our latest dev version that's fixed. It was a long-standing issue of original DOSBox, see here: https://github.com/dosbox-staging/dosbox-staging/issues/2282

So we have a couple of options:

- You are using `vgaonly` and it's an artifact of the 16-bit truncation.
- You are using some high-gamut display or some weird colour profile and the issue is introduced by SDL and/or Windows.
- The game is supposed to look like this in DOS.

Will investigate later, it's a weird one.

**Comment by johnnovak** [comment] 2023-08-11 06:01
You have a good eye @OpenRift412! 🕵🏻 It's indeed a Staging specific issue, I can reproduce it in our latest v0.80.1 stable release. The good news is that it's already fixed in our dev build, so no action is needed! 🎉 

We use a lookup table to convert from 18-bit to 24-bit RGB (standard VGA only supports 18-bit RGB), and I've recently changed the lookup calculation to a different method (but I wasn't aware I'm fixing anything; I thought I'm just replacing it with an identical alternate implementation 😅). So yeah, I'm 99% sure it was that.

---

Comparison using Video Test Bench (freeware): [VTBFR45.zip](https://github.com/dosbox-staging/dosbox-staging/files/12318887/VTBFR45.zip)

I used the following test image:

- **1** – Color Bar Menu
- **9** – 64 Step Gray Scale

If you check the grey values with a colour picker, you'll find on the 0.80.1 screenshot basically all of them are off a bit, and every second gradation step has a greenish tint:

<img width="274" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/acd968d1-b94f-4cdb-8285-87eb2a815cf2">

In our current dev build, though, the results are perfect — the greys are perfecty greys across the full range. So that settles it.


## v0.80.1

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/14520680-58ea-422a-a7c1-025a20669605)

## v0.81.0-alpha (current dev build)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/98f942bb-ee76-44f3-ab05-ff62e19185b0)

**Closed** 2023-08-11 06:04 UTC
Labels: bug, video

**Comment by johnnovak** [comment] 2023-08-11 23:03
Oh, and if you could confirm @OpenRift412 that the colours are fine in the latest dev build that would be great (downloadable from here https://dosbox-staging.github.io/downloads/development-builds/), but then I'm 99.999% sure it's fine now anyway 😄

**Comment by OpenRift412** [comment] 2023-08-12 01:04
> Oh, and if you could confirm @OpenRift412 that the colours are fine in the latest dev build that would be great (downloadable from here https://dosbox-staging.github.io/downloads/development-builds/), but then I'm 99.999% sure it's fine now anyway 😄

![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/c03a3980-ad2d-4c0b-8d3b-05c1a5a018c3)

Looks fixed to me! Thanks!

**Comment by johnnovak** [comment] 2023-08-12 01:08
> > Oh, and if you could confirm @OpenRift412 that the colours are fine in the latest dev build that would be great (downloadable from here https://dosbox-staging.github.io/downloads/development-builds/), but then I'm 99.999% sure it's fine now anyway 😄
> 
> ![image](https://user-images.githubusercontent.com/29780788/260178612-c03a3980-ad2d-4c0b-8d3b-05c1a5a018c3.png)
> 
> Looks fixed to me! Thanks!

Thanks for confirming! One more thing to add to our regression test schedule: check those greyscale test patterns 😅

**Comment by kcgen** [comment] 2023-08-12 01:49
Yup, with the old 16-bit DAC, green is given the extra bit:

5 bits for red, (or 32 gradient steps)
6 bits for green (or 64 gradient steps)
5 bits for blue (or 32 gradient steps)
---
5 + 6 + 5 adds up to 16 bits.

So at most, we could only show 32 perfectly balanced gray colours.  If we had a 64 step grayscale, green could increment for each band, where as the blue and red would only increment every second color.

green always gets the extra bit because our eyes are most sensitive in the green bands (probably most animals as well, surely evolutionary as vegetation is green, and more gain in dark helps survival). https://www.nde-ed.org/NDETechniques/PenetrantTest/Introduction/lightresponse.xhtml

**Comment by johnnovak** [comment] 2023-08-12 03:24
> Yup, with the old 16-bit DAC, green is given the extra bit:
> 
>     * 5 bits for red, (or 32 gradient steps)
> 
>     * 6 bits for green (or 64 gradient steps)
> 
>     * 5 bits for blue (or 32 gradient steps)
> 
> 
> 5 + 6 + 5 adds up to 16 bits.
> 
> So at most, we could only show 32 perfectly balanced gray colours. If we had a 64 step grayscale, green could increment for each band, where as the blue and red would only increment every second gray band.
> 
> green always gets the extra bit because our eyes are most sensitive in the green bands (probably most animals as well, surely evolutionary as vegetation is green, and more gain in dark helps survival). https://www.nde-ed.org/NDETechniques/PenetrantTest/Introduction/lightresponse.xhtml

That's fine, but what isn't clear is how this problem manifests in the `svga_s3` mode too in 0.80.1. AFAIK we only had the 18-bit to 16-bit truncation problem with the `vgaonly` mode, so in the case of `svga_s3`, this was a regression compared to legacy DOSBox.

In any case, moot point now as VGA now supports 18-bit colour depth properly. But I'll check things with grayscale gradients for all VGA/VESA modes later, just to be sure.

**Comment by kcgen** [comment] 2023-08-12 04:54
Ahh sorry; didn't catch that nuance - then a regression it once way, indeed.

**Comment by Un1versalG** [comment] 2024-05-17 22:59
Not sure if this could help you. I was having an issue with my 4D stunts game showing orange instead of grey in many spots (dashboard, outlines, shading, etc..) Turns out the CHGCOLOR setting was the culprit. I put a hashtag in front of it and the colour looks like the original.

**Comment by johnnovak** [comment] 2024-05-18 01:01
> Not sure if this could help you. I was having an issue with my 4D stunts game showing orange instead of grey in many spots (dashboard, outlines, shading, etc..) Turns out the CHGCOLOR setting was the culprit. I put a hashtag in front of it and the colour now looks like the original.

Totally different issue, nothing to do with this ticket. The root cause of this ticket was a coding error when performing colour conversion in the emulator side—nothing to do with DOS programs.
