### ISSUE TITLE
timed=true messes up conventional memory

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3411] opened 2024-02-17 09:51 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel i3 9100, 32GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

entering the command timed=true uses 35840 (!) KB of conventional memory, leaving 0 KB free.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run DOSBox-Staging 0.81
2. timed true
3. mem

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by PoulpSquad** [comment] 2024-02-17 09:52
timed false behaves in the same fashion by the way.

**Comment by weirddan455** [comment] 2024-02-17 20:21
I can't reproduce this.

![mem](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/940cd08a-5590-4b0a-8624-1c05f8c42d4c)

**Comment by PoulpSquad** [comment] 2024-02-17 22:07
Thank you for looking into it weirddan455.

![image0003](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/ba366d89-19f1-45d7-aead-1f0f01a97723)

Thinking it might be a bug in MEM.EXE 1.12 from FreeDos, I went to MSD.EXE (3.01) to check conventional memory, but it doesn't respond to any inputs, mouse nor keyboard.

CheckIt Pro is left hanging on a black screen with a blinking cursor.

DOS Colonization hangs at startup when it tries to run OPENING.EXE -g %1 %2 %3 %4 %5 %6 %7 %8 %9.

**Comment by weirddan455** [comment] 2024-02-18 00:32
Thanks @PoulpSquad it is reproducible with FreeDOS's MEM.EXE.  I found a bug in the init code when the joystick section gets changed at runtime and I'm working on a fix.

**Comment by PoulpSquad** [comment] 2024-02-18 00:34
Thank you for your help.

By the way, this release of Staging is amazing!

**Comment by johnnovak** [comment] 2024-02-18 00:36
> Thank you for your help.
> 
> By the way, this release of Staging is amazing!

Glad to hear that @PoulpSquad. Out of curiosity, what are the top 3 new features that make it amazing for you?

**Comment by PoulpSquad** [comment] 2024-02-18 00:50
1) Integer scaling
2) Auto-CRT shader
3) No a specific feature, but more lots of small (and not so small) changes all over the place. They make Staging more user-friendly (for instances, changes to MIXER and the way MT-32 ROMs are handled).

Extra bonus points for DIR command being interruptible. Having hundreds of folders and not being able to stop a DIR made me unreasonably angry every time!

**Comment by johnnovak** [comment] 2024-02-18 01:07
Cheers @PoulpSquad. My fingerprints are all over those top three items, haha 😎 I'm glad you appreciate those usability enhancements. 

We spent a lot of thoughts on the MIXER and MT-32 improvements, and I'm glad to see there are people out there who notice and appreciate these usability enhancements 👍🏻

Personally, enhancing usability and the general user experience is my number 1 item, so expect this trend to continue. We have many great features, but if they're hard to use, it's almost as if they don't even exist.

**Comment by weirddan455** [comment] 2024-02-18 02:42
Don't close this yet.  I'm still working on it.  I've found the cause of the bug.  I'm just doing a bit of refactoring to make sure this kind of thing doesn't happen again.  One small step in cleaning up the init mess that has been the source of many bugs.

**Comment by PoulpSquad** [comment] 2024-02-18 02:44
Sorry, my bad. I'll leave this open then.

Thank you again for fixing this issue!

**Closed** 2024-02-19 18:46 UTC
Labels: bug
