### ISSUE TITLE
Mouse input spins when raw input is disabled

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#2646] opened 2023-06-25 19:30 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Other

### If Other OS, please describe

These are accounts from other people.

### Relevant hardware info

Varies

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

According to multiple people I've troubleshooted with, games with mouse input seem to have issues where there's a lot of false input when raw input is not enabled. Thing is, I don't think I've experienced the issue for myself, so this is all based on what other people have told me.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set mouse_raw_input to false in config
2. Run game with mouse input
3. Check results

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment] 2023-06-25 21:44
Any particular game having this problem? Is it related to some particular OS?

You realize, that "some people told me it is not working properly with some games on some hardware, but I don't know how to reproduce it" bug report has very slim chance to be resolved?

**Comment by johnnovak** [comment] 2023-06-25 22:21
If you can't provide exact reproduction details @OpenRift412, we'll close this tomorrow. We can't fix "something doesn't work on some people machines on same games... or so I've heard!".

**Comment by OpenRift412** [comment] 2023-06-25 22:54
> Any particular game having this problem? Is it related to some particular OS?
> 
> You realize, that "some people told me it is not working properly with some games on some hardware, but I don't know how to reproduce it" bug report has very slim chance to be resolved?

This can happen with just about any game with mouse control as far as I've been told. I know the people complaining about this problem are not gonna go to Github and make post the issue, so I thought I might as well. 

Me and my friends typically play games through [Classic Gaming Arena](https://www.classicgamingarena.com/), which uses the latest version of Staging. That's where most reports I've heard of this issue are coming from. I'll also let the dev of CGA know about it as well, see if he can just have raw input forced by default as a duct tape solution.

**Comment by johnnovak** [comment] 2023-06-25 23:01
Yes, so we have no idea how they are packaging Staging into their installers, maybe they even recompile it, who knows... Please bring it up with them. What I can say I haven't experienced any such issues on macOS and Windows, and I'm not aware of anyone else in the team either having a "spinning mouse" issue.

**Comment by Grounded0** [comment] 2023-06-25 23:19
Easy way to find out if its DOSBox or DOSBox Staging is by typing VER on the command line.

**Comment by ThomasEricB** [comment] 2023-06-25 23:35
Can confirm. I am having, perhaps the same issue, on the Steam Deck.

**Comment by ThomasEricB** [comment] 2023-06-25 23:56
Here is a video of this happening on my end:

https://www.youtube.com/watch?v=QsABxGWb0v0

As you can see, the mouse does spin horizontally through all options without any input, making the menu in The Need for Speed very hard to navegate.

**Comment by johnnovak** [comment] 2023-06-26 01:22
> Here is a video of this happening on my end:
> 
> https://www.youtube.com/watch?v=QsABxGWb0v0
> 
> As you can see, the mouse does spin horizontally through all options without any input, making the menu in The Need for Speed very hard to navigate. It keeps switching between all the options in light speed.

Config?

**Comment by Burrito78** [comment] 2023-06-26 10:54
Can't reproduce this with NFS:SE (eXoDOS) using mouse_raw_input=false.
Closing this ticket now, it sets a really bad example on how to report a bug properly. 

Please include proper infos, logs and repro pack next time.

**Closed by Burrito78** 2023-06-26 10:54 UTC
Labels: bug

**Comment by johnnovak** [comment] 2023-06-26 23:37
> @ThomasEricB Are you sure this is related to mouse, not to the joystick? Does it reproduce with
> 
> ```ini
> [joystick]
> joysticktype = disabled
> ```
> 
> ? I remember some time ago I have disabled the joystick due to crappy gamepad introducing such problems.

We wouldn't know because fail to raise proper tickets...
