### ISSUE TITLE
Muting Roland CM-32L in Spellcasting 301 results in lost SysEx state

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3087] opened 2023-11-03 22:50 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Intel)

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Screenshot of the game section impacted:

<img width="1392" alt="Screenshot 2023-11-04 at 0 11 29" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/29784cdc-68a5-46d7-861f-48d5259a9c2f">

Normal run:

https://github.com/dosbox-staging/dosbox-staging/assets/48192273/89544f06-ee6e-414e-a221-9ec8b768aaf2

With mute and unmute event at 0:01:

https://github.com/dosbox-staging/dosbox-staging/assets/48192273/5922d4b8-5f4a-4bc1-8947-2d02926f81db

Here's a brief explanation what's happening here:

https://github.com/sfryers/MT32Editor

Song seems to play fine when its replayed by the game engine. Maybe that results in SysEx state being restored?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Proceed around 10 moves in the game into your dorm room
2. Mute the audio with DOSBox Staging hotkey
3. Unmute the audio
4. Observe Roland CM-32L having lost its SysEx state

### Your configuration

```ini
[midi]

mididevice = fluidsynth (i do a MIDI flip to MT-32/CM-32L in the batch file)
midiconfig =
mpu401     = intelligent

[mt32]

model       = cm32l
romdir      =
mt32_filter = off
```

### Provide a Log

```text
2023-11-04 00:29:46.849 | MOUNT: Path '~/Misc/dosbox/c_drive' found
2023-11-04 00:29:46.883 | MOUNT: Path '~/Misc/images/iso/dosbox' found
2023-11-04 00:29:58.394 | FSYNTH: Shutting down
2023-11-04 00:29:58.432 | MT32: Initialized CM-32L/LAPC-I Control v1.02 from mt32-roms
2023-11-04 00:29:58.434 | MT32: Operating at 48000 Hz without resampling
2023-11-04 00:29:58.435 | MIDI: Opened device: mt32
2023-11-04 00:29:58.594 | DISPLAY: VGA 640x480 16 color (mode 12h) at 59.94 Hz VFR, scaled to 2560x1920 with 1 pixel aspect ratio
2023-11-04 00:29:58.622 | MT32: LCD-Message:  Spellcasting 301  
2023-11-04 00:29:58.809 | SB16: DSP was reset
2023-11-04 00:29:58.809 | SB16: Speaker-output has been toggled on
2023-11-04 00:30:04.525 | MT32: LCD-Message: Legend Entertainment
2023-11-04 00:30:05.230 | MT32: LCD-Message:   Spellcasting 301  
2023-11-04 00:30:05.417 | SB16: DSP was reset
2023-11-04 00:30:05.417 | SB16: Speaker-output has been toggled on
2023-11-04 00:30:15.997 | MIXER: Muted
2023-11-04 00:30:20.562 | MIXER: Unmuted
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-11-04 01:50
Took me a while to realise that the difference is the drum sounds between the drum recordings (the snare drum is much shorter and higher pitched in the correct first recording).

My view is the mute functionality for internal audio devices should simply set the master volume to zero and that's it. "Saving" CPU power by messing around with the audio devices is pointless and you can't do it correctly anyway for MIDI devices. I might have already done that for all internal audio devices, can't remember 😄 (don't have time to look into it now)

Muting/unmuting _external_ MIDI devices is a much more complicated issue, and I've introduced some code earlier this year to address that correctly. That of course needs to stay.

So the TL;DR is we should just have another float multiplier at the end of the mixer channel called `global_mute` or something that can be either `0.0f` (muted state) or `1.0f` (unmuted) state and that's it. Every other mute logic should just go away and we should always render. The "global mute" should act as the mute button of an external amplifier—your SC-55, GUS, and SoundBlaster won't stop rendering and pumping out audio just because you've flipped the mute button on your external amp 😎

**Comment by Grounded0** [comment] 2023-11-04 02:52
@johnnovak 

Amen to that. Just yank it off the line and keep the machine running.

**Comment by weirddan455** [comment] 2023-11-04 14:57
It looks like we are not doing anything special on mute at the MT32 layer.  I see some special case code for external MIDI device mute, as @johnnovak said but built-in MIDI just sets a flag and returns.

We're not just setting `volume = 0` either though.  We're calling `SDL_PauseAudioDevice` which stops SDL's audio callback.  Our internal callback that renders MT32 keeps on running but is replaced by a function `handle_mix_no_sound` which is intended to account for this.

I'll try to repo this myself and see if I can find what's going on.  I suspect there's some faulty logic in the mixer itself.

**Comment by weirddan455** [comment] 2023-11-04 15:37
@Grounded0  I found a copy of the game but it's starting me out at a beach and this random woman keeps trying to seduce me lmao.  How do I get to the dorm and how do I enable MT32 sound?  Not seeing a setup program.  The less steps from game startup until repo the better.

There's some timing code in the SDL callback that doesn't get run while the audio is paused.  I suspect that's a problem and maybe the solution is to do away with the SDL pause and simply say that pause is the same as a 0 mixer volume (with special case for external MIDI).

**Comment by Grounded0** [comment] 2023-11-04 15:50
`wait`
`look at woman`
`look at woman`
`look at woman`
`read spell book
`cast woo spell`
`jump into bed`

**Comment by weirddan455** [comment] 2023-11-04 15:59
Thanks @Grounded0 

I'm going out for a  few hours.  I'll try to take a look at this more later today.

**Comment by MasterO2** [comment] 2023-11-04 16:16
> To run with Sound Blaster + Roland MT-32/CM-32L:
> 
> ```
> S301 BLASTER 7 220 MT32 2 330
> ```
> 
> To get into your dorm room:
> 
> ```
> wait
> look at woman
> look at woman
> look at woman
> read spell book
> cast woo spell
> jump into bed
> ```

Grounded0, Dosbox-Staging's resident pick-up artist.  :D

**Comment by Grounded0** [comment] 2023-11-04 16:31
> Grounded0, Dosbox-Staging's resident pick-up artist. :D

![4875733-spellcasting-101-sorcerers-get-all-the-girls-dos-front-cover](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/b00acc26-8647-455f-88de-9167a292d48a)

**Comment by weirddan455** [comment] 2023-11-04 19:56
I'm back at my computer and got into the dorm room in game with MT32 sound.  Unfortunately, I'm so far unable to reproduce the issue.  @Grounded0 can you please share the results of `mixer /listmidi`?  The `cm32l` setting is an alias that can choose one of `cm32l_102`, `cm32l_100`, or `cm32ln_100` (preferred in that order).

I've tested with the first two and the drum sounds correct before and after muting the audio.  I can hear the difference in your provided clips but on my system it all sound like the first (correct) sample even after a mute + unmute.

Also just want to confirm you are running the lastest code off `main` (or if not, which version).

**Comment by Grounded0** [comment] 2023-11-04 21:02
2023-11-04 00:29:58.432 | MT32: Initialized CM-32L/LAPC-I Control v1.02 from mt32-roms

Running version 0.80.1.

**Comment by kcgen** [comment] 2023-11-04 21:08
Latest main [**:file_folder: `universal dmg`**](https://github.com/dosbox-staging/dosbox-staging/suites/17909589642/artifacts/1028756099)

**Comment by Grounded0** [comment] 2023-11-04 21:26
I'll try `main` if Dan can't repro on 0.80.1.

**Comment by johnnovak** [comment] 2023-11-04 22:02
> I'll try `main` after Dan tries repro on `0.80.1` as that's what we officially support.

That's true, but if this is fixed in main, the learning is that dev team members should alwats re-test with main too before raising a report. That saves cycles for everyone.

Nice pickup technique, btw, @Grounded0. Good times 😎

**Comment by Grounded0** [comment] 2023-11-04 22:23
Fixed in:

<img width="1392" alt="Screenshot 2023-11-05 at 0 21 36" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/bdf43055-6ecc-43f9-9d6e-0f5e50628039">

Hopefully `0.81.0` is released this year since 90% of our users are still on `0.80.1`.

**Closed** 2023-11-04 22:26 UTC
Labels: bug, midi

**Comment by johnnovak** [comment] 2023-11-04 22:29
> Fixed in:
> <img alt="Screenshot 2023-11-05 at 0 21 36" width="1392" src="https://user-images.githubusercontent.com/48192273/280495493-bdf43055-6ecc-43f9-9d6e-0f5e50628039.png">
> 
> Hopefully `0.81.0` is released this year since 90% of our users are still on `0.80.1`.

The plan is 0.81.0 RC will come out this Dec, then the final on the early months of 2024 after more internal testing and user feedback.

The team decided we will go with the release candidate model going forward.

**Comment by Grounded0** [comment] 2023-11-04 22:52
Technically we're already in de facto RC run with eXoDOS v6 release but if that's what have been decided its all good.

**Comment by johnnovak** [comment] 2023-11-04 23:07
> Technically we're already in de facto RC run with eXoDOS v6 release but if that's what have been decided its all good.

The situation with the release of eXoDOS v6 is a very special case because they only "enable" Staging for select games they have verified to work with the latest dev version for their needs which is a subset of a _general_ RC release.

**Comment by Grounded0** [comment] 2023-11-05 00:26
I'm happy to write bulk of the release notes myself. Maybe we a new ticket that ties together whats necessary to move forward to steer the effort.

**Comment by johnnovak** [comment] 2023-11-05 11:24
> I'm happy to write bulk of the release notes myself. Maybe we a new ticket that ties together what's necessary to move forward in steering the effort.

Thanks, there are lots of new features, so everything helps. You can view the current release draft here:
https://github.com/dosbox-staging/dosbox-staging/releases

I will write the notes for my own major features myself, so please leave those alone (adaptive CRT shaders, VGA double-scanning improvements, MIXER improvements, MIDI muting, image capture enhancements, plus maybe a few other things I can't remember).
