### ISSUE TITLE
Graphics pipeline modernization

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#2131] opened 2022-12-15 07:29 UTC
This issue is meant to outline, track, and discuss overhaul of window management and rendering pipeline.

The broad goals are to simplify window-related routines, to modernize the current rendering backends as necessary (namely, SDL renderer and OpenGL), to bring in new backends (GL Core, GL ES), and to replace the current shader system with much more advanced and flexible one based on RetroArch specification (Slang). This should improve codebase maintainability, improve performance and compatibility somewhat, hopefully modularize things enough to make bringing additional backends trivial (e.g. much requested Vulkan), and pave the road for simpler OSD implementation and perhaps even Android port.

The roadmap (subject to change) is as follows:

- [x] Teh Great Purge — removal of surface output (#433; done in #2780);
- [ ] Windowing rework;
- [ ] Rendering pipeline overhaul:
  - [ ] Resource management improvement;
  - [ ] Replacement of legacy OpenGL functionality;
  - [ ] GL Core and ES profiles implementations;
- [ ] Slang shader system implementation (#100):
  - [ ] SPIRV-Cross integration;
  - [ ] Shader chaining.

There are also some things of interest that are either not very important at the moment or have additional prerequisites:

- Vulkan backend — someday, maybe, but not before renderers overhaul is done (#565);
- Complete removal of remaining scalers — used for double-scanned modes, could do it on GPU instead, requires research;
- Platform/vendor-specific OpenGL improvements:
  - Apple extensions — not hard to do, but first things first;
  - Mesa DMA buffer — requires EGL, which will be available properly only in SDL3;
  - Windows — additional research required;
- Colour management, HDR support (#1793);
- Accelerated 3dfx Glide backend — can be externalized into separate project, akin to dgVoodoo/nGlide;
- Accelerated Rendition Speedy3D et al. — hey, anything's possible with some shader magic.
 
Treat the list as a backlog, and expect both lists to expand and shrink as the work progresses.

This post was supposed to be longer and explain some things in finer detail, but thoughts constantly flow through. So… just ask your questions. Whats, hows, whys. Even if you know the answer.

**Comment by GranMinigun** [comment] 2022-12-16 02:48
1. See assignees (I'm going to regret that...);
2. Should be mostly refactoring of window-related code. Right now some routines are spread across different paths, like viewport setup, for example. Some of that is me, some likely is very old code from SDL1 era.

**Comment by kcgen** [comment] 2022-12-16 16:33
Right on, @GranMinigun ! :rocket: 

I can imagine this will be a long running branch, repeatedly rebased against `main`. At same time, any commits that have benefits "on their own" in the `main` branch can be cherry-picked as we go. 

For example, once surface is removed, that can go into `main`, without any strings attached.

**Comment by johnnovak** [comment] 2022-12-17 03:55
> Complete removal of remaining scalers — used for double-scanned modes, requires research;

We have removed all software scalers recently, haven't we?

Yes, so for double-scanned modes we need a `doublescan` boolean config or something, then just resize 320x200 to 640x400 internally (and all similar modes). (Technically, you also need to double the horizontal resolution from 320 to 640 so shaders work correctly; that's how a real VGA card does it too).

I've been contemplating always double scanning low-res VGA internally (perhaps by porting the more advanced line-based renderer of DOSBox-X over), but it's a _lot_ of work and complexity for little practical benefit (unless you want to be able to run demos).  Because technically VGA could only do 350, 400, and 480 lines in standard resolutions—low-res modes were literally emulated!

Short version: demos sometimes change VGA registers per scanline to achieve certain effects (technically, you could change the palette at every scanline if are able to do it quickly enough — a common trick in many Amiga games and demos to display a lot more than 16 or 32 colours!), so for that you really need a renderer that does line-by-line rendering (400 actual scanlines in 200-line modes). Whereas DOSBox just renders the screen one quarter at a time, breaking such effects.

Maybe in the future when there's nothing else left to do somebody could do a proper, 100% true to the hardware VGA emulation similar to DOSBox-X. But the thing is, it's only needed for demos. Until then the simple scaler solution would work fine. And we need that, because currently by using `machine = vgaonly` although you get double-scanning, it doesn't work with SVGA and VESA games where you need to set `machine` to something else. That's a serious practical drawback for games that mix SVGA hires and 320x200 low-res screens.

------

Another thing, rendering should be decouple from the physical dimensions of the viewport (similarly to how hi-dpi on macOS works). That way you could render something at x2, x3, etc. internal resolution, then scale down to whatever viewport size you have by bilinear interpolation (this yields better results for certain CRT shaders, especially when combating moire; it's faster than integrating the upscaling into the shader code, and of course when you would need to teach every single shader how to upscale internally...)

**Comment by GranMinigun** [comment] 2022-12-17 05:46
Wasn't aware that DOSBox doesn't emulate output per-scanline. That'd indeed be a welcome change, but it's out of scope for this ticket. I was thinking of just somehow doubling lines by means of SDL renderer or OpenGL shader respectively, but didn't know about those details. It's probably better for those scalers to stay as-is for now then.

I thought of exposing some sort of `prescale` configuration setting, but didn't think about details yet. It should allow to do arbitrary (well, up to hardware 16K limit...) size framebuffer which is then rendered into backbuffer. The main purpose is for the SDL renderer to have naive oversampling, like `sharp` shader. As for shaders themselves, maybe it'll be a uniform, so you could have a shader that does just that, integer scaling. Or maybe it'll set initial framebuffer size. Additional research required on my side, but the overall idea should be clear.

**Comment by GranMinigun** [comment] 2022-12-17 06:42
Great. Looks like the purge will have to wait. Mapper is using surface output. Suggestions?

**Comment by johnnovak** [comment] 2022-12-17 06:49
> It's probably better for those scalers to stay as-is for now then.

@kcgen has already removed all the scalers in 956a54d9cd2111a2

> Looks like the purge will have to wait. Mapper is using surface output. Suggestions?

I think you can purge; you just need to write a simple abstraction layer over the drawing functions used by the mapper and redirect the drawing to the `texture` backend. It's extra work, but should be pretty trivial, and after that you can purge `surface`.

The new mapper is on the horizon, but in the distance, far away... :) Once the OSD is mostly working. So I'd say just do the above.

**Comment by GranMinigun** [comment] 2022-12-17 06:57
He left the scalers that do line doubling. They're not exposed in the configuration.

**Comment by johnnovak** [comment] 2022-12-17 07:07
> He left the scalers that do line doubling. They're not exposed in the configuration.

Right, wasn't aware of that 👍🏻

**Comment by GranMinigun** [comment] 2022-12-22 20:02
Progress report: so far the mapper was moved to SDL renderer (and, as a bonus, its window now can be freely resized just because), a bunch of `Bitu`s along the way were replaced, and surface output got mercilessly evaporated out of existence. Of course, nothing's perfect in this world: I've adopted the `goto` fallback for the time being as a quick, dirty, and obvious solution, but it trips CI in OpenGL-less configuration (can make it even more dirty with a preprocessor directive, of course...); `get_canvas_size()` also trips CI due to unused argument - SDL 2.26 introduced a very handy function, but 2.0.5 is still listed as the bare minimum, I believe?; and "the nail of the programme" - MSVC cannot into constexpr used in lambdas. 102 errors. Where's muh cake for reaching new heights?

Oh, and an actual bug I introduced - texture output now triggers assertion on toggling fullscreen mode. Happy holidays. (I'll figure this one out with time, just a warning not to cherry-pick anything yet, just in case.)

**Comment by FeralChild64** [comment] 2023-01-06 21:59
@GranMinigun I don't know if you are going to touch the relevant code - but if so, please avoid using `KEYBOARD_ClrBuffer()`.

Right now I'm trying to rewrite the keyboard controller code (the current one is, IMHO, not suitable for further patching with quick fixes), and I see this function is occasionally VERY dangerous:
- it can clear the result of a command the guest software has just sent to the keyboard controller, the keyboard itself, or (hopefully soon) the mouse
- sometimes the key press/release scancode consists of 2 or more bytes; if the guest has picked the first one from the buffer, and we are clearing the buffer before the second byte gets picked up, we might get funny results

Moreover, unpatched Windows 3.11 for Workgroups does not like unnecessary keyboard IRQs (it can even make the keyboard stop working at guest side in such case, even some real life keyboard controllers used to trigger this problem) - so once we fired an IRQ for the scancode, there is no way to withdraw it safely.

I am trying to make this function slightly safer - but, in fact, it would be best to get rid of it completely.

**Comment by johnnovak** [comment] 2023-01-06 23:36
Some things to consider @FeralChild64 (intentionally keeping the descriptions high-level):

- Currently, taking a screenshot of the final rendered output causes slowdowns because it reads the framebuffer pixel by pixel synchronously. It would be good if the screenshot action wouldn't cause slowdowns with the new pipeline.
- Similarly, it would be good if we could created video recordings of the final rendered output (post-shader), and in an efficient manner.

**Comment by GranMinigun** [comment] 2023-01-07 11:51
> I don't know if you are going to touch the relevant code

Wanted to say "unlikely", but I see now it sits inside window event polling. Probably not a big deal though.

Screencap - yeah, I know it's slow. Ideally it should be threaded, but in general both threading and screencap are uncharted territories for me. No promises, but keeping that in mind.

Runtime shader reload - shader loading will move into its own function(s) either way, so should be trivial to implement.

Right now I'm more concerned about design/architectural questions than specific implementation details, to be honest. Should've read some smart books. Oh well.

**Comment by johnnovak** [comment] 2023-01-07 20:15
> Right now I'm more concerned about design/architectural questions than specific implementation details, to be honest. 

Happy to discuss/brainstorm ideas with you if you feel like it. Or just listen to your high-level architectural plans and offer feedback. Of course, only if you think that would help 😄

**Comment by GranMinigun** [comment] 2023-01-23 15:37
So, here's sort of a prototype of how the updated window/rendering pipeline might look. For now the focus is on general flow and especially the way resources are dealt with - the window and renderer are created once, textures and their contents are updated as necessary. DOSBox currently creates the window at least twice, for example. (While the code is compilable and functional, not all files are provided for building, as that would only be useful for benchmarking in which I'm not really interested right now.)

[proto.zip](https://github.com/dosbox-staging/dosbox-staging/files/10481065/proto.zip)

It goes pretty simple: create window, create renderer or context, create textures, set viewport, go brrr. And that's really all we need. Comments on code quality are only accepted if they're snarly enough. Also please ignore OpenGL path implementation details for now, it's not important and will change. Feedback is quite welcome otherwise.

One huge problem will be figuring out how the current pipeline flows to cleanly replace it and not break everything along the way. But once that's done, the resulting milestone should be good enough to go into the next release.

**Comment by johnnovak** [comment] 2023-01-24 02:32
Looks good so far @GranMinigun.

> One huge problem will be figuring out how the current pipeline flows to cleanly replace it and not break everything along the way.

I'd say that's the biggest remaining piece of the puzzle. I'd personally try to reimplement the functional equivalent from scratch as much as possible; I suspect there's all sorts of weird workarounds in the current code and legacy cruft accumulated over time, half of them probably no longer needed.

So this looks sane so far, but I guess the majority of the work is still ahead, and we'll just need to extensively test it for a few months when it's fully done.

**Comment by GranMinigun** [comment] 2023-01-24 05:06
> what package provides you with the Glad GL header?

Again: I'm not interested in benchmarking. Thus no point in building the binary. You will end up empty anyway, as it requires not just Glad, but also shaders and test images. The output won't differ compared to the old version of the proto that you had anyway.

> What's this paletted texture thing by the way and why do we need or want it?

It is what it sounds like: an indexed texture with a separate palette. The image is colourized during rasterization instead of being passed as 32-bit data. This noticeably helps limited bandwidth of integrated GPUs (read - lower frametimes), so I want to implement that further down the road as part of OpenGL modernization.

**Comment by kcgen** [comment] 2023-01-24 05:24
> Again: I'm not interested in benchmarking.

Neither am I; but thought it was some kind of running skeleton with some simple concepts string together just to show the flow and rough architecture. 

But yeah; doesn't need to run, and I can read through the code!

**Comment by johnnovak** [comment] 2023-01-24 05:54
> It is what it sounds like: an indexed texture with a separate palette. The image is colourized during rasterization instead of being passed as 32-bit data. This noticeably helps limited bandwidth of integrated GPUs (read - lower frametimes), so I want to implement that further down the road as part of OpenGL modernization.

That's a neat idea, and I'm not necessarily against such optimisations for really low-end hardware if it doesn't complicate things too much. Also, it needs to be measured how much this would improve things; if not much even in the best-case scenario, it might be an unnecessary complication.

Just be wary that you might run into non-trivial problems by assuming a fixed palette per frame. Some games change the palette mid-frame to output more colours possible in a given screen mode. Admittedly, there are relatively few games that do this as this wasn't that easy to do on CGA/EGA/VGA (as opposed to the Amiga, where it was common practice to change the palette as often as every few scanlines using the Blitter graphics co-processor!)

Affected games I know of:

- Lemmings
- Oh No More Lemmings
- California Games
- Pinball Fantasies
- Pinball Dreams (maybe)

And probably a lot of demos (probably out of scope for use, but still, it would be nicer not to make things worse).

More info (search for "palette"):

- https://www.vogons.org/viewtopic.php?t=57254
- http://nerdlypleasures.blogspot.com/2014/09/oddball-ega-and-vga-resolutions-when.html

**Comment by johnnovak** [comment] 2023-01-24 05:59
Another thing to look into if you really want to optimise things is that the VGA can only do 18-bit colours, the EGA up to 6-bit RGB, etc. So that would be another way to reduce the required bandwidth without having to deal with paletted images. You could even RLE compress 😎

**Comment by GranMinigun** [comment] 2023-01-24 13:42
> Some games change the palette mid-frame to output more colours

...you just had to ruin my genius plan by bringing that up, haven't you?

Anyway. Worst case we could just fall back to the current behaviour as necessary, as the games and demos that do that aren't demanding in the first place. Additional research required. I consider performance difference significant enough to consider playing with separate palette. Something around 1/3 higher framerate on my HD 630 with RAM clocked at 2400 MHz for a 1600x1200x8 test image, if I remember measurements correctly. Yes, that's an edge case, but the difference was significant enough all the way down to 640x400x8.

Let's save that discussion for later. It's deep into optimization territory anyway, we're just not there yet. The OpenGL stuff you see in the proto were my initial experiments on possible updated renderer from long time ago, even before I considered rewriting SDL-related stuff. Some things were intentionally removed for the time being.

**Comment by johnnovak** [comment] 2023-01-24 21:32
Yeah, this stuff can be implemented as an extra optimisation step at the end. To keep things simple, in the optimised path you can always transfer 8-bits per pixel, then you can can "collect" the full palette during building the frame and modify (re-index) pixel values accordingly. If you run out of 256 colours you can just revert to the unoptimised path and leave it there. But I don't think 256 colour VGA games bothered by this technique, and you probably can't do the palette change trick more than once or twice per frame. But the demos, well...

Also keep in mind that the palette can often change per frame in all VGA games (e.g. screen fades, palette cycling style animations, etc.)

**Comment by johnnovak** [comment] 2023-03-02 06:35
@GranMinigun you might have heard about this excellent new library, but posting it here anyway for reference.

https://github.com/SnowflakePowered/librashader

It's basically the RetroArch SLANG shader system reimplemented as a Rust library with C bindings.

More info here:
https://snowflakepowe.red/blog/announcing-librashader-0.1.0
https://snowflakepowe.red/blog/introducing-librashader-2023-01-14

There's a massive interest in this and it's maturing very quickly; I think it's a no-brainer for us to just adapt it instead of rolling our own. That's good news for you; you're future workload has just been cut in half at least! 😅 

Judging by the [reactions of other emulation devs](https://www.reddit.com/r/emulation/comments/10c8i8h/introducing_librashader_a_complete/), it seems everybody is naturally converging towards adapting the superior SLANG-based RA shader system. I predict this library will enjoy quick adoption rates in many (if not most) emulator projects, hence it's destined to become a rock-solid and the de facto standard shader library in the near future.

**Comment by GranMinigun** [comment] 2023-04-05 19:53
Huh. No, haven't heard about it. Seems to be pretty heavy though... We'll see.

**Comment by ThomasEricB** [comment] 2023-04-05 20:15
> Huh. No, haven't heard about it. Seems to be pretty heavy though... We'll see.

@GranMinigun We have been discussing Librashader a lot on Discord, and the fact that solves a major gap + it's cross-platform, even if it's a bit heavy, I think people here would agree in biting the bullet _**as long as it**_ works great with our code and functions as intended...

**Comment by johnnovak** [comment] 2023-04-05 22:12
> Huh. No, haven't heard about it. Seems to be pretty heavy though... We'll see.

Optimised windows DLL is 18 MB in the latest GitHub release. I'm all for keeping our releases non-bloated, but in this case, if it's a high-quality, better-than-reference implementation of the RA Slang shader pipeline, then in my view it's worth it. I'm not against adding a quality SC-55 emulation either -- if it's 30 megs, I don't care. Disk is cheap and the internet is fast 😎 

If you want to do it anyway because it's fun to do so that's another matter, of course 😄 I'm just thinking you can easily burn 6-12 months of work on this to get it right -- time that could be spent on other important things. Well, if you do it, you should consider the library approach too so other projects can benefit from it as well, plus it will be better tested in the end.

All in all, you might burn a lot of time and end up with a similarly sized library because there is a lot going on there. At least read the guy's blog posts on the subject and the project readme in detail before considering writing your own thing:

https://snowflakepowe.red/

Other emulator authors might be incorporating this library as well, and if it becomes a de-facto standard, using one common, well-tested implementation instead of rolling your own becomes a no brainer. But that's hard to tell now.

https://www.reddit.com/r/emulation/comments/10c8i8h/introducing_librashader_a_complete/

Btw, ScummVM missed the train with their recent release; they implemented the old GLSL RA pipeline that was obsolete 5 years ago... All exciting new shader dev work is Slang based.

**Comment by kcgen** [comment] 2023-04-05 22:18
The more streamlined and serialized SDL/pain/ can get, the better - especially if we can send frames out to this cross-platform, well maintained future-proof shader library. 

This task alone (streamlining sdlmain) is the big effort - and would surely get it in shape to be more adaptable if we ever need to switch/add more host rendering libraries too (ie: video encoding sink, as an example).

**Comment by GranMinigun** [comment] 2023-04-10 06:17
Trying to figure out the current flow. Just the relevant stuff, not full outline of DOSBox's life cycle.

The starting point appears to be `GUI_StartUp()`: some configuration values are being read and set, and `set_output()` is called. It reads more configuration variables (output, renderer driver, screensaver, window and viewport settings), then asks for a window via `SetDefaultWindowMode()` and tries to create GL context. Recreating window when we only want to change output type might be necessary if the current window was created without flags needed for the requested output (that is, you can reuse OpenGL window for SDL renderer, but not vice-versa).

`SetDefaultWindowMode()` just calls `SetWindowMode()`. Resources are cleaned up (including destroying renderer), window flags are set, and window is created. SDL renderer or GL context is recreated. Fullscreen shenanigans. Finally, presentation is set up, but we're not done yet.

DOSBox enters the emulation loop. `VGA_SetupDrawing()` is called - if we don't know what mode the emulated machine runs, we cannot prepare an appropriate texture. ReelMagic emulation snatches a call to `RENDER_SetSize()`, from which it calls its `VideoSetupMixer()`, and from there an actual `RENDER_SetSize()` is called. Here, the emulated display mode parameters (like resolution and refresh rate) are passed to renderer, and `RENDER_Reset()` is called, which does some scaler related stuff, asks to apply OpenGL shader, and calls `GFX_SetSize()`.

Pain.

`GFX_SetSize()` fills `sdl.draw` structure with emulated display mode (resolution, PAR, etc.), then proceeds to setting VSync and calling `SetupWindowScaled()`. That function may dispatch to `setup_window_pp()`, both are responsible for setting window size via call to `SetWindowMode()`. Problem is, the window might be (and likely is) recreated, along with renderer or context.

Back to `GFX_SetSize()`. Next step is preparing some sort of draw buffer (texture, PBO). It also seems to hint the internal "rasterizer" about used format, so the data from the emulated display memory always comes in e.g. RGBA8 format to the texture. Next, the window size gets set _again_, and desired output viewport is calculated and set. At this point, everything should be ready to draw fancy oversized rectangles like it's 20XX indie gaming.

**Comment by johnnovak** [comment] 2023-04-10 07:32
Up to you, but isn't it easier to ignore the current flow wholesale and just re-implement it all from scratch in a logical and sane manner? That's what I'm planning to do with the current mapper (if it will be me who reimplements it); I don't even care what it's doing and how currently, I just wanna nuke it and rebuild it based on sane principles...

Btw, be aware of the window decoration config setting. Ideally, we would want that to be toggleable at runtime from the OSD (it's a low priority thing though, but my point is certain actions might trigger the recreation of the window... although maybe decorations can be toggled on and off without recreating the window, I'm not sure).

**Comment by johnnovak** [comment] 2023-04-10 07:32
> At this point, everything should be ready to draw fancy oversized rectangles like it's 20XX indie gaming.

No rectangles on my screen! CRT shaders all the way! 😎

**Comment by GranMinigun** [comment] 2023-04-10 08:28
> isn't it easier to ignore the current flow wholesale

Without understanding what goes where I have no idea what to nuke, at the very least. I think some things will be stripped and/or repurposed, like `set_output()`, while others will indeed be nuked (I'm looking at you, `SetWindowMode()`). Part of the problem is certain functions are tied to emulation and communicate machine properties (`GFX_SetSize()`), and it's honestly not immediately obvious to me whether it's feasible or makes sense to do something about it, aside from extracting renderer-related parts into their own functions (which I do anyway). Also a ton of callbacks and sections and whatsnot, which makes navigation without debugger non-trivial.

Window decorations should be toggleable. If right now toggling decorations recreates the window, then it's an issue in how configuration is handled. Should be just a call to `SDL_SetWindowBordered()`. Same for other window-related configuration settings.

**Comment by johnnovak** [comment] 2023-04-10 08:57
> Without understanding what goes where I have no idea what to nuke, at the very least.

Make sense! Well, good luck man 😄

**Comment by dreamer** [comment] 2023-04-10 10:45
@GranMinigun heh, the current state is already simplified compared to what we inherited from upstream + initial state of SDL2 patch - originally it was a spaghetti of various subcases, confused functions doing multiple different things and everything decorated with ifdefs for SDL1, SDL2, Direct3D, Windows, OS/2, and MacOSX...

From rendering perspective the most important function is `GFX_StartUpdate` (see the comment I left there), followed by `GFX_EndUpdate`. As for other functions - it's messy, and it is messy for a reason - we need to accommodate window events incoming in different order on different OSes (thankfully at least we get the same type of events thanks to SDL), and other OS-specific behaviour.

**Comment by FeralChild64** [comment] 2023-04-10 10:51
Wpuld it be feasible to split out the whole OpenGL code, so that it resides in a separate file? One day we might decide to switch to Vulkan, or at least offer it as an alternative output.

**Comment by ThomasEricB** [comment] 2023-04-10 11:27
> Would it be feasible to split out the whole OpenGL code, so that it resides in a separate file? One day we might decide to switch to Vulkan, or at least offer it as an alternative output.

@FeralChild64 stole words from my mouth! That what I was about to say! I agree 100%.

**Comment by GranMinigun** [comment] 2023-04-10 12:49
No promises, but it is on my radars. Would also be useful in case I'll ultimately decide to not use glad or other loader and just load needed stuff via SDL.

**Comment by johnnovak** [comment] 2023-04-10 23:11
> As for other functions - it's messy, and it is messy for a reason - we need to accommodate window events incoming in different order on different OSes (thankfully at least we get the same type of events thanks to SDL), and other OS-specific behaviour.

Could we abstract the platform differences away? We could map all platform specific event to "Staging meta-events", then various backends would only know about the meta-events.

I would give the following design some consideration; all bullet point are separate files/classes:

- SDL main
- SDL to meta event mapper
- Vulkan backend
- OpenGL backend
- Texture backend
- other backends...

In my experience, nothing kills a project as fast and makes maintenance a nightmare as tight, rigid coupling between submodules, and parts that should really be separate having knowledge of each other. As I see it, the more we can chop off these long tenctancles making their way into every corner of the codebase, the better.

Information-sharing should be kept to the bare minimum and localised to function, class, and module level, whichever is the strictest we can get away it. Platform specific events ending up in rendering backends is a design-smell to me.

**Comment by GranMinigun** [comment] 2023-04-15 12:18
@dreamer, regarding `opengl_driver_crash_workaround()` - did you report that to SDL team? I observe the window being recreated even when software renderer is requested. Asking for an OpenGL window unconditionally feels... wrong.

**Comment by kcgen** [comment] 2023-04-15 13:38
Was isolated in a commit with explanation: e50fc3135ffe959f67537e1fdecee27010df2fb9

**Comment by johnnovak** [comment] 2023-04-15 21:45
Thinking about it more, it's unfortunate SDL does not normalise evnts across platforms, but I'm suspecting that's by design as normalising them could be quite app-specific.

Another big benefit of event normalisation I forgot to mention above would be reduced testing effort. We would only need to test the event normaliser, ideally we'd have a small test app for that. Then if the normaliser produces the correct DOSBox events, there is no need to retest all functionality over and over on all platforms; if the correct normalised events get produced on all platform, we've compartmentalised the platform specific differences into a single module, vastly reducing overall testing effort.

**Closed** 2023-10-28 22:53 UTC
Labels: enhancement, discussion, refactorization, video

**Comment by johnnovak** [comment] 2023-10-28 23:00
<img width="425" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/22e5e8a3-0dbf-4412-912e-247c756378f8">

That's it, you quit @GranMinigun ? 🤔
