### ISSUE TITLE
Isolate source of vsync lag under Linux

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#104] opened 2019-12-26 01:14 UTC
Vsync causes frame stuttering and audio-drop outs when backed by SDL2's hardware accelerated backends such as `opengl` and `opengles2`.  This is true for:
- fullscreen and windowed modes
- resolutions ranging from original (postage-stamp) to hardware-scaled 1080p
- output modes `texture(nb)` and `opengl(nb)`
- aspect correction on or off
- scaler disabled or enabled (such as `none`, `normal2x`, or `normal3x`)

The only way `vsync = true` becomes useable is to avoid hardware acceleration such as using `output = surface` or `renderer = software`.

The following steps reproduce the issue on Linux x86-64, and include a pre-configured `dosbox.conf`.  

Copy & paste:
``` bash
cd /dev/shm
wget "https://github.com/dreamer/dosbox-staging/files/4000936/Jazz.Jackrabbit.Holiday.Hare.1995.zip" \
    -q -O - | busybox unzip -
cd "Jazz Jackrabbit Holiday Hare 1995"
wget "https://github.com/dreamer/dosbox-staging/suites/377829540/artifacts/876301" \
    -q -O tmp.zip \
    && unzip -p tmp.zip | xz -dc | tar -xv --strip 1 \
    && rm tmp.zip
./dosbox jazz.exe

```

[Jazz Jackrabbit Holiday Hare 1995.zip](https://github.com/dreamer/dosbox-staging/files/4000936/Jazz.Jackrabbit.Holiday.Hare.1995.zip)

**Comment by dreamer** [comment] 2019-12-26 03:49
I can reproduce the issue on my laptop. Interestingly, I see another issue, that might be related:

I changed the configuration to:
```
vsync = false
fullresolution = desktop
…
aspect = true
```
to test how the game is supposed to behave - and in-game, `aspect = true` is lost. Loading screen before map is ok, but in-game it's disabled and game uses resolution  320x203. When game is started with `aspect=false`, the resolution is 320x199.

**Comment by krcroft** [comment] 2019-12-26 04:40
Thanks for testing on your side; rules out something wonky with my Xorg and direct-rendering configuration. 

Very interesting that aspect correction isn't performed.  Jazz Jackrabbit is unique in that it deliberately drops to a custom resolution (320x199 instead of 200) so it can run the display at 60hz instead of 70hz if it used the standard 320x200. Jazz Jackrabbit also doesn't use aspect correction.. (maybe DOSBox auto-disables aspect correct for these custom VGA modes? Or maybe this is a bug in DOSBox and the custom mode is throwing off it's aspect calculation! interesting stuff.  I need to dig more into SVN now too!)

At least vsync is good on the Windows side. 

When I read the SDL guide for moving from 1.2 to 2.0, some of the patterns (ie: blitting and the sequence of function calls) don't jive - and our code is still using the 1.2 approach (will write more details in the next day or so) so I'm hoping once we try to dropping in those "standard" 2.0 function calls, we might fix vsync too.

**Comment by dreamer** [comment] 2019-12-26 06:08
I just wrote long posts on Vogons asking for [testing](https://www.vogons.org/viewtopic.php?p=811398#p811398) and [asking NY00123](https://www.vogons.org/viewtopic.php?p=811399#p811399) about cooperation. Hopefully someone will respond… Later I'll write a post on some dosbox-related subreddits - hopefully it'll bring in more testers as well.

**Comment by krcroft** [comment] 2019-12-26 09:54
I'm quick to read your vogons posts; lots of good information to share with the community. Hopefully NY00123 has time to jump in!  
Yeah, Jazz is a neat/unique in how it's been a challenge to emulate properly:
- https://github.com/libretro/dosbox-libretro/issues/61
- https://www.vogons.org/viewtopic.php?f=33&t=37821#p336477 and 
- http://nerdlypleasures.blogspot.com/2014/09/oddball-ega-and-vga-resolutions-when.html

**Comment by dreamer** [comment] 2019-12-27 09:28
Small update: on my laptop I can't get rid of screen tearing (in any app at all) under X11 - I need to use Wayland for that, so I wanted to make sure this problem is not related to X11. It's not - I managed to start dosbox-staging as purely Wayland app this way:

    SDL_VIDEODRIVER=wayland ./src/dosbox <args>

Overall the results are: dosbox starts and games are playable, but there are many tiny (unrelated) issues.

With vsync on - there's no difference, same slowdowns as under X11 with vsync on
With vsync off - I think I saw some screen tearing, but it was much, much harder to notice than with X11. I would be useful to have some kind of DOS exec to dedicated to testing tearing, like https://www.youtube.com/watch?v=MfL_JkcEFbE

**Comment by krcroft** [comment] 2019-12-28 05:59
Whoa - SDL2 supports wayland without X11; amazing!
I ripped that video to AVI and found our master branch wasn't compatible with QuickView (throws a `codec initialization error`, but older DOSBox binaries work fine).

I eventually turned it into a testcase (on the in-progress `kc/coverage-1` branch) and bisected the regression to SVN commit 4301; you'll see a PM in vogons about it also sent to QBix and jmarsh.

But yet - that video does work great for seeing tearing!  Much easier than watching horizontal scrolling in games or cracktros (where usually only small objects or text are scrolling around).

**Comment by krcroft** [comment] 2020-01-02 06:13
Potential fix is outside SDL2 and DOSBox:

Add this block to `/etc/X11/xorg.conf.d/20-intel.conf`
``` 
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "TripleBuffer" "true"
   Option      "TearFree"     "true"
   Option      "DRI"          "false"
EndSection
```

I previously was using `TearFree` _and_ `TripleBuffer` but surprisingly those didn't take effect until I disabled DRI! With these three set, Jazz plays buttery smooth (full/window, opengl/texture, vsync on/off).

**Comment by grapeli** [comment] 2020-01-02 21:06
This configuration change doesn't make sense. Global DRI disable is unacceptable. TripleBuffer is also enabled by default.

You will achieve the same effect in this way:
dri_driver=unknown ./dosbox  (equally absurd)
or unfortunately turning vertical refresh off
vblank_mode=0 ./dosbox
https://dri.freedesktop.org/wiki/ConfigurationOptions/

More tips used for specific applications can be found in this file - /usr/share/drirc.d/00-mesa-defaults.conf.

dri_driver=unknown dosbox

**Comment by krcroft** [comment] 2020-01-02 23:17
@grapeli,
Whether it makes sense or not, the configuration eliminates the stuttering. I'm not saying it's a solution or a good one.. just that it's interesting that tweaking the intel driver alone is sufficient to result in smooth tear-free play (without any adjustment to SDL2 or DOSBox's rendering settings).

We still don't know if the problem exists in SDL2 itself or how the new DOSBox SDL2 code is configuring SDL2.  I hope the latter is true and we can entirely solve it in DOSBox.

Fully agree global settings are far worse than per-application, and I appreciate seeing your suggestions that we can control it locally (as a temporary work-around?). Another question I have is regarding DRI.. are DRI2 and 3 still enabled? From what I can see DRI1 always had issues with vsync and tearing. 

Also, does disabling DRI simply mean that SDL2 is forced to use a software (non-hardware accelerated) backend, in which cause we're simply using software rendering again which we know isn't affected but this bug?

**Comment by dreamer** [comment] 2020-02-12 08:06
With shader support merged in, we need some re-tests to see how vsync problem was affected.

**Comment by GranMinigun** [comment] 2020-02-12 09:16
Menu (and also after-play DOS screen) in HH95 is still affected. Gameplay seems to be fine though. Pixel dissolve in Catacomb 3-D doesn't slow down anymore. Moving cursor lightning fast in Master of Orion 2 still affects performance.
Superscape Benchmark, while able to output hundreds of frames, crawls down to mere 40FPS with vsync on. Frame pacing is very inconsistent. Same could be said for other apps and games though.
Makes me wonder, how exactly vsync works in our case. Could it be a problem with how DOSBox rasterizes image? (Just thinking out loud.)

**Comment by BPaden** [comment] 2020-02-19 00:40
So I've recently purchased a freesync display, and I've noticed a couple of things.

Generally, vsync works fine with variable refresh, though it doesn't hold the native refresh rate of 70hz or whatever as you'd hope. It jumps all over the place. Anyway, there is a bug where some applications cause the display to get stuck in 60hz unless I turn the monitor off and back on again. At 60hz, I get the issue described here. Were you testing on a 60hz display for both Windows and Linux, @krcroft?

The second thing I notice is that refresh actually still varies if you turn vsync off. Maybe I misunderstood, but I would expect my display to hold 144hz with vsync off. I read somewhere on the internet somewhere once that variable refresh requires vsync to be on, so it must be true. I wonder if dosbox isn't getting unredirected on gnome, now that it isn't using exclusive fullscreen. Does/should dosbox set _NET_WM_BYPASS_COMPOSITOR on x11?

**Comment by krcroft** [comment] 2020-02-19 06:03
> Menu (and also after-play DOS screen) in HH95 is still affected. Gameplay seems to be fine though.

Yes; it's as if the video mode plays a role in exasperating vsync; and HH's menu-mode feels like one of those fast demo-scene modes compared to the in-game-mode, which feels more "normal".  That's just me guessing though; I not sure how to detect or diagnose this though.

> Pixel dissolve in Catacomb 3-D ~doesn't slow down anymore~ nevermind, it is still slow; seems I've missed something while testing. Moving cursor lightning fast in Master of Orion 2 still affects performance. Crusader shows slow down in the very beginning of intro cinematic: it's fading from black per-line.

Wow; nice testing! You've found a bunch of corner cases. Is there any overlap with these that also  cause degraded behavior with SVN?  If so, perhaps some of the issue lies outside of SDL and in pure-DOSBox code.

> Superscape Benchmark, while able to output hundreds of frames, crawls down to mere 40FPS with vsync on. Frame pacing is very inconsistent. Same could be said for other apps and games though (Quake).
> Makes me wonder, how exactly vsync works in our case. Could it be a problem with how DOSBox rasterizes image? (Just thinking out loud.)

I'm not sure; but this is all great information points when someone start digging around in the code.

**Comment by krcroft** [comment] 2020-02-19 06:16
> So I've recently purchased a freesync display, and I've noticed a couple of things.

Nice; after 25 years of progress, the LCD panel world can finally match the old CRT's in refresh-rate! 

> Generally, vsync works fine with variable refresh, though it doesn't hold the native refresh rate of 70hz or whatever as you'd hope. It jumps all over the place.

Are you seeing this subjectively, or is there some driver-overlay that shows the live frame-rate? Just curious; sounds useful!

> Anyway, there is a bug where some applications cause the display to get stuck in 60hz unless I turn the monitor off and back on again.

I guess that's Windows/Driver-related (if you're closing DOSBox between programs/games), or are you running DOS games back-to-back within the same DOSBox session?

Were you testing on a 60hz display for both Windows and Linux, @krcroft?

60 Hz: yes; but only under Linux - however both x86_64 (via OpenGL) and on ARM7 (via OpenGLES). 

> The second thing I notice is that refresh actually still varies if you turn vsync off. Maybe I misunderstood, but I would expect my display to hold 144hz with vsync off. 

Is that the case in window-mode and fullscreen?  My son has a 144 Hz G-sync monitor, and some older games (when in true full-screen mode) don't behave well, and framerates collapse.  But games shown in window-mode (or borderless but windowed-mode) are always locked to the full 144 Hz rate.

> Does/should dosbox set _NET_WM_BYPASS_COMPOSITOR on x11?

It looks like SDL2 takes this into account (in SDL2) https://hg.libsdl.org/SDL/file/tip/src/video/x11/SDL_x11window.c#l597

**Comment by BPaden** [comment] 2020-02-19 08:07
> Are you seeing this subjectively, or is there some driver-overlay that shows the live frame-rate? Just curious; sounds useful!

This is a feature of the monitor. You can watch the refresh rate update live in the setting panel. It's a bit limited, since it's a single updating number instead of a graph so you can't see change over time, and it's integer only.

You can also get FPS on Linux/Mesa with the environment variable GALLIUM_HUD=fps. The numbers mostly seem to match, except the refresh rate will sometimes jump well over 70 for a second or two (running Quake), while the fps doesn't seem to. Actually, in retrospect, having the refresh rate mimic the refresh rate expected by the game for variable refresh monitors is a completely different feature from vsync, so maybe not appropriate to discuss here. :P

> I guess that's Windows/Driver-related (if you're closing DOSBox between programs/games), or are you running DOS games back-to-back within the same DOSBox session?

This is on Linux, and as you described later, only for certain games. Descent rebirth is an example, which is another application still stuck on sdl1. Dosbox-staging using sdl2 doesn't have this particular problem. I just happened to notice because I didn't realize my panel was stuck at 60hz again when I booted up Quake and ended up with crackling audio.

> Is that the case in window-mode and fullscreen? My son has a 144 Hz G-sync monitor, and some older games (when in true full-screen mode) don't behave well, and framerates collapse. But games shown in window-mode (or borderless but windowed-mode) are always locked to the full 144 Hz rate.

Looks like Quake running in dosbox-staging with vsync=false in windowed mode is running at 144hz. I may have gotten it backwards before. Gnome is set to 144hz display mode. Maybe dosbox can only have variable refresh **because** the application is unredirected, which wouldn't be the case for a window.

**Comment by GranMinigun** [comment] 2020-02-19 12:23
> Generally, vsync works fine with variable refresh, though it doesn't hold the native refresh rate of 70hz or whatever as you'd hope.

Just to clarify: it shouldn't.

If FreeSync or G-Sync is active and framerate stays in display's refresh rate range, then it will always try to keep refresh rate in sync with FPS.

If FPS goes above your maximum refresh rate, then Vsync kicks in: if it's off, then your framerate goes above your refresh rate with possible tearing; when it's on, FPS is clamped to refresh rate.

Now the interesting part: when FPS goes below minimum refresh rate, if you have a G-Sync or FreeSync display with low framerate compensation, then display starts to duplicate output frames to prevent flicker (so for 24 FPS you'll get 48 Hz, for example). But if you have FreeSync display without low framerate compensation, then it stays at its minimum refresh rate and Vsync kicks in.

> Is there any overlap with these that also cause degraded behavior with SVN?

I think I remember that Master of Magic had same problem with cursor moving as MOO2 when double buffering was on, but I need to re-check.

> But games shown in window-mode (or borderless but windowed-mode) are always locked to the full 144 Hz rate.

G-Sync should have an option for whether refresh rate should be based on compositor or current window. Don't know about FreeSync though.

**Comment by GranMinigun** [comment] 2020-04-06 11:01
So, what happened to `vsync` config setting?

**Comment by dreamer** [comment] 2020-04-06 11:18
This was new option introduced by SDL2 patch, and in testing we found additional problems during initialization (discussed in #222). Properly addressing the problem will probably mean redesign of main dosbox emulation loop, so it's a major development effort.

We'll get back to it after [0.75.0](https://github.com/dosbox-staging/dosbox-staging/projects/2) release - fixing this *properly* should open the gates for handling adaptive sync as well.

**Comment by vanfanel** [comment] 2021-04-07 17:01
What happens here is simply that you are running games that expect a ~70Hz refresh rate (all DOS 640x400 games / 320x200) on a 60Hz display. So that's expected.
Can this option come back, please? It's NOT a problem when using 70Hz modes...

**Closed** 2021-07-24 17:13 UTC
Labels: Linux, bug
