### ISSUE TITLE
PC Speaker: Space Racer (1988, Broderbund) Broken engine sounds

### ISSUE THREAD

**Issue by BPaden** [dosbox-staging/dosbox-staging#464] opened 2020-06-25 21:15 UTC
**Describe the bug**
Space Racer is an interesting game to test because of the music in the intro and the voice sample at the beginning of a race. Those actually work on dosbox-staging! :D Though it does sound a little muffled compared to PCEM. Anyway, the engine noise that plays during a race just sounds like intermittent pops and static in dosbox-staging.

**To Reproduce**
It should be immediately noticeable after a the countdown in a race. Controls for this game (as far as I have been able to figure out) are enter for accelerate, numpad for movement and space for shoot.

**Expected behaviour**
You should hear an approximation of engine noise when playing. There is also a different sound for going down a hill and gaining speed.

**Environment (please complete the following information):**
Arch, x86-64

**Version of dosbox-staging:**

v0.76.0-alpha-231-g97f75181

**Configuration parameters:**

You probably need to limit cycles for this game. I set it to fixed 500. 

**Additional context**
It's a bit of a pain to set up real dos in pcem, and even more so on early motherboards — not to mention transfering files from the host to the guest. So I went ahead and did that and recorded the audio.

**WARNING!** A loud, high-pitched tone accompanies the race countdown that is irritating to listen to with headphones. The song is loud as well in PCEM. You don't want to listen to this with max volume and headphones.

I included the beginning in case you'd like to compare the song between dosbox and pcem. The broken audio bit starts about 1:06. Compare to the engine noise in pcem starting around 1:16.

[pcem](https://drive.google.com/file/d/14JhOWt_ohhmDuiODrfP93_dtH6QYiBA9/view?usp=sharing)
[dosbox-staging](https://drive.google.com/file/d/1fNVuIb4kyO_1338rXmJo8p88YN0jkiLu/view?usp=sharing)

**Comment by kcgen** [comment] 2020-06-26 02:15
Thanks @BPaden, can you kick the tires with `kc/pc-regression-fix-3`?

I've regression tested it with all of my prior testing games, plus added Space Racer (what a cool game with some amazing PC speaker control!).

**Comment by kcgen** [comment] 2020-06-26 04:02
Regarding the volume: staging and upstream's pcspeaker use the same volume for pulse-width-modulation (PWM) volume versus the "beeper" style PIT-mode volume.   

Space Racer's nice intro music is generated in PWM mode, while the engine rumble is from the PIT mode. 

It's easy to set a higher volume in general - which is really nice for  the music, but those engine square waves become devastating on the ears.

PCEM on the other hand seems to specifically attenuate the PIT sounds - which is good thing on the ears.

**Comment by BPaden** [comment] 2020-06-26 15:43
Hah, I do appreciate any attempt to prevent dos games from blowing out my eardrums, which a lot of these games seem determined to do, this one included. These PC speaker games are designed for their sound coming out of a noisy box four feet away and not sitting right next to your ear, that's for sure.

The new branch does fix the engine sounds. However, I still hear a slight popping sound behind the engine sounds that isn't present in pcem. I wasn't sure if that's related to reducing PIT volume that you mentioned.

**Comment by kcgen** [comment] 2020-06-26 17:06
@BPaden ; thanks for the quick report back.  I haven't touched the PIT / square wave volumes yet, but that's coming up next! Will keep you posted.

**Comment by kcgen** [comment] 2020-06-28 09:14
> However, I still hear a slight popping sound behind the engine sounds that isn't present in pcem.

@BPaden, it turns out prior attempts to tackle DC-offset (in general) were audible to you, as steps of any size wind up creating some kind of sound, similar to the Tandy DAC. 

I've now implemented a sine wave that grabs the DC offset and wraps it around the centerline:

![2020-06-28_01-06](https://user-images.githubusercontent.com/1557255/85942804-844c4f00-b8e0-11ea-9f82-65bc398fc182.png)

The goal here is to walk softly in every possible way:
- Use sine curves, because they are ideal inputs for speaker movement
- Use a sine frequency that's inaudible
- Use multiple curves to allow the speaker diaphram to overshoot and steadily dampen to zero (instead of abruptly ending at zero coming from a high amplitude peak).
- And here's the secret sauce --> you're going to tune it :-)

I can only guess at what you can and cannot hear, so there are two tunables at the top of `src/hardware/pcspeaker.cpp`, in the latest `kc/pc-regression-fix-3`:

``` c++
#define DC_SILENCER_WAVES   10u
#define DC_SILENCER_WAVE_HZ 33u
```

The first controls the number of waves generated, and the second is their frequency.   Above are my defaults. 

A higher frequency will shorten the curves, allowing them to get to zero faster - but you might hear it too.  I've bounded it between 20 Hz up to 60 Hz.

Ideally I would like to make both a bit tigher; say try to get waves down to 5, and the Hz up to 40 Hz.  Curious what you find!

Here are another couple examples of it in action:

![2020-06-28_01-08](https://user-images.githubusercontent.com/1557255/85942805-844c4f00-b8e0-11ea-9e82-f59e95cf0f0a.png)

This shows how the silent waves abut with new samples -- it just picks up without any overlap or harm done to the new (very harsh!) square-wave signal.

![2020-06-28_01-12](https://user-images.githubusercontent.com/1557255/85942806-84e4e580-b8e0-11ea-84f9-62bb80779a92.png)

**Comment by BPaden** [comment] 2020-06-28 23:13
Actually, with your hint I think I've figured out that it isn't working for me at all. It looks like your silencer code is being reached (I threw in some additional printfs), but all I get out are square waves. Now that you mention it, looking at the pcem tones, I do see some jittering at the beginning and end of each tone, but in dosbox, it's just clean square waves.

**Comment by kcgen** [comment] 2020-06-28 23:15
### Update on the PC speaker volume front

Branch `kc/speaker-volume-differentiation-1` applies a higher volume to PWM-mode audio and a lower volume to square-wave PIT-mode audio.

Why do we want this? Because 1) square waves carry twice the power as sinusoidal waves (in a general sense), but PC-speaker square waves are produces at 100% volume 100% of the time.  So not only do they have more power, they're at a higher amplitude - both of which play into loudness.

The original authors accurately emulating the PC speaker in that there really only was one volume settings - and they did their best to make sure those square wave don't bash your ears too hard.  The downside was that PWM (RealSound) like Countdown, Link 386, Mean Streats, and Space Racer's music sound much quieter than the powerful square-wave beeps and boops.

@BPaden , feedback always appreciated!

**Comment by kcgen** [comment] 2020-06-28 23:30
> Actually, with your hint I think I've figured out that it isn't working for me at all.

If you run a debug build: `./scripts/build.sh -c gcc -t debug`

Do you see this printed in with the console messages?

```
SILENCER: Using 10 waves at 33-Hz across 13698 samples
```

The DC silencer kicks when the speaker goes idle, and then scrubs the offset.  I just ran Space Racer again, and after the guy says "hello", you can see it in effect.  Here's the zoom-out of the "hello" portion:

![2020-06-28_16-24](https://user-images.githubusercontent.com/1557255/85960977-2a896a80-b95c-11ea-9fef-0e6ed361718a.png)

Then here's the zoom in, where it's more obvious:

![2020-06-28_16-24_1](https://user-images.githubusercontent.com/1557255/85960985-3e34d100-b95c-11ea-91f3-821a656f9fae.png)

Another check for your repo state:

$ `git rev-parse --verify`: HEAD 472ea9f277b3a0645c48782bb20fb74be442d4ea
$ `git describe`: v0.76.0-alpha-234-g472ea9f2
$ `md5sum src/hardware/pcspeaker.cpp src/hardware/dc_silencer.cpp`

``` text
eea6cde21f8fd79a56ca6d72c86c80a4  src/hardware/pcspeaker.cpp
89e2354900518b7bc14d45b6b92830ba  src/hardware/dc_silencer.cpp
```

**Comment by BPaden** [comment] 2020-06-28 23:33
@kcgen I just tried kc/speaker-volume-differentiation-1, and that seems like a great idea to me! I turned the volume up slightly to hear the intro music more clearly, and the countdown timer and engine noise seemed noticeably less obnoxious on the ears.

**Comment by kcgen** [comment] 2020-06-28 23:43
Thanks @BPaden ! 

The goal for these volume levels is that users won't have adjust their system's volume..  you can be listening to a Youtube music video one minute, then fire up Space Racer the next minute and won't have to turn up or down the volume (also, you won't need `mixer speaker 400` or `mixer speaker 25` tweaks either).

When you compare Space Racer's intro section when the electric guitar  starts jamming - is that volume still too low?

**Comment by kcgen** [comment] 2020-06-28 23:49
At this line in pcspeaker.cpp: `static constexpr float minus_5db = 0.562341`, you can drop in a bit less attenuation see what you think (goal is to match professionally mixed music, especially in the guitar section as that's a fair bit louder):

- 4 dB = `0.630957`
- 3 dB = `0.707946`
- 2 dB = `0.794328`
- 1.5 dB = `0.841395`
- 1 DB = `0.891251`

**Comment by BPaden** [comment] 2020-06-29 00:26
Hmm, everything matches in `kc/pc-regression-fix-3` except for the md5sum for pcspeaker.cpp which is `3fd6444e062b44926043793208cbced4` for me. I confirmed it was different with a fresh clone as well. Not sure why that wouldn't match but everything else did.

Anyway, now that you've pointed it out, I do see the sine wave filling in a long pause between the bikes revving their engine and the countdown starting. I did move those values back and forth quite a bit without noticing any real difference. I think the square waves are too close together for that to kick in.

I think this may be what I'm hearing:
![2020-06-28-19:19:42](https://user-images.githubusercontent.com/1188012/85962112-8233d000-b974-11ea-801f-824fb18bc979.jpg)

It's hard to tell, because everything moves so fast in real time, but I managed to find a 0.7 second region where I heard three pops and I counted three of those little dips.

**Comment by kcgen** [comment] 2020-06-29 02:02
> I think the square waves are too close together for that to kick in.

You're right.  the DC Silencer kicks in only after 75ms - and we see in your screenshot the first square wave starts roughtly ~35ms after the prior square wave ends; then there's a short ~3ms blip, and then ramp down again.. after which the 75ms countdown starts again:

![2020-06-28_18-54](https://user-images.githubusercontent.com/1557255/85965303-21ef5f00-b971-11ea-84e9-4e875fd038d4.png)

So that particular stretch is not touched, and just what the game is doing. 

In audacity, you can stretch your internal window showing the two stereo lines - and then you can further stretch just one of the channels - so you can really magnify the vertical axis; which I find handy.

When stretched, the wait period and silencing jump out like little cork screws :-) In Space Racer, it only kicks in three times:

![2020-06-28_18-45](https://user-images.githubusercontent.com/1557255/85965440-92967b80-b971-11ea-9202-ee0f6195cdb6.png)

Then the square-wave engine noises crank up, and the delays are never long enough for DC silencing:

![2020-06-28_18-46](https://user-images.githubusercontent.com/1557255/85965441-92967b80-b971-11ea-8de2-6f45c5b169f3.png)

**Comment by kcgen** [comment] 2020-06-29 04:44
@BPaden , 

Branch ` kc/issue-464-rc-1` contains both fixes we've worked on here (engine-noise and volume control).

This is just a temporary branch for us to test with to confirm there's no adverse interaction between the two; after which I'll move them forward for PR.

**Comment by BPaden** [comment] 2020-06-29 17:14
Not off-hand, but I did a quick search and ran into [this video](https://www.youtube.com/watch?v=pzNbGa05dfg), which might be a good place to start. I went ahead and skimmed through it to find all the games. Some of them probably use PIT for sound effects as well:

three stooges
turbo cup
crazy cars
space racer
world class leader board
mach 3
purple saturn day
perestroika
bad cat
hard drivin
aspar gp master
mean streets
countdown
crime wave
links the challenge of golf
pinball fantasies

**Comment by kcgen** [comment] 2020-06-30 16:27
before, 

| Game | Before | After <br> kc/issue-464-rc-1 |
| Countdown | [before](https://drive.google.com/file/d/1JGke4n8K1x9cC9Cjt3S9g2fo4NU7FeOW/view?usp=sharing) | [after](https://drive.google.com/file/d/11qkWsJjZiXMbX-33qFiY1OnkJQPAAJ6V/view?usp=sharing) |
| Crazy Cars | before | after |
| Crime Wave | before | after |
| Digger | before | after |
| Duke Nukem 1 | before | after |
| Hard Drivin'  | before | after |
| Karateka | before | after |
| Links 386 Golf | before | after |
| Links the Challenge of Golf | before | after |
| Mach 3 | before | after |
| Mean Streets | before | after |
| Paratrooper | before | after |
| Pinball Fantasies | before | after |
| Shamus | before | after |
| Sopwith | before | after |
| Space Racer | before | after |
| Turbo Cup | before | after |

**Comment by kcgen** [comment] 2020-06-30 17:01
In the above, PWM volume should be solid and clear in the **after**'s, and not sound so damped down like in the **before**'s.  
Square wave beeps and boops should sound comfortable and tolerable for long play periods; and not pound your ears out.

If we think the **after**s are generally better, then I'll prepare the work covered here in three PRs.

 - regression fix for the engine noise
 - silencer fix for the post-effect pops
 - volume differentiation enhancement

**Comment by BPaden** [comment] 2020-07-02 21:24
The volume adjustments are definitely a clear improvement. I think in the case of Crazy Cars, part of the issue there is the game is very sensitive to timing.

I get pretty good results at 500 cycles, but the music is definitely more distorted than it should be. Even on an emulated 6mhz 286 in pcem, the sound was also not very good, but it seemed clear enough in the video. I'm not sure how it was recorded in the video, though. I doubt it was on real hardware. Probably an old version of dosbox. I don't have an old AT or anything lying around, unfortunately.

Shamus is another title that is sensitive to timing. The walking sounds seem correct to me at 500 cycles.

Turbo Cup has a similar improvement as Space Racer. I also notice a weird sound in this game. You'll probably be able to hear it in my recording. For some reason, this sound is more pronounced on my machine than in your recording. [Check it out](https://drive.google.com/file/d/1GY1m7wUJ27A11QrysjXUpmss1y2njRfd/view?usp=sharing).

It sounds significantly different, actually. Not sure why that would be, but whatever the underlying reason, that's probably why I also notice pops in Space Racer. Maybe an underlying pulseaudio thing?

**Comment by kcgen** [comment] 2020-07-03 00:19
> The volume adjustments are definitely a clear improvement. <..> Turbo Cup has a similar improvement as Space Racer.

@BPaden, thank you for lending your critical ear.

> I get pretty good results at 500 cycles

Yup, I also dial down the timings on these mid-80s games. 500 cycles put dosbox around an 8 Mhz 286 - which bang-on for a ~1988 PC.  I think I've set Shamus and Alley Cat even lower; the tad bit of slow down lets me get a bit further :-)

Another thing I do is lock the mixer and PC Speaker to 16,000 Hz, disable all other sound devices, and disable memory beyond 640k:

``` text
[dosbox]
machine=pcjr # (ega or cga)

[dos]
xms=false
ems=false
umb=false

[mixer]
rate=16000

[speaker]
pcspeaker=yes
pcrate=16000
tandy=off
disney=false

[gus]
gus=false

[sblaster]
sbtype=none
oplmode=none
```

> It sounds significantly different, actually. Not sure why that would be, but whatever the underlying reason, that's probably why I also notice pops in Space Racer. Maybe an underlying pulseaudio thing

I can only think of a couple things:

1. grab/build the latest `kc/issue-464-rc-2`, as I've re-based everything against master, which includes the initial enveloper, and re-merged the two cleanly together.

2. use a low sampling rate; I suggest 16,000 because that's roughly on par with the actual frequency respond of inferior, slow-to-react internal PC speaker back in the 80s.  They were as cheap as they got.. essentially cloc-radio speakers; had terrible frequency response and extremely poor signal-to-noise ratio.

Today's speakers and headphones have a very tight response and much higher SnR. At 44,100 or 48,000 they will fathfully reproduce those square-wave spikes!  The best option is to use 16,000, 11025, or 22050.

Keep in mind that unlike a poor speaker, you might hear the odd harmonic - so in Speed Racer at 16,000 the three beep, beep, beep, boooop starting line tones have a bit of warble.  Maybe at 11025 or 22050 you can eliminate them :-)

Let me know if both those get you a bit closer. 

_(PS- Although I grew up with EGA + PC Speaker games on our family's Amstrad, I increasingly disregarded them with the advent of the NES and early PC sound cards. However, this effort has rekindled my appreciation for these early DOS-era games.  Thanks for that :-)_

**Comment by BPaden** [comment] 2020-07-05 19:35
A minor correction: 500 cycles is too slow.

I forgot to mention it before, but I noticed that Turbo Cup was too choppy at 500 cycles compared to an emulated to an emulated 6mhz 286 in pcem and today I decided to do some comparisons with the [mips benchmark](https://archive.org/download/msdos_mips). Pcem's performance characteristics aren't perfect either, but it's reasonably close and it's convenient to be able to choose a model of cpu at a give frequency for comparison's sake.

Here's 

280 ≈ 4.77 mhz 8088 (dosbox wiki says 315. Looking at the benchmarks, I think this is too fast. BTW, it turns out Crazy Cars works best around here, despite being released in 1987.)
900 ≈ 6 mhz 286
1150 ≈ 8 mhz 286

This is important for this issue because I've found that a difference of even just a couple hundred cycles either way — in addition to the pcrate —  can make a huge difference in the way some of these games sound. Here is Space Racer at 16khz and 1150 cycles, just the engine noise. [The results are self evident](https://drive.google.com/file/d/1I-NR9xPGb9c6Fjnq22xPVIoO1O7biWjx/view?usp=sharing).

Sounds pretty good to me. In addition to being too pronounced because of too-high pcrate, the dips in Space Racer from the engine sounds are about 10 times longer than they should be at 500 cycles.

**Comment by kcgen** [comment] 2020-07-05 21:47
I agree; I think you've found a sweet spot for Space Racer; very interesting regarding the dip durations!   

@dreamer, this kind of painstaking tuning @BPaden has taken the time to dial in will make our archive-ROM format all the more valuable.  Users will be able to fire up a game with all these settings locked in, ensuring a consistent and fool-proof experience. 

@BPaden , Part 4 of 4 in the PR series sets the default pcrate to ~18.9 KHz to match the actual peak pc speaker frequency response based on clock timers in the hardware - which removes the harmonic warble in the three beep beeps at the starting line with pcrate 16000. (So should be a tad better; but we don't have an integrated build yet that includes all four fixes simultaneously.. soon enough :-). 

So this is also in the right direction versus "cdrom 44100" rates, which did not exist back then.

**Comment by kcgen** [comment] 2020-07-17 06:05
@BPaden , thanks again for this detailed report :clap:  It resulted in the merging of a regression fix (engine sound), DC offset silencing improvement, PWM-vs-square wave volume differentiation, and using a lower default sampling rate to match actual PC-speaker performance.  I think we can close this; onward and upward!

**Closed by kcgen** 2020-07-17 06:05 UTC
Labels: bug

**Comment by BPaden** [comment] 2020-07-17 07:00
Awesome work all around, @kcgen! Thanks for looking into this. It sounds great.

**Comment by Akuma-Git** [comment] 2020-09-02 18:23
Having some issues with Digger 1983, sound has ticks & scratches.
[digger1983.flac.zip](https://github.com/dosbox-staging/dosbox-staging/files/5164072/digger1983.flac.zip)

**Comment by dreamer** [comment] 2020-09-02 19:41
@Akuma-Git let's discuss this problem in #598
