### ISSUE TITLE
Archimedean Dynasty: Bugged HUD elements with 3dfx

### ISSUE THREAD

**Issue by geist22** [dosbox-staging/dosbox-staging#2943] opened 2023-09-16 10:52 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-1677-gf7498da22

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Certain HUD elements are rendered wrong when playing the 3dfx version, and appear distorted a bit to the right. They consist of mostly text in the cockpit and 3rd person views, but also other elements such as reticles, circles and sqares around enemies, lines, etc.

Below are two screenshots comparing the software version to the 3dfx version. Check the upper middle part of the HUD, the text block in the middle left and the armor indicator on the lower right.

Software:
![03a](https://github.com/dosbox-staging/dosbox-staging/assets/107389189/807b8c22-d25e-49be-bb57-d0d7726457d9)

3dfx:
![03b](https://github.com/dosbox-staging/dosbox-staging/assets/107389189/a47cb000-6957-4b9f-b19f-7979316fb08e)

### Steps to reproduce the behaviour.

1. Download & install the game from the link below
2. Install the 1.120 patch and the 3dfx patch, working download links can be found at https://soggi.org/misc/3dfx-voodoo-game-patches.htm
3. Start the game via AD3DFX.EXE and start a mission such as training/instant action.
4. Look at the HUD and compare it to how it looks when playing through AD.EXE

### Download URL of affected game or software

https://archive.org/download/archimedean-dynasty

### Your configuration

```ini
The issue appears even with a default config file.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-09-16 12:18
Can you check if DOSBox X and PCem/86box renders the HUD correctly with Voodoo @geist22 ?

**Comment by geist22** [comment] 2023-09-16 12:59
I've run the game in DOSBox ECE and it displayed correctly. I think it used the nGlide wrapper.

I previously tried to get it running in DOSBox X, but 3dfx mode in this game didn't work there no matter what I tried. I haven't tried the other programs, I think knowing that DOSBox ECE displays it correctly should suffice, but if you still need them tell me so I can try setting it up.

**Comment by geist22** [comment] 2023-09-16 13:24
I've managed to get it running in a new DOSBox X version now without a problem. HUD displays fine there, too. Though both ECE and X have a minor issue where the background image of the pre-mission briefing screen is sometimes cut off (haven't seen this so far in staging).

**Comment by johnnovak** [comment] 2023-09-16 21:45
Thanks @geist22. Just to be clear, you used low-level Voodoo emulation (not high-level emulation, which uses Glide) in DOSBox X? Stuff like nGlide and do things very differently; it's a completely different approach than true low-level Voodoo emulation. Just to make sure we have an apples to apples comparison 😄

**Comment by geist22** [comment] 2023-09-16 21:57
> Just to be clear, you used low-level Voodoo emulation (not high-level emulation, which uses Glide) in DOSBox X?

I'm using `dosbox-x-mingw-win32-20230901214948.zip` from https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.09.01 with default config. I'm afraid I have no idea what kind of technique is used below the hood there. I was under the impression DOSBox-X used a wrapper for 3dfx, just like ECE.

**Comment by johnnovak** [comment] 2023-09-17 00:03
> > Just to be clear, you used low-level Voodoo emulation (not high-level emulation, which uses Glide) in DOSBox X?
> 
> I'm using `dosbox-x-mingw-win32-20230901214948.zip` from https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.09.01 with default config. I'm afraid I have no idea what kind of technique is used below the hood there. I was under the impression DOSBox-X used a wrapper for 3dfx, just like ECE.

This page might help:
https://dosbox-x.com/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X

According to that, Glide is off by default, so you must be using the low-level emulation then.

**Comment by geist22** [comment] 2023-09-17 00:38
Glide is off in the config and I'm using the .OVL file provided by the game. Some games I have installed use wrappers, but IIRC these only work locally and are not used by the system as a whole. So it seems to be the low-level emulation.

Thought ECE and X used an integrated wrapper, maybe I was wrong or got confused. GOG version of Archimedean Dynasty does use a DAUM build with nGlide if I remember correctly.

**Comment by Grounded0** [comment] 2023-12-11 00:24
Are you using Glide 2.43? That's the most robust version of Glide for DOS.

**Comment by geist22** [comment] 2023-12-11 02:09
Driver... are you talking about the GLIDE2X.OVL file? The readme says the game was set up to use version 2.42.

Can you provide a working link for 2.43?

**Comment by Grounded0** [comment] 2023-12-11 02:17
@kcgen 

Can you link your prepared driver pack for this user. ⬆️

**Comment by kcgen** [comment] 2023-12-11 03:40
Here's 2.43: [glide2x.ovl.zip](https://github.com/dosbox-staging/dosbox-staging/files/13630698/glide2x.ovl.zip)

Unfortuantely 2.43 doesn't improve it, and neither do the line drawing methods:

![2023-12-10_19-29](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/5ea62067-596a-4ff6-a20b-4b9d1b3af42d)

**Comment by Grounded0** [comment] 2023-12-11 09:11
@kcgen 

I think the game just applies texture filtering on all surfaces including the HUD that produces this effect. Since it also happens with Glide 2.43 there is very little we can do about it or its not in our scope to sort this out. Suggest closing with a "Close as not planned" flag.

**Comment by Grounded0** [comment] 2023-12-11 15:13
We made a more careful team analysis of the problem and admit there is probably a problem in low-level emulation. We currently don't have the manpower to figure this out but hopefully 0.81.0 release will bring more people in who are more capable of figuring out Glide issues so this would be something for them to look at.

**Comment by Python-Exoproject** [comment] 2024-07-26 16:46
Id like to add my 2 cents as well.

I was about to start looking into converting exodos 3dfx games over to Staging and the first game up is Archimedean Dynasty where Ive encountered this HUD issue.

Currently we are using ECE with its software implementation of 3dfx and there the HUD is fine, but in Staging I get the same blurred HUD as per the screenshot above.

As Staging's implementation is not at the same performance as ECEs yet I will have to park this project for now which is a shame as in general Stagings implementation seems faster and more robust. Ill watch this ticket eagerly for any progress

**Comment by johnnovak** [comment] 2024-07-26 21:53
@Python-Exoproject The problem is, neither of us in the core team care much about the Voodoo, and this requires a deep dive into the Voodoo low level emulation code. Maybe try to bribe Aaron Giles, it's his original code 😆

**Comment by interloper98** [comment] 2024-07-26 22:13
@Python-Exoproject , I think X and ECE have two 3dfx interfaces to the host - software-only (like Staging) but also using a glide wrapper (which I think tends to be Windows-only?)

This bug might be common to all the software-only implementations with  the gl/glide interface being unaffected. Will try to isolate this.

**Comment by Python-Exoproject** [comment] 2024-07-26 23:06
Appreciate you looking into it @interloper98 

The ECE config we use in eXoDOS uses the software 3dfx implementation so its apples to apples in that sense

**Comment by Python-Exoproject** [comment] 2024-07-26 23:17
@johnnovak If Aaron wrote the code then is it the same code in ECE? If so then it should make it easier to spot what ECE is doing right compared to Staging hopefully?

**Comment by johnnovak** [comment] 2024-07-27 01:48
> @johnnovak If Aaron wrote the code then is it the same code in ECE? If so then it should make it easier to spot what ECE is doing right compared to Staging hopefully?

I don't know 😄 I have stayed away from the Voodoo thing on purpose, and I have every intention to continue doing so 😆

**Closed** 2024-07-27 13:49 UTC
Labels: bug, help wanted, game compatibility, video, voodoo, eXoDOS/Win3x

**Comment by Python-Exoproject** [comment] 2024-07-28 15:46
Not that its needed but I can confirm the fix is working, thanks again @interloper98
