### ISSUE TITLE
Support game-specific builds of DOSBox

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1671] opened 2022-05-14 19:43 UTC
### DWD DOSBox

 - **Game(s):** Wizardry VI
 - **What:** There is an audiopop issue that this build of dosbox fixes. See file "custom-readme.txt" under heading "Extras" in the archive DWDdosbox.rar for details.
 - **Sources:**: https://github.com/hiddenasbestos/dosbox-gridc. The build is mainly for use with Grid Cartographer but still includes the wizardry pop fix according to the docs 
 - **Binary:** [DWDdosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/8693738/DWDdosbox.zip)
 - Another option for this is already in Staging's PC Speaker code (in a generic way, as well), however it would need to be externalized as a conf setting: see https://github.com/dosbox-staging/dosbox-staging/issues/963#issuecomment-812088248

### DOSBox GunStick
 - **Game(s):* Cosmic Sheriff (1989), Mike Gunner (1988), and Pack Regalo Gun Stick (1989)
 - **What:** : These games use this build as it turns the mouse cursor into a crosshair.
 - **Sources:**: patch included with binary
 - **Binary:** [GunStick_dosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/8693737/GunStick_dosbox.zip)

### DOSBox 0.63

 - **Game(s):** Viper (1998)
 - **What:** Most builds just crash, though X gives an error "CacheBlock overrun 2 written 8195 size 8192".

### Boppie's Great Word Chase (1985)

It was previously understood that the floppy disk contained copy protection that could be represented using the standard img format. 

New information from @NRS-NewRisingSun indicates otherwise:

> Looking at the Kryoflux stream files of the game that are in TDC, the disk is not copy-protected at all, and runs perfectly fine in Vanilla/ECE DOSBox using `BOOT DISK.IMA`.

-- thanks, @NRS-NewRisingSun.

### mpubuild of DOSBox

 - **Game(s):** Casino Tournament of Champions (1995)
 - **What:** Game has a lot of cuttoff speech once you get past the intro stuff. It says welcome blah blah, after that it uses speech to read "We have a great deal to offer you. Games of chance for any taste." During the speech it cuts off at the word chance. This continues on the next screen where it cuts out at the words "Black Jack Tournament".
 - **Sources:**: This was built by ripsaw8080; source is (on vogons?)
 - **Binary:**[mpubuild_dosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/8693736/mpubuild_dosbox.zip)

### STDOSBox

 - **Game(s):** SimTown (1995)
 - **What:** This game has an in game error message pop up anytime you build a house in the game. Happens with all forks as well.
 - **Sources:**: This was built by ripsaw8080; source is (on vogons?)
 - **Binary:** [STdosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/8693735/STdosbox.zip)

**Comment by LowLevelMahn** [comment] 2022-05-14 20:18
Do you want to detect the game and behave diffenently in staging or make normal staging more compatible?

**Comment by kcgen** [comment] 2022-05-14 20:46
Made more compatible, ideally. Given ripsaw8080 opted for one-off builds, my guess is those instances came with regressions/downsides.

Worst case, we'd add a conf option to support a class of games (for example, I can see the cross-hair cursor being valuable for lots of POV shooter type games), or a conf setting to change some behavior in a generic way (that happens to fix some games).  

We definitely wouldn't add one-off game-hacks (or detection) to Staging or game-specific conf settings.

**Comment by dreamer** [comment] 2022-05-14 20:55
I think this exercise is probably to track if game-specific builds incorporate any changes that we might want to upstream ;)

I know about following additional game-specific builds:

### Carmageddon
- **Game**: Carmageddon (GOG and Steam releases)
- **What**: Glide patch and additional changes, Windows-only.
- **Sources**: Code dump is distributed with the game, I imported changes to branch `forks/steam-carmageddon-1`: 00e70c191d035cf4bdd4665f950d74234d2e3918

### Blizzard's fork
- **Game**: The Lost Vikings
- **What**: One tiny bugfix that was incorporated in later SVN version long time ago, Blizzard-specific changes to show Blizzard splash screen. Change to remove DOSBox name from window title. Windows-only changes.
- **Sources**: Patches included with old release of The Lost Vikings (back when Blizzard was offering this game to download for free). After review I decided it's not necessary to preserve these changes on a branch.

**Comment by kcgen** [comment] 2022-05-14 21:15
Thanks for those additions @dreamer !

**Comment by Torinde** [comment] 2023-09-23 13:42
**Microsoft Flight Simulator v1.05** ([ticket](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-67424512))
- **What**: [FPU DIV exceptions](https://www.scs.stanford.edu/05au-cs240c/lab/i386/s14_07.htm)
> -- from ripsaw's readme --
> The 8088 processor has different divide exception behavior than later Intel processors, and it is for this reason that MSFS v1.05 doesn't work correctly in DOSBox. There are actually a few quirks of the 8088 that DOSBox doesn't emulate; although some unofficial branches do, but I'm not sure if any get the divide exception behavior fully correct. Anyway, I've made workarounds for the few games affected by the quirks, including MSFS v1.05. The attached patch replaces the divide exception handler in v1.05 with the one from v2.13, which is less 8088-specific -- it generally works, but the demo @ mode appears sensitive to speed.
- **Sources**: "some unofficial branches" (Daum, X, Staging, ECE, another?). 
Separately [MartyPC](https://int10h.org/blog/2023/07/martypc-pc-xt-emulator-raising-the-bar/) is a recent very precise 8088 emulator, so may come in handy for comparison.

**Comment by rderooy** [comment] 2023-09-23 14:48
> ### Microsoft Flight Simulator v1.05 ([ticket](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-67424512))
> * **What**: [FPU DIV exceptions](https://www.scs.stanford.edu/05au-cs240c/lab/i386/s14_07.htm)
> 
> > -- from ripsaw's readme --
> > The 8088 processor has different divide exception behavior than later Intel processors, and it is for this reason that MSFS v1.05 doesn't work correctly in DOSBox. There are actually a few quirks of the 8088 that DOSBox doesn't emulate; although some unofficial branches do, but I'm not sure if any get the divide exception behavior fully correct. Anyway, I've made workarounds for the few games affected by the quirks, including MSFS v1.05. The attached patch replaces the divide exception handler in v1.05 with the one from v2.13, which is less 8088-specific -- it generally works, but the demo @ mode appears sensitive to speed.
> 
> * **Sources**: "some unofficial branches" (Daum, X, Staging, ECE, another?).
>   Separately [MartyPC](https://int10h.org/blog/2023/07/martypc-pc-xt-emulator-raising-the-bar/) is a recent very precise 8088 emulator, so may come in handy for comparison.

DOSBox-X indeed has a `cputype=8086` setting specifically for games like these. No need to patch the games.

**Comment by kcgen** [comment] 2023-09-23 15:43
Good to document both options; thanks @Torinde and @rderooy.

**Comment by johnnovak** [comment] 2023-09-23 22:21
I can't say I love this idea of basically supporting per-game DOSBox hacks. A much better way would be to patch the executable and leave DOSBox alone (like NewRisingSun has done for many games). The scope of fixes/changes you can do via DOSBox side hackery is also very limited; basically, you can only apply bandaids to a limited range of emulator problems. By patching the actual game, you have much greater freedom and are able to change behaviour, fix bugs, add features, etc.

Giving it's limited utility, fragile and hacky nature, plus all the naintenance complications this would introduce, personally I would not even entertain the idea further. So to be clear, in all these cases either improving the emulator in general or providing a custom patched EXE (by someone else, not by us) is the correct answer, I think.

**Comment by Torinde** [comment] 2023-09-24 06:57
Since this is in the eXoDOS project - does the above include all of eXoDOS/eXoWin3x games that use _other_ DOSBox variants besides original/SVN/Daum (#2945)/Staging?

It seems all of the cases above are "clear", except Viper 1998.

**Regression from old original DOSBox? Can that be investigated?**
- Viper (1998) - DOSBox 0.63 works, other versions/builds mostly crash, X gives an error

.conf setting to add in Staging
- Wizardry VI - PC speaker fix is already in Staging, however it would need to be externalized as a conf setting ([#963](https://github.com/dosbox-staging/dosbox-staging/issues/963#issuecomment-812088248))
- Cosmic Sheriff (1989), Mike Gunner (1988), and Pack Regalo Gun Stick (1989) - .conf setting to turn the mouse cursor into a crosshair.

Fix source available in a patch/diff branch
- Casino Tournament of Champions (1995) - a lot of cuttoff speech - fixed in build by ripsaw8080, source on vogons
- SimTown (1995) - in game error message - fixed in build by ripsaw8080, source on vogons
- Carmageddon (GOG and Steam releases) -  Glide patch and additional changes https://github.com/dosbox-staging/dosbox-staging/commit/00e70c191d035cf4bdd4665f950d74234d2e3918
- Microsoft Flight Simulator v1.05 - would require a cputype=8086, like in X

Fix identified, but source not available
- Boppie's Great Word Chase (1985) - requires Transcopy format ([#2224](https://github.com/dosbox-staging/dosbox-staging/issues/2224)) due to copy protection, potentially will fix a "class of games"

Done
- The Lost Vikings - the relevant part of the fix is already in SVN

**Comment by johnnovak** [comment] 2024-03-29 21:32
Game specific builds and plugin systems are out of scope. We have enough on our plates and enough complexity already, thank you 😅

**Closed** 2024-03-29 21:33 UTC
Labels: enhancement, out of scope, game compatibility, won't do

**Comment by Grounded0** [comment] 2024-04-30 21:17
I think we should try to run these games and check if they work with DOSBox Staging 0.81.x.

**Comment by dreamer** [comment] 2024-06-06 07:36
> > [](https://github.com/dosbox-staging/dosbox-staging/commit/00e70c191d035cf4bdd4665f950d74234d2e3918)
> 
> What are the "additional changes", besides Glide, which Staging now has?

Nothing special, some modification in function `Normal_loop` [link](https://github.com/dosbox-staging/dosbox-staging/commit/00e70c191d035cf4bdd4665f950d74234d2e3918#diff-f5ea1ed765f6d313041204e8564ce84ca2dc2c94255c6ad4d92f933d0fe723e4), and a letter added to the window title. Nothing we would like merged.
