### ISSUE TITLE
[BUG] Dosbox Debugger - Hotkeys like F10 do not work anymore

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1487] opened 2022-01-01 10:15 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hotkeys do not work anymore in dosbox debugger, im using them always, several times a week

### Steps to reproduce the behaviour.

build dosbox with debug/heavy_debug and start debug with a program, try using F10, F5 etc. nothing happens, debug window got the focus

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2022-01-02 16:11
@LowLevelMahn , thanks for this. Calling setlocale() conflicts with ncurses when it's already established its display. We could call it before, but we apparently [also need to ensure](https://stackoverflow.com/a/9927113) the locale is limited to UTF-8 (which it might not be) or we need to use ncursesw - also not a guarantee. So I'm just not calling setlocale() - or other OS-specific locale queries  when running inside the debugger.

Build to test: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1646505954

**Comment by LowLevelMahn** [comment] 2022-01-06 10:18
works for me!

**Comment by kcgen** [comment] 2022-01-06 19:05
Thanks for the confirmation @LowLevelMahn ! 
Closing.

**Comment by LowLevelMahn** [comment] 2022-02-04 07:05
happens again with current git (04.02.2022/8:04) :/

no hotkey works in debugger

**Comment by Grounded0** [comment] 2022-02-09 07:41
Closing as duplicate of #1561.

**Closed by Grounded0** 2022-02-09 07:41 UTC
Labels: bug
