### ISSUE TITLE
Command & Conquer: Red Alert crash after load one saved game

### ISSUE THREAD

**Issue by F0xMcloud** [dosbox-staging/dosbox-staging#3810] opened 2024-07-06 11:29 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-x64-0.82.0-alpha-5e1f5

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Game run normally, then you save one games, when try load game in one new seccion, background is missing and units overwrite on screen when you move them.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run game
2. Play some mission (first by example, then save game)
3. Close game and start again
4. Load previous saved game, background is missing and units overwrite on all screen when move them
5. Load again game without close game
6. Game crash with next error:

![imagen](https://github.com/dosbox-staging/dosbox-staging/assets/162722808/d8c33c8f-d90a-4d00-8cc3-ba566172165d)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by F0xMcloud** [comment] 2024-07-06 11:33
[SAVEGAME.zip](https://github.com/user-attachments/files/16115814/SAVEGAME.zip)

attached my saved game

**Comment by weirddan455** [comment] 2024-07-06 21:11
I cannot reproduce this.  I can create my own saves and load them back with no problem.

Your save file won't load at all for me.  It gives an error message "Obsolete saved game".  Perhaps you have an older game version.  Mine says v1.04 on the title screen.  Can you confirm what version you have?  This could be a game version and installing a patch will fix it.

Another thought I had was if you installed the game using a DOSBox version affected by the regression from #3802 it may have not installed properly.  You could try re-installing the game now that ISO file regression has been fixed.

**Comment by MasterO2** [comment] 2024-07-06 21:22
@F0xMcloud Maybe take a look at https://www.pcgamingwiki.com/wiki/Command_%26_Conquer:_Red_Alert#Essential_improvements as well?

**Comment by johnnovak** [comment] 2024-07-07 00:34
@F0xMcloud Please use the latest 3.03p fan patch or the eXoDOS version and let us know if you're still getting the issue after the upgrade.

Some of these games are just buggy, and it can be a massive waste of time to determine whether something is a game or emulation bug.

So please always use the latest official patches with every game you're playing. Or even better, just grab eXoDOS which usually has the best and most stable version of the games.

**Comment by F0xMcloud** [comment] 2024-07-07 12:21
> I cannot reproduce this. I can create my own saves and load them back with no problem.
> 
> Your save file won't load at all for me. It gives an error message "Obsolete saved game". Perhaps you have an older game version. Mine says v1.04 on the title screen. Can you confirm what version you have? This could be bug in the game itself and installing a patch will fix it.
> 
> Another thought I had was if you installed the game using a DOSBox version affected by the regression from #3802 it may have not installed properly. You could try re-installing the game now that ISO file regression has been fixed.

I use verified cd image from "redump.org", i have installed all expansions "Aftermatch" and "Counterstrike", so my red alerte is updated to vseriosn 2.00

**Comment by MasterO2** [comment] 2024-07-07 12:35
> > I cannot reproduce this. I can create my own saves and load them back with no problem.
> > Your save file won't load at all for me. It gives an error message "Obsolete saved game". Perhaps you have an older game version. Mine says v1.04 on the title screen. Can you confirm what version you have? This could be bug in the game itself and installing a patch will fix it.
> > Another thought I had was if you installed the game using a DOSBox version affected by the regression from #3802 it may have not installed properly. You could try re-installing the game now that ISO file regression has been fixed.
> 
> I use verified cd image from "redump.org", i have installed all expansions "Aftermatch" and "Counterstrike", so my red alert is updated to version 2.00
> 
> ![imagen](https://private-user-images.githubusercontent.com/162722808/346334710-f4274039-91c8-4bb9-b088-1e6d2357256e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTU5MjUsIm5iZiI6MTcyMDM1NTYyNSwicGF0aCI6Ii8xNjI3MjI4MDgvMzQ2MzM0NzEwLWY0Mjc0MDM5LTkxYzgtNGJiOS1iMDg4LTFlNmQyMzU3MjU2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMjMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWZhMGQ5ZGQ4NmZlMjU5MjliMWQwNWI4YWIwYzkxMzk3MTdmODYzMTYwOTU2ZDU0YTM3YTFmOTViNmNiODQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rq0lbZusdEPb0ttm4g4scYma7pVurc87_sO0njCXc3Q)
> 
> I installed again full game + expasions and saved game after lasts fix.
> 
> I think issue is related to disc swap, i have mount all discs at same time in next order:
> 
> cd1 -> Red alert (allied disc 1) cd2 -> Red Alert (soviet disc 2) cd3 -> Aftermatch (disc 3) cd4 -> Conterstrike (disc 4)
> 
> By default dosbox mount disc 1 (first in list), so i swap disc when game need with keyboard shortcut (Ctrl+F4)
> 
> My save games is from mission 3 (soviet disc 2), so i have swap disc when load saved game

The original Command & Conquer game supports having all 3 discs inserted at the same time on different drives.

Have you tried mounting or imgmounting all 3 Red Alert discs on the D, E, and F drives respectively?

**Comment by F0xMcloud** [comment] 2024-07-07 12:39
not i have all them mount on "D" drive, then i swap with keyboard shortcut

**Comment by weirddan455** [comment] 2024-07-07 16:34
I still can't reproduce the problem with disk switching.  It seems at least the first Soviet mission is playable on the Allied disk so I downloaded a save game from this site (Soviet mission 5)  http://ra.afraid.org/html/downloads/savedgames.html

It prompted to insert the Soviet disk and Ctrl+F4 just worked for me :man_shrugging:

**Comment by interloper98** [comment] 2024-07-07 16:51
@weirddan455 , I wonder if there's something going on with the conf files (or default settings)?

The screenshot shows its running at 3000 cycles (but the crash is inside DOS4GW); I would expect protected me to be running at 60,000 cycles (if the conf is default?)

@F0xMcloud, can you attach your `dosbox.conf` for this game and paste your log output? (The log should be in the Widnows cmd.exe console adjacent to DOSBox Staging GUI window).

**Comment by johnnovak** [comment] 2024-07-07 22:11
> The screenshot shows its running at 3000 cycles (but the crash is inside DOS4GW); I would expect 60,000 cycles for protected mode (if the conf is default). Hmm.. or maybe the crash popped it out of pmode?

Yeah, so by the time this gets printed to tge console, we're out of pmode. That's normal.

**Comment by F0xMcloud** [comment] 2024-07-08 10:54
[logs.txt](https://github.com/user-attachments/files/16126498/logs.txt)

[dosbox-staging.zip](https://github.com/user-attachments/files/16126506/dosbox-staging.zip)

Here is my log file untill crash happen and my config file.

**Comment by johnnovak** [comment] 2024-07-08 11:05
> > The screenshot shows its running at 3000 cycles (but the crash is inside DOS4GW); I would expect 60,000 cycles for protected mode (if the conf is default). Hmm.. or maybe the crash popped it out of pmode?
> 
> Yeah, so by the time this gets printed to the console, we're out of pmode. That's normal.

Well, probably the printout happens while still in pmode, then the pmode->realmode switch happens one nanosecond later, to be exact 😄

**Comment by Grounded0** [comment] 2024-07-16 00:45
Can anyone still reproduce this or was this just one flaky build of `main`?

Anyone who feels they don't want the extra drama of running developer builds should just stick to release versions because this stuff is bound to happen on `main`.

**Comment by interloper98** [comment] 2024-07-16 02:03
I tried it just now but couldn't reproduce it on `main`.
1. started an allied mission, saved my game.
2. aborted the mission and exited back to the DOS prompt
3. restarted `ra.exe` (still in the same DOSBox Staging session), loaded the mission, and was able to keep playing.

**Comment by johnnovak** [comment] 2024-07-20 22:19
@F0xMcloud @MasterO2 any updates?
This doesn't seem like a Staging issue so I'm inclined to close it.

**Comment by MasterO2** [comment] 2024-07-21 21:06
> @F0xMcloud @MasterO2 any updates? This doesn't seem like a Staging issue so I'm inclined to close it.

Since I did not create this issue, I defer your question to @F0xMcloud.

**Comment by johnnovak** [comment] 2024-07-21 22:29
Two core members couldn't reproduce the issue and the last messages from the OP indicated the game is fine when the CDs are mounted properly, so closing.

**Closed by johnnovak** 2024-07-21 22:29 UTC
Labels: bug
