### ISSUE TITLE
Freeze Installing MechWarrior 2 in 0.81 RC

### ISSUE THREAD

**Issue by Lowe0** [dosbox-staging/dosbox-staging#3313] opened 2024-01-09 15:58 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.x-rc1

### What Operating System are you using?

Windows 10

### If Other OS, please describe

Debian ARM

### Relevant hardware info

Alienware M11x R3, RPi 5 8GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When installing MechWarrior 2 , after the initial configuration, the installer will start to copy files.  After MS.EXE, the install will stop copying any further.  No messages are written to the dosbox console.

Tested on Windows 10 x64 and Debian ARM 64 on RPi 5 (built from source at RC1 tag).  Regression tested against 0.80.1 on Windows 10 x64.

MechWarrior 2 disc is v1.1 w/o NetMech.  MD5 of bins:
MD5 (MECH2 (Track 01).bin) = 3203cd8c30e17e550279cc3288d72bb0
MD5 (MECH2 (Track 02).bin) = cb2980cd76688bc25c75c34810c94565
MD5 (MECH2 (Track 03).bin) = 2c440f1e16cbd88c28fbd2337446a60a
MD5 (MECH2 (Track 04).bin) = 78054480d57bea35d36a672317306e49
MD5 (MECH2 (Track 05).bin) = 407ec6d6dac8e3f1ebe66feb3875535f
MD5 (MECH2 (Track 06).bin) = f0e1811a03dd932dff0f354b57669dba
MD5 (MECH2 (Track 07).bin) = 7dc20165ff0472a4a0e001758fc74127
MD5 (MECH2 (Track 08).bin) = 1c331ca748944f42db0962e13049eda6
MD5 (MECH2 (Track 09).bin) = e1b2e10e8f4f90f398a2ce282f81a0df
MD5 (MECH2 (Track 10).bin) = e6adac7cf9140e099b79d11ed2dbc334
MD5 (MECH2 (Track 11).bin) = 33fa2eea2f8602b6614a4d9b5e3cf446
MD5 (MECH2 (Track 12).bin) = be9ba60210cadc98bdaea0cb35da0807
MD5 (MECH2 (Track 13).bin) = 3c2a4f62661c677a3c014309327f8d10
MD5 (MECH2 (Track 14).bin) = 3cf8eccb39f6a4a71627fe78c96e8452
MD5 (MECH2 (Track 15).bin) = b57eed47db220541e552c180964b5f2f
MD5 (MECH2 (Track 16).bin) = e23e7a0ea1312574a7b069278f5ed457
MD5 (MECH2 (Track 17).bin) = 19edf21e7c2e2917458809c65970872d
MD5 (MECH2 (Track 18).bin) = 4777f7ccadd7e7cfdc6909219932221b
MD5 (MECH2 (Track 19).bin) = 80b8579305045254c495fde11c41f1c6
MD5 (MECH2 (Track 20).bin) = 4bd810ec2dfd886b45793e5c4906d70a
MD5 (MECH2 (Track 21).bin) = b8b683fd200cf4a5e849f4e89abba806
MD5 (MECH2 (Track 22).bin) = ec8a8f2b1931838c4793b31822c110b6
MD5 (MECH2 (Track 23).bin) = 084f315d1b5ff7bd59d974b0367e581e
MD5 (MECH2 (Track 24).bin) = 7353e26cc7a7f8650315be603d63de2e
MD5 (MECH2 (Track 25).bin) = afea327622bed15b04b566f47947249d
MD5 (MECH2 (Track 26).bin) = 19f947d1c5795885612044c087fceb72
MD5 (MECH2 (Track 27).bin) = 851f15c716ee5765a3fe20ede19f6df6

I tested this using a MW2 v1.0 CD mounted directly as /dev/cdrom on Debian ARM 64; this made no difference, but I can rip it to a proper bin/cue set and retry to reproduce like-for-like.

### Steps to reproduce the behaviour.

Repro:

1. Start dosbox-staging 0.81
2. Mount a host path as the C drive
3. Mount a host path to a bin/cue pair as the D drive with -t cdrom
4. Change drive to D:
5. Run INSTALL.EXE
6. Configure sound (use no sound or music card; this doesn't impact reproducibility)
7. Configure install size (tried all sizes; again, doesn't impact reproducibility)
8. Start the install; a list of copied files will begin to appear
9. Wait until MS.EXE is written

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2024-01-09 21:42
Thanks @Lowe0 - can you try w/ the latest MSYS2 dev build? 

https://dosbox-staging.github.io/releases/development-builds/

(It's possible this has been fixed already with the handful of fixes since RC1)

**Comment by Grounded0** [comment] 2024-01-09 23:12
@Lowe0 

It isn't obvious in your post but does this work in 0.80.1?

**Comment by Lowe0** [comment] 2024-01-10 01:08
> @Lowe0
> 
> It isn't clear in your post but does this work in 0.80.1?

Yes.  Sorry to be unclear, but I did regression test against 0.80.1 on Win10 x64.  (Can't also regression it on Pi, as I don't have a Pi running a pre-Bookworm image to test, and 0.80.1 segfaults on Bookworm on ARM 64.). Mech2 installs from the same bin/cue pair w/o issue under 0.80.1.  (And if you mount the resulting install under 0.81 RC, the game runs fine.)

@kcgen I'll try the dev build out shortly.  Thanks!

**Comment by kcgen** [comment] 2024-01-10 02:14
Confirmed good w/ `main` using the MechWarrior 2: 31st Century Combat [USA v1.0 release](http://redump.org/disc/24334/) mounted from [original BIN/CUE](https://ia903404.us.archive.org/view_archive.php?archive=/33/items/mechwarrior-pc-redump/MECHWARRIOR-PC-REDUMP/MechWarrior%202%20-%2031st%20Century%20Combat%20%28USA%29.zip). 

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/7dd0b34a-719f-4a19-8858-b0c3c01a2387

**Comment by johnnovak** [comment] 2024-01-10 02:46
> Confirmed good performing a maximum installation w/ `main` using the MechWarrior 2: 31st Century Combat [USA v1.0 release](http://redump.org/disc/24334/) mounted from [original BIN/CUE](https://ia903404.us.archive.org/view_archive.php?archive=/33/items/mechwarrior-pc-redump/MECHWARRIOR-PC-REDUMP/MechWarrior%202%20-%2031st%20Century%20Combat%20%28USA%29.zip).

On what? The latest dev build?

**Comment by kcgen** [comment] 2024-01-10 02:57
> On what? The latest dev build?

Yup.. latest `main` branch. It has all the backported fixes.

**Comment by weirddan455** [comment] 2024-01-10 06:26
>  Wait until MS.EXE is written

Probably this was fixed by #3299

There was a string compare function that incorrectly matched substrings of device driver names like "MSCDEX".  The issue I tested against occured when launching an `M.EXE` so would expect the same from `MS.EXE`.

**Comment by Lowe0** [comment] 2024-01-10 14:04
> > Wait until MS.EXE is written
> 
> Probably this was fixed by #3299
> 
> There was a string compare function that incorrectly matched substrings of device driver names like "MSCDEX". The issue I tested against occured when launching an `M.EXE` so would expect the same from `MS.EXE`.

I’ll pull main when I get home from work and retest.  Thanks for the insight!

**Comment by Grounded0** [comment] 2024-01-11 00:28
Closing.

**Closed by Grounded0** 2024-01-11 00:28 UTC
Labels: regression
