### ISSUE TITLE
Expose additional settings through `midiconfig`

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1119] opened 2021-07-05 11:37 UTC
While current defaults for built-in MIDI synths are good, some people may still feel the need to adjust something under the hood. They could use external software, but it's more practical to stick to whatever is already there.

To not clutter the configuration with more options, `midiconfig` could be utilised to set things like gain, reverb, chorus, some other FluidSynth and mt32emu-specific options, as a comma- or space-separated string of `variable=value` elements.

**Comment by dreamer** [comment] 2021-07-06 07:36
Closing as duplicate of #843

**Closed by dreamer** 2021-07-06 07:36 UTC
Labels: discussion, enhancement
