### ISSUE TITLE
Digger 1983 sound issue

### ISSUE THREAD

**Issue by Akuma-Git** [dosbox-staging/dosbox-staging#599] opened 2020-09-02 19:43 UTC
**Describe the bug**
Having some issues with Digger 1983, sound has ticks & scratches.
Attached ZIP

**To Reproduce**

**Expected behaviour**
Clean sound.

**Environment (please complete the following information):**

**Version of dosbox-staging:**
v0.76.0-alpha-670-g5b5fd7c3

**Configuration parameters:**
cycles=850
boot DIGGER.IMG

**Additional context**
[digger1983.flac.zip](https://github.com/dosbox-staging/dosbox-staging/files/5164463/digger1983.flac.zip)

**Comment by kcgen** [comment] 2020-09-02 19:55
Very good catch @Akuma-Git - Indeed; we've had a regression; but this was playing clean during when we wrapped up the PC Speaker improvement PRs.  Will try to bisect where it was introduced.

**Comment by kcgen** [comment] 2020-09-02 20:35
Reproduced and working on fix.

**Comment by kcgen** [comment] 2020-09-02 22:01
@Akuma-Git , can you give https://github.com/dosbox-staging/dosbox-staging/pull/600 a spin?
(branch: `kc/digger-wave-type-fix-1`)

**Comment by kcgen** [comment] 2020-09-02 22:06
Note that compared to SVN and others, staging will lowed the amplitude of Digger's square-wave sound effects to carry (roughly) the same perceived loudness as the music.  This is because its sound-effects are powerful square waves compared to the music, which is an approximated sine-wave. 

In general, staging always reduces the level square waves versus sine-waves; to prevent some games from literally blowing your ears out :-)

**Comment by dreamer** [comment] 2020-09-02 22:23
Issue got closed automatically as soon as I merged-in the fix. @Akuma-Git - since this was merged to master, you can test these builds now: https://dosbox-staging.github.io/downloads/devel/

If you still experience sound problems in this game, feel free to reopen the issue (or leave a comment - I'm not sure if users can reopen themselves).

**Comment by Akuma-Git** [comment] 2020-09-03 07:36
Its on par with SVN now :+1: , however there are still pops and crackles.
Attached:
digger_git_v0.76.0-alpha-673-g666faa90.flac
digger_svn_rev_4358.flac

[digger_audio_git_svn.zip](https://github.com/dosbox-staging/dosbox-staging/files/5166930/digger_audio_git_svn.zip)

**Comment by Akuma-Git** [comment] 2020-09-03 07:55
When I record sound with SVN, recording is filename_###.wav
However in staging the recording is dosbox_###.wav, is this by design ?

**Comment by dreamer** [comment] 2020-09-03 07:58
@Akuma-Git our builds are created automatically on CI, we just sometimes post links where to download them :)

I re-tested carefully and yeah, I can still hear clicks after every music section - we're on par with SVN, not better.

@kcgen do you have an idea if we can mitigate those few remaining clicks?

**Comment by dreamer** [comment] 2020-09-03 08:03
> When I record sound with SVN, recording is filename_###.wav (digger_###.wav)
> However in staging the recording is dosbox_###.wav, is this by design ?

I can't reproduce - for me the recordings are always named as the program that is running (I tested both normal programs and a booter game). Perhaps you started the recording before starting the game?

**Comment by Akuma-Git** [comment] 2020-09-03 08:27
> > When I record sound with SVN, recording is filename_###.wav (digger_###.wav)
> > However in staging the recording is dosbox_###.wav, is this by design ?
> 
> I can't reproduce - for me the recordings are always named as the program that is running (I tested both normal programs and a booter game). Perhaps you started the recording before starting the game?

You were too fast :) , I believe it to be a recording taken with boot DIGGER.IMG instead of DIGGER.COM. So I deleted the post.

**Comment by kcgen** [comment] 2020-09-03 16:21
> I re-tested carefully and yeah, I can still hear "pops" after every music section - we're on par with SVN, not better.

Yes, this end-of-the-music-loop pop has always annoyed me too; it ends in a short discontinuity that's part of the waveform generated by the game.

> @kcgen do you have an idea if we can mitigate those few remaining artifacts?

It would involve "processing" the stream and watching for these patterns and then reshaping them. Kind of like the what the enveloper does, but it would run all the time for the PC speaker, and would be more intensive than simply a level-limiter.  

If this were a common issue with PC speaker games, then absolutely.  But carrying a load like this just for Digger feels wrong.  Maybe we can contact the author and see if they can fix it?

**Comment by kcgen** [comment] 2020-09-03 17:25
Closing this because the regression that was flagged has been fixed & merged, (however we can still keep trying to make Digger better-than-baseline).



> When I record sound with SVN, recording is filename_###.wav (digger_###.wav) However in staging the recording is dosbox_###.wav, is this by design ?

SVN limits when you start recording -- it will ignore your key-presses until it actually starts the DOS program and the window-title changes.

However dosbox-staging lets you start recording almost immediately (and will honor your Ctrl + F6 hotkey), even before the DOS program is started up.  If you're really fast, then your recording will be "dosbox-000.wav", but if you wait a bit till the program starts, then the recording will be named after the program executable (digger-000.wav).

**Closed by kcgen** 2020-09-03 17:25 UTC
Labels: bug, game compatibility

**Comment by kcgen** [comment] 2020-09-04 02:27
@Akuma-Git ,

When you beat the level, it plays a little tune, which terminates "perfectly" (you won't hear a pop):

![2020-09-03_18-43](https://user-images.githubusercontent.com/1557255/92192300-85d34f80-ee1a-11ea-8ab9-75a923238b0c.png)

Contrast this with the in-level tune, which terminates in a pop:

![2020-09-03_18-47](https://user-images.githubusercontent.com/1557255/92192303-85d34f80-ee1a-11ea-9a85-9f278293fc6c.png)

So the answer lies within; the developers need to terminate the main tune with the same chunk of PIT/timer calls that the level-win tun terminates with.   Or.. maybe the executable can be patched/hacked with similar effect.

(like @dreamer mentioned, SVN and also DOSBox-X are also affected - however they run their speaker very quiet because they haven't compensated for thundering square-wave power like staging has; but if you amplify the tune to match staging's levels then you will similarly hear the pop).

Oh - I also noticed the DOS remastered Digger apparently supports SoundBlaster output - but I couldn't figure out how to get that working.  Perhaps if that worked fine and without pops, then we can also consider it good-as-solved.

**Comment by dreamer** [comment] 2020-09-04 08:37
Oh, in SVN I hear popping without amplifying the sound level at all.
