### ISSUE TITLE
Covox Sound Master - two potential games

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1843] opened 2022-08-10 16:09 UTC
@Python-Exoproject indicated that a handful of games support the CSM:

https://nerdlypleasures.blogspot.com/2012/04/unique-pc-hardware-game-support.html
 - Conan - The Cimmerian
 - Galleons of Glory
 - Megatraveller 2
 - Prince of Persia (v1.0 only)
 - Punisher, The
 - Sim Earth
 - Spirit of Excalibur
 - Twilight 2000
 - Ultima VI
 - Vengeance of Excalibur
 - Where in Time if Carmen Sandiego (AY8930 music)
 - Where in the World is Carmen Sandiego (320x200 VGA Version)

However, @Python-Exoproject confirmed that most of these also support Adlib and other FM music options. When it comes to sound effects, the following almost exclusively use the CSM:

 - MegaTraveller 1 (PC Speaker or CSM)
 - Space 1899 (Adlib or CSM)
 - SimCity (PC Speaker, Tandy, or CSM)
 - The Punisher (Covox through PC Speaker or Covox through CSM)
 - Transylvania III (Covox Speech Thing or CSM)

And of these, only MegaTraveller 1 and The Punisher are limited to using the PC Speaker or CSM, and aren't able to  use the SB's DAC when configured on a CSM-compatible port (220).

This means that these two games probably use some CSM-specific detection routine, followed by playing effects via the CSM DAC.

**Comment by Jkapp76** [comment] 2023-01-12 05:43
This may be unrelated, but, could this needed Covox enhancement have anything to do with me having so many issues getting proper sound to work with the "Last half of Darkness" series?

It's been a long time since I tried them and they may work nowadays. But the games had speech and weird sounds that played through that parallel port speaker and I never got it working on DOSBox.

**Comment by johnnovak** [comment] 2023-01-12 05:48
> This may be unrelated, but, could this needed Covox enhancement have anything to do with me having so many issues getting proper sound to work with the "Last half of Darkness" series?
> 
> It's been a long time since I tried them and they may work nowadays. But the games had speech and weird sounds that played through that parallel port speaker and I never got it working on DOSBox.

Mobygames lists them as having Covox Sound Master II support, so yes, it might be related.

https://www.mobygames.com/game/dos/last-half-of-darkness/techinfo

**Comment by johnnovak** [comment] 2024-06-13 03:25
Duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/2219

**Closed** 2024-06-13 03:26 UTC
Labels: duplicate, enhancement, audio
