### ISSUE TITLE
"Open with DOSBox Staging" Context Menu Button Doesn't mount current directory

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3041] opened 2023-10-22 20:29 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-alpha-1811-g6e534

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In release builds of staging, selecting the "Open with DOSBox Staging" option from the context menu will open Staging with the folder that you opened the context menu in mounted as drive C, in the current dev build, it doesn't do anything.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Right click in a folder in file explorer, click the "show more options" button in the context menu
2. Click "Open with DOSBox Staging" button
3. Staging should open, not mounting anything as the C drive.

### Your configuration

```ini
https://gist.github.com/OpenRift412/c7b699b85f209e88491d4c0cfcbfb098
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment] 2023-10-22 22:10
Can you remove [text] from the title. Makes it difficult to read and does not form in our ticket style. Thanks.

**Comment by johnnovak** [comment] 2023-10-22 22:28
I removed it as it was a really shit feature... From memory, depending on _where_ exactly you right-clicked in Windows Explorer inside a folder, either an EXE or BAT file you right-clicked on was executed and the folder was mounted, but the local dosbox.conf was ignored, or (I think) if you right-clicked on the blank area, only the folder was mountef, the if you right clicked exactly on the local `dosbox.conf`, then was Staging started from that folder and picked up the local config, which is the most important and common use case.

In my getting starting guide I would've had to explain this at great lengths; it's confusing as fuck. I myself had to spend a good 10 minutes on it to figure out what the hell is going on with the context menus. Not against bringing back some of these more advanced options, but they must not confuse the basic use case, which is just starting Staging from a folder, picking up the local conf.

**Comment by johnnovak** [comment] 2023-10-22 22:36
See my PR where I normalised and rationalised the right-click context menu for Windows:

https://github.com/dosbox-staging/dosbox-staging/pull/2355

**Comment by johnnovak** [comment] 2023-10-22 22:41
Relevant section of the Getting Started guide -- I want these instructions to be simple and non-confusing for newcomers. Requiring people to right-click on blank area or search for `dosbox.conf` to right-click on are shit solutions
 The user must be able to click _anywhere_ inside a folder or _on_ a folder icon to start Staging from there. The most common use case must be the easiest to discover and use.

https://dosbox-staging.github.io/preview/dev/getting-started/prince-of-persia/#starting-dosbox-staging

> If you have used the installer with the default options to set up DOSBox Staging (and it’s highly recommended to do so while you’re still learning the ropes), simply right-click on the Prince of Persia folder in Windows Explorer and select the Open with DOSBox Staging in the context menu.
> 
> Alternatively, you can enter the folder, right-click anywhere on the blank area inside it, then select Open with DOSBox Staging in the context menu.

**Comment by OpenRift412** [comment] 2023-10-22 22:47
> I removed it as it was a really shit feature... From memory, depending on _where_ exactly you right-clicked in Windows Explorer inside a folder, either an EXE or BAT file you right-clicked on was executed and the folder was mounted, but the local dosbox.conf was ignored, or (I think) if you right-clicked on the blank area, only the folder was mounted, then if you right-clicked exactly on the local `dosbox.conf`, only then was Staging started from that folder and picked up the local config, which is the most important and common use case.
> 
> In my getting starting guide, I would've had to explain this at great lengths; it's confusing as fuck. I myself had to spend a good 10 minutes on it to figure out what the hell is going on with the context menus (never used them in Explorer before). Not against bringing back _some_ of these more advanced options, but they must not confuse the basic use case, which is just starting Staging from a folder, picking up the local conf. That must be as easy as possible, without any weird "traps" to confuse user.


> See my PR where I normalised and rationalised the right-click context menu for Windows:
> 
> #2355

I'm a little bit confused. DOSBox will not mount anything regardless of if I'm right clicking an open space inside the folder or the folder itself. I'm not trying to open an EXE.

**Comment by johnnovak** [comment] 2023-10-22 22:51
> I'm a little bit confused, but let me explain my situation again: DOSBox will not mount anything as the C drive regardless of if I'm right clicking an open space inside the folder or the folder itself. I'm not trying to open an EXE.

It will behave as if you started it with `--working-dir FOLDERNAME`.

**Comment by OpenRift412** [comment] 2023-10-22 23:47
> > I'm a little bit confused, but let me explain my situation again: DOSBox will not mount anything as the C drive regardless of if I'm right clicking an open space inside the folder or the folder itself. I'm not trying to open an EXE.
> 
> It will behave as if you started it with `--working-dir FOLDERNAME`.

Right, but it's not doing anything. It's still in the Z drive. The C drive isn't mounted at all.

**Comment by johnnovak** [comment] 2023-10-23 00:53
> > > I'm a little bit confused, but let me explain my situation again: DOSBox will not mount anything as the C drive regardless of if I'm right clicking an open space inside the folder or the folder itself. I'm not trying to open an EXE.
> > 
> > 
> > It will behave as if you started it with `--working-dir FOLDERNAME`.
> 
> Right, but it's not doing anything. It's still in the Z drive. The C drive isn't mounted at all.

Yes. Because `--working-dir` only simulates starting Staging from the specified folder. If a local `dosbox.conf` exists, it picks it up, plus it does the automounting if `drives/c` etc. exists.

My main problem with automounting the current folder as C is that it conflicts with the magic automounted `drives/` folders.

Not against re-introducing a context menu item perhaps to "auto-mount the current folder as C", but then it will need to be explicitly stated in the context-menu entry. E.g., "Auto-mount folder as C drive and run DOSBox Staging" or something.

I really don't wanna change the semantics of "Open with DOSBox Staging" — that should just start Staging from that folder using `--working-dir` and that's it.

**Comment by OpenRift412** [comment] 2023-10-23 01:26
> > > > I'm a little bit confused, but let me explain my situation again: DOSBox will not mount anything as the C drive regardless of if I'm right clicking an open space inside the folder or the folder itself. I'm not trying to open an EXE.
> > > 
> > > 
> > > It will behave as if you started it with `--working-dir FOLDERNAME`.
> > 
> > 
> > Right, but it's not doing anything. It's still in the Z drive. The C drive isn't mounted at all.
> 
> Yes. Because `--working-dir` only simulates starting Staging from the specified folder. If a local `dosbox.conf` exists, it picks it up, plus it does the automounting if `drives/c` etc. exists. Just starting `dosbox.exe` that's in your PATH from any given folder won't mount that folder—that's expected and correct behaviour.
> 
> My main problem with automounting the current folder as C is that it conflicts with the magic automounted `drives/` folders.
> 
> Not against re-introducing a context menu item perhaps to "auto-mount the current folder as C", but then it will need to be explicitly stated in the context-menu entry. E.g., "Auto-mount folder as C drive and run DOSBox Staging" or something. Maybe I'd go even as far as _not_ to install this context-menu option by default; advanced users fond of this legacy feature could tick a checkbox in the installer to get this context-menu entry installed, but its use is discouraged for regular use, so it should be opt-in.
> 
> I really don't wanna change the semantics of "Open with DOSBox Staging" — that should just start Staging from that folder using `--working-dir` and that's it.

I see. Honestly I really don't see the usefulness in having it use the `--working-dir` function, but I suppose that's up to you. I guess a second context menu item that re-introduces the mounting functionality would do fine. Probably something concise like "Mount folder in DOSBox Staging".

**Comment by johnnovak** [comment] 2023-10-23 03:44
> I see. Honestly I really don't see the usefulness in having it use the --working-dir function, but I suppose that's up to you. I guess a second context menu item that re-introduces the mounting functionality would do fine. Probably something concise like "Mount folder in DOSBox Staging".

Sorry, wasn't aware that I closed this—must have mis-touched something on my phone 😄 

The usefulness is that there's one recommended standard way to set up games:

- `YourGameFolder` is the game folder
- `YourGameFolder/dosbox.conf` is the local per-game config that only contains a few lines to override settings from the primary config, just what the game needs, nothing more.
- `YourGameFolder/drives/c` is the C drive which gets automounted. In the future, you'll be able to just chuck the CD images into `drives/d` etc. and they'll get automounted as well (we're not there yet).
- You start up your game by running Staging _from that folder_. Local config gets picked up & automounts get automounted. That can be accomplished by:
  - Starting `dosbox.exe` from `YourGameFolder` (if it's in your PATH).
  - Starting `dosbox.exe --working-dir YourGameFolder` from anywhere else.
  - Right-clicking on the `YourGameFolder` icon in Explorer, or inside the blank area of `YourGameFolder` and select the `Open with DOSBox Staging` item.

That is the standard and recommended way; I'm recommending this to newcomers in the upcoming [Getting Started](https://dosbox-staging.github.io/preview/dev/getting-started/introduction/) guide. This way of setting up and launching games is well-defined and works consistently across platforms. Feel free to familiarise yourself with the guide; it still needs updating for the final release.

**Comment by johnnovak** [comment] 2024-03-15 00:29
This is the new behaviour and as I explained the old mount behaviour was at odds with providing a consistent cross-platform behaviour. Not a bug, closing.

**Closed by johnnovak** 2024-03-15 00:29 UTC
Labels: bug

**Comment by gex581990** [comment] 2024-07-30 04:36
I don't understand how this is supposed to be the standard behavior.  We have to alter a games folder structure just for this to work? With Dosbox-x you can simple right click an .exe/.com/.bat and run it with, no problems.  If you want you can also mount the folder (as is) with right click then be able to call the program/game with it's name and extension into the prompt. But this is needlessly convoluted. I'm not seeing the benefit of this "new intended behavior". I have hundreds of Dos games and I'm not altering every single folder just to run it with this when they work as is with most other forks.

**Comment by johnnovak** [comment] 2024-07-30 05:03
> I have hundreds of Dos games and I'm not altering every single folder just to run it with this when they work as is with most other forks.

Fine 😎

**Comment by Grounded0** [comment] 2024-07-30 08:49
Fixing stupid vs preserving backwards compatibility. I think we've struck a good balance there since few people are complaining.

**Comment by Amaroq-Clearwater** [comment] 2024-07-30 09:31
Thanks for the inspiration!

> Do we correct glaring issues and risk breaking everything, or do we let them be, preserving the status quo on the off chance it’s the only thing holding the whole house of cards together? 
> 
> Sometimes, the best way to fix something is to leave it broken—at least then, everyone knows what to expect.

What do you think?

**Comment by maximilien-noal** [comment] 2024-07-30 09:46
The old behavior is part of the many reasons I quit working on a dosbox frontend.

I'm glad it has been finally fixed !

**Comment by johnnovak** [comment] 2024-07-30 10:45
> Thanks for the inspiration!
> 
> > Do we correct glaring issues and risk breaking everything, or do we let them be, preserving the status quo on the off chance it’s the only thing holding the whole house of cards together?
> > Sometimes, the best way to fix something is to leave it broken—at least then, everyone knows what to expect.
> 
> What do you think?

We try to strike a balance here, but we can't completely ignore the 20 years of history of DOSBox. But some things are just best left forgotten 😆 


> The old behavior is part of the many reasons I quit working on a dosbox frontend.
> 
> I'm glad it has been finally fixed !

Indeed, it was weird and inconsistent and a cause for numerous issues and complications.
