### ISSUE TITLE
Do not discard commented lines in [autoexec] section

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3234] opened 2023-12-18 11:54 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

When using the `config -wc` command - lines commented with `#` are being discarded:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/d97f4473-3424-43f9-b9b1-8d2ee2b75337)

### Describe the solution you'd like

Like #2415 does for empty lines - `#` lines also to be preserved.

### Describe alternatives you've considered

Using DOS batch comment prefix (`rem` lines are preserved).

### Add any other context or screenshots about the feature request here.

Testing latest build for the issues I mentioned at https://github.com/dosbox-staging/dosbox-staging/issues/3128#issuecomment-1825396175

Related item is:
> config -wc -created dosbox.conf in exe folder instead of updating the dosbox-staging.conf in %APPDATA% (also dosbox-staging.conf in %APPDATA% has priority over dosbox.conf in exe folder - or dosbox.conf in exe folder isn't used at all?)

It still works like that and I don't see it as a bug. I don't have opinion on what the priority of those files should be. What's strange for me is that Staging `config -wc` doesn't create/update `dosbox-staging.conf`, but creates `dosbox.conf` even if such doesn't exist in any of the folders and the same isn't used afterwards.

Also, config -wc seems to unnecessarily duplicate the [autoexec] user lines in some cases.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment] 2023-12-18 15:00
`REM` is the official DOS comment marker so we probably shouldn't honour any other comment marker as being non-standard. If we start treating `#` as a comment marker it will create problems somewhere else.

**Comment by FeralChild64** [comment] 2023-12-18 15:30
To be precise, there are two ways to put comments in the `[autoexec] `section - either using `rem` keyword, or double colon:

```BAT
rem Comment 1
:: Comment2
```

Comments starting with hash (`#`) are always discarded/overwritten/updated when saving configuration file.

**Comment by FeralChild64** [comment] 2023-12-18 15:31
Closing - not a bug.

**Closed as not planned by FeralChild64** 2023-12-18 15:31 UTC
Labels: enhancement

**Comment by kcgen** [comment] 2023-12-18 17:02
Although the `[autoexec]` block is inside the conf, the content block of `[autoexec]` is MS-DOS Batch content. 

It's passed to our Batch parser, just like a real DOS program.

So if we added carve outs, we would be deviating from proper Batch handling.

The way to think of `REM` is _'remark'_, which was the proto-terminology for today's 'comment'.

**Comment by FeralChild64** [comment] 2023-12-18 17:03
Sorry, indeed there is _enhancement_ tag. Still, I can’t think of any sane way to implement this - we need to write new comments, as these gets outdated frequently.

**Comment by Grounded0** [comment] 2023-12-18 20:34
It's mainly a namespace pollution issue. Once you steer away from strict DOS guidelines weird things start to happen elsewhere when characters in batch files are treated as remarks and so on.

**Comment by FeralChild64** [comment] 2023-12-18 21:08
Not to mention we are autogeneration two comment lines at the beginning of the section. Laso, users might be puzzled why the #-comments comments inside [autoexec] persist, while all the others disappear.

**Comment by johnnovak** [comment] 2023-12-18 21:55
@Torinde 

> What's strange for me is that Staging config -wc doesn't create/update dosbox-staging.conf, but creates dosbox.conf even if such doesn't exist in any of the folders and the same isn't used afterwards.

You want -wcd for that. Both -wc and -wcd work as documented; please read the help text for both carefully.

Preserving config file comments _might_ be helpful in some situations, indeed. But it creates a lot of complexity and we'd need a brand new ini parser with comment preserving behaviour. Such ini readers/writers exist, or we could write one, but that's lots of research and a work -- quite the opposite of trivial :) 

If the OSD will support saving settings configured via the on screen GUI, we'll need to potentially rethink our approach to config writing. It's a huge unknown as of yet, we'll see. One option is preserving existing comments and only append to the current local config what's changed.
