### ISSUE TITLE
Call for community provided-or-funded Apple silicon CI runners

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#3323] opened 2024-01-13 19:06 UTC
For the last couple years I've provided and maintained a macOS CI runner for the project, however I'm not able to continue in this role.

This is my own fault, as any single point of failure on an open-source project is a big risk, and now it's been realized unfortunately rather abruptly.  I should have worked harder to eliminate this risk when I had ample time and ability to prioritize this.

A couple quick options that I can suggest:

- **Apple macOS m1 community funding**
    
    Currently, GitHub doesn't offer the macOS M1 runner for free, so one option is funding the CI minutes with community donations. There have been 7,686 macOS workflow runs since getting it setup during the first year of the project, averaging about 250 MacOS workflows per month. Each workflow consists of two M1 setup & build jobs (debug and release). Assuming each run needs 3 minutes to setup and build on the VM, that adds up to 1500 minutes/mo. At [0.16c/min](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates), that's 240 USD/mo.

   Of course, some months can be multiples higher during very active development. Perhaps the project could re-tool CI and dramatically reduce the use of the these M1 jobs to save on those costs.

- **Apple macOS m1 community runners**

    Another option is having a new team of macOS apple silicon users run GitHub's runner software. The idea is that with enough redundancy, no single person is responsible - and machines can freely come off and online. These users could be credited with an "Apple CI team" rank in Discord and given specific thanks in the release notes.

- **Local builds only**

  Another option is simply doing without, and the maintenance team builds releases locally. Apple M1 users who want alpha builds can setup a compilation environment.

The main point in all of this is **_avoiding making this one person's responsibility_** and ensuring the solution has redundancy and some scalability.  If the community wants it bad enough, then the community needs to step forward with their spare machine cycles and/or funds to make this happen.

There's certainly other creative options; Just throwing these out to help!

**Comment by weirddan455** [comment] 2024-01-13 19:49
I'd like to throw out third party cloud hosting as another potential option.  Googling "mac m1 cloud hosting" shows several options available at significantly less cost than what GitHub is charging.  As long as they allow SSH access, we should be able to install GitHub runner software on it.

We would still need funding for that of course, but we may be able to bring the cost down.

**Comment by johnnovak** [comment] 2024-01-13 22:37
Thanks for running a MacMini at your personal expenses for this long @kcgen ❤️ 

@weirddan455 is right, this could be achieved significantly cheaper by a 3rd party service. For example, this European based providers is offering runners at 0.11 Euro per hour:

https://www.scaleway.com/en/hello-m1/

So doubling @kcgen 's monthly average estimate (let's be generous), that's still just around 7 USD per month. Definitely covered by @Grounded0 's contributions, so no need to impersonate Jimmy Wales or a random Jehova's Witnesses person 😎 🤘🏻

**Comment by johnnovak** [comment] 2024-01-13 22:46
Ok my calculation was a bit flawed. If we pay hourly, one run would be probably billed as a full hour if they are spaced apart. But that's still just around 30 USD per month.

I also badly need to optimise the runners so purely doco related changes don't trigger a full code rebuild for all platforms. That's massively wasteful.

**Comment by shermp** [comment] 2024-01-13 22:54
@johnnovak unfortunately, it gets even worse:

> Due to license constraints, the minimum lease for Apple silicon-as-a-Service is 24 hours. As a result, a Mac mini M1 can only be deleted after a minimum allocation period of 24 hours.

Had a look, Amazon EC2 is the same.

Basically means it's only useful as a full time always-available machine. Which would be ~80euro/month at scaleway.

**Comment by johnnovak** [comment] 2024-01-13 23:23
Ah... I was too enthusiastic too soon, then. Always read the fucking fine print 😩

**Comment by johnnovak** [comment] 2024-01-13 23:33
So, making this distributed and/or community funded is a nice idea, but in practice, a MacMini next to the router would do the job just fine, and it's much simpler. Basically what @kcgen has been doing.

Throwing away thousands of dollars on the Mac CI runners _every single year_ is obscene when someone can just buy a MacMini for about 700 USD. And it's the same effort to set it up once!

So if no one has a better idea or wants to host it on his always-on Mac setup, then I'll just probably buy a MacMini from the donation money.

<img width="374" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/1796e3e3-7c3b-4ccc-8723-6794e98e537e">

**Comment by Grounded0** [comment] 2024-01-14 00:38
@johnnovak 

If you plan to stick around yeah. Do specify it with 16 GB of RAM though, please as it will make builds much faster.

**Comment by johnnovak** [comment] 2024-01-14 03:45
Actually, @kklobe found this free GitHub CI solution for macOS:
https://www.flyci.net/

So we're giving that a go instead. 500 mins free per month, seems like it's all we need, and we optimised our pipeline a bit further.

**Comment by Grounded0** [comment] 2024-01-14 04:27
Apple silicon Mac Mini is almost silent and very small and can be stashed away somewhere outside of view so its not out of question to run one inside ones home as a CI runner. Its power usage is also low so its not going to been in utility bills either.

**Comment by johnnovak** [comment] 2024-01-14 04:33
> Apple silicon Mac Mini is almost silent and very small and can be stashed away somewhere outside of view so its not out of question to run one inside ones home as a CI runner. Its power usage is also low so its not going to be seen in utility bills easily either.

No doubt, and I'm not worried about noise or running cost, that's no problem like you said. It's just if we have a solution that's not tied to a single person (me), that's preferable. But if FlyCI sucks, plan B is that I go and just buy the MacMini. It's still just a bit under 900 USD with the 16 GB mem upgrade, I've checked, so definitely an option.

**Comment by Grounded0** [comment] 2024-01-14 04:34
If FlyCI is insufferably slow like GitHub was just before Christmas then that is an option.

**Comment by johnnovak** [comment] 2024-01-14 04:37
> If FlyCI is insufferably slow like GitHub was just before Christmas then that is an option.

Absolutely. We'll just try FlyCI, then drop it if it's problematic.

**Comment by kgantchev** [comment] 2024-01-14 07:29
@johnnovak My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). We're **VERY** thankful for your trust in our service! I want to personally thank you for giving us a try. No doubt, the pressure is on us to deliver so **we're going to do everything we can to make sure that we don't let you down!**

Please keep in mind that we're a brand-new startup and we might have some kinks to iron out before everything is running super smoothly. Please let us know if you run into **any** issues. Our team is 100% committed to making your builds run fast and reliably.

**Comment by johnnovak** [comment] 2024-01-14 07:42
> @johnnovak My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). We're **VERY** thankful for your trust in our service! I want to personally thank you for giving us a try. No doubt, the pressure is on us to deliver so **we're going to do everything we can to make sure that we don't let you down!**
> 
> Please keep in mind that we're a brand-new startup and we might have some kinks to iron out before everything is running super smoothly. Please let us know if you run into **any** issues. Our team is 100% committed to making your builds run fast and reliably.

Thanks for dropping by @kgantchev and the reassurance. We're certainly very hopeful that FlyCI will work out well for us. Sure, some initial difficulties are expected with every new service and we understand it's in beta currently. Having said that, what we're doing is not exactly mission-critical either 😅, but it would be nice to be able to "outsource" our Mac CI runner and not have to buy and maintain our own box (and paying the GitHub fees is out of the question for us).

We'll definitely let you know if we're having issues. Thanks again! 😄

**Comment by kgantchev** [comment] 2024-01-14 07:51
@johnnovak Thank you! And just to add some re-assurance: 

- [We're a team of 20](https://st6.io/team/) with a ton of experience building dev tools.  
- While FlyCI is a new product line for us, it's turning out to be growing very fast so **we've now focused our entire team on it.**  
- We're backed by the biggest Mac hosting provider in the world so we're very optimistic that we won't have a problem with scaling issues.   

Again, thank you for trusting us!

**Comment by johnnovak** [comment] 2024-01-14 08:34
> @johnnovak Thank you! And just to add some re-assurance:
> 
>     * [We're a team of 20](https://st6.io/team/) with a ton of experience building dev tools.

Clearly some wrong assumptions on my part then 😅 

>     * While FlyCI is a new product line for us, it's turning out to be growing very fast so **we've now focused our entire team on it.**
> 
>     * We're backed by the biggest Mac hosting provider in the world so we're very optimistic that we won't have a problem with scaling issues.

That sounds great 👍🏻 
 
> BTW, how did you hear about [FlyCI](https://flyci.net)?

One of our dev team members (@kklobe) posted a link to it. So maybe he can answer that question.

**Comment by kklobe** [comment] 2024-01-14 14:13
> > BTW, how did you hear about [FlyCI](https://flyci.net)?
> 
> One of our dev team members (@kklobe) posted a link to it. So maybe he can answer that question.

I saw the comment at https://github.com/orgs/community/discussions/69211#discussioncomment-7941899

**Comment by kgantchev** [comment] 2024-01-14 14:15
@kklobe thank you! :)

**Comment by Grounded0** [comment] 2024-01-17 06:10
@Burrito78 

Can you check on your macOS 10.15 machine does the new binaries run built with this new CI runner that now online:

- #3329

**Comment by Grounded0** [comment] 2024-01-17 06:22
Here's my last known good `otool` dumps for anyone trying to get the recipe right on this:

```
$ otool -l -arch x86_64 dosbox

Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.15
      sdk 12.1
   ntools 1
     tool 3
  version 711.0

$ otool -l -arch arm64 dosbox

Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 12.1
   ntools 1
     tool 3
  version 711.0
```

Remember to optimise for speed over binary size which is the opposite what Apple recommends.

**Comment by johnnovak** [comment] 2024-01-17 07:34
> Remember to optimise for speed over binary size which is the opposite what Apple recommends.

I always do that, and don't care what Apple or anyone recommend 😎 🤘🏻

**Comment by kklobe** [comment] 2024-01-17 15:37
the new Apple x64 builds crash for @Burrito78 on macOS 10.15. Based on the crash report: `Symbol not found: _kIOMainPortDefault`, the issue seems to be due to the version of SDL2 installed by HomeBrew on my Mac running Sonoma. HomeBrew has never supported distributing applications build against its dependencies, since you get a version that's compiled for your OS. I tried building SDL from source with `export MACOSX_DEPLOYMENT_TARGET=10.15`, but it still produces `minos 14.0` (also by design). For reference, the SDL2 code in question seems to be here: https://github.com/libsdl-org/SDL/blob/0d7df16812c75c4a587d7d2673e3d1a5f2c2879b/src/haptic/darwin/SDL_syshaptic_c.h#L22.

I think the short-term workaround is to get an Apple Silicon machine running macOS 11 that we can use as a runner temporarily, until we get a better long-term solution.

**Comment by Grounded0** [comment] 2024-01-17 17:27
Yeah me and @kcgen knew this would come bite our asses soon. Already planned to moving to MacPorts to avoid this but lets figure out an interim solution for 0.81.0 that could be something like kcgen's buildbot producing a one-off build for us for 0.81.0 once things settle down in his area and he gets his utilities back.

**Comment by kklobe** [comment] 2024-01-17 17:51
> Yeah me and @kcgen knew this would come bite our asses hence we've postponed upgrading from macOS 11. Already planned to moving to MacPorts to avoid this but lets figure out an interim solution for 0.81.0 that could be something like kcgen's buildbot producing a one-off build for us for 0.81.0 once things settle down in his area and he gets his utilities back while development builds would remain macOS 10.15 incompatible for a while.

I'd even be willing to host and maintain it for the short-term if @kcgen wanted to ship it my way?

**Comment by kcgen** [comment] 2024-01-17 21:14
The repair work will be done tomorrow, so I plan to get my systems back up  then. But I do need to wind down my involvement with project for various reasons (all personal, nothing to do with project or community), so hopefully the team can continue to find alternatives for the macOS CI system.

**Comment by johnnovak** [comment] 2024-01-18 00:05
> The repair work will be done tomorrow, so I plan to get my systems back up then. But I do need to wind down my involvement with the project for various reasons (all personal, nothing to do with project or community), so hopefully the team can continue to find alternatives for the macOS CI system.

Sure, that's understandable. It would just help if we could release at least RC2 and the final using your setup 😄

**Comment by kcgen** [comment] 2024-01-18 21:34
The M1 is finally back online; nice work @kklobe !
Will leave the runner process off for now to avoid mixing in this older environment (macOS 11.x + clang 13.0.0); shout otherwise!

**Comment by johnnovak** [comment] 2024-01-19 00:43
> The M1 is finally back online; nice work @kklobe ! Will leave the runner process off for now to avoid mixing in this older environment (macOS 11.x + clang 13.0.0); shout otherwise!

Thanks for the update @kcgen, yep that's for the best for now short-term.

**Comment by kklobe** [comment] 2024-02-05 22:38
Update: M1 runners now available for open source projects!

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by johnnovak** [comment] 2024-02-06 00:06
> Update: M1 runners now available for open source projects!
> 
> https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

I'm in favour of giving that option a honest attempt before discarding it and rushing off buying some hardware. We might still do that, but at least let's investigate this _free_ options first and/or rule it out.

**Comment by shermp** [comment] 2024-02-06 00:51
> > Update: M1 runners now available for open source projects!
> > https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> 
> I'm in favour of giving this option a honest attempt before discarding it and rushing off buying some hardware 😅 We might still do that, but at least let's investigate this _free_ option first and/or rule it out.

Yes. Also, Github hosted runners simplify matters a LOT. No need to worry about managing secrets or access tokens. And unlike self-hosted runners, Github hosted runners are always a clean VM every run.

**Comment by johnnovak** [comment] 2024-02-06 03:33
> Yes. Also, Github hosted runners simplify matters a LOT.

Agreed. I have a strong bias towards keeping the macOS CI jobs on GitHub.

**Comment by johnnovak** [comment] 2024-02-27 01:50
Looks like with @kklobe's help we managed to resolve this issue by using GitHub's M1 runners, so closing.

**Closed by johnnovak** 2024-02-27 01:50 UTC
Labels: help wanted, macOS, CI, build system

**Comment by Grounded0** [comment] 2024-02-27 01:54
An excellent outcome. No more nasty dependencies like a Mac Mini stashed away into some closet somewhere.
