### ISSUE TITLE
Bottom of screen cropped in Descent II

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#1593] opened 2022-03-14 23:12 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When loading Descent 2, the 640x480 mode seems to crop a bit on the bottom for some reason. I've also noticed that loading it in 0.77 didn't seem have the issue.

[Here's my config.](https://github.com/dosbox-staging/dosbox-staging/files/8248996/Descent2config.txt)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load up Descent 2
2. Make sure resolution is set to 640x480
3. Look at the bottom of the screen

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment] 2022-03-15 04:07
So, I can't seem to reproduce this (on Windows 10), I've tried 0.77.1, 0.78.1 and a recent main, using the provided config file, as well as my own. I'm testing the GOG release, which is DII version 1.2. If there is an issue, it is so subtle that I've missed it. 

If you can provide a screenshot showing the issue, that would be very appreciated.

As a side note, apparently DII has a tendency to crash dosbox-staging if the resolution is switched too many times.

**Comment by LowLevelMahn** [comment] 2022-03-15 11:35
also provide your config

**Comment by Burrito78** [comment] 2022-03-16 07:48
Config is linked above. But screenshot would be nice!

**Comment by OpenRift412** [comment] 2022-03-27 20:54
Had to take these in Windowed mode since they wouldn't show in DOSBox's native screenshot tool.
![image](https://user-images.githubusercontent.com/29780788/160300475-b6a490fe-6e02-43a1-8637-ebce628b691c.png)

![image](https://user-images.githubusercontent.com/29780788/160300491-4a487daf-68ae-40e6-9b4d-3740618dfbc5.png)

**Comment by OpenRift412** [comment] 2022-03-27 20:58
_Apparently_ running this without the GLshader I use (which you can download below) seems to alleviate the issue. The problem is though, I didn't have this problem with the shader before the current version, so something in recent releases has been messed up.

[CRT-Lottes_tweaked.zip](https://github.com/dosbox-staging/dosbox-staging/files/8358484/CRT-Lottes_tweaked.zip)

**Comment by GranMinigun** [comment] 2022-03-27 21:10
Yes, it is a known issue. Technically, the shader is broken (I won't go into details, if you don't mind). If you've got that shader from Tyrells' repository, then I've reported it already, and the shader was updated. Unfortunately, there's yet another problem with what shaders expect from DOSBox and how Staging now handles OpenGL.

I thought that behaviour was changed back for all external shaders in 0.78.x though? I don't see which version you're running, could you please specify it?

**Comment by kcgen** [comment] 2022-03-27 21:48
(for ref: https://github.com/dosbox-staging/dosbox-staging/pull/1461)

**Comment by kcgen** [comment] 2022-03-27 21:53
@OpenRift412 , in addition to sharing the version of Staging you're using, please also copy and paste your console log output.

**Comment by OpenRift412** [comment] 2022-03-27 23:27
> @OpenRift412 , in addition to sharing the version of Staging you're using, please also copy and paste your console log output.

Here you go.
[d2 bug log.txt](https://github.com/dosbox-staging/dosbox-staging/files/8358708/d2.bug.log.txt)

**Comment by kcgen** [comment] 2022-03-28 00:14
Thanks @OpenRift412.  Looks like you're running Staging 78.1.

> I thought that behaviour was changed back for all external shaders in 0.78.x though? I don't see which version you're running, could you please specify it?

@GranMinigun - yes, NPOT is being properly disabled (reported in the log), and I confirmed that textures sizes being used are powers-of-two for this (added logging). 

![2022-03-27_17-08](https://user-images.githubusercontent.com/1557255/160307207-879f6d1b-1cc4-43ac-bcea-88a61897f125.png)

> Technically, the shader is broken (I won't go into details, if you don't mind). If you've got that shader from Tyrells' repository, then I've reported it already, and the shader was updated. Unfortunately, there's yet another problem with what shaders expect from DOSBox and how Staging now handles OpenGL.

Thanks @GranMinigun.

@OpenRift412 , in the meantime, try using the GLSL file: `fakelottes.tweaked.glsl` or the equivalent built-in (which doesn't need the GLSL file): `crt-fakelottes-flat`.  It appears to be very similar.

![Screenshot from 2022-03-27 17-07-10](https://user-images.githubusercontent.com/1557255/160307435-c51e7050-065b-4147-bb92-13062877e5ea.png)

**Comment by kcgen** [comment] 2022-04-04 14:09
@GranMinigun indicated the cropping is due to a bug in a shader and that he's already opened an issue against it. An equivalent and working shader that produces the same results without the cropping was indicated in the comment above. Closing.

**Closed by kcgen** 2022-04-04 14:09 UTC
Labels: bug
