### ISSUE TITLE
FLAC assertion failed

### ISSUE THREAD

**Issue by numberZero** [dosbox-staging/dosbox-staging#269] opened 2020-03-31 19:43 UTC
`Assertion failed: targetByte >= rangeLo (dr_flac.h: drflac__seek_to_approximate_flac_frame_to_byte: 5272)`

The only FLAC-encoded data was CD-DA. CUE file is:

```
TITLE "..."
FILE "track-01.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
FILE "track-02.flac" FLAC
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00
FILE "track-03.flac" FLAC
  TRACK 03 AUDIO
    INDEX 01 00:00:00
...
FILE "track-18.flac" FLAC
  TRACK 18 AUDIO
    INDEX 01 00:00:00
```

Not sure which track was playing, but definitely not 2, 3, nor 18.

**Comment by numberZero** [comment] 2020-03-31 20:04
I see that’s too little info, but the bug appeared only once, I couldn’t even get a stack trace.

**Comment by kcgen** [comment] 2020-03-31 20:09
Good stuff @numberZero ;  which game is it, and do you think you can reproduce it?  

In `src/dos/cdrom_image.cpp`, comment-in the `// #define DEBUG` statement and then re-build. It will show you seek locations, and presumably this dr_flac `assert` will trigger just after we attempt to seek.  

Are you using `master` (or the new [draft decoders](https://github.com/dreamer/dosbox-staging/pull/261) branch?)

**Comment by kcgen** [comment] 2020-04-01 00:15
@numberZero , check out: branch `kc/bound-cdda-seeks-1`, which adds protection against seeks and reads beyond the logical end of the track.  

It still returns the expected (negative, failed) value to the games if it requests and out-of-bounds seek, so we shouldn't have regressions - but it detects this higher-level in the code without letting the bad seek drill down into the codec layer (which is where your assert came from).

**Comment by kcgen** [comment] 2020-04-01 15:38
@mackron , can you confirm my understand here:
-  I suppose this was an out of bounds seek, and because we were using a debug build, the assert triggered?
- For release builds, these asserts will fall away, and `drflac__seek_to_approximate_flac_frame_to_byte`would return false in this case? (the upstream code assumes a false bool in the negative case; if so then we would have carried on without issues).

**Comment by mackron** [comment] 2020-04-01 22:00
Hmm, this may well be a bug in dr_flac. Bounds checking is done in `drflac_seek_to_pcm_frame()` here:
```c
    /* Clamp the sample to the end. */
    if (pcmFrameIndex > pFlac->totalPCMFrameCount) {
        pcmFrameIndex = pFlac->totalPCMFrameCount;
    }
```
I need more information, though. A stack trace would be a good start if possible. One question - would the FLAC file have included a seek table? Binary search seeking is used both with and without the presence of a seek table, so perhaps the issue is present in only one of those cases, maybe?

To answer your questions. The `DRFLAC_ASSERT()` macro just evaluations to `assert()`, so yes only triggered in debug. No, you cannot assume `drflac__seek_to_approximate_flac_frame_to_byte()` will work properly in release with a false result. It may work by coincidence, but certainly not by design. My assumption would be that it'll get stuck in a loop, or eventually end up at the very start or very end of the file.

**Comment by kcgen** [comment] 2020-04-01 22:44
@numberZero ,

Is is possible for you to share your flac files with @mackron ?

Also, we can get a backtrace by running:

1. `cd to/game/directory`
1. `gdb /path/to/dosbox-staging/src/dosbox`
1. `b abort` tells gdb to break on any abort
1. `run playgame.bat` launch your game using whatever you use to start it up
1. hopefully reproduce the abort in the game.  If it does, you will be back at the `gdb>` prompt
1. `bt` will ask gdb to print the full backtrace.  Paste it here :-)

**Comment by mackron** [comment] 2020-04-04 00:56
I've re-run my automated test cases and both the seek-table and non-seek-table binary searches complete without issue. I've also scanned over the code and can't see anything obviously wrong. I think this is definitely going to be an edge case. In any case, I need more information before I can debug any further.

**Comment by dreamer** [comment] 2020-04-04 00:59
@numberZero can you share you flac files with us, so we could try to reproduce it?

**Comment by numberZero** [comment] 2020-04-05 19:10
GitHub doesn’t allow large files, so here is just one FLAC: [cd.zip](https://github.com/dosbox-staging/dosbox-staging/files/4434562/cd.zip) (they were all created at the same time in the same way, so there should be no difference. Can’t be sure though.)

> You can get a backtrace by running:

`ulimit -c unlimited`, thanks =)

**Comment by kcgen** [comment] 2020-04-05 20:22
Thanks for the FLAC upload @numberZero.

Testing the integrity `flac -wst cd/worms-united-04.flac`, FLAC reports: `WARNING, cannot check MD5 signature since it was unset in the STREAMINFO`; which normally shouldn't happen.

MPV believes the FLAC is four minutes and eight seconds in duration - when it only contains 42 seconds of audio. 

I don't have access to the bin/cue for Worms United; but you could retry with these steps:
1. Confirm you're using the current release of FLAC:
  - `flac --version` : flac 1.3.3
  - `metaflac --version`: metaflac 1.3.3

1. Confirm you're using the current release of `bchunk`:
  - ` bchunk --version`: binchunker for Unix, version 1.2.2
  - or build it from source http://he.fi/bchunk/bchunk-1.2.2.tar.gz

1. Rip the bin/cue to ISO + tracks: `bchunk -w BIN_FILE CUE_FILE  track`. The tracks will be named `track##.wav`. 
 
1. Compress and add seek-points to the tracks:
  - `flac -5 *.wav`
  - `echo *.flac | xargs -n1 -P4 metaflac --add-seekpoint=1s`

1. Test them:
  - `flac -wst *.flac` It should return nothing if they're good
  - `echo $?`: 0, and return 0 to the shell.

**Comment by numberZero** [comment] 2020-04-05 23:09
It appears the track I uploaded was truncated. It was actually **the only** damaged file among the set.

**Comment by kcgen** [comment] 2020-04-05 23:46
> It appears the track I uploaded was truncated. It was actually **the only** damaged file among the set (17 tracks, not counting data).

Glad to hear the file was truncated in your working game directory (given the uploaded zip was flawless with valid checksums).  Also explains why the file's header advertised having 4:08 of audio; seeking beyond its truncated 42s would land in errorville.

 I think we can now reasonably conclude that the truncation was the root cause here, and gracefully caught by an assert as well - instead of plowing into uncharted memory and segfaulting or bus-error'ing.

Suggest we close this out; @numberZero is that ok? @mackron , is there anything more you want to explore to further improve dr_flac?

**Comment by numberZero** [comment] 2020-04-05 23:50
`assert` is for *internal* errors. Not for corrupted third-party files. Would assertions be disabled, what would happen?

**Comment by kcgen** [comment] 2020-04-06 00:04
> `assert` is for _internal_ errors. Not for corrupted third-party files. Would assertions be disabled, what would happen?

Yes; might have to make a release build to watch the sparks fly, and test what @mackron mentioned: 

> It may work by coincidence, but certainly not by design. My assumption would be that it'll get stuck in a loop, or eventually end up at the very start or very end of the file.

If dr_flac does happen to return false, then the audio for that request simply will not play; and subsequent seeks into available content _should_ play. 

The recent boundary fix I added won't protect us here because it receives the track length's from the codecs, which in turn parse them from the tracks' headers (as opposed to exhaustively reading all the packets).

**Comment by mackron** [comment] 2020-04-06 00:38
When I get a chance, I'll use @numberZero's sample file and try to reproduce. dr_flac should gracefully handle it by just abandoning the seek and returning false. I would rather dr_flac be as stable as possible, even when fed erroneous streams. The assert that was triggered here is for the internal workings of the binary search algorithm, not for protecting against erroneous streams, so I don't think depending on that assert alone is an acceptable solution.

**Comment by mackron** [comment] 2020-04-06 09:22
OK, I've been able to reproduce and fix the issue in dr_flac. It was due to a busted seek table. For some reason all byte offsets in the seek table were set to 0 which caused problems with the binary search. Fixed in the dev branch: https://github.com/mackron/dr_libs/commit/eaa125cc191e0047e4ba9aab7c59524fc326f504

**Closed** 2020-04-19 11:54 UTC
Labels: bug
