### ISSUE TITLE
CD Audio in Wingstar (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3742] opened 2024-06-06 16:14 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Run the game (I used eXoDOS version) and on 0.74 you hear CD Audio during gameplay. Use X\ECE\Staging there is no CD Audio

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the game and compare CD Audio music in gameplay between Staging and 0.74
2.
3.

### Your configuration

```ini
Used defaults with cycles=50000, game folder mounted as C and cd cue file mounted as D
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment] 2024-06-06 17:25
Looks like the game is using the SB16's mixer to turn down the CD audio volume.

A couple solutions I tested:
 - Keep using SB16, but use `sbmixer = off`
 - Switch to sbpro2 (then you can leave `sbmixer` as-is)
 - Switch to GUS


Here's Staging lastest CI build w/ sbpro2:

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/b927f534-0a44-4ce1-8e70-b4bc890c09e0

**Comment by weirddan455** [comment] 2024-06-06 17:35
>  Looks like the game is using the SB16's mixer to turn down the CD audio volume.

Nice find.  I was trying to do a bisect but it broke many years ago, probably in a DOSBox SVN commit.  It was using autotools build system back then and, while I was able to compile 0.74 from source, a lot of the intermediate commits won't build so I'm not able to do a proper bisect.

**Comment by weirddan455** [comment] 2024-06-06 18:19
OK, pretty sure it's just this commit.  Found by looking at `git blame` after @interloper98 narrowed down what the problem was.  It's a commit from 2010 that's implementing Soundblaster CD audio mixer support and never made its way into DOSBox 0.74_3 so that version only works because setting CD volume this way wasn't implemented.

d7597b8dd86b0e861d17edd9fbd1c6d06b6c4a31

Unclear if this is actually a DOSBox bug or a game bug.  The game is writing into the Soundblaster port telling us to set CD audio volume to 0 and we're doing what it asked :man_shrugging: 

Maybe there's an emulation inaccuracy somewhere but if there is I can't find it at the moment.

**Comment by interloper98** [comment] 2024-06-06 18:21
Glad it wasn't a real regression, @weirddan455! Thanks for confirming on the code side.

**Comment by interloper98** [comment] 2024-06-06 18:25
Other games use the sb16's CT mixer to very precisely control music vs. voice volume; such as turning down the music during speech sequences. 

So I suspect it's just a game bug (maybe the devs only had an sbpro or GUS).

**Comment by interloper98** [comment] 2024-06-06 20:48
> Unclear if this is actually a DOSBox bug or a game bug. The game is writing into the Soundblaster port telling us to set CD audio volume to 0 and we're doing what it asked 🤷‍♂️

> Maybe there's an emulation inaccuracy somewhere but if there is I can't find it at the moment.

@weirddan455 , here's a recording of Warcraft 2 using the SB16's mixer to control the CDROM's volume. From what I can hear, the range of volumes sounds perfect to me:

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/59ac25da-3084-4921-8341-fa84bc6c53ff

This test is at least one check toward DOSBox being correct. I can't recall other games with this CD-music volume control feature - but sure there are more.

**Comment by weirddan455** [comment] 2024-06-06 21:33
@interloper98 I tested Warcraft II with some log statements added to the code.  It's actually using MSCDEX to control CD audio volume, not the Soundblaster's mixer.  You can set `sbmixer=false` and that volume slider still works.  Even the digital volume slider doesn't seem to use the mixer.

Quake is another game that has a CD audio slider but it also uses MSCDEX and doesn't appear to touch the Soundblaster mixer at all.

Finding a game that actually uses Soundblaster mixer would be a data point but the problem with Wingstar could be something more subtle like we're reporting a wrong value somewhere else and that's making it mute CD audio.  Or it could just be a buggy game.  You'd probably have to test on a real SB16 to know for sure.

**Comment by johnnovak** [comment] 2024-06-06 21:42
> You'd probably have to test on a real SB16 to know for sure.

I can test it on my AWE32 which is basically an SB16 plus "extras". Also en my ESS which emulates the SB Pro.

Better than nothing, I guess.

**Comment by johnnovak** [comment] 2024-06-06 21:53
List of DOS games that use CD Audio in some form (by kcgen):

https://www.vogons.org/viewtopic.php?p=673031#p673031

**Comment by weirddan455** [comment] 2024-06-06 22:19
Worth noting if I change the in-game setup to use any of the other Sound Blaster settings, CD audio plays fine (it doesn't even attempt to write to the port to mute it) but the sound effects don't play, even I change `sbtype` in DOSBox config to match.  Only Sound Blaster 16 works.

![image0001](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/94f56ec6-a291-499a-88fc-0ce007a75f65)

Setting `sbmixer = off` is a good work-around though.  I was looking into this thinking it was a CD audio bug, which I had gotten fairly familiar with working on but it's looking more like a potential Sound Blaster bug which I'm not as familiar with.

**Comment by interloper98** [comment] 2024-06-06 22:58
>  It's actually using MSCDEX to control CD audio volume

@weirddan455 -- great find! I guess we still need to find a game that tweaks the CD volume via SB mixer.  

@johnnovak ; damn... That's a huge stack of CD audio games to dig through 😌. I've played some of them; will try to remember if any offered volume control.

**Comment by Python-Exoproject** [comment] 2024-06-07 03:20
Thanks @interloper98 Ive used sbmixer=false which worked, so as far as eXoDOS is concerned this is resolved as we have a solution.

**Comment by interloper98** [comment] 2024-06-07 06:48
@weirddan455 , seeing as Warcraft II and Quake both used MSCDEX, I wanted to find you a couple more that positively use the SB16's mixer to control the CD volume.

Here are four confirmed (tested by disabling the sbmixer), with Staging-specific confs that you can drop in if you extract these zips from the eXoDOS pack.

(With these custom confs, I'm just launching from the console)

<details>

<summary>Chasm - The Rift (1997)</summary>

```ini
# No setup needed; game auto-detects SB16 on startup.
# Adjust CD audio in Options -> CD Volume.
# The initial 80% CD music volume is pretty quiet, but
# still audible if you turn up the volume.

[dosbox]
memsize = 63

[cpu]
core = dynamic
cpu_cycles_protected = 120000
cpu_throttle = true

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = sb16
sbmixer = on

[autoexec]
mount c .
imgmount d cd\CHASMPR.cue -t cdrom
c:
cd chasm
chasm
```

</details>

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/be45d128-ba98-446c-80dd-131d8a5af633

<details>

<summary>Operation Body Count (1994)</summary>

```ini
# Skip the intro scenes and start a new game.
# (You need to start a game to get the CD music underway).
# Press ESC to go back to the main menu, then up arrow and select 'Audio Mix'
# Arrow down to 'CD Music' and hold right-arrow max out its volume.
# Do the same for the 'Master volume', at which point you'll hear the CD music.

[cpu]
core = dynamic
cpu_cycles = 15000

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = sb16
sbmixer = on

[autoexec]
mount c .
imgmount d CD\BODYCOUNT.cue -t cdrom
c:
cd BCCD
call BC CDMUSIC
```

</details>

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/3516669b-e3ba-4004-9a76-f48c117c3c17

<details>

<summary>Terra Inc (1997)</summary>

```ini
# At the main menu, click the lavender music
# icon off then on to reset the music.
# Then you can adjust the music volume using
# the lower scale.

[dosbox]
memsize = 63

[cpu]
core = dynamic
cpu_cycles_protected = 30000
cpu_throttle = true

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = sb16
sbmixer = on

[autoexec]
mount c .
imgmount d CD\TerraInc.cue -t cdrom
c:
CD TERRAINC
autotype -w 3 right enter , enter , left enter x
SETSND
TERRAINC
```

</details>

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/75ac0feb-056f-4a18-a41b-a85ada5bc617

<details>

<summary>WipEout (1995)</summary>

```ini
# Game auto-detects SB16.
# CD audio is playing from the start.
# Volume can be adjusted from the main menu.

[dosbox]
memsize = 63
dos_rate = 60
vmem_delay = 600

[cpu]
core = dynamic
cpu_cycles_protected = 120000
cpu_throttle = true

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = sb16
sbmixer = on

[autoexec]
mount c .
imgmount d cd\Wipeout.cue -t cdrom
d:
cd
cls
call wipeout.bat
```

</details>

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/1613072d-a0cc-46ea-81d3-77eae2230bba

**Comment by interloper98** [comment] 2024-06-26 04:22
Recommend we close this one as the CDDA audio works however the game is just turning down the CDDA volume using the SB16's mixer IO control.

`sbtype=sb16 + sbmixer=false` are both `sbtype=sbpro2` working options.

**Comment by weirddan455** [comment] 2024-06-26 05:24
There's a good change there's still an emulation inaccuracy here.  `sbmixer = false` is a good workaround so it's not game-breaking anymore but that is a convenience setting that doesn't reflect real hardware.  On a real SB16, the mixer would always be on (as far as I know) so why is the game muting its own music tracks?  Does it do that on real hardware or are we doing something wrong?

**Comment by interloper98** [comment] 2024-06-26 05:30
I think the fact that the above 4 games have good cdda volume control via the SB ctmixer across the entire volume range at least has me confident that the emulation side is correct and that this one game is buggy.

My hunch is that developer owned an sbpro and only coded the sb16 compatibility without testing.

Another thought is that the developer had an sb16, but used a direct audio out from the cdda drive instead of feeding audio through the sb16 where it can cut the volume.

(Totally agree that verification on hardware is the best though, provide we know the CDROM is routed through the sb16).

**Comment by johnnovak** [comment] 2024-06-26 06:14
> I think the fact that the above 4 games have good cdda volume control via the SB ctmixer across the entire volume range at least has me confident that the emulation side is correct and that this one game is buggy.
> 
> My hunch is that developer owned an sbpro and only coded the sb16 compatibility without testing.
> 
> Another thought is that the developer had an sb16, but used a direct audio out from the cdda drive instead of feeding audio through the sb16 where it can cut the volume.
> 
> Maybe ran the miniplug output to their stereo or headphones:
> 
> ![Screenshot_20240625_224754](https://private-user-images.githubusercontent.com/165201780/343024594-e21abf0d-c4ce-4887-957d-ec2260ef5ca9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODE4NjIsIm5iZiI6MTcxOTM4MTU2MiwicGF0aCI6Ii8xNjUyMDE3ODAvMzQzMDI0NTk0LWUyMWFiZjBkLWM0Y2UtNDg4Ny05NTdkLWVjMjI2MGVmNWNhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNTU5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmIzY2YxZmRlYTI5ODc2ZWE2ZWUxYTZmYTU0ZDIwNWMwMzlmMjA1YWU2YzU1NTg4YWMwMzg0YzgwOWUxMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VGfWDNQvmUD3cQtIYrNPsksPZ3Q1u7U0wWHy59L-T1I)
> 
> (Totally agree that verification on hardware is the best though if we're sure the CDROM's audio is routed through the sb16).

I'm kinda learning towards this explanation, yeah, and conclude that the game is buggy.

Pretty challenging to find working CD-ROM drives with CD audio support these days to test on real hardware 😅

**Comment by interloper98** [comment] 2024-06-26 07:41
Added logging around every access of ctmixer's CDA volume value (reads and writes).

When `sbtype = sb16`, the game reads the CDDA left and right volumes and (regardless of what it gets back) always follows that by writing a zero value to the CDDA left and right volumes:

```
SB16: Resetting DSP
ctmixer_read at line 2687: IO index 0x36: Read SB16 left CDDA volume value 0xf8
ctmixer_read at line 2701: IO index 0x37: Read SB16 right CDDA volume value 0xf8
ctmixer_write at line 2464: IO index 0x36: Write SB16 CDDA volume left value 0x0
ctmixer_write at line 2478: IO index 0x37: Write SB16 CDDA volume right value 0x0
```

It does that before the intro screen. It doesn't do any more CDDA IO reads or writes after this.

When `sbtype = sbpro2`, the games neither reads nor writes CDDA volumes. It only performs a DSP reset and carries on to its intro and then into the game:

```
SB16: Resetting DSP
```

I looked through the Sound Blaster programming guide https://pdos.csail.mit.edu/6.828/2018/readings/hardware/SoundBlaster.pdf
 and noticed we're missing ctmixer IO index 0x3c, called "Output mixer switches (SB16)".

This lets the program selectively turn the line, CD, and mic paths on or off so they're included or excluded from the analog mixing path:

bit 4 - Line.L on/off
bit 3 - Line.R on/off
bit 2 - CD.L on/off
bit 1 - CD.R on/off
bit 0 - Mic on/off

Adding logging for this in the `ctmixer_write` switch:

```c++
case 0x3c: // Output mixer switches (SB16)
	if (sb.type == SbType::SB16) {
		LOG_MSG("%s at line %d: IO index 0x3c: Output mixer switches (SB16) value 0x%x",
		        __FUNCTION__,
		        __LINE__,
		        val);
	}
	break;
```

Rerunning the game with this:

```
SB16: Resetting DSP
ctmixer_read at line 2687: IO index 0x36: Read SB16 left CDDA volume value 0xf8
ctmixer_read at line 2701: IO index 0x37: Read SB16 right CDDA volume value 0xf8
ctmixer_write at line 2464: IO index 0x36: Write SB16 CDDA volume left value 0x0
ctmixer_write at line 2478: IO index 0x37: Write SB16 CDDA volume right value 0x0
ctmixer_write at line 2507: IO index 0x3c: Output mixer switches (SB16) value 0x0
```

Lol. So the game not only sets the CD left and right volumes to 0, but it then completely shuts off the CD from the mixing output. So it's a double-whammy!

I have no doubt the game would mute and disable the CD on a real SB16 too looking at these port writes!

Here's the log patch file: [log_sblaster_cdda_io.patch.zip](https://github.com/user-attachments/files/15984045/log_sblaster_cdda_io.patch.zip)

Run `git apply /path/to/patch` when inside your source root.

**Comment by johnnovak** [comment] 2024-06-26 08:36
Nice detective work @interloper98 🕵🏻‍♂️ That's enough evidence to conclude this is a game bug.

Well, to their credit, they made sure the CD Audio output is _really_ muted for good 😎 

Unless someone can prove the game doesn't completely mute the CD Audio output on Sound Blaster 16 on real hardware (highly unlikely), we can conclude the emulation is not at fault, so closing.

Please just use `sbtype = sbpro2`.

**Closed by johnnovak** 2024-06-26 08:36 UTC
Labels: not a bug, game compatibility, audio
