### ISSUE TITLE
Mouseclick doesn't work in Day of the Tentacle CD

### ISSUE THREAD

**Issue by Max833** [dosbox-staging/dosbox-staging#1835] opened 2022-08-07 00:04 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0-alpha-1085-g1a771

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7 3770k, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Install and start the game (choose mouse support!). The mouse movement is working, but it doesn't response to a click. I have the german cd version.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Max833** [comment] 2022-08-07 10:57
[conf.zip](https://github.com/dosbox-staging/dosbox-staging/files/9276636/conf.zip)

**Comment by FeralChild64** [comment] 2022-08-07 19:42
Looks like a regression after https://github.com/dosbox-staging/dosbox-staging/commit/9a42619611c62bdb35b948bc93720096be751615 - thank you for spotting it.

A temporary workaround, until I fix this, would be to launch a CtMouse driver before starting the game.

**Comment by Max833** [comment] 2022-08-08 16:09
Thank you! I have downloaded an older version for now.

**Comment by FeralChild64** [comment] 2022-08-08 21:23
@Max833 With commit https://github.com/dosbox-staging/dosbox-staging/commit/891d79e08efffbadfb638dbf9b3b8dd26b2eddae the problem should be fixed. Can you confirm?

**Comment by Max833** [comment] 2022-08-09 16:09
@FeralChild64 It is working perfectly now with v0.79.0-alpha-1109-g4b73

Thank you!

**Closed** 2022-08-09 16:09 UTC
Labels: regression
