### ISSUE TITLE
GUS Incorrect sounds occur during some Star Control 2 DOS themes

### ISSUE THREAD

**Issue by marsej** [dosbox-staging/dosbox-staging#1530] opened 2022-01-15 19:37 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging version 0.78.1

### What Operating System are you using?

Windows 10

### Relevant hardware info

4790k, gtx 760, ALC1150

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There are couple occurrences of sounds that should not happen during introduction music from approx 25 to 45 seconds into the intro with starcon2.exe /s:gravis, with or without following settings.bat that do not occur when soundblaster is used instead.

SET ULTRASND=240,5,5,3 
rem I found a post saying that SC2 doesn't like the extra ,3 there but it didn't have any effect removing it.
starcon2 /s:gravis
SET ULTRASND=240,5,5,3,3

Sound quality is great on this GUS emulation otherwise. I came to find staging-build because Dosbox Optionals I also used had issues with GUS sound popping on mididemo.bat and SC2. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run starcon2 /s:gravis
2. Wait for music to start
3. Wait 25 seconds from intro music starting
4. Listen/record for 20 seconds
5. Switch to SoundBlaster and repeat from 1 then compare that section. Didn't hear any incorrect sounds on SB.

The incorrect sounds sound like a lowish "brrrrrt brrr brrrrt".

edit/update:
6. Change GUS DMA to 5 and now the "brrrt" sounds are gone but there is glitching sounds about 39 seconds into the intro on every lead-stab. I found a page with real GUS recording and it does not have that glitching: 
 http://nerdlypleasures.blogspot.com/2016/10/reasons-for-owning-gravis-ultrasound.html

### Your configuration

```ini
https://gist.github.com/marsej/9f2b938ffbd2d93e06f7526d8ee7a709
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by marsej** [comment] 2022-01-15 19:39
Changed the IRQ to match the GIST conf. I had it correctly in DOS but copy pasted the .bat from another place which had wrong IRQ.

**Comment by marsej** [comment] 2022-01-15 19:48
Well well, I changed DMA to 5  (/s:gravis) like somewhere else was suggested and now instead of "brrrt brrr" sounds I get some sort of temporal glitching, can't explain it, it starts happening 40 seconds from where the intro music starts and happens approx every 5 seconds when the lead sound kicks in. The lead sounds beginning is subtly garbled up temporally or something.

**Comment by kcgen** [comment] 2022-01-15 20:08
Make a local  `dosbox.conf` (inside your Star Control 2 directory), withe following settings:

``` ini
[cpu]
core=dynamic
cycles=max 95% limit 30000

[midi]
mididevice = none

# Star Control II needs DMA 5
[gus]
gus=true
gusdma=5

[sblaster]
sbtype=none

[speaker]
pcspeaker=false
tandy=off
disney=false

[dos]
xms=true
ems=true
umb=true
```

Then launch and ensure it's using the conf file. Look for log lines like:

``` text
2022-01-15 12:07:02.955 | CONFIG: Loaded primary conf file /your/home/directory/config/dosbox-staging.conf
2022-01-15 12:07:02.955 | CONFIG: Loaded local conf file dosbox.conf
```

Curious if that helps.

**Comment by marsej** [comment] 2022-01-15 20:18
It still glitches with your conf but it's so subtle that I'm many would not note.
I found this page:
http://nerdlypleasures.blogspot.com/2016/10/reasons-for-owning-gravis-ultrasound.html
at 0m:48s the lead sound I'm talking about kicks in and is flawless, no subtle glitching.

**Comment by marsej** [comment] 2022-01-15 20:25
Correction: The glitch occurs in the sounds that occur at 0:39, 0:44, 0:49 etc.

**Comment by kcgen** [comment] 2022-01-15 20:34
Here's what I'm getting (Ctrl + F7 to record .avi or Ctrl+F6 record .wav file).

![2022-01-15_12-24](https://user-images.githubusercontent.com/1557255/149636632-e77b393b-86b6-4b0c-9437-23c1a85c3f2a.png)

https://user-images.githubusercontent.com/1557255/149636865-75b2df91-9332-4501-9d3b-364d1a71d93c.mp4

[sc2.flac.zip](https://github.com/dosbox-staging/dosbox-staging/files/7875849/sc2.flac.zip)

**Comment by marsej** [comment] 2022-01-15 20:41
I'm talking about the introduction music that's before the copy protection with the timestamps mentioned. I haven't yet listened for more music than that with this new emulation.

**Comment by marsej** [comment] 2022-01-15 21:22
Put a loop around 46-49 seconds into both of these files and compare. Needs critical listening - there's couple glitches per stab.

[GUS_sc2_intro_garbling_in_stabs_47-48_seconds_and_repeats.zip](https://github.com/dosbox-staging/dosbox-staging/files/7875903/GUS_sc2_intro_garbling_in_stabs_47-48_seconds_and_repeats.zip)
[SB_sc2_intro__no_glitches.zip](https://github.com/dosbox-staging/dosbox-staging/files/7875907/SB_sc2_intro__no_glitches.zip)

**Comment by marsej** [comment] 2022-01-16 04:06
It sounds like there's a whole other class of issue with the green Ur-quan music that comes up when (in the game) the probe meets you when going to earth. (after copy protection). 

This is easily heard difference, it's almost as if incorrect instrument was being used! How is this even possible?

[GUS_urquan_weirdness(emu).zip](https://github.com/dosbox-staging/dosbox-staging/files/7876359/GUS_urquan_weirdness.emu.zip)

[SB_no_urquan_weirdness(emu).zip](https://github.com/dosbox-staging/dosbox-staging/files/7876360/SB_no_urquan_weirdness.emu.zip)

and at 2m:20s in the first example here with real GUS it sounds perfect: http://nerdlypleasures.blogspot.com/2016/10/reasons-for-owning-gravis-ultrasound.html

**Comment by marsej** [comment] 2022-01-16 04:32
This victory ditty after melee is completely broken: 

I'm launching the game with this .bat file (I added ultrinit but it doesn't make a difference): 

SET ULTRASND=240,5,5,5
c:\ultrasnd\ultrinit.exe
starcon2 /s:gravis
SET ULTRASND=240,5,5,5,5
(I also tried settings from http://nerdlypleasures.blogspot.com/2016/10/reasons-for-owning-gravis-ultrasound.html but it made no difference)

[GUS_ditty_completely_broken(emu)_at_2m10s.zip](https://github.com/dosbox-staging/dosbox-staging/files/7876383/GUS_ditty_completely_broken.emu._at_2m10s.zip)

The Ilwrath theme that plays before starts making weird sound at 22 s. The sound ends at 38 s.

**Comment by marsej** [comment] 2022-01-16 05:09
I tried again Dosbox Optionals with the old GUS code (lower quality and popping), there's no incorrect sounds there (on the green Ur-quan theme (occurs when probe hits you going to earth) ! So something about the new GUS emulation in Staging is not right.
Also the ditty plays correctly.
[GUS(old_emul)_correct_sounds_but_worse_quality.zip](https://github.com/dosbox-staging/dosbox-staging/files/7876426/GUS.old_emul._correct_sounds_but_worse_quality.zip)

**Comment by kcgen** [comment] 2022-01-16 08:45
> It sounds like there's a whole other class of issue with the green Ur-quan music that comes up when (in the game) the probe meets you when going to earth. (after copy protection).
> 
> This is easily heard difference, it's almost as if incorrect instrument was being used! How is this even possible?
> 
> [GUS_urquan_weirdness(emu).zip](https://github.com/dosbox-staging/dosbox-staging/files/7876359/GUS_urquan_weirdness.emu.zip)

> and at 2m:20s in the first example here with real GUS it sounds perfect: http://nerdlypleasures.blogspot.com/2016/10/reasons-for-owning-gravis-ultrasound.html

Apologies @marsej ; I've been struggling to reproduce any of these 

Here's what I'm getting with the current `main` build (no changes to GUS):

### GUS with Low DMA (`gusdma = 5`)

Conf file: [sc2.conf1.txt](https://github.com/dosbox-staging/dosbox-staging/files/7876589/sc2.conf1.txt)

https://user-images.githubusercontent.com/1557255/149652811-f4c6f087-dd21-4377-b762-7e28ae928efb.mp4

### GUS with High DMA (`gusdma = 5`)

Conf file: [sc2.conf2.txt](https://github.com/dosbox-staging/dosbox-staging/files/7876588/sc2.conf2.txt)

https://user-images.githubusercontent.com/1557255/149652808-d1a61d1b-26c9-4dbf-99bf-adbe34d4c4af.mp4

---

Can you try either of the above conf files and nothing more? (ie: please **_don't_** load c:\ultrasnd\ultrinit.exe or SET ULTRASND=240,5,5,5,5. )

**Comment by marsej** [comment] 2022-01-16 09:49
I tried both your new conf files alone (had to rename dosbox-staging.conf to dosbox-staging0.conf to stop it from loading) using -conf switch.
Then I made following modification:

[autoexec]
mount c ..\dosboxopt\Dosbox\HDD-D
c:
cd starcon2
rem starcon2.com
starcon2.exe

I do not have starcon2.com at all. I installed from floppy images and use the map manually to answer the copy protection question. If you google: archive star control 2 ibm pc floppy image
you should get same installation files. And use the .exe to start. Can you get a repro with those files?

In another news, on Dosbox Optionals I got the music working without popping with the DMA change using same game files, only issue with optionals-build is that I get popping sounds in recording still but not anymore otherwise and I'm not sure if the panning is as wide-sounding (even with Pantable=accurate) as with Staging.

I read there are differences between SC2 floppy and CD versions executables that can mess up GUS somehow but these files work in Optionals-build so I'm not sure what to say.

**Comment by marsej** [comment] 2022-01-16 10:03
Forgot to say in previous comment that using your conf files the result was same as before (garbled intro stab, incorrect instr. in ur-quan theme).

**Comment by marsej** [comment] 2022-01-16 11:25
latest, to keep things interesting, very interesting indeed: 
all with DMA 5 IRQ5:

dosbox optionals:
in SC2CD, gusexe.bat with manual protection doesn't have popping in green ur-quan (probe) theme. Sounds perfect but records with pops (ctrl+f6).
in SC2CD, guscom.bat with no protection has popping in green ur-quan (probe) theme.
in SC2CD, starcon2.com with no protection has random sound effects played in middle of the music.

dosbox staging:
in SC2CD, starcon2.com with no protection has popping sounds in music
in SC2CD, starcon2.exe with map protection has incorrect sounds in green ur-quan (probe) theme.

gusexe.bat:
SET ULTRASND=240,5,5,5
c:\ultrasnd\ultrinit.exe
gusclear.exe
starcon2.exe /s:gravis
SET ULTRASND=240,5,5,5,5

guscom.bat (same as above with starcon2.com that skips protection)

**Comment by kcgen** [comment] 2022-01-16 13:03
Can you please attach the floppy images or a zip of your post-installed folder. I have the CD version. Thanks.

**Comment by marsej** [comment] 2022-01-16 13:05
Here, click the 7z https://archive.org/download/001005-StarControl2

**Comment by kcgen** [comment] 2022-01-19 03:49
@marsej, thanks for the detailed and methodical comparisons!

Can you try the binary here: <https://github.com/dosbox-staging/dosbox-staging/actions/runs/1715987919>

It includes a couple of GUS changes as well as another nice community patch that was authored by Peter Ferrie and discussed w/ ripsaw8080 here:  https://www.vogons.org/viewtopic.php?t=28331

This adjustment uses the original EMM386.EXE approach to preventing wrapped memory-access during DMA transfers, which you will notice SC2 has some (these are the `segbound wrapping (read): 20000:1ffff size 1 [1] wrap ffff` messages).

I can still here very faint periodic tiny pops - but I also noticed when I turn up the sound-cloud recording to equal volume, it has (roughly?) similar pops.  So it could very well be game-induced or par of the internal PCM content.  (certainly there are many other GUS mod-tracker style games that don't exhibit this).

Curious what you find!

**Comment by marsej** [comment] 2022-01-25 09:09
Great! With the starcon2.com (CD version) the music is fine now, I only got a couple instances of issues but I can't repro them reliably. I used save games to check most of the music.

**Comment by marsej** [comment] 2022-01-25 09:18
I found that with the binary you gave at
https://github.com/dosbox-staging/dosbox-staging/actions/runs/1720203247

the c:\ultrasnd\mididemo.bat has incorrect instruments/no instruments playing. Can you repro that?

**Comment by kcgen** [comment] 2022-01-25 18:21
Thanks for these checks, @marsej.  Repro'd.
New build underway: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1747047586
(Hopefully this is it!)

**Comment by kcgen** [comment] 2022-01-25 18:24
> Great! With the starcon2.com (CD version) the music is fine now, I only got a couple* instances of issues but I can't repro them reliably. I used save games to check most of the music. (* I found 5 instances of music issues within 3 hours of playing so if I could repro them more reliably they might be worth investigating)

Thanks- to give the team more regression test points, would you be able to zip your savegames?
If you edit a new response here, you can drag n' drop zip files straight away (25 MB/attachment).

**Comment by marsej** [comment] 2022-01-27 20:31
Here's notes, I included some other games that are well known for good GUS (native sup.) music.
---
OMF2097 OK sharew. https://archive.org/download/omf20_zip

epic pinball demo - intro/menu OK, table1(android) maybe little popping at beginning of track http://cd.textfiles.com/cream/cream06/games/pinbal2.zip

ISDEMO popping in the beginning of intro http://cd.textfiles.com/cream/cream06/games/isdemo.zip
ISDEMO popping in the beginning of planet scan music - Start game by loading a save file then click "Sci" and click the round yellow icon on blue backround (it says "planet scan" when hovering over it)

SC2:

SAVE 11 alpha164 sc2cd com & sc2flp exe kohr-ah music pops audibly throughout the theme, no popping with SB16

SAVE 25 alpha164 sc2cd com & sc2flp exe talking pet pops and instance of random drums playback that doesn't belong in the theme
- in this theme the pops are visible in the ingame-waveform/oscilloscope at bottom right of screen as visual step-ups of the waveform when the popping occurs
- them random drum sound is not visible in the ingame-waveform/oscilloscope at bottom right of screen 
- pops with SB16 too

- pops not heard here 26m52s (though the theme plays for short amt of time so hard to be sure) https://www.youtube.com/watch?v=1PHswZKY-l8

SAVE 26 (Use DEVICE/Burvix Caster to initiate Chenjesu theme) alpha164 sc2cd com chenjesu garbled sounds/popping
- pops with SB16 too

Same saves should work for CD & floppy version.

[SC2SAVES.zip](https://github.com/dosbox-staging/dosbox-staging/files/7953606/SC2SAVES.zip)

**Comment by kcgen** [comment] 2022-01-29 01:23
Thanks for these @marsej.

I've added one last change in: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1764400178

This leverages the audio enveloper to tamp-down samples that make huge back-to-back jumps within the GUS signal - however many of the pops you're now catching involve SC2's internal mod player injecting a bias or audio-offset (and you've also flagged those in the SB16 output too). 

You can see it when SC2's spectrum analyzer graph jumps vertically.  That's in the data itself, and unfortunately, it's not a large enough jump for us to "scrub off" with the enveloper.  Well, if I set the enveloper tight enough to dampen those pops - then it also dampens legitimate audio signals like cymbal crashes and drum hits - which we don't want).

So I think we're close to the end of the line w/ SC2.  I believe the only options left are to fix its the internal mod player or the mod files themselves, so they avoid those offset jumps.

(I also noticed that the hardware GUS recording (on Sound Cloud) also contains pops when I turn up the volume and listen closely.)

**Comment by marsej** [comment] 2022-01-29 02:50
Hmm Those songs your video includes were fine to my ears already, the problematic ones are (the new build still pops with these):

"ISDEMO popping in the beginning of planet scan music - Start game by loading a save file then click "Sci" and click the round yellow icon on blue backround (it says "planet scan" when hovering over it)"

"SC2: SAVE 11 alpha164 sc2cd com & sc2flp exe kohr-ah music pops audibly throughout the theme, no popping with SB16"

**In both, with SB16 there's no popping.**

I found this bug report:
https://github.com/joncampbell123/dosbox-x/issues/500

Which suggested there would be an option implemented to eliminate popping even though the HW does it but it seems it hasn't been implemented yet.

**Comment by marsej** [comment] 2022-01-29 02:57
Here's the affected songs. It's only two songs so maybe not worth the effort ...

[alpha166 isdemo planet scan pops at 25sec.zip](https://github.com/dosbox-staging/dosbox-staging/files/7962847/alpha166.isdemo.planet.scan.pops.at.25sec.zip)
[alpha166 sc2cd kohr-ah pops throughout the theme.zip](https://github.com/dosbox-staging/dosbox-staging/files/7962848/alpha166.sc2cd.kohr-ah.pops.throughout.the.theme.zip)

**Comment by kcgen** [comment] 2022-01-29 03:15
> Which suggested there would be an option implemented to eliminate popping even though the HW does it but it seems it hasn't been implemented yet.

Staging has had a lot of changes to try to improve audio (and GUS), throwing any care for strict emulation out the window.

We're already preventing all forms of wrap-around using floating point accumulation at the voice-level, and then soft-limiting that floating point signal to contain it within the 16-bit range. If you capture the WAV output file and inspect the waveforms, you will see no discontinuities that jump from the positive side into the negative side.

This PR adds more pop protection for samples that stay stay within bounds, but are jumping by a large amount. It works for those -- but to scrub the remaining pops that you're noting here would simultaneously muffle high frequency signals.

**Comment by kcgen** [comment] 2022-01-29 03:25
Here's an example for  the Kohr-Ah theme, when I tighten Staging's enveloper even more:

![2022-01-28_19-18](https://user-images.githubusercontent.com/1557255/151645439-0984ee80-9878-4fb3-908a-659edbfd0dd6.png)


https://user-images.githubusercontent.com/1557255/151645500-5ae8e626-35cc-4aec-a8f3-bc631f620549.mp4

If you think that's an improvement, we could offer a knob to adjust the envelope strength?

I personally find pops to get very exhausting - to the point where they will ruin the entire experience for me (especially w/headphones or earbuds).  So I can see the benefit of trying to eliminate them, even if it means some high-frequency tones will have to be scrubbed a bit.  It's really the lesser of two evils (depending on ones' preferences).

**Comment by marsej** [comment] 2022-01-29 09:23
That scrubbing sounds quite aggressive. It should be possible to sacrifice some cpu perf to actually look-up the incoming data for pop-patterns in the audio buffer and then eliminate them on the fly for recognized patterns. That could be combined with a pattern from the executable name so that the feature that does audio pop-pattern elimination is only turned on when specific name executables are run.

**Comment by kcgen** [comment] 2022-01-29 10:01
If there's a general way to detect and remove low amplitide micropops amidst high db, noisy samples in an environment where you can only see the current (and older) samples - then sure; such a general approach could be used universally. 

If you can inspect your WAV recordings in a tool that lets you see the waveforms (audacity), visually find the pops, come up with an amplitude pattern that fits the pops but won't also match a large number of high db noise-like signals (say, like the pkunk drum hits), then we'll have a general pop eliminator. 

My take is that this is non-trivial. Even commercial pop reducers expect a significant deviation from the baseline characteristics (and some use significant deadhead to make Fourier transforms).

**Comment by marsej** [comment] 2022-01-29 10:40
Another game with incorrect sounds playing at seemingly random time: **Descent 1**.
In this hardware recording there's no issues:
https://www.youtube.com/watch?v=yg1zJAomL4E&t=4561s (wait 14 seconds for oddly placed drum sounds)

but this is with alpha 166:
[alpha166 descent shareware v14 repeated drums at 15 seconds.zip](https://github.com/dosbox-staging/dosbox-staging/files/7963499/alpha166.descent.shareware.v14.repeated.drums.at.15.seconds.zip)

**Comment by marsej** [comment] 2022-01-29 10:44
Here's descent 1 v1.4 shareware:
http://ftp.funet.fi/pub/msdos/games/interplay/desc14sw.exe (it's a zip-exe)
It's possible the hw recording linked above uses a different version or something.

**Comment by marsej** [comment] 2022-01-29 11:07
re: "general way of detecting pops", you are right assuming the volume/amp is software mixed I think and player modifiable. I wrote that comment hoping the games would always send same data to the GUS regardless of volume, so that you could just create something like:
starcon2.com { hex array }
so that when starcon2.com is running, if hex array matches a sample incoming at some of the gus channels, then process that sample to eliminate the pop.

**Comment by kcgen** [comment] 2022-01-29 17:19
> re: "general way of detecting pops", you are right assuming the volume/amp is software mixed I think and player modifiable.

GUS-native games, like SC2, start by writing raw PCM samples (8-bit or 16-bit) into the GUS's memory banks. Those memory regions are associated with GUS 'voices', that the game commands the GUS to play simultaneously - basically like a mod player or midi player, where the GUS does the work of looping, volume ramping, panning, and mixing of those voices. 

The loading of the PCM samples is done some moments before a song plays. So that's where a hack of this nature could scan for some pattern and then ideally fix the bad samples on-the-spot. That sounds nice and tidy (and perhaps even 'general purpose') on paper..

But... he problem still exists of figuring out patterns to look for to find those micro-blips. I've already dumped those raw loaded samples written by the game in the GUS's memory - and inspected adjacent samples that have large differences between them:

(see description beneath)

![2022-01-29_09-04](https://user-images.githubusercontent.com/1557255/151670142-e7de6265-f5de-4e02-9ff1-2338ae124b93.png)

The `prior A | B` and `current C | D` describe two samples:
 - "Prior" is an output sample that's "interwave" constructed from RAM values A and B
 - "Current" is an output sample that's "interwave" constructed from RAM values C and D

The "diff" value is the magnitude between these two samples. Look at these.. they swing the full 16-bit extent /back-to-back/ and they still don't cause pops when all the voices are accumulated into the final multi-voice stream (which is where the enveloper has proven helpful ..) but taken individually: these swings could cause pops.  So that's why I'm saying the task of finding the "wild" samples is pretty damn hard.. where you're swimming in a sea of samples that already are swinging to both extents.  (have you had any luck pinpointing any micropops in the wav files?)

Also: we don't know what comes after current+1, because that instruction and potential address change haven't been given to us by the game yet.

The best way to fix these would be to dump the mod tracks, fix them using normal audio processing tools, and then re-write them back into the data files. So that effort could be done by some SC2 hacking community.  Although.. at that point, I'm sure UQM is the better approach.

**Comment by kcgen** [comment] 2022-01-29 18:56
> Another game with incorrect sounds playing at seemingly random time: **Descent 1**. In this hardware recording there's no issues: https://www.youtube.com/watch?v=yg1zJAomL4E&t=4561s (wait 14 seconds for (edit: **lack of**) oddly placed drum sounds)
> 
> but this is with alpha 166: [alpha166 descent shareware v14 repeated drums at 15 seconds.zip](https://github.com/dosbox-staging/dosbox-staging/files/7963499/alpha166.descent.shareware.v14.repeated.drums.at.15.seconds.zip)

Here's what I'm getting in descent shareware v14:


https://user-images.githubusercontent.com/1557255/151673887-f31daa52-1f5d-4171-aca0-dbab86a72367.mp4



```ini
[cpu]
core=dynamic
cycles= 30000

[midi]
mididevice = none

[dos]
xms=true
ems=false
umb=false

[sblaster]
sbtype  = none
oplmode = none

[gus]
gus      = true
gusdma   = 5
ultradir = c:\ultrasnd

[speaker]
pcspeaker = false
tandy     = off
disney    = false

[autoexec]
mixer gus 200
mount c .
c:
cd descent
call descent.bat
```

**Comment by marsej** [comment] 2022-01-29 19:26
re: Descent. In your video clip it sounded good to me until 1m14s. I have to find hardware recording for that song to verify it should play like that (it sounds like there's a stale note for a while, on my end I get the same stale sounding note). But even with your config I get those random drums in the introduction music which I linked to previously. The drums are fine in your video clip... Odd. I get same repeat drum issue with Dosbox-X  too.

re: a way to fix pops, maybe:

Some sort of per-sample-scrubber/muter toggle functionality with option to save which sample needs scrubbing into some scrubthese.conf that would store enough bytes from the sample along with exe name to recognize it later. Kinda like SC-155 but instead of midi-channel volume faders you'd have gus sample mute/scrub buttons for users to diagnose popping issues with.

UltraSound Lowlevel ToolKit v2.22 (21 December 1994).pdf Section 3.9 says there are several potential causes of pop sounds so that's another issue... it may be necessary to do more than one kind of scrubbing.

**Comment by kcgen** [comment] 2022-01-29 21:11
I came across mention that some 3rd party GUS MIDI patches (Pro Patches Lite 1.50/1.60/1.61) contained a looping bug in a small number of samples, which have been fixed by the community. 

My guess is your `ULTRADIR=` path is pointing to those affected MIDI patches. 

Here's my bundled shareware 1.4 directory. 

[desc14sw-gusdemo.zip](https://github.com/dosbox-staging/dosbox-staging/files/7964734/desc14sw-gusdemo.zip)

Feel free to toggle the `ultradir` setting in the embedded `dosbox.conf` to compare both sets.

```
[gus]
ultradir=c:\ppl161
# ultrasnd=c:\usnd411
```

**Comment by kcgen** [comment] 2022-01-29 21:21
> UltraSound Lowlevel ToolKit v2.22 (21 December 1994).pdf Section 3.9 says there are several potential causes of pop sounds so that's another issue... it may be necessary to do more than one kind of scrubbing.

very interesting; I haven't heard of this toolkit - will look it up. Thanks for the info, @marsej !

**Comment by kcgen** [comment] 2022-01-29 21:39
> . I found this Yamaha recording where the same notes play but it sounds better: https://www.youtube.com/watch?v=gp0dqcHI8pI

Think of the Gravis as a 32-channel hardware MOD player.  It was revolutionary for mixing that many channels at once, given CPU's at the time couldn't. 

But as a MIDI device, with only 1MB of RAM and sub-44.1 kHz sampling rate (when the majority of channels are used), it's unable to stand up to almost 30-years of software-based MIDI synthesis progression the the form of FluidSynth combined with a high quality Soundfont running at 48 kHz. 

I would suggest reading Staging's MIDI wiki page  and always using FluidSynth instead of the GUS for MIDI playback. It's superior in every way.

**Comment by marsej** [comment] 2022-01-30 00:22
My ULTRASND folder is same that came with Dosbox Optionals here:
https://github.com/MartyShepard/DOSBox-Optionals/releases/download/4397/DOSBox.SVN.r4397.Optionals.Build.on.Dec.25.2020.183550.7z \Dosbox\HDD-C\ULTRASND

Can you try that one to see if you get the same repeating drum issue in Descent intro? btw. Optionals also has Lottes vga glsl shader that I can't figure how to get working on Staging. With some minor I have it looking to some degree closer to what I recall 1991 CRT looking.

re: toolkit, if you didn't find it already try: http://dk.toastednet.org/GUS/SOURCE%20CODE/

**Comment by marsej** [comment] 2022-01-30 00:36
[lottesmodindy.zip](https://github.com/dosbox-staging/dosbox-staging/files/7965062/lottesmodindy.zip)

I tried pasting the screenshot here but it needs to be seen at 1:1 scale and not some zoom level otherwise the crt stuff doesn't look right.

**Comment by marsej** [comment] 2022-01-30 01:00
btw I tried googling for this bug report but google doesn't seem to find this thread. It found this instead:
https://www.vogons.org/viewtopic.php?t=50504
"Though the GUS version sounds more clear, the trumpet sound also sounds very harsh, and 'delayed' as if it misses the first note. There is also some minor crackling/popping. The part starting at 1:10 sounds completely off to me."

Someone in 2016 reported exactly same issues in SC2 w/ GUS. Might want to report back there once done.

**Comment by marsej** [comment] 2022-01-30 01:16
Great, I managed to repro the repeated drum issue. It's because of the files included with Dosbox Optionals ULTRASND folder.

**Comment by grapeli** [comment] 2022-01-30 20:53
Regarding the example presented in this [post](https://github.com/dosbox-staging/dosbox-staging/issues/1530#issuecomment-1024967314).

I can clearly hear the scratching in the recording. The most time is 36.630 to 38.597 seconds.
You can see it in the spectogram. I have marked some of them. There are many more.

![spectrogram](https://user-images.githubusercontent.com/452325/151717345-063132cb-c910-461f-8305-e9f4172e2639.png)

You can try to generate a spectogram with ffmpeg.
`ffmpeg -v quiet -i 151673887-f31daa52-1f5d-4171-aca0-dbab86a72367.mp4 -ss 00:36.630 -to 00:38.597 -lavfi showspectrumpic=s=2048x512:scale=5thrt:win_func=blackman:orientation=vertical:start=250:stop=12000 spectrum.png`

I am surprised by succumbing to the magic of the GUS. It would make sense in the case of real hardware.

Regarding this recording, the actual sampling frequency is maximally up to 8000Hz. You can hear it.
It's really better to use midi, fluidsynth or its equivalent. Using sound fonts from Gravis Ultrasound, such as Gus1live_v12.sf2, eawpats.sf2, Gravis_Ultrasound_Classic_PachSet_v1.6.sf2.
The sound is very similar and the sound quality is incomparably better.

**Comment by kcgen** [comment] 2022-01-31 00:14
@grapeli, these soundfonts are impressive! 

I didn't know there were GUS-equivalent soundfonts that essentially provide a 'remastered' calibe output for those still wishing for an overall GUS experience.  Right on.

**Comment by grapeli** [comment] 2022-01-31 09:01
@kcgen 
Naturally, it may be a matter of taste. I do not urge you to give up using emulated gravis in dosbox.

Your recording sounds generally acceptable to me.
I can only have reservations about the mixer settings, `mixer gus 200`.
It is very risky. Could be the main cause of all the "click/pop" in the bass registers (they are too boosted anyway).

**Closed** 2022-02-01 21:51 UTC
Labels: bug
