### ISSUE TITLE
[BUG][ARM][GCC10.2] segfault when starting games with core = dynamic

### ISSUE THREAD

**Issue by SupervisedThinking** [dosbox-staging/dosbox-staging#844] opened 2021-01-27 16:04 UTC
**Describe the bug**
Once you try to actually start a game it segfaults, the command line itself works fine

Strace output:
https://pastebin.com/PdDNHTF2

**To Reproduce**
compile dosbox-staging for ARM with GCC 10.2, run some stuff

**Expected behaviour**
well it should run the game, works fine on generic x86_64 builds

**Environment (please complete the following information):**
https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/dosbox/dosbox-staging/package.mk

**Version of dosbox-staging:**
latest 

**Configuration parameters:**
https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/dosbox/dosbox-staging/config/dosbox-staging-git.conf

**Additional context**
probably related to:
```
    # Switch to gcc 9 to avoid buggy assembly genetation of gcc 10
    # On armv7l, gcc 10.2 with -O2 on the file core_dynrec.cpp generates assembly that wrongfully passes NULL to the runcode function
    # resulting in a segfault crash. It can be observed by writing block->cache.start to stdout twice where it is NULL at first
    # and then the actual value thereafter. This affects upstream SVN DOSBox as well as this core.
 ```

https://github.com/libretro/dosbox-pure/blob/main/Makefile#L65-L69

**Comment by dreamer** [comment] 2021-01-27 17:13
*Side note: it seems like LibreELEC uses incorrect licensing info for DOSBox Staging, it's **GPL-2.0-or-later** (same licence as DOSBox). Correct it, please.*

@SupervisedThinking Thank you for the bug report! Can you specify exactly what version do you experience the problem on?

Your link says: `PKG_VERSION="`a827baa1b2cddd6cea166cafd6b597c568eac58d`" #v0.76.0+ r4422` - this is a bit contradictory information, as this commit refers to version `v0.77.0-alpha-276-ga827baa1` (on master branch); you can run `git describe` to generate human-readable version info…

I don't know if that's the version you have problem with, because your link points to HEAD in the repo (so you might've changed it already?). Also, it's not "0.76.0+" - you will find stable release at branch `release/0.76.x` (please don't package the unstable version from master for end users).

Have you tested with older GCC versions or Clang to conclude that problem happens exactly with GCC 10? I find it very unlikely that it's a GCC problem, more likely it's an issue similar to #746 (fixed in #800) - except this time on Linux.

> Expected behaviour
> well it should run the game, works fine on generic x86_64 builds

It's not that simple - dynamic recompiler (which *might* be crashing in here, based on strace output) has a separate implementation for x86_64 and for ARM. Lately, our upstream landed a number of changes to dynamic recompiler in SVN trunk.

**Additional info needed**
- What game exactly are you testing - does it crash on start or when launching the game?
- Please post exactly the version you experience the regression on: I presume it's v0.77.0-alpha-276-ga827baa1, but I can't be sure.
- Please test if you can reproduce the crash using new commits on stable 0.76.0 branch: branch name `release/0.76.x`, commit  7499bcc6262d51b19e5c28b6f9716ea209adbefb (v0.76.0-17-g7499bcc6)
- Can you confirm the problem disappears when using GCC 9 or Clang?

**Comment by SupervisedThinking** [comment] 2021-01-27 18:23
It's my personal fork of LE which I maintain for retrogaming & I've fixed the license.

You can start DOSbox & use to terminal to change into the directory but once you start the game you'll end with a segfault. The game was SW Dark Forces but it's doesn't matter. I've tested Doom, Settlers, etc. pp all crash once you start a game or if you try to run other programs like setup.exe.

I thought the package revision should be clear it's https://github.com/dosbox-staging/dosbox-staging/commit/a827baa1b2cddd6cea166cafd6b597c568eac58d my comment is just a sidenote since your last svn merge was based on r4422 & it's 0.76.0+ so after this release.

I used this DOSbox fork too https://github.com/duganchen/dosbox & it also crashed with the latest LE toolchain & worked fine back in the days with older gcc versions. I stumbled uppon this possibility because the dosbox-pure dev mentioned & it makes sense to me because gcc10 "broke" a lot of stuff and needed fixing.

Since the whole toolchain is tailored for gcc10 I can't swap it out easily but back in the days DOSbox-sdl2 worked fine with a gcc 9.2 toolchain https://github.com/5schatten/LibreELEC-RR/blob/master-rr/packages/lang/gcc/package.mk

**Comment by SupervisedThinking** [comment] 2021-01-27 19:54
Strace 0.76.0
https://pastebin.com/Y04paMVj

same result -> I've tried to start SWDF & it failed once you start dark.exe

**Comment by kcgen** [comment] 2021-01-27 20:05
> @SupervisedThinking Thank you for the bug report!

I'll second that; and nice to more ARM platforms in the mix!

> SW Dark Forces, Doom, Settlers

To isolate if it's the dynamic recompiler, could you try specifying `core = normal`? 

Also, could you try real-mode game (say, Space Quest 3) with `core = normal` vs `core = dynamic`?

**Comment by SupervisedThinking** [comment] 2021-01-27 20:49
@kcgen the SBCs are quite nice to play retro games well once the emulator runs properly 😄 

I made some tests as you suggested and indeed

SQ3 0.76.0 core = normal
https://pastebin.com/4Z1Q155Y

DF 0.76.0 core = normal
https://pastebin.com/ALeRX2Vd

SQ3 0.76.0 core = dynamic
https://pastebin.com/HVupMi4n

Strace SQ3 0.76.0 core = dynamic
https://pastebin.com/ET17Gd12

So all in all it looks like games run fine, but slow, if I select `core = normal` but crash once I select ` core = dynamic`

**Comment by SupervisedThinking** [comment] 2021-01-27 23:24
It's most likely a GCC 10 bug:
https://github.com/schellingb/dosbox-pure/issues/8#issuecomment-749634165

@schellingb
maybe you & the dosbox-staging team could team up to fix this or exchange knowledge?

**Comment by schellingb** [comment] 2021-01-28 19:06
GCC 10.2 trips up when compiling for armv7l with -O2. Specifically on the function `CPU_Core_Dynrec_Run`.

If you add two printf's to the code like
```c
printf("1: %p\n", block->cache.start);
printf("2: %p\n", block->cache.start);
static int n = 0; if (n++ > 10) exit(1);
		BlockReturn ret=core_dynrec.runcode(block->cache.start);
```

It will print fun things like
```
1: (nil)
2: 0xaeb531b0
```

Running `gdb -batch -ex "disassemble CPU_Core_Dynrec_Run" core_dynrec.cpp.o >dump.txt` will write out the generated disassembly of that function and it seems like GCC in general has a hard time with that function.

| Compiler settings | Lines of generated assembly | Causes segfault |
| ------------- | ------------- | ------------- |
| g++-10 -O0  | 232| |
| g++-10 -O1  | 4620| |
| g++-10 -O2  | 4992| Yes |
| g++-10 -O3  | 163 | |
| g++-9 -O0  | 232| |
| g++-9 -O1  | 4619| |
| g++-9 -O2  | 163| |
| g++-9 -O3  | 210| |

O2 in GCC10 being the largest certainly is curious. Although both versions generating fairly large output on O1 also seems not great (but neither causes the null pointer segfault like GCC10 on O2).

I tried to bring up the issue in the official GCC IRC channel but got no response. At the time I was busy with releasing my project so I couldn't bring myself to register on the Bugzilla tracker and just resorted to using GCC9 for now.

**Comment by kcgen** [comment] 2021-01-28 20:02
@schellingb, excellent thorough investigation! 

Thank you also for expanding you analysis with gdb and assembly LOC tallieS versus optimization levels.

Very interesting that v10 -O3 and v9 -O2 both produce 163 LOC while v10 -O2 balloons 30-fold and sequential printf's show the null (despite the core not being multithreaded). Ouch. 

PVS static analysis has habitually flagged the dynamic core as being excessively complex, so even though this is no doubt an issue with GCC, certainly the complexity might be part of the problem.

When time permits, I will poke around with minimal restructuring and see if it changes 10's output. 

Will also relay to qbix and jmarsh via vogons PM.

**Comment by SupervisedThinking** [comment] 2021-02-08 11:15
@dreamer you should receive an email soon about a dev device, I guess you'll sort out the details then yourself 👍🏻 
@kcgen I've passed his mail address because it was public

**Comment by kcgen** [comment] 2021-02-08 11:27
@SupervisedThinking , that's amazing news! 👍 Thank you for your support, and pass our appreciation to the PINE64 crew!

My info can be found in several copyrights if you `git grep gmail` the source. My name / nic pattern will be obvious :-) when you see it, send an email and I will reply.  Regards.

**Closed** 2021-03-27 13:12 UTC
Labels: bug
