### ISSUE TITLE
Set default autoexec value

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#880] opened 2021-02-12 11:12 UTC
How do I set the default autoexec options?
```
mount C .
C:
```
https://build.opensuse.org/package/view_file/home:13ilya/dosbox-staging/dosbox-staging-0.76.0-config.patch?expand=1
```diff
 	MSG_Add("AUTOEXEC_CONFIGFILE_HELP",
 		"Lines in this section will be run at startup.\n"
 		"You can put your MOUNT lines here.\n"
+		"mount C .\n"
+		"C:\n"
 	);
```
So they are commented out, how can you define them without a comment?
And why isn't it the default?
I haven't come across any situation where this is NOT required.

**Comment by dreamer** [comment] 2021-02-12 14:28
@IlyaIndigo It's not the default because it would break a lot of scripts and usecases. For example - add this to your autoexec, then go to some game directory and run `dosbox game.exe`. It would affect *a lot* of users depending on graphical frontends and their old scripts to run the games.

Your change lands commented-out because you added it to the translation message.

If you want to mount current working dir automatically: `dosbox .` - it will mount `.` as C: and switch to it :)

If you want to patch DOSBox Staging to do it automatically, then you will need to place lines like this somewhere (I think this should work, haven't tested it myself):

```C++
AutoexecObject autoexec_cmd;
autoexecline.Install("mount C .");
autoexecline.Install("C:");
```

**Comment by kcgen** [comment] 2021-04-08 16:23
Hi @IlyaIndigo , 

I agree with your suggestion, but unfortunately the time to implement it would have been back when DOSBox was just starting life in the early 2000's.  Even if we implemented it and expected users to change their games and front-ends, it would still conflict with how the other DOSBox forks behave - and then cause regressions in them.

Because of this user-interface incompatibility issue, I believe there is no reasonable way to implement this. I will close this for now.

**Closed by kcgen** 2021-04-08 16:23 UTC
Labels: question
