### ISSUE TITLE
make command.com tab completion work like bash (Prompting completion)

### ISSUE THREAD

**Issue by rekaerst** [dosbox-staging/dosbox-staging#634] opened 2020-09-28 03:12 UTC
**Is your feature request related to a problem? Please describe.**
The current tab completion behavior for the filename is looping through all candidates (Rotating completion
), and it's inconvenient when you have a lot of files starting with a similar string in their names in your working directory.

**Describe the solution you'd like**
If a typed string were ambiguous, pressing the tab command.com would complete the longest matching string in candidates and display all candidates starting with that string:
![image](https://user-images.githubusercontent.com/52642831/94385988-116da100-0179-11eb-9f72-bf461e8804ac.png)
if there is only one matching candidate, pressing the tab shall complete that candidate and another tab shall add whitespace.
if there are no matching candidates, pressing the tab shall do nothing.
It just works like bash

**Describe alternatives you've considered**
Download and use FreeCom from FreeDos, its tab completion is Prompting Completion by default.

**Additional context**
https://en.wikipedia.org/wiki/Command-line_completion

**Comment by MasterO2** [comment] 2020-09-28 12:36
I previously raised a similar issue below:

https://github.com/dosbox-staging/dosbox-staging/issues/399

**Comment by nemo93** [comment] 2021-08-31 13:34
Duplicate of #399. Closing this one for now. @rekaerst feel free to add any further inputs to #399 please.

**Closed by nemo93** 2021-08-31 13:34 UTC
Labels: enhancement
