### ISSUE TITLE
Big Red Racing wobbly camera with Dosbox?

### ISSUE THREAD

**Issue by elvisish** [dosbox-staging/dosbox-staging#521] opened 2020-07-27 19:04 UTC
For years Big Red Racing has been unplayable with Dosbox due to a strange bug that causes the camera to wobbly on the X axis: https://youtu.be/94nbLl95unw?t=75

All Youtube videos have the same issue and it's never been addressed in any version of Dosbox, would it be possible it could be looked at for Staging? I wish I knew what caused it but I have no idea, I can only imagine it's some sort of floating-point issue that didn't happen back in real Dos.

**Comment by kcgen** [comment] 2020-07-27 19:23
@elvisish, thanks for that video reference; and yes.. what a sight for sore eyes! 

I don't recall it being like that the last time I played it; but I tend to game on a Pi, and non-x86 architectures use a different dynanmic core than x86 builds.

 Will check it out.

**Comment by MasterO2** [comment] 2020-07-27 19:28
@kcgen 

Here is also a video **without** the wobble:

https://youtu.be/YtOtfMbgJMI?t=246

**Comment by MasterO2** [comment] 2020-07-27 20:10
> 
> 
> @elvisish, thanks for that video reference; and yes.. what a sight for sore eyes!
> 
> I don't recall it being like that the last time I played it; but I tend to game on a Pi, and non-x86 architectures use a different dynamic core than x86 builds.
> 
> Will check it out.

@kcgen 

Windows 10 - 64-bit 
Dosbox-Staging  0.75 Release

I can confirm after testing BRR's demo (https://www.dosgamesarchive.com/file/big-red-racing/brr-demo/) in Dosbox-Staging 0.75, that the camera wobble is still present there.  I do not own the full game, so the above demo version is the only way I could test it.

**Comment by elvisish** [comment] 2020-07-27 21:59
> @kcgen
> 
> Here is also a video **without** the camera wobble:
> 
> https://youtu.be/YtOtfMbgJMI?t=246

I think the framerate is so low it could still be wobbling but I'm not sure if it would be possible to see it?



> > @elvisish, thanks for that video reference; and yes.. what a sight for sore eyes!
> > I don't recall it being like that the last time I played it; but I tend to game on a Pi, and non-x86 architectures use a different dynamic core than x86 builds.
> > Will check it out.
> 
> @kcgen
> 
> Windows 10 Pro - **64-bit**
> Dosbox-Staging 0.75 Release (**32-bit**)
> 
> I can confirm after testing BRR's demo (https://www.dosgamesarchive.com/file/big-red-racing/brr-demo/) in Dosbox-Staging 0.75, that the camera wobble is still present there. I do not own the full game, so the above demo version is the only way I could test it.

The full game behaves the same as the demo so it's perfectly usable for testing.



> @elvisish, thanks for that video reference; and yes.. what a sight for sore eyes!
> 
> I don't recall it being like that the last time I played it; but I tend to game on a Pi, and non-x86 architectures use a different dynamic core than x86 builds.
> 
> Will check it out.

It would be interesting to know if it works differently on a different architecture.

**Comment by kcgen** [comment] 2020-07-27 23:38
I tried many variations:
- disabled the x86/x86-64 dynamic recompiler
- disabled the more generic dynrec compiler
- disabled x86 and x86-64 FPUs
- built using gcc, clang, and the Intel compiler without any optimizations (most strict FPU handling)
- configured dosbox to run with the normal core and tested CPU types from 386 to pentium
- compared a subset of these on the Rpi3

The end result was always the same: at 486-level cycles (in the 20k to 30k range - which is the max on the Pi3), the low frame-rate seems to cancel or hide the camera wobble. At higher cycles, >40k the frame-rates are now fast enough to display all the distinct positions of the camera wobble.

So my guess is this is the game's own code doing this. 

Know that the camera seems to "oscillate" at some frequency, I tried various `frameskip` settings, and it seems to improve things. 

Give this a shot:

``` ini
[cpu]
cycles=fixed 40000

[render]
frameskip=3
```

When in game, I let the other cars race ahead then I idle the truck slowly forward to inspect the wobble.  Normally with high cycles and no skip the mountain edges at the sides of the screen rotate up and down rapidly - but with these setting the mountain range stays very steady. Frame rates are decent too - (but not butter smooth either).

50k cycles and 5 frame skip is also decent, with a tad smoother framerate. 

The game also can display various metric if you run it with the `-DIAGS` argument, but I don't think any of the values represent camera roll, which is the culprit here.

![2020-07-27_16-35](https://user-images.githubusercontent.com/1557255/88602391-97f5ed00-d027-11ea-9544-efe983ad9db5.png)

**Comment by elvisish** [comment] 2020-07-28 05:43
Really interesting, I wonder if it could have always skipped and a slightly low framerate was hiding it. I wish I had an actual old computer with dos on it to try out, it would be interesting to see if there's any difference at all.

Thanks for all of the trouble you've gone to!

**Comment by dreamer** [comment] 2020-07-30 11:41
Asked around on [reddit](https://www.reddit.com/r/dosgaming/comments/hzbpzo/a_camera_bug_in_big_red_racing/), if someone can reproduce the issue on real hardware and so far the closest we got was running on Windows ME, Pentium 3 450MHz - and the camera is visibly stuttery: [video](https://www.youtube.com/watch?v=2Eka-zFIHhQ&feature=youtu.be). However, several people reported that they don't remember this problem being there originally (myself included).

**Comment by dreamer** [comment] 2020-07-30 11:54
Oh, turns out ADG did in-depth investigation into this issue while [reviewing this game](https://www.youtube.com/watch?v=WRNdTxbRX2A) (explanation starts at 6:10) - turns out this is a problem in-game caused by camera being affected by the physics engine.

I wonder if we could hack around it by enforcing a specific max refresh rate of 30 or 60Hz instead of real VGA refresh rate…

**Comment by grapeli** [comment] 2020-07-30 12:23
The available patches do not improve anything?
https://archive.org/compress/BRRD225/formats=ZIP&file=/BRRD225.zip

**Comment by elvisish** [comment] 2020-08-03 09:49
> The available patches do not improve anything?
> https://archive.org/compress/BRRD225/formats=ZIP&file=/BRRD225.zip

I wasn't even aware there were patches!

**Comment by kcgen** [comment] 2020-08-03 16:44
Propose we close this, given the bug exists in the game's camera engine code (as proven on real hardware). 

"Solving" this on the dosbox side would involve some terrible hacks that first need to detect the camera calculation entering the FPU code, and then zero-or-flatten the roll axis/angle.

Perhaps the most viable approach would be a TSR or hacking the game's executable to similar effect.

**Closed by kcgen** 2020-08-03 16:44 UTC

**Comment by danieltowers** [comment] 2024-09-26 08:54
I used to play this on a 486 DX66 and the camera was always a bit jerky in my opinion. But it wasn't noticable enough to affect the game play.

For DOSBox I set CPU to 166000 and I think it it then plays very close to the original. I didnt enable any frame skipping


```
[cpu]
cycles=fixed 166000
```

**Comment by danieltowers** [comment] 2024-09-26 09:08
I tried a few different values. 166000 seemed to give the smoothest gameplay on my system. Anything higher and the camera wobble becomes very noticable. I'm playing it in 640x480 mode, not sure if that makes a difference

**Comment by johnnovak** [comment] 2024-09-26 10:50
> I tried a few different values. 166000 seemed to give the smoothest gameplay on my system. Anything higher and the camera wobble becomes very noticable. I'm playing it in 640x480 mode, not sure if that makes a difference

Haha, sure it does 😆 The 640x480 mode has 4.8 times more pixels than the 320x200 mode.

166000 / 5 = ~ 33000, so yeah, that's around the DX2-66 speeds.

Most 640x480 SVGA 3D DOS games ran like 5-10 FPS slideshows even on the fastest DOS-era hardware, so it checks out that this game needs the fastest Pentium MMX speeds. Cycles 166000 it's actually approaching Pentium II speeds, that' CPU was released in 1997.

You might find the game runs smoothly in 320x200 mode at 30000 cycles or a even a bit less around 25k.

**Comment by danieltowers** [comment] 2024-09-26 11:09
Cheers John. 320x200 is a bit pixelated for me these days, although that's the resolution I used to play it on back in 1995!
