### ISSUE TITLE
Improve imgmount/boot multiple image format

### ISSUE THREAD

**Issue by InsufferableHexavaxxedNPC** [dosbox-staging/dosbox-staging#3045] opened 2023-10-23 08:42 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

Greetings.

I'm currently running some tests because a multiple floppy image installation malfunctioned and it hit me just how stiff the current format for imgmount/boot is.

Right now you must type in the whole address for every image, one after the other, and on the same line. This can become rather inconvenient for long addresses and numerous disks. Feedback from Staging as it's presented after mounting also becomes harder to read due to the long line wraping around 80 columns.

I was hoping something like what you see on the attached screenshot could be implemented in order to simplify and beautify this process.

Allowing the use of newline characters as separators for the files would be a good start.

Best regards and sorry for any inconvenience.

### Describe the solution you'd like

![image0002-raw](https://github.com/dosbox-staging/dosbox-staging/assets/129743500/8915b5f1-5dc0-439f-8457-80315bf26f04)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment] 2023-10-23 11:44
This is already covered in a ticket:

https://github.com/dosbox-staging/dosbox-staging/issues/2509

**Comment by Grounded0** [comment] 2023-10-23 12:16
Seems like a good idea to improve readability of multiple image mounts.

We already support using wildcards to mount images but that doesn't solve the readability issue:

`IMGMOUNT A GAMEDISK*.*`

Closing this as duplicate of:

- #2509

**Closed** 2023-10-23 12:19 UTC
Labels: enhancement

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-25 03:01
Thanks you Grounded0, that's an excellent pro tip right there!

Pretty much solved the bigger issue for me, though a stack of images with completely different names (a far less common occurrence anyways) would sitll require tweaking.

I guess I must have had some manner of subconscious blockage that kept me from realizing this was possible due to mesages like the one you get when trying to use wildcards for file renaming within Staging.

If any case, I think this very handy tip may be worth mentioning in the manual.

Best regards.

**Comment by kcgen** [comment] 2023-10-25 03:46
> Pretty much solved the bigger issue for me, though a stack of images with completely different names (a far less common occurrence anyways) would sitll require tweaking.

The wildcard handling is pretty robust, so you might be able to feed it quite a mess provided they can be naturally sorted. Here are a couple examples:

https://github.com/dosbox-staging/dosbox-staging/pull/2270#issue-1577072766

https://github.com/dosbox-staging/dosbox-staging/pull/2270#issuecomment-1425065274

For example, if you have these images (strictly ordered by character):
- `DATA02.img`,
- `DATA3.IMG`,
- `data1.img`,

Running an `imgmount *.img` will natural sort the mount order to: `data1.img`, `DATA02.img`, and `DATA3.IMG`.

**Comment by Grounded0** [comment] 2023-10-25 08:56
We should document this on `HELP IMGMOUNT` page if it isn't already.
