### ISSUE TITLE
Joystick detection issue in some LucasArts flight sims

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#3320] opened 2024-01-13 09:52 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

I have been configuring some older LucasArts flight sims to work in DOSBox Staging, which are currently already running fine for me under DOSBox-X. 

I have carefully checked joystick settings and all other config options, but two games in particular seemingly lock up on a message that says "center joystick then click button" which appears after the title screen. The affected games are Battlehawks 1942 and Secret Weapons of the Luftwaffe. 

I have tried pressing all keyboard keys and mouse buttons and nothing will let me advance beyond this screen. Disabling the joystick in the config file also does nothing. I would be happy to play these games with the keyboard, but running them in Staging seems to demand the presence of a joystick.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by almeath** [comment] 2024-01-13 10:27
I have figured out that the 'hidden' joystick setting is now required rather than 'auto' in order to bypass this issue.

**Comment by johnnovak** [comment] 2024-01-14 00:05
> I have figured out that the 'hidden' joystick setting is now required rather than 'auto' in order to bypass this issue.

We should probably add this info to the wiki.

**Comment by rderooy** [comment] 2024-01-14 09:24
If the game has joystick support, and it works in other DOSBox variants, then it would appear something is broken. Hiding or disabling the joystick is only a work-around, not a fix.

**Comment by weirddan455** [comment] 2024-01-14 14:16
I am unable to reproduce this.  I tried both games with every available joystick setting.  Tried with my gamepad plugged in and with it unplugged.  I never see the screen you're talking about.

**Comment by weirddan455** [comment] 2024-01-14 15:33
Probably this is the same issue as #3326 which I was able to reproduce.

**Comment by weirddan455** [comment] 2024-01-15 12:48
Should be fixed in #3327 but we can leave this open for now as I was unable to reproduce.

If you could please test against latest main and let us know if the issue is now resolved, that would be great.

**Comment by johnnovak** [comment] 2024-01-27 23:08
@almeath This should be fixed in the latest DEV build. Could you please confirm?

**Comment by almeath** [comment] 2024-02-03 07:24
Thanks. I can confirm that in 0.81.0-rc2, this issue is resolved. I can specify joystick=auto and the above mentioned games start up normally.

**Comment by johnnovak** [comment] 2024-02-03 08:06
> Thanks. I can confirm that in 0.81.0-rc2, this issue is resolved. I can specify joystick=auto and the above mentioned games start up normally.

Thanks for confirming @almeath!

**Closed by johnnovak** 2024-02-03 08:06 UTC
Labels: question, input handling
