### ISSUE TITLE
Video Capture aspect ratio regression

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2813] opened 2023-08-31 22:34 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

@johnnovak you might want to take a look at this.  It's from #2777 that got merged yesterday.  Commit bc924b6f7cb966e5a2f1b0235e0d43a5bde68fd4

```
bc924b6f7cb966e5a2f1b0235e0d43a5bde68fd4 is the first bad commit
commit bc924b6f7cb966e5a2f1b0235e0d43a5bde68fd4
Author: John Novak <john@johnnovak.net>
Date:   Tue Aug 22 22:32:08 2023 +1000

    Implement adaptive CRT emulation shaders
    
    - All shader management code has been moved from 'render.cpp' to
      the ShaderManager.
    
    - The 'default' shader alias to 'interpolation/sharp' has been replaced
      with the 'sharp' alias.
    
    - Three new adaptive (auto-switching) CRT emulation shader modes have
      been added: 'crt-auto', 'crt-auto-machine', and 'crt-auto-arcade'.
      These modes switch dynamically between CRT shader variants depending
      on the current video mode, the graphics adapter in use, and the
      viewport resolution (see the description of the 'glshader' setting for
      further details).

 include/render.h           |  35 +--
 src/gui/meson.build        |   5 +-
 src/gui/render.cpp         | 453 ++++++++++++++------------------------
 src/gui/sdlmain.cpp        |  16 +-
 src/gui/shader_manager.cpp | 531 +++++++++++++++++++++++++++++++++++++++++++++
 src/gui/shader_manager.h   | 179 +++++++++++++++
 src/hardware/vga_draw.cpp  |  12 +
 vs/dosbox.vcxproj          |   2 +
 vs/dosbox.vcxproj.filters  |   6 +
 9 files changed, 918 insertions(+), 321 deletions(-)
 create mode 100644 src/gui/shader_manager.cpp
 create mode 100644 src/gui/shader_manager.h
```

I think what is happening is before this commit the `RenderedImage` has both `double_width` and `double_height` set.  Afterwards, it's only doubling the width.

Correct 640X400 resolution capture:

![good-capture](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/62b1c083-e8a9-4fc4-adb8-44b13a5754d7)

Incorrect 640X200 resolution capture:

![bad-capture](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/d4f98ee6-3f02-4e7f-9b15-c8d364681adb)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Start a 320X200 resolution VGA Game (I used Doom)
2. Ctrl + F7 to start a video capture
3. Aspect ratio is wrong

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-08-31 23:03
Thanks @weirddan455 . Possible duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/2734. I'll handle all possible video related regressions in that ticket.

**Comment by johnnovak** [comment] 2023-08-31 23:10
Btw, depending on which shader you use, you'll get different video output now 😄 Try crt-auto, and crt-auto-arcade and the default sharp shader. You'll be amazed 😄 (all will be fixed, of course)

**Comment by weirddan455** [comment] 2023-09-01 00:07
I was testing with crt-auto.  The video output didn't look like what I saw on screen.  Looked like no shaders applied.  I wasn't really expecting that to work though.  I figured we have to render OpenGL to an external framebuffer or something to get that.

We can combine this with #2734 if you like.  However, this only regressed on main yesterday whereas that other bug is almost a month old.

**Comment by johnnovak** [comment] 2023-09-01 01:10
> We can combine this with #2734 if you like. However, this only regressed on main yesterday whereas that other bug is almost a month old.

Yes, it seems like that, I'll give you that. But it's same thing, trust me. I'm talking about the root case 😄 Please wait until I fix the linked ticket.

**Comment by johnnovak** [comment] 2023-09-01 01:18
@weirddan455 Very condensed story: I changed the way the doubling flags behave, and what exact dimensions the rendered images can have, but I never updated the video capture code to take the altered semantics into account... plus some other murky stuff 😅

**Comment by johnnovak** [comment] 2023-09-01 01:20
> I was testing with crt-auto. The video output didn't look like what I saw on screen. Looked like no shaders applied. I wasn't really expecting that to work though. I figured we have to render OpenGL to an external framebuffer or something to get that.

We're not doing post-shader captures, and I don't think that's a good idea because CRT shaded output doesn't compress well. It would increase your filesizes 5-10x at good quality settings (like noise in older movies, if you wanna encode that properly and semi-losslessly).

But entirely new discussion; video capturing post-shaded is way out of scope for now 😄

**Comment by MasterO2** [comment] 2023-12-12 23:01
What's the status on this issue for 0.81?

**Comment by johnnovak** [comment] 2023-12-12 23:25
> What's the status on this issue for 0.81?

Fixed by the linked PR.

**Closed by johnnovak** 2023-12-12 23:25 UTC
Labels: bug, regression, video
