### ISSUE TITLE
Supaplex locks up in `main` unless MPU+MIDI is enabled

### ISSUE THREAD

**Issue by rarioj** [dosbox-staging/dosbox-staging#2397] opened 2023-04-11 00:16 UTC
Thanks @rarioj for this submission. It's been bisected to 9a42619 and reproduced with the following:

Use the attached self-contained zip that has all the audio devices off: [2397.tar.gz :file_folder: ](https://github.com/dosbox-staging/dosbox-staging/files/11216912/2397.tar.gz)

1. `git checkout 9a42619` should hang when clicking and moving the mouse randomly inside the controls menu.

2. `git checkout 9a42619^` will not hang when clicking and moving the mouse randomly inside the controls menu.

**Comment by FeralChild64** [comment] 2023-04-11 17:34
Indeed, I can reproduce the problem. Investigating...

---

Workaround to still play the game: enable serial mouse; in the current GIT version this is:

```ini
[mouse]
com_mouse_model = wheel+msm

[serial]
serial1 = mouse
```

and use CuteMouse driver - run `ctmouse /s` before starting the game.

**Comment by kcgen** [comment] 2023-04-11 19:05
> [edit2] Something in DSP_DoReset must be disrupting the mouse handling, namely commenting out PIC_RemoveEvents and PIC_AddEvent

Interesting; I recall the reset takes some time to settle after processing DSP actions; perhaps the PIC add and remove actions need to be scheduled further out in time?

**Comment by kcgen** [comment] 2023-04-11 19:11
Found it:

https://pdos.csail.mit.edu/6.828/2018/readings/hardware/SoundBlaster.pdf (logical page 24 of 141)

![2023-04-11_12-04](https://user-images.githubusercontent.com/1557255/231263930-ea50f899-2572-412f-83cf-ad80137bfac8.png)

Looks like the SB code delays 20 microseconds during a reset [edit] tried 5 μs and up to 90 μs without any change).

**Comment by FeralChild64** [comment] 2023-04-11 21:17
I did one more short test before sleep: it seems it is enough to comment-out `DSP_AddData(0xaa);` from `DSP_FinishReset` to prevent the game from entering non-responsive state.
So this is not an incompatibility between mouse code and SoundBlaster code - the game must be doing something after it receives the `0xaa` response, which is not properly handled.

**Comment by johnnovak** [comment] 2023-04-12 21:29
From MobyGames:
https://www.mobygames.com/game/2106/supaplex/specs/

> Original game runs at twice the intended speed on 286 and above. Will also work on all higher DOS versions and most Windows versions. Soundblaster support is highly limited to original Soundblaster cards. The 8-bit Soundblaster works best, other 'compatible' cards mostly lock up the game.

But maybe they are only talking about the original herr, not the later CD-ROM re-release.

**Comment by kcgen** [comment] 2023-04-13 00:02
> But maybe they are only talking about the original here, not the later CD-ROM re-release.

Found a partial copy of the floppy version https://archive.org/details/002452-Supaplex, but is missing the second disk (so can't start the game far enough to get to the control menu). 

On the CDROM side, maybe the sound blaster is hiding the regression because I can repro the hang with zero audio devices:

![2023-04-12_16-30](https://user-images.githubusercontent.com/1557255/231608124-b07bddaa-0cff-44c5-b077-c0dee7a2ff3e.png)

Here's a self-contained zip that has all the audio devices off, and even the CDAUDIO interface is gone: [2397.tar.gz :file_folder: ](https://github.com/dosbox-staging/dosbox-staging/files/11216912/2397.tar.gz)

`git checkout 9a42619` -> repro when clicking randomly in the controls
`git checkout 9a42619^` -> can't repro (won't hang in controls)

Maybe this will help you isolate it, @FeralChild64

**Comment by kcgen** [comment] 2023-04-27 19:02
@FeralChild64 - I've updated the original issue body this time eliminating any involvement with audio devices (by disabling them all). Maybe this can help?

**Comment by FeralChild64** [comment] 2023-05-04 19:35
The more I investigate, the more mysterious it seems. On commit https://github.com/dosbox-staging/dosbox-staging/commit/19fcfc5e0 (the last good one) the problem does not reproduce if using the built-in DOS mouse driver - but if you run _CtMouse 2.1b4_ before starting the game (so that it will replace our internal mouse driver), it will get locked just like with current GIT main. Same with _Mouse Systems Mouse_ driver v8.00 (run `MSCMOUSE.COM /p` to force using PS/2 mouse port).

**Comment by kcgen** [comment] 2023-05-04 19:47
Could it be that original hardware + CtMouse 2.1b4 or  Mouse Systems Mouse driver v8.00 will similarly lock up?

If so - then it sounds like this is perfectly fine and we can close it out.

**Comment by kcgen** [comment] 2023-05-04 21:33
> The more I investigate, the more mysterious it seems.

:mag_right: !

> if you run _CtMouse 2.1b4_ before starting the game (so that it will replace our internal mouse driver), it will get locked just like with current GIT main.

Using this approach, I started bisecting back.

Starting at commit 7287f65f1, _CtMouse 2.1b4_ is unable to handle/send mouse clicks.

However 7287f65f1^ (and prior), _CtMouse 2.1b4_ is able to  handle/send mouse clicks.  Perhaps 7287f65f1 is where the regression originates (and _CtMouse_ is acting like a cannery)

**Comment by kcgen** [comment] 2023-05-05 05:33
(Update: something broke in that prior bisect attempt where I mentioned CtMouse not processing clicks; I'm redoing the bisect now. Sorry for that false-positive @FeralChild64 !)

**Comment by FeralChild64** [comment] 2023-05-05 18:44
With _CtMouse_ loaded the game stops responding even under DOSBox-X - so bisecting would probably need to go really far into the past.

**Comment by FeralChild64** [comment] 2023-05-05 19:12
i have found something: `http://www.bd-fans.com/Supaplex.html`, see SndFix.zip file content:

> The Sound Blaster base address is fixed by Supaplex at 220h, and used either
> IRQ 2, IRQ 3, IRQ5 or IRQ 7.  Checking for the used IRQ, this sub-program
> crashes many new PC's when IRQ 2 is tested.  This patched version does not
> test for IRQ 2 anymore, but the Sound Blaster can still use IRQ 3, IRQ 5 or
> IRQ 7, at will.  The base address 220h has not been changed.

This makes sense... the unpatched game really does something strange with IRQ 2, as it makes `secondary_startIRQ()` calls during mouse movement to stop. And the patch fixes the problem for me.

@rarioj Could you check this unofficial [SndFix.zip](http://www.bd-fans.com/Files/Classic_Supaplex/Bugs/SndFix.zip) patch?

**Comment by FeralChild64** [comment] 2023-05-05 19:54
Right, IRQ 2 is used to cascade interrupts to the secondary interrupt controller. It also explains why CtMouse works if ordered to use COM1 serial mouse - as its IRQ uses primary interrupt controller.

The game was originally written in 1991, and looks like a really low-budget one...

**Comment by kcgen** [comment] 2023-05-05 20:23
> Right, IRQ 2 is used to cascade interrupts to the secondary interrupt controller. It also explains why CtMouse works if ordered to use COM1 serial mouse - as its IRQ uses primary interrupt controller.

![4941533](https://user-images.githubusercontent.com/1557255/236561494-4cebc23d-d5da-499c-b0d5-93bd2ae5d57c.jpg)

**Comment by kcgen** [comment] 2023-05-05 21:46
@python-exoproject, not sure if you have the patch mentioned by @FeralChild64 integrated with Supaplex: <https://github.com/dosbox-staging/dosbox-staging/issues/2397#issuecomment-1536667131>, but it seems it would be very useful to avoid any PS/2 relate mouse interface bugs (with any dosbox fork and on real hardware as well).

**Comment by MasterO2** [comment] 2023-05-05 21:49
This also sounds like another potential great entry to the Games Issues page on the Dosbox Staging Wiki.

**Comment by johnnovak** [comment] 2023-05-05 22:01
Another case when DOSBox did nothing wrong and the original game is flaky as hell...

One of my "favourites" is that the numpad keys for movement don't always register in Eye of the Beholder II. The normal cursor keys work 100% of the time. Wasted half a day on it until I realised yep, it's flaky on real hardware too... It's a mistake to think all games worked perfectly on real hardware.

**Comment by rarioj** [comment] 2023-05-05 23:53
> @rarioj Could you check this unofficial [SndFix.zip](http://www.bd-fans.com/Files/Classic_Supaplex/Bugs/SndFix.zip) patch?

Hi @FeralChild64 thank you.

I did apply the sound fix patch. The same issue still occurred on **DOSBox-Staging** (as soon as I went to controls, enabled S.Blaster, and FX). The sound fix patch applied in **DOSBox** and **DOSBox-X** without any problem (they worked even before the patch).

I played around in the controls menu: AdLib with Music + FX enabled worked fine, Internal (PC Speaker) with Music + FX enabled worked fine, Roland with Music + FX enabled worked fine (although no sound effects), but as soon as I click on S.Blaster and FX, the game crashes.

Clicking around in the controls menu didn't crash the game for me (as long as the Sound Blaster and sound effects combination is disabled).

Any other specific steps or configuration to test?

**Comment by FeralChild64** [comment] 2023-05-06 11:37
@rarioj Could you paste your DOSBox Staging configuration? With the patch, I cannot reproduce the problem on my system.

@MasterO2, @Python-Exoproject - there is one more unofficial patch for the game on the page I linked, the _SpeedFix_.

**Comment by rarioj** [comment] 2023-05-06 12:35
Hi @FeralChild64

I'm sorry, you're right. I did another test with the patch and it's working. It was an error in my `[autoexec]` section with the unzip flag. I used `C:\UNZIP\UNZIP.EXE -O X:\PATCH.ZIP` earlier with the capital `-O` flag to extract and overwrite. Turned out the right overwrite flag is `-o` with small letter o. Hence, the patch didn't apply when I tested before.

The patch works [👍](https://emojipedia.org/thumbs-up/). Definitely should add this to the Wiki.

Thank you.

Here's my dosbox.conf anyway:

```
[sdl]
autolock = true

[autoexec]
@ECHO OFF

MOUNT C "./drive"
IMGMOUNT D "./Assets/cdrom.iso" -t iso
MOUNT X "./Assets"

IF NOT EXIST C:\SUPAPLEX\SUPAPLEX.EXE GOTO F_INSTALL
IF EXIST C:\SUPAPLEX\SUPAPLEX.EXE GOTO F_START

:F_INSTALL
D:
CALL HDINSTALL.BAT
IF NOT EXIST X:\MANUAL.PDF COPY D:\MANUAL\MANUAL.PDF X:
C:
CD C:\
MD UNZIP
CD UNZIP
X:\UNZ542X3.EXE
CD C:\SUPAPLEX
C:\UNZIP\UNZIP.EXE -o X:\PATCH.ZIP

:F_START
C:
CD C:\SUPAPLEX
SUPAPLEX.EXE

:F_EXIT
EXIT
```

**Comment by MasterO2** [comment] 2023-05-06 13:03
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#supaplex

**Comment by kcgen** [comment] 2023-05-08 17:51
> Right, IRQ 2 is used to cascade interrupts to the secondary interrupt controller. It also explains why CtMouse works if ordered to use COM1 serial mouse - as its IRQ uses primary interrupt controller.

@FeralChild64 ,

I haven't checked it, but I think if we  set `ps2_mouse_model = none` , we should expect it to work correctly, similar to upstream DOSBox, right? (And similar to CtMouse in non-PS/2 mode)

**Comment by johnnovak** [comment] 2023-05-09 01:35
> > Right, IRQ 2 is used to cascade interrupts to the secondary interrupt controller. It also explains why CtMouse works if ordered to use COM1 serial mouse - as its IRQ uses primary interrupt controller.
> 
> @FeralChild64 ,
> 
> I haven't checked it, but I think if we set `ps2_mouse_model = none` , we should expect it to work correctly, similar to upstream DOSBox, right? (And similar to CtMouse in non-PS/2 mode)

Hey, just an idea: could this be related to the problem with Gauntlet? https://github.com/dosbox-staging/dosbox-staging/issues/2460#issuecomment-1537235652 The MPU401 also uses IRQ2.

**Comment by kcgen** [comment] 2023-05-09 01:35
Tried to answer the above. There is something going on with MIDI:

| Version | `mpu401` | `mididevice` | `ps2_mouse_model` | Result |
| --- | --- | --- | --- | --- |
SVN latest | `intelligent` | `none` | N/A | runs
Staging 80.1 | `intelligent` | `none` |`explorer` | runs
Staging 80.1 | `intelligent` | `none` | `none` | runs
Staging main | `intelligent` | `none` | `none` | lockup
Staging main | `intelligent` | `none` |`explorer` | lockup
Staging | `intelligent` | `mt32` or `fluidsynth` | `none` | runs
Staging | `intelligent` | `mt32` or `fluidsynth` | `explorer` | runs

Here's the conf I'm using: [dosbox.conf.zip](https://github.com/dosbox-staging/dosbox-staging/files/11426334/dosbox.conf.zip), with [package](https://github.com/dosbox-staging/dosbox-staging/files/11216912/2397.tar.gz) 

@johnnovak - this feels like it's paralleling Gauntlet, which has the same behavior. (Staging main now need MIDI present to keep Gauntlet going, even though Gauntlet is circa 1988 and doesn't use MIDI)?

**Comment by kcgen** [comment] 2023-05-09 01:36
@johnnovak - crossed in the ether! :beers:

**Closed** 2023-06-04 15:17 UTC
Labels: regression
