### ISSUE TITLE
Dosbox Debugger does not react on key presses

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#4089] opened 2024-12-06 16:34 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

(already discussed on discord but having a real issue is better then some comments somewhere)

the builtin debugger of dosbox does not react to keypresses - that worked in former releases (and also under linux)

minor: also the [x] close icon doesn't close the debugger-window

on discord: interloper98 found the relevant commit: 

https://github.com/dosbox-staging/dosbox-staging/commit/d225c9a619fc69de19a68da473dcfa244862582d

that seems to break the keys in the debugger

### Steps to reproduce the behaviour.

1. build Dosbox with config.h `#define C_DEBUG 1`
2. start dosbox
3. in console `debug attrib.com` then the debug windows comes up
4. press F5(run) or F10(single step) - nothing happens

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-12-07 04:23
> The bisect is specific to Windows, too. (The debugger's F5 and F10 keys work OK under Linux for the affected commit).

@LowLevelMahn has a fair point that we should do more Windows testing. I think that has to change; I urge everybody in the team who has a Windows installation but does not develop on Windows primarily to test their features during the PR phase on Windows as well.

I admit I'm guilty of not doing that; I develop on macOS 99% of the time, and I only test stuff before release. But that's too late, you can't possibly give all yours merged stuff as much scrutiny as you did during the PR phase.

At the end of the day, most people use DOSBox on Windows. It's cool to have a Mac version and I'm sure Linux people all have their righteous reasons 😆, but 99% of people are on Windows.

**Comment by LowLevelMahn** [comment] 2024-12-07 10:44
maybe additional: 
ask on discord for testers if keyboard/key usage behavior gets change - so the german/french/... guys can help testing

**Comment by LowLevelMahn** [comment] 2024-12-07 14:34
interloper98 is right the debugger works fully under linux in a VM
but i can't close the dosbox or debugger-windows with [x] on WSL (need dosbox crash to console with Ctrl+C)

discord user max said that WSL got problems with closing windows
but testing QtCreator, xterm, glxgears and gedit worked - and im using WSL day by day without problems with UIs

**Comment by LowLevelMahn** [comment] 2024-12-07 19:54
> But I understand we're talking about the Visual Studio build, so I'm trying to get that build working but getting a handful of link errors:
> lld-link : error : could not open 'msvcrt.lib': no such file or directory
> lld-link : error : could not open 'oldnames.lib': no such file or directory
> lld-link : error : could not open 'msvcprt.lib': no such file or directory
> lld-link : error : could not open 'MSVCRT.lib': no such file or directory
> lld-link : error : could not open 'OLDNAMES.lib': no such file or directory
> Anyone else get these or know how to fix them? I'll some test builds from CI and the old releases in the meantime.

never got such problems - you need to use VS2022 (Community) + ClangCL + vcpkg that should be enough - never failed more me this way - i will try a delete-all-fresh-build just to be safe that nothing happend with the VStudio stuff

> I tested a handful of release versions and the main window always closes with [x], however I'm not running inside VMWare or WLS.
> which release did this new regression start?

this happens only with WSL (as i stated) - im not sure when the [x] for the debug-window stopped working - could be broken since the switch to SDL/PDU-Curses window - im testing only every some month so this could be a really an very old regression

**Comment by LowLevelMahn** [comment] 2024-12-07 20:01
> > VS2022 (Community) + ClangCL + vcpkg that should be enough
> 
> Thanks - yes - that's what I'm using. I installed them some time late last year - and whatever auto-updates they're doing behind the scenes. Not sure of the exact minor versions of them, but I guess I should blow it all away and try from scratch.

discord me if you need direct help

> > this happens only with WSL (as i stated)
> 
> I'll read able how to setup WSL and run binaries from within it.

beware: WSL takes much space on your hard-disk - distro+libs so easily some 20-30GB...

**Comment by johnnovak** [comment] 2024-12-07 21:47
Guys, we only support running on native OSes. VMware, WSL, etc. are out of scope.

Of course, I won't stop @interloper98 to investigating this, but we can lose a lot of time making sure everything is 100% correct in virtualised environment. I think it's a time wasted 🤷🏻

**Comment by LowLevelMahn** [comment] 2024-12-08 08:55
> Guys, we only support running on native OSes. VMware, WSL, etc. are out of scope.

i understand the WSL concerns (its relativly new) - even when im using it for 2 years in my linux development

but having Linux or Windows in a VM is more then standard for at least 10 years now, at all my custormers and privately - im doing my prof. development with native Windows+Linux and both in VMWares - so having a virtual system isn't that uncommon

(for example: VirtualBox Mouse-Driver stuff is special to dosbox - not nothing that is usually needed in any form)

it would be very strange if dosbox would fail in any way running in a VM - unrelevant if Windows or Linux, its just too common nowerdays - but you're making the rules - im just a consumer here :)

> (if it's indeed a new issue).

ok its not - it was since 0.79 like this (the WSL behavior of not able to close with any window [x] is strange but as John stated - currently not supported)

**Comment by johnnovak** [comment] 2024-12-08 14:28
@Torinde @LowLevelMahn By all means fix this and submit a patch for WSL if this is important for you guys 😄 

Personally, I think it's a fool's errand -- you'll get horrible audio and even visual latency if you run any "multimedia" applications like emulators or games through WSL. Surely it's OK for non-demanding desktop apps.

**Comment by LowLevelMahn** [comment] 2024-12-08 15:32
> By all means fix this and submit a patch for WSL if this is important for you guys

not a big deal for me dosbox staging works in WSL and VMWare for me without problems
except this little tiny "wont't close on [x]" thing

**Comment by weirddan455** [comment] 2024-12-09 12:47
Can you please clarify reproduction steps @LowLevelMahn ?  I don't see anything regarding virtualization in the top post but apparently that's the only way it's bugged if I'm reading the follow up comments correctly.

>  @LowLevelMahn has a fair point that we should do more Windows testing. I think that has to change; I urge everybody in the team who has a Windows installation but does not develop on Windows primarily to test their features during the PR phase on Windows as well.

I mean I'm not going to argue against more testing but I don't think Windows is especially problematic as far as regressions go.  Here we're talking about a debugger build.  I don't think any of the core contributors use the debugger.  I've only ever even compiled it once or twice.  And then on top of that, it's maybe only bugged under virtualization?  No one here is testing that use-case.

>   nowadays you can think of VMWare, VirtualBox, QEMU, WSL, etc. just as another PC model

There's more to it than that.  As far as real-world usage for Linux VMs go, 90%+ of them are headless servers and that's where all the big money for support goes.

WSL was meant for console use only for developers.  X11 support was kind of hacked on after the fact.  VMWare and VirtualBox require external kernel modules to have a fully featured desktop.  QEMU kind of works out of the box with open source drivers but even there I often have problems with GUI desktop applications.

Input, audio, and video can all be problematic.  Input because you're often using some VM driver that supports seamless mouse integration, drag and drop, clipboard integration, etc that we don't have to deal with on a native machine.  Video because you're usually using some slow/gimped software OpenGL implementation.  Audio because it can introduce latency going through an emulated audio device and then through both host and guest OS audio stacks.

I'm with @johnnovak on this one.  If someone wants to submit a PR, feel free but it's a pain in the butt to debug all that crap and I don't even know why you would want to run DOSBox in a VM in the first place.  Staging is very portable.  [Even if you're running some obscure toy OS, you can probably get a native build.](https://ports.serenityos.net/dosbox-staging/dependencies)

**Comment by LowLevelMahn** [comment] 2024-12-09 12:58
@weirddan455

the dosbox debugger keys not functioning in a **native Windows host** (nothing related to VMs, WSL2 or Linux)
the debugger keys work under Linux (native, VM or WSL2) without a problem

according to interloper98 it starts to fail with native Windows with this commit: https://github.com/dosbox-staging/dosbox-staging/commit/d225c9a619fc69de19a68da473dcfa244862582d

**Comment by weirddan455** [comment] 2024-12-09 14:43
Thanks @LowLevelMahn this thread took a hard left at the VM talk :laughing: 

>  minor: also the [x] close icon doesn't close the debugger-window

This is reproducible in Linux but the keys still work.  I'll take a look in Windows and see what I can do.

**Comment by weirddan455** [comment] 2024-12-09 16:33
Ok, this is what I've got:

- Bug is not reproducible with an MSYS2 build, only with Visual Studio
- Visual Studio took over an hour to build dependencies from vcpkg... I hate programming in Windows

Narrowed down the buggy commit to one of two.  Commit log goes like this:

1. d225c9a619fc69de19a68da473dcfa244862582d - Rework remaining locale settings and autodetection - Bug is reproducible
2. 0b1f510683b36d46440a781f8e151b7f942a9f23 - Rework host language (messages) autodetection - Commit does not compile
3. 71b765e50923c6dc0300011ca2636167033d2b96 - Move some locale data to a separate file - Bug is not present

I don't know if it's feasible but it would be nice if CI would build every commit separately before we commit a PR so we don't run into commits that don't compile when trying to bisect.

**Comment by LowLevelMahn** [comment] 2024-12-09 16:39
> Visual Studio took over an hour to build dependencies from vcpkg... I hate programming in Windows

vcpkg usage+compile everything is not typical for Windows programming - normaly you got your third parties like in Linux but vcpkg makes it easier to update versions - the same happens when updating your base system, but vcpkg is set to compile (i think) same would happen if you use Gentoo :)

**Comment by weirddan455** [comment] 2024-12-09 16:44
There's something wrong with the vcpkg dependency builds.  I have an 8 core CPU and it was sitting mostly idle save for a Windows Antimalware process.  When it actually gets to DOSBox code, it spins up all my cores and builds pretty quickly.

**Comment by weirddan455** [comment] 2024-12-09 17:08
Anyway, I found what the problem is and it's strange.  This is the function that reads keystrokes for the debugger:

https://github.com/dosbox-staging/dosbox-staging/blob/2286d37ae84cf31056f91787c0f71c8ce0caa71a/src/debug/debug.cpp#L1690-L1694

It reads it in with `key = getch()`.  That returns the correct code (269 in decimal for the F5 key).  However, it later does a `switch toupper(key)`.  Whatever @FeralChild64 did in that giant commit changed the behavior of `toupper()`.  In 71b765e and earlier, it passes the value through as 269.  Starting with d225c9a it returns 13 and therefore doesn't register as the correct key.  I would expect `toupper()` to only modify ASCII letters so I'm not sure why it's doing this.

**Comment by LowLevelMahn** [comment] 2024-12-09 17:13
>  I'm not sure why it's doing this.

and only on windows...

**Comment by weirddan455** [comment] 2024-12-09 17:42
Workaround PR up for this issue #4098  I just wrote my own `ascii_to_upper()` function that does what the debugger's input handler expects.

**Comment by weirddan455** [comment] 2024-12-09 20:01
![winblows](https://github.com/user-attachments/assets/d676239b-75dd-431b-b4dd-1d5ca9543498)

**Comment by johnnovak** [comment] 2024-12-09 20:19
> > Visual Studio took over an hour to build dependencies from vcpkg... I hate programming in Windows
> 
> I got smoked by this yesterday, too 💀 (thought it was just me; at least we're in the same boat! 🤜 🤛 😆 )
> 
> ![9d6p7u](https://private-user-images.githubusercontent.com/165201780/393979625-01c8be3a-d3f0-4a06-8def-0219f310cfda.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzQ5MzIsIm5iZiI6MTczMzc3NDYzMiwicGF0aCI6Ii8xNjUyMDE3ODAvMzkzOTc5NjI1LTAxYzhiZTNhLWQzZjAtNGEwNi04ZGVmLTAyMTlmMzEwY2ZkYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMDAzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYThjODAwNWQyMGU3Mjc2MjAyZDRlMTllM2E0YmY5NmVkOGVmMDEwMzNhNWFiNDViZmRmOTYwNjQ2NDUzZmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-Ap1sK8R-t_sMZP50Rc3DzPyCfsmYEaPjkDZU1LqXEc)

Yeah, happens after you don't build on Windows for a while.

This is a one-time cost for a "cold build"; the second build will be fast. So no apples vto oranges comparison please 😄

Rest assured, I think you'll have the same "slowdown" for vcpkg cold builds on Linux and macOS too once we fully migrate to it 😎 Fair is fair! 😏 

IMO, everbody has a few minutes or half an hour for an initial build... It's fine. It's a small price to pay for a better and unified cross-platform build method thst's _actually_ used by people (unlike Meson whic is always behind and the ports are kinda neglected). So CMake + Ninja + vcpkg is the way, as we went over this numerous times.

Relying on system deps is a bad way to build software in a reproducible manner and to cross-compile (but we can optionally support it, sure). And Meson is a niche thing used by too few people and has objective shortcomings. The world has chosen CMake.

**Comment by johnnovak** [comment] 2024-12-09 20:44
> will probably still blow away visual studio (even with initial vcpkg deps built).

Not 100% sure that it will be faster, but we'll see. Well, and you need VS if you want to use the best C++ debugger on any platform. And profilers like Intel VTune. There's a reason why game devs and pro C++ people pretty much only use Visual Studio on Windows.

**Comment by johnnovak** [comment] 2024-12-09 20:49
> Probably a big chunk of the blame goes to Glib and friends too.

I was gonna say 😆 I'm pretty sure you're right!

We'll move FluidSynth out into a CLAP plugin eventually to decontaminate the codebase from this acute Glib infection 🤢 🤮 😆 

That's the only dependency I'm aware of which must use GNUisms and GCCisms heavily, so no wonder... Blame Linux! 😆

**Comment by LowLevelMahn** [comment] 2024-12-09 20:52
> I'm going to be upset if my Linux builds take that long with vcpkg but I don't think they will.
it will not - filesystem accesses are just better, resource usage at most - and less virus scan software killing your performance - and the compilers/linkers are faster - for example: 1Mio lines of code builds on WSL2 with clang++ ~2 times faster then MSVC on the same hardware (without pseudo virtualization) on a clean, non network shared, non VPN, default virus-scanner settings

> Well, and you need VS if you want to use the best C++ debugger on any platform. And profilers like Intel VTune. There's a reason why game devs and pro C++ people pretty much only use Visual Studio on Windows.

there are so many developers that don't have a clue about that very true business fact

**Closed as completed** 2024-12-10 13:43 UTC
Labels: Windows, regression, input handling, debugger
