### ISSUE TITLE
Sound emulation: Long road to Perfection

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#278] opened 2020-04-07 17:25 UTC
Follow-up on #171.

Turns out DOSBox has some (serious) problems with sound hardware emulation and/or output. Audio volume with different hardware or output (digital vs. MIDI) is unbalanced, hardware is either not accurately emulated or even outright broken, and while I was gathering edge test-cases, some questions arose. Hope I'll be clear enough and I won't need to rewrite the whole thing. But it will probably be better to break it down to smaller and more focused issues.

Let's start simple: PC speaker in terms of volume sounds just about right. SoundBlaster emulation seems to be too loud, and Gravis UltraSound and MIDI (OPL included) are way too quiet. From my understanding, General MIDI and Sound Canvas devices just send instructions to an external renderer, and so it shouldn't be a problem of DOSBox (user's synth could be configured to output with lower volume, and it also depends on used soundfont), but I'm not sure.

Another thing considering volume problem is that 16-bit output for some reason has lower volume than 8-bit output. Applies both to SB and GUS audio.

Oh, Gravis UltraSound... this one's painful. Seems it's emulated totally incorrect, and because of that we have various problems, namely: incorrect sound, lack of stereo separation, sometimes no output at all, low volume. It's also not clear which model is emulated, and in some cases we might need to emulate at least MAX one.

Speaking of incorrect emulation. SB16 has some sort of low-pass filter, which isn't present in DOSBox. Sure, that's inaccurate and sounds different, but not necessarily worse. SB2 (or was it Pro?) has its own filter in place though.

Now, to be more specific - some test subjects:

**Might and Magic III: Isles of Terra**. This one is interesting because it's the only known to me game that actually changes audio volume depending on SB type and `sbmixer` setting: it sounds louder with older soundcard models, and also with mixer turned off. What exactly `sbmixer` setting does? Why is it needed? When we should switch it? SounBlaster is only used in cut-scenes for voices, everything else (SFX included) is rendered by Roland device (if it's selected, that is; otherwise OPL emulation comes into play, and it's... not good there).

**Doom**. Both Gravis UltraSound and SoundBlaster can be used for SFX and MIDI. SB digital audio sounds louder than it presumably should (for instance, source ports have comfortable sound level). MIDI on the other hand is quiet. GUS is quiet in both cases, and it seems that General MIDI also has lowered volume (why?!). So, because of constant action SB just "mutes" music by itself, and if we use GUS, then we loose details. Yet another problem is stereo separation with GUS: it works with `gusrate` set to 11025 or 22050 _only_. All, or almost all of that should be applicable for most of games that support both SB and GUS - and that's a whole lot.

**The Elder Scrolls II: Daggerfall**. Notable for using HMI. If GUS is selected for digital audio, then during testing audiosample is "crackling". In-game it gets more interesting: there are periodic "clicks", and right channel outputs sound with strongly lowered tone (turn up da bass!). Stereo separation is kinda working though. All of that could be (and probably are) just HMI or game's bugs, but noting it just in case.

**Quake**. Uses CD-DA for music, works good. Readme file states that SB and GUS MAX/PnP are supported for audio output (note - not original model; upd: support for original GUS was added with later patch), `techinfo.txt` - that only SB cards are. Sources have something on GUS. Game detects and initializes with GUS, but - no sound is output, no matter what DOSBox settings or game launch parameters are.
```
Sound Initialization
Sound Card is UltraSound
Sound Sampling Rate: 19293
```

**Crusader: No Remorse**. Supports GUS' hardware mixing. Uses tracker music. Also seems to support both 8- and 16-bit audio mixing/output. First, SB has different volume when selecting either DMA (8-bit) or HDMA (16-bit), with former being louder. Second, GUS seems to work in 16-bit mode, and it is close to being inaudible. No stereo separation either, no matter `gusrate` setting.

And some misc questions. As was already mentioned, SB cards have different filters, like brickwall/lowpass/whatever in SB16. How about making them optional? Accurate emulation is great, but there are people (myself included) that would prefer "clean" sound, and some may like sound of older SB models more.

Another question is - why 49716Hz is maximum frequency? From where comes that number, and what about people that have audio hardware capable of working at 96/192KHz?

Windows specific: how about adding direct OmniMIDI support? This software synthesizer can work with wrapper (and it doesn't for me, for whatever reason), but it's obviously slower than direct access. It has its own API, which is documented.

Phew... that was long enough. Please don't force me to do that again.

**Comment by volkertb** [comment] 2020-04-12 18:12
I'd like to add another (small) issue I noticed in DOSBox a while back, namely the fact that the upstream project makes no distinction between the Covox Speech Thing and the Disney Sound Source, even though these are distinct and mutually incompatible devices. The Former is a dumb DAC directly on the printer port, relatively easy to build as a DIY project in the form of a resistor ladder. The DSS however is a somewhat more complex device, since it has a FIFO buffer, which makes it somewhat easier to program for and less taxing on the CPU, at the price of supporting only a 7kHz fixed audio output frequency.

DOSBox in fact emulates a Covox Speech Thing and confusingly calls it a DSS in its documentation and in the config ini file.

Now, granted, this oversight in upstream DOSBox is not that big a deal in practice, since pretty much every game that supports these parallel port sound devices also supports superior sound cards, the proper emulation of which of course has a much higher priority. But such a mixup is not accurate and confusing, and it results in most games with Disney Sound Source support (such as Wolvenstein 3D and some later SCI-based Sierra adventures, to name a few) not to work with the so-called "DSS support" in DOSBox, when people try to play with that feature.

The PCEm project in contrast, emphasizing on hardware emulation accuracy over game performance, does emulate both the Covox Speech Thing and the Disney Sound Source correctly and accurately. Since both DOSBox and PCEm are GPL2-licensed, it would be no problem to "steal" the proper code from PCEm to fix such inaccuracies, right?

I'm not sure how the emulation quality of more sophisticated audio hardware like Sound Blaster and GUS compares between upstream DOSBox and PCEm.

But in a forked project with a compatible licnese, you get to pick and choose, right? 😉

**Comment by kcgen** [comment] 2020-06-07 00:59
@GranMinigun , 

Drew up the audio chain, in part just to get the lay of the land, but also pin-point areas to dig into (sorry, used a pencil.. maybe someone can tweak it and make it look better):

![dosbox audio chain](https://user-images.githubusercontent.com/1557255/83957623-58c4d000-a81e-11ea-908a-dd6c3db4a88a.jpg)

**Comment by kcgen** [comment] 2020-06-07 01:17
> why 49716 Hz is maximum frequency?  (for OPL devices)

For OPL devices, the following formula is used to determine the frequency number for a given note frequency (in Hertz) and block:

    f-num = freq * 2^(20 - block) / 49716

This formula can produce frequency numbers outside of the allowed 0-1023 range if the block number is too low, or the frequency is higher than the hardware can produce.

The sampling frequency of OPL2 and OPL3 chips is approximately 49716 Hz, leading to the constant in the formula. Occasionally this is rounded to 50000 leading to a small pitch variation if the wrong constant is used to play these songs. OPL2 cards like Adlib and early Sound Blasters used the 14.31818 MHz oscillator signal from ISA bus slot and divided it by four on card, thus running the OPL2 chip at 3.579545 MHz, which gets divided internally by 72 to get the sampling rate. OPL3 cards had to be compatible, and mostly the sound cards have separate 14.31818 MHz oscillator on board which the OPL3 uses directly, and this gets divided internally by 288 to get the sampling rate. 

**Ref:** http://www.shikadi.net/moddingwiki/OPL_chip

So we have two scenarios:

1. Run the OPL at 49716 Hz for the most accurate output from it, but then let dosbox's rudimentary resampler adjust frequencies down to the mixer's rate, which defaults to 44,100 Hz, and then finally have your audio API resample to the audio devices preferred rate, which typically defaults to 48000.

2. Run the OPL at 48,000 Hz to match both our mixer's output rate and audio device's preferred rate such that we fully avoid both dosbox's and the OS API's resamplers, and instead allow the OPL code to provide us with the slightly-lower-frequency data.

The second option is better if the OPL code gracefully handles different sampling rates.  I'd rather use the audio values straight from the OPL code than have them resampled twice-over, each time losing precision.

Given we have `compat`, `fast`, and `nuked` OPL types, it makes sense to see which work fine at 48 kHz versus those that would be better suited to using 49.x kHz and then resampling.

**Comment by GranMinigun** [comment] 2020-06-07 01:24
You monster.

By the way, any reasons to replace SDL with OpenAL? Just curious. ioquake3 and Yamagi Quake 2, for example, switched to OAL, and sound quality got better, but DOSBox is a different beast, so..?

**Comment by kcgen** [comment] 2020-06-07 01:59
Regarding all the volume issues, it's largely due to centrally mixing all dosbox's emulated device channels in one output (area **D** in the image where they funnel into the mixer).

The trouble is the mixing: say you've got two 16-bit audio streams both of which can "cap out" at full volume.  If you try to combined them, then many added samples will blow-past their 16-bit headroom and be clipped. So the simple "solution" is to cut their volumes by half then add.

DOSBox's mixer has a lot more than two feeds, plus it receives them in 8, 16, and even 32 bit depths. There's a bunch of tricky volume and scaling bit-shifts through the sound code, but the GUS code is especially full of it because it tries moves everything into 32-bit space with some hardcoded shifts (in hopes of retaining dynamic range).

After knocking out some of this hardcoded shifting and simply returning straight 16-bit values to the mixer, the GUS volume all of sudden became right on par with other volumes.  So this might be direction to go to address this at a fundamental level.

**Comment by kcgen** [comment] 2020-06-07 02:25
> any reasons to replace SDL with OpenAL

Very interesting suggestion! The knee-jerk response is that dosbox only produces a single audio stream, therefore doesn't need OpenAL's multi-channel, heterogenous format and rate handling. 

But all of dosbox's audio stretching, resampling, and volume shifting is specifically _to_ produce a single output stream.  OpenAL would free us from that complexity by allowing each devices to have its own audio channel at it's native, unadulterated bit depth and sample rate directly into OpenAL. 

- Read 16-bit values from CD-DA at 44.1 kHz and pass them straight into OpenAL.  
- Read 8-bit values at 22 kHz from the Sound Blaster and pass them straight into OpenAL.
- Generate a 16 kHz square wave from the PC Speaker, and pass that into OpenAL.

The code would absolutely be simplified and more readable, because all of this bit-shifting and scaling would be eliminated.

From a hardware perspective, this one-to-one output model is more realistic too.  The physical PC Speaker is tied to it's own speaker.  The Sound Blaster card has it's own dedicated line-out. If you had a GUS or MIDI device - those too had their own separate line-out's.

**Comment by kcgen** [comment] 2020-06-07 02:32
@GranMinigun If you want to try the current three audio PR fixes, you can do an octopus merge with:

``` shell
git checkout -B audio-test

git merge --no-edit kc/suppress-sb-dma-init-1 kc/zero-offset-speaker-1 kc/envelope-channel-on-start-1 kc/instant-launch-1

make distclean

./scripts/build.sh -c gcc -t release
```

Give it a whirl with something like Eye of the Beholder 3 (configured w/ SB for fx and music) which loves to pop the speaker.. it's a much nicer experience now.

**Comment by kcgen** [comment] 2020-06-07 05:21
More thoughts, and why I'm liking [OpenAL Soft](https://github.com/kcat/openal-soft) more and more:

- **Project is current.** Active development, using modern CI tools and C++ standards, and in wide-spread use.

- **Devices are threaded.** Connecting each device to an OpenAL source runs each process in its own thread, which matches actual hardware.  In a world of 4-core $10 Rpi-A's and 8-core cellphones, this would not only free up cycles to the dosbox CPU core, but also provide lower latency from bytes-to-ears.
 
- **Buffers-debloated**.  Each device writes directly into an OpenAL buffer - which is ultimately where I was hoping to get to in the CD-DA code (but only could get as far as the dosbox Mixer).  This will let us unwind layers of buffers in the device code that flow in the mixer, and from the mixer's various processors into SDL. This will make the code clearer and more direct in its operation.

As for cross-compatibility, compiler-compatilibity, ease-of-installation, and so on: I haven't looked into it that much yet.

@dreamer , curious what your thoughts are and if you have experience with it.

**Comment by kcgen** [comment] 2020-06-11 00:50
For future reference, attached is the Gravis Ultrasound SDK rev 2.22, released December 1994.
[Gravis_Ultrasound_SDK_rev2.22.pdf](https://github.com/dosbox-staging/dosbox-staging/files/4761961/Gravis_Ultrasound_SDK_rev2.22.pdf)

**Comment by kcgen** [comment] 2020-06-12 18:56
@GranMinigun, see [this post](https://github.com/dosbox-staging/dosbox-staging/issues/424#issuecomment-643057482) for progress on GUS stereo separation with a Gravis SDK-compliant, constant-power pan-table.

Give any of those test builds a spin with the attached Second Reality Demo using a decent pair of headphones.  The builds will show you which GUS voice channel is being panned and the position, so you can possibly see and hear it in tandem. 

This is a very small change, but I believe it's what was actually intended versus the more muddy table created by AMD.  Curious what you think!

**Comment by GranMinigun** [comment] 2020-06-13 08:06
Unfortunately, decent headphones have passed out, so I'm not sure whether I'll be able to hear all the details. I'm following your progress closely, and will try to check things out anyway.

**Comment by kcgen** [comment] 2020-08-02 19:57
@GranMinigun , https://github.com/dosbox-staging/dosbox-staging/tree/feature/gus-improvements-1 attempts to address these issues.  Listen to some comparisons here: https://github.com/dosbox-staging/dosbox-staging/wiki/Gravis-UltraSound-Enhancements.

**Comment by kcgen** [comment] 2020-08-04 01:23
Comparing the GUS enhancement branch versus SVN and X in Quake at 120000 cycles:

**DOSBox-SVN** 

- No sound effects in Quake. Sound Blaster is recommended
- https://www.vogons.org/viewtopic.php?f=31&t=20774&p=151291
- https://www.vogons.org/viewtopic.php?f=31&t=20774&p=151291

Given Quake performs all stereo and effect mixing in software (and generates a 16-bit stereo stream), there is zero benefit to use the GUS versus SB16. So this comparison is simply academic for the sake of this issue (as Quake was mentioned).

**DOSBox-X**

Sound effects work as expected. Some stuttering, but that's due to the 120,000 cycles.
During the transition to a new game, the last sound-effect played hitches for a split second while the map is loading. 

- ![2020-08-03_17-28](https://user-images.githubusercontent.com/1557255/89240452-f0416780-d5b0-11ea-8531-2adbbb03a41b.png)

- Download the audio file: [quake_001.flac.gz](https://github.com/dosbox-staging/dosbox-staging/files/5019463/quake_001.flac.gz)


**dosbox-staging**

- ![2020-08-03_17-32](https://user-images.githubusercontent.com/1557255/89240461-f899a280-d5b0-11ea-90cd-38418f62f11e.png)

- Download the audio file: [quake_000.flac.gz](https://github.com/dosbox-staging/dosbox-staging/files/5019546/quake_000.flac.gz)

**Comment by dreamer** [comment] 2020-08-23 19:53
Woah, this issue got closed automatically once I merged a PR with GUS improvements. This was unintentional of course, I expect we still have audio improvements ahead of us!

Reopening (unless @GranMinigun and @kcgen decide, that it's time to close this issue).

**Comment by GranMinigun** [comment] 2020-09-07 21:00
Guess the time has come for an intermission. [_E2M3 starts playing_]

From general problems, it seems that only lowered volume of 8-bit sound on 16-bit output is left. According to [this comment](https://github.com/dosbox-staging/dosbox-staging/issues/407#issuecomment-653786398), it seems to be an expected behaviour. Though I'd prefer to create a discussion - it would be nice to verify that's indeed what's happening on real hardware and whether there's any way to automagically compensate.

Another related, but probably game-specific concern is Crusader games: according to [this list](https://www.vogons.org/viewtopic.php?t=54670), it renders 16-bit audiostream, but selecting HDMA in sound setup still have lowered volume. Either the list is incorrect or...

Also regarding volume - any plans on increasing volume for OPL by ~150%? (421088a)

What about PC speaker? Should we open an issue for it? It's not really pleasant to my ears, but I don't remember how it should sound.

A gentle reminder: [this comment](https://github.com/dosbox-staging/dosbox-staging/issues/278#issuecomment-612655246) wasn't answered (at least I didn't see an answer).

If there's any interest in adding audio filtering, then we could create an issue for that. I know it won't be a priority, but discussion and tracking won't hurt. I personally only interested in possibility to turn it off (because I prefer bit-exact audio, yeah).

Same goes for theoretical possibility to replace DOSBox mixer with SDL2 one or OpenAL. (I remember whys and why nots.)

[There was some writing on used frequencies and stuff but it was stolen by UFO.]

Now, FluidSynth... we had a discussion on _one particular problem_. It's pretty serious, and I think I'll open an issue for that with all details currently gathered. Hope we could resolve it for 0.76 release.

Might and Magic III - it just needs MT-32 emulation. Discussion is in #257.

Crusader: No Remorse / No Regret - I wonder if it outputs audio on GUS in mono on real hardware too.

TES: Daggerfall - oof. HMI. I wasn't able to befriend it with GUS, even with the hint from Vogons.

Think I didn't miss anything? If you feel like it, I have nothing against closing this issue. Or editing first post. Back to testing GUS...

**Comment by kcgen** [comment] 2020-09-07 22:24
Thanks for all the testing and careful listening @GranMinigun, and for raising all the lose ends not explicitly addressed.
Suggest we try to close out what we can, and those remaining get spun off into new issues.

> it seems that only lowered volume of 8-bit sound on 16-bit output is left.

If there are output level differences, then they are caused by the game either programmatically (ie: software-mixing) or in the PCM sample recordings themselves (ie: 8-bit samples having full dynamic range, but 16-bit samples only recorded at a fraction of the available range). 

We can prove it to ourselves if we hold the source constant but just change the the audio card being driven by the software.  To do this, I used MPXPlay. 

Three scenarios:

1. 16-bit output using SB16
    - dosbox-staging config: `sbtype = sb16`
    - MPXPlay's INI: `SoundcardName=SB16`.

2. 16-bit output using GUS
    - dosbox-staging config: `gus = true`
    - MPXPlay's INI: `SoundcardName=GUS`.

3. 8-bit output using SBPro2
    - dosbox-staging config: `sbtype = sbpro2`
    - MPXPlay's INI: `SoundcardName=SBP`.

Also double check that the following neutral MPXPlay settings are configured:
``` ini
SoundcardFreq=0         ;manual setting of output freq (0:outfreq is controlled by freq of song(s))
SoundcardChan=0         ;manual setting of output channels (WDS,SBP or wav-output)
SoundcardBits=0         ;manual setting of output bits (at Audigy 2/4/LS,Live24,ICH4,IHD,wav-output,WIN\
,WDS)
SoundcardVol =100        ;-scv (0-100)(-1:get value from the card)
SoundcardTrbl=100       ;-sctr (1-100-200)(100:original tone, 0:get value from the card)
SoundcardBass=100       ;-scbs (hardware tone at SB16/AWE cards, else soft-tone by au-mixer)
MixerControl =0        ;+1:enable limiter, +2 allways use soft-tone (disable hw-tone), +4: 0.1% speed c\
ontrol (500-1000-9999)
SoundVolume  =100       ;-sv
AutoVolume   =0         ;-sva (slow volume correction (up and down too))
Surround     =100       ;-sr
Speed        =100       ;-sp
Balance      =0         ;(-99...0...+99)
Swapchan     =0         ;swap channels (reverse stereo)
LoudnessVol  =100       ;expand/loudness value of volume
```

For all three tests, play the same source audio file (suggest a ~1 minute FLAC audio track).
Start WAV capture in dosbox for the entire playback duration.
Open all three recordings in `audacity`, press `ctrl + A` to select the entire audio region, then **Effect** > **Amplify**, and see if dB gain needed to normalize the sequences differs.  These should be very close to indentical for all three recordings, meaning that output levels are the same across 8 and 16 bit (for all supported sound devices).


> whether there's any way to automagically compensate.

This can be done.. basically you keep track of the peak level over a rolling window of seconds, say 10 seconds. If the level is below the max by some threshold (say, below 80%) then you take `max / peak` and then you incrementally step the scaling up (by a very low dB amount) every ~1ms until the current target is achieved.  

This can be done very accuracy on a per-sample basis, but the dilemma lies in the rolling window.  Image you have a 2 minute intro sequence that's deliberately recorded at very low levels with subtle background noises and spooky creaks. The algorithm doesn't know the difference if this is deliberately at a low volume or if it's a game problem and shold be "pulled up".  So the auto-volume would soon have this operating at full dynamic range - which is /not/ what the game authors intended.

So then we might say, Ok - let's use a bigger time windows.  That does work - but then you drag out the periods before the pull-up occurs. 

In the end, for GUS, I opted to track the streams total peak output and report back to the user when the close the games and given the use the exact "pull up" percent and mixer command line to use if they want to normalize the game's audio.  I also prefer "sample exact" output and as little modification along the line, so I liked this as a compromise. 

We could add type of helpful output for all the channels.

> Another related, but probably game-specific concern is Crusader games: according to this list, it renders 16-bit audiostream, but selecting HDMA in sound setup still have lowered volume. Either the list is incorrect or...

The game's samples that it writes into the GUS's memory have extremely low levels; the only known solution is to pull it up via the mixer.  From the GUS diagnostic output, a value of `mixer gus 550` works well. 

Also note that the Crusader games only use a single output voice to the GUS and don't touch the pan register.  This indicates that these games are performing their mixing entirely software-side.  So they are not the fabled "excellent GUS examples" as many tend to tout them as.

Contrast this with another game that writes 16-bit PCM samples into the GUS's memory: Quake.  It has zero-issues with it's samples hitting the entire 16-bit dynamic range.

> Also regarding volume - any plans on increasing volume for OPL by ~150%? (421088a)

It's in the queue, but I haven't looked into this yet (or the justification leading to the 1.5 multiplier). 


> What about PC speaker? Should we open an issue for it? It's not really pleasant to my ears, but I don't remember how it should sound.

It should sound just like SVN (in a wave-form sense), but the output levels (and perceived volume) of square waves versus approximated sine-waves (ie: RealSound) should now be very close to on-par with each other. Contrast this with SVN where the sine-waves will be perceived to have much power volume versus square wave sequences.

We still have work to do to incorperate the PC Speaker patch used in ECE, this is in backlog list and separate issue not needed.

> A gentle reminder: this comment wasn't answered (at least I didn't see an answer).

> If there's any interest in adding audio filtering, then we could create an issue for that. I know it won't be a priority, but discussion and tracking won't hurt. I personally only interested in possibility to turn it off (because I prefer bit-exact audio, yeah).

Given dosbox itself doesn't have a "hardware noise floor" or hiss like the original hardware, there is little value in adding filtering unless someone wanted to experience lower frequencies ranges simply for the sake of nostalgia.  However, I don't see a need to work on such code (or introduce more maintenance burden) unless this is a sought-after feature.  If you want to run a straw-poll and we get a decent percent of people wanting this, then we can consider it! 

> Same goes for theoretical possibility to replace DOSBox mixer with SDL2 one or OpenAL. (I remember whys and why nots.)

Currently there are easy improvements to be made in the mixer and little to gain (while adding complexity and dependencies) by switching.  The SDL Mixer is poorly described.. it's actually an audio player that can mix one music stream while being able to play N other audio samples.  So it's more used by game developers who want to offload the audio work and just tell SDL to play "sound effect 1.ogg for 0.2 s" while "music-track-5.flac" is playing. 

> [There was some writing on used frequencies and stuff but it was stolen by UFO.]

Sorry; can you elaborate?

> Now, FluidSynth... we had a discussion on one particular problem. It's pretty serious, and I think I'll open an issue for that with all details currently gathered. Hope we could resolve it for 0.76 release.

We will fix the out levels and wrapping by switching to float output and using the soft limiter.  However you've mentioned per-voice level differences, which we have no way of programmatically influencing unless we started tampering with the actual MIDI commands handed to us from the game before we pass them onto FluidSynth for rendering. 

I'm not hopeful in this area, but please option an issue - maybe we can pull in the QSynth or FluidSynth developers and you can explain what you're experiencing to them. 


> Might and Magic III - it just needs MT-32 emulation. Discussion is in #257.

Integrating Munt is in the backlog.

> Crusader: No Remorse / No Regret - I wonder if it outputs audio on GUS in mono on real hardware too.

Need someone objective to test this - ideally simply capturing the output and giving us the audio recording. Feel free to open a game-specific issue for this with "Request for Help" level.  

> TES: Daggerfall - oof. HMI. I wasn't able to befriend it with GUS, even with the hint from Vogons.

We can look into it; suggest opening a game-specific issue.

**Comment by kcgen** [comment] 2020-12-15 03:06
Closing this thread. 
Lots of goods stuff was brought up and it resulted in hundreds of commits spanning roughly 7 months of work.
All generally-addressable issue have been resolved - ie: fixed, can't fix, or are game-side.
As recommended above, new tickets should be opened to address game-specific issues, one at a time.
Thanks for the thorough critique @GranMinigun!

**Closed by kcgen** 2020-12-15 03:06 UTC
Labels: discussion
