### ISSUE TITLE
Center mouse cursor before releasing it doesn't work with windows scale of 200%

### ISSUE THREAD

**Issue by Max833** [dosbox-staging/dosbox-staging#2610] opened 2023-06-17 16:04 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Newest dev build

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Center mouse cursor before releasing it (https://github.com/dosbox-staging/dosbox-staging/commit/bb294a0ed1a837b8763f25308c0f784e55d8732a) is a great idea and it works with 100% DPI scaling but not with 200%. The cursor isn't in the middle of the screen when DPI scaling is enabled and you release the mouse.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Select Start > Settings > System > Display and set the DPI scaling to 200%.
2. start dosbox and release the mouse

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment] 2023-06-17 20:15
@Max883 Thanks for reporting this. Are you able to test whether https://github.com/dosbox-staging/dosbox-staging/tree/fc/mouse-centering-fix-1 fixes the issue for you? Unfortunately, I'm a Linux user, and I can't reproduce the problem using Wayland.

**Comment by Max833** [comment] 2023-06-17 20:40
It is working perfectly now! Thanks a lot!! =)

**Comment by FeralChild64** [comment] 2023-06-17 20:42
Not so fast with closing - this still has to go through review and get merged to the main branch :)

**Closed** 2023-06-19 02:50 UTC
Labels: bug
