### ISSUE TITLE
Various issues with the HELP command

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1685] opened 2022-05-17 05:01 UTC
## Unlisted commands

The `HELP` command makes no mentioning of the following commands (I think I've listed them all). I think they should be included in the list, which would make them discoverable by the user just by looking at the output of `HELP /ALL`.

- ATTRIB
- AUTOTYPE
- BOOT
- CHOICE
- COMMAND
- CONFIG
- COUNTRY
- IMGMOUNT
- KEYB
- LOADFIX
- LOADROM
- LS
- MEM
- MIXER
- MOUNT
- RESCAN
- SERIAL
- SUBST

## Inconsistent behaviour

It also works inconsistently; this is the output of `HELP CALL`:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/698770/168730368-77552d42-2cac-4543-be3e-270cc50fe1a0.png">

Which is different to the output of `CALL /?`:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/698770/168730451-cd54cf09-288a-4536-a640-7cca14dd11e9.png">

For other commands, `HELP <cmd>` and `<cmd> /?`displays the exact same text:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/698770/168730539-677c3a1a-3d4d-4ce0-8bc9-5ed5618e65d5.png">

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/698770/168730716-ee51e328-c446-437f-ae8d-46d6953b3945.png">

I think there should be no difference between `HELP <cmd>` and `<cmd> /?` for any of the commands.

## Important commands are not listed

This is the output of the `HELP` command:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/698770/168731141-b213b66e-6887-40ef-bd7c-d9279e52e59a.png">

The choice of commands included in this short list is questionable. Without specifying the `/ALL` flag, I think the most useful commands should be listed, e.g. `MIXER`, `MOUNT` and `IMGMOUNT` should be included, and perhaps `CONFIG` and `RESCAN` too.

Whereas the current list includes commands such as `IF`, `GOTO`, `SET`, `SHIFT`, `REM`, `CHOICE`, `PAUSE` — I'd say these shouldn't be in the basic list but only in the full list, as most users will never write batch files, but would most definitely want to use the `MIXER` or `MOUNT` commands.

**Comment by shermp** [comment] 2022-05-17 05:11
This seems to effectively be a duplicate of  #1660 

Perhaps we should continue discussion there?

**Comment by johnnovak** [comment] 2022-05-17 05:25
> This seems to effectively be a duplicate of #1660
> 
> Perhaps we should continue discussion there?

Well, there's overlap between the two tickets but there's extra info in both ticket not present in the other. I think we can keep them separate for now?

**Comment by Burrito78** [comment] 2022-05-17 07:27
Big YES. The output of this help command is ancient and obviously was never discussed but is just a relic of its time.

Batch file commands are of no use for basic users and shouldn't be shown using help without parameters. This just buries the important commands which are VERY important for using DOSBox at a basic level.

Also DOSBox documentation inconsistencies are my pet peeve. They confuse new users, look amateurish and don't feel modern at all. Documentation shouldn't be A here and B there, it should all be written in one or two places and referenced/linked so there is as little duplicate documentation as possible. Sorry for the rant.

**Comment by shermp** [comment] 2022-05-19 21:58
So, I'm thinking of having a crack at refactoring (at least some of) the help system this afternoon/weekend. From what I'm gathering, the behaviour should be something like:
```
help
```
Display the most common commands, ideally on one screen, and not necessarily the ones hat currently show.

```
help /ALL
```
Should show help for all commands/programs,including those which are currently omitted. Should this be categorised at all into shell commands and other commands?

```
help cmd
cmd /?
```
Should both show the same help output.

Any other thoughts?

**Comment by johnnovak** [comment] 2022-05-20 00:40
Great, agree with the above list of things to do! 🚀 

> Should this be categorised at all into shell commands and other commands?

I think we should always think from the perspective of a regular end user when it comes to interface design. Would making that distinction be useful for the user, would it make their lives easier, or is that just some unnecessary detail? I tend to think that normal users don't care about that distinction at all (well, I know I don't when I'm just using DOSBox), and having two different alphabetically sorted lists would make it difficult to find the command you're looking for.

But if we decide that info is really useful, we could still have our single A-Z sorted list and also mention per command whether it's a built-in or an external command.

**Comment by kcgen** [comment] 2022-05-20 01:13
Yeah - it's definitely balancing act; how much of a helpful "cheat sheet" can we pack on a page?

I was thinking something like this (obviously a lot simpler):

![Unix-Linux-Command-Reference](https://user-images.githubusercontent.com/1557255/169428366-dcc8876a-2ecf-4de8-830f-45e07c08e7f1.png)

Where our categories might be:
 - filesystem
 - networking
 - media-mounting
 - ...

Then again, even that assumes some knowledge ... these might be foreign to a 100% tablet gamer or someone whose only owned an iPhone.  But, we've gotta start somewhere!

**Comment by shermp** [comment] 2022-05-20 01:22
There's also the `intro` command, so I think `help` should be used as a reference for commands, rather than a complete "beginners guide"

**Comment by johnnovak** [comment] 2022-05-20 01:44
> Then again, even that assumes some knowledge ... these might be foreign to a 100% tablet gamer or someone whose only owned an iPhone. But, we've gotta start somewhere!

Yeah, so when compiling the list I think the best approach would be to think like this: what would a typical novice user need for installing, configuring and playing a typical game? So definitely no commands that are only useful in batch files, that's an advanced.

> There's also the `intro` command, so I think `help` should be used as a reference for commands, rather than a complete "beginners guide"

I think the `intro` should give detailed explanations of the useful commands, maybe one or two more pages could be added to it (but not too many). Then the short `help` output should list at least the same commands from the `intro` as a quick-reference guide, and possibly a few more (for people who've read the `intro` text already and are vaguely aware of what can be done, but don't remember the exact command names).

**Comment by shermp** [comment] 2022-05-24 11:06
So, I have been working on this.

`help /all` now shows all available commands:
![image](https://user-images.githubusercontent.com/14854761/170019920-5f13edd3-50b5-4465-aa50-736c80b66389.png)
![image](https://user-images.githubusercontent.com/14854761/170019984-5756584c-3cc1-4a7c-adfd-f0361c770143.png)

`help <cmd>` and `<cmd> /?` now show the same help text:
![image](https://user-images.githubusercontent.com/14854761/170020185-adf814e0-28e5-4c9c-8566-9425987fc17a.png)
![image](https://user-images.githubusercontent.com/14854761/170020249-2d57c6f8-ca2f-4a9f-b19e-1c94d78b1ef8.png)

The help for all shell commands can also invoked with `-h` and `--help` as well as `/?`. I haven't gone through all the programs yet though.

Code probably needs a bit more cleanup, and I we need to come up with a list of 18-20 programs and commands to list with the bare `help` command.

BTW, I've noticed that `config`'s help could use some love.

**Comment by johnnovak** [comment] 2022-05-24 13:04
Noice! :)

> BTW, I've noticed that `config`'s help could use some love.

Yeah, I've noticed too and definitely agree with you.

**Comment by kcgen** [comment] 2022-05-24 14:18
Looks great!

> BTW, I've noticed that config's help could use some love.

Let some of that love flow to the wrapped `IMGMOUNT` summary, too :-). 
Maybe something like:
 - `"Mounts CD (bin/cue, iso) and floppy (img) images"`, or
 - `"Mounts CD (bin/cue, iso) and floppy (img) images to a DOS drive"`

**Comment by johnnovak** [comment] 2022-05-24 22:51
Small comment: the `MOUNT` command should start with an uppercase letter.

**Comment by shermp** [comment] 2022-05-24 23:12
> Small comments:
> 
> * the description of the `MOUNT` command should start with an uppercase letter.
> * the description of the `CONFIG` command should end with a period.

I haven't changed any messages (yet), so it currently uses whatever is available.

Another detail is that not all programs and commands have a "short" help line. In such cases, I'm using the first line from the "long" help. That's what's happening with `CONFIG`.

**Comment by johnnovak** [comment] 2022-05-24 23:16
> > Small comments:
> > 
> > * the description of the `MOUNT` command should start with an uppercase letter.
> > * the description of the `CONFIG` command should end with a period.
> 
> I haven't changed any messages (yet), so it currently uses whatever is available.
> 
> Another detail is that not all programs and commands have a "short" help line. In such cases, I'm using the first line from the "long" help. That's what's happening with `CONFIG`.

Cheers, makes sense!

**Comment by Burrito78** [comment] 2022-05-25 07:21
List of default commands for HELP:

CD
CLS
CONFIG
COPY
DEL
DIR
EXIT
IMGMOUNT
INTRO
MD
MIXER
MOUNT
RD
REN
RESCAN
TYPE

Any i missed?

**Comment by Burrito78** [comment] 2022-05-25 08:53
Thanks, the list could be broken down into two parts for better readability. 
I'm not happy with "File commands" and "DOSBox commands" though. Maybe something more elegant could replace these.

-File commands
CD
COPY
DEL
DIR
MD
RD
REN
TYPE

-DOSBox commands
CLS
CONFIG
EXIT
IMGMOUNT
INTRO
MIXER
MOUNT
RESCAN

**Comment by shermp** [comment] 2022-05-25 09:11
Remember, any grouping would eat into the number of commands/programs that can be displayed on the single page, and I think for the "common" help, keeping it to a single page is desirable. We have a max of 25 lines to play with.

**Comment by johnnovak** [comment] 2022-05-25 10:36
I agree, short help should definitely be a single page. What we have now would fit on a 80x25 screen nicely with the proposed categorisation, assuming single-line short descriptions (which is the case already for these commands, if I'm not wrong):

![image](https://user-images.githubusercontent.com/698770/170242981-13efdad0-ca83-4e10-b98a-ca9bf53d5437.png)

We could even add up to two extra commands if we really wanted to! 😉

**Comment by johnnovak** [comment] 2022-05-25 10:43
@shermp 🥇 for removing the `<` and `>` characters surrounding the commands. That was completely unnecessary and didn't add any value, only some potential confusion, and took up valuable space. 👍🏻

**Comment by johnnovak** [comment] 2022-05-25 10:48
Another small inconsistency thing. In the list of commands we use upper case and blue colour for the command names, but in the detailed help for the individual commands we use lowercase and green colour.

Wouldn't it make sense to use the same colour and casing consistently? Then the user would go, "okay, this is in lowercase and it's green, so that's a command!" I think colour coding is good, but then it needs to be applied consistently across the board.

I like the lowercase bright green personally for the commands, but happy with whatever, just make it consistent.

![image](https://user-images.githubusercontent.com/698770/170244995-e5f96089-5a91-4474-a203-48c8b5b9a999.png)

**Comment by shermp** [comment] 2022-05-25 11:05
> @shermp 🥇 for removing the `<` and `>` characters surrounding the commands. That was completely unnecessary and didn't add any value, only some potential confusion, and took up valuable space. 👍🏻

Yeah, I didn't like the `<` and `>` either. Didn't actually save any space though, because I replaced them with spaces to keep the same amount of padding. Can adjust to give another couple of characters if needed though.

Don't mind what colour we use, it's easy enough to change (and I no longer have to lookup *<redacted>* ANSI codes).

**Comment by johnnovak** [comment] 2022-05-25 11:20
> While we're at it, why not add a "useful for batch file" grouping for `help /all`?

Yeah, so that's a variation on @kcgen's "cheat sheet" idea, and I think it's worthwhile to do it. I'd say grouping the commands is more useful than a simple A-Z ordered list.

How about these groups for the full help?

- File commands
- DOSBox commands
- Batch scripting
- Misc (for stuff like `VER`, `MEM`, `LH`, etc.)

I'm not really happy with it, it's just a start; most likely we could come up with better categories, so post your ideas 😄

**Comment by shermp** [comment] 2022-05-25 11:33
> I'm not really happy with it, it's just a start; most likely we could come up with better categories, so post your ideas 😄

Naming things is Hard (tm)

**Comment by shermp** [comment] 2022-05-26 07:01
Ok, I've refactored the refactor, Will open a draft PR once all CI workflows complete.

**Comment by johnnovak** [comment] 2022-07-23 23:59
Work on this item has been completed, just keeping it open for documentation purposes.

**Comment by Burrito78** [comment] 2023-05-13 14:40
I think it would be better to create a new issue for the documentation and link the closed issues there. Less clutter.

**Closed by Burrito78** 2023-05-13 14:40 UTC
Labels: documentation, enhancement
