### ISSUE TITLE
SSE 4.2 listed as hardware requirement but does not appear to be used

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2955] opened 2023-09-22 18:23 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On the website, SSE 4.2 is listed as a requirement on x86:  https://dosbox-staging.github.io/downloads/linux/#hardware-requirements

However, I don't think we're setting the correct compiler flags to even utilize this.  We need to be setting `-march` to whatever the minimum supported CPU is.  https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

Doing a `git grep _m128` (to look for SIMD intrinsics) shows Voodoo emulation doing some SSE2 stuff.  SSE2 should be fine with the default `march` as I believe every x86_64 CPU supports SSE2 at a minimum.

The only other place I'm seeing intrinsics is inside `src/libs`.  `dr_flac.h` (part of SDL Sound from the looks) has a lot of it in particular, including SSE4.1.  However, it's all behind `#ifdefs` that I don't think we're defining anywhere.  I wouldn't be surprised if this is getting built without SIMD at all.  It looks like these files just got copy-pasted and we're compiling without running the build system they were meant to be built with.  The `meson.build` file in that directory is very bare bones.

I noticed this because I was trying some SIMD for the video scaler and the SSE4 intrinsics wouldn't compile without adding `-march=native` to the meson build flags manually.  I'm getting close to 10x the performance with this so I think it's worth getting these compile flags right :smile: 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-09-22 19:35
Good catch, @weirddan455 !

Prior to moving to Meson, we were using OS-based minimum hardware requirements.

So for example:

The oldest still-in-support MacOS on x86-64 required Nahelem CPUs, so we had:

`cflags_release+=(-march=nehalem)`:

https://github.com/dosbox-staging/dosbox-staging/blob/release/0.76.x/scripts/automator/build/clang-darwin_x86_64

And most in-support Linux OSes systems were similar:

```
# Enable math vectorizions using instructions available in circa-2008+ CPUs
x86_math=(-mfpmath=sse -msse4.2)
cflags_release+=("${x86_math[@]}")
```

https://github.com/dosbox-staging/dosbox-staging/blob/release/0.76.x/scripts/automator/build/gcc-linux_x86_64


I wonder if we can even bump that up further now? 

Of course, for users compiling at home on even older hardware, we could even switch to `-march=native` or `-mtune=native` (on Arm), and wring out whatever instructions the host can offer.  


The further CPU instructions our CI release binaries can support are capped by the oldest hardware supported by "big three" in-support OSes:

 - Win10 22H2 (21H2 went EOL in July!)
 - macOS 11 Big Sur (hanging on... Goes EOL Nov!)
 - Debian 10
 - Ubuntu 20.04
 - Fedora 37

The above users can truth that our zip releases will run straight away on their machines. 

But for other users, they can simply build from sources.

**Comment by shermp** [comment] 2023-09-22 19:36
If you are experimenting with SIMD in new code, perhaps have a look to see if a library like https://github.com/google/highway (or similar) would be useful to avoid writing architecture specific SIMD code.

**Comment by weirddan455** [comment] 2023-09-22 20:51
>  Our limit to offering SIMD in our CI release binaries is capped by the oldest hardware supported by "big three" in-support 

We're already exceeding that with requiring SSE 4.2 then, I believe.  Debian 12 and Windows 10 still offer 32 bit builds.  Even if we ignore that and say we're only supporting 64 bit, I'm pretty sure no one is requiring specific SIMD instructions.

As far as I know, all the big Linux distros are still comping for "generic x86_64" meaning it should theoretically be able to run on any 64 bit x86 CPU.  Ubuntu only lists as CPU requirement "2ghz dual core processor".

Windows has a big ole list of "officially supported CPUs" but I don't put too much stock in it.  My CPU is too old to be on that list.  It still runs the latest Windows 10 just fine and even if it didn't, Microsoft is still pushing me updates regardless :laughing: 

That said, I think it's fine to just pick some minimum CPU to target and make that our requirement for binary builds regardless of what the OS is doing.  We just need to re-add that to our build system as it seems that flag has been forgotten.

>  If you are experimenting with SIMD in new code, perhaps have a look to see if a library like https://github.com/google/highway (or similar) would be useful to avoid writing architecture specific SIMD code.

That's probably a good idea.  It's only a small hot path I'm writing SIMD for.  I just wrote it with Intel intrinsics for now just because adding a library to a build system is pain.  It'd probably be easier to just write an ARM version to be honest.  But I agree a cross platform solution would be ideal.

**Comment by Torinde** [comment] 2023-09-23 11:08
> We're already exceeding that with requiring SSE 4.2 then, I believe.

Correct. Only macOS 12 is a little bit ahead - oldest CPU officially supported has AVX.

Above you look at the minimum requirements, but when somebody builds himself - will it automatically use the most advanced instructions available on that host? E.g. will most users get AVX2 and Zen 4 users get AVX512? Or they'll need to add a flag/option to enable that when building?

**Comment by johnnovak** [comment] 2023-09-23 11:52
> SSE4. 2 was first introduced in Intel Nehalem core in November 2008. The first AMD CPUs with SSE 4.2 support were launched in October 2011. 

Why does this all even matter? If someone uses a CPU older than 12 years, well, time to upgrade 😄

**Comment by Grounded0** [comment] 2023-09-23 15:21
It would be interesting if someone did testing what is the minimal x86-64 CPU feature level required to run this. Is it SSE3, SSSE3 or SSE4.1?

If that information was provided we could update our website with that information.

**Comment by weirddan455** [comment] 2023-09-23 17:17
>  Above you look at the minimum requirements, but when somebody builds himself - will it automatically use the most advanced instructions available on that host? E.g. will most users get AVX2 and Zen 4 users get AVX512? Or they'll need to add a flag/option to enable that when building?

You have to add a flag that we currently don't have in our build system.  `-march=native` tells the compiler that it's free to use any instruction that the CPU you're currently building on supports (and not just for code explicitly using SIMD intrinsics but anywhere in the codebase the compiler sees fit.)  However, that means the resulting binary will not work on older CPUs.  Doing `-march=nehalem` or whatever we want to say our minimum support CPU is is probably what we want to use in CI when it's building a binary meant for release.

>  It would be interesting if someone did testing what is the minimum x86-64 feature level required to run this. Is it SSE3, SSSE3, SSE4.1 or actually SSE4.2. If this was confirmed to run on Intel Core 2 (Merom) that would be SSSE3 which is the minimum system you would want to run DOSBox Staging anyway. These systems also provide OpenGL 2.1 support so they're actually useful.

>  If that data was provided we could update our website with that information.

I think we don't need any SIMD features at all, strictly speaking.  There's not very much explicit SIMD code in Staging and where it does exist, there's also a plain C++ version for compatibility.  Also, the binaries we have been building since the switch to Meson have only been using SSE2 (you get that one "for free" when compiling for x86_64 since all 64 bit CPUs support that).

The main advantage to enabling newer features would be to allow the compiler to better optimize (potentially, we would need to benchmark to see how much this really helps in practice) and then balance that versus how much do we want to support old CPUs.

For what it's worth, the SSE 4.1 instructions I was trying out are looking to be the wrong tools for what I was trying to do anyway so my FFmpeg scaler routine may end up only needing SSE2 regardless (and I will still have a plain C++ version for ARM and whatnot).

**Comment by weirddan455** [comment] 2023-09-23 17:45
To focus back in a bit, I think we should done one of the two:

1.  Make no changes to our build system and remove the SSE 4.2 requirement from the website.  The binaries we're currently generating don't actually have this requirement.  This means our binaries will work on all x86_64 CPUs.

2.  Add compiler flags to our build system to actually generate binaries utilizing SSE 4.2 that we're claiming to require.  This maybe gives better performance (probably not a huge amount, maybe I'll benchmark at some point to find out) at the expense of losing compatibility with old CPUs.

**Comment by kcgen** [comment] 2023-09-23 18:47
I would lean toward #1, @weirddan455. 

During the transition from our build templates (which included these flags) to Meson, @dreamer and I did extensive performance comparisons and found almost no measurable performance gain when letting the compiler use > SSE2 instructions. 

Infact, LTO provides more gain (about 3 to 5% depending on the tests) versus SIMD. 

Also, back then we had users complaining about unsupported instruction crashes because they were running quite old processors. 

So the benefit (universal CPU support) very much outweighed the gains. 

---

The biggest problem is that compilers do a terrible job of autovectorizing even when SIMD instructions are available. 

Build with `meson setup -Dautovec_info=true ... ` to see the annotated vectorization attempts (works on Arm, too). In most cases the compiler will fail to autovectorize. 

The biggest chunk of time goes to the dynamic cores, which themselves are constructing an instruction sequences to run at the host-level, and in that process perform lots simple operations like memory reads and writes (from emulated DOS memory space).

**Comment by Grounded0** [comment] 2023-09-23 18:51
@kcgen

Can i rewrite those SSE4.2 texts to x86-64 CPU required? I think this is the best way to go for now.

**Comment by kcgen** [comment] 2023-09-23 18:58
The big SIMD wins like you mentioned are in the video handling code.. big loops that chew through pixels. 

If it's easy enough to code by hand, then maybe that's the perfect sweet spot (just a handful of NEON and SSE2.. and we're done for many many years). 

The sweet thing with Highway is we can write SIMD that still looks like C++, and behind the scenes Highway compiles N instances of the block with AVX2, AVX, SSE 4.x, SSE2, and similarly on other platforms (NEON, Altivec, etc). 

So we gain in maintainability and performance, because every user gets the maximal implementation for their hardware. 

We also gain by outsourcing future technology conversation to Google's engineerers.. who added RISC-V and other instruction sets. So we get that for free just by updating Highway.

The gains have to be worth the addition though. Who knows, maybe there's a lot more we can do in Voodoo and even vga_draw.

**Comment by Grounded0** [comment] 2023-09-23 19:41
I've updated the pages here. Feel free to PR since i don't have the energy:

https://github.com/Grounded0/dosbox-staging.github.io/blob/master/downloads/linux/index.html

https://github.com/Grounded0/dosbox-staging.github.io/blob/master/downloads/macos/index.html

https://github.com/Grounded0/dosbox-staging.github.io/blob/master/downloads/windows/index.html

Looks much nicer and less scary because 90 % of the users don't know what SSE4.2 is.

**Comment by kcgen** [comment] 2023-09-23 19:52
Thanks @Grounded0; it needs to snipped from mkdocs's source markdown files. Looks like these were added in 
c785afcbb (with lots of good other info); so perhaps a partial revert would work. 

I'm unfortunately not at my desk and not able to progress this yet.

**Comment by Grounded0** [comment] 2023-09-23 20:18
Updated mkdocs:

https://github.com/Grounded0/dosbox-staging/blob/main/website/docs/downloads/linux.md

https://github.com/Grounded0/dosbox-staging/blob/main/website/docs/downloads/macos.md

https://github.com/Grounded0/dosbox-staging/blob/main/website/docs/downloads/windows.md

Omitting information about MouSSE from macOS page because all Macs officially supported by us implement SSE4.2 in hardware anyway.

**Comment by weirddan455** [comment] 2023-09-23 20:19
@kcgen I will agree with your assessment then.  If there's minimal performance gains to be had, it doesn't make sense to break compatibility.  I also just finished re-writing my code to use only SSE 2 instructions.  The couple of SSE 4 instructions I was using were incorrect for what I was doing regardless of what was decided here.

So, we just need to update the website to remove that section about SSE 4.2 since we're not actually requiring it and then this ticket can be closed.

We may also want to investigate the `#define` macros for SDL Sound to be sure it's building with at least SSE 2 support.  I am suspecting we may be getting a scalar-only build.

**Comment by johnnovak** [comment] 2023-09-23 21:57
I'm happy with either solution, frankly, I don't care about not supporting older than 12 year old CPUs, and yeah, you can't rely on compiler auto-vectorisation. The problem is that even if something gets auto-vectorised, you make an innocent looking change and suddenly it's not vectorised anymore. That's the main reason why people still write such code by hand (or ise libraries); to guard against random performance regressions.

But manually vectorised code is ugly as hell, and you need to design your algorithms around it. There aren't many obvious gains to be had from vectorisation in DOSBox, IMO. At the same time, there are vastly more important optimisation targets: moving stuff out of the main loop. Mnually vectorised code should be a last resort, and frankly, I don't think we'll ever need it and/or do it. It's a pain to write, understand, and maintain.

Also, pointing out that Windows 7 is not supported because the Glib fiasco with Fluidsynth. If you guys want to improve compatibility with people on older _computers_, getting Win 7 compatibility back would be far more important than SSE 4.2

Also, I agree that the SSE 4.2 requirement on the website is a bit scary. Best to remove it, regardless of whether we technically require it or not.

**Comment by GranMinigun** [comment] 2023-09-23 23:14
`-march=x86-64-v2` is a thing. Just saying.

**Comment by Kappa971** [comment] 2023-09-24 00:18
```
CPU:
  Info: dual core model: Intel U4100 bits: 64 type: MCP arch: Penryn rev: A
    cache: L1: 128 KiB L2: 2 MiB
  Speed (MHz): avg: 1200 min/max: 1200/1300 cores: 1: 1200 2: 1200
    bogomips: 5187
  Flags: ht lm nx pae sse sse2 sse3 ssse3
```

Old netbook from 2009 with Debian. The only Linux PC I have, Windows 10 is usable but heats up the CPU too much. I even tried Windows 11 but it consumes too much ram (I only have 4GB of ram), heats up the CPU and the useless built-in "graphic" card is too crappy for the unnecessarily heavy GUI of Windows 11 (the new interface is nice but I don't understand why It's so heavy, sometimes it feels slow even on my desktop PC).
Anyway, I often ran DOSBox Staging on this PC to generate the translation files, not knowing that I was running DOSBox Staging on an unsupported CPU. Obviously I don't play games on this PC, so I don't know if DOSBox could crash.

**Comment by weirddan455** [comment] 2023-09-24 00:59
@Kappa971  You should be fine.  The x86 builds haven't been requiring SSE 4.2 for quite a while now from my understanding.

It also tends result in very reproducible and abrupt crashes if you try and run a binary compiled for too new of a CPU.  As soon the CPU sees an instruction it doesn't understand, it raises an exception and kills the whole process so it should be very obvious if that was the case.

It sounds like we're all in agreement that that section should just be removed from the website as it's no longer accurate.

**Comment by Torinde** [comment] 2023-09-24 07:41
There is also the point of previous Staging versions. 
- In the release notes it's stated that macOS and Linux require SSE4.2 from the first release and Windows for version 0.75.1 or newer.
- from above I understand that from some (which?) subsequent version that requirement was dropped (to SSE2? or to the minimum on CPUs required for the relevant OS? Vista and 7 don't require even MMX, macOS 10.15 CPUs support at least AVX, but Rosetta 2 maxes out at SSE4.2).

I think a note should be added to the relevant versions in "Older builds" (where most people won't look anyway, so less danger of scaring somebody) - "requires SSE4.2" or "requires SSE2", etc.

> Windows 7 is not supported because the Glib fiasco with Fluidsynth

Isn't that Vista problem? Last time I tried - Win7 was working with the MSVC builds.


As for raising again the floor to gain performance - agree with above conclusions. Just a note - it seems [AVX/2/512 helps a lot for PS3 emulation](https://whatcookie.github.io/posts/why-is-avx-512-useful-for-rpcs3/), so maybe will help with Voodoo as well?

**Closed** 2023-09-25 21:59 UTC
Labels: bug, documentation, website

**Comment by Torinde** [comment] 2023-10-29 07:56
On Windows, on a laptop with SSSE3 and no SSE4:
- 0.75.2 onwards Staging starts with output=surface or texture (output=OpenGL gives blank screen, but commands still work if blindly written)
- 0.75.1, 0.75.0, 0.75.0-rc1, 0.75.0-pre - don't start at all, give errors about various DLLs such as MSVCP140.dll, VCRUNTIME140.dll, Zlib (I don't know if those need SSE4.1 or SSE4.2 or something else that laptop is lacking)

So, assuming release notes are correct, then the only version requiring SSE4.2 is 0.75.1. I suggest changing [the website](https://dosbox-staging.github.io/downloads/windows/#older-builds) accordingly (e.g. mention "requires CPU with SSE4.2" only on 0.75.1 - and don't mention anything about CPU on the other versions.

Also, I couldn't run Staging if its files are on a SMB share/UNC path. Is somebody able to do that (e.g. is it a problem only in my setup)?

**Comment by Grounded0** [comment] 2023-10-29 11:03
No we're not going to start editing our web page for old ass releases like 0.75.1. 🙂

**Comment by johnnovak** [comment] 2023-10-29 12:59
Older releases are really for bisecting bugs. I might update the SSE info one last time, but yeah, what @Grounded0 said.
