### ISSUE TITLE
Shadow Warrior's sound hiccups with CD music on (imgmount only)

### ISSUE THREAD

**Issue by InsufferableHexavaxxedNPC** [dosbox-staging/dosbox-staging#3030] opened 2023-10-20 09:01 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Greetings.

Shadow Warrior's sound will hiccup during the intro and also when navigating the menu IF music's turned on within the game and the audio CD has been mounted using imgmount: real hardware CD-ROM drives or a virtual one like ImgDrive will not introduce any hiccups, but I avoid them in this context because the API responsible for handling the necessary calls (particularly track looping) has been hopelessly broken since Vista (some people say XP, but I never experienced this on XP), and a number of "fixes" out there seldom ever work correctly, so at the end, it's like trading malaria for sickle cell.

This has been a problem for as long as DosBox has been able to run Shadow Warrior with CD music on; This is not something introduced by Staging, but I think it's still worth reporting in case there's hope for improvement.

Other games like Blood, Quake, Carmageddon, Redneck Rampage, etc, seem to work OK, but this one has been picky from the get-go.

Needless to say, such a thing never happened to me on real, period (or newer) hardware. Actually, the first time I tried this game was on a 50-something mhz 486 with a 2x CD-ROM drive and even on that piece of junk, sound was fine.

This happens with a default config (edited only to mount the C drive and the CD image), as well as with my high-performance modification.

The audio in raw video recordings for SW has no hiccups, so it's not worth uploading.

Best regards and sorry for any inconvenience.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment] 2023-10-20 09:36
I played through Shadow Warrior 1.2 with no RedBook CD audio issues. Can you share a recording or may the disc image be corrupted? RedBook CD audio is a very delicate format since it has little to no error correction.

**Comment by kcgen** [comment] 2023-10-20 09:42
Steps to reproduce the behaviour.

Explain how to reproduce
1.
2.
3.
Download URL of affected game or software

No response
Your configuration

No response

---

@InsufferableHexavaxxedNPC : please provide these fields so we can repro the issue.

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-20 09:56
Oh no no no! I'm not talking about the music (image created from my original, redump-validated paid-for CD) which plays back perfectly fine, but the sound itself, that is, everything that isn't RedBook audio, and it's not during gameplay, it happens exclusively during the intro screen and menu navigation.

Here's a sample of what I'm talking about, though it's not my video, and it can get worse depending on the setup: https://www.youtube.com/watch?v=a-fr0x4ok7A

Listen carefully the first seconds as Low Wang's laugh kicks in.

**Comment by Grounded0** [comment] 2023-10-20 10:05
That audio glitch at start is due to Build engine switching to a Smacker video it plays back to the user before switching back to the Build engine. I'm no Shadow Warrior fan or preservationist so maybe i'm missing something.

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-20 10:09
> That audio glitch at start is due to Build engine switching to a Smacker video it plays back to the user before switching back to the Build engine. I'm no Shadow Warrior fan or preservationist so maybe i'm missing something.

Don't take my word for it because it's been a while since I messed around with this, but I think Shadow Warrior had the animation frames and audio stored in the grp and played it back using it's own code.

**Comment by Grounded0** [comment] 2023-10-20 10:21
I see no `.SMK` files on the disc image so the video is indeed bundled into `.GRP`. Maybe we can run this on native hardware. If native hardware also does this then we can do nothing about it.

**Comment by Grounded0** [comment] 2023-10-20 10:26
If that audio glitch is from the game engine loading the video animation on the fly there's little we can do about it. I can definitely reproduce it myself. These things were extremely rudimentary back in the day and people often were happy if the games worked at all with their current `AUTOEXEC.BAT`, `CONFIG.SYS` and `DEVICE` mix.

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-20 10:33
@kcgen: I'll be sure to provide what's missing, but I cannot do it right now. Thing is , though, this has been happening to me on every Windows PC I've owned since forever, so I thought to myself this had to be a minor, yet known issue, but guess I was wrong.

@Grounded0: sound hiccups happen when navigating the menu as well, so I wouldn't say it's exclusively linked to media playback. I think I'm gonna have to record the whole thing with some other app to fully show what I mean.

**Comment by Grounded0** [comment] 2023-10-20 10:35
I tried the startup sequence with only max 30 % CPU cycles which results the intro having no audio glitch but then the game is unplayable garbage.

**Comment by kcgen** [comment] 2023-10-20 10:38
> @kcgen: I'll be sure to provide what's missing, but I cannot do it right now. 

Ok great; will investigate at that time.

**Comment by weirddan455** [comment] 2023-10-20 10:45
For what it's worth, I've noticed some intermittent audio stuttering on my machine too (though mostly with MT-32 and Fluidsynth MIDI sound).  It's been tricky to reproduce so I haven't investigated too much.

@kcgen pointed out a program called gamemode in Linux that can help alleviate these issues by providing higher priority to the Dosbox process (among other low-level optimizations).  Maybe there is some similar optimizations for Windows?  I know at the very least you can try upping the priority in task manager.

But yeah, we really need more information before we can investigate this.

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-21 06:28
[sw.zip](https://github.com/dosbox-staging/dosbox-staging/files/13059999/sw.zip)
[dosbox-staging.txt](https://github.com/dosbox-staging/dosbox-staging/files/13060001/dosbox-staging.txt)
[stderr.txt](https://github.com/dosbox-staging/dosbox-staging/files/13060002/stderr.txt)
 > we need to test with your exact game image

Done.

http://redump.org/disc/2010/

Notice that it doesn't quite seem to matter what image I'm using. For the longest time I'd use my CloneCD image that I created with an insane 1x, overkill "every useless bit counts" approach, then I created another one using the method from the redump wiki and finally I downloaded a redump copy from a trustworthy source that perfectly matched the one I created myself, but no difference so far as I can tell; they all work ok with mount, but glitch out with imgmount.

> your exact config files

Done, but I remind you that it happens with default as well.

> and know exact steps (in-game) how to reproduce the audio skips.

Done. Just run sw.exe, watch the whole intro and start a new game. There really isn't a whole lot to it, because the hiccups are absent during actual gameplay.

Attached also is stderr.txt and a FLAC audio recording of a 30sec session, showing somewhat more accentuated hiccups than what you hear on that youtube video.

Bets regards.

**Comment by johnnovak** [comment] 2023-10-24 22:14
We eventually got there @InsufferableHexavaxxedNPC, but in the future please fill out the issue ticket correctly and preferably use the minimal amount of words. Those questions in the issue ticket are there for a reason; we are inclined to gnore/close tickets going forward that are not filled out with all the info we ask for. We are a small team and asking for clarifications takes too much time and energy for us.

If someone looks at the issue ticket in the future, lots of relevant info is missing and one has to go fishing for them in this longish comment thread. I too thought you're talking about the CD Audio music, "sound" is a very vague term and so is "hiccups". At minimum I'd expect a recording demonstrating the issue, the exact config you used, the hash of the dev build if not using a stable release, and a link to the redump image you're using. And all that info in the top comment, not spread around.

Thanks for your understanding, filling out tickets correctly is in everybody's interest 😄

**Comment by InsufferableHexavaxxedNPC** [comment] 2023-10-25 03:11
Absolutely; sorry about that stinking mess.

I normally get very little time for online stuff so I was hoping it would be clear enough from a quick description and the fact that, in my very personal experience, said "hiccups" have been so obvious and prevalent for so long and on so many different systems that there was "no way" someone else didn't experience them as I did. But that's not how the real world works. 

Message acknowledged, moving forward :)

**Comment by Grounded0** [comment] 2024-07-24 09:51
Played through both episodes and still haven't noticed any problems with the CD audio. Also the CD audio sounds just fine when navigating the menus. The only thing I can confirm is that when I use high cycles value like max 80 % on my system there is a tiny sound hiccup as the game engine loads at the start of the game. I can't reproduce this at cycles max 50 %:

<img width="1392" alt="Screenshot 2024-07-24 at 12 46 23" src="https://github.com/user-attachments/assets/65544645-2ddd-4a01-8681-0a530cfa11f1">

**Comment by Grounded0** [comment] 2024-07-24 09:54
I'll give the author few days to respond to this and we'll close this as https://github.com/dosbox-staging/dosbox-staging/issues?q=is%3Aissue+is%3Aclosed+label%3A%22not+a+bug%22.

**Closed** 2024-07-25 22:45 UTC
Labels: not a bug, game compatibility, audio
