### ISSUE TITLE
Speed Limiting for Descent 1/2

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#1586] opened 2022-02-27 05:01 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

N/A

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

The first two Descent games definitely fall into that "speed sensitive" category where you can never find a consistent balance between good performance and proper game speed.

### Describe the solution you'd like

I recall a couple years back, the DOSBox SVN builds implemented a speed-limiting feature for DOS Quake, which eliminated the need to fiddle with cycles to get the game running at the correct speed. Would this be possible to do with Descent 1 and 2?

### Describe alternatives you've considered

Trying to find the ideal clock speed for framerate and proper game speed.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment] 2022-02-27 07:11
instead of a specific patch for "those games" exclusively
a focus on testing if a game is "running too fast" for all games.

but what is "too fast" if thats just how it behaved on a real dos pc with higher specs than the recommended?

**Comment by kcgen** [comment] 2022-02-27 08:56
@OpenRift412 , please record these games running too fast and attach for link to the videos. Also, please describe steps so others can reproduce this issue. Thanks.

**Comment by arrowgent** [comment] 2022-02-27 12:57
descent 1 confirmed has done this forever.  so its not very isolated to dosbox-staging or even dosbox
i can show this on my amd athlonxp 3200+ running dos

**the issue here is your ship bobs up and down rapidly and your weapons fire quickly**
long standing game engine issue

just tested dos32a anyways
`sb /r descentr.exe`
ran the game.  same thing.

`max 50%` or `50,000` or `100,000 cycles` have been suggested to be a compromise

https://user-images.githubusercontent.com/57545549/155883232-c2f78e17-49e5-4c48-b0a8-0ed3d87afecf.mp4

had to severely scale the video down to fit 10mb ...

**Comment by Kappa971** [comment] 2022-03-01 01:11
This issue in Alien Trilogy is more serious than in Descent. 
In Descent, limiting the cycles makes the game playable, but I remember Alien Trilogy which is a real disaster. You can limit the cycles, but the game will run too fast in some areas and too slow in others. I dropped out after the first level...

Exhumed uses the Build Engine, does it have speed problems? It's strange... Duke Nukem 3D, for example, has problems with flashing sprites if the CPU is too fast (setting the video memory to 8 mb greatly mitigates the issue), but has no speed problems. I remember instead that Exhumed is inexplicably very heavy compared to other Build Engine games like Duke Nukem 3D, Shadow Warrior or Blood (despite only supporting 640x480 as the maximum resolution).

I didn't notice any speed issues in Quake either, do you use a NASA PC? :)

**Comment by AaronBPaden** [comment] 2022-03-02 17:42
I wish dosbox allowed you to input cycles directly as mhz to make reasoning about cycle count easier.

Anyway, even 50k is more than Descent needs at the default resolution I think. Try 40k. For 640x480, real hardware from the late 90s has trouble running it, from recordings that I've seen on LGR. The sluggishness is noticeable. I'd say about 85-90k is about what I would expect.

In cases like that, where the game was just very demanding for the time, there may not be a "perfect" setting that doesn't have slowdown and doesn't run too fast, even if dosbox were cycle accurate, which it ain't.

**Comment by arrowgent** [comment] 2022-03-03 21:11
> I wish dosbox allowed you to input cycles directly as mhz to make reasoning about cycle count easier.

machine=svga_s3
cpu cycles=9650
cputype=auto

comparison of 9650 cycles to 100 mhz on two wildly different systems
![100mhz](https://user-images.githubusercontent.com/57545549/156651621-e9317ff7-759e-4f5b-88da-d639530efcb8.png)
![rpi100](https://user-images.githubusercontent.com/57545549/156651625-a4989b79-8d8c-4913-994e-bda212017813.png)

if your system = 100mhz at 9650 cycles, it would be safe to assume all systems would report identically.

not a comparison, the values are actually skewed when cycles=max 100%
![max](https://user-images.githubusercontent.com/57545549/156651623-6653b440-eb94-4c43-8aeb-f61939bed59e.png)
not a comparison because the raspberry pi reports Twice as fast FPU & MHZ but HALF the cpu clock speed


how any of this matters is difficult to compare
do you want the CPU Clock to report 100mhz or do you want the "performs like" to report 100mhz
and does it translate to actual usage inside dosbox when playing a specific game?

for comparison, for this benchmark to recognize "cpu clock = 100.77x mhz"
one system is set to cycles=7350
![dbclk100](https://user-images.githubusercontent.com/57545549/156653258-d8e74c6c-6b11-495c-9381-105eddae9401.png)

the other system cycles=14650
![dbrpiclk100](https://user-images.githubusercontent.com/57545549/156653275-1ae3063e-cfeb-42a6-b29d-18515b36513c.png)



anyone have a more accurate CPU benchmark or calculation?

even the (dosbench suite) TOPBENCH reports incorrectly
a 3.6ghz intel i7 quadcore reports:
16-bit real-mode x86 benchmark iterations score: 190
a 1.9ghz raspberry pi 4 reports:
16-bit real-mode x86 benchmark iterations score: 259
both are locked to cpucyles = 9650 with nearly identical settings otherwise

which one do you believe is correct?
what comparisons can be made between two wildly different computers running dosbox and in which games would "automatic" cycles actually work or fix the issue?

most of the time i run games at cycles=max 95% unless its really old then something less like 1990 cycles or less than 3000 cycles.
currently as many will recognize the "fix" is complicated
ive seen many times where people are confused by this "tinkering" and dont understand cycles, auto, max, dosbox.conf etc.
they then go on to say "dosbox isnt good" or whatever, because they really dont understand dosbox, dos, or things of its nature
they want their games to run "flawlessly" out of the box with no adjustments or configuration
i dont know what to tell them or say.  this is how it is currently

**Comment by AaronBPaden** [comment] 2022-03-03 23:51
> which one do you believe is correct?

Just an idle comment. I don't think it's relevant to this bug report to go off in that direction. But ideally a mhz setting would result in a relatively close approximation of real-world performance, with timings that are consistent across devices (and if the device can't keep up it would just not run at full speed). I suspect this may not actually be feasible.

WRT a heuristic for automatic, the current heuristic is limited sure, but fine for many games. I think manual intervention is always going to be inevitable for some games. I just ran into a case where the final boss of System Shock was bugged until I dropped the cycles from the default max to 40k, for example.

The modern solution would be a build-in gamesdb that set the correct cycle-count automatically on a per-game basis. But the nature of dos games, with its many revisions, mods and no standard distribution format makes that impractical. It would also be error prone. Like System Shock, you might not run into any issues with a setting until many hours into a game for example.

So I guess my opinion is this is a bug with no clear solution outside of completely changing the design of dosbox to be more accurate, which would no doubt come at a performance cost and would not be popular with people trying to run Quake in software mode at high resolutions, for example.

**Comment by arrowgent** [comment] 2022-03-04 06:20
> per game basis

this would introduce a .txt file with md5 hash of each .exe of the game/software

that .txt file could literally be 10x larger than dosbox itself

and if i hex edit a .exe game binary to "fix" a bug, then the automation of speed selection would be irrelevant

compare this to sdl [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB)
its 1595 lines long and is 416696 bytes

lets compare this to a fair approximation by mobygames listing
7901 games in the dos category

what about win3.1 games? approximately 1028 games in this category
you cant just detect speed of a game running in win3.1 and i can think of three experiences where even 10,000 cpu is too fast running in win3.1


and i mean how much more info can you put in the user's face to explain this?
![db_speed1](https://user-images.githubusercontent.com/57545549/156709618-490907fc-3ef7-4add-a902-61cf26c4ddcf.png)

Dosbox: 
Initial release - January 31, 2002; 20 years ago

**Comment by finalpatch** [comment] 2023-02-10 11:50
The fast emulation speed made Descent unplayable, due to its game logic is programed to be dependent on CPU speed. But the problem of emulation speed is not unique to Descent.  Many other games, for example, Duke Nukem 3D,  will happily render 200 frames despite the player's monitor can only display 60 frames a second, waste energy and generate heat. 

What we want, is a way to limit the number of frames rendered by the game up to the refresh rate of the player's screen.  We want the frames to be rendered quickly, so that we don't see half drawn frames, and we never skip a frame.  But at the same time, we don't draw more frames than the player can actually see.

On modern systems, this can be achieved by enabling vertical sync in the display driver.  Because all games have to access the graphics hardware through a handful of graphics APIs (DirectX, OpenGL, Vulkan, Metal).  And these APIs all have one function call that presents the current frame to screen. This provides a perfect choke point to limit the game's speed.  The game can either voluntarily wait for vsync, or we can force it in the display driver control panel.

In DOSBOX,  there is no established graphics APIs that all games use. However, I suspect we can still find such a chock point, after spent some time reading Descent's source code https://github.com/videogamepreservation/descent 

The main game loop uses the technique called "Page flipping" to achieve tear free screen update, which is conceptually the same thing as the "present" call in modern graphics APIs.  This is done by the 2 assembly routines "gr_modex_setstart" and "gr_vesa_setstart", for VGA and SVGA respectively.  Since we emulate the video adapter in DOSBOX, I believe it is possible to detect the point page flipping games swapping their back buffer to the front, and block the game's execution until the next vertical retrace,  equivalent to forced vsync.

This, of course, potentially increases the latency by up to 1 frame's time.  Another idea is that when we reduce the game's cycles, we don't reduce it evenly (or randomly).  Instead,  for example if the cycles are set to 50%, then we block out the first half of a frame's time, and allow the game to run for the second half of a frame before the vsync point.  This will still allow the game to have plenty of time to complete the rendering of a frame, but the presenting point will be half a frame closer to the vsync point.

One more consideration is that the VGA/VESA set_start function is not only used for page flipping, but sometimes also used for smooth scrolling.  This will require some heuristic, for example, if the new frame buffer has any overlapping with the old one, then it's likely being used for scrolling, if they don't overlap, then it's probably page flipping.

This is just my 2 cents.  My hope is we can make DOSBOX a lot more energy efficient as well as helping games like Descent run correctly.

**Comment by kcgen** [comment] 2023-02-10 18:16
> detect the point page flipping games swapping their back buffer to the front, and block the game's execution until the next vertical retrace, equivalent to forced vsync.

This is a unique look at the problem, @finalpatch, and "opens the box" in that we would be scanning for specific game instruction sequences (`gr_*_setstart` instruction pattern) followed by changing some behavior in DOSBox (halting game-side instruction execution).

If done "in place" and "rote" style, we're talking adding loops and if/else blocks with Decent-specific logic right inside the emulatd CPU cores (which doesn't exist on hardware).

That said, it would be cool to have it: we could make Descent play perfectly - even better than real hardware.

When these very specific game hack have come up before, the devs have always opted to spin of one-off builds, just for the give game. Here are some:

https://github.com/dosbox-staging/dosbox-staging/issues/1671

Imagine adding CPU-scanning hacks for 10 more games. Now 1000 games. The CPU code would be riddled with game-specific hacks. 

So I think the right way to do would be with a modular "function" plugin approach, combined with a With a default-off conf setting, so the CPU scan & result would no-ops.

**Comment by OpenRift412** [comment] 2023-02-10 19:45
> 
> So I think the right way to do it (without contaminating the cores or other areas with embedded game-specific logic) would be to make this modular with a handful of checkpoints.
> 
> At each checkpoint, zero or more pluggable routines (function pointers or binds) could run and enact their change.
> 
> combine that with a default-off conf setting (or even a new conf section, like [plugins]`, so the user could turn on as many as they like.
> 
> The code for these could be neatly arranged in a plugins directory with game-specific filenames too.
> 
> The result would be minimal touches in the codebase, and something that could be disabled entirely and cleanly.

So you want to introduce CPU plugins for specific games? That actually sounds like a really cool idea if you decide to go forward with that. Though something to note, this sort of speed limiting already exists in DOSBox's SVN codebase for DOS Quake. That may be handled differently, though.

**Comment by kcgen** [comment] 2023-02-10 19:49
Yes, @OpenRift412 :+1: 

A plugin and checkpoint approach would avoid making big messes inside the codebase, and allow for one, 10, or 1000 hacks - all neatly arranged. 

> Though something to note, this sort of speed limiting already exists in DOSBox's SVN codebase for DOS Quake. That may be handled differently, though.

Can you point to the code? I haven't seen any Quake-specific hacks/handling in the code base myself - but I'm not too well versed in the `/src/cpu` areas. Thanks!

**Comment by finalpatch** [comment] 2023-02-10 20:05
We are already halting the game side CPU execution today,  it's called cycle limit.  There is an "auto" setting, but my personal experience is that so far we have been pretty bad at estimating the cycles the games the **require** to run well.  The default cycles for real mode game is 3000 and although it can run most real mode games, it often feels rather sluggish: the input latency feels high, and screen updating is visible.  For protected mode games, "auto" is equal to "max" and normally this is way too high, resulting in games spending most of these cycles either redrawing frames users can't see, or spinning waiting for vertical retrace.

What I'm suggesting is a new way to throttle the CPU cycles by observing the time point they perform page flipping. Of course not all games do page flipping, but many do.  So this is not a Descent specific hack,  it will work for an entire category of games. For example, we can have a new throttling strategy called "smart":  if the game does page flipping then we increase cycles until we detect at least one page flip per VGA retrace cycle.

**Comment by finalpatch** [comment] 2023-02-10 20:07
And "detecting page flipping" does not mean we detect certain instruction sequences in Descent or specific games.  Instead, we detect this in the VGA/VESA emulation, when we see a request to set the frame buffer start pointer.

**Comment by OpenRift412** [comment] 2023-02-10 20:08
> 
> Can you point to the code? I haven't seen any Quake-specific hacks/handling in the code base myself - but I'm not too well versed in the `/src/cpu` areas. Thanks!

I don't know exactly, but the change was made in [SVN build r4215 on April 20th 2019](http://[source.dosbox.com/dosboxsvn.txt](http://source.dosbox.com/dosboxsvn.txt)).

**Comment by finalpatch** [comment] 2023-02-10 20:24
I think we can start by adding the ability to detect frame rate, and optionally display this either in the corner of the game window or in the console. Many modern games have builtin frame rate display. Steam can show fps, Retroarch can show fps.  This will give us valuable insight on how games are actually running.

**Comment by finalpatch** [comment] 2023-02-10 20:54
> And "detecting page flipping" does not mean we detect certain instruction sequences in Descent or specific games. Instead, we detect this in the VGA/VESA emulation, when we see a request to set the frame buffer start pointer.

In DOSBOX, this is a write to `vga.config.display_start`

**Comment by kcgen** [comment] 2023-02-10 21:19
Sounds perfect, @finalpatch :+1: - and agree with all your points.

The auto-cycle determination worked very well when host CPUs were still the bottleneck, and typically held-back games from spooling up to their full frame rates.

But these days, absent careful code on the game side (like monitoring BIOS ticks times or their own vsync back-off), `max` can let games generate far more frames than their developers expected. 

Funny story: coincidentally today, a user on eXo's Discord running MechWarrior 2 mentioned *"My mech is blowing up as soon as I enter the training mission"*! :grin: 

eXo recommended he switch to 130k cycles (down from `max`), and that did it.

**Comment by kcgen** [comment] 2023-02-10 21:24
> I don't know exactly, but the change was made in [SVN build r4215 on April 20th 2019](http://%5Bsource.dosbox.com/dosboxsvn.txt%5D(http://source.dosbox.com/dosboxsvn.txt)).

Found that commit in the repo (all of SVN's commits going back the very first one are maintained in the repo with original authorship) Staging itself just picks up as "follow on" commits, as a an internal soft-fork on top of the SVN commits. You can see r4215 here: **`git show 139456b2d0375962219f7f0d3447208fd65f39b1`**

```
commit 139456b2d0375962219f7f0d3447208fd65f39b1
Author: ripsaw8080 <ripsaw8080@users.sourceforge.net>
Date:   Sat Apr 20 22:59:42 2019 +0000

Make effect of I/O delay more consistent as cycles run out.
Prevents flickering in NBA Jam Tournament Edition at higher
cycles, and also improves automatic speed limiting in Quake.
    
Imported-from: https://svn.code.sf.net/p/dosbox/code-0/dosbox/trunk@4215
```

```diff
diff --git a/src/hardware/iohandler.cpp b/src/hardware/iohandler.cpp
index 4954ae984..af1d01099 100644
--- a/src/hardware/iohandler.cpp
+++ b/src/hardware/iohandler.cpp
@@ -208,14 +208,14 @@ inline void IO_USEC_write_delay_old() {
 
 inline void IO_USEC_read_delay() {
        Bits delaycyc = CPU_CycleMax/IODELAY_READ_MICROSk;
-       if(GCC_UNLIKELY(CPU_Cycles < 3*delaycyc)) delaycyc = 0; //Else port acces will set cycles to 0. which might trigger problem with games which read 16 bit values
+       if(GCC_UNLIKELY(delaycyc > CPU_Cycles)) delaycyc = CPU_Cycles;
        CPU_Cycles -= delaycyc;
        CPU_IODelayRemoved += delaycyc;
 }
 
 inline void IO_USEC_write_delay() {
        Bits delaycyc = CPU_CycleMax/IODELAY_WRITE_MICROSk;
-       if(GCC_UNLIKELY(CPU_Cycles < 3*delaycyc)) delaycyc=0;
+       if(GCC_UNLIKELY(delaycyc > CPU_Cycles)) delaycyc = CPU_Cycles;
        CPU_Cycles -= delaycyc;
        CPU_IODelayRemoved += delaycyc;
 }
```

A good general fix by @ripsaw8080 :+1:

**Comment by johnnovak** [comment] 2023-08-10 22:23
Um, just use fixed cycles values and job done? I'm not a fan of the proposed hacks. For games where no single fixed cycles value can be found, more accurate CPU emulation might be the answer that approximates instruction latencies to some degree vs our current simple 1 instruction = 1 cycle model.

Then, I wouldn't be surprised in many of these games misbehave similarly on much faster CPUs on real hardware. Those SVGA modes were tested at 5-10 FPS rates or something by the dev team as there weren't faster machines available, so what happens at 50x the CPU power is basically untested behaviour I'm pretty sure...

Tomb Raider, System Shock and Screamer play as 5 FPS slideshows in 640x480 on my Pentium MMX 200 box which is a typical high-end late DOS era machine.

**Comment by johnnovak** [comment] 2023-12-15 21:44
Closing, we don't want to support game specific hacks on the emulation side.

**Closed by johnnovak** 2023-12-15 21:44 UTC
Labels: won't do
