### ISSUE TITLE
Support cross-compilation for Windows using Linux 

### ISSUE THREAD

**Issue by Matthaiks** [dosbox-staging/dosbox-staging#39] opened 2019-11-10 20:17 UTC
A script that builds DOSBox for Windows under Linux would be great. MSYS2 is rather slow.

**Comment by krcroft** [comment] 2019-11-12 02:42
Should be very do-able @Matthaiks, thanks for the suggestion. This will tie in with adding more general cross-compiling to the build script (such as ARM/Linux, Aarch64/Linux, PowerPC/Linux, and PowerPC/OSX). 

Regarding MSYS2 - I'm curious if the build script at least is working for you on a Windows host?  (I've only been able to test it under GitHub's CI VMs as I don't own a Windows machine at home, and haven't heard feedback from others yet.)

**Comment by krcroft** [comment] 2019-11-12 02:44
Adding this related cross-compiling tool: https://github.com/tpoechtrager/osxcross

**Comment by Matthaiks** [comment] 2019-11-12 06:57
> Regarding MSYS2 - I'm curious if the build script at least is working for you on a Windows host?

Yes. dosbox.exe needs 12 DLL files to work and it's being build without its icon and file properties, though.

**Comment by sfhacker** [comment] 2020-01-22 09:43
Ciao.
Is there any Windows binary we could download?

Thanks in advance.

**Comment by dreamer** [comment] 2020-01-22 09:56
@sfhacker Yes: https://github.com/dreamer/dosbox-staging#development-snapshot-builds

> Pre-release builds can be downloaded from CI build artifacts. Go to [Linux](https://github.com/dreamer/dosbox-staging/actions?query=workflow%3A%22Linux+builds%22+is%3Asuccess) or [Windows](https://github.com/dreamer/dosbox-staging/actions?query=workflow%3A%22Windows+builds%22+is%3Asuccess), select a build you are interested in, click "Artifacts" button (in the top right), and download the package.

Occasionally, I am also uploading some specific snapshot builds to [v0.75.0-pre pre-release page](https://github.com/dreamer/dosbox-staging/releases/tag/v0.75.0-pre).

**Comment by sfhacker** [comment] 2020-01-22 18:33
@dreamer Thanks for your prompt response. Are there Windows binaries 32-bit or 64-bit?
Any dependencies?

Thanks again.

**Comment by dreamer** [comment] 2020-01-23 05:19
32-bit; all dlls are included with the precompiled snapshot package; read more at https://github.com/dreamer/dosbox-staging#windows

The 64-bit code is feature-full at this point, so it's only a matter of someone adding 64-bit profiles to the Visual Studio project, doing few small tweaks, testing, and updating release jobs in CI.

**Comment by krcroft** [comment] 2020-01-27 04:39
@Matthaiks , regarding performance, the msys2 builds take two minutes and Linux one minute; so although that's a 50% time savings, the absolute amount is still small in human terms.  Plus, in terms or workflow duration, the build times are dwarfed by other activities like code analysis that takes > 10 minutes. 

Do we really intend to build windows binaries on Linux? Although we might be forced to cross-compile for ARM (because GitHub doesn't have native VMs), I don't think we have that need for Windows. 

Suggest we close this unless we can think of other good reasons for it.

**Comment by sfhacker** [comment] 2020-01-27 08:08
We don’t use MSYS2 but MSYS1 and it is super fast. Who wants to produce Windows binaries on a Linux box?

**Comment by dreamer** [comment] 2020-01-27 09:30
We have recurring problems with MinGW/GCC builds (no matter if MSYS1 or MSYS2), to the point that it's the most obnoxious build environment we support. Every single build environment using MinGW+GCC resulted in slightly different issues, and we can't even reproduce them reliably between different machines.

We still can't use some C99 features (%zu format specifier) strictly because they don't work correctly in GCC on MinGW, some users have problems with using some non-ANSI POSIX functions (MinGW + MSYS1 + GCC + C++11 is the only environment that's making fuss about it) while other ones work fine (even though they should cause problems everywhere if MinGW maintainers were consistent).

Thanks to @krcroft efforts, dosbox-staging is buildable on Windows in MSYS2 with little effort (honestly, without `build.sh` script I couldn't be bothered to even try compiling it), so we're going to keep using it in CI going forward. There are signs of MSYS2 being bundled with Windows images and vcpkg landing support for msys-based triplets, so we might adjust once those will be finished and available.

Anyway; using Linux to cross-compile for Windows is a desirable feature; e.g. on Fedora, all the mandatory dependencies for mingw-based builds are already provided in the repositories, so adjusting `build.sh` to support it should be rather easy.

Unfortunately, Ubuntu does not provide mingw dependencies in an official repos (maybe they are in some PPAs somewhere - I haven't looked), but IF we managed to have working Ubuntu-based Linux cross-compile for Windows setup, then we could potentially drop dependence on MSYS2 and advise users to switch to WSL-based builds (honestly, installing Ubuntu in WSL on Windows 10 is easier and more stable than dealing with MSYS* BS).

Therefore, I prefer to keep this issue open; very likely I'll work on Fedora-based cross-compilation script (at some point); hopefully, Ubuntu script should be possible as well.

As for new developers coming in: just use Linux and rely on CI to build for Windows; it is so much easier in every aspect I could think of :).

**Comment by krcroft** [comment] 2020-01-27 10:06
Interesting and all valid points; I hadn't thought of ditching msys all-together, but deprecating it does make sense given how their author(s) appear to be running language-lawyering fiefdoms at the expense of their users. (Maybe msys + clang, or msys + gcc++17 will bring consistently?)

Cross-compiling for Windows will give us more analyzed code-coverage, being able to expose all those `#ifdef WIN32` branches to our analyzers.

**Comment by sfhacker** [comment] 2020-01-27 23:02
Windows 10 x64  //  MSYS 1  // c++11

    1.- Download master branch
    2.- autoconf -fiv
    3.- ../configure --prefix=/mingw
    4.- make all
    5.- That's all folks!
	
	
![image](https://user-images.githubusercontent.com/25817529/73221019-f4c93580-41b3-11ea-8483-4eb67f0f99dd.png)

![image](https://user-images.githubusercontent.com/25817529/73221204-673a1580-41b4-11ea-99f5-c494c346ca6b.png)
                                                                   **dosbox.exe (x64, has no dependencies at all)**
	
We have been using MinGW/MSYS environment for ages. We build large projects (e.g. Heimdal Kerberos, FreeRADIUS, and so on) without any issue on a regular basis.
	
	There is no need to use MSYS2.
	We have no idea what build.sh file is.
	We didn't have to install any dependencies at all.
	We don't use Linux nor MSVC.
	
	Some points to consider:
	
	    - Some users mix/confuse pears and oranges (i.e. MSYS & MinGW)
	    - Some users have polluted their build environment(s).
	    - Some users, especially those coming from the Linux world, have no or little experience with MinGW.

We can make dosbox.exe (master branch, 64-bit) available and we are more than happy to provide assistance building dosbox from source on Windows.

Have fun.

**Comment by dreamer** [comment] 2020-01-27 23:23
That's really great, but few questions:

1) How did you provide SDL2, SDL2_net, opusfile, libpng, other dependencies?
2) Can you reproduce your environment on GitHub CI? How long does a clean build take?
3) Does your environment provide Clang compiler alongside GCC? What versions?
4) Does your environment provide 32-bit builds alongside 64-bit?
5) Please add a `printf("%zu", sizeof(int));` somewhere in dosbox-staging code and tell us if GCC generated additional warnings in this line when compiling with `-Wall`.
6) Which project exactly do you represent?
7) We will be very happy to accept assistance with making MSYS* based builds more reliable in general. We'll keep using MSVC for our release builds, but we care about supporting compilation in diverse development environments, supporting multiple OSes, compilers, etc :)

**Comment by sfhacker** [comment] 2020-01-28 10:31
a) How did you provide SDL2, SDL2_net, opusfile, libpng, other dependencies?
Those dependencies were already available in my build environment. I didn't have to install them.
I guess if your environment didn't have them, you could download the binaries from official repositories.

b) Can you reproduce your environment on GitHub CI? How long does a clean build take?
What does GitHub CI have to do with this? We are mere users here. So far, there was/is no need to add this project to any CI. If you need some statistics, I can arrange that for you.

c) Does your environment provide Clang compiler alongside GCC? What versions?
What does Clang have to do with this? We are simple users here. However, we use cmake, ninja and another one I don't remember right now.

d) Does your environment provide 32-bit builds alongside 64-bit?
It is multi-arch.

e) Please add a printf("%zu", sizeof(int)); somewhere in dosbox-staging code and tell us if GCC generated additional warnings in this line when compiling with -Wall.
Provide some code snippet along with compiler switches.

f) Which project exactly do you represent?
We are mere users and represent no project.

> We'll keep using MSVC for our release builds, ....

We should not force people to buy, download and install Visual Studio. There is no need for that.
Of course you can use it, but should not be an imposition.

As we said, we build large projects using MSYS/MinGW on a regular basis and our build system is very reliable.

Regards.

**Comment by dreamer** [comment] 2020-01-28 10:55
You are missing the point. I don't care about build environment of any particular person - if it works for you, then great. My MSYS2-based env works great for me - I use it only as last resort, as I am Linux developer first and foremost and my Fedora works even better.

The point is: we need to provide easy to follow and automatically-reproducible way of building dosbox-staging. If I can't reproduce your setup on CI, then it's worthless to me. And handwaving "just install dependencies from somewhere" does not cut it.

> We should not force people to buy, download and install Visual Studio. There is no need for that.
Of course you can use it, but should not be an imposition.

Visual Studio (Community edition) is free-to-use; I am not forcing anyone to use it, but if someone decides to use non-free OS, then using non-free compiler provided by the OS vendor is not a stretch. Using free-to-use MSVC compiler with free (completely free) vcpkg is the easiest way to build dosbox-staging on Windows right now, MinGW-based environments are not even close.

If you are here to help, then great - I'm waiting for results of `printf` test - adding a single line literally anywhere in the code is not such a big task.

**Comment by krcroft** [comment] 2020-01-28 11:00
**zutest.cpp**
``` c++
#include <stdio.h>
int main()
{
    printf("%zu\n", sizeof(int));
    return 0;
}
```

`g++ -m32 -std=c++11 -Wall zutest.cpp -o zutest`

`g++ -m64 -std=c++11 -Wall zutest.cpp -o zutest`

We've hit issues on MSYS2 with `%zu` being unavailable.  Also try adding `-static-libgcc -static-libstdc++` (just to see if that changes anything).

**Comment by dreamer** [comment] 2020-01-28 11:58
Also, we don't hit it consistently - on my Windows 10 MSYS2 installation it seems to be working fine, but the exact same steps on GitHub CI (Windows Server 2019) generate warnings.

**Comment by sfhacker** [comment] 2020-01-28 12:44
> printf("%zu\n", sizeof(int));

I'm far from an expert but I was told it is good practice to use platform independent macros (e.g. PRIxxxx, etc) for format specifiers. These macros will work fine for both Linux and M$, whether 32-bit or 64-bit.
Thus, I took the liberty to improve the above source code line:

`printf("%" PRIu64 "\n", sizeof(int));`

Can you try this on your 'funny' build environment and let us know how it works?

**Comment by dreamer** [comment] 2020-01-28 12:56
Ehh… We know what PRI* macros are and when to use it (and we do use them in dosbox-staging). This is incorrect usage, as this particular macro is for formatting `uint64_t` values. Standard `%zu` is for formatting `size_t` values - and it works everywhere (even modern MSVC)… except MinGW, where it's randomly broken on *some* systems.

**Comment by krcroft** [comment] 2020-02-06 09:20
In related news; GitHub has now addressed this request - https://github.com/actions/virtual-environments/issues/104; so Windows and Ubuntu VMs come preinstalled with GCC and Clang. 

Will need to poke around on the Windows side and see if `pacman` is available for us to pull in our dependencies.

**Comment by Vaporeon** [comment] 2020-04-26 04:23
`%zu` can be used with mingw-w64 when using `__USE_MINGW_ANSI_STDIO`

Keep in mind mingw-w64 is a fork of MinGW. the original project deprecated `__USE_MINGW_ANSI_STDIO`, while mingw-w64 fully supports it. I don't think many use the original MinGW any more, it was forked for similar reasons as this project.

**Comment by dreamer** [comment] 2020-04-26 18:43
We do use MSYS2, which (AFAIK) uses mingw-w64 by default. It did not solve the problem. We tried using `__USE_MINGW_ANSI_STDIO` - last time I checked it worked on my development machine (Windows 10), but didn't work on Windows Server 2019 (our CI, where it really matters).

I hope we'll be able to replace windows-based MinGW* with builds inside WSL (which seems to work better).

**Comment by dreamer** [comment] 2020-09-04 10:02
Some new development: WSL is now available on GitHub CI: https://github.com/marketplace/actions/setup-wsl

Unfortunately, Fedora cannot be preinstalled in WSL via this action (yet? - we would prefer Fedora, because it packages our mingw dependencies already - Unlike Debian/Ubuntu, which package only the compiler).

However, there's also an option of running Alpine or OpenSUSE Leaf - perhaps those provide mingw dependencies we need.

**Comment by kcgen** [comment] 2021-09-20 02:26
Meson likely makes this even more doable than with autotools.   

Closing this because it's not an active or pending concern of the project, nor are any maintainers willing to pour effort into this (we're already trying to keep up with supporting three OS'es and multiple versions of GCC, Clang, and VS2019.

If someone feels this is unacceptable, then please come forward and offer your help. Thank you.

**Closed by kcgen** 2021-09-20 02:26 UTC
Labels: enhancement, Windows, Linux
