### ISSUE TITLE
Investigate playability issues with Spong (1993)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2938] opened 2023-09-16 00:43 UTC
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `Spong93/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Burrito78** [comment] 2023-09-25 12:42
Increase cycles to more than 30000 and up to eliminate flicker.

I think we can close this.

**Comment by Python-Exoproject** [comment] 2024-04-27 16:32
Something has changed in 81.1 that has broken this game @johnnovak, maybe a regression?

In 81.1:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/a4813b63-c021-4756-a6d9-2086907730a0)

In 80.1:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/bc2fe833-e9bf-4411-b648-6dfcbd7209f5)

**Comment by johnnovak** [comment] 2024-04-27 20:25
Huh, that's a weird one @Python-Exoproject. Yeah looks like a regression, having a look.

**Comment by johnnovak** [comment] 2024-04-27 23:38
By the way, why this bottom of the barrel shareware (?) game with rudimentary graphics needs any "custom modes" is anyone's guess...

Half of the time it's the shareware games with an user base of ten people doing all this freaky shit 😐 

<img width="987" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/bdcdac77-2872-4966-8beb-9e460e7b4c16">

**Comment by johnnovak** [comment] 2024-04-28 00:45
It was me again. Well, it shouldn't be surprising... the old saying is true: only those who actually do some work make mistakes 😏  (no has been touching the VGA code much except for me, at least not extensively)

```
1fdb907aff43424c024de41a50cc5f08a5ac154c is the first bad commit
commit 1fdb907aff43424c024de41a50cc5f08a5ac154c
Author: John Novak <john@johnnovak.net>
Date:   Sat Jan 27 11:43:06 2024 +1000

    Swap the Color & Palette Registers setup order on mode switches
```

**Closed** 2024-05-04 01:26 UTC
Labels: game compatibility, regression, video, eXoDOS/Win3x
