### ISSUE TITLE
Quitting the emulator hangs the process when any LPT DAC device is in use

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#4061] opened 2024-11-17 00:48 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main

### What Operating System are you using?

macOS (Apple Silicon)

### Relevant hardware info

MacBook Pro (2021, M1 Pro)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When any LPT DAC device is in use in the `main` build, quitting the emulator hangs the process. This is a regression from 0.82.0

### Steps to reproduce the behaviour.

1. Get the audio device test pack from our [audio tests wiki page](https://github.com/dosbox-staging/dosbox-staging/wiki/Audio-emulation-tests#audio-device-tests).
2. Run [Takeover by Epical](https://github.com/dosbox-staging/dosbox-staging/wiki/Audio-emulation-tests#takeover-by-epical-covox) using the Covox LPT DAC device as instructed.
3. Quit the emulator after the demo has started up.
4. Note `SDL: Exit requested` gets logged twice but the process hangs.

### Download URL of affected game or software

https://github.com/dosbox-staging/dosbox-staging/wiki/Audio-emulation-tests#takeover-by-epical-covox

### Your configuration

```ini
Included in the test pack.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment] 2024-11-17 06:12
Can't reproduce this on Linux.  I do see the double `SDL: Exit requested` but I'm also seeing that without starting the demo and it exits cleanly anyway.

**Comment by weirddan455** [comment] 2024-11-17 09:06
Scratch that, I can reproduce it now that #3875 got merged.  I was testing against `main` before so the regression is probably in that PR.  I'm guessing you ran into this bug while you were testing it.

**Comment by johnnovak** [comment] 2024-11-17 09:13
> I'm guessing you ran into this bug while you were testing it.

Ah yeah, that is what must have happened. I just thought it was main...

**Comment by weirddan455** [comment] 2024-11-17 10:06
PR in with the fix.  I knew right where to look due to running into these deadlocks myself.  A check to stop the LPT DAC queue got accidentally removed during a refactor.

**Closed** 2024-11-17 23:13 UTC
Labels: regression, audio
