### ISSUE TITLE
[BUG] uncorrect pixel-perfect aspect ratio with vgaonly setting in 0.78

### ISSUE THREAD

**Issue by Diduz** [dosbox-staging/dosbox-staging#1485] opened 2021-12-31 14:48 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

GeForce 2070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using the "machine = vgaonly" setting in v.0.78, the "openglpp" and "texturepp" output  produce a wrong 1.00 aspect ratio. Worked fine in 0.77.1. I attach two screens from Alien Carnage (one of the games that require vgaonly), so you can see the difference. ;-)

![078_vgaonly_aspect_ratio](https://user-images.githubusercontent.com/39902698/147828995-d54da0da-fbdf-4f49-8813-c6057559f4e2.jpg)
![077_1_vgaonly_aspect_ratio](https://user-images.githubusercontent.com/39902698/147828998-6ba455e3-f910-46ee-9131-2116f8baecff.jpg)
.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment] 2021-12-31 14:53
Is the aspect ratio correct with machine = svga_s3?

**Comment by Diduz** [comment] 2021-12-31 15:02
> Is the aspect ratio correct with machine = svga_s3?

Yes it is. Sorry, I should've mentioned that.

**Comment by Grounded0** [comment] 2021-12-31 15:09
So the game runs with svga_s3?

**Comment by Grounded0** [comment] 2021-12-31 15:10
Me and krc spent a ton of time on getting these fine details right with the new svga_s3 code.

**Comment by Diduz** [comment] 2021-12-31 15:21
Yeah, the game runs with svga_s3, but fades in Alien Carange have always been broken if you don't set "machine=vgaonly". "svga_s3" works fine and its aspect ratio is perfectly fine if you run games that don't require that specific setting, but that strange fades behaviour in Alien Carnage is still there in v.0.78 if you don't set "machine=vgaonly".

**Comment by Grounded0** [comment] 2021-12-31 15:25
Thanks. That machine type then has to have its regression fixed.

**Comment by Diduz** [comment] 2021-12-31 15:27
Thanks to you for all the work you've been doing on Dosbox Staging, it's become my favorite Dosbox version in the last year or so!

**Comment by kcgen** [comment] 2022-01-02 17:24
Here are some older issues involving aspect correction problems with pixel-perfect + vgaonly:
 - https://github.com/dosbox-staging/dosbox-staging/issues/544
 - https://github.com/dosbox-staging/dosbox-staging/issues/808

**Comment by kcgen** [comment] 2022-01-04 17:28
It's all about priorities.

"Pixel perfect" places the individual pixel correctness as its utmost priority. 
This means that we never blend pixels with neighbouring content, which also mean we can only scale pixels by whole integer.  For example: an image that's 320-pixels wide can only ever be scaled in whole multiples:
 - x2-> 640
 - x3 -> 960, and so on.
 - We'll never scale at some fraction, like 1.5, or 2.5, or.. something else. 
 - Because at say, 2.5 scaling, the resulting scene would contain 20% of "incorrectness" to achieve the width. That incorrectness could be blending the pixel colors. Or it could step-wise transitions, or it could be making every 3rd pixel twice as wide, and so on.

So armed with that knowledge you can now see those perfect integers being used:

![2022-01-04_09-13](https://user-images.githubusercontent.com/1557255/148097360-737ea99c-b8e4-4563-b408-366399bc8498.png)

Ok wait: but why is the aspect ratio all screwed up?
![2022-01-04_09-14](https://user-images.githubusercontent.com/1557255/148097482-c39d0daf-9621-4695-b338-24ec714cec53.png)

Remember, the first priority are the pixels and scaling them fully - the aspect ratio is compromised in this case. 
Because the user's screen (or their `windowresolution` setting) doesn't give us enough total canvas to work with, we try to land as close to the correct aspect ratio as possible.

Ok: I want both cakes and get pixel perfect *and* perfect aspect ratios.  For this, you need a very big display.

Even at 4k, it's not enough to hit the desired ratios:

![2022-01-04_09-24](https://user-images.githubusercontent.com/1557255/148099364-dd3a4952-159e-41dd-9c97-b6a06de5fafe.png)

**Comment by kcgen** [comment] 2022-01-04 17:35
Ok: I want both cakes - what would it take to get pixel perfect *and* perfect aspect ratios?

Staging supports it - but for this, you need a very big display that supports 4800x3600:

![ac_4800x3600](https://user-images.githubusercontent.com/1557255/148100174-da9aab2b-ec5b-4a14-be35-caa28b211d38.png)

**Comment by kcgen** [comment] 2022-01-04 17:41
The non-PP modes allow pixels to be blended, and therefore we can hit the desired aspect-ratios.

**Comment by kcgen** [comment] 2022-01-04 17:42
@arrowgent  <- you now have a reason to upgrade to 8k :+1:

**Comment by kcgen** [comment] 2022-01-04 17:44
The latest `main` branch does a better job at using available screen space to achive PP scaling. So I will close this ticket for now. I will also be back porting it to 0.78.1 soon enough.  Thanks again for the report @Diduz and discussion @arrowgent.

**Comment by arrowgent** [comment] 2022-01-04 17:45
well yes i understand whole interger scaling issues


this also suggests
`machine = vgaonly`
is correct when used for its application
640x400 or 320x200 is the correct vga resolution reguardless of pixel perfect?
the game is reporting to the video output to set that resolution?

```
Text 720x400 (mode 3h)
DISPLAY: VGA 640x400 8-bit (mode 13h)
```
are both the correct resolution that VGA supports

https://en.wikipedia.org/wiki/Mode_13h

**Comment by kcgen** [comment] 2022-01-04 17:55
Yes, that's the source resolution (320x200), however when render on an analog CRT, the resulting scene as viewed by the user was stretched 20% vertically -> so that's where the 1.2 aspect comes into play, and why we multiply 320x200 -by- 5x6 to get 1600x1200. The result is what the artist and game developers intended.

**Comment by arrowgent** [comment] 2022-01-04 18:18
for the cake example

would *pp + vgaonly be the only way to force setting a 320x200 resolution?
this can be extremely useful for show examples and testing this resolution

if your intent is to change this to scale to 4:3 then how would someone enable the 320x200 resolution?
s3 seems to handle these options correctly and is the probally most used video mode when comparing games

anecdotally, many old CRT had knobs to stretch the VxH to adjust fit the screen
before it became integrated to an OSD to digitally adjust this
it used to bother me endlessly when i changed resolutions to 1280x1024 because it didnt fit the screen


lastly, is there a change in s3 or pp that needs to be checked in vgaonly? or is vgaonly correct as it is now?
https://dosbox-staging.github.io/v0-78-0/
`Merged S3 video patch by s3freak. This adds more video modes and supports up to 8 MiB of video memory, vmemsize = 8, when using machine = svga_s3`
`Removed VESA modes 320x200x15/16/24, which were added late in the 90s and were not properly supported by some games`

**Comment by arrowgent** [comment] 2022-01-04 18:26
also the OP
> Alien Carnage (one of the games that require vgaonly)
it works fine in `machine           = svga_s3` so im not sure where this idea comes from
im using the downloaded version 0.78.0 from releases, ie: no changes

**Comment by Diduz** [comment] 2022-01-04 20:57
> > fades in Alien Carnage have always been broken if you don't set "machine=vgaonly"
> 
> checked again, s3 fades work fine the same as vgaonly

I recheked: they don't. ;-)
With "svga_s3" fade-ins are screwed. First the graphic screen appears with a weird "curtain effect" (up-down), the screen goes black, then you get the fade-in. Fade-out works fine.
With "vgaonly" you get the right behaviour: black screen, fade in, title, fade out.
Check: https://www.vogons.org/viewtopic.php?t=30360 (_"BTW, the screen fades look nicer with machine=vgaonly due to support for video blanking"_).
Granted, the game still works with "svga_s3" (as I said), but fade-ins don't. I admit I went overboard about Alien Carnage "requiring vgaonly" :-D, but the problem IS there. You need "vgaonly" to obtain the intended behaviour of the game (and I remember that, because I played it back then on my original 386).

**Comment by kcgen** [comment] 2022-01-04 23:42
> would *pp + vgaonly be the only way to force setting a 320x200 resolution?

Set `[render] aspect = false`, and that will give you the game's original resolution without the CRT vertical stretch. Should work in all the machine times (CGA/EGA/.. ) for all non-high resolution modes. 

Keep in mind that in general, the modes >= 640x480 implied square pixels (and artists and developers expected that) - so for those resolutions, `aspect` no longer has an effect. But fortunately, this dillema was sorted out and you shouldn't see stretched shields and oval suns in high-res or win 3.1 games.

>  is there a change in s3 or pp that needs to be checked in vgaonly? or is vgaonly correct as it is now?

I think, with respect to pixel-perfect scaling, there shouldn't be any remaining issues lurking when using these mode.

**Comment by arrowgent** [comment] 2022-01-05 17:28
>First the graphic screen appears with a weird "curtain effect" (up-down), the screen goes black, then you get the fade-in. Fade-out works fine.

> With "vgaonly" you get the right behaviour: black screen, fade in, title, fade out.

youre right, i checked again vgaonly does this, s3 does not.
that behavior might be the expected result from the newer s3 "hardware" emulation
possibly s3 is not expected to do the fade ins although it should respect Mode-13h

> I think, with respect to pixel-perfect scaling, there shouldn't be any remaining issues lurking when using these mode.

dont mind me, i tend to ask a lot of hypothetical questions reguarding correct and expected features

> http://legacy.3drealms.com/news/2007/05/alien_carnage_freeware.html
> decided to download it myself

any case, this added to my 3dr freeware folder.  i forgot to download this one in my list ages ago
[thanks for all the fish](https://i.imgur.com/4Sq0TLm.png)

**Comment by kcgen** [comment] 2022-01-05 17:36
Very nice setup, @arrowgent . Is that a custom menu?  Also - I see the handy FPS and vsync overlay! (that you've thoroughly documented for everyone to try :+1: )

**Closed** 2022-01-07 04:16 UTC
Labels: bug
