### ISSUE TITLE
Dosbox-staging 0.81.1 ANSI sequence handling

### ISSUE THREAD

**Issue by kingjoma** [dosbox-staging/dosbox-staging#4003] opened 2024-10-23 17:53 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

SteamOS Linux

### Whats your question and how can we help?

Hi Team

Please can you confirm if version 0.81.1 handles ANSI sequencing the same as 0.80.1. 

Since updating to 0.81.1 the attached ANSI sequence in my script doesn’t seem to be displaying correctly. 

The ANSI sequence and both versions display is attached as 3 seperate images.  The 0.81.1 version is representing the vertical lines on the border as repeated “?” Etc. 

Your input would be most helpful. 

![IMG_3163](https://github.com/user-attachments/assets/eda50257-f6b4-4013-895d-a670b156f3ec)

![IMG_3161](https://github.com/user-attachments/assets/4479b47c-73e3-4db4-95ba-3b32983b0b0b)

![IMG_3164](https://github.com/user-attachments/assets/f8b2d35a-e440-4307-93cd-7116b10e3ea6)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment] 2024-10-23 18:12
This seems to be a duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/3027

**Comment by kingjoma** [comment] 2024-10-23 20:43
Hi All

I have read the other threads on this. I agree that if this is limited to minor aesthetic issues on legacy launch scripts and the "upgrade" to UTF-8 has more significant improvements then I can live with the new status quo. Happy if you close this thread. 
Thanks.

**Closed** 2024-10-23 22:21 UTC
Labels: question, not a bug
