### ISSUE TITLE
Occasional stutters when output is set to opengl

### ISSUE THREAD

**Issue by mckellenjaundice122** [dosbox-staging/dosbox-staging#2860] opened 2023-09-12 15:59 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-7200U @ 2.50 GHz, 8 GB Ram, Intel HD 630

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There seems to be a bug which i am unsure if it has either been fixed accidentally or intentionally sometime after the original person who first reported this issue who was using 0.75.1 [here](https://github.com/dosbox-staging/dosbox-staging/issues/655) For curiosity's sake, i decided to use 0.76.0 which i happened to have lying around my files to see if the same issue occurs, and to my surprise, it does not. Another things to note which i'm not sure are relevant but have to do with the performance. When set to anything else besides opengl, the performance takes about a 15% or so hit, most evidently in intensive games such as quake, where i go from 59 fps on average with timedemo demo1, to around 46 fps, all tests done at 640x480, so, although using texture does fix it, it comes it with own caveats, meaning the image becomes blurry and as far as i can tell, the scaler feature has been deprecated and now only works in opengl in form of shaders, meaning this seems the be the only way of getting rid of this bug without using an older version. Vsync does not seem to affect this, but i will list the common config settings i have used throughout me testing versions.

After more extensive testing, it seems to be as 0.76.0 is the last version where this issue does not happen, even weirdly, performance takes a huge drop, lagging hard enough to be more than stutters and full blown slowdowns, this happens in-between versions 0.77.0 - 0.78.1, 0.79.1 is when the game starts working fine again, albeit now with the new issue of the stutter as mentioned above.

Upon even more testing, i eventually came to the conclusion that it's also not dependent on resolution, Virtual pool has the same stutter on 320x240 just like it does in 640x480. As such, here's a short list of the games i have tested which result in these kind of stutters as described above.

Command and conquer red alert (C&C 1 is fine for some reason)
Carmageddon (both 640x480 and 320x240)
MDK
Virtual pool
Quake

core = dynamic
vsync = false
cycles = auto 20000 limit 80000
fullresolution  = desktop
windowresolution  = 1280x960
memsize = 32
blocksize  = 2048
prebuffer  = 80

Besides these settings, i have used the default values for everything else, i would also like to note this bug/issue doesn't seem to exist in other forks, namely dosbox ECE and dosbox-x, neither does it in dosbox 0.74-3. Another game i have gotten to get a consistent stutter for testing is virtual pool, which generally stutters around less than a minute into a new game, most noticably the midi music abruptly stutters for a fraction of a second while in quake it's seems to be more at random, and not really dependent on what's happening on screen, often times happening when i'm looking at a wall and nothing at all during big fights.

The stutters themselves at first i thought were audio only when i heard them in a couple other games, but they sometimes subtle enough to not be that big of a nuisance, but can ruin immersion for some people and in some more atmospheric games. They are short, usually less than a fraction of a second, and it applies to the entire game, video, sound, not just midi, but all of it, it almost behaves as if the emulation itself slows down, which i don't understand why as i think my CPU should be okay enough considering how this only seems to happen in staging.

### Steps to reproduce the behaviour.

Easiest way to reproduce
1. Install virtual pool (gives most consistent and visible stutters)
2. Run the game, video mode seems to be irrelevant
3. After starting a new game, stutters will start happening sometime a minute or so after playing, noticable in the midi sound hitching along with the video for a fraction of a second

### Your configuration

```ini
https://gist.github.com/mckellenjaundice122/bdbbe48ce2c94f972624218810971542
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-09-12 16:31
Please post your full console log output and a attach a zip of your Quake demo with your conf so we're comparing exact 1:1 apples to apples (just drag and drop your log.txt and quake-demo.zip directly in the edit box here).

**Comment by GranMinigun** [comment] 2023-09-12 16:32
The performance hit in OpenGL output is due to usage of Pixel Buffer Object extension. It's a known problem, and will be remedied in a future release.

As a former Windows 10 user, I have to warn that Intel's OpenGL driver there is absolutely terrible. Expect not only worse performance, but other issues as well, including broken presentation timing, broken extensions, graphical artefacts. That may or may not be the cause of stutters. For reference, I have i5-7400, same generation desktop model with the same GPU, maybe higher clocked, but that's irrelevant.

Have you tried the latest _development_ version of DOSBox Staging to confirm the issue is still present?

**Comment by kcgen** [comment] 2023-09-12 16:53
No worries!

First, be sure you're launching the executable from a CMD or powershell prompt. 

1. (in your Windows-based console) `cd to\your\game\directory`,
2. Then launch `c:\path\to\dosbox\dosbox.exe`
3. Confirm your game is launcheable
4. If so, now re-launch but redirect the output to a text file: `c:\path\to\dosbox\dosbox.exe > log.txt`
5. Alternatively, you can click and drag, then copy and paste the text out of your Windows-based console into the text box here.

**Comment by Grounded0** [comment] 2023-09-12 17:55
I got standardised benchmark package here with DOSBench. Makes a lot easier when everyone is running exactly the same unit tests:

https://anttipeltola.eu/misc/files/DOSBENCH.ZIP

**Comment by kcgen** [comment] 2023-09-12 21:43
> PC player benchmark SVGA (this one for some reason flickers really badly, and only when the dosbox window is focused, score is 101.5)

This particular benchmark flickers when it's drawing frames faster than the VESA rate (your score of ~100 fps / VESA 70 fps = ~42% faster than realtime).
 - so you're seeing part of the screen getting blanked but only partially before the new frame is written.
 - when there are lots of 3D objects, you might not notice any flickering because the frame rate briefly has fallen at or below VESA's 70 Hz rate

When you "unfocus" the benchmark, Window's itself doesn't schedule as many CPU cycles for it - so you're seeing `cycles = max` simply not running at fast.  If you let the entire PC player benchmark run unfocussed and you notice no ficker, then your score will be sub-70 fps.

Your scores are quite good, I would say.

**Comment by kcgen** [comment] 2023-09-12 21:43
@mckellenjaundice122 , can you do another benchmark run with the latest MSYS2 dev build, and also capture and post your log output?

**Comment by weirddan455** [comment] 2023-09-12 21:54
>  When you "unfocus" the benchmark, Window's itself doesn't schedule as many CPU cycles for it

Slightly off topic but do we do anything in our code to influence this?  I have noticed bad MIDI stuttering (plays garbage repeating sounds for multiple seconds) with FluidSynth in Duke 3D that happens sometimes when the window is unfocused and then goes back to normal when I focus the window.  I had thought about putting a bug report in but it's hard to reproduce.

This is happening in Linux for me.  I'm not sure if this is related to what OP is describing or if this is a separate issue.

**Comment by kcgen** [comment] 2023-09-12 22:07
> Slightly off topic but do we do anything in our code to influence this?

Yup, see "SetPriority" in sdlmain.cpp, but over a year ago we switched the `"priority"` defaults to `"auto auto"`, meaning that we don't make any OS-specific scheduling changes to the process. So basically  let the OS schedule as it sees fit.

That said: a lot of people might have very old conf files with the old values still in there, like "normal lower", in which case it will lower the PID priority when out of focus.

Try using `auto auto` and then launch with `gamemoderun /path/to/dosbox` (I think Arch has  gamemoderun). You should get pretty similar benchmarks speeds foreground or background.

**Comment by kcgen** [comment] 2023-09-12 22:17
If you hear errors in MT32 or FluidSynth (built-in), check the logs for warnings about their audio buffers running too low.

If you see the low buffer warnings, it means the MT32 or FluidSynth threads were too CPU-starved to keep up with realtime, and you'll hear a gap when the queue runs dry.

But if you don't see low buffer warnings despite hearing MIDI glitches (another with other audio drop outs): then the problem is the entire process is getting blocked, overloaded (auto-cyclers possibly over-estimating), or some other scheduling problem.  This can happen with lots of other CPU-intesively processes competing. 

DOSBox's "load profile" can be confusing to OS schedulers too - because it run N emulated cycles per millisecond of wall time, and if those N cycles only takes 1/10th of the millisecond, then we effectively sleep the remainder, and we appear to only need 10% of the CPU and not 100% (fair enough.. maybe we don't need to be burning the CPU at 4.5 Ghz or whatever).

So that's where gamemoderun (and other scheduling tweaks) can help.

**Comment by weirddan455** [comment] 2023-09-12 22:38
I just had the audio bug out on me again.  There were no errors in console and this time it continued playing just 2-3X slower so it sounded really bad.  Then it went right back to normal as soon as I focused the window.

I also had it take a long time to launch the game (taking 20-30 seconds instead of the normal 5 or so seconds) when I had Dosbox unfocused so I guess it's not just sound that's affected even though that's where it's the most obvious.

I added log statements and the `SetPriority` does nothing because it's set to auto.  And like I said before, it's hard to reproduce.  Only managed to get the audio bug/slowdown once out of the 5 or so times I tried just now.

Anyway, don't want to de-rail this thread too much if this is completely unrelated.  I'll put a ticket in if I can find a reliable repro case.

**Comment by johnnovak** [comment] 2023-09-12 23:05
> I just had the audio bug out on me again. There were no errors in console and this time it continued playing just 2-3X slower so it sounded really bad. Then it went right back to normal as soon as I focused the window.

Never ever had such an issue on macOS or Windows in the last 2 years. Not a single time. Audio is always perfectly playing in the background, zero glitches. Same with raw MIDI output. Maybe something specific to your Linux setup?

**Comment by kcgen** [comment] 2023-09-12 23:14
> Then it went right back to normal as soon as I focused the window.

If our `priority` is `auto auto`, that's the Linux process scheduler pulling the priority strings (or the window manager looking at foreground/background, and asking the scheduler to tweak the PID).

Staging will run straight away in the console's frame buffer, even with the window manager. 
 - boot straight to your console with `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash init 3"`, and launch with: `SDL_VIDEODRIVER=kmsdrm dosbox [args]`. Should be smooth sailing :-)

**Comment by weirddan455** [comment] 2023-09-12 23:32
>  Staging will run straight away in the console's frame buffer without X11 or Wayland.

Mind blown.  That actually launched Dosbox.  Of course, it didn't respond to my keyboard and I had to full reboot to get my system back but that's still cool.

**Comment by weirddan455** [comment] 2023-09-13 15:07
@kcgen I always boot my system into console and just type `startx` to launch X11 and KDE.  Less things that can go wrong if my Nvidia driver fails or something so I can at least always get to a console to fix it.

And yeah, the `/dev/input` permissions was my first thought as well.  Normally programs will get keyboard input from X11.  I also know for a fact my raw `/dev/input` keyboard device is not readable by my user.  I could probably add myself to the `input` group to fix it.

**Comment by kcgen** [comment] 2023-09-13 16:38
@mckellenjaundice122 : when you have a chance to revisit the suggestions in [this comment](https://github.com/dosbox-staging/dosbox-staging/issues/2860#issuecomment-1716495112) and the follow on comment, your results will help.

**Comment by kcgen** [comment] 2023-09-13 17:43
(no rush.. just wanted to avoid it scrolling off the queue)

**Comment by MasterO2** [comment] 2023-09-13 21:08
@mckellenjaundice122, regarding Virtual Pool and the 40,000 CPU Cycles, can you add an entry for that on https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues?  That would be immensely helpful for anyone else who wants to play that game in the future.

**Comment by kcgen** [comment] 2023-09-13 21:27
That's all great news, @mckellenjaundice122! 

DOSBox (all of them) can run things very nicely, however with only two  cores available, there's not much elbow room when other applications (like the bloated Electron-based Discord app) spikes its CPU usage across multiple threads for short blips of time. 

Your findings will surely help others.

Those suggested conf settings are meant to be deliberately low-overhead for your Intel iGPU, however you can now roll them back, one by one, and test the performance impact/benefit, and decide how you like.

For Quake, just for fun, you can achieve a very smooth "soap opera" effect by running `dos_rate = host` (assuming your PC runs at 60Hz) , `vsync = on`, plus using Quake's `vid_wait` settings (see `[autoexec]` commands below). 

Here's how it looks:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/849e858e-158f-4e0c-80be-0479a7d2b920

And my conf that I recorded it from:

```
[sdl]
presentation_mode = vfr
output = openglnb
windowresolution = 1280x960
fullscreen = false
vsync = true

[render]
glshader = none

[dosbox]
memsize = 48
startup_verbosity = quiet
dos_rate = host

[dos]
xms = false
ems = false
umb = false

[cpu]
core   = dynamic
cycles = max

[midi]
mididevice = none

[ipx]
ipx = false

[ethernet]
ne2000 = false

[joystick]
joysticktype = disabled

[autoexec]
@echo off
mount c .
quake.exe +vid_wait 1 +_vid_wait_override 1 -nocdaudio
```

For any other DOS games, I always recommend starting with default settings (none of those that I recommended above), and only adjust from there as needed.  Our wiki has some great tips on how to best manage your conf files.

**Comment by kcgen** [comment] 2023-09-13 21:54
> i feel like this whole thing wasn't entirely in vain either, seems like turning off mididevice and glshaders does have quite a bit of an impact on performance

Yes - they both do, and in slightly different ways:

 - the glshaders increase your iGPU's work by quite a bit (versus the simple `sharp` and `none` shaders). This will show up possibly as a bit more lantency for each frame which in turn means DOSBox has a bit less time to give Quake, leading to Quake itself running at a slightly lower frame rate.

 - Your 'u'-based CPU itself has strict power limits - so more iGPU strain means more wattage being allocated to it, and a bit less to the CPU side, so this can squeeze your peak `cycles = max` given over to the game.

 - Fullscreen vs. Window-mode (and window-size) will also have an effect. The less rendering area, the less work to do.

 - Of course.. power-hungry external AMD / NVidia / ARC-based GPUs won't break a sweat with these shaders, but Intel's iGPU is very weak.

 - For MIDI in your case, I would suggest trying the built-in FluidSynth plus a lean soundfont, like [Creative Labs 4MBGM](https://archive.org/download/500-soundfonts-full-gm-sets/500_Soundfonts_Full_GM_Sets.zip/4MBGMGSMT.sf2).

    ```ini
    [midi]
    mididevice = fluidsynth
    
    [fluidsynth]
    soundfont = path\to\your\4MBGMGSMT.sf2
    ```
    This will use your second core and should put no extra strain on your main DOSBox thread.

> oh, and setting the dos_rate to host makes quake flicker

Yes - this was just a test to keep the DOSBox Staging's presentation frame rate from going beyond your hosts's rate, just incase your host has some kind of vsync-enforcement/override. You can knock that out again.

**Comment by johnnovak** [comment] 2023-09-13 22:31
That's a bit of emulator user 101: when you seem to have performance problems with an emulator, quit all other programs and try again. We had reports in the past where the automatic desktop image switcher caused serious MIDI timing fluctuations whenever it changed the image in the backgroind every 20 seconds... And that was with sending MIDI to external hardware, so very undemanding CPU usage wise! Discord is a resource hungry monster, yes...

In general, treat DOSBox as any other performance intensive game or application. The surest way is to do a clean boot, then only start Staging, then see if the problem persists. Of course, various 3rd party software that auto-start on Windows start can also cause performance degradation (e.g. periodic antivirus checkers, backup software, disk cleaners, etc.) Those would affect other programs as well, but emulators are particularly sensitive to timing hiccups, and it's the sound that goes first.

**Comment by weirddan455** [comment] 2023-09-13 23:01
90s era game developers:  Brought real time 3D graphics to sub 100mhz 486 PCs dropping down to assembly language when needed to squeeze out every last bit of performance on limited hardware.

Modern web developers:  I'm trying to send text... over the internet... with like emojis and stuff.  How can I possibly do that without GBs of RAM and multiple CPU cores?

**Comment by johnnovak** [comment] 2023-09-14 00:21
> 90s era game developers: Brought real time 3D graphics to sub 100mhz 486 PCs dropping down to assembly language when needed to squeeze out every last bit of performance on limited hardware.
> 
> Modern web developers: I'm trying to send text... over the internet... with like emojis and stuff. How can I possibly do that without GBs of RAM and multiple CPU cores?

@kcgen sent this to me a while ago 😄 Cheers me up every single time, but it's a "lolsob" type of thing, yeah.

![games](https://github.com/dosbox-staging/dosbox-staging/assets/698770/7f794cb0-4b4b-4aea-8be5-2920fc137daf)

**Comment by kcgen** [comment] 2023-09-14 00:49
@GranMinigun had actually played that 96KB game (2004 .kkreiger):  https://m.youtube.com/watch?v=-oQ45rutu0g

Amazing stuff!

**Comment by weirddan455** [comment] 2023-11-05 15:13
The issue with stuttering when the window is unfocused (that I mentioned in a previous comment) has been resolved in #3085.  This ticket has gotten quite long and somewhat off topic (partially my fault).  @mckellenjaundice122 Is there a remaining issue here or was the problem just Discord hogging CPU cycles?

**Comment by mckellenjaundice122** [comment] 2023-11-09 16:52
> The issue with stuttering when the window is unfocused (that I mentioned in a previous comment) has been resolved in #3085. This ticket has gotten quite long and somewhat off topic (partially my fault). @mckellenjaundice122 Is there a remaining issue here or was the problem just Discord hogging CPU cycles?

I believe that was the only issue so far, it's just my weak laptop's cpu not really being able to handle dosbox staging too well if i have discord in the background open, the only odd thing though, is that it's not affected if i have it open in chrome instead, but it's a small tradeoff, other than that, i'd say staging feels less rigid performance wise than dosbox 0.74.3, where in mainline, i could do pretty much all of the above in the background and not have one stutter while staging feels more fragile in that sense, but as far as i understand it, it's because staging aims for higher accuracy, which is perfectly fine. I have tested a bunch more games since i started this issue and haven't come any glaring issue, so i've been pretty happy with switching to staging completely, just gotta keep those things in mind.

**Comment by MasterO2** [comment] 2023-11-09 16:56
> > The issue with stuttering when the window is unfocused (that I mentioned in a previous comment) has been resolved in #3085. This ticket has gotten quite long and somewhat off topic (partially my fault). @mckellenjaundice122 Is there a remaining issue here or was the problem just Discord hogging CPU cycles?
> 
> I believe that was the only issue so far, it's just my weak laptop's cpu not really being able to handle dosbox staging too well if i have discord in the background open, the only odd thing though, is that it's not affected if i have it open in chrome instead, but it's a small tradeoff, other than that, i'd say staging feels less rigid performance wise than dosbox 0.74.3, where in mainline, i could do pretty much all of the above in the background and not have one stutter while staging feels more fragile in that sense, but as far as i understand it, it's because staging aims for higher accuracy, which is perfectly fine. I have tested a bunch more games since i started this issue and haven't come any glaring issue, so i've been pretty happy with switching to staging completely, just gotta keep those things in mind.

Another setting you may want to review in your `dosbox-staging.conf` is:

https://github.com/dosbox-staging/dosbox-staging/wiki/Frequently-asked-questions#advanced-cpu-cycle-count-configuration

That will help reduce the percentage of CPU needed for protected mode games.

**Comment by mckellenjaundice122** [comment] 2023-11-09 17:01
> > > The issue with stuttering when the window is unfocused (that I mentioned in a previous comment) has been resolved in #3085. This ticket has gotten quite long and somewhat off topic (partially my fault). @mckellenjaundice122 Is there a remaining issue here or was the problem just Discord hogging CPU cycles?
> > 
> > 
> > I believe that was the only issue so far, it's just my weak laptop's cpu not really being able to handle dosbox staging too well if i have discord in the background open, the only odd thing though, is that it's not affected if i have it open in chrome instead, but it's a small tradeoff, other than that, i'd say staging feels less rigid performance wise than dosbox 0.74.3, where in mainline, i could do pretty much all of the above in the background and not have one stutter while staging feels more fragile in that sense, but as far as i understand it, it's because staging aims for higher accuracy, which is perfectly fine. I have tested a bunch more games since i started this issue and haven't come any glaring issue, so i've been pretty happy with switching to staging completely, just gotta keep those things in mind.
> 
> Another setting you may want to review in your `dosbox-staging.conf` is:
> 
> https://github.com/dosbox-staging/dosbox-staging/wiki/Frequently-asked-questions#advanced-cpu-cycle-count-configuration
> 
> That will help reduce the percentage of CPU needed for protected mode games.

I already have "auto 20000 limit 80000" on my default cfg for that reason, so that i have a balanced enough setup for the majority of games and then handle it via .bat files if a game is more picky, though one weird thing i have to mention, and i'm unsure if it's a bug or undocumented, but, if i were to set my cycles to just "auto" before running a game, but having had the previously mentioned in my default cfg, the game will still run as if it's only at 80000 cycles despite directly writing in "cycles auto" in the command line, i found that can be overwritten if i instead set "cycles max" the previously mentioned limit of 80k cycles is gone, so i'm unsure if that's how just "auto" is supposed to work if you previously limit it in the same session or not, it's a small issue, anyway.

**Comment by Grounded0** [comment] 2023-11-09 18:22
What shader do you use and what display resolution? We've recently improved performance by removing OpenGL PBO that will benefit Intel iGPUs the most by reducing GPU workload.

If you do the math then CPU + GPU shader adds more workload to poor 15 W TDP chip than DOSBox 0.74 without GPU shader. That means it will cut back on performance more often than without using a shader.

**Comment by Grounded0** [comment] 2023-11-09 18:35
I'll close this in couple of days since we've reduced GPU thermal dissipation with OpenGL PBO removal. That's the best we can do without buying new hardware to author of this ticket.

**Comment by johnnovak** [comment] 2023-11-09 21:34
Maybe we should add a "bottom of the barrel laptop cursed with an Intel iGPU" recommended base config to the Wiki one day 😄

**Comment by mckellenjaundice122** [comment] 2023-11-09 21:40
> What shader do you use and at what display resolution? We've recently improved performance in development builds by removing OpenGL PBO that will benefit Intel iGPUs the most by reducing GPU workload.
> 
> If you do the math then CPU + GPU shader adds more workload to poor 15 W TDP chip than DOSBox 0.74 without GPU shader. That means it will cut back on performance more often than without using a shader. When shopping for the next laptop go for at least 45 W TDP design preferably with discrete GPU or AMD APU design.
> 
> Intel iGPUs **_suck_** and should be **_banished from this earth._**

The gl shader is set to just default which i believe is sharp? without it, i get that blurry image i get on mainline dosbox without forcing the scaler to 3x, but it seems staging has gotten rid of the scaler feature and replaced it with shaders, which is a bummer for those with potato computers like mine, since i either have to deal with a blurry image, or have a sharper image and deal with a lower performance, i know this is probably out of scope seeing how many other things staging excels at especially accuracy wise (i got settlers 2 to install only using staging, mainline crashed during the install). The display resolution is just my desktop one when in full screen, 1920x1080, set using just the "desktop" parameter in the config, in windowed, mainly because some games are a bit hard on the eyes when set to fullscreen but that's a me problem i use 1280x960 because it scales nicely without messing the aspect ratio too much.



> Maybe we should add a "bottom of the barrel laptop cursed with an Intel iGPU" recommended base config to the Wiki one day 😄

You have my blessing to add the specs of my poor laptop to such a wiki if you ever want to make such a page. 😔

**Comment by johnnovak** [comment] 2023-11-09 21:48
Try `glshader = sharp` and see how that goes. The default option is CRT shaders which can be slow on potato computers 😄

**Comment by mckellenjaundice122** [comment] 2023-11-09 21:52
> Try `glshader = sharp` and see how that goes. The default option is CRT shaders which can be slow on potato computers 😄

I don't believe i ever have seen the crt shaders enabled on my copy of dosbox staging. Using just sharp, tells me that no such shader exists, telling me to use interpolation/sharp, which to me, looks exactly the same to what it's normally set to when just using "default", i'm not using the development versions, just the latest stable version, 0.80.1.

**Comment by Grounded0** [comment] 2023-11-09 21:55
He's using 0.80.1 so it's already `sharp`. He will get less TDPmax crap out by continuing to use `sharp` and getting GPU workload significantly reduced by OpenGL PBO removal in future 0.81 or by using development builds today.

**Closed by Grounded0** 2023-11-09 21:55 UTC
Labels: bug

**Comment by mckellenjaundice122** [comment] 2023-11-09 21:57
Thank you all again for all of your work, if anything, i'm glad this is documented out there so that anyone else running into the same headaches as me gets some reassuring. Keep up the great work, and i'm looking forward to the 0.81 and the future of staging. :)
