### ISSUE TITLE
Implement support for Windows 11 context menu

### ISSUE THREAD

**Issue by ZachKnife1008** [dosbox-staging/dosbox-staging#3881] opened 2024-08-19 22:36 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I'm a bit miffed by the fact that DOSBox Staging doesn't support the new context menu in Windows 11. I think it's about time we change that.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-08-19 23:38
> I'm a bit miffed by the fact that DOSBox Staging doesn't support the new context menu in Windows 11. I think it's about time we change that.

Thanks for volunteering @ZachKnife1008! Looking forward to your PR that add this functionality!

**Comment by Grounded0** [comment] 2024-08-20 00:19
Duplicate of:

- #2305

**Closed** 2024-08-20 00:19 UTC
Labels: duplicate, enhancement

**Comment by Grounded0** [comment] 2024-08-20 00:20
You can also issue a bounty for it. Seems like a fairly easy job so someone might pick it up for 200 USD.

**Comment by johnnovak** [comment] 2024-08-20 01:35
> You can also issue a bounty for this. Seems like a fairly easy job so someone might pick it up for 100 USD.

Yeah, so easy I might as well do it once I'm back from my holidays 😄 Probably a few lines of code in the installer script.
