### ISSUE TITLE
Crashes with mouse_raw_input=false using v0.81.0-rc2

### ISSUE THREAD

**Issue by codeflorist** [dosbox-staging/dosbox-staging#3345] opened 2024-01-23 20:12 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-rc2

### What Operating System are you using?

Windows 11

### Relevant hardware info

Intel i7-13700K, Nvidia 3080 GTX

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

RC2 is very unstable, when `mouse_raw_input = false` is set. If `mouse_capture` is `onclick` it immediately crashes after the mouse is captured. Using `seamless` it seems more stable on my PC, but always crashes on my Surface Pro 6 notebook, once fullscreen is enabled.

### Steps to reproduce the behaviour.

This is reproducable on my PC and Notebook
1. Create new config with RC2
2. Change `mouse_raw_input` to `false`.
3. Launch dosbox.
4. Click the window to capture the mouse

On my laptop, this is also always reproducable (but not on PC):
1. Change `mouse_capture` to `seamless`
2. Enter fullscreen after launch (or use `fullscreen = true` in config

### Your configuration

```ini
mouse_raw_input = false
```

### Provide a Log

```text
no log, because of crash.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment] 2024-01-24 15:19
Not able to reproduce this in Linux.  I'll need to get out my Windows machine to test some of these Windows specific bugs coming in.

**Comment by FeralChild64** [comment] 2024-01-24 16:03
I confirm, I can reproduce the problem on Windows 11, with Intel Arc A770 card.

It’s possible this is SDL library problem - when I copy SDL2.DLL which was shipped with 0.80.1, the problem does not reproduce anymore. When I copy the newer SDL2.DLL version (shipped with 0.81-rc2) to 0.80.1, the problem starts reproducing on 0.80.1.

**Comment by FeralChild64** [comment] 2024-01-24 16:34
If I’m not mistaken, the crash happens within the `SDL_SetRelativeMouseMode(true);` call in `GFX_SetMouseCapture` function.

**Comment by Grounded0** [comment] 2024-01-24 17:39
Should we roll back to SDL 2.26.5 on Windows CI runner?

**Comment by Grounded0** [comment] 2024-01-24 17:42
Can someone check this on macOS too since i'm short on time due to other things.

**Comment by johnnovak** [comment] 2024-01-27 23:10
@FeralChild64 Do you think it would be worthwhile to put together a repro case and submit it to the SDL guys? Ideally, we don't want to ship the final with known bugs on Windows 11, and this seems to be quite serious.

**Comment by shermp** [comment] 2024-01-28 00:12
Just as another data point, I cannot reproduce this on my laptop (Ryzen 7 5800H, Vega graphics), either with `main` or the rc2 download. I am running Windows 11.

I updated my msys2 environment to pull the latest dependencies, where SDL2 is 2.28.5

**Comment by johnnovak** [comment] 2024-01-28 01:56
> Just as another data point, I cannot reproduce this on my laptop (Ryzen 7 5800H, Vega graphics), either with `main` or the rc2 download. I am running Windows 11.
> 
> I updated my msys2 environment to pull the latest dependencies, where SDL2 is 2.28.5

Just to double check, can you try with 2.28.1 as well? @FeralChild64 was able to reproduce with that version. Apparently they have fixed it since then (?). Man, I really dislike to deal with constantly moving targets like this...

**Comment by shermp** [comment] 2024-01-28 02:14
Yeah, tried with 2.28.1 as well. No crashes. So if it's an SDL2 issue, hardware configurations must also be in play.

**Comment by johnnovak** [comment] 2024-01-28 02:15
> Yeah, tried with 2.28.1 as well. No crashes. So if it's an SDL2 issue, hardware configurations must also be in play.

Thanks for checking @shermp.

**Comment by FeralChild64** [comment] 2024-01-28 13:57
> Do you think it would be worthwhile to put together a repro case and submit it to the SDL guys?

@johnnovak For now my attempts to create a repro-snipped have failed, it probably needs more things initialized - I didn't have much time to experiment this week, unfortunately.

**Comment by codeflorist** [comment] 2024-01-28 16:02
I think I've found the common denominator. The crash only happens (on both my machines), if a dpi scaling of more than 100% is selected in the display settings of windows.

Maybe with this it is also reproducable on win 10.

I've also commented this in the SDL-issue.

**Comment by shermp** [comment] 2024-01-28 18:13
Confirmed. I set my scale to 125%, and it immediately crashed. No logs from dosbox unfortunately.

**Comment by johnnovak** [comment] 2024-01-28 22:13
That's great info @codeflorist 🎉 We should add testing with higher than 100% DPI scale factor to our regular regression testing schedule.

**Comment by weirddan455** [comment] 2024-01-30 00:23
I bisected the SDL issue and added some info to hopefully help them come up with a proper fix.  Funny thing is, the SDL regression at fault here was them fixing a bug that we filed back in June.

https://github.com/libsdl-org/SDL/issues/7855
https://github.com/dosbox-staging/dosbox-staging/pull/2611

**Comment by johnnovak** [comment] 2024-01-30 00:41
> I bisected the SDL issue and added some info to hopefully help them come up with a proper fix. Funny thing is, the SDL regression at fault here was them fixing a bug that we filed back in June.
> 
> [libsdl-org/SDL#7855](https://github.com/libsdl-org/SDL/issues/7855) #2611

To give them some credit, fixing such OS integration bugs is a minefield and super hard to regression test.

That's similar to me messing around with the VGA code—I change the order of a few lines, then 6 months later we realiseI broke a few games that do some arcane things with the VGA hardware...

It's no surprise they go through this "two steps forward, one step backward, one more step backward, three steps forward, goto 10" with pretty much every release. You could put a whole 20+ people team on this constantly regression testing everything on every OS combination, and maybe then it would be solid all the time.

**Comment by weirddan455** [comment] 2024-01-30 21:14
Fix has been merged upstream.

**Comment by johnnovak** [comment] 2024-01-30 23:03
> Fix has been merged upstream.

We might just upgrade to the latest SDL, after all 😄 Certainly that's the easiest thing to do...

**Comment by Grounded0** [comment] 2024-01-30 23:52
> So I'm much more inclined to downgrade to 2.28.5 which is known to work well on Windows.

You probably meant SDL 2.26.5 but yeah. We'll need RC3 is we pick SDL 2.30.0 because its a deployment risk for production quality software until proven otherwise through mass testing.

**Comment by johnnovak** [comment] 2024-01-31 00:37
> You probably meant SDL 2.26.5 but yeah.

Correct, yeah 😄 

> We'll need RC3 if we pick SDL 2.30.0 because its a deployment risk for release quality software until proven otherwise through mass testing.

Absolutely. 2.30.0 contains tons of changes, there can be any numbers of regressions of there—we don't wanna go there now.

**Comment by kcgen** [comment] 2024-02-04 00:16
Wanted to add a small suggestion whenever we hit show-stopper bugs in any of our deps: exclude the bad version range in Meson's `version: []` list.

Meson tests the dep's actual version against the list of `version: []` items. All the items need to pass for the dep to be allowed.

- Say all the 2.28.x range is bad, add a single item: `... ,'< 2.28 || > 2.28', ...`
- Or if just a couple specific versions are bad, knock them out one-by-one: `... ,'!=2.28.3', '!=2.28.5', ...`
- 
Now it's to the environment to provide a passing version - be it a Homebrew lib, the fallback wrap, MSYS2 package, hand-built “configure && make”, etc…  The idea being this exclusion is going to hold true no matter who or how the binary is being compiled (be it our own static CI releases, someone at home, Homebrew devs, or a Linux distro).

**Comment by johnnovak** [comment] 2024-02-04 05:55
Thanks @kcgen. The team decided to just go with our previous idea to pin everything, including the SDL version.

The SDL version would be variable per platform, potentially, but the rest of deps would probably be the same version across all platforms for a given release.

The idea is to have 100% reproducible builds, zero moving targets. Every single Staging release would be tied to one set of dependencies (with the SDL version potentially variable per platform).

**Comment by johnnovak** [comment] 2024-02-20 05:34
0.81.0 final is out and 2.3.0 is supposed to fix this, so closing.

**Closed by johnnovak** 2024-02-20 05:34 UTC
Labels: bug, SDL
