### ISSUE TITLE
The Horde stuck on black screen after setting vga_render_per_scanline or vmem_delay on the command line

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3721] opened 2024-06-01 01:17 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7 7700K, 32GB RAM, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Horde will freeze on a black screen or DOS/4GW banner after altering the values of vmem_delay or vga_render_per_scanline.

This happens even when setting the default values.

EDIT: ANY of the values in the [dosbox] section will crash the Horde.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Mount the Horde media.
2. Input any option from the [dosbox] section, like vga_render_per_scanline=true,  vmem_delay=off etc.
3. Run horde.exe
4. Stare at the black emptiness, wondering why this game is so damn finicky.

### Your configuration

```ini
[sdl]
output = opengl
texture_renderer = auto

[dosbox]
machine = svga_s3
memsize = 16

[autoexec]
mount c f:\emus\dosbox\c -t dir
imgmount d f:\Emus\dosbox\library\hordecd.cue -t iso -fs iso
c:
cd c:\horde
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment] 2024-06-01 02:29
I tried to reproduce this but could not. "The Horde" starts fine, on both the latest `main` and `0.81.0`. I'm running Windows 11.

**Comment by weirddan455** [comment] 2024-06-01 07:45
I can't reproduce this either.  Furthermore, neither of those settings are changeable at runtime.  It should always throw an error and do nothing if you attempt to change them.

You said in your other ticket, you were running a batch file from the `[autoexec]` section and removing that fixed it.  Are you still doing that?  Are you running a default config now?  It's very important to be precise about how you are triggering this bug so that others can reproduce it.

![image0001](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/fa74b2ec-cd24-45c0-917c-3826feb2c177)

**Comment by weirddan455** [comment] 2024-06-01 07:57
On `main` I can trigger it by running `memsize=32` from the command line as that config setting is changeable at runtime.  Probably some code that gets run in `DOSBox_RealInit` triggers the bug when it gets executed for a 2nd time by config changes.

I'll look into this more later.  Thanks for the repro case @PoulpSquad

**Comment by johnnovak** [comment] 2024-06-01 09:25
@weirddan455 I'm confused. The original ticket mentions putting `vga_render_per_scanline = true` into the `[dosbox]` section in the config, but you're testing setting it from the CLI after startup. The two are different, so you're not testing what's in the original description, no?

**Comment by weirddan455** [comment] 2024-06-01 10:26
@johnnovak Read the title.  I guess the description is worded somewhat ambiguously.

**Comment by johnnovak** [comment] 2024-06-01 10:32
> @johnnovak Read the title. I guess the description is worded somewhat ambiguously.

Right, got it now. Well, it's easy to miss if you're not paying attention to the wording, yeah 😆 

The good news is that if this only manifests when setting these options from the CLI, it's not even that much backport-worthyd material. If they work fine from the config, that's good enough.

But when FeralChild figures out the Gods keyboard regression, we could backport a fix for this as well. I guess I'm just saying it's not really a showstopper.

**Comment by weirddan455** [comment] 2024-06-01 10:37
Yeah, not a showstopper and the root issue is still present on ‘main’ anyway as there are other runtime changeable config options in [dosbox] that trigger it all the same.

**Comment by PoulpSquad** [comment] 2024-06-01 11:17
Thank you for looking into this. For a moment here I thought I was losing my mind!

**Comment by weirddan455** [comment] 2024-06-01 13:17
This is not a recent regression.  I think `vga_render_per_scanline` and `vmem_delay` may be new-ish config options so attempting to change them on old versions does nothing.  However, `memsize` is an old option and changing it at the CLI has this same behavior going all the way back to OG DOBox 0.74-3.

**Comment by weirddan455** [comment] 2024-06-01 13:36
It's also a very quick fix.  `CMOS_Destroy` was marked with `changeable_at_runtime` but `CMOS_Init` was not.  Sometimes you accidentally delete your CMOS and forget to re-create it.  How embarrassing :blush:

**Comment by johnnovak** [comment] 2024-06-01 13:43
It's always the CMOS batteries causing mayhem 😎

**Comment by PoulpSquad** [comment] 2024-06-01 13:51
Can you guys fix this and still make it changeable at run-time from CLI? That would be amazing!

**Comment by weirddan455** [comment] 2024-06-01 14:04
> Can you guys fix this and still make it changeable at run-time from CLI? That would be amazing!

`vga_render_per_scanline` and ` vmem_delay` were never meant to be changeable at runtime.  We have an internal flag that marks which settings can be changed.  It's just that flag was never actually enforced so it would run re-configure settings and act like it worked regardless.  Presumably changing those settings would have no real effect on v0.81.1.  On the dev branch, I made a change to the CLI utility to instead report an error when attempting to change those settings.

`memsize` is one that is marked changeable.  My patch doesn't change that.  It stops one of the many functions that get run on re-config from being run.

**Closed** 2024-06-01 14:21 UTC
Labels: bug
