### ISSUE TITLE
Support alternative shader directories

### ISSUE THREAD

**Issue by BillyTPilgrim** [dosbox-staging/dosbox-staging#370] opened 2020-05-12 20:55 UTC
Hi all,

Would it be possible to have DOSBox look in its own root folder for a GL shader folder as well as in the current location, the same way that it looks for .conf files? I try to keep my games as portable as possible on my system, so having the option of a glshaders directory inside the DOSBox directory is appealing.

**Comment by dreamer** [comment] 2020-05-12 22:37
Depends on what you mean exactly by "root folder".

I think it would make sense for dosbox-staging to look for shaders into additional locations; some XDG directories, but also e.g. current working directory.

**Comment by BillyTPilgrim** [comment] 2020-05-12 22:42
Yeah, sorry, I don't mean root in the Linux sense of the word, sorry - I'm familiar with working with Linux but I don't use it day to day. I meant the current working directory.

**Comment by kcgen** [comment] 2020-05-13 01:13
Yes,  it would be absurd to place shader files inside each game's directory (mingled in with game-files), because shaders are not game-specific (plus would result in duplicate files spread across many games, in addition to possibly some being older inferior versions).

Although looking _relatively_ off the current-working-directory (say `./shaders/...`) is general good design and tolerates re-organizing the application directory structure. 

I like the idea of a common data directory (XDG-defined), in which perhaps we could have `resync-shaders` script that pulls the latest shaders from @tyrells's repo.

**Comment by kcgen** [comment] 2020-11-16 17:13
> Would it be possible to have DOSBox look in its own root folder for a GL shader folder

@dreamer , I tested and confirmed this works (I think you added this, right?).

@BillyTPilgrim , in latest source build, you can do the following:

Place your shaders into a `glshaders` directory inside your DOSBox Staging configuration directory.  Then configure them using subdirectories and filename relative to that directory:

``` ini
[render]
glshader = crt/crt-lottes.tweaked.glsl
```

Given my directory tree:

``` text
/home/kcgen/.config/dosbox
├── dosbox-staging.conf
├── dosbox-staging-git.conf
└── glshaders
    ├── crt
    │   ├── crt-aperture.glsl
    │   ├── crt-caligari.glsl
    │   ├── crt-easymode.glsl
    │   ├── crt-easymode.tweaked.glsl
    │   ├── crt-lottes.glsl
    │   ├── crt-lottes.tweaked.glsl
...
```

**Comment by mgtroyas** [comment] 2021-05-07 06:57
Sorry I don't completely understand. Is it possible to place the glshaders folder in the same place the dosbox executable resides? The idea is having a portable dosbox install, as already happens with the conf file.

**Comment by kcgen** [comment] 2021-05-07 09:07
> Sorry I don't completely understand. Is it possible to place the glshaders folder in the same place the dosbox executable resides? The idea is having a portable dosbox install, as already happens with the conf file.

The `glshader = `can be an absolute path or relative with respect to the current work directory or the config directory's glshaders subdirectory. 

Just experiment to with the setting and location to learn how it works. 

If that doesn't help, describe your game directories layout, where you're launching dosbox from, and we can help further.

**Comment by mgtroyas** [comment] 2021-05-20 17:38
Ok, now I understood. I have a folder with the dosbox executable, the conf file and a folder called "glshader". In this case I've realized I just need to use the shader filename, like "crt-easymode-halation.glsl" with no additional path. I was adding the folder name before ("glsaders\crt-easymode-halation.glsl") and it didn't work.

Now I have the problem all the shaders show a complete black image, or do nothing at all, but that is another issue.

**Comment by kcgen** [comment] 2021-05-20 21:12
@mgtroyas , glad you're progressing.

Try this - 

1. Place this file ([xbr-lv2.glsl.txt](https://github.com/dosbox-staging/dosbox-staging/files/6518756/xbr-lv2.glsl.txt)) in your `glshaders/` directory. Rename it to `xbr-lv2.glsl` without the `.txt` extension (which I added to let me attach it here in GitHub).

2. Update your config with:

    ``` ini
    [sdl]
    fullscreen = false
    windowresolution = 1280x960
    output = openglnb
    sensitivity = 75
    
    [render]
    scaler = none
    glshader = xbr-lv2.glsl
    ```   

Its 'effect' should be quite apparent, with smooth but crisp edges (click to view 1:1 zoom):

![2021-05-20_14-02](https://user-images.githubusercontent.com/1557255/119049412-5ac36880-b975-11eb-8867-61eb500abf04.png)

**Comment by mgtroyas** [comment] 2021-05-21 08:31
Thank you, I also managed to get the DosBox console (my launcher was hiding it) so now I can see the errors:
1) Don't know what I did yesterday but I must include the path to the shader file in the config file, like "glshaders\crt-easymode.glsl". If not, a "file not found" error is shown on the console.
2) The shader you attached works perfectly. Also does for instance "crt-geom.glsl".
3) But all other shaders like "crt-aperture.glsl", "crt-easymode.glsl" or "crt-lottes.glsl" show a complete black window. No errors are shown on the console.

I've used a lot of these shaders on PCem, on the OpenGL 3.0 renderer, so I don't think is a problem from my system (AMD Radeon RX580).

**Comment by kcgen** [comment] 2022-04-28 20:57
Shaders can reside in custom paths:

```ini
glshader = custom_path/xbr-lv2.glsl
```

The custom path can be absolute or relative.

In the case where it's relative, this allows shaders to be bundled with the game, for example:

``` text
/game/
├── start.exe
├── dosbox.conf
└── game_specific_shaders
    └── xbr-lv2.glsl
```

The conf file could contain `glshader = game_specific_shaders/xbr-lv2.glsl`, and when DOSBox Staging is launched from within `./game/`, it will read the shader.

Closing this, as shaders can exist in custome absolute and relative paths.

**Closed by kcgen** 2022-04-28 20:57 UTC
Labels: enhancement, good first issue, shaders
