### ISSUE TITLE
Weird mouse cursor movement behaviour in Ultima Underworld I

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1722] opened 2022-06-12 07:32 UTC
If you run Ultima Underworld I with any mouse setting other than `sensitivity = 200` or above, slow physical mouse movements are not registered _at all_ below a certain threshold. This is how to reproduce it:

1. Use mouse `sensitivity` lower than 200 (yes, you can trigger it with 199!). Fullscreen vs windowed and `raw_mouse_input` enabled or disabled doesn't make any difference whatsoever.
2. Move your mouse slowly, and if it's slow enough, you can keep moving it indefinitely without the on-screen pointer changing its position even by a single pixel!

This might seem like a non-issue -- just move the mouse a little bit faster, right? Well, the problem is that if you don't "accelerate" your hand fast enough when starting a movement, the pointer won't start to follow your physical mouse immediately, which results in jerky motion and general unresponsiveness. Moreover, you need to stay above the magic threshold whenever you move the mouse; if you drop below it, the pointer will be "stuck" until you cross over the threshold again. Needless to say (but I will say it! 😏), this is super annoying and ruins the gaming experience.

The fact that the problem is "fixed" when using sensitivity values greater than or equal to 200, but still manifests at 199, means that probably something is fundamentally wrong with the mechanism of translating SDL events into DOSBox mouse events. Maybe some weird rounding issue is going on, I don't know. It definitely warrants further investigation not just because of UU1, but all other games might be affected as well, just the issue is not noticeable due to the way they interact with the emulated mouse hardware directly.

All of this was tested on Windows 10, and changing the mouse speed or acceleration in Windows doesn't make any difference to the threshold issue. In fact, as `sensitivity = 200` makes the mouse move quite quickly in the game, one can counteract this by setting the mouse speed to "low" in Windows.

**Comment by kcgen** [comment] 2022-06-12 08:28
I will find the snippet tomorrow (late here right now), but the current logic measures only the movement delta between the last and current mouse position events. If the delta rounds to zero (or less than a pixel on the DOS side), then no movement is registered. Because the logic doesn't keep a running tab for these 'sub pixel' dx, dy values, the accumulated position isn't considered, and the behaviour you mentioned is quite common (fully eating slow movement). 

@FeralChild64, does your PR fix any of this directly, when not using the VMware driver shim?

**Comment by FeralChild64** [comment] 2022-06-12 10:37
My PR keeps the DOS mouse driver behavior mostly unchanged (rework of this part is going to be a part of the next PR) - but the new serial mouse emulation does not forget the sub-pixel movements, so it is likely the problem won't occur.

@johnnovak: Could you try to reproduce it with the serial mouse emulation from my integration branch?
- compile DOSBox from branch https://github.com/dosbox-staging/dosbox-staging/tree/fc/mouse-rework-1
- in _[serial]_ section of the configuration file put _serial1=serialmouse_ (without any additional parameters, they are mostly in case problem occurs, defaults should work 99.9% of the time)
- load CtMouse driver forcing serial mouse (`ctmouse.exe /S` command)

**Comment by johnnovak** [comment] 2022-06-12 11:53
> Because the logic doesn't keep a running tab for these 'sub pixel' dx, dy values, the accumulated position isn't considered, and the behaviour you mentioned is quite common (fully eating slow movement).

Oh man, that's quite bad and most definitely needs to be fixed. The lucky thing is that the problem is not really noticeable in most games...

> Could you try to reproduce it with the serial mouse emulation from my integration branch?

@FeralChild64, I've tried that, but no cigar. These are my findings:

- No improvements whatsoever with `serial1=serialmouse` with or without the `ctmouse` driver being loaded (`sensitivity = 200` doesn't help either).
- With the default mouse settings and `sensitivity = 100` the situation is improved somewhat, but still far from good.
- With the default mouse settings and `sensitivity = 200` the workaround doesn't work anymore.

What I find confusing is that the mouse works in the game even when only specifying ` serial1=serialmouse` but not loading the driver (but the movement is still jerky). Is this supposed to happen, or am I doing something wrong?

**Comment by FeralChild64** [comment] 2022-06-12 20:41
> What I find confusing is that the mouse works in the game even when only specifying serial1=serialmouse but not loading the driver (but the movement is still jerky). Is this supposed to happen, or am I doing something wrong?

That's expected behavior - serial mouse and DOS/BIOS mouse emulation are almost completely independent and work in parallel.

**Comment by FeralChild64** [comment] 2022-07-23 19:02
@johnnovak Are you sure this is an emulator issue, and not the game issue? I could reproduce the problem:

- with DOSBox Staging built-in mouse driver
- with DOSBox Staging, with Mouse Systems mouse driver
- with DOSBox Staging, with CtMouse 2.1 driver
- with DOSBox X
- with QEMU using CtMouse driver

I haven't tried DOSEmu and 86Box yet.

**Comment by johnnovak** [comment] 2022-07-23 23:54
> @johnnovak Are you sure this is an emulator issue, and not the game issue? I could reproduce the problem:
> 
>     * with DOSBox Staging built-in mouse driver
> 
>     * with DOSBox Staging, with Mouse Systems mouse driver
> 
>     * with DOSBox Staging, with CtMouse 2.1 driver
> 
>     * with DOSBox X
> 
>     * with QEMU using CtMouse driver
> 
> 
> I haven't tried DOSEmu and 86Box yet.

No I'm not, but testing this in other emulators doesn't really prove much, other than those emulators not being 100% faithful to the real hardware either, I guess? As projects often take bits of code form one another, it's quite plausible that all of them are broken in some specific way. 

If you think about it, the game has very good support for playing it via the mouse only. My reasoning is it would've been a huge oversight to have released it with such broken mouse support. I might be wrong, though, but unfortunately I can't test it on actual hardware myself.

Another warning flag is that when you use `sensitivity = 200`, the mouse movement becomes fluid (the start/stop behaviour is comppletely gone), but then it's hard to make precise movements. My workaround for that is to disable raw mouse input, and set the mouse speed to the slowest setting at the OS level. Apparently people here are using the same workaround:

https://www.gog.com/forum/ultima_series/uw_1_and_2_problem_with_mouse

So unless you can 100% confirm the issue is present on real hardware, I'd keep looking :shrug:

**Comment by FeralChild64** [comment] 2022-07-26 04:21
Post on the GOG forum by Litoncinnamon:

> What worked for my was going into my gaming mouse's driver setup and setting the polling rate down from "500 Hz" to "125 Hz" (As low as it will go) and immediately all of my mouse issues were gone. It seems a high polling rate can cause DOSBox to spaz out on certain games.

gives a clue: the game does not like high mouse sampling rates. And I confirm this by experimenting with various DOS mouse drivers and enforced/hardcoded settings.
BTW, the game has really crappy mouse support, it does not subscribe to events (which could be limited in rate easily in the current driver), instead it polls the mickey counters, which are currently updated in a real time - probably nobody would guess this could be a problem.

We need to introduce a mouse setting to alter the sampling rate (easy) and make sure states which can be polled are not updated more often (not fun at all, elegant solution will require another redesign…)

**Comment by johnnovak** [comment] 2022-07-26 04:40
> gives a clue: the game does not like high mouse sampling rates. And I confirm this by experimenting with various DOS mouse drivers and enforced/hardcoded settings.
> BTW, the game has really crappy mouse support, it does not subscribe to events (which could be limited in rate easily in the current driver), instead it polls the mickey counters, which are currently updated in a real time - probably nobody would guess this could be a problem.

Great detective work, so glad to hear you're making progress on this! 🥳

**Comment by kcgen** [comment] 2022-07-26 05:30
> make sure states which can be polled are not updated more often (not fun at all, elegant solution will require another redesign…)

When these game poll the mouse state, are we required to return a value? (ie: like a blocking function call, so the "throttling" on a real system would be through the inherent latency in the equipment and PS/2 or serial bus?)

Or is it the polling mechanism like a callback, or ping-ping function, where the game registers the poll request, and then some milliseconds later we can write the mouse state into some function or memory register?

**Comment by FeralChild64** [comment] 2022-08-03 19:21
@kcgen: MOUSE.COM interface is a complicated little beast.

One possibility for the application is to subscribe to callbacks - in 99% cases this is what applications do, and the rate of callbacks is actually limited by every branch of DOSBox, usually to 200 per second.

But when asked (I mean - our internal MOUSE.COM replacement, hardware interfaces work differently), we have to return the value of an internal counter (called a mickey counter) or cursor position - put them into registers before we return from INT33. Ultima Underworld uses this mechanism - actually, it asks for the counters really often, and it seems it cannot handle situation where these counters change too often (and today gaming mice can easily reach 1000 changes per second...).

---

I have fixed the problem in my development branch - https://github.com/FeralChild64/dosbox-staging/tree/fc/mouse-updates-4
You can change the emulated mouse sampling rate by executing `MOUSECTL.COM dos -r <value>`, default is currently 125 Hz.

I have chosen 125 Hz, as this is the sampling rate of basic (non-gaming) USB mice - so that everyone should now have a similar experience by default, there shouldn't be a situation where the game works or not depending on the host system mouse settings.
And 125 Hz is still quite a lot - Microsoft Mouse Driver 8.20 sets PS/2 mouse to 60 Hz, CuteMouse asks for 100 Hz.

**Comment by 0mnicydle** [comment] 2022-08-10 23:45
I haven't done too much testing on this yet, but it looks like this commit related to this issue has at least causes problems with mouse button events in Doom:

https://github.com/dosbox-staging/dosbox-staging/commit/9a42619611c62bdb35b948bc93720096be751615

Buttons presses/releases may fail to register completely, and if you hold a mouse button the associated action may be noticeably delayed compared to normal. I haven't looked too deeply into this but it sounds like there has been changes to the mouse polling rate? I have a 1000Hz mouse and I suspect that if DOSBox is doing direct polling at a lower rate (as opposed to emulating a lower rate with buffered events), then events will be missed.

**Comment by johnnovak** [comment] 2022-08-11 00:52
Just to be clear, this is *game* issue; the weird mouse behaviour is 100% reproducible on real hardware. There's nothing to fix here at the emulator level.

Please see this comment for further details:
https://github.com/dosbox-staging/dosbox-staging/pull/1833#issuecomment-1206480824

It's nice that via emulation we can set the sensitivity to 200 and get rid of the weird start threshold behaviour stutter when not moving the mouse fast enough (btw, FastTracker II has the exact same issue on real hardware, *but* only when moving the mouse to the right or downwards).

**Comment by 0mnicydle** [comment] 2022-08-11 03:07
Another side effect of that commit is circle strafing with mouse in Doom is noticeably less smooth than I am used to.

I am having flashbacks to when this commit caused similar issues:

https://github.com/dosbox-staging/dosbox-staging/commit/c03ba5df8abe2930a9b58f899b8b64ef04d46098

**Comment by kcgen** [comment] 2022-08-11 03:55
@0mnicydle , regarding https://github.com/dosbox-staging/dosbox-staging/commit/ff42c8e400e46f8f2f4a2b66738d5b8d7e1a6d7e - I think there were some follow-up adjustments, correct? (just want to be sure we're not still carrying that as a regression).

**Comment by 0mnicydle** [comment] 2022-08-11 04:12
@kcgen Correct. I believe the first commit I posted by mistake was a refinement of the second, and ultimately everything got rolled back to before the first.

**Comment by FeralChild64** [comment] 2022-08-11 04:32
@0mnicydle The idea of this patch was to limit the polling rate to something more manageable by DOS software (actually to 125 Hz for movements, but for buttons it actually cheats and updates them more often). I intend to make this adjustable (the code is actually written on my development branch), but I assume we are already in the string freeze.

If there are smoothness issues, I can check whether it is feasible to rise this in the mouse code to, let say, 200 Hz (if there are no serious regressions with known problematic games).

I’ll try to have a look at the buttons issues later today.

**Comment by kcgen** [comment] 2022-08-11 04:40
It's working pretty nice as it is; I think @johnnovak even reported that it's better than physical hardware. 

@FeralChild64 : is it possible for people running at higher Hz rates (like @0mnicydle , who also has a high-refresh display), to use `MOUSECTL.COM dos -r 500` to crank up the poll rate?

**Comment by 0mnicydle** [comment] 2022-08-11 04:47
@FeralChild64 Just going by memory of the 200Hz floor instituted the last time a polling change was attempted, I don't think it will feel too much different than 125Hz, but if it doesn't defeat the purpose of what you are trying to accomplish to have it at 200Hz instead, that does have the whole PS/2 analogue appeal going for it.

But yes, the button thing is something else entirely if you already took steps to account for missed events--I don't remember the last crack at this having the button issue.

And again, whatever direction this ends up going, I just hope power users don't lose the ability to retain the current per tick polling we have now, as it's part of the "Nyquist DOSBox" recipe (to steal an expression of @kcgen's) speed/smoothness freaks like me really desire.

**Comment by Grounded0** [comment] 2022-08-11 06:49
Giving pro users ability to set their mouserate seems like a good idea. We want something that works out of the box for everyone but allows customisation for pro users who understand caveats.

**Comment by 0mnicydle** [comment] 2022-08-11 10:48
> Giving pro users ability to set their mouserate seems like a good idea. We want something that works out of the box for everyone but allows customisation for pro users who understand benefits and caveats of their choices.

Preferably with an intelligent mechanism in place to skip any sort of time since last poll evaluation in favor of a simple guaranteed poll per tick at values equal to or greater than the tick rate... I worry that if it's simply left to the user to express as a rate that's being timed against even at a value of 1000, some minor timing error could end up with the evaluation coming up short by some tiny amount and periodically skipping a polling event.

**Comment by johnnovak** [comment] 2022-08-11 10:57
Yeah, I've also noticed that in many games the pointer moves _much_ smoother in DOSBox than on real hardware. CPU speed doesn't really matter here, I'm using a fast Pentium MMX; it's just that software-based mouse support was always an aftertought on DOS PCs (unlike on the Amiga, for instance, where the mouse pointer used a hardware sprite from the computer's inception in 1985, so it was 100% buttery smooth 100% of the time, regardless of CPU speed or load, just like on modern computers).

So what I'm trying to say, if it doesn't introduce weird bugs, smoother movement is always preferable in emulation in my opinon.

**Comment by Grounded0** [comment] 2022-08-13 21:33
Closing this as #1850 has been merged. Feel free to reopen it if this issue pops up again.

Connected ticket:
- #1850

**Closed by Grounded0** 2022-08-13 21:33 UTC
Labels: bug

**Comment by misha-tpt** [comment] 2022-11-08 23:18
I'm still running into this issue on 0.79.1 in Ultima Underworld, and I'm confused what the solution is intended to be besides changing sensitivity to 200 🤔

**Comment by johnnovak** [comment] 2022-11-08 23:42
> I'm still running into this issue on 0.79.1 in Ultima Underworld, and I'm confused what the solution is intended to be besides changing sensitivity to 200 🤔

This is an issue unfixable at the emulator level as it's present on real hardware too. I'm not aware of any other workaround than setting the sensitivity to 200 (and optionally lowering the mouse sensitivity at the OS level to somewhat counteract the resulting faster mouse speed).

See this comment for further details: https://github.com/dosbox-staging/dosbox-staging/issues/1722#issuecomment-1211446457

**Comment by FeralChild64** [comment] 2022-11-09 17:17
@misha-tpt In 0.80.0-alpha you can limit the rate even further from the command line, for example `MOUSECTL -r 100` - maybe this will improve the situation a bit for you. Unfortunately, it seems nothing more can be done.
