### ISSUE TITLE
Remap Mouse Buttons to keys/vice versa?

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#979] opened 2021-04-18 22:29 UTC
Do you think it could be possible to add the ability to use mouse buttons for keys and the other way around? It could be useful for certain games.

**Comment by kcgen** [comment] 2021-04-19 02:26
@OpenRift412 , it's come up before, and we definitely want this. 

Like you said, the benefits are extreme -- I don't think I'm exaggerating either 😅.

Give mousing games consume one hand, adding three to five additional actions (wheel up, down, middle-click, forward/back thumb buttons) adds a whopping 250% more actions on the mouse-side over the common two button limit.

I think this support is critical to removing atleast one element that makes games age badly. Infact, I would say that leaving perfectly viable mouse inputs 'dead' is an severe disservice.

Also, unlike controllers, SDL uses fixed mouse event names - so folks packaging games could provide canned mouse mappings that make the nose sense for a give game.  This type of thing could be crowd-sourced too. 

I will add it to the 0.78 list and also take a look at the feasibility in the meantime!

**Comment by nemo93** [comment] 2021-08-31 13:17
Closing as this is in fact a duplicate of #583. Definitely to improve mapper to bing more events/devices/inputs would be nice.

**Closed by nemo93** 2021-08-31 13:17 UTC
Labels: enhancement
