### ISSUE TITLE
SimCity 2000 Special Edition crash and data corruption on exit

### ISSUE THREAD

**Issue by galland101** [dosbox-staging/dosbox-staging#3868] opened 2024-08-10 11:55 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 7 7800X3D, NVIDIA GeForce RTX 3070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The GOG DOS release of SimCity 2000 SE seems to run, but upon quitting the game, it dumps a a number of lines saying "illegal command" and "File open error".  The files in the C drive that SimCity 2000 is installed in get corrupted.  The game cannot be launched again until after DOSBox Staging is restarted.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Game using SC2000.BAT file.
2. Run Game and load a few scenarios
3. Quit Game

### Your configuration

https://gist.github.com/galland101/ff175c1fe1c5c474be9c595272f26115

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-08-10 12:13
Duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/3518 (read the whole thread for details if interested.)

The workaround that fixes the issue is documented in our wiki:
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#simcity-2000

It's just a badly coded game that assumed some very specific memory layout and `LOADFIX` fixes that.

**Closed** 2024-08-10 12:13 UTC
Labels: bug, duplicate
