### ISSUE TITLE
Perfect Assassin Exception: 00, Error code: 0000

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#2475] opened 2023-05-13 16:46 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81-alpha-710-g84a8831ef

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro Linux Last Version

### Relevant hardware info

CPU: AMD Ryzen 7 - Nvidia 3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the beginning of the game, we enter the first cave. There is a dying alien, when trying to talk to him, the game kicks us out with the following error Exception: 00, Error code: 0000

I have tried several different cd images

I have tried dosbox 0.74.3 with the same dosbox-stagging.conf file and it works well.

![Sin nombre](https://github.com/dosbox-staging/dosbox-staging/assets/7293829/b1f975c6-92e7-4f21-bcf8-b2d4075cacb8)

### Steps to reproduce the behaviour.

Installation:
-Minimum install

Sound Card:
-Sound Blaster 16

-Try to talk to the dying alien in the first cave you see at the beginning of the game.

### Your configuration

```ini
machine   = svga_s3
memsize   = 32
cputype   = pentium_slow
cycles    = max
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-05-13 17:18
`cycles = max` is usually too much (especially on modern hardware).

Looks like `cycles = 100000` is enough to max out the game, and no issues talking to the alien.

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/a8d3954d-e9b2-4bb0-805d-85de01a8c884

You can hold "Alt + F12" to fast-forward through the initial "loading ... " screen too.

**Comment by MasterO2** [comment] 2023-05-13 17:42
Now added to game issues accordingly:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#perfect-assassin

**Comment by orderorder** [comment] 2023-05-13 19:34
> `cycles = max` is usually too much (especially on modern hardware). Try to find the least fixed-cycles needed to run the game just at the edge of it's peak frame-rate.
> 
> Looks like 60k to 100k is sufficient to max out the game, and no issues talking to the alien.
> 
> Suggest `cycles = 85000`
> 
>  pass_000.mp4 
> You can hold "Alt + F12" to fast-forward through the initial "loading ... " screen too.

I just tried the stable version of dosbox-stagging 0.80.1 and it doesn't fail.

**Comment by Grounded0** [comment] 2023-05-13 21:08
@kcgen Should we reinvestigate this or what? ⬆️

**Comment by johnnovak** [comment] 2023-05-13 22:00
I think we should. Hard crashes that are "fixed" by using different cycles settings are never great.

**Comment by kcgen** [comment] 2023-05-13 23:44
"Another crash on the cause way!" ->  :sweat_smile:  (The CauseWay memory extender was famous for being incredibly buggy)

Returned back to the C: prompt, with the emulator and DOS core still ticking along.

Will double check, none the less.

It's a crash in CauseWay extender.

**Comment by kcgen** [comment] 2023-05-14 15:43
> I just tried the stable version of dosbox-stagging 0.80.1 and it doesn't fail.

@orderorder , can you confirm the CauseWay extender doesn't crash on latest `main` with those conf settings?  (I've already confirmed this on my system, however would appreciate that verification). Then we can close this out.

**Comment by kcgen** [comment] 2023-05-14 16:45
> I think we should. Hard crashes that are "fixed" by using different cycles settings are never great.

The reason CauseWay 0.74.3 doesn't crash under 0.74.3 is because 0.74.3 predates the addition of the x86-64 dynrec core to SVN.

Doing a bit more testing, the threshold where the CauseWay extender starts crashing is 475000 cycles. I suspect a fast Pentium II or III would be able to crash it too.

**Comment by orderorder** [comment] 2023-05-14 17:21
I am testing on two different computers. It seems that the fact that it worked in the stable version 0.80.1 was something accidental that occurs with some randomness. After restarting dosbox many times, both in the latest "main" version and in the stable version, the game keeps crashing.

**Comment by kcgen** [comment] 2023-05-14 17:58
> both in the latest "main" version and in the stable version, the game keeps crashing.

If 500k+ cycles are used, it crashes in all dosboxes (or `cycles = max` on a fast enough system that can exceed 500k cycles).

Are you positive you're using fixes `cycles = 100000` or less? The window title bar will show "100000 cycles/ms".  At that point, CauseWay should not crash.

**Comment by kcgen** [comment] 2023-05-14 20:47
There's nothing more to investigate.
 - I've reproduced the crash on SVN and X all above 500k cycles
 - Reproduced the crash with the normal core also above 500k cycles
 - All are fixed by lowering cycles to 100k (well, below 475k, but the game only needs around 60k to 100k)

**Comment by johnnovak** [comment] 2023-05-14 20:47
Yeah, weird things happen even in late DOS era programs with the default cycles=max setting. E.g. in Tomb Raider demo the main menu just keeps spinning and spinning without any user interaction and there is no way to stop it... Set cycles to 200k and it's perfect.

**Closed by kcgen** 2023-05-14 20:47 UTC
Labels: bug

**Comment by orderorder** [comment] 2023-05-14 20:49
> There's nothing more to investigate.
> 
> * I've reproduced the CauseWay crash on SVN and X all above 500k cycles
> * Also reproduced with the `normal` core above 500k cycles
> * All are fixed by lowering cycles to 100k (well, below 475k, but the game only needs around 60k to 100k)

I have done several tests and I agree with the cycles

**Comment by kcgen** [comment] 2023-05-14 20:53
Thanks @orderorder :+1:
