### ISSUE TITLE
On CRT VGA display, Psycho Pinball freezes on high res mode with aspect ratio set to off

### ISSUE THREAD

**Issue by petran79** [dosbox-staging/dosbox-staging#3689] opened 2024-05-21 16:57 UTC
version 0.81.1:

I use Linux Mint 21.3 connected to a CRT VGA monitor and have DosBox Staging fullscreen set to true and aspect ratio to off so games like Jazz Jackrabbit can be set to fill the whole screen during gameplay.
However there is an issue with Psycho Pinball. With aspect ratio off, high-res mode tables freeze after a while. Low-res mode tables run fine.
In order for high res tables to play I have to disable aspect ratio on dosbox.conf. 
When I previously run Jazz Jackrabbit, exited the game and run Psycho Pinball, during freeze I could hear sound from game Jazz Jackrabbit when I pressed buttons.
As a result I run the game with separate config file.

Command log gives the following.

petros@petrospc:/mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging$ ./dosbox
date       time         | 
2024-05-21 19:40:43.456 | arguments: ./dosbox
2024-05-21 19:40:43.456 | Current dir: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging
2024-05-21 19:40:43.456 | stderr verbosity: 0
2024-05-21 19:40:43.456 | -----------------------------------
2024-05-21 19:40:43.456 | dosbox-staging version 0.81.1
2024-05-21 19:40:43.456 | ---
2024-05-21 19:40:43.456 | LOG: Loguru version 2.1.0 initialised
2024-05-21 19:40:43.476 | CONFIG: Loaded primary config file '/home/petros/.config/dosbox/dosbox-staging.conf'
2024-05-21 19:40:43.476 | CONFIG: Loaded local config file 'dosbox.conf'
2024-05-21 19:40:43.476 | LANG: Using internal English language messages
2024-05-21 19:40:43.511 | SDL: version 2.29.0 initialised (x11 video and pulseaudio audio)
2024-05-21 19:40:43.511 | DISPLAY: Initialised 758x569 windowed mode using bilinear scaling on display-0
2024-05-21 19:40:44.022 | OPENGL: Vendor: NVIDIA Corporation
2024-05-21 19:40:44.022 | OPENGL: Version: 4.6.0 NVIDIA 550.78
2024-05-21 19:40:44.022 | OPENGL: GLSL version: 4.60 NVIDIA
2024-05-21 19:40:44.022 | OPENGL: NPOT textures supported
2024-05-21 19:40:44.056 | RENDER: Using shader 'none'
2024-05-21 19:40:44.056 | VGA: Pixel doubling enabled
2024-05-21 19:40:44.057 | VIDEO: Using the DOS video mode's frame rate
2024-05-21 19:40:44.072 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0x7ad648200010
2024-05-21 19:40:44.073 | VGA: Double scanning VGA video modes enabled
2024-05-21 19:40:44.073 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2024-05-21 19:40:44.084 | VOODOO: Initialized with 4 MB of RAM, multithreading, and no bilinear filtering
2024-05-21 19:40:44.085 | CAPTURE: Image capturer started
2024-05-21 19:40:44.090 | MIXER: Negotiated 2-channel 48000 Hz audio of 1024-frame blocks
2024-05-21 19:40:44.090 | MIXER: Master compressor enabled
2024-05-21 19:40:44.091 | MIXER: Reverb enabled ('medium' preset)
2024-05-21 19:40:44.091 | MIXER: Chorus enabled ('normal' preset)
2024-05-21 19:40:44.216 | MT32: Unknown file in ROM folder: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging/mt32-roms/a__m-9.27c256.ic27.bin             
2024-05-21 19:40:44.223 | MT32: Unknown file in ROM folder: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging/mt32-roms/r15179857.ic13.bin                 
2024-05-21 19:40:44.261 | MT32: Unknown file in ROM folder: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging/mt32-roms/a__m-9.27c256.rom                  
2024-05-21 19:40:44.261 | MT32: Unknown file in ROM folder: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging/mt32-roms/sed1200-a.bin                      
2024-05-21 19:40:44.283 | MT32: Unknown file in ROM folder: /mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos/staging/mt32-roms/r15179917.ic19.bin                 
2024-05-21 19:40:44.300 | MT32: Initialised MT-32 Control v1.07 from mt32-roms
2024-05-21 19:40:44.300 | MT32: Operating at 48000 Hz without resampling
2024-05-21 19:40:44.300 | MIDI: Opened device: mt32
2024-05-21 19:40:44.301 | MPU-401: Running in intelligent mode on ports 330h and 331h
2024-05-21 19:40:44.301 | OPL: Operating at 48000 Hz without resampling
2024-05-21 19:40:44.301 | OPL: Running OPL3 on ports 220h and 388h
2024-05-21 19:40:44.301 | OPL: Sound Blaster 16 OPL output filter enabled
2024-05-21 19:40:44.314 | DMA: Initialised primary controller
2024-05-21 19:40:44.314 | DMA: Initialised secondary controller
2024-05-21 19:40:44.314 | SB: Operating at 22050 Hz and upsampling to the output rate
2024-05-21 19:40:44.314 | SB16: Modern DAC output filter enabled
2024-05-21 19:40:44.314 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2024-05-21 19:40:44.314 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2024-05-21 19:40:44.315 | GUS: Operating at 48000 Hz without resampling
2024-05-21 19:40:44.315 | GUS: Setting 'ULTRASND' environment variable to '240,3,3,5,5'
2024-05-21 19:40:44.315 | GUS: Setting 'ULTRADIR' environment variable to 'C:\ULTRASND'
2024-05-21 19:40:44.315 | GUS: Running on port 240h, IRQ 5, and DMA 3
2024-05-21 19:40:44.315 | PCSPEAKER: Operating at 48000 Hz without resampling
2024-05-21 19:40:44.315 | PCSPEAKER: Initialised discrete model
2024-05-21 19:40:44.315 | PCSPEAKER: High-pass filter enabled (18 dB/oct at 120 Hz)
2024-05-21 19:40:44.315 | PCSPEAKER: Low-pass filter enabled (12 dB/oct at 4800 Hz)
2024-05-21 19:40:44.324 | MOUSE: Will be captured after the first left or right button click
2024-05-21 19:40:44.324 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2024-05-21 19:40:44.325 | MOUSE (PS/2): Standard, 3 buttons
2024-05-21 19:40:44.404 | DOS: Loaded modern locale for country 1, 'United States'
2024-05-21 19:40:44.422 | SLIRP: Slirp version: 4.7.0
2024-05-21 19:40:44.422 | SLIRP: Successfully initialized
2024-05-21 19:40:44.422 | NE2000: Initialised on port 300h and IRQ 3
2024-05-21 19:40:44.423 | CONFIG: Loaded auto-mounted drive config file 'resources/drives/y.conf'
2024-05-21 19:40:44.423 | AUTOEXEC: Using autoexec from one or more joined sections
2024-05-21 19:40:44.469 | MAPPER: No joysticks found
2024-05-21 19:40:44.484 | MAPPER: Failed loading mapperfile 'mapper-sdl2-0.81.0-rc1.map' directly or from resources
2024-05-21 19:40:44.485 | MAPPER: Loaded default key bindings
2024-05-21 19:40:44.504 | SDL: Window size initialized to 256x192 pixels
2024-05-21 19:40:44.636 | SDL: Using standard SDI (auto) display refresh rate of 85 Hz
2024-05-21 19:40:44.811 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 720x400 pixels with 1:1 (1:1) pixel aspect ratio                                                               
2024-05-21 19:40:44.814 | OPENGL: VSync state: on                     
2024-05-21 19:40:44.815 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 720x400 pixels with 1:1 (1:1) pixel aspect ratio                                                               
2024-05-21 19:40:44.815 | MOUNT: Path 'resources/drives/y' found      
2024-05-21 19:40:44.818 | MOUNT: Path '/mnt/7571a82e-f4bb-4ae8-90aa-252228c292c7/msdos' found                                               
2024-05-21 19:40:44.843 | CDAUDIO: Operating at 48000 Hz without resampling
2024-05-21 19:40:59.776 | GUS: Activated 14 voices at 44100 Hz
2024-05-21 19:41:00.103 | DISPLAY: VGA 320x240 256-colour graphics mode at 59.713 Hz VFR, scaled to 640x480 pixels with 1:1 (1:1) pixel aspect ratio
2024-05-21 19:41:00.111 | DISPLAY: VGA 320x240 256-colour graphics mode at 59.713 Hz VFR, scaled to 640x480 pixels with 1:1 (1:1) pixel aspect ratio
2024-05-21 19:41:09.067 | SDL: Using standard SDI (auto) display refresh rate of 58 Hz                                      
2024-05-21 19:41:09.082 | DISPLAY: VGA 320x368 256-colour graphics mode at 67.391 Hz throttled VFR, scaled to 668x768 pixels with 1:1 (1:1) pixel aspect ratio                            
2024-05-21 19:41:09.102 | DISPLAY: VGA 320x368 256-colour graphics mode at 67.391 Hz throttled VFR, scaled to 668x768 pixels with 1:1 (1:1) pixel aspect ratio
2024-05-21 19:41:22.487 | CDROM: Shutting down CD-DA player
2024-05-21 19:41:22.487 | PCSPEAKER: Shutting down discrete model                                
2024-05-21 19:41:22.487 | GUS: Audio comprised of 8-bit samples from 1 voices                    
2024-05-21 19:41:22.488 | GUS: Shutting down                                                     
2024-05-21 19:41:22.488 | OPL: Shutting down OPL3                                                
2024-05-21 19:41:22.488 | SB16: Shutting down                                                    
2024-05-21 19:41:22.488 | MPU-401: Shutting down                                                 
2024-05-21 19:41:22.488 | MT32: Shutting down                                                    
2024-05-21 19:41:22.488 | CAPTURE: Image capturer shutting down                                  
2024-05-21 19:41:22.488 | DMA: Shutting down primary controller                                  
2024-05-21 19:41:22.488 | DMA: Shutting down secondary controller                                
2024-05-21 19:41:22.903 | atexit   

As for Dosbox.conf file, if I set aspect ratio to off, game freezes at high res table mode.

fullscreen          = true
display             = 0
fullresolution      = original
windowresolution    = default
window_position     = auto
window_decorations  = true
transparency        = 0
host_rate           = auto
vsync               = auto
vsync_skip          = 0
presentation_mode   = auto
output              = opengl
texture_renderer    = auto
waitonerror         = true
priority            = auto auto
mute_when_inactive  = false
pause_when_inactive = false

aspect             = on
integer_scaling    = off
viewport           = fit
monochrome_palette = amber
cga_colors         = default
glshader           = none

**Comment by MasterO2** [comment] 2024-05-21 17:29
You have a lot of `Unknown file in ROM folder` error messages, so have you tried running Psycho Pinball **without** MT32 configured?  Maybe those unknown MT32 roms that you're using are causing the freezing?

**Comment by petran79** [comment] 2024-05-21 17:40
will try but sound in-game is not set to mt32. I think it has more to do with monitor resolution and refresh conflicts as vga switches natively, unlike in Windows 10. I set xorg conf to skip EDID information so I can set custom low resolutions below 640x400

**Comment by johnnovak** [comment] 2024-05-21 22:24
@petran79 DOSBox Staging is a self-contained emulator -- its goal is to faithfully replicate the  retro-PCs experience in a purely software environment on current operating systems. Interfacing with various retro hardware is out of scope, including CRT monitors.

Nobody in the dev team has the ability to test with actual CRT monitors connected to a modern PC running Staging. I don't think I even have DVI ports anymore, just HDMI on my PC :) 

So, if some (or most? I have no idea) work with your CRT monitor, treat is a bonus. But it's an unsupported bonus 😄

**Closed by johnnovak** 2024-05-21 22:24 UTC
Labels: out of scope

**Comment by weirddan455** [comment] 2024-05-27 02:33
I agree that supporting CRT monitors could be considered out of scope.  I don't own a CRT monitor myself to test with.  However, I think there may be something actionable here.

The core issue, if I understand correctly, is that we are attempting to set the host's resolution to something that the monitor does not support resulting in a black screen.  This is something that could affect LCD monitors as well if these same settings are used, although typically LCD users would prefer to use the LCD's native resolution and use DOSBox's scaling (since an LCD monitor's built-in scaler is usually crap and doesn't respect aspect ratio).

**Comment by petran79** [comment] 2024-05-27 03:22
I notice that some games show black screen at full screen when I set output to OpenGL with bilinear filtering while others do the same if I set it to texture with nearest neighbour. Though in this case bilinear filtering is not applied at all . In post 0.81.1 dev builds bilinear filter is shown in windowed mode but game turns black in full screen.

**Comment by johnnovak** [comment] 2024-05-27 03:23
> I agree that supporting CRT monitors could be considered out of scope. I don't own a CRT monitor myself to test with. However, I think there may be something actionable here.
> 
> The core issue, if I understand correctly, is that we are attempting to set the host's resolution to something that the monitor does not support resulting in a black screen. This is something that could affect LCD monitors as well if these same settings are used, although typically LCD users would prefer to use the LCD's native resolution and use DOSBox's scaling (since an LCD monitor's built-in scaler is usually crap and doesn't respect aspect ratio).

Yeah I have a bunch of CRTs but honestly can't be arsed to maintain such a niche feature.

You might right about the `fullresolution` problem (when it's not set to `desktop`). I see that as very low priority, though; 99.99% of people use the native res.

**Comment by Grounded0** [comment] 2024-05-27 08:04
Duplicate of:

- #3206
