### ISSUE TITLE
Raspberry Pi4 Retropie sound issue

### ISSUE THREAD

**Issue by jlopezvil** [dosbox-staging/dosbox-staging#326] opened 2020-04-26 23:32 UTC
I have using a Raspberry Pi4 with Raspbian GNU/Linux 10 (buster).

I have compiled dosbox-staging with --disable-opus-cdda  option becasuse if not is doesn compile saying opusfile not found. Prevoiusly I have installed libopusfile0 package but as I said it doesnt compile if i dont use the "--disable-opus-cdda" option.

Using "--disable-opus-cdda" option it compiles but when playing games there is not sound from mounted cds with audio tracks. 

I post here compile log withouth --disable-opus-cdda option ...

[rps_2020-04-26_174827.log](https://github.com/dosbox-staging/dosbox-staging/files/4536694/rps_2020-04-26_174827.log)

Thanks.

**Comment by kcgen** [comment] 2020-04-26 23:40
@jlopezvil , thanks for the report!

Can you try this in your `dosbox-staging` source directory:

```
sudo apt install $(./scripts/list-build-dependencies.sh -c gcc -m apt)
```
That should install all of the build dependencies. Then try an optimized build:

```
./scripts/build.sh -c gcc -t release -m lto
```

**Comment by jlopezvil** [comment] 2020-04-26 23:56
With your two commands it is compiling and detecting opusfile.
Thanks a lot...

Also another issue. With raspberry pi4 with kernel 5.4 now with dosbox in full screen the image is not centered on the monitor.. Its on the left.  I have readed this is because using 
dtoverlay=vc4-kms-v3d and not dtoverlay=vc4-fkms-v3d  in  boot/config.txt

Could you make something in your optimized code to get the image be centered on screeen (full screen)?

**Comment by dreamer** [comment] 2020-04-27 00:00
@jlopezvil can you make a screenshot or photo of how does it look in practice? What options do you have set in `.conf` file?

**Comment by kcgen** [comment] 2020-04-27 00:14
@jlopezvil ,

Edit `/home/pi/.config/dosbox/dosbox-staging-git.conf`, and make these changes:

- `fullscreen = true`
- `output = texturenb`
- `capture_mouse = onstart middlerelease`
- `glshader  = none`

If you're Rpi4 is feeding an HDMI TV, then also update all of the audio rates from `44100` to `48000` except for `gusrate` (which should stay at 44100). 48 kHz is the native sampling rate over HDMI, so this will avoid any resampling in your audio chain.

**Comment by jlopezvil** [comment] 2020-04-27 00:17
Monitor is 16x9. Image is correct but not centered is on the left ...
Here the config file (changed extension to .txt for append HERE)
[dosbox-SVN.conf.TXT](https://github.com/dosbox-staging/dosbox-staging/files/4536754/dosbox-SVN.conf.TXT)

**Comment by kcgen** [comment] 2020-04-27 00:20
@jlopezvil , that file appears to be for DOSBox SVN, which `dosbox-staging` will not use.

`dosbox-staging` uses `/home/pi/.config/dosbox/dosbox-staging-git.conf`. Can you confirm that you have this file? Also, when you run `dosbox` from the command line, it will print the config file that it's using in the first couple lines of output on your console.

**Comment by dreamer** [comment] 2020-04-27 00:21
Or `/home/pi/.config/dosbox/dosbox-staging.conf` if you happened to build the tagged `0.75.0-rc1` stable release.

**Comment by jlopezvil** [comment] 2020-04-27 00:40
Runnig it is saying ...

MIXER: Can't open audio: No available audio device , running in nosound mode.

**Comment by kcgen** [comment] 2020-04-27 01:23
RetroPie is launching the original DOSBox implementation; so to use `dosbox-staging`, we'll have to "swap in" your compiled binary, and also copy dobox-staging's config file.

1. Drop to the command line (**_alt + F4_** in RetroPie)
1. Change directories to where you compiled `dosbox-staging`
1. Manually launch and then quit it: `./src/dosbox .` then press **_ctrl+F9_**
1. Inspect the console output for it's config file.
    You're looking for:
    - `/home/pi/.config/dosbox/dosbox-staging.conf`, or
    - `/home/pi/.config/dosbox/dosbox-staging-git.conf`
1. Edit this config file per the settings I mentioned in my prior post above.
1. Now change directories to one of your DOS games, and manually launch it using your dosbox-staging binary, and confirm it starts up properly and is centered.  At this point, you know your `dosbox-staging` configuration is setup properly. Don't move onto the next steps until this is done and confirmed good.
1. Change directories back to your `dosbox-staging` source, where you compiled the binary.
1. Overwrite RetroPie's dosbox **binary** with your compiled binary:
    - `sudo cp ./src/dosbox /opt/retropie/emulators/dosbox/bin/dosbox`
1. Overwrite RetroPie's dosbox **conf** file with your version, which you learned in step 4 above.  You'll launch either:
    - `sudo cp  /home/pi/.config/dosbox/dosbox-staging-git.conf /opt/retropie/configs/pc/dosbox-SVN.conf`, or
    - `sudo cp  /home/pi/.config/dosbox/dosbox-staging.conf /opt/retropie/configs/pc/dosbox-SVN.conf`
1. Now type `exit` to jump back to Emulationstation and try launching a game from RetroPie. Hopefully it's now using dosbox-staging and your config file.  Also, never update DOSBox again from RetroPie's setup script (otherwise it will re-overwrite the changes you made here).

**Comment by jlopezvil** [comment] 2020-04-27 08:47
Done as you say ... 
But not sounds

MIXER: Can't open audio: No available audio device , running in nosound mode.

**Comment by kcgen** [comment] 2020-04-27 09:01
Edit your conf file, and make the midi settings:

```
mpu401 = intelligent 
 mididevice = default 
 midiconfig = 128:0
```

Then recopy your config over top retropie's file like before. 

If that doesn't fix it, try running: `pulseaudio --daemon`, and retry.

**Comment by nemo93** [comment] 2020-04-27 13:05
@jlopezvil out of curiosity what game(s) is/are you trying to run here? I'd like to try on my end to replicate your issue.

**Comment by kcgen** [comment] 2020-04-27 13:32
@nemo93 , thanks for lending your help. I could reproduce the video left-justification in windowed-mode Pi3 but unfortunately can't reproduce this sound issue (my kernel's default alsa setup is sufficient; I'm not using an asound.conf or pulse).

**Comment by jlopezvil** [comment] 2020-04-27 14:19
With you advices I have running dos-box staggin with pi4 with no sound issues and centered ...
Im now trying the game Pinball Fantasys
Only issue now is that dosbox is getting better benchmark running it tha dosbox-staging.
dosbox runs well the game but dosbox-staggin is a bit slow running it ...
[dosbox-SVN.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4540163/dosbox-SVN.conf.txt)
[dosbox-staging-git.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4540164/dosbox-staging-git.conf.txt)


Some idea?

**Comment by kcgen** [comment] 2020-04-27 14:32
Glad your problem is solved @jlopezvil ; was it the midi-settings or did you need pulseaudio running as well?

Please share the benchmark are you running, and results from both binaries so we can compare and investigate. Thanks.

**Comment by dreamer** [comment] 2020-04-27 14:35
(Just a suggestion)
```
output = texture
texture_renderer = opengles2
```
?

Also, since you are compiling yourself because we don't have ARM builds yet - make sure, that you are compiling release builds (it makes a difference); @kcgen listed instructions for you earlier:

    ./scripts/build.sh -c gcc -t release -m lto

If you want to configure yourself, then you need *at least* following flags:

    ./configure CFLAGS="-DNDEBUG -O3" CXXFLAGS="-DNDEBUG -O3"

(but script is going to pick better flags specific for your architecture, etc)

**Comment by dreamer** [comment] 2020-04-27 14:51
For everyone in the thread: what do you suggest we can do to avoid such out-of-the-box problems?
Should we ask RetroPie community to include dosbox-staging in available emulators?

**Comment by jlopezvil** [comment] 2020-04-27 14:53
I have include it for myself ...    Later i will try parameters and also again building script.

**Comment by kcgen** [comment] 2020-04-27 14:58
> Should we ask RetroPie community to include dosbox-staging in available emulators?

I think so; and I believe @nemo93's [on it](https://retropie.org.uk/forum/post/212756) :-)

Regarding finding and editing the config file, having an argument like `dosbox -edit`, that automatically opens the config file using $EDITOR or falls back to known-present editors on the respective platforms (notepad.exe or WordPad.exe on Windows, TextEdit on macOS, perhaps nano on Linux).

**Comment by dreamer** [comment] 2020-04-27 15:05
There are options `-editconf` and `-printconf`, but it seems like they do not work on Linux at all - it seems like they never worked on Linux - they don't work in 0.74-3 for me either, grrr :(.

And it's also bad, that there's no `dosbox --help` available to discover them (and users might not know, that we have our own man page - especially users compiling from source).

**Comment by jlopezvil** [comment] 2020-04-27 15:09
It a bit embarrasing .... 

By mistake I was running   dosbox standar because using a .sh file that calls dosbox and not dosbox-staging ....     Also make this change it works .. Only was necessary the command that @kcgen suggest my to dependences was installed ... Command was  sudo apt-get install -y $(./scripts/list-build-dependencies.sh -c gcc -m apt)    (upper in the issue)

**Comment by dreamer** [comment] 2020-04-27 15:33
Well, people make mistakes - happens to everyone :) Through more scrutiny, we discovered some missing pieces, so the results are positive overall.

@jlopezvil tell us about performance and if you find any new issues; if there's nothing worthy of bugtracker issue, then close this report, please.

I reported #327 and will look at `-printconf` today.

@kcgen As for MIDI - every solution in this area will be platform-specific for now (at least until FluidSynth lands). I was notified that one of dosbox retroarch cores fixed MIDI autodetection problems on Linux - we planned to improve this area as well, but perhaps the work is already done.

**Closed** 2020-04-27 15:40 UTC
Labels: Raspberry Pi, question

**Comment by kcgen** [comment] 2020-04-27 16:56
On my Pi3 I get numerically-identical performance when comparing:
- RetroPie's build of the original dosbox, which uses SDL1 and when configured with its fastest `output=surface` setting.
- RetroPie's build of their patched SDL2-version of dosbox, which uses SDL2 and using its default settings.
- A release-build of dosbox-staging, which uses using SDL2 and any of the `output=texture*` modes.

For example, with `cycles=max 95% and `machine=vgaonly` Quake `quake.exe +timedemo demo1 +exec mode0.cfg -nosound -nocdaudio` produces 9.5 FPS in all three. 

Using `cycles=fixed 29000`, all three produce 11.4 FPS, and they consume just under 100% CPU when monitoring in `top` (they bounce around between 93% and 96%).

**Comment by jlopezvil** [comment] 2020-04-27 19:06
I must say that with later changes suggested by @dreamer , that was output = texture
texture_renderer = opengles2 and also rate to 48.000 dosbox-staging runs same that dosbox, no issues with sound and centered with correct aspect ....    Great and only one day beetwen opening issue and closing with things running ok. Now time to more test and getting running better if is possible .....

**Comment by jlopezvil** [comment] 2020-05-05 21:15
Sorry guys, making more tests with other pinball games, with the same config, for example, dosbox is running correctly but dosbox-staggin is running slower ... With Pinball Fantasies it runs ok both of them. But with epic pinball dosbox runs ok but dosbox-staggin runs slower.

Configs are the same as last post (dosbox with overlay and dosbox-staing with output = texture
texture_renderer = opengles2)

Some ideas to test?

**Comment by kcgen** [comment] 2020-05-06 04:32
Some folks have reported stuttering and sound issues (even throwing big hardware at it).  The game is actually very efficient CPU-wise, and it runs with 8000 cycles in real-mode. 

Try pasting the following into your Pi's shell; it creates a new game directory in `/tmp`. It configures the game to use the Gravis Ultrasound, and includes a local `dosbox.conf` tailored for the game:

``` shell
cd /tmp
wget "https://github.com/dosbox-staging/dosbox-staging/files/4584789/setup-epic_pinball.sh.txt" -O - | bash
```

Then launch it:

``` shell
cd EpicPinball
/path/to/dosbox-staging/src/dosbox start.bat
```

If that works, then you can incorporate whatever configuration elements work into your own setup.

[epic_pinball-config.tar.gz](https://github.com/dosbox-staging/dosbox-staging/files/4584766/epic_pinball-config.tar.gz)
[setup-epic_pinball.sh.txt](https://github.com/dosbox-staging/dosbox-staging/files/4584789/setup-epic_pinball.sh.txt)

**Comment by jlopezvil** [comment] 2020-05-07 10:05
Sorry, where I must to place to dosbox.conf specific file. I know the general dosbox-staging-git.conf its located on ..../configs/pc ....     Specific with the modified params for epicpinball must be placed on the game directory (later mounted as c unit) ?

**Comment by dreamer** [comment] 2020-05-07 10:28
@jlopezvil dosbox-staging loads .conf files in the following order:

1. If user passed paths to config files using `-conf` or `-userconf` parameter, then these files will have the highest priority and no other files will be loaded beforehand. User can pass multiple files this way, and subsequent files will overwrite settings from previous ones (except `autoexec` section, which will be merged), e.g.:

        $ dosbox -conf A.conf -conf B.conf

    *Only files A.conf and B.conf are loaded, A first, B overrides/appends to settings from A.*

2. If no `-conf` parameters are passed, then `dosbox.conf` from **current working directory is used** (only this file; it doesn't matter directory is loaded as drive C or not)

3. If there's no `dosbox.conf` in current working directory, then default conf file is used (default path for stable release: `~/.config/dosbox/dosbox-staging.conf`)

4. If default file does not exist, then a new one is generated.

You can see exactly which files were loaded on stderr (I know, not the best place); they are prefixed with `CONFIG`, e.g.:

```
$ ./src/dosbox 
dosbox-staging version 0.75.0
---
CONFIG: Loading primary file /home/dreamer_/.config/dosbox/dosbox-staging.conf
```

(I don't  know Retropie does it exactly, perhaps the project has its own scheme enforced via -conf parameters)

Hope this helps a bit :)

**Comment by jlopezvil** [comment] 2020-05-07 13:03
autoexec section ...... ?    How it works?

**Comment by dreamer** [comment] 2020-05-07 13:54
@jlopezvil example:

File `a.conf` has "@echo A" inside, file `b.conf` has "@echo B" inside - when user runs:

```
$ dosbox -c "@echo C" -conf a.conf -conf b.conf
```
then dosbox shell will write:
```
A
B
C
```

**Comment by jlopezvil** [comment] 2020-05-07 21:57
Now i Have learning how adjust parameters per game ... Only editing the game.conf and adding here the parameteres different from standard in  dosbox-staging-git.conf

Now each game can take different cpu parameters and sound. It works ... Thanks again.

**Comment by jlopezvil** [comment] 2020-05-07 22:00
Example ....

This in  /home/pi/RetroPie/roms/pc
[EpicPinball.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4596001/EpicPinball.conf.txt)

This the standard and first readed in   /opt/retropie/configs/pc/
[dosbox-staging-git.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4596002/dosbox-staging-git.conf.txt)

**Comment by kcgen** [comment] 2020-05-08 05:22
Glad you're all set @jlopezvil !
