### ISSUE TITLE
Investigate playability issues with Falcon A.T. (1988)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2899] opened 2023-09-16 00:35 UTC
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `FalconAT/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Grounded0** [comment] 2023-09-18 20:02
Will be reviewed soon.

**Comment by Burrito78** [comment] 2023-09-21 11:31
Results (macOS Ventura 13.5.2/Apple M2):

**DOSBox Staging 0.81.0-alpha-1689**
Regression against DOSBox SVN!
Switching between fullscreen/windowed sometimes results in a black screen. This can be fixed by switching again.
Otherwise all OK.

**DOSBox SVN	snapshot 12.09.23**
Game locked up for me after around 30s.

**DOSBox-X v2023.09.01**
Game locked up for me after around 30s.

I don't run Windows so i can't test with Daum.

**Comment by johnnovak** [comment] 2023-09-21 21:39
> Switching between fullscreen/windowed sometimes results in a black screen.

That's a weird one @Burrito78. Can you try if different presentation modes fix this? Can you try explicit CFR and VFR? Does texture output mode change anything?

**Comment by Burrito78** [comment] 2023-09-22 08:45
OK, after some more testing i have to say that the picture comes back after some time, takes 1 to 2 seconds for me when it happens.

Happens when you are in the resolution when you are in the cockpit of the plane on the airfield.

Only happens in presentation mode 'auto'!

**Comment by johnnovak** [comment] 2023-09-22 09:48
> OK, after some more testing i have to say that the picture comes back after some time, takes 1 to 2 seconds for me when it happens.
> 
> Happens when you are in the resolution when you are in the cockpit of the plane on the airfield.
> 
> Only happens in presentation mode 'auto'!

What is your monitor's refresh rate @Burrito78? So with CFR and VFR set explicitly it never happens, can you 100% confirm that? This is important.

Is there any movement on the screen when you toggle fullscreen and the screen turns black?

**Comment by kcgen** [comment] 2023-09-22 10:01
Great; should be easy to reproduce and I suspect a small fix. (Currently the presenter is disengaged across some SDL changes like this.. maybe we can leave it engaged).

**Comment by Burrito78** [comment] 2023-09-22 11:44
My screen is 60Hz and the issue only happens in 'auto' mode, not CFR or VFR, just verified again.

![Bildschirmfoto 2023-09-22 um 13 42 19](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/24cd75a6-86e7-4844-a3dc-b8a7a1c9f53d)

Yes, there is movement. These two pixels are blinking.

![Bildschirmfoto 2023-09-22 um 13 44 01](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/36fc67b5-d837-4970-a3e1-a25e2e711cd8)

**Comment by rderooy** [comment] 2023-09-22 12:16
Only single-player mode was tested.

Game seems to run just fine here with the various DOSBox builds. No issues with freezing or the screen turning black.

Switching to full-screen only works properly for SDL2 builds, due to my Wayland multi-display setup. For SDL1 builds, it goes into a multi-monitor full-screen with the a small dosbox window in the middle between monitors. But these are SDL specific issues.

To start flying, first press W to unleash the brakes. Then keep + pressed to accelerate, and finally just use the up key to lift off.

@Burrito78 in your screenshot the brakes are on.

My monitors are 75Hz CFR. No support for VFR.

Some log fragments:
```
2023-09-22 14:05:20.394 | DISPLAY: Text 640x400 16 color (mode 03h) at 70.087 Hz VFR, scaled to 1280x960 with 1.2 pixel aspect ratio
2023-09-22 14:05:24.495 | CHOICE: '1' (#1 of 3 choices)
2023-09-22 14:05:24.628 | DISPLAY: EGA 640x350 16 color (mode 10h) at 70.086 Hz VFR, scaled to 1280x960 with 1.371 pixel aspect ratio
2023-09-22 14:05:37.994 | DISPLAY: EGA 640x400 16 color (mode 0Eh) at 70.086 Hz VFR, scaled to 1280x960 with 1.2 pixel aspect ratio
2023-09-22 14:06:30.771 | SDL: Using VRR-adjusted (auto) display refresh rate of 72 Hz
2023-09-22 14:06:30.771 | DISPLAY: EGA 640x400 16 color (mode 0Eh) at 70.086 Hz VFR, scaled to 1920x1440 with 1.2 pixel aspect ratio
2023-09-22 14:06:33.194 | SDL: Using standard SDI (auto) display refresh rate of 75 Hz
2023-09-22 14:06:33.194 | DISPLAY: EGA 640x400 16 color (mode 0Eh) at 70.086 Hz VFR, scaled to 1280x960 with 1.2 pixel aspect ratio
2023-09-22 14:06:34.102 | SDL: Using VRR-adjusted (auto) display refresh rate of 72 Hz
2023-09-22 14:06:34.102 | DISPLAY: EGA 640x400 16 color (mode 0Eh) at 70.086 Hz VFR, scaled to 1920x1440 with 1.2 pixel aspect ratio
2023-09-22 14:06:35.095 | SDL: Using standard SDI (auto) display refresh rate of 75 Hz
2023-09-22 14:06:35.095 | DISPLAY: EGA 640x400 16 color (mode 0Eh) at 70.086 Hz VFR, scaled to 1280x960 with 1.2 pixel aspect ratio
```

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
priority=higher,higher
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[vsync]
[cpu]
core=auto
cputype=auto
cycles=auto
isapnpbios=true
[keyboard]
[pci]
[mixer]
[midi]
mididevice=default
[sblaster]
[gus]
[innova]
innova=true
[speaker]
[joystick]
[serial]
[printer]
[parallel]
dongle=true
[glide]
[dos]
[ipx]
[ne2000]
[ide, primary]
enable=false
[ide, secondary]
enable=false
[ide, tertiary]
[ide, quaternary]
[autoexec]
mount c .\eXoDOS\FalconAT
c:
@echo off
cls
@call run
exit
```

**Comment by rderooy** [comment] 2023-09-22 12:37
FYI, it seems there are 2 releases of the game, the original 1988 release, and a later 1994 CD compilation release. The later one apparently supports mouse, which does not appear to be the case for the eXoDOS version.

**Comment by kcgen** [comment] 2023-09-22 13:13
Adding myself to looking into black screen issue for the 0.81 release.

**Comment by Grounded0** [comment] 2023-09-23 04:53
Anyone testing this will find these instructions useful:

Falcon 3.0 (DOS, 1991) Keyboard Shortcuts:

https://cheatography.com/alejulian/cheat-sheets/falcon-3-0-dos-1991/

Getting your F-16 off the ground from default setup:

1. Turbine start and spool up: Press on your NUMPAD section STAR (*) key until RPM/N1 hit 100 %
2. Press on your NUMPAD section key FORWARD SLASH (/) to turn afterburner ON. (MIL => AB 1)
3. Set maximum afterburner fuel burn by pressing COMMA (,) until AB 5 is indicated
4. Release wheel brakes by pressing W
5. Acquire positive climb
6. Pull gear up by pressing G

Playing this again brings a lot of memories of my 286. 😁

**Comment by Grounded0** [comment] 2023-09-23 05:00
I'm somewhat of a combat flight simulator geek so i can say base mechanics of the game seem to work well.

**Comment by Grounded0** [comment] 2023-09-26 06:18
I tested this Innovation audio option and seems to work well:

<img width="1392" alt="Screenshot 2023-09-26 at 9 07 16" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/4a2a1477-820f-4f67-a890-715624d636ef">

Closing since everything seems to be working.

**Comment by Grounded0** [comment] 2023-09-26 06:33
There seems to be an issue with 0.81 so opening it for now until its resolved.

**Comment by johnnovak** [comment] 2023-10-12 08:34
@Grounded0 I'm a bit confused by your above comment: is there a regression or not? If there is, what is it exactly?

**Comment by Grounded0** [comment] 2023-10-12 08:47
Its not a game compatibility issue so we could close this for now. It has something to do with SDL:

> Switching between fullscreen/windowed sometimes results in a black screen. This can be fixed by switching again.
Otherwise all OK.

**Comment by Grounded0** [comment] 2023-10-12 08:52
@Burrito78

Can you file a followup ticket on your fullscreen/window mode change issue as we're closing this since its not directly game compatibility related issue.

**Closed** 2023-10-12 08:52 UTC
Labels: game compatibility, regression

**Comment by Burrito78** [comment] 2023-10-12 11:15
https://github.com/dosbox-staging/dosbox-staging/issues/2993
