### ISSUE TITLE
Relentless: Twinsen's Adventure (LBA) throws a VESA error at startup.

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3749] opened 2024-06-09 03:11 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

Hello,

I'm having trouble running Relentless: Twinsen's Adventure (Little Big Adventure).

It crashes 100% of the time with an error that reads:

Error: SVGA card BIOS does not support VESA extensions.
Please refer to your SVGA card documentation for installing VESA driver.

This happens with all versions of Staging I've tried (0.75, 0.78, 0.79, 0.80 and 0.81) and all variations of the S3 machine settings (svga_s3,  vesa_oldvbe and vesa_nolfb).

SDD 5.3a has no effect on this issue.

In 0.80 and 0.81 at least, other machine types like paradise seem to be working (I didn't test them for very long, the intro seems to be playing fine).

Is there a way to make LBA run with machine=svga_s3?

Thank you for your time.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-06-09 04:31
@PoulpSquad Try this and perhaps also limiting `cycles`.

```ini
[render]
vga_render_per_scanline = off
```

**Comment by PoulpSquad** [comment] 2024-06-09 04:40
Thank you for your quick reply johnnovak,

vga_render_per_scanline = off nor cycles=fixed 5000 have had any effect.

**Comment by Grounded0** [comment] 2024-06-09 04:46
I would like to have some corroborating reports on this since this has Moby Score of 8.2 and is fairly popular game especially in Europe.

**Comment by PoulpSquad** [comment] 2024-06-09 05:02
@johnnovak 

vesa_mode = halfline and vesa_mode = all have no effect on my end :/

**Comment by johnnovak** [comment] 2024-06-09 05:27
So is it working in 0.81.1 then on Paradise? Can you play it 50-10 minutes and report back?

There's nothing to be gained from "making it run on S3" if it's perfectly playable on Paradise.

**Comment by Grounded0** [comment] 2024-06-09 05:32
30 minutes of playtime should be enough to close this off and make a note in Wiki that Paradise video option is required.

**Comment by johnnovak** [comment] 2024-06-09 05:38
Yeah, and to elaborate further, of course fixing regressions is a good thing, but if it's been like this since 0.75, it would be probably super hard to figure out what the difference is... And most games are fine; it's not like every VESA game broken since 0.75.

So hence I'm saying, tread carefully, and if `svga_paradise` makes it possible to run the game, probably best to leave the SVGA code alone.

**Comment by Grounded0** [comment] 2024-06-09 05:41
Since it was like this since DOSBox Staging 0.75 that would mean the regression happened somewhere between DOSBox 0.74 and DOSBox SVN since DOSBox Staging largely was about bringing DOSBox SVN to the masses.

**Comment by johnnovak** [comment] 2024-06-09 05:41
> Since it was like this since DOSBox Staging 0.75 that would mean the regression happened somewhere between DOSBox 0.74 and DOSBox SVN since DOSBox Staging largely was about bringing DOSBox SVN to the masses.

Well, that's another idea: could you test in SVN too @PoulpSquad?

**Comment by PoulpSquad** [comment] 2024-06-09 05:43
@johnnovak : Sure, I'll get on it right now and report back.

**Comment by martyMcfly7** [comment] 2024-06-09 05:46
Sorry to interrupt, but I have LBA and LBA2 working with the default staging config (0.81.1). I have had no issues with any of the few past staging releases to my knowledge. This sounds like a bad ISO or wrong setup configuration. I'm currently running the CD version of LBA with svga_s3.

**Comment by Grounded0** [comment] 2024-06-09 05:48
@martyMcfly7 

Thanks for bringing out the point that these are two very popular games. I also think its a bad ISO now that you report that both games run okay.

**Comment by PoulpSquad** [comment] 2024-06-09 05:58
I just tried the european version (LBA) and it seems to work.

Both dumps (Euro and US) were tested against the latest DAT from Redump. Maybe the US version I have isn't a bad dump but a different release?

**Comment by Grounded0** [comment] 2024-06-09 06:00
Hard to say whats happening there but it isn't our concern. 😁

**Closed** 2024-06-09 05:59 UTC
Labels: bug, game compatibility, video

**Comment by interloper98** [comment] 2024-06-09 06:02
All good here too. Default install using CI latest build and only adjusting cycles:

```ini
[cpu]
cpu_cycles_protected = 50000

[autoexec]
@echo off
imgmount d "cd\Little Big Adventure.cue" -t cdrom
mount c .
c:
cd lba
LBA
```

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/374aa7b2-6e95-4149-96e6-acf34606ce06

**Comment by PoulpSquad** [comment] 2024-06-09 06:04
Ah man, I'm glad it works. I love this game!

Thank you guys for your help, I appreciate it!

**Comment by johnnovak** [comment] 2024-06-09 07:35
Thanks @interloper98 @martyMcfly7 and @PoulpSquad for the investigation. Glad to see it was just a case of a bad dump/rip or maybe some obscure version difference.
