### ISSUE TITLE
Green background in Windows 3.x console

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2512] opened 2023-05-22 16:53 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

GIT from few days ago (I have problems with current main), also reproducible on 0.80.1

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

MS-DOS prompt from Windows 3.11, if launched in windowed mode, has a strange background color.

BTW, displaying the DOSBox version in this case is, in my opinion, not needed - especially using such a bright color, IMHO not playing well with default Windows theme.

### Steps to reproduce the behaviour.

1. Install Windows 3.11 for Workgroups 
2. Go to _Main_ group, launch _PIF Editor_, open `dosprmpt.pif` file, change from _Full Screen_ to _Windowed_, save the file
3. Go to _Main_ group, launch _MS-DOS Prompt_
4. Enjoy the green console background instead of the traditional black one

![bug](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/5a1a0750-9b4e-4f33-8192-8cc27f26a846)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-05-22 17:13
Reproduced on SVN too.

![2023-05-22_10-10](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/41cfac87-db6a-4013-b3ec-6cc888c7427a)

DOSBox-X shows the correct black background.

**Comment by kcgen** [comment] 2023-05-22 22:49
> DOSBox-X shows the correct black background.

Bisected to https://github.com/joncampbell123/dosbox-x/commit/bc33031c7d609f1148273a0565641cdd14134b3a

**Comment by Grounded0** [comment] 2024-01-01 06:27
Since this is still apparently broken the workaround is to launch MS-DOS Prompt in full screen and then press Alt+Enter to switch the DOS prompt to windowed mode.

**Comment by Grounded0** [comment] 2024-01-03 07:00
Confirmed with 0.81.0 RC:

<img width="924" alt="Screenshot 2024-01-03 at 8 58 53" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/ad3a3c64-4c82-495d-8031-1e651b4862ee">

**Comment by Grounded0** [comment] 2024-01-03 07:02
The workaround for now is to launch MS-DOS Prompt in full screen mode and then press Alt+Enter to switch the MS-DOS Prompt to windowed mode.

**Comment by Grounded0** [comment] 2024-06-24 14:53
Someone should check is this fixed with S3 Trio64 driver release v1.70. The graphics driver does much of the work here.

**Comment by interloper98** [comment] 2024-06-24 15:50
Using the PIF editor, set the `DOSPROMPT.PDF` with high graphics memory:

![2024-Jun-24_08-45-42](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/d36de75b-fe2e-494c-bc94-890ad1e39033)

Result:

![2024-Jun-24_08-46-23](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/808ca8b1-39c9-4219-9301-f1a23a5e1960)
 
Still a bug, but at least it works!

**Comment by Grounded0** [comment] 2024-06-24 16:10
Looks like we can close this since this is a driver issue.

**Comment by Grounded0** [comment] 2024-06-24 16:22
@interloper98 

Does this problem still occur just by setting the value from full screen to windowed?

**Comment by Grounded0** [comment] 2024-06-26 21:56
I'm suggesting closing this on the basis that INT 10h modesetting code sets odd/even disable for alphanumeric text mode (as real hardware does).

Fixing this would break something else as its a deviation from how the real hardware behaves.

Current workaround is here: https://github.com/dosbox-staging/dosbox-staging/issues/2512#issuecomment-2186890444

**Comment by interloper98** [comment] 2024-06-26 22:43
I can confirm that @Grounded0.
If the pif settings are left with defaults like you've shown then the windowed prompt background is green.

**Comment by johnnovak** [comment] 2024-06-26 22:56
Thanks @Grounded0 and @interloper98, there is nothing to fix here, I agree. Our aim is to be bug-compatible with all DOS software running on real hardware.

**Closed by johnnovak** 2024-06-26 22:56 UTC
Labels: bug, video, Windows 3.x

**Comment by Grounded0** [comment] 2024-08-22 09:53
This seems to have been fixed with 0.81.0 RC:

<img width="1392" alt="Screenshot 2024-08-22 at 12 53 31" src="https://github.com/user-attachments/assets/8ef51bc0-7e40-473a-bd6e-0418a34e7c41">

**Comment by Grounded0** [comment] 2024-08-22 10:05
Yeah still bugging with 0.82.0 RC1 as predicted by INT 10h modesetting code sets odd/even disable for alphanumeric text mode (as real hardware does).

Workaround here:

https://github.com/dosbox-staging/dosbox-staging/issues/2512#issuecomment-2186890444
