### ISSUE TITLE
Privateer 2 Crash

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#2983] opened 2023-10-10 09:41 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The stable 80.1 release runs Privateer 2, however every time I run the game with 0.81.0-alpha it crashes out of dosbox completely

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Privateer 2 using "Dark.exe" in staging 0.81.0-alpha
2.
3.

### Download URL of affected game or software

eXodos release

### Your configuration

```ini
Default settings, IE I just drag and dropped the exe
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-10-10 22:21
Looks like we have a dynamic recompiler regression. Related:
https://github.com/dosbox-staging/dosbox-staging/issues/2984

**Comment by weirddan455** [comment] 2023-10-11 14:44
Can you please test against latest main?  If this is the same problem as #2984 it should be fixed in https://github.com/dosbox-staging/dosbox-staging/commit/b75daa22a0c470f581c67de5138296d427e06fe6

**Comment by johnnovak** [comment] 2023-10-11 21:40
> Can you please test against latest main? If this is the same problem as #2984 it should be fixed in [b75daa2](https://github.com/dosbox-staging/dosbox-staging/commit/b75daa22a0c470f581c67de5138296d427e06fe6)

@Python-Exoproject would you be able to retest this with the latest MSVC dev build? The MSYS build is currently broken.

**Comment by Python-Exoproject** [comment] 2023-10-13 11:36
Thanks guys. Ive had a chance to now check the newest build and can confirm the issue is resolved. Also fixed the same problem with Tomb Raider Gold

**Comment by Grounded0** [comment] 2023-10-13 12:17
Seems like this can be closed now.

**Closed** 2023-10-13 12:17 UTC
Labels: bug, regression
