### ISSUE TITLE
Crash with RaspiOS Legacy and BRCM GPU drivers

### ISSUE THREAD

**Issue by cmitu** [dosbox-staging/dosbox-staging#3590] opened 2024-04-11 15:36 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Relevant hardware info

Raspberry Pi 3B

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Version 0.81 doesn't work anymore with the legacy GPU stack (BRCM), even though the drivers can deliver an accelerated GLES2 context. Previous version, using a similar `output=texture` or `output=texturenb` configuration, didn't have an issue (see [here](https://gist.github.com/cmitu/4a016749a6d27323d590554c5fdc50d4) for a succesfull log file from the previous version).

### Steps to reproduce the behaviour.

Kind of difficult without having a RaspiOS (buster) using the BRCM GPU drives, since the current RaspiOS release is using the open source MESA drivers, which shouldn't have this issue (tested ok on the Pi4, which uses the same driver).

Just starting `dosbox` is enough to crash the application. (see the log below). 

### Your configuration

```ini
Changed from the default `.conf` (generated via `-printconf`):

output              = texture
texture_renderer    = opengles2
glshader = none
```
Full config: https://gist.github.com/cmitu/b2468c59f558ccd8dcf9ecf403e7b32f
```


### Provide a Log

```text
ate       time         |
2024-04-11 15:26:35.586 | arguments: /opt/retropie/emulators/dosbox-staging/bin/dosbox --fullscreen
2024-04-11 15:26:35.587 | Current dir: /home/pi/RetroPie-Setup
2024-04-11 15:26:35.587 | stderr verbosity: 0
2024-04-11 15:26:35.587 | -----------------------------------
2024-04-11 15:26:35.587 | dosbox-staging version 0.81.0
2024-04-11 15:26:35.587 | ---
2024-04-11 15:26:35.587 | LOG: Loguru version 2.1.0 initialised
2024-04-11 15:26:35.592 | CONFIG: Loaded primary config file '/home/pi/.config/dosbox/dosbox-staging.conf'
2024-04-11 15:26:35.593 | LANG: Using internal English language messages
2024-04-11 15:26:35.684 | SDL: version 2.30.2 initialised (RPI video and alsa audio)
2024-04-11 15:26:35.685 | DISPLAY: Initialised 1067x800 windowed mode using bilinear scaling on display-0
2024-04-11 15:26:35.731 | SDL: Failed to create window: Could not create GLES window surface
Stack trace:
6   0x7674b768 __libc_start_main + 268
5     0x28b7e0 sdl_main(int, char**) + 6316
4      0xe3344 Config::Init() const + 40
3      0xe3240 Section::ExecuteInit(bool) + 120
2     0x287cd4 /opt/retropie/emulators/dosbox-staging/bin/dosbox() [0x287cd4]
1     0x2876dc /opt/retropie/emulators/dosbox-staging/bin/dosbox() [0x2876dc]
0      0xf1d78 E_Exit(char const*, ...) + 92
2024-04-11 15:26:35.731 | ABORT: SDL: Could not initialize video: Could not create GLES window surface
Aborted
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment] 2024-04-11 16:30
I do have a Raspberry Pi 3 laying around but Debian 10 (buster) is old legacy.  It's not even listed on their download page anymore.  Legacy is Debian 11 and current is Debian 12.

Debian 10 (on desktop) works for v0.81.0 as far as I know but we have dropped support for it on the main branch (I believe due to its old compiler version not supporting some newer C++ features we wanted to use).

Your best bet is to upgrade the OS honestly.  I doubt anyone on the core team wants to fuss with Debian 10 since we decided to drop support for it.

You could also try forcing software rendering with SDL environment variables to see if it'll work.  Run `export SDL_RENDER_DRIVER=software` in the terminal before launching dosbox.

**Comment by cmitu** [comment] 2024-04-11 16:42
> I do have a Raspberry Pi 3 laying around but Debian 10 (buster) is old legacy. It's not even listed on their download page anymore. Legacy is Debian 11 and current is Debian 12.

Yes, it's 'old legacy'.

> Debian 10 (on desktop) works for v0.81.0 as far as I know but we have dropped support for it on the main branch (I believe due to its old compiler version not supporting some newer C++ features we wanted to use).

 Hm, the `gcc` version on RaspiOS (Raspbian) 10 works compiles fine the current release - version 8.3.0.

> 
> Your best bet is to upgrade the OS honestly. I doubt anyone on the core team wants to fuss with Debian 10 since we decided to drop support for it.

 Sure, that's an option, but I don't think the OS is at fault here - but the GLES 'only' part of the drivers.

> You could also try forcing software rendering with SDL environment variables to see if it'll work. Run `export SDL_RENDER_DRIVER=software` in the terminal before launching dosbox.

That's produces the same crash, with an extra line with 
```
2024-04-11 16:38:46.308 | SDL: Failed to set 'opengles2' texture renderer driver; falling back to automatic selection
```
 since the SW render driver was forced.

**Comment by cmitu** [comment] 2024-04-11 18:52
> I mean, the graphics drivers are a part of the OS. If you want to compile a new Mesa, feel free but I would just upgrade OS if I were you.

They're kind of not, since I can still install the legacy BRCM legacy drivers on the latest RaspiOS, but let's say that's true. I know that it works with an upgraded OS and with the Mesa drivers - I said so in the first post.

I suspect the bug is rather triggerd by the fact that the legacy driver is a _OpenGL ES2_ only GPU/driver, without any OpenGL (classic/core) support. Shouldn't Dosbox Staging be working in such a configuration, rather than outright crash ?

> Oh, sorry you need to change the `texture_renderer` setting in your conf file to software. I believe that takes priority over environment variables.

Unfortunatley, that doesn't work also, with or without forcing the SDL renderer.

**Comment by weirddan455** [comment] 2024-04-11 19:18
>  I suspect the bug is rather triggerd by the fact that the legacy driver is a OpenGL ES2 only GPU/driver, without any OpenGL (classic/core) support. Shouldn't Dosbox Staging be working in such a configuration, rather than outright crash ?

I mean, yeah theoretically it should work.  You've proved it's a regression from 0.80.1 so I'm not trying to argue that it's not a bug.  The trouble is it's a lot of work for one of us to install a very old OS on a real Pi, run through a bisect of compiling at least a dozen commits on a slow device (or set up a cross compile environment which might end up taking even more time as those are often finicky), find the issue, PR the fix, and then confirm we didn't break any other platform in the process.

> I know that it works with an upgraded OS and with the Mesa drivers - I said so in the first post.

That's just your best solution then isn't it?  We're coming close to releasing v0.81.1 already so it's doubtful we can get this in on time (maybe if you wanted to do a bisect yourself it would help) and we're dropping support for Debian 10 after that.

**Comment by johnnovak** [comment] 2024-04-11 21:55
So, the simple answer is that supporting such outdated OSrs and weird driver combos is out of scope. We simply don't have the resources to deal with that.

Furthermore, the texture backend is managed by SDL, so any OpenGL related to the texture renderer is SDL territory. Hugr can of worms.

Like @weirddan455 said, if someone PRs a fix then we'll merge it (if it's a clean fix), but probably an SDL bug. You can try messing around with different SDL versions perhaphs.

**Closed by johnnovak** 2024-04-11 21:55 UTC
Labels: bug, out of scope, SDL, Raspberry Pi

**Comment by cmitu** [comment] 2024-04-12 02:47
Fair enough. 

In order to test my theory about a GLES2 only issue, I compiled (on a recent OS) SDL without OpenGL support, but with OpenGLES2 support (`configure --disable-video-opengl --enable-video-opengles2 ...`). With this SDL library, `dosbox` doesn't crash, though there are a few errors:
  * despite my configuration having `glshader = none`, there's a shader compilation error thrown at some point (MESA's GLSL compiler is quite strict).
  * the colors are wrong, instead of the blue background start-up message, I get a red background, which is kind of expected.

This was tested on a the current RaspiOS and on a Pi4, to try and simulate a driver without OpenGL (core) support. That proves that 'GLES2 only' is not enough to trigger the reported crash, it's also a combination of SDL video driver (RPI) and renderer (GLES2/SW ?) that's at fault.

**Comment by Grounded0** [comment] 2024-04-12 02:54
Changing close signal since left unresolved.

**Comment by johnnovak** [comment] 2024-04-12 03:49
> Fair enough.
> 
> In order to test my theory about a GLES2 only issue, I compiled (on a recent OS) SDL without OpenGL support, but with OpenGLES2 support (`configure --disable-video-opengl --enable-video-opengles2 ...`). With this SDL library, `dosbox` doesn't crash, though there are a few errors:
> 
>     * despite my configuration having `glshader = none`, there's a shader compilation error thrown at some point (MESA's GLSL compiler is quite strict).
> 
>     * the colors are wrong, instead of the blue background start-up message, I get a red background, which is kind of expected.
> 
> 
> This was tested on a the current RaspiOS and on a Pi4, to try and simulate a driver without OpenGL (core) support. That proves that 'GLES2 only' is not enough to trigger the reported crash, it's also a combination of SDL video driver (RPI) and renderer (GLES2/SW ?) that's at fault.

Like I said, we don't wanna go down this rabbit hole...
