### ISSUE TITLE
Gmock unit tests open multiple dosbox windows, then fails due to timeouts

### ISSUE THREAD

**Issue by oturpe** [dosbox-staging/dosbox-staging#1476] opened 2021-12-29 21:23 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.79.0-alpha-12-gff280a88

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora 35

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am a co-maintainer for the Fedora dosbox-staging package.
I am having problems with running the 0.78.0 test suite in the Fedora build environment.
Analyzing the problem I have is difficult,
because I cannot even locally run the tests with success.
I have followed the Fedora instructions in `BUILD.md`
(which, by, the way, seems to be missing instructions for installing `gmock`).

When I run `meson test -C build`,
three dosbox windows are spawned.
Then, after a 30 second wait,
these windows close and the test suite fails
due to timeout in the following tests:
`dos_files`, `drives`, `shell_cmds`.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install dependencies as described in `README.md` and `BUILD.md`
2. `$ meson setup build`
3. `$ meson compile -C build`
4. `$ meson test -C build`

Expected result
Tests complete successfully

Actual result
Three dosbox windows are spawned,
and the test suite hangs in the mentioned tests
until they all reach a 30 second timeout and fail:

### Your configuration

```ini
n/a
```

### Provide a Log

```text
$ meson test -C build
ninja: Entering directory `/home/otto/src/Ohjelmistot/dosbox-staging/build'
[1/6] Generating version.cpp with a custom command
 1/11 gtest example                      EXPECTEDFAIL    0.02s   exit status 1
 2/11 gtest fs_utils                     OK              0.01s
 3/11 gtest iohandler_containers         OK              0.23s
 4/11 gtest setup                        OK              0.02s
 5/11 gtest soft_limiter                 OK              0.29s
 6/11 gtest string_utils                 OK              0.43s
 7/11 gtest rwqueue                      OK              1.30s
 8/11 gtest support                      OK              2.62s
 9/11 gtest drives                       TIMEOUT        30.05s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=89 /home/otto/src/Ohjelmistot/dosbox-staging/build/tests/drives

10/11 gtest dos_files                    TIMEOUT        30.09s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=119 /home/otto/src/Ohjelmistot/dosbox-staging/build/tests/dos_files

11/11 gtest shell_cmds                   TIMEOUT        30.04s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=54 /home/otto/src/Ohjelmistot/dosbox-staging/build/tests/shell_cmds



Ok:                 7   
Expected Fail:      1   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            3
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2021-12-29 22:20
> I have followed the Fedora instructions in BUILD.md, which, by, the way, seems to be missing instructions for installing `gmock`.

Thanks for flagging this @oturpe. Can you share those instructions to install `gmock` on Fedora? dreamer is a Fedora user and previously took care of this area. He's activity on the projected dropped off prior to adding gmock, so unfortunately we have no active maintainers running Fedora.

When we added `gmock` as a dependency, I scanned Repology for it under various names (`gmock-dev`, `gmock-devel`, `libgmock-dev`, `libgmock-devel`, ...), however, there are no valid hits:  https://repology.org/projects/?search=gmock.  Maybe some metadata for Fedora is missing in repology if indeed gmock is a separate package?

**Comment by oturpe** [comment] 2021-12-29 22:34
I made pull request #1477 for this.

It seems Repology is tracking source rpms,
and in Fedora, the `gtest` source rpm creates both `gtest` and `gmock` binary rpms.

For any Fedora related things, I am available.
Just ping me if there is something in the future.

**Comment by kcgen** [comment] 2021-12-29 22:35
gmock finally lets us standup the DOSBox internals and make whitebox calls into the API and test results.

> Three dosbox windows are spawned,

I think this is the problem. On all the systems we're run tests, no windows are actually spawned on typical Linux, macOS, and Windows desktops.  For example, when I run this from my Ubuntu 20.04 system, it runs purely on the console (and I'm not setting `SDL_VIDEODRIVER=` or anything special):

![2021-12-29_14-29](https://user-images.githubusercontent.com/1557255/147708336-d5a6526f-07d6-4551-9331-cc7bdc8cb7b2.png)

**Comment by kcgen** [comment] 2021-12-29 22:37
> Just ping me if there is something in the future.

:+1: 

Thanks.

In the meantime, any help in trying to suppress x11/wayland/GUI access by gmock or SDL would help.  Perhaps the Fedora build of gmock is giving a bit more access versus on Ubuntu/Debian?

**Comment by oturpe** [comment] 2021-12-29 22:53
I suspect that gmock is not the cause here,
because one of the problematic tests is `drives`,
which does not even include gmock.

Anyhow, I will cross compare my failing setup
with the Ubuntu ci that works
and try to find a difference in configuration.

**Comment by voyageur** [comment] 2021-12-30 23:09
Chiming in on the Gentoo packaging side :) We have a similar issue in this [downstream bug](https://bugs.gentoo.org/830237), with the 3 same tests: `dos_files`, `drives`, and `shell_cmds`.

Running in sandbox, the tests fail on SIGABRT - most probably caused by dosbox window trying to start. Running locally, I have similar result of the test spawning a dosbox window, and the test passing when closing the dosbox window.

From a quick look at the source files the new tests look similar to working previous ones, so I guess this is somewhere in how these tests with dosbox_dep are built?

**Comment by brandonrobertz** [comment] 2021-12-31 01:37
Hello thanks for filing this. I'm the author of the new test suite additions. I think `GMock` isn't related directly. The tests that use GMock also use `dosbox_dep` which is basically the entire `libdosbox` library, which is all of DOSbox in library form. It's possible we could fix this somewhere inside meson. I don't really know enough about the video parts of the code to say what we could/should do here, though. I'll try some testing in a no-X/wayland linux environment to replicate. My quick fix to things like this is typically to run xvfb, but that's not a real fix, of course.

**Comment by kcgen** [comment] 2021-12-31 01:42
Yes, using the `dummy` or `null` video driver suppresses display output.  Can set the `SDL_VIDEODRIVER=` variable to either of those. Or pass it in code during SDL initialization: <https://wiki.libsdl.org/SDL_VideoInit>

**Comment by brandonrobertz** [comment] 2021-12-31 07:04
> Yes, using SDL2's `dummy` or `null` video drivers will suppress display output. Can set the `SDL_VIDEODRIVER=` environment variable prior to launch or pass the driver name as a char* during SDL initialization: https://wiki.libsdl.org/SDL_VideoInit

Maybe we can set that as the default inside our text fixture?

**Comment by kcgen** [comment] 2021-12-31 07:46
Will try!

**Comment by brandonrobertz** [comment] 2021-12-31 20:19
Just an update: I've replicated this issue on Fedora 35 Server and Ubuntu Server 20.04.

**Comment by oturpe** [comment] 2022-01-01 08:07
On my machine, doing `SDL_VIDEODRIVER=null` does not work, the following error appears:

```
2022-01-01 10:04:44.851 | ABORT: Can't init SDL null not available
```

The same with `SDL_VIDEODRIVER=dummy` does not spawn any visible windows,
but otherwise it is the same as before,
the problem tests stall, then fail due to a timeout.

I also suspect that any fix cannot be done (solely) in `DOSBoxTestFixture`,
because the `drives` does not use that.

**Comment by kcgen** [comment] 2022-01-01 17:00
This was pretty subtle! we had two `main()`'s in play. Usually gmock's takes precedent (as evident by all the CI runs that pass without MALLOC_PERTURB or 30-second timeout errors), but with some compiler+linker combos, this seems to get flipped so gmock actually executes the program itself. 

To see this in action (don't pull the latest commit just yet):

1. install clang and gcc-7 and g++7
2. `meson setup --native-file=.github/meson/native-clang.ini build/clang`
3. `meson compile -C build/clang && meson test -C build/clang`
4. `meson setup --native-file=.github/meson/native-gcc-7.ini build/gcc7`
5. `meson compile -C build/gcc7 && meson test -C build/gcc7 `

The clang run should run clean where as the gcc-7 run scenario should produce popups.

Now `git pull` on your `main` branch and run steps 3 and 5 again.

**Closed** 2022-01-01 17:03 UTC
Labels: bug, tests

**Comment by oturpe** [comment] 2022-01-01 19:50
Thank you for the fix!
It works for Fedora,
I can now build the Dosbox 0.78.0 package and run all the tests.

**Comment by kcgen** [comment] 2022-01-01 20:03
Thanks for the confirmation, @oturpe - glad all's well again in Fedora-land.

**Comment by kcgen** [comment] 2022-01-01 20:05
@brandonrobertz: thank you for jumping in on quick notice and doing a detailed investigation. :rocket:  
Sharing your results directly lead to this fix.
