### ISSUE TITLE
Wide colour gamut issue on Windows 11

### ISSUE THREAD

**Issue by shermp** [dosbox-staging/dosbox-staging#2870] opened 2023-09-15 10:13 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-alpha-1676-gfed6c628d

### What Operating System are you using?

Windows 11

### Relevant hardware info

HDR OLED Laptop screen, AMD Ryzen 7 5800H with Integrated GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using Dosbox Staging on Windows 11 with an HDR capable monitor, with Windows HDR mode **enabled**, Dosbox in full screen mode has over saturated colours. 

Colours are fine in windowed mode.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. When using a HDR capable display, Go to Windows Display settings, and enable the **Use HDR** toggle.
2. Run Dosbox staging with a game. I used Epic Pinball in my example.
3. In Windowed mode, observe correct colours.
4. Switch to full screen with Ctrl-Enter. Observe over saturated colours.
5. Switch back to windowed mode, note the colours are again correct.

### Your configuration

```ini
[dosbox]
memsize  = 63
vmemsize = 8

[cpu]
cycles = 100000

[autoexec]
mount c .
imgmount d cd/Timeshock!.cue -t cdrom
c:
cd TSHOCK
shock
exit
```

### Provide a Log

```text
2023-09-15 22:12:34.035 | arguments: C:\\msys64\\home\\sherm\\dosbox-bin-clang64\\dosbox.exe
2023-09-15 22:12:34.035 | Current dir: C:\DOSBox Programs\EpicPC95
2023-09-15 22:12:34.035 | stderr verbosity: 0
2023-09-15 22:12:34.036 | -----------------------------------
2023-09-15 22:12:34.036 | dosbox-staging version 0.81.0-alpha-1676-gfed6c628d
2023-09-15 22:12:34.036 | ---
2023-09-15 22:12:34.036 | LOG: Loguru version 2.1.0 initialised
2023-09-15 22:12:34.048 | SDL: version 2.28.2 initialised (windows video and wasapi audio)
2023-09-15 22:12:34.049 | CONFIG: Loaded local config file 'dosbox.conf'
2023-09-15 22:12:34.049 | LANG: Using internal English language messages
2023-09-15 22:12:34.049 | DISPLAY: Initialised 888x666 windowed mode using bilinear scaling on display-0
2023-09-15 22:12:34.223 | OPENGL: Vendor: ATI Technologies Inc.
2023-09-15 22:12:34.223 | OPENGL: Version: 4.6.0 Compatibility Profile Context 22.11.2.221130
2023-09-15 22:12:34.223 | OPENGL: GLSL version: 4.60
2023-09-15 22:12:34.223 | OPENGL: Pixel buffer object available
2023-09-15 22:12:34.223 | OPENGL: NPOT textures supported
2023-09-15 22:12:34.224 | VIDEO: Using the DOS video mode's frame rate
2023-09-15 22:12:34.235 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0000020CD0730040
2023-09-15 22:12:34.235 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2023-09-15 22:12:34.246 | RENDER: Auto-switched to shader 'crt/hercules'
2023-09-15 22:12:34.246 | VGA: Double-scanning VGA video modes enabled
2023-09-15 22:12:34.247 | VGA: Pixel-doubling enabled
2023-09-15 22:12:34.247 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2023-09-15 22:12:34.254 | CAPTURE: Image capturer started
2023-09-15 22:12:34.698 | MIXER: Negotiated 2-channel 48000 Hz audio in 1024-frame blocks
2023-09-15 22:12:34.698 | MIXER: Master compressor enabled
2023-09-15 22:12:34.878 | MIDI: Opened device: win32
2023-09-15 22:12:34.879 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-09-15 22:12:34.880 | OPL: Operating at 48000 Hz without resampling
2023-09-15 22:12:34.880 | OPL: Running OPL3 on ports 220h and 388h
2023-09-15 22:12:34.880 | SB16: Sound Blaster 16 OPL output filter enabled
2023-09-15 22:12:34.880 | DMA: Initialised primary controller
2023-09-15 22:12:34.880 | DMA: Initialised secondary controller
2023-09-15 22:12:34.880 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-09-15 22:12:34.880 | SB16: Modern DAC output filter enabled
2023-09-15 22:12:34.880 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2023-09-15 22:12:34.880 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2023-09-15 22:12:34.881 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-09-15 22:12:34.881 | PCSPEAKER: Initialised discrete model
2023-09-15 22:12:34.881 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-09-15 22:12:34.881 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-09-15 22:12:34.881 | MOUSE: Will be captured after the first left or right button click
2023-09-15 22:12:34.881 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-09-15 22:12:34.881 | MOUSE (PS/2): Standard, 3 buttons
2023-09-15 22:12:34.890 | SLIRP: Slirp version: 4.7.0
2023-09-15 22:12:34.891 | SLIRP: Successfully initialized
2023-09-15 22:12:34.891 | NE2000: Initialised on port 300h and IRQ 3
2023-09-15 22:12:34.893 | CONFIG: Loaded auto-mounted drive config file 'C:\msys64\home\sherm\dosbox-bin-clang64\resources\drives\y.conf'
2023-09-15 22:12:34.894 | AUTOEXEC: Using autoexec from one or more joined sections
2023-09-15 22:12:34.919 | MAPPER: No joysticks found
2023-09-15 22:12:34.919 | MAPPER: Loaded default key bindings
2023-09-15 22:12:34.920 | SHELL: Redirecting output to NUL
2023-09-15 22:12:34.921 | MOUNT: Path 'C:\msys64\home\sherm\dosbox-bin-clang64\resources\drives\y' found
2023-09-15 22:12:34.923 | MOUNT: Path '.' found
2023-09-15 22:12:34.927 | IMGMOUNT: Path './cd/EPIC_PINBALL.iso' found
2023-09-15 22:12:34.928 | CDAUDIO: Operating at 48000 Hz without resampling
2023-09-15 22:12:34.945 | RENDER: Auto-switched to shader 'crt/vga-1440p'
2023-09-15 22:12:34.945 | SDL: Using standard SDI (auto) display refresh rate of 90 Hz
2023-09-15 22:12:34.979 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 1600x1200 with 1:1.35 (20:27) pixel aspect ratio
2023-09-15 22:12:38.236 | CHOICE: '1' (#1 of 3 choices)
2023-09-15 22:12:38.237 | MPU-401: Shutting down
2023-09-15 22:12:38.347 | CONFIG: 'default' is an invalid value for 'mididevice', using the default: 'auto'
2023-09-15 22:12:38.460 | MIDI: Opened device: win32
2023-09-15 22:12:38.462 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-09-15 22:12:38.480 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz VFR, scaled to 1600x1200 with 1:1.2 (5:6) pixel aspect ratio
2023-09-15 22:12:38.486 | SB16: DSP was reset
2023-09-15 22:12:38.486 | SB16: Speaker-output has been toggled on
2023-09-15 22:12:38.487 | SB16: DSP was reset
2023-09-15 22:12:38.487 | SB16: Speaker-output has been toggled on
2023-09-15 22:13:15.564 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
2023-09-15 22:13:15.588 | RENDER: Auto-switched to shader 'crt/vga-4k'
2023-09-15 22:13:18.394 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz VFR, scaled to 1600x1200 with 1:1.2 (5:6) pixel aspect ratio
2023-09-15 22:13:18.407 | RENDER: Auto-switched to shader 'crt/vga-1440p'
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment] 2023-09-15 10:15
As an addendum, the use of the HDR toggle is for Windows to provide SRGB clamping, as my laptop monitor does not provide  SRGB clamping.

**Comment by shermp** [comment] 2023-09-15 10:30
Actually, this is basically a continuation of [#1793](https://github.com/dosbox-staging/dosbox-staging/issues/1793)

**Comment by GranMinigun** [comment] 2023-09-15 11:16
DWM (Windows' compositor) is responsible for tonemapping the image. Fullscreen mode is exclusive, bypassing composition step. A workaround would be to run in borderless fullscreen window, and a proper (but currently somewhat difficult to pull off) solution is to cooperate with DWM via DXGI presentation.

As a side note, nVidia has a toggle to present OpenGL and Vulkan surfaces via DXGI in its GPU control panel, which might help. No idea whether Intel and AMD plan to add such option.

Closing as a duplicate of #1793.

**Closed by GranMinigun** 2023-09-15 11:16 UTC
Labels: bug, video
