### ISSUE TITLE
error: constexpr declaration of 'strnlen' follows non-constexpr declaration

### ISSUE THREAD

**Issue by AA1999** [dosbox-staging/dosbox-staging#2600] opened 2023-06-14 08:40 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main branch

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Archlinux 6.3.7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I followed the guide [here](https://github.com/dosbox-staging/dosbox-staging/blob/main/BUILD.md#built-in-debugger-build) to build it using a debugger (heavy) and when I ran the compile command I see:

```cpp
meson compile -C build/debugger
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/arshia/dosbox-staging/build/debugger
ninja: Entering directory `/home/arshia/dosbox-staging/build/debugger'
[41/361] Compiling C++ object src/libs/decoders/libdecoders.a.p/opus.cpp.o
FAILED: src/libs/decoders/libdecoders.a.p/opus.cpp.o 
clang++ -Isrc/libs/decoders/libdecoders.a.p -Isrc/libs/decoders -I../../src/libs/decoders -I../../include -I. -I../.. -Isrc/libs/ghc -I../../src/libs/ghc -Isrc/libs/loguru -I../../src/libs/loguru -I/usr/include/SDL2 -I/usr/include/opus -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -O3 -Wno-unknown-pragmas -fpch-preprocess -Weffc++ -Wextra-semi -fstrict-aliasing -Wstrict-aliasing -fmerge-all-constants -fno-math-errno -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -ffinite-math-only -ffunction-sections -fdata-sections -fPIC -O3 -pipe -std=c++20 -D_REENTRANT -MD -MQ src/libs/decoders/libdecoders.a.p/opus.cpp.o -MF src/libs/decoders/libdecoders.a.p/opus.cpp.o.d -o src/libs/decoders/libdecoders.a.p/opus.cpp.o -c ../../src/libs/decoders/opus.cpp
In file included from ../../src/libs/decoders/opus.cpp:46:
In file included from ../../include/math_utils.h:27:
In file included from ../../include/support.h:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/thread:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/stop_token:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/semaphore:37:
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/semaphore_base.h:180:5: error: unknown type name 'sem_t'
    sem_t _M_semaphore;
    ^
In file included from ../../src/libs/decoders/opus.cpp:46:
In file included from ../../include/math_utils.h:27:
../../include/support.h:170:18: error: constexpr declaration of 'strnlen' follows non-constexpr declaration
constexpr size_t strnlen(const char* str, const size_t max_len)
                 ^
/usr/include/string.h:413:15: note: previous declaration is here
extern size_t strnlen (const char *__string, size_t __maxlen)
              ^
In file included from ../../src/libs/decoders/opus.cpp:46:
In file included from ../../include/math_utils.h:27:
../../include/support.h:172:7: warning: nonnull parameter 'str' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
        if (!str) {
            ~^~~
/usr/include/string.h:414:33: note: declared 'nonnull' here
     __THROW __attribute_pure__ __nonnull ((1));
                                ^
/usr/include/sys/cdefs.h:392:28: note: expanded from macro '__nonnull'
# define __nonnull(params) __attribute_nonnull__ (params)
                           ^
/usr/include/sys/cdefs.h:386:57: note: expanded from macro '__attribute_nonnull__'
#  define __attribute_nonnull__(params) __attribute__ ((__nonnull__ params))
                                                        ^
1 warning and 2 errors generated.
[43/361] Compiling C++ object src/libs/decoders/libdecoders.a.p/mp3.cpp.o
FAILED: src/libs/decoders/libdecoders.a.p/mp3.cpp.o 
clang++ -Isrc/libs/decoders/libdecoders.a.p -Isrc/libs/decoders -I../../src/libs/decoders -I../../include -I. -I../.. -Isrc/libs/ghc -I../../src/libs/ghc -Isrc/libs/loguru -I../../src/libs/loguru -I/usr/include/SDL2 -I/usr/include/opus -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -O3 -Wno-unknown-pragmas -fpch-preprocess -Weffc++ -Wextra-semi -fstrict-aliasing -Wstrict-aliasing -fmerge-all-constants -fno-math-errno -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -ffinite-math-only -ffunction-sections -fdata-sections -fPIC -O3 -pipe -std=c++20 -D_REENTRANT -MD -MQ src/libs/decoders/libdecoders.a.p/mp3.cpp.o -MF src/libs/decoders/libdecoders.a.p/mp3.cpp.o.d -o src/libs/decoders/libdecoders.a.p/mp3.cpp.o -c ../../src/libs/decoders/mp3.cpp
In file included from ../../src/libs/decoders/mp3.cpp:33:
In file included from ../../include/math_utils.h:27:
In file included from ../../include/support.h:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/thread:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/stop_token:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/semaphore:37:
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/semaphore_base.h:180:5: error: unknown type name 'sem_t'
    sem_t _M_semaphore;
    ^
In file included from ../../src/libs/decoders/mp3.cpp:33:
In file included from ../../include/math_utils.h:27:
../../include/support.h:170:18: error: constexpr declaration of 'strnlen' follows non-constexpr declaration
constexpr size_t strnlen(const char* str, const size_t max_len)
                 ^
/usr/include/string.h:413:15: note: previous declaration is here
extern size_t strnlen (const char *__string, size_t __maxlen)
              ^
In file included from ../../src/libs/decoders/mp3.cpp:33:
In file included from ../../include/math_utils.h:27:
../../include/support.h:172:7: warning: nonnull parameter 'str' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
        if (!str) {
            ~^~~
/usr/include/string.h:414:33: note: declared 'nonnull' here
     __THROW __attribute_pure__ __nonnull ((1));
                                ^
/usr/include/sys/cdefs.h:392:28: note: expanded from macro '__nonnull'
# define __nonnull(params) __attribute_nonnull__ (params)
                           ^
/usr/include/sys/cdefs.h:386:57: note: expanded from macro '__attribute_nonnull__'
#  define __attribute_nonnull__(params) __attribute__ ((__nonnull__ params))
                                                        ^
1 warning and 2 errors generated.
[44/361] Compiling C++ object src/libs/decoders/libdecoders.a.p/mp3_seek_table.cpp.o
FAILED: src/libs/decoders/libdecoders.a.p/mp3_seek_table.cpp.o 
clang++ -Isrc/libs/decoders/libdecoders.a.p -Isrc/libs/decoders -I../../src/libs/decoders -I../../include -I. -I../.. -Isrc/libs/ghc -I../../src/libs/ghc -Isrc/libs/loguru -I../../src/libs/loguru -I/usr/include/SDL2 -I/usr/include/opus -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -O3 -Wno-unknown-pragmas -fpch-preprocess -Weffc++ -Wextra-semi -fstrict-aliasing -Wstrict-aliasing -fmerge-all-constants -fno-math-errno -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -ffinite-math-only -ffunction-sections -fdata-sections -fPIC -O3 -pipe -std=c++20 -D_REENTRANT -MD -MQ src/libs/decoders/libdecoders.a.p/mp3_seek_table.cpp.o -MF src/libs/decoders/libdecoders.a.p/mp3_seek_table.cpp.o.d -o src/libs/decoders/libdecoders.a.p/mp3_seek_table.cpp.o -c ../../src/libs/decoders/mp3_seek_table.cpp
In file included from ../../src/libs/decoders/mp3_seek_table.cpp:86:
In file included from ../../include/math_utils.h:27:
In file included from ../../include/support.h:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/thread:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/stop_token:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/semaphore:37:
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/semaphore_base.h:180:5: error: unknown type name 'sem_t'
    sem_t _M_semaphore;
    ^
In file included from ../../src/libs/decoders/mp3_seek_table.cpp:86:
In file included from ../../include/math_utils.h:27:
../../include/support.h:170:18: error: constexpr declaration of 'strnlen' follows non-constexpr declaration
constexpr size_t strnlen(const char* str, const size_t max_len)
                 ^
/usr/include/string.h:413:15: note: previous declaration is here
extern size_t strnlen (const char *__string, size_t __maxlen)
              ^
In file included from ../../src/libs/decoders/mp3_seek_table.cpp:86:
In file included from ../../include/math_utils.h:27:
../../include/support.h:172:7: warning: nonnull parameter 'str' will evaluate to 'true' on first encounter [-Wpointer-bool-conversion]
        if (!str) {
            ~^~~
/usr/include/string.h:414:33: note: declared 'nonnull' here
     __THROW __attribute_pure__ __nonnull ((1));
                                ^
/usr/include/sys/cdefs.h:392:28: note: expanded from macro '__nonnull'
# define __nonnull(params) __attribute_nonnull__ (params)
                           ^
/usr/include/sys/cdefs.h:386:57: note: expanded from macro '__attribute_nonnull__'
#  define __attribute_nonnull__(params) __attribute__ ((__nonnull__ params))
                                                        ^
1 warning and 2 errors generated.
[49/361] Compiling C object src/libs/decoders/libdecoders.a.p/flac.c.o
In file included from ../../src/libs/decoders/flac.c:42:
../../src/libs/decoders/dr_flac.h:1928:36: warning: unused function 'drflac__le2host_32' [-Wunused-function]
static DRFLAC_INLINE drflac_uint32 drflac__le2host_32(drflac_uint32 n)
                                   ^
1 warning generated.
[50/361] Compiling C++ object src/libs/loguru/libloguru.a.p/loguru.cpp.o
ninja: build stopped: subcommand failed. 
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. `git clone https://github.com/dosbox-staging/dosbox-staging`
2. `git checkout main -f`
3. `git pull` (failsafe, not really needed)
4. `cd dosbox-staging`
5. `meson setup -Denable_debugger=heavy build/debugger`
6. `meson compile -C build/debugger`

### Provide a Log

```cpp
meson setup -Denable_debugger=heavy build/debugger 
The Meson build system
Version: 1.1.1
Source dir: /home/arshia/dosbox-staging
Build dir: /home/arshia/dosbox-staging/build/debugger
Build type: native build
Project name: dosbox-staging
Project version: 0.81.0-alpha
C compiler for the host machine: clang (clang 17.0.0 "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)")
C linker for the host machine: clang ld.bfd 2.40.0
C++ compiler for the host machine: clang++ (clang 17.0.0 "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)")
C++ linker for the host machine: clang++ ld.bfd 2.40.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring drives with command
Configuring y.conf with command
Configuring y with command
Configuring freedos-cpi with command
Configuring EGA.CPX with command
Configuring EGA2.CPX with command
Configuring EGA3.CPX with command
Configuring EGA4.CPX with command
Configuring EGA5.CPX with command
Configuring EGA6.CPX with command
Configuring EGA7.CPX with command
Configuring EGA8.CPX with command
Configuring EGA9.CPX with command
Configuring EGA10.CPX with command
Configuring EGA11.CPX with command
Configuring EGA12.CPX with command
Configuring EGA13.CPX with command
Configuring EGA14.CPX with command
Configuring EGA15.CPX with command
Configuring EGA16.CPX with command
Configuring EGA17.CPX with command
Configuring EGA18.CPI with command
Configuring freedos-keyboard with command
Configuring KEYBOARD.SYS with command
Configuring KEYBRD2.SYS with command
Configuring KEYBRD3.SYS with command
Configuring KEYBRD4.SYS with command
Configuring glshaders with command
Configuring none.glsl with command
Configuring crt with command
Configuring interpolation with command
Configuring misc with command
Configuring scaler with command
Configuring mapping with command
Configuring ASCII.TXT with command
Configuring CAPITAL_SMALL.TXT with command
Configuring DECOMPOSITION.TXT with command
Configuring MAIN.TXT with command
Configuring mapping-freedos.org with command
Configuring CP_30000.TXT with command
Configuring CP_30006.TXT with command
Configuring CP_30034.TXT with command
Configuring mapping-unicode.org with command
Configuring CP_437.TXT with command
Configuring CP_737.TXT with command
Configuring CP_775.TXT with command
Configuring CP_850.TXT with command
Configuring CP_852.TXT with command
Configuring CP_855.TXT with command
Configuring CP_856.TXT with command
Configuring CP_857.TXT with command
Configuring CP_860.TXT with command
Configuring CP_861.TXT with command
Configuring CP_862.TXT with command
Configuring CP_863.TXT with command
Configuring CP_864.TXT with command
Configuring CP_865.TXT with command
Configuring CP_866.TXT with command
Configuring CP_869.TXT with command
Configuring CP_874.TXT with command
Configuring CP_1250.TXT with command
Configuring CP_1251.TXT with command
Configuring CP_1252.TXT with command
Configuring CP_1253.TXT with command
Configuring CP_1254.TXT with command
Configuring CP_1255.TXT with command
Configuring CP_1256.TXT with command
Configuring CP_1257.TXT with command
Configuring CP_1258.TXT with command
Configuring license.txt with command
Configuring mapping-wikipedia.org with command
Configuring CP_708.TXT with command
Configuring CP_720.TXT with command
Configuring CP_773.TXT with command
Configuring CP_776.TXT with command
Configuring CP_777.TXT with command
Configuring CP_778.TXT with command
Configuring CP_851.TXT with command
Configuring CP_853.TXT with command
Configuring CP_899.TXT with command
Configuring CP_1117.TXT with command
Configuring CP_1169.TXT with command
Configuring CP_1270.TXT with command
Configuring CP_3021.TXT with command
Configuring CP_3848.TXT with command
Configuring translations with command
Configuring de.lng with command
Configuring en.lng with command
Configuring es.lng with command
Configuring fr.lng with command
Configuring it.lng with command
Configuring nl.lng with command
Configuring pl.lng with command
Configuring ru.lng with command
Configuring mapperfiles with command
Configuring xbox with command
Has header "filesystem" : YES 
Compiler for C supports arguments -Wno-unknown-pragmas: YES 
Compiler for C++ supports arguments -Wno-unknown-pragmas: YES 
Compiler for C supports arguments -fpch-preprocess: YES 
Compiler for C++ supports arguments -fpch-preprocess: YES 
Compiler for C supports arguments -Wmaybe-uninitialized: NO 
Compiler for C++ supports arguments -Wmaybe-uninitialized: NO 
Compiler for C supports arguments -Weffc++: YES 
Compiler for C++ supports arguments -Weffc++: YES 
Compiler for C supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C supports arguments -fstrict-aliasing: YES 
Compiler for C++ supports arguments -fstrict-aliasing: YES 
Compiler for C supports arguments -Wstrict-aliasing: YES 
Compiler for C++ supports arguments -Wstrict-aliasing: YES 
Compiler for C supports arguments -fmerge-all-constants: YES 
Compiler for C++ supports arguments -fmerge-all-constants: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C++ supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-signed-zeros: YES 
Compiler for C++ supports arguments -fno-signed-zeros: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C++ supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -fassociative-math: YES 
Compiler for C++ supports arguments -fassociative-math: YES 
Compiler for C supports arguments -freciprocal-math: YES 
Compiler for C++ supports arguments -freciprocal-math: YES 
Compiler for C supports arguments -ffinite-math-only: YES 
Compiler for C++ supports arguments -ffinite-math-only: YES 
Compiler for C supports arguments -frename-registers: NO 
Compiler for C++ supports arguments -frename-registers: NO 
Compiler for C supports arguments -ffunction-sections: YES 
Compiler for C++ supports arguments -ffunction-sections: YES 
Compiler for C supports arguments -fdata-sections: YES 
Compiler for C++ supports arguments -fdata-sections: YES 
Compiler for C supports arguments -shared-libstdc++: NO 
Compiler for C++ supports arguments -shared-libstdc++: NO 
Compiler for C supports arguments -shared-libgcc: NO 
Compiler for C++ supports arguments -shared-libgcc: NO 
Compiler for C supports arguments -lstdc++_s: NO 
Compiler for C++ supports arguments -lstdc++_s: NO 
Compiler for C supports arguments -fPIC: YES 
Compiler for C++ supports arguments -fPIC: YES 
Compiler for C++ supports link arguments -Wl,-map,dosbox.map: NO 
Compiler for C++ supports link arguments -Wl,-Map,dosbox.map: YES 
Compiler for C++ supports link arguments -Wl,--Map,dosbox.map: YES 
Compiler for C++ supports link arguments -Wl,--gc-sections: YES 
Checking for function "clock_gettime" : NO 
Checking for function "__builtin_available" : YES 
Checking for function "__builtin___clear_cache" : YES 
Checking for function "mprotect" : YES 
Checking for function "mmap" : YES 
Header "sys/mman.h" has symbol "MAP_JIT" : NO 
Checking for function "pthread_jit_write_protect_np" : NO 
Checking for function "sys_icache_invalidate" : NO 
Run-time dependency threads found: YES
Checking for function "pthread_setname_np" with dependency threads: YES 
Checking for function "realpath" : NO 
Checking for function "strnlen" : NO 
Checking whether type "struct dirent" has member "d_type" : YES 
Has header "pwd.h" : YES 
Has header "strings.h" : YES 
Has header "netinet/in.h" : YES 
Has header "sys/socket.h" : YES 
Checking for function "getpeername" : YES 
Checking for function "getsockname" : YES 
Checking if "test for setpriority support" compiles: YES 
Checking if "test for __builtin_expect support" compiles: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Found CMake: /usr/bin/cmake (3.26.4)
Run-time dependency atomic found: NO (tried pkgconfig and cmake)
Checking if "compiler supports atomic types using external library" with dependency atomic: links: YES 
Library dl found: YES
Library stdc++fs found: YES
Dependency threads found: YES unknown (cached)
Run-time dependency iir found: YES 1.9.4
Run-time dependency opusfile found: YES 0.12
Run-time dependency sdl2 found: YES 2.26.5
Run-time dependency zlib found: YES 1.2.13
Run-time dependency speexdsp found: YES 1.2.1
Checking if "SpeexDSP system library has reliable floating-point API" with dependency speexdsp runs: YES
Header "sys/select.h" has symbol "FD_ZERO" : YES 
Run-time dependency sdl2_net found: YES 2.2.0
Run-time dependency slirp found: YES 4.7.0
Run-time dependency sdl2_image found: YES 2.6.3
Run-time dependency gl found: YES 1.2
Run-time dependency fluidsynth found: YES 2.3.2
Run-time dependency mt32emu found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency mt32emu

Executing subproject mt32emu 

mt32emu| Project name: mt32emu
mt32emu| Project version: 2.7.0
mt32emu| C++ compiler for the host machine: clang++ (clang 17.0.0 "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)")
mt32emu| C++ linker for the host machine: clang++ ld.bfd 2.40.0
mt32emu| Configuring config.h using configuration
mt32emu| Build targets in project: 1
mt32emu| NOTICE: Future-deprecated features used:
mt32emu| * 0.64.0: {'copy arg in configure_file'}
mt32emu| Subproject mt32emu finished.

Dependency mt32emu from subproject subprojects/munt-libmt32emu_2_7_0 found: YES 2.7.0
Run-time dependency libpng found: YES 1.6.39
Run-time dependency xi found: YES 1.8.1
Run-time dependency alsa found: YES 1.2.9
Configuring config.h using configuration
Found git repository at /home/arshia/dosbox-staging
Build targets in project: 27

dosbox-staging 0.81.0-alpha

  Build Summary
    Build type           : release
    Install prefix       : /usr/local

    SpeexDSP provider    : system library
    SDL_net 2.0 support  : True
    slirp support        : True
    SDL_image 2.0 support: True
    FluidSynth support   : True
    mt32emu support      : True
    PNG support          : True
    ManyMouse support    : Enabled
    ALSA support         : True
    Byte order           : little-endian
    Per-page W^X         : True
    CPU dynamic core     : optimized for x86/x86_64 (dyn-x86)
    CPU core target arch : X86_64

  Subprojects
    mt32emu              : YES 1 warnings

  User defined options
    enable_debugger      : heavy

Found ninja-1.11.1 at /usr/bin/ninja  
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-09-01 22:25
Take a look at how the CI loop builds it @AA1999. Ultimately, this issue tracker is not dev tech support, so closing this. Please join our dev chat on our Discord to discuss this.

**Closed by johnnovak** 2023-09-01 22:25 UTC
Labels: bug

**Comment by kcgen** [comment] 2023-09-21 14:27
@AA1999,

Thanks for the full log output.

It looks like you're compiling with Clang-17.0.0 (snipped from your log):

```text
C compiler for the host machine: clang (clang 17.0.0 "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)")
C linker for the host machine: clang ld.bfd 2.40.0
C++ compiler for the host machine: clang++ (clang 17.0.0 "clang version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)")
C++ linker for the host machine: clang++ ld.bfd 2.40.0
```

However, it's using GCC 13.1.1's header files and standard template library (also from your log):

```text
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/stop_token:39:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/semaphore:37:
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/semaphore_base.h:180:5: error: unknown type name 'sem_t'
    sem_t _M_semaphore;
    ^
```

The first error encountered is:

```
/usr/lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../
include/c++/13.1.1/bits/semaphore_base.h:180:5:
 error: unknown type name 'sem_t'
```

Because the error is coming from your system's own STL header files, this points to something broken in your overall build environment.

I did try to reproduce it:

- _Uninstalled_ GCC 12.x
- Installed gcc-13 exclusively, to get its header files.
- Installed latest clang:
    `clang 18.0.0 "Ubuntu clang version 18.0.0~20230915053829.322)"`

Used your reproduction steps, specifically adjusted to ensure it builds with clang instead of gcc:

1. meson setup --native-file=.github/meson/native-clang.ini -Denable_debugger=heavy build/debugger 

```text
[06:56:00@server dosbox-staging] (main $) meson setup --native-file=.github/meson/native-clang.ini -Denable_debugger=heavy build/debugger 
The Meson build system
Version: 1.2.1
Source dir: /usr/src/dosbox-staging
Build dir: /usr/src/dosbox-staging/build/debugger
Build type: native build
Project name: dosbox-staging
Project version: 0.81.0-alpha
C compiler for the host machine: ccache clang (clang 18.0.0 "Ubuntu clang version 18.0.0 (++20230915053706+715fc4fc6065-1~exp1~20230915053829.322)")
C linker for the host machine: clang ld.bfd 2.40
C++ compiler for the host machine: ccache clang++ (clang 18.0.0 "Ubuntu clang version 18.0.0 (++20230915053706+715fc4fc6065-1~exp1~20230915053829.322)")
C++ linker for the host machine: clang++ ld.bfd 2.40
```

2. meson compile -C build/debugger

3. Result? It buils clean without a single warning.

Try to purge all your headers tree(s) and compilers (all gcc versions, all clang versions), plus any headers or compilers you might have installed manually. Then re-install the latest GCC and Clang compilers from a fresh start.

Then try a GCC-specific build:

1. meson setup --native-file=.github/meson/native-gcc.ini -Denable_debugger=heavy build/debugger-gcc
2. meson compile -C build/debugger-gcc

And a Clang-specific build:

1. meson setup --native-file=.github/meson/native-clang.ini -Denable_debugger=heavy build/debugger-clang

2. meson compile -C build/debugger-clang


Leave this ticket closed and `not-a-bug` because the log results point to the issues being a mangled build environment.
