### ISSUE TITLE
Include a Text Editor?

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#392] opened 2020-05-22 21:35 UTC
Since the subject of "less" (https://github.com/dosbox-staging/dosbox-staging/issues/391) was brought up recently, how about text editors?

Some prominent examples' official repositories:

https://www.nano-editor.org/git.php

https://github.com/vim/vim

I am not saying to include either one or both.  If there are other simpler text editors that would accomplish that for DOS, then go with whatever those are.

**Comment by dreamer** [comment] 2020-05-22 21:54
Lack of text editor is a bummer, yes. Personally, I am working around it by adding Norton Commander in my path (and using F3 to view / F4 to edit), but well - new users won't know how to do it. I was thinking about bundling Midnight Commander to get a similar functionality OOTB but need to investigate further if it's feasible.

Vim does not support DOS any more (for a long time), but archival versions do - I tested it some time ago, and the last version with DOS support does not work so well (it was stretching DOS capabilities to the limit already); it's also quite weird to use so ancient version, lacking many features.

*Perhaps instead of built-in text editor it would be better to create a feature, that allows users to easily obtain/preserve various helpful tools. E.g. `utils` directory in DOSBox config dir, that would be automatically added to PATH... or maybe even something better ;)*

**Comment by ritalat** [comment] 2020-05-23 13:39
I think FreeDOS includes a GPL clone of Edit. Perhaps that could be used?

**Comment by MasterO2** [comment] 2020-05-23 14:06
> 
> 
> I think FreeDOS includes a GPL clone of Edit. Perhaps that could be used?

https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/edit/

Although edit is **not** listed below, here are more text editors from freedos:

https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/group-edit.html

Note: They appear to be source code, not executables, though.

**Comment by ritalat** [comment] 2020-05-23 14:17
> Although edit is **not** listed below, here are more text editors from freedos:
Hmmm seems like Edit is part of the base package group of FreeDOS. It can be found here:
https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/edit.html

**Comment by dreamer** [comment] 2020-05-23 14:24
Maybe I'll rephrase my answer a little bit :)

There's a significant difference between programs and utilities, that are built-in dosbox (like `dir`, `ls`, or `autotype`) and programs/utils that can be emulated in dosbox.

- built-ins - they are written in C/C++ and compiled as internal emulator functions - this makes it easier to develop, maintain, and distribute.
- programs like `edit` or `vim` - those are open source programs, that can be *compiled* for DOS and emulated in dosbox, but we can't simply drop them in dosbox code to include out of the box. We would need to set up specific build process including cross-compilation from Linux, Windows, macOS to DOS (which is *hard*).

We could "cheat" by compiling those programs once and then bundling them with dosbox-staging as binary blobs (it would be ok with GPL as long as we would provide GPL-compatible source code for those utilities we precompile)… but there are consequences to it: namely, our code wouldn't be easy to audit any more, which makes it less likely for distributions to pick us up. It also makes it harder for *us* to verify and fix the software.

We'll need to square this circle somehow - the first step towards doing so will be done when we'll get around to fixing #256 (DOS32/A is written in assembler, but the core of the issue is the same).

I am going to include some more baseline utilities/shell improvements OOTB, but "bigger" things (like text editors) will need a better approach, closer in scope to DOS32/A.

**Comment by Akuma-Git** [comment] 2020-09-05 13:49
This could be hung under: https://github.com/dosbox-staging/dosbox-staging/issues/601

**Comment by kcgen** [comment] 2020-09-05 14:19
> We'll need to square this circle somehow

Distributing dosbox-staging alone versus dosbox-staging with a suite of DOS tools is similar to the distinction between the Linux kernel versus distribution.

Once we open this can of gummy bears, there are going to good arguments to include all manner of DOS utilities, applications, developer tools, and so on.

Drawing the line will be difficult and arbitrary. I will be the first to admit that having an organized directory tree of best-in-class programs covering the full spectrum of uses (all in, say 200 MB) would be wonderful.

The work needed to do this right and get from start to finish could be years of effort - including ongoing updates with latest stable builds of actively maintained tools.  

It's a burden that would dilute our focus on dosbox-staging if we were also fielding bug reports, new requests, writing release notes, and so on.

So I would prefer spinning this out into "sibling project" with new folks taking up that effort.

**Comment by dreamer** [comment] 2020-09-05 14:40
I agree with @kcgen - not only we would need to take care of distributing those tools, but also keep a tab on updating them, have various build systems (prepare them in the first place), take care of licenses, testing, etc, etc. I don't have a stomach for it, because I use dosbox-staging exclusively for games.

For tiny new commands it's different - I still think we should have commands like `ls` or `more`/`less` available out of the box, built-in.

If we have some volunteers willing to build a collection of tools, that we could simply drop in utils directory once it'll be implemented in #601, then I can create a new Git repo in dosbox-staging org to help people organize.

Closing this issue. People willing to create a compilation of tools: please leave a comment in #601.

**Closed by dreamer** 2020-09-05 14:40 UTC
Labels: enhancement

**Comment by Akuma-Git** [comment] 2020-09-05 15:49
> > We'll need to square this circle somehow
> 
> Distributing dosbox-staging alone versus dosbox-staging with a suite of DOS tools is similar to the distinction between the Linux kernel versus a Linux distribution.
> 
> Once we open this can of gummy bears, there are going to good arguments to include all manner of DOS utilities, applications, developer tools, and so on.
> 
> Drawing the line will be difficult and arbitrary. I will be the first to admit that having an organized directory tree of best-in-class programs covering the full spectrum of uses (all in, say 200 MB) would be wonderful.
> 
> The work needed to do this right and get from start to finish could be years of effort - including ongoing updates with latest stable builds of actively maintained tools.
> 
> It's a burden that would dilute our focus on dosbox-staging if we were also fielding bug reports, new requests, writing release notes, and so on.
> 
> So I would prefer spinning this out into a sibling project with new folks taking up that effort.

Oh god no, I just stated that the user has an option to put the tools there, in this case an editor. Distributing tools to satisfy every user would be madness.
