### ISSUE TITLE
Extremely low performance on Raspberry Pi 5 using Pi OS Bookworm

### ISSUE THREAD

**Issue by Brunnis** [dosbox-staging/dosbox-staging#3152] opened 2023-11-25 15:17 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Relevant hardware info

Raspberry Pi 5 8GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The performance of DosBox Staging in Raspberry Pi OS Bookworm is rather poor and seems to be very dependent on the window size or if you run in full screen. I've been testing the game Descent, and with the default window size of 1421x1066 the game runs slightly slow but at least pretty playable. Reducing the size of the window makes the game run at full speed. Now, pressing Alt+Enter to go into full screen mode makes the game run so slow that it effectively grinds to a halt. You can hear some individual notes of the midi sound track play very slowly and the screen doesn't seem to update at all.

My desktop resolution is 2560x1440. If I set the desktop to 640x480 instead, Descent will happily run in full screen mode at full speed. So it seems scaling of the output is disproportionally slow, slowing down game performance from fullspeed to far below 1% of full speed. I've also tested Rise Of The Triad and it has the same unusably low performance in fullscreen.

I'm using the Flatpak version of DosBox Staging. All settings at default. Raspberry Pi OS is also a fresh installation at default settings, except for adding the line "kernel=kernel8.img" to /boot/firmware/config.txt (reverts from 16KB pages to 4KB), as that's needed for DosBox Staging to properly run games.

Setting Raspberry Pi OS to use Wayland or X11 does not seem to make a difference.

I do get the following errors when launching DosBox Staging:

`V3D 7.1 not supported by this version of Mesa.`
`libGL error: glx: failed to create dri3 screen`
`libGL error: failed to load driver: vc4`
`V3D 7.1 not supported by this version of Mesa.`
`libGL error: glx: failed to create dri2 screen`
`libGL error: failed to load driver: vc4`

Graphics acceleration on the system is fully working for both OpenGL and Vulkan. Games like Yamagi Quake 2 (OpenGL) and vkQuake3 (Vulkan) are running fine.

### Steps to reproduce the behaviour.

1. Install Raspberry Pi OS Bookworm (64-bit) on a Raspberry Pi 5
2. Add line to /boot/firmware/config.txt: kernel=kernel8.img
3. Boot the OS and install DosBox Staging via Flatpak
4. Launch Descent. Observe the severe performance impact as window size is changed.
5. Press Alt+Enter to go into full screen mode. Game in effect grinds to a halt.

### Your configuration

```ini
Default settings
```

### Provide a Log

```
date       time         | 
2023-11-25 21:23:04.104 | arguments: dosbox
2023-11-25 21:23:04.104 | Current dir: /home/mikael
2023-11-25 21:23:04.104 | stderr verbosity: 0
2023-11-25 21:23:04.104 | -----------------------------------
2023-11-25 21:23:04.104 | dosbox-staging version 0.80.1
2023-11-25 21:23:04.104 | ---
2023-11-25 21:23:04.104 | LOG: Loguru version 2.1.0 initialized
2023-11-25 21:23:04.130 | SDL: version 2.28.4 initialized (x11 video and pulseaudio audio)
2023-11-25 21:23:04.131 | CONFIG: Loaded primary conf file /home/mikael/.var/app/io.github.dosbox-staging/config/dosbox/dosbox-staging.conf
2023-11-25 21:23:04.131 | LANG: Using internal English language messages
2023-11-25 21:23:04.131 | RENDER: Using GLSL shader 'interpolation/sharp'
2023-11-25 21:23:04.131 | DISPLAY: Initialized 1422x1066 window-mode using Bilinear scaling on 1440p display-0
V3D 7.1 not supported by this version of Mesa.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: vc4
V3D 7.1 not supported by this version of Mesa.
libGL error: glx: failed to create dri2 screen
libGL error: failed to load driver: vc4
2023-11-25 21:23:04.379 | OPENGL: Vendor: Mesa
2023-11-25 21:23:04.379 | OPENGL: Version: 4.5 (Compatibility Profile) Mesa 23.2.1 (git-49a47f187e)
2023-11-25 21:23:04.379 | OPENGL: GLSL version: 4.50
2023-11-25 21:23:04.379 | OPENGL: Pixel buffer object: available
2023-11-25 21:23:04.379 | OPENGL: NPOT textures: supported
2023-11-25 21:23:04.385 | VIDEO: Using the DOS video mode's frame rate
2023-11-25 21:23:04.436 | MEMORY: Using 4096 DOS memory pages (16 MiB) at address: 0x7f74be5010
2023-11-25 21:23:04.437 | VIDEO: Initialized S3 Trio64 VESA 2.0 compatible with 4-MiB of FP DRAM supporting 86 modes
2023-11-25 21:23:04.482 | MIXER: Negotiated 2-channel 48000-Hz audio in 512-frame blocks
2023-11-25 21:23:04.482 | MIXER: Reverb disabled
2023-11-25 21:23:04.482 | MIXER: Chorus disabled
2023-11-25 21:23:04.482 | MIXER: Master compressor enabled
2023-11-25 21:23:04.484 | ALSA: No available MIDI devices found
2023-11-25 21:23:04.484 | MIDI: No working MIDI device found/selected.
2023-11-25 21:23:04.484 | MIDI: Opened device: none
2023-11-25 21:23:04.484 | OPL: Operating at 48000 Hz without resampling
2023-11-25 21:23:04.484 | OPL: Running OPL3 on ports 220h and 388h
2023-11-25 21:23:04.484 | SB16: Sound Blaster 16 OPL output filter enabled
2023-11-25 21:23:04.484 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-11-25 21:23:04.484 | SB16: Modern DAC output filter enabled
2023-11-25 21:23:04.484 | SB16: BLASTER=A220 I7 D1 H5 T6
2023-11-25 21:23:04.484 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2023-11-25 21:23:04.485 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-11-25 21:23:04.485 | PCSPEAKER: Initialized discrete model
2023-11-25 21:23:04.485 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-11-25 21:23:04.485 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-11-25 21:23:04.485 | MOUSE: Will be captured after the first left or right button click
2023-11-25 21:23:04.485 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-11-25 21:23:04.485 | MOUSE (PS/2): Standard, 3 buttons
2023-11-25 21:23:04.489 | SLIRP: Slirp version: 4.7.0
2023-11-25 21:23:04.489 | SLIRP: Successfully initialized
2023-11-25 21:23:04.489 | NE2000: Base=0x300 irq=3
2023-11-25 21:23:04.490 | CONFIG: Loaded drive conf file /app/share/dosbox-staging/drives/y.conf
2023-11-25 21:23:04.695 | MAPPER: Found one joystick
2023-11-25 21:23:04.695 | MAPPER: Initialized raphnet technologies 1-player WUSBMote v2.1 with 6 axes, 16 buttons, and 0 hat(s)
2023-11-25 21:23:04.695 | MAPPER: Loaded default key bindings
2023-11-25 21:23:04.698 | SHELL: Redirect output to NUL
2023-11-25 21:23:04.698 | MOUNT: Path '/app/share/dosbox-staging/drives/y' found
2023-11-25 21:23:04.714 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-11-25 21:23:04.750 | SDL: Failed setting the OpenGL vsync state to off (0): That operation is not supported
2023-11-25 21:23:05.018 | DISPLAY: Text 640x400 16 color (mode 03h) at 70.087 Hz VFR, scaled to 1421x1066 with 1.2 pixel aspect ratio
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment] 2023-11-25 20:15
Are you using 0.80.1, or the current GIT version? Does the situation improve if you set

```ini
[sdl]
output = surface
```

?

**Comment by kcgen** [comment] 2023-11-25 20:18
Please paste your full console log in the ticket body (where it says: "Provide a Log").

My guess is your Quake binaries are not Flatpaks?

Build it locally yourself to ensure the binary can access all of your hosts libraries and hardware devices.

Even with the above, prior Pi 400 and older perform best with `vsync = on` and using a window/screen size 720p or smaller in total pixels.

**Comment by Brunnis** [comment] 2023-11-25 20:25
> Are you using 0.80.1, or the current GIT version? Does the performance improve if you set
> 
> ```ini
> [sdl]
> output = surface
> ```
> 
> ?

Using 0.80.1. No, "Surface" output setting runs terribly in full screen as well, despite not scaling to fit the screen.

> Please paste your full console log in the ticket body (where it says: "Provide a Log").

Sure, will update ASAP.

> My guess is your Quake binaries are not Flatpaks?

Correct.

> Build it locally yourself to ensure the binary can access all of your hosts libraries and hardware devices. All those GL errors look bad (like the binary/SDL/OpenGL isn't able to get to the hardware, so might be rendering in software).

I will give it a try.

> Even when the above are fixed and hardware acceleration is working, the Pi 400 and prior perform best with `vsync = on` and using a window/screen size 720p or smaller in total pixels.

Yeah. I have a bit higher expectations for the Pi 5, but not expecting miracles, of course.

**Comment by kcgen** [comment] 2023-11-25 20:31
```
Vendor: Mesa
2023-11-25 21:23:04.379 | OPENGL: Version: 4.5 (Compatibility)
```

The logs helped. @FeralChild64 and my suspicion of lacking hardware acceleration are probably correct. 

The Vendor field should be some kind of hardware manufacturer.. like Intel, AMD, Broadcom, etc.. (I could be wrong though.. maybe these are early drivers on the pi5 or something). 

If a local build of Staging doesn't change it, then your next step is to look at where your SDL library is coming from and consider building that from sources too (because it has compile-time awareness of Pi-speciric acceleration).

**Comment by Brunnis** [comment] 2023-11-25 21:04
Okay, built latest commit from source. With default settings, the performance was still very low in full screen. I noticed it seemed to employ a pretty nice CRT shader, so I went into the configuration file and set glshader = none. With this setting both Descent and Rise Of The Triad now run full speed. This is with the desktop at 2560x1440 and using X11. I confirmed that the mode that was used during full screen in DosBox was indeed 2560x1440 as well.

Below is the new log when launching DosBox. You were right about the lack of HW acceleration. It now states "Broadcom" as vendor. Thanks for pointing me in the right direction.

```
date       time         | 
2023-11-25 21:57:05.042 | arguments: ./dosbox
2023-11-25 21:57:05.042 | Current dir: /home/mikael/dosbox-staging/build/release
2023-11-25 21:57:05.042 | stderr verbosity: 0
2023-11-25 21:57:05.042 | -----------------------------------
2023-11-25 21:57:05.042 | dosbox-staging version 0.81.0-alpha
2023-11-25 21:57:05.042 | ---
2023-11-25 21:57:05.042 | LOG: Loguru version 2.1.0 initialised
2023-11-25 21:57:05.043 | CONFIG: Loaded primary config file '/home/mikael/.config/dosbox/dosbox-staging.conf'
2023-11-25 21:57:05.043 | LANG: Using internal English language messages
2023-11-25 21:57:05.066 | SDL: version 2.26.5 initialised (x11 video and pulseaudio audio)
2023-11-25 21:57:05.066 | DISPLAY: Initialised 1422x1066 windowed mode using bilinear scaling on display-0
2023-11-25 21:57:05.547 | OPENGL: Vendor: Broadcom
2023-11-25 21:57:05.547 | OPENGL: Version: 3.1 Mesa 23.2.1-1~bpo12+rpt2
2023-11-25 21:57:05.547 | OPENGL: GLSL version: 1.40
2023-11-25 21:57:05.547 | OPENGL: NPOT textures supported
2023-11-25 21:57:05.554 | RENDER: Using shader 'none'
2023-11-25 21:57:05.554 | VGA: Pixel-doubling enabled
2023-11-25 21:57:05.554 | VIDEO: Using the DOS video mode's frame rate
2023-11-25 21:57:05.601 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0x7f72e5f010
2023-11-25 21:57:05.602 | VGA: Double-scanning VGA video modes enabled
2023-11-25 21:57:05.602 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2023-11-25 21:57:05.622 | VOODOO: Initialized with 4 MB of RAM, multithreading, and no bilinear filtering
2023-11-25 21:57:05.622 | CAPTURE: Image capturer started
2023-11-25 21:57:05.637 | MIXER: Negotiated 2-channel 48000 Hz audio of 512-frame blocks
2023-11-25 21:57:05.638 | MIXER: Master compressor enabled
2023-11-25 21:57:05.642 | MIDI:ALSA: No available MIDI devices found
2023-11-25 21:57:05.642 | MIDI: Can't find device: 'auto', MIDI is not available
2023-11-25 21:57:05.642 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-11-25 21:57:05.642 | OPL: Operating at 48000 Hz without resampling
2023-11-25 21:57:05.642 | OPL: Running OPL3 on ports 220h and 388h
2023-11-25 21:57:05.642 | SB16: Sound Blaster 16 OPL output filter enabled
2023-11-25 21:57:05.642 | DMA: Initialised primary controller
2023-11-25 21:57:05.642 | DMA: Initialised secondary controller
2023-11-25 21:57:05.642 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-11-25 21:57:05.643 | SB16: Modern DAC output filter enabled
2023-11-25 21:57:05.643 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2023-11-25 21:57:05.643 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2023-11-25 21:57:05.643 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-11-25 21:57:05.643 | PCSPEAKER: Initialised discrete model
2023-11-25 21:57:05.643 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-11-25 21:57:05.643 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-11-25 21:57:05.643 | MOUSE: Will be captured after the first left or right button click
2023-11-25 21:57:05.643 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-11-25 21:57:05.643 | MOUSE (PS/2): Standard, 3 buttons
2023-11-25 21:57:05.646 | SLIRP: Slirp version: 4.7.0
2023-11-25 21:57:05.647 | SLIRP: Successfully initialized
2023-11-25 21:57:05.647 | NE2000: Initialised on port 300h and IRQ 3
2023-11-25 21:57:05.647 | CONFIG: Loaded auto-mounted drive config file 'resources/drives/y.conf'
2023-11-25 21:57:05.879 | MAPPER: Found one joystick
2023-11-25 21:57:05.879 | MAPPER: Initialised raphnet technologies 1-player WUSBMote v2.1 with 6 axes, 16 buttons, and 0 hat(s)
2023-11-25 21:57:05.879 | MAPPER: Loaded default key bindings
2023-11-25 21:57:05.881 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-11-25 21:57:05.900 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1421x1066 with 1:1.35 (20:27) pixel aspect ratio
2023-11-25 21:57:05.901 | MOUNT: Path 'resources/drives/y' found
```

**Comment by rderooy** [comment] 2023-11-25 21:15
I thought the VC4 driver was for older Pi's, and V3D is for the Pi4 and Pi5?

In any case, the issue may be that the flatpak runtime does not really support the Pi5 yet.

**Comment by kcgen** [comment] 2023-11-25 21:18
@Brunnis - great! You are the first to report Pi 5 results, and this is looking pretty good, even at > 1080p.

Would you be able to run a couple benchmarks that many of us around here use?

1. [:file_folder: **`perfdos.zip`**](https://github.com/dosbox-staging/dosbox-staging/files/13398108/perfdos.zip)

    - extract, `cd perfdos`, launch: `/path/to/dosbox --noprimaryconf`

2. [:file_folder: **`quakes.zip`**](https://github.com/dosbox-staging/dosbox-staging/files/13398103/quakes.zip)

    - extract, `cd quakes`, launch: `/path/to/dosbox --noprimaryconf`

Might want to run them each a couple times, as the numbers can bobble around a bit (and report all of them).

(Adding @nemo93)

**Comment by johnnovak** [comment] 2023-11-25 21:46
Try with `glshader = sharp` too. Setting it to `none` gets you bilinear interpolation which looks ugly as hell 😄

**Comment by Brunnis** [comment] 2023-11-25 23:12
@kcgen Sure! The results are:

perfdos:
95
98
98

quakes:
52.1
51.5
52.2

Out of curiosity, how does a Pi 4 do in these tests? BTW, although the tests are run in a window, I tried switching desktop resolution between 2560x1440 and 1920x1080. Results were the same. Same story for X11 vs Wayland.

Regarding the ”sharp” shader, it unfortunately introduces some performance issues in Descent at full screen 2560x1440. I’ll try at 1920x1080 tomorrow to see if that makes a significant difference.

**Comment by kcgen** [comment] 2023-11-26 02:31
Those are very playable numbers. 

The Pi 4 and earliers were marginal for demanding DOSBox games, a bit like running a 486 in the mid 90s. Just not enough 'oomph. 

> Out of curiosity, how does a Pi 4 do in these tests? 

A bit better than 1/4th of your numbers; pretty choppy.

> BTW, although the tests are run in a window, I tried switching desktop resolution between 2560x1440 and 1920x1080. Results were the same. Same story for X11 vs Wayland.


That's good information; because on the pi4, rendering latency really takes off beyond 720p as the output texture grows (this was a common theme for console emulators on it too). 

>
> Regarding the ”sharp” shader, it unfortunately introduces some performance issues in Descent at full screen 2560x1440. I’ll try at 1920x1080 tomorrow to see if that makes a significant difference.

👍

**Comment by Brunnis** [comment] 2023-11-26 23:31
I tested the ”sharp” shader at 1920x1080 instead of 2560x1440. That seemed to clear up the performance issues (at least from what I could tell during a quick test on the first level).

I also moved the SD card to a Raspberry Pi 4 rev. 1.1, to get a likes-for-likes comparison. This is the initial revision of the Pi 4 which runs at 1.5 GHz. With shader set to “none”, Descent runs with fairly low frame rate. Maybe around 15-20 FPS.

Running the performance tests on the Pi 4 resulted in:

perfdos:
29
28
28

quakes:
15.8
16.0
15.8

So, perfdos seems to run upwards 240% faster on the Pi 5 and Quake is around 225% faster (just as you indicated, @kcgen).

**Comment by johnnovak** [comment] 2023-11-26 23:56
So everything is normal and works as expected, great. Thanks for the comprehensive testing, @Brunnis.

**Comment by johnnovak** [comment] 2023-11-30 00:57
Closing as this is all expected behaviour.

**Closed by johnnovak** 2023-11-30 00:57 UTC
Labels: not a bug

**Comment by actraiser30** [comment] 2024-09-28 09:13
If dosbox had multicore support will go like a rocket,1 core is nothing even in a normal PC.
