### ISSUE TITLE
Keyboard Br275 implementation is currently not working properly. Also, it oes not appear in any documentation and special keys ~ and / do not work when pressed unlike DosBox-X

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2057] opened 2022-10-30 16:07 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Keyboard Br275 implementation is currently not working properly. Does not appear in any documentation and special keys ~ and / do not work when pressed unlike DosBox-X. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Have an ABNT 2 Brazilian Keyboard
2. Set KEYB br275
3. Does not output some keys properly

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2022-10-30 16:12
Closing (duplicate of #1981)

**Closed by kcgen** 2022-10-30 16:12 UTC
Labels: bug
