### ISSUE TITLE
Allow mouse buttons to be mapped to keyboard keys or controller buttons

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3073] opened 2023-10-30 14:21 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Intel)

### Is your feature request related to a problem? Please describe.

I've come across at least two games that require user to press right and left mouse buttons at the same time to perform an action. Games that are impacted are at least Settlers I (known as Serf City: Life is Feudal) and a mid 1990s adventure game i can't remember right now. This action is impossible to perform on a MacBook trackpad:

![img-6492](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/3494a314-a345-4cca-b8c7-e2d743fe7b79)

Excerpt from Serf City: Life is Feudal manual:

<img width="445" alt="Screenshot 2023-10-31 at 4 02 40" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/b692106d-67ad-4cb7-9a30-9daf1eb3bb54">

### Describe the solution you'd like

The only way to implement this is to allow user to map a mouse button to a keyboard key or a controller button.

DOSBox ECE included a patch to fix this long standing issue and it worked without issues there:

[DOSBox Staging: ECE patches project card](https://github.com/dosbox-staging/dosbox-staging/projects/5#card-38825286)

[DOSBox Staging: Allow mapping keys to mouse buttons](https://github.com/dosbox-staging/dosbox-staging/commit/d88f6db3b9193d276756b01703c6e9822e8646e5)

https://yesterplay.net/dosboxece/

https://sourceforge.net/p/dosbox/patches/264/

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-10-30 22:34
The new mapper will support this and a lot more. But the OSD will come first. 

Can you perhaphs link this to all the other mapper related tickets/requests @Grounded0? I'm quite sure this is a duplicate of a similar existing ticket where I gave the same reply.

**Comment by Grounded0** [comment] 2023-10-31 00:02
Do you have a single ticket that includes all the mapper feature requests?

**Comment by johnnovak** [comment] 2023-10-31 01:10
> Do you have a single ticket that includes all the mapper related tickets?

I can see you figured out the answer is a no 😄 Thanks for creating the megaticket @Grounded0. ❤️

**Comment by Grounded0** [comment] 2023-10-31 01:14
@kcgen you can stop any work implementing this so it can be implemented in bulk in a rewrite.

**Comment by Torinde** [comment] 2023-10-31 07:13
related [ECE project card](https://github.com/dosbox-staging/dosbox-staging/projects/5#card-38825286) - https://github.com/dosbox-staging/dosbox-staging/commit/d88f6db3b9193d276756b01703c6e9822e8646e5

**Comment by Grounded0** [comment] 2023-10-31 12:15
Thanks @Torinde.

**Comment by Grounded0** [comment] 2023-10-31 12:29
This is the last standing issue according to our ECE project card so it probably should go in now then to finish the job now:

[DOSBox Staging: ECE patches project card](https://github.com/dosbox-staging/dosbox-staging/projects/5#card-38825286)

[DOSBox Staging: Allow mapping keys to mouse buttons](https://github.com/dosbox-staging/dosbox-staging/commit/d88f6db3b9193d276756b01703c6e9822e8646e5)

**Closed** 2023-11-01 20:40 UTC
Labels: enhancement
