### ISSUE TITLE
SVGA S3 Trio emulation is faulty for games using VESA LFB (was: Duke Nukem 3D title screen flickers)

### ISSUE THREAD

**Issue by bmunger** [dosbox-staging/dosbox-staging#366] opened 2020-05-10 20:48 UTC
I have started testing against some of my DOS games and found this bug.  Seems to only show up at the title screen text after the 3D Realms logo.  Parts of the upper character flicker.  This does not happen in upstream Dosbox.  Also tested with opengl/openglb.  This is on a 64 bit Linux build (Ubuntu 18.04).

**Comment by dreamer** [comment] 2020-05-10 20:53
@bmunger when you're saying "upstream Dosbox" do you mean 0.74-3 or SVN?

Does the problem happen when you try different `machine` setting, like:
```
machine = vesa_nolfb
```
?

Also, does it happen when you start with `fullscreen = true`?

*(I don't have DN3D set up for testing anywhere near me, so was not able to reproduce the problem yet)*

**Comment by bmunger** [comment] 2020-05-10 20:59
@dreamer I run the Dosbox SVN newest commit and compile it myself.

I can confirm that the issue goes away with vesa_nolfb

Setting fullscreen = true does not change behavior

Something to do with machine = svga_s3 apparently.  It's consistent though.  I also run Nvidia binary drivers.

**Comment by dreamer** [comment] 2020-05-10 21:24
I had a hunch about `vesa_nolfb` because I observed a similar regression in SVN when 64-bit dynarec was implemented (in my case "flickering" regression was in TOPBENCH) - relevant code was not touched at all, but faster emulation speed triggered some kind of timing issue in `svga_s3`. We had some more changes, that *might* result in faster emulation speed compared to SVN, so maybe it had negative effect on this timing problem in svga_s3 as well…

@bmunger please add info about what version of dosbox-staging are you testing exactly and what SVN revision you are testing against - it will help us with bisecting the issue.

If you'll have any problems with playing while using `vesa_nolfb`, then report them as well :)

This issue stays **open** until we'll figure out exactly why this regression happened.

**Comment by bmunger** [comment] 2020-05-10 22:05
@dreamer 
No problem.
dosbox-staging: commit 8a3a9bfc7565ad2c1567827bdd1143bb84501f9e
dosbox-svn: 4339

I just updated dosbox-svn and it seems to also have this issue now.  Going to attempt to figure out where it broke.  I had updated dosbox-svn fairly recently. as well.

**Comment by dreamer** [comment] 2020-05-10 22:09
If you know how to use git-bisect, then you can try bisecting through `svn/trunk` branch in staging repo (it's the exact mirror). If this is the same issue as in TOPBENCH, then the suspect SVN revision is 4260 (fe177b413603793a3342cfe22f1fc9e050cbea76).

**Comment by bmunger** [comment] 2020-05-10 22:20
The problem is introduced in that SVN revision.  I checked r4259 and r4260.

It also affects the gun held on screen as well if left in the demo mode for a while.  I have not tested but this behavior should be visible in the demo version as well.

Something else to test against a future fix.  Thanks for the help!

**Comment by kcgen** [comment] 2020-05-10 22:42
@bmunger , nice work in bisecting this!

I'm sure upstream would be interested to learn of this regression; especially the exact SVN commit that caused it.

Would you be able to add it to DOSBox's issue tracker? https://sourceforge.net/p/dosbox/bugs/

**Comment by dreamer** [comment] 2020-05-10 23:17
@kcgen I communicated this problem to jmarsh once already; maybe if someone else will mention it, it will get the necessary attention…

**Comment by kcgen** [comment] 2020-05-13 22:38
I agree; plus, now seeing that two separate user-space applications are affected, adds further evidence that the issue is in DOSBox's code instead of being a one-off glitch with topbench.

@bmunger, are you able to submit this issue to sourceforge?

**Comment by bmunger** [comment] 2020-05-13 23:43
@kcgen I will submit it.

**Comment by bmunger** [comment] 2020-05-14 00:03
Submitted upstream as issue 530.
https://sourceforge.net/p/dosbox/bugs/530/

**Comment by kcgen** [comment] 2020-05-14 02:43
Fantastic answer by @ripsaw8080!

**Comment by dreamer** [comment] 2020-05-14 14:56
**ripsaw8080** said:
> The flickering is an issue related to page flipping that affects all Build-engine games. There are a somewhat complicated set of factors that determine if (or to what extent) the issue appears: video resolution, number of video pages, system speed, and scene complexity. The 64-bit dynx86 core providing more speed than the dynarec is probably why you are seeing the issue to a greater extent. However, it's possible you could see it to a lesser extent with dynarec, such as flickering of the HUD or held weapon when closely facing walls in the game because low detail scenes are rendered faster.
> 
> The issue doesn't appear with machine=vesa_nolfb because the absence of LFB means bank-switching must be used, thus there is no page flipping. Ken Silverman, the author of the Build engine, has a NOLFB TSR utility on his website originally intended for real systems, but it can be used in DOSBox to disable LFB if you'd rather use machine=svga_s3 than switching to machine=vesa_nolfb. Alternatively, you can try using cycle limits, which I prefer to use with Build games rather than fixed cycles, but it can be tricky to find the right amount of cycles to eliminate the flickering due to variations in framerate caused by varying scene complexity.

Link to [NOLFB utility](http://www.sierrahelp.com/Utilities/DisplayUtilities/NOLFB.html).

What's notable is that this utility was a workaround for OSes, that dropped support for linear frame buffer feature of VESA 2.0... This gives some hint, that although it's a working and valid workaround - perhaps we're still having a bug somewhere in `svga_s3` emulation - probably a bug predating r4260, but it was simply hidden earlier.

I'm not sure if we should close this bug or keep it open to follow up with the investigation…

**Comment by MasterO2** [comment] 2020-05-16 19:59
> 
> 
> I have started testing against some of my DOS games and found this bug. Seems to only show up at the title screen text after the 3D Realms logo. Parts of the upper character flicker. This does not happen in upstream Dosbox. Also tested with opengl/openglb. This is on a 64 bit Linux build (Ubuntu 18.04).

If you're looking to run anything Duke Nukem 3D, you should be using Eduke32: 

https://eduke32.com/

Ubuntu should already have a package for that in its repository, so that would eliminate the need for you to run Duke 3D in DOS.

Of course, you can still use DOSBox if you want to play it that way, but I was merely bringing Eduke32 up if you didn't happen to know about it by now.

**Comment by bmunger** [comment] 2020-05-16 21:46
@MasterO2 Thanks.  I'm aware.  In this instance I was using it to test software I am familiar with to see if there were any notable changes.  However, also in this case, there is a clear advantage of using the original Duke Nukem 3D code.  Multiplayer is something that has not worked well with Eduke32 in the past and is probably in similar shape these days.  Running DOSBox IPX or serial/modem emulation can make this work though.

As far as the bug report goes, it's probably best to close this since improved behavior within the limits of the build engine is not likely under svga_s3.

**Comment by dreamer** [comment] 2020-05-17 21:51
OK, I slept on it and think this issue should stay **open** as a bug (but not game-specific one). Using `vesa_nolfb` is a great workaround available to all users, so the priority is not high, but unless someone will dig in and confirm that this is 100% not a bug in S3 Trio emulation - we should keep it open.

Basically, we *know* this problem happens not only in Build engine games (as it happens in ~TOPBENCH~ PCPBENCH as well). We also *know*, that NOLFB utility for Build games was a workaround for OSes dropping support for VESA extension, and not for "processors being too fast".

On Vogons I found [list of games](https://www.vogons.org/viewtopic.php?p=4053#p4053), that *supposedly* require NOLFB:
```
Age of Rifles
Archimedean Dynasty
Blood
Constructor
Death Rally
Duke Nukem 3D
Extreme Paintbrawl
Fantasy General
Grand Theft Auto (Required for 24bit, 8 bit works fine)
Mechwarrior 2
Mechwarrior 2 Mercenaries
Megarace 2
Mortal Kombat Trilogy
NAM/Napalm
Need for Speed
Nemesis: The Wizardry Adventure
Powerslave
Redneck Rampage
Redneck Rampage Rides Again
Redneck Deer Huntin'
Shadow Warrior
Syndicate Wars
System Shock
TekWar
TIE Fighter
Toonstruck
Versailles 1685
Witchhaven
Witchhaven 2: Blood Vengeance
WWII GI
```
(but I find it dubious, as I tested Megarace 2 and TIE Fighter with svga_s3 and don't need NOLFB utility)

For people who have some spare cycles and want to dig in ;) :
- `vesa_nolfb` internally turns on the same emulation code as `svga_s3` except turning on a boolean to disable certain handling, so that should make investigation easier (I don't know why it was named `vesa_nolfb` and not `svga_s3_nolfb`). That boolean turns off specific bits - look inside function VESA_GetSCGAModeInformation in file `ints/int10_vesa.cpp`
- the code lives in files: `src/hardware/vga_*`, I suggest starting investigation around timing-related code (search for "GetClock" and "svga.get_clock").

I will close this issue once we either:
- confirm, that SVGA S3 Trio emulation is definitely correct (e.g. via reproducing this problem on real hardware using this card and fast processor, or via analysis of emulator source code, confirming all the same VESA BIOS Extensions are available on S3 and in dosbox emulated S3, etc)
- or find the **exact** root cause for this problem in code and explain or fix it (so no handwaving about "oh, that's just the way it is").

*Either way, we'll learn something new about this undocumented emulator code.*

**Comment by flashmasta** [comment] 2020-05-26 18:22
This is a bug I would love to help out if I could.  Build games (notably Duke3D and Blood for sure as I have played them recently) are the only games I have had to create custom conf file and run with vesa_nolfb.  On dosbox-staging stable I can remove the flickering completely by lowering speed to 50% (between 50-60% it is still there on edge cases). I can confirm that dosbox-x stable (0.83.1) does not have this issue with Blood and Duke3D at least while set to svga_s3.  Changing the dosbox-x conf to vesa_nolfb makes no change.  I am wondering if they just have that bit permanently set now?

**Comment by kcgen** [comment] 2020-05-26 22:48
> only difference I see in vga_s3.cpp between staging, vanilla, and dosbox-x is X

I /think/ I remember that DOSBox-X defaults to `core = normal`.  This would have been a couple years ago though; but might be worth double-checking.  So you could try `dynamic` w/ DOSBox-X, or vice-versa (`normal` w/ SVN and staging).

**Comment by dreamer** [comment] 2020-05-26 22:53
I don't think DOSBox-X has 64-bit dynarec (the feature that made dosbox fast enough to trigger this issue).

**Comment by flashmasta** [comment] 2020-05-26 23:12
When I test dosbox-x when core = dynamic (auto by default, I assume it is using dynamic when auto) I get the same (good) results.  If I switch staging to core = normal there is no flickering but slow.

It does appear that dosbox-x uses a 64-bit dynamic core as far as I can tell.

**Comment by kcgen** [comment] 2020-05-27 00:35
Found it:
![Screenshot at 2020-05-26 17-31-29](https://user-images.githubusercontent.com/1557255/82963097-cf3c1500-9f76-11ea-9c85-9ef40adabbb7.png)

At least as of September last year, `core = auto` in DOSBox-X means:
- use the `normal` core when in 16 bit real-mode
- switch to `dynamic` core for 32 bit protected-mode programs

Duke3D used protected-mode, so (if assuming this logic holds), you would have been running with the dynamic core.

**Comment by flashmasta** [comment] 2020-05-27 17:44
I noticed some interesting behavior (at least to me). I found a way to get dosbox ece to flicker in Blood but only in a very specific way.  See this video: https://youtu.be/GsDv2lr3IAA

You can see that starting the game there is no flickering at all but as soon as I start pressing my character into the wall at about the 00:22 mark you can see the HUD start to flicker.

That is something that I couldn't get dosbox-x to do at all, no matter what I did I could not get dosbox-x to flicker.  I was able to get dosbox-staging to do that HUD flicker very rarely when speed was set to 50% but once I set it to 45% it either stopped completely or I just couldn't get it to pop up in the time I tested. (in all cases:machine=svga_s3 and core=dynamic).

I'm not sure if that means anything but hopefully it is useful, or if they are able to be directly compared in this regard though.

**Comment by sabercyclone041** [comment] 2020-06-26 11:43
Hi, first comment here and this thread prompted me to join. 

Can we add Wrath of Earth to the list of games that suffer from flicker. The opening cutscenes and intro all display fine, but when I get into the core gameplay itself, I get flickering in the form of thick black lines, mainly in the middle of the screen. I've tried both the svga_s3 and vesa_nolfb for the machine setting, both openglnb and surface for the output setting and operating with full resolution set to both true and false.

As I know the title is pretty obscure, if anyone wanted to take a look at it firsthand, The My Abandonware page with a copy of it for download, can be found [here](https://www.myabandonware.com/game/wrath-of-earth-29t).  

If anyone can give me a heads up if there's something I'm not doing that I need to do (I already had to set EMS to false and as a precaution for low memory, I set the memsize to 64), I'd greatly appreciate it.

**Comment by Gamewizard** [comment] 2020-12-07 09:00
I can confirm having this issue on Duke Nukem 3D with the newest 0.76 release I compiled locally for FluidSynth support. 

Some video I captured of the issue: https://youtu.be/KN1FePBbXqs

**Comment by nemo93** [comment] 2020-12-07 10:43
@Gamewizard, all. I may have a similar case with Blood patched with version 1.10 and above. With versions 1.00 & 1.02 game will play absolutely fine with Staging (with or without dos32a). Yet after patching game up to 1.10 or 1.11 then flickering will appear right in the demo (hud is mostly flickering). While in game flicker seems to stop after a few minutes or so but I haven't tested extensively. I'll give a try to the values you've mentioned.

Note: Blood 1.10+ will show the intros as FMV as well as cutscenes before each episode. After 25 years I discover there were cutscenes in that game !!!

**Comment by nemo93** [comment] 2020-12-20 17:04
@sabercyclone041 hey! I'm about to add Wrath_of_Earth in my test array. I've stumbled upon [that page](https://www.pcgamingwiki.com/wiki/Wrath_of_Earth#Flickering_graphics) where they state to run the game with low amount of cycles (10000) to prevent any flickering. I wonder if you tried that as well?

**Comment by kcgen** [comment] 2021-08-23 00:43
When `cycles` exceeds ~220k/s, it will exercise the S3 adapter too fast and those blanking/empty scan lines will start to show through its own 70 hz frame-rate. NOFLB "works" because it doesn't make those blanking scans - is essence it always writes "positive" raster information.

On my system the auto-cycle logic (`cycles = max`) will climb into the 600,000 range when running PC Player's benchmark at 640x480.  Setting it to `cycles = max 95% limit 220000` does the job (and will still backoff for CPU intensive games where my system would be unable to provide 220k cycles).

This is an area where we could pace the internal adapter output no faster than 70 Hz, or we could insert wall-clock delays to prevent the auto cycler's math from winding up that far, or we could simply cap the auto-cycler when S3 is running in a high-resolution mode.  None of these sound very good.. well, maybe the 70 fps limit is the best of the bunch...

**Closed** 2021-09-13 19:23 UTC
Labels: bug, help wanted
