### ISSUE TITLE
Dosbox Staging SteamOS flatpak Modifier keys captures

### ISSUE THREAD

**Issue by kingjoma** [dosbox-staging/dosbox-staging#3302] opened 2024-01-03 20:40 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

I have Dosbox Staging installed as a flatpak on my Steamdeck and it seems as if the CTRL and ALT keys have been captured by the emulator and not being released to Steam input. These modifier keys do not function on Dos Games. Is there a way to release these modifiers so Steam Input can grab them and use them? 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2024-01-03 21:43
@kingjoma, the problem appears to be at the interface between flatpak and Steam OS. I would suggest asking about this with whoever created the flatpak for Steam OS. 

Alternatively, I know @ThomasEricB compiles DOSBox Staging directly on his Steam deck. I believe you can follow the nix-OS instructions to do the same: https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/build-nix.md

Because there are no issues with **Ctrl** and **Alt** working with our downloadable binaries on Linux, BSD, macOS, and Windows, I'll close this as out-of-scope.

**Closed** 2024-01-03 21:44 UTC
Labels: question, external, packaging, won't do

**Comment by rderooy** [comment] 2024-01-03 21:51
I don't think there is a special "steam deck" flatpak, I think it is the regular flatpak which is available for both x86_64 and arm64.

I don't understand the question though. Of course DOS programs use the ctrl and alt keys, and while I don't have a steam deck, they seem to work fine on the x86_64 flatpak build. DOS programs can use the keys, as they should be able to.

**Comment by kcgen** [comment] 2024-01-03 22:32
Thanks @rderooy for the background (I wasn't sure if Steam OS has a separate flatpak repo or something); also thanks for confirming your existing flatpak works fine.

Assuming @kingjoma is using your flatpak, I guess this means the problem is even further upstream w/ Steam OS eating those keystrokes itself (and not passing them to flatpak). So @kingjoma, maybe this issue should be raised with the Steam OS project.

**Comment by rderooy** [comment] 2024-01-03 22:50
@kcgen when I read what he wrote, it get a feeling that he wants the contrary, namely that the CTRL and ALT modifier keys are NOT going to DOSBox Staging, but rather to Steam OS itself when Staging is running. This is obviously not going to work as such.

**Comment by johnnovak** [comment] 2024-01-03 23:38
> @kcgen when I read what he wrote, it get a feeling that he wants the contrary, namely that the CTRL and ALT modifier keys are NOT going to DOSBox Staging, but rather to Steam OS itself when Staging is running. This is obviously not going to work as such.

Out of scope for us. And I think he can unmap those keys in the mapper, but that would break certain programs/games.

**Comment by kingjoma** [comment] 2024-01-04 02:58
Hi All. Thank you for the wonderful response time. I am a complete Linux novice and used the flatpak as I don't understand how to build a programme or properly understand the command line in Linux. I am happy to try build Dosbox Staging in SteamOS but even the link to ThomasEricB's NixOS install guide is tough to follow. Is there a way I can get in touch with ThomasEric to talk me through the build on SteamDeck?

**Comment by Grounded0** [comment] 2024-01-04 03:09
You could open a discussion here and ping the person to join it:

https://github.com/dosbox-staging/dosbox-staging/discussions
