### ISSUE TITLE
Wolfenstein 3D Super Upgrades crash

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#2212] opened 2023-01-09 16:57 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I installed Wolfenstein 3D v1.4 and it works. I found out about this collection of levels called `Wolfenstein 3D Super Upgrades`. The installation is successful, I run the WolfMaster program (wolfm.bat), choose levels, start the game and it crashes/freezes without errors. This is what I found on a forum:
```
The addon was released as freeware by 3DRealms, and is available (with no support) on their FTP server. Wolf3D is crashing because the external menu program tries to rename some files using wildcards, which DOSBox does not support.

You can work around the situation by using the 4DOS command shell, which has more full-featured versions of DOS commands. Place 4DOS.COM in the root of your mounted C: drive, and then type "SET COMSPEC=C:\4DOS.COM" in DOSBox prior to running the addon. You can put the SET command in the autoexec section of your conf file for convenience. You should also probably re-install Wolf3D and the addon because of the leftover files that didn't get renamed.

```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Wolfenstein 3D v1.4
2. Install Wolfenstein 3D Super Upgrades
3. In the Wolfenstein 3D folder run "setup" (it will install WolfMaster)
4. Run WolfMaster (wolfm.bat), choose some levels and start the game

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment] 2023-01-09 17:07
Does the recommended work-around, work?

> You can work around the situation by using the 4DOS command shell, which has more full-featured versions of DOS commands. Place 4DOS.COM in the root of your mounted C: drive, and then type "SET COMSPEC=C:\4DOS.COM" in DOSBox prior to running the addon. You can put the SET command in the autoexec section of your conf file for convenience. You should also probably re-install Wolf3D and the addon because of the leftover files that didn't get renamed.

**Comment by Kappa971** [comment] 2023-01-09 17:10
> Does the recommended work-around work?

I haven't tried it yet, but I guess this needs to be fixed in DOSBox Staging (if it doesn't require too much work).

**Comment by Kappa971** [comment] 2023-01-09 17:23
Yes, it works with 4DOS.COM

**Comment by kcgen** [comment] 2023-01-09 17:23
Yes; I agree @Kappa971 - wildcard renaming has the potential to change a lot of files instantly, so if this is added, we'll need some thorough testing to adhere to MS-DOS wildcard renaming spec (if there is one).

**Comment by Burrito78** [comment] 2023-05-13 14:51
4DOS saved the day.

**Comment by Kappa971** [comment] 2023-05-13 17:26
Yes, but the problem with DOSBox Staging is not solved and should be addressed (4DOS is a workaround).

**Comment by johnnovak** [comment] 2023-05-13 22:23
Please leave it open @Burrito78. DOS compatibility is clearly broken here, this should be fixed not worked around

**Comment by weirddan455** [comment] 2023-11-14 02:16
I've reproduced and tracked down the root cause of this.  One of the executable is invoking a shell command that looks something like `ren *.a *.wl6` to change the file extensions of multiple files.

Our `DOS_Shell::CMD_RENAME` implementation currently does not support wildcards so this currently fails to rename anything.  I'm going to work on adding support for this.

**Comment by MasterO2** [comment] 2023-11-14 02:36
https://www.vogons.org/viewtopic.php?f=33&t=19436&p=140452&hilit=wolfenstein%203d%20super#p140452 

 Apparently, Wolfenstein 3D Super Upgrades is **freeware**.

The FTP link in the above Vogons link still works if you use `curl`, `wget`, or anything else that supports FTP.

Per the Readme file, Wolf3D-SU became **freeware** in May 2006.

**Comment by johnnovak** [comment] 2023-11-14 03:29
> I've reproduced and tracked down the root cause of this. One of the executable is invoking a shell command that looks something like `ren *.a *.wl6` to change the file extensions of multiple files.
> 
> Our `DOS_Shell::CMD_RENAME` implementation currently does not support wildcards so this fails to rename anything. I'm going to work on adding support for this.

Excellent @weirddan455, much appreciated! ❤️

**Closed** 2023-11-17 05:47 UTC
Labels: bug
