### ISSUE TITLE
Events are missing from the mapper user interface

### ISSUE THREAD

**Issue by amak79** [dosbox-staging/dosbox-staging#298] opened 2020-04-19 11:05 UTC
Certain events are missing from the mapper user interface (CTRL+F1) from dosbox-staging. The full list of missing events compared to DOSBox 0.74-3 are `Cap Mouse`, `Speedlock`, `Rec Wave`, `Cap MIDI`, `Screenshot`, `Video`, `Dec Fskip`, `Inc Fskip`, `Dec Cycles`, `Inc Cycles`, `Cap OPL`, and `Swap Image`.

I don't know if these events were removed intentionally or not but I would expect events such as `Screenshot` and `Video` to be present. In particular the video capture event which I wanted to reconfigure because the default (CTRL+ALT+F5) conflicts with the Plasma desktop on Linux.

Tested with git master (commit c7281b1c482dd89cacfa4a0082123a16cdf211af) on Gentoo Linux.

**Comment by dreamer** [comment] 2020-04-19 11:46
I can confirm this. These buttons started disappearing when we moved to SDL2 (mapper code was largely rewritten by SDL2 patch we imported), then they started (occasionally) appearing again as we were fixing various mapper issues, and now they disappeared again :/

This is not intentional, we want to restore these actions.

Default shortcuts being `Ctrl+Alt+F<something>` is a separate problem affecting every Linux user. We need to replace these with other combination (we inherited this bug from the upstream project). It's even known issue in DOSBox SVN, that they decided *not* to fix (there's a section in the manual where they advice every Linux user to change mappings on their own).

As a workaround I tried if I can manually replace it in fresh mapper file, and turns out yes:

    hand_video "key 62 mod2"

Changes video capture shortcut to ALT+SHIFT+F5 (which is surprising, because I was expecting ALT-F5).

So we have at least 2-3 related issues in here:

- missing buttons in mapper GUI
- bad defaults on Linux
- surprising "mod2" behaviour

Let's keep this in a single report for now - all 3 issues are somewhat related.

**Comment by kcgen** [comment] 2020-04-19 12:06
Awesome catch guys; I wasn't aware of this happening! During the mapper reload fix for the joysticks, I noticed the mapper's state is  extremely sensitive to overall order-of-operations of where it lives in relation to when other 'modules' in DOSBox are started up for the first time (implying at least this aspect of it's design is quite fragile and error prone). 

For example, we see both the Speedlock and Fullscreen bindings in the code:

- src/dosbox.cpp: 2MAPPER_AddHandler(DOSBOX_UnlockSpeed, MK_f12, MMOD2,"speedlock","Speedlock");`

- src/gui/sdlmain.cpp: `MAPPER_AddHandler(SwitchFullScreen,MK_return,MMOD2,"fullscr","Fullscreen");`

So why is Speedlock absent in the GUI while Fullscreen is still present? 

It's all order of operations.  These "keybind registrations" calls aren't done in some common roundup task.  Instead, they are sprinkled about in normal code, that you need to execute to (as a side effect) get the keybind registration. 

So one approach might involve going through the pre-SDL2 code and finding that precarious order of operations and reproduce it here again, and hope it doesn't conflict with any new SDL2-isms we need. 

A more robust fix is to roundup all these side-effect keybind events, and lift them out into some time-independent call, driven by the mapper's initialization, making it fool proof and resilient again order of operations.

**Comment by kcgen** [comment] 2020-04-19 16:51
![Screenshot at 2020-04-19 09-35-36](https://user-images.githubusercontent.com/1557255/79694101-3e5d7580-8223-11ea-88a6-38f9e21a1c7d.png)

@amak79 , @dreamer , can you kick the tires on `kc/mapper-defreg-1`?

**Comment by amak79** [comment] 2020-04-20 00:08
I tested that branch but I still have `Cap Mouse`, `Screenshot` and `Video` missing.

**Comment by kcgen** [comment] 2020-04-20 02:03
> I tested that branch but I still have `Cap Mouse`, `Screenshot` and `Video` missing.

Darn; I wonder why.  Just to to confirm - you've built cb6c4bcd? I re-built, re-ran, and still get everything showing up in the above screenshot. 

Can you try with a clean config-state, and make sure you have no mapper file?

**Comment by amak79** [comment] 2020-04-20 02:24
It seems to be caused by passing `--enable-screenshots` to configure. By default my Gentoo package for dosbox-staging passes that option. If I don't pass it then I get the `Screenshots` and `Video` events but I'm still missing `Cap Mouse`.

**Comment by amak79** [comment] 2020-04-20 02:31
Interestingly with `--enable-screenshots` configure outputs the following:
```
checking png.h usability... yes
checking png.h presence... yes
checking for png.h... yes
checking for png_get_io_ptr in -lpng... yes
checking whether screenshots will be enabled... no
```

**Comment by kcgen** [comment] 2020-04-20 02:58
> but I'm still missing `Cap Mouse`.

Ah, Sorry @amak79! The `Cap Mouse` event will only exist if the mouse is capturable in the first place; and by default the mouse is `seamless`, so it can't be captured :-)

```
	// Only setup the Ctrl+F10 handler if the mouse is capturable
	if (sdl.mouse.control_choice & (CaptureOnStart | CaptureOnClick)) {
		MAPPER_AddHandler(ToggleMouseCapture,MK_f10,MMOD1,"capmouse","Cap Mouse");
	}
```

Give `capture_mouse = onstart middlerelease` (or `onclick`) a try, and the event should be map'able.

**Comment by amak79** [comment] 2020-04-20 03:02
Setting `onclick` for `capture_mouse` enables the `Cap Mouse` event.

**Comment by amak79** [comment] 2020-04-20 04:09
With regards to the screenshots configure flag, removing line 437 (`enable_screenshots=no`) from `configure.ac` results in `--enable/disable-screenshots` to behave as expected.

**Comment by dreamer** [comment] 2020-04-20 14:10
> With regards to the screenshots configure flag, removing `enable_screenshots=no` from line 437 in `configure.ac` results in `--enable/disable-screenshots` to behave as expected.

Screenshots are enabled by default and we do not support option `--enable-screenshots`, only `--disable-screenshots`, pedantically speaking :) Anyway, we'll need to make it work consistently - thanks for pointing this out (this problem is due to my inexperience with autoconf weirdness).

**Comment by kcgen** [comment] 2020-04-20 14:15
@dreamer, thinking about the current PR (https://github.com/dosbox-staging/dosbox-staging/pull/299) - right now, it doesn't change functional behavior of the mapper (ie: the mod1 vs mod2 issue you mentioned, or this `--enable/disable screenshot` nuance) -- it just centralizes the initialization of the mapper and keyboard.  

I will note that it partially addresses this issue here, but will drop that it fixes it - so we can address the others in a separate PR.

**Comment by amak79** [comment] 2020-04-20 14:20
> this problem is due to my inexperience with autoconf weirdness

The [Autotools Mybuster](https://autotools.io/) is great Autotools reference. There is a good [section](https://autotools.io/autoconf/arguments.html) about the `AC_ARG_ENABLE` macro.

**Comment by dreamer** [comment] 2020-04-20 14:35
In the past, I tried to follow some advice from this reference. It was incomplete and caused new problems, so I tend to stick to [autoconf manual](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/index.html) nowadays. I'll give it another shot.

**Comment by amak79** [comment] 2020-04-21 13:06
@dreamer I've figured out how to properly handle the `--disable-screeshots` flag within the Gentoo package. Unless you really want to make it consistent with the other `--disable` flags, it isn't necessary to make any changes to `configure.ac`.

**Comment by kcgen** [comment] 2020-08-29 20:45
I believe we can close this:

The PR was fixed to include all of the actions (no longer missing the ones listed above):

![2020-08-29_13-40](https://user-images.githubusercontent.com/1557255/91645790-56c57400-e9fd-11ea-87ab-30152f0dd2ae.png)

The default keystrokes under Linux are (atleast for me), what I expect and don't include an extra Mod (Alt) key:

- Record audio: Ctrl + F6
- Capture screenshot: Ctrl + F5
- Cycles Up and Down: Ctrl + F12/F11
- Quit: Ctrl + F9

![2020-08-29_13-41](https://user-images.githubusercontent.com/1557255/91645791-56c57400-e9fd-11ea-8ad2-77ccb025d959.png)

@amak79 @dreamer - can you confirm?

**Comment by dreamer** [comment] 2020-08-29 23:12
I made a separate bug report so we won't forget to fix those 3 default keybindings (somehow); as for this issue, I agree - it's fixed, I am closing it.

@amak79 if you think we should keep this open, then leave a comment - I'm willing to reopen if something does not work correctly.

**Closed by dreamer** 2020-08-29 23:12 UTC
Labels: bug

**Comment by amak79** [comment] 2020-08-29 23:15
The default keystroke for video capture (CTRL+ALT+F5) still conflicts with my Plasma desktop on Linux. The missing events are present now so I can assign a different keystroke combination. Tested with 0.75.1.

**Comment by dreamer** [comment] 2020-08-29 23:20
For default keybind issue I created #585 - to focus specifically on this problem.
