### ISSUE TITLE
Fluidsynth sounds incorrect

### ISSUE THREAD

**Issue by x73rmin8r** [dosbox-staging/dosbox-staging#2701] opened 2023-07-27 04:46 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DOSBOX-staging-v0.81.0-alpha-1152-g5d881

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I think there may be a problem with the Fluidsynth implementation in Staging. I ran across a song (level 8 of Descent) that sounds noticeably wrong using Fluidsynth, but sounds correct when using the same soundfont file using the external midi player CoolSoft VirtualMIDISynth. Also DOSBOX-X using Fluidsynth sounds correct, so it might not be a fault with Fluidsynth itself.

Same behavior in alpha 1152 and release version of Staging. Tried with the Fluidsynth reverb and chorus settings off and on.

[descent-fluidsynth-error.zip](https://github.com/dosbox-staging/dosbox-staging/files/12179354/descent-fluidsynth-error.zip)

The sound recorder didn't capture the music using the external midi player, but to my ear the output I got when using VirtualMIDISynth and Fluidsynth in DOSBOX-X sounded essentially the same as an AWE32 card (1mgm.sf2 is from a dump of the AWE32 ROM) (https://www.youtube.com/watch?v=avrvEVQgdaM). There's possibly some differences in the reverb/chorus effects, but the actual melody starting at about 0:16 in my recording was what I noticed being incorrect.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. set fluidsynth as the midi device with the 1mgm.sf2 soundfont
2. set Descent to use general midi 
3. start level 8 (use cheats to levelskip, during gameplay type "gabbagabbahey" to enable cheats, then "farmerjoe" to open level select menu

### Download URL of affected game or software

gog descent (level 8 isn't in shareware version unfortunately)

### Your configuration

```ini
https://gist.github.com/x73rmin8r/b4a9900ad3196cba7f27bc47823ddb53
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-07-27 07:48
Thanks @x73rmin8r, I can reproduce the problem in DOSBox Staging with the Level 8 music.

My findings so far:

- I can reproduce it in the latest dev version of Staging with _any_ SoundFont on macOS and Windows
- Exact same results on 0.77.1
- Now the confusing part: DOSBox X 2023.05.01 on macOS has the same problem, but on Windows the problem is gone! Huh? 😱 I tried this several times and I'm 100% sure about it: DOSBox X on macOS has the same issue, but Windows is fine!
- Tried Falcosoft MIDI Player on Windows and the Roland SCVA—they're fine, so at least we're not sending wrong data to the external MIDI devices, that's certain.

I'm inclined to think this is a weird FluidSynth bug and we're not doing anything wrong. But it's strange that the Windows build of DOSBox X does not have the bug...

Can someone test this on Linux with DOSBox X and latest Staging? @weirddan455 @FeralChild64 ?

Also, just explicitly pointing out that CoolSoft VirtualMIDISynth uses the BASS library, not FluidSynth (I believe you know that as you kinda implied that; I just wanted to spell it out 😄)

**Comment by weirddan455** [comment] 2023-07-27 14:47
I'm assuming the .wav file inside the attached `descent-fluidsynth-error.zip` is the bugged sounding one and the YouTube link is the correct one?

If so, yeah it sounds bugged to me on both Staging and DOSBox-X on Linux.

@johnnovak What version of DOSBox-X did you test on Windows?  Build from source or did you just download a binary?  If from source, which of their many build scripts did you use?

My hunch is that there's a FluidSynth regression and your Windows build of DOSBox-X is using an older version of FluidSynth that doesn't contain the bug.  Their build system is giving me a headache just looking at it though so I'm not sure how to confirm.  They have in-tree FluidSynth code in src/libs yet, on my Linux system, it is also dynamically linking to my system's FluidSynth.  If I uninstall my system's FluidSynth and re-build, support just gets compiled out and I hear nothing (unlike Staging where it falls back to a Meson Wrap).

**Comment by kcgen** [comment] 2023-07-27 19:20
Bumped FluidSynth wrap to 2.3.3 (latest) on `main`. It fixes:

- https://github.com/FluidSynth/fluidsynth/issues/1250

(but I haven't been able to test it)

**Comment by weirddan455** [comment] 2023-07-27 19:52
I forgot to mention, I had tested with that 2.3.3 warp already.  Also the 2.3.3 that comes packaged with Arch.  It sounds the same to me as 2.3.2 (bugged).

DOSBox-X has some older FluidSynth code in their tree.  It might even be modified from upstream.  It was most recently touched a year ago, though most files haven't been touched in 3 years.

That's why I'm assuming it's a regression, though on Linux (and I'm assuming on Mac, I saw some calls to the Brew package manager in there) the bug still manifests because it dynamically links to system libraries.

On Windows, the scripts I saw had FluidSynth completely disabled.  Though I'm probably missing something... their build system really frightens me lol.

**Comment by johnnovak** [comment] 2023-07-28 01:56
> Bumped FluidSynth wrap to 2.3.3 (latest) on `main`. It fixes:

That's great @kcgen, thanks for that. I've rebuilt everything but this doesn't fix the issue. Although not sure how can I verify that Meson indeed uses 2.3.3 or something else.

> I'm assuming the .wav file inside the attached descent-fluidsynth-error.zip is the bugged sounding one and the YouTube link is the correct one?

Yes.

> If so, yeah it sounds bugged to me on both Staging and DOSBox-X on Linux.

Thanks for confirming.

> @johnnovak What version of DOSBox-X did you test on Windows? Build from source or did you just download a binary? If from source, which of their many build scripts did you use?

Latest binaries from their website (version 2023.05.01). I'm not gonna build it from source, nope 😅 

> My hunch is that there's a FluidSynth regression and your Windows build of DOSBox-X is using an older version of FluidSynth that doesn't contain the bug. 

Yes, or they use some custom hacked version that's in their repo, like you said 🤷🏻 

---

Ok, so reality check here:

- The issue is present in 0.77.1 which was released on 2021-08-28. As we haven't had a huge influx of MIDI / FluidSynth related bug reports since then, this is likely a very rare edge case. Annoying if you want to play Descent, but I think the majority of MIDI soundtracks don't trigger the bug.

- External MIDI modules work fine (as long as they're not FluidSynth), so this points in the direction of a FluidSynth problem. Also, I tried about 5 different SoundFonts (official Creative ones, GeneralUser, Fluid R3, etc.), and all exhibit the issue, meaning this is a universal problem, not SoundFont specific.

- If you use the menus in DOSBox X, that pauses the sending of MIDI events, and if you do this while the "bendy" notes are playing, you'll hear the bad notes slowly slide up about an octave or so. I don't think any SC-55 or GS patches do this kind of thing by default, so this indicates that some of the FluidSynth modulators are causing the behaviour. This can be either because the MIDI file in question sends some data that sets up such a modulator erroneously, or maybe there's a default modulator that does pitch glides and the MIDI file somehow triggers it.

All in all, a low priority issue that I will definitely debug, but it will take some time. I'll need to capture the raw MIDI output of the Level 8 music, analyse the raw MIDI data in a MIDI sequencer, then play it back using the official FluidSynth binaries only and trying to narrow down the issue to a sequence of MIDI messages.

Note that FluidSynth doesn't actually _aim_ to be SC-55 or GS compatible or anything, so maybe this will be an unfixable/out-of-scope issue for them. We'll see.

My assessment is that we can release v0.81.0 with this bug, but I'll see how much time I'll have to tinker with it.

**Comment by weirddan455** [comment] 2023-07-28 13:12
>  Although not sure how can I verify that Meson indeed uses 2.3.3 or something else.

I just run the `ldd` command on the final binary to verify what it's been linked with.  Meson will try to find a library on your system to link with and, if you don't have one, will use the .wrap file to compile it from source.

```
[daniel@arch dosbox-staging]$ ldd build/release/dosbox | grep fluidsynth
        libfluidsynth.so => /home/daniel/code/dosbox-staging/build/release/subprojects/fluidsynth-2.3.3/libfluidsynth.so (0x00007fd7e5141000)
```
In this case, it built from wrap.  You can also just check for the presence of `subprojects/fluidsynth` inside your build folder.  If that's not there, it's probably linking with a system library.

**Comment by johnnovak** [comment] 2023-07-28 21:38
Thanks @weirddan455. I'm wondering if there's an easy way to write the version of external deps we link against into a big string at compile time, then compile that in. Then we could query that at runtime or log it. Although it has limited utility, it might help in some troubleshooting scenarios, and unless it's super complicated to compile that in, I think it's a no brainer.

**Comment by weirddan455** [comment] 2023-07-28 22:04
That's probably possible.  That's a build system thing.  I don't know Meson well enough to say how easy it would be.

IMO, it's usually more useful to collect runtime versions of libraries (see #2689 where I did that with SDL).  With fluidsynth, there are similar functions `fluid_version()` and `fluid_version_str()`

At runtime, you know what version of the library is running _right now_ which is more useful to put in the logs for when bug reports come in from users who might not know what libraries are on their system.

**Comment by johnnovak** [comment] 2023-07-28 22:21
> At runtime, you know what version of the library is running _right now_ which is more useful to put in the logs for when bug reports come in from users who might not know what libraries are on their system.

Agreed. I will do so for FluidSynth at least.

But after some further reading I'm pretty sure FluidSynth implements more MIDI controllers than the SC-55, so a note portamento related MIDI CC event enables portamento for that MIDI channel that sounds wrong and "bendy". On SC-55 and clones that just gets ignored.

Need to confirm, but can't think of any other explanation. The solution will be to filter messages not implemented by the SC-55 out.

**Comment by johnnovak** [comment] 2023-07-29 03:04
Okay, turns out this has been reported to the FluidSynth guys already:
https://github.com/FluidSynth/fluidsynth/issues/705

If they are unwilling to make the portamento range configurable (see my comment https://github.com/FluidSynth/fluidsynth/issues/705#issuecomment-1656527775), then I'll need to do the mapping manually based on the reverse-engineered SC-55 portamento range (it's not documented anywhere, AFAIK). Lucky that I have not one but two SC-55 modules here 😎🤘🏻 (but I assume SCVA implements this correctly too).

**Comment by johnnovak** [comment] 2023-07-30 07:35
@x73rmin8r fixed in the above PR ☝🏻

**Comment by x73rmin8r** [comment] 2023-07-31 01:40
> @x73rmin8r fixed in the above PR ☝🏻

Once again I'm blown away by the complexity that balloons out of looking into seemingly minor bugs, and the depth of understanding you all have of how all this works, both on a software level and a retro hardware level. Really appreciate all the work and expertise that goes into all this.

**Comment by johnnovak** [comment] 2023-08-02 03:46
Fixed in https://github.com/dosbox-staging/dosbox-staging/pull/2705

**Closed by johnnovak** 2023-08-02 03:46 UTC
Labels: bug, midi
