### ISSUE TITLE
Cursor keys disabled in CGA modes

### ISSUE THREAD

**Issue by evertvorster** [dosbox-staging/dosbox-staging#2089] opened 2022-11-25 09:29 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch

### Relevant hardware info

Lenovo E15 Gen 2 AMD

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am using Alleycat to test my configurations. 
I have copied the dosbox-staging.conf in my home directory to the directory where I have alleycat
renamed the dosbox-staging.conf to dosbox.conf
added the following lines to autoexec.bat section of config file:
MOUNT C .
C:
ALLEYCAT

When I run the game like this, with no other changes to the config file, the cursor keys work fine.
 
However, I remember playing this on a monochrome CGA PC. 

When I change the machine type to cga, or cga_mono, the cursor keys on the keyboard no longer works.
The numpad keys still work, though, but I thought it strange that changing the video part of the emulation would affect the keyboard. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. change machine type to cga

### Your configuration

```ini
https://gist.github.com/evertvorster/b4bc86011eded9e40e82e604b2932a8e#file-dosbox-conf
```

### Provide a Log

```text
https://gist.github.com/evertvorster/b4bc86011eded9e40e82e604b2932a8e#file-console_output-txt
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment] 2022-11-25 14:57
First of all, dosbox and by extension dosbox-x uses a rather poor 'machine=` setting to switch between different video adapter emulations. But it does more then just change emulated video adapter, it also changes some other machine settings. Starting with a mda, cga or Hercules machine type will cause it to emulate an early IBM PC in _some_ regards, compared to the default which is to emulate a late DOS PC.

This does effects things like keyboard type, which was changed from the original IBM PC and PC XT and the later IBM AT and PC/2 models.

Having said that, I have played Alley Kat in the past and just tried it, and with `machine=cga` it plays just fine. No issues with cursor keys. So it may be an issue with the version of the game you have.

ps, for the best experience the game can offer, try `machine=pcjr`.

**Comment by rderooy** [comment] 2022-11-25 15:07
Sorry, I messed up with my comment. I started the game from DBGL and it launched the game with dosbox-x and not dosbox-staging.

With dosbox-staging and `machine=cga` it does not work properly. It does work with `machine=pcjr`, but you will get a different experience.

With dosbox-x there, it defaults to an IBM PC/XT keyboard type with `machine=cga`, but not with -staging. And there is no config setting to force the keyboard controller to a IBM PC/XT type which is needed for this game.

**Comment by grapeli** [comment] 2022-11-25 18:53
In dosbox-staging it also worked properly, some time ago. 

The keyboard stopped working properly as of this commit 7dedc3a2.

**Comment by evertvorster** [comment] 2022-11-25 19:33
Wow, you guys are on it! 

It's nice to see such a responsive community. 

I want to re-create the experience of using a IBM-PC 8088 in 1983 with a monochrome amber screen, as this was my introduction into computing when I was just a teen. This is why I tried the cga_mono setting. 
Of course I will play with the other settings as well. As I document the later years of DOS gaming, I am sure to use the later PC emulations as well. 

Thanks for looking into this!

**Comment by kcgen** [comment] 2022-11-25 20:29
Thanks for the quick bisect, @grapeli.

When I look back at that commit Staging, here's how its logic maps to the XT keyboard handling documentation:

(click to open full screen):

![2022-11-25_11-56](https://user-images.githubusercontent.com/1557255/204050107-19d5e883-5814-4630-a459-697c9d661d18.png)

Ref: https://fd.lod.bz/rbil/ports/keyboard/p0060006f.html

Spellicotper is a 1986 game that was developed for the PC XT (the PC AT spec came out later, in 1987). [**:file_folder: spellicopter.zip**](https://github.com/dosbox-staging/dosbox-staging/files/10094894/spellicopter.zip)

Maybe there's a bit more nuance involved in the logic, such as detecting bit 7 as a pulse (perhaps following an: off>on->off pattern, otherwise ignore it?)

The XT keyboard layout doesn't have the four arrow keys:

![IBM_PC_XT_5160](https://user-images.githubusercontent.com/1557255/204052493-d927afe5-1621-4086-9084-5108fdcdcb4a.JPG)

Ref: https://en.wikipedia.org/wiki/IBM_Personal_Computer_XT

Another thought is that, when in XT-mode (machine = CGA / pre-EGA), we could still silently make the arrow keys map over to the numpad arrows.

**Comment by evertvorster** [comment] 2022-11-25 20:42
Wow, that is almost the exact model of PC that I started on, apart from the monitor being monochrome. 
Queue a wave of nostalgia!
As you quite correctly state, the keyboard does not have cursor keys. 

However, it would be nice to silently map the cursor keys to the keypad keys.

**Comment by kcgen** [comment] 2022-11-25 20:48
> However, it would be nice to silently map the cursor keys to the keypad keys.

Will try for it! Thanks for the bug report, @evertvorster.

If Anyone want to help with this, PR's are very welcome!

**Comment by grapeli** [comment] 2022-11-25 22:22
Certainly better is the current state, i.e. Spellicopter game launching and Alley Cat working only with the help of cursors from the numeric keypad.

**Comment by arrowgent** [comment] 2022-11-28 01:52
amazing that alleycat is still a staple testing software for dosbox

just downloaded 0.79.1, installed it, and config -wcd

alley cat works fine.
enables CGA display mode (using default config settings) according to terminal output
and the arrow keys + numpad works without issues
left, right, up, down.  the game seems to operate correctly without issues.

linux x86_64 ubuntu 18.04


_however, if youre specifically setting a machine mode, that might be an issue..._


```
#loadfix to put 64kb conventional memory setting
loadfix
config -set "dosbox machine=svga_s3"
config -set "dosbox memsize=2"
config -set "cpu cycles=1024"
config -set "cpu cputype=386"
mixer spkr 50:50
cd alleycat
cat
cls
loadfix -f
```

**Comment by kcgen** [comment] 2022-11-28 16:18
Also check out TandyCat, a very nice patch by @bjt42.

Here's a zip to try in Staging `main` (I recomment the latest build with it, because it fixes a regression with stuck/dupe key presses in this game, specifically in XT-mode)

[:file_folder: **`tandycat.zip`**](https://github.com/dosbox-staging/dosbox-staging/files/10105559/tandycat.zip)

---

The wonderful AlleyCat jingle really dances on the Tandy 3-voice:

https://user-images.githubusercontent.com/1557255/204327765-22c37472-cde5-4281-95f1-e41ab0849a33.mp4

**Comment by kcgen** [comment] 2022-11-28 17:23
This issue is fixed in `main` (AT-arrow keys work)

**Closed by kcgen** 2022-11-28 17:23 UTC
Labels: bug

**Comment by rderooy** [comment] 2022-11-28 18:23
There is no need for the TandyCat patch. Just run the game with `machine=pcjr` for the same graphics and sound.

**Comment by kcgen** [comment] 2022-11-28 20:12
Great tip, @rderooy ! It was hiding from me in plain sight all these years. Thanks for the tip.
