### ISSUE TITLE
Restart facility is unstable when launched from Windows GUI

### ISSUE THREAD

**Issue by Asterchades** [dosbox-staging/dosbox-staging#3346] opened 2024-01-24 08:33 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1, 0.81-RC1, 0.81-RC2

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 9 3900X, NVidia GeForce RTX 3070, 32GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using the provided Restart feature (default [Ctrl]+[Alt]+[Home]) results in undesirable behaviour should DOSBox Staging be launched directly from the Windows GUI. It does not seem to make any difference whether it is launched directly via the executable or through a shortcut, or whether this is done using the Explorer or the "Run" command.

On the first attempt it presents the following error in the client:

> Illegal command: dosbox.exe
> Preventing an early 'exit' call from terminating.

An accompanying warning in the console indicates:

> SHELL: Exit blocked because program quit after only 0.5 seconds

Any subsequent attempt to Restart will result in client exiting entirely, with the following error in the console (before it also closes):

> ABORT: Restarting failed

Also worth mentioning is that the inclusion of @ symbols or ECHO OFF in the [autoexec] section of the config file can result in the first Restart no longer showing system text, with ECHO OFF having a 100% chance of this occurring. A caret is present, all user-entered text works correctly and the environment itself appears otherwise unaffected, including text-based software (such as the exit screen on many Shareware titles), but no text-based feedback is presented from the DOS environment. This also appears to suppress the Shell warning.

Note that launching from a console (such as Windows Terminal) does _not_ exhibit this (mis)behaviour - including the missing text feedback - and will happily Restart as many times as you care to try. Execution via a batch file also works as expected, even when invoked via the Windows GUI. Both of these must take the current directory into consideration when relative paths are used in the DOSBox config, however.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch DOSBox Staging from the Windows GUI.
2. Trigger the Restart feature ([Ctrl]+[Alt]+[Home]).
3. <optional> Trigger the Restart feature a second time.

### Your configuration

```ini
Configuration used is the default, as generated by the respective versions of DOSBox Staging.
```

### Provide a Log

```text
https://gist.github.com/Asterchades/7c9f0c2e7ae57c40c8c4ab494d6aa4fd
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-01-24 10:58
Thanks for your report. 

For the record, tested this on macOS launching from the GUI, and it works fine there.

Looks like we could improve the Windows situation a bit then 😄

**Comment by weirddan455** [comment] 2024-01-24 13:08
Cannot reproduce the bug in Linux.

**Comment by weirddan455** [comment] 2024-01-24 18:36
Well this is strange.  I can reproduce the bug but for me it is the exact opposite:  Launching by double-clicking the .exe works fine.  Launching by the MSYS2 terminal has the client quit on the 2nd restart attempt (although I see no errors/warnings in the logs).  On Windows 10.

**Comment by weirddan455** [comment] 2024-01-24 21:29
OK, I think I've figured out what's going on.  When we restart, we're calling the function `execvp`.  On POSIX systems, this replaces the current process with the given process.  We're calling it with the same command we were launched with so it effectively reloads the dosbox executable.

Windows support for POSIX functions is often janky, as seen here.  Windows has no native support for replacing the currently running program.  Instead, the implementation does essentially:

```
CreateProcess(); // Create a new Dosbox Process
ExitProcess(0); // Exit the current process
```

This would be fine, except the new child process inherits the console from the parent.  On Windows, if Dosbox was not launched from a console, we create one.  As far as I can tell, the parent is destroying the console when it exits which causes the child to also exit.

A solution that worked for me in testing is to do away with `execv` and call `CreateProcess` directly passing in the `DETACHED_PROCESS` flag.  This causes the child to not inherit the console.  This will cause a new console window to be created for the child.  Might be a little annoying for users launching Dosbox from the console but seems preferable to the alternative.

**Comment by johnnovak** [comment] 2024-01-24 22:20
Nice detective work @weirddan455. I can see opening a new console windows when DOSBox is launched from the console even as a feature and an improvement (as long as the new log windows is closed on DOSBox exit), so I'm not against it. Plus that's a highly niche use case on Windows, I don't think I've ever done that, personally 😄

**Comment by Asterchades** [comment] 2024-01-25 04:52
Tested the fix (via 0.82.0-alpha-81-g0d3c555cb) and can confirm it's working. Have tried both the default configuration and my custom configuration, launched both directly and through a console - two dozen restarts each without so much of a hint of trouble.

One curious observation, however: only the first console appears to be using the correct colours. All subsequent consoles use a medium grey for everything, rather than having the timestamps in a dark grey, warnings in yellow, and errors I assume in red (I cannot reliably trigger one any more).

**Comment by johnnovak** [comment] 2024-01-25 05:00
> One curious observation, however: only the first console appears to be using the correct colours. All subsequent consoles use a medium grey for everything, rather than having the timestamps in a dark grey, warnings in yellow, and errors I assume in red (I cannot reliably trigger one any more).

Yeah, that's not ideal. Any idea perhaps how to improve that @weirddan455 ?

**Comment by weirddan455** [comment] 2024-01-25 13:42
I can see the colors are off now after restart.  I missed that in testing.  I'm looking into it.

**Comment by weirddan455** [comment] 2024-01-25 15:16
Should be fixed by #3351 if you would like to test @Asterchades

**Comment by johnnovak** [comment] 2024-01-25 23:30
> Should be fixed by #3351 if you would like to test @Asterchades

Thanks for jumping on this so quickly and doing a quality fix @weirddan455 🎖️

**Comment by Asterchades** [comment] 2024-01-26 10:09
Can confirm the colours are now working (0.82.0-alpha-84-g3b332d0d0).

But - and I'm really sorry to do this, because I'm a big fan of your work (especially how quickly this keeps being resolved) - it has introduced another change which may not be intentional. The console is now becoming the active window following a Restart, rather than the DOSBox environment.

Initial launch still has the DOSBox environment as the active window. The alpha I previously tested (with the broken colours) also set the DOSBox environment as the active window following a Restart.

**Comment by johnnovak** [comment] 2024-01-26 10:37
> The console is now becoming the active window following a Restart, rather than the DOSBox environment.

Interesting, this must be another Win 11 pecularity. I'm quite sure the DOSBox window stays in focus on Win 10, but I'll tretry later.

**Comment by Asterchades** [comment] 2024-01-26 11:52
I may have found another difference between our setups which could be responsible.

My terminal is set to the Windows Terminal, which is the task that remains active when Restarting with the newer alpha. If I change it back to the Windows Console Host, the DOSBox environment is correctly made the active task. So that could well be why yours is correctly making DOSBox the active window and mine isn't.

It's also a little interesting to watch its behaviour when Windows Terminal is in use, but no existing Windows Terminal window is active. When an existing Windows Terminal is up, a new tab is opened by the Restart which becomes the active task. Without an existing Windows Terminal, a new Terminal is opened by the Restart and the system is left in a strange kind of "task limbo" where no window is currently active.

_As an aside, switching to the Console Host does not alter my Restart behaviour under 0.81.0-RC2. So the way our direct/terminal launch behaviours differed previously is definitely deeper in the OS than that._

My understanding is that the Windows Terminal either will or already has replaced the Console Host as the default terminal in Windows 11. I don't believe this was back-ported to Windows 10, though the option exists to manually change it.

**Comment by weirddan455** [comment] 2024-01-26 16:39
OK, I'll re-open the issue again.  The Dosbox window was staying active for me but I was using the old school "command prompt" on Windows 10.  I'm not on Windows right now to test further.

A possible solution could be to simply call `SDL_RaiseWindow` sometime during init.

**Closed** 2024-01-30 16:08 UTC
Labels: bug, Windows

**Comment by Asterchades** [comment] 2024-01-30 17:25
Can confirm it's working (0.82.0-alpha-87-ga07c4).

No buts this time - just working. And not because I feel bad about the chain reaction here, even if I get that it happens sometimes, rather because there genuinely isn't anything that I can see which is wrong with it.
