### ISSUE TITLE
Emulated Joystick default when Joystick=auto

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3326] opened 2024-01-14 14:40 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using Hardball! (1987) as an example, in ECE if you have no real joystick plugged in and joystick=auto the game will not detect joystick for player control and the mapper will show "disabled" above the joystick controls. If you then set joystick=2axis the game will detect the emulated joystick and joystick 1 will be active in the mapper, as it should.

In Staging 81-RC1 joystick=2axis works as it should, however if you set joystick=auto the game can still see the emulated joystick and offers it for player control.

I think this is a bug as you would only want to opt in to the emulated joystick by setting joystick=2axis\4axis\etc, not have it on all the time unless joystick=disabled

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set joystick=auto in conf
2. Start Hardball!
3. Look at the controls offered for the two players

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment] 2024-01-14 15:32
Confirmed.  This behavior is also a regression from 0.80.1.  In that previous version, Hardball does not detect a joystick when `joystick = auto` is set and there is no joystick plugged in.

I'll dig into this more in a little bit.  I believe the reason we do this is to allow the user to create a "virtual" joystick by mapping joystick keys to other devices such as a mouse and keyboard (by using the mapper accessed by `dosbox -startmapper`).  Perhaps the best solution is to only present a joystick to DOS if the user has such keys mapped or a real joystick is plugged in.

**Comment by weirddan455** [comment] 2024-01-15 12:46
Fixed in #3327

**Closed by weirddan455** 2024-01-15 12:46 UTC
Labels: bug, input handling
