### ISSUE TITLE
DOSBox executing INI section if it's after AUTOEXEC and not an official section

### ISSUE THREAD

**Issue by ZummiGummi** [dosbox-staging/dosbox-staging#3727] opened 2024-06-03 09:05 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If a dosbox.conf file has a section after [AUTOEXEC], then it will run the text in DOSBox.
![Screenshot of error](https://github.com/dosbox-staging/dosbox-staging/assets/3189508/821bfd18-a74d-448b-8438-3917c43105be)
![Screenshot of dosbox conf](https://github.com/dosbox-staging/dosbox-staging/assets/3189508/576d42cc-e1ac-44cd-ad59-edf4335c31f8)
If you put an official section under [AUTOEXEC] then the error doesn't happen.
DOSBox-X doesn't have this problem, didn't test with OG DOSBox.

I would have expected only the text in  [AUTOEXEC] section to be executed?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Edit a dosbox configuration file
2. Add a new section after [AUTOEXEC], e.g. [EXTRA]
3. Run DOSBox calling the configuration file
4. DOSBox will try to run the text in the [EXTRA] section

### Your configuration

```ini
[AUTOEXEC]
MOUNT C .\DRIVES\C
C:
[Extra]
Key=Value
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-06-03 11:29
Well, I'm very hesitant to agree that this is a bug. I'd say the sane behaviour is to execute whatever comes aftes `[autoexec]` as DOS commands. 

So always put the autoexec section last, problem solved.

**Comment by ZummiGummi** [comment] 2024-06-03 19:11
I'm fine with whatever is decided, like you said, it's easy enough to work around, and is a tiny edge case that no one else is likely to run across.

I'll leave it up to the staging project if you want to close this ticket, I only wanted to bring it to your attention in case this was unexpected behavior.

FYI, this setup doesn't generate any visible errors even though there is text after [AUTOEXEC]

![Screenshot of no error](https://github.com/dosbox-staging/dosbox-staging/assets/3189508/1dc8d289-5122-49f7-987e-440eb4a20caf)


```

[AUTOEXEC]
MOUNT C .\DRIVES\C
C:
[SDL]
Key=Value
```



```

2024-06-04 07:00:26.289 | CONFIG: Invalid option 'Key'
2024-06-04 07:00:26.289 | CONFIG: Loaded local config file 'dosbox.conf'
```

Have a great day.

**Comment by johnnovak** [comment] 2024-06-12 03:48
Closing as this is not a bug. I've improved the [autoexec] sections's description in this PR: https://github.com/dosbox-staging/dosbox-staging/pull/3754/commits

**Closed by johnnovak** 2024-06-12 03:48 UTC
Labels: not a bug
