### ISSUE TITLE
[composite] F12 conflict and config "off"

### ISSUE THREAD

**Issue by arrowgent** [dosbox-staging/dosbox-staging#2699] opened 2023-07-23 23:37 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

This package contains a development branch named refs/tags/v0.80.1 with commit 5c9161dc2 of the DOSBox Staging project.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

https://github.com/dosbox-staging/dosbox-staging/blob/5d881591fd9504163a165eb4bacb7a09fa5c1f61/website/docs/downloads/release-notes/0.75.0.md?plain=1#L498

```
[composite]
#   composite: Enable composite mode on start. 'auto' lets the program decide.
#              Note: Fine-tune the settings below (ie: hue) using the composite hotkeys.
#                    Then read the new settings from your console and enter them here.
#              Possible values: auto, on, off.

composite   = off
```

does not disable the button F12

im noticing this because by default, STEAM uses F12 for screenshots.
it also cannot be modified or disabled in the key-mapper (ctrl+f1)
unmapping the binding does not alter the composite CGA switching behavior

it may be rare but there are now games on steam using dosbox-staging by default

two things should be possible:
* binding the button to some other button
* disabling the button via config = off

-------------------------------------------------

running the same game from my dosbox-staging and pressing F12 does nothing.
similar configuration, similar enough.
this may particularly be unique to that GIT commit version

my personal system dosbox-staging is this:
```
dosbox-st --version
dosbox-staging, version 0.80.1
```
no git or anything, it was downloaded from releases.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. open game in ega/tandy mode
2. press F12
3. screen changes to HI/LO CGA colors
4. repeat pressing F12 to cycle
5. attempt CTRL+F1 mapper to remove binding
6. attempt conf file to disable composite = off

### Download URL of affected game or software

https://store.steampowered.com/app/2295210/The_Aching/

### Your configuration

```ini
machine            = tandy
captures           = capture
memsize            = 16
mcb_fault_strategy = deny
vmemsize           = auto
dos_rate           = default
vesa_modes         = compatible
speed_mods         = true
autoexec_section   = join
automount          = true
startup_verbosity  = auto

[composite]
#   composite: Enable composite mode on start. 'auto' lets the program decide.
#              Note: Fine-tune the settings below (ie: hue) using the composite hotkeys.
#                    Then read the new settings from your console and enter them here.
#              Possible values: auto, on, off.

composite   = off

core      = auto
cputype   = 386
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment] 2023-07-24 00:00
further i have tested using the provided `dosbox` setting as:
`dosbox -conf aching.conf` in the game folder

and replacing `dosbox` with my version of `dosbox-staging` downloaded directly from `releases`

the game's dosbox-staging pressing F12 cycles the CGA composite modes
my dosbox-staging does also, if however i run my dosbox-staging from outside of the game folder (./local/games/dosbox-staging/) it does not have the cga composite color cycling


pressing F12 repeatedly does this in the log:

```
2023-07-23 16:58:54.429 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-07-23 16:58:54.433 | DISPLAY: Tandy 320x200 16 color (mode 09h) at 59.923 Hz CFR, scaled to 1440x1080 with 1.2 pixel aspect ratio
2023-07-23 16:58:55.789 | COMPOSITE: State is auto
2023-07-23 16:58:55.840 | DISPLAY: Tandy 640x200 4 color (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:56.128 | COMPOSITE: State is on
2023-07-23 16:58:56.182 | DISPLAY: CGA 1280x400 composite (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:56.376 | COMPOSITE: State is off
2023-07-23 16:58:56.430 | DISPLAY: Tandy 640x200 4 color (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:56.656 | COMPOSITE: State is auto
2023-07-23 16:58:56.904 | COMPOSITE: State is on
2023-07-23 16:58:56.955 | DISPLAY: CGA 1280x400 composite (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:57.070 | COMPOSITE: State is off
2023-07-23 16:58:57.121 | DISPLAY: Tandy 640x200 4 color (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:57.301 | COMPOSITE: State is auto
2023-07-23 16:58:57.555 | COMPOSITE: State is on
2023-07-23 16:58:57.610 | DISPLAY: CGA 1280x400 composite (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:57.716 | COMPOSITE: State is off
2023-07-23 16:58:57.766 | DISPLAY: Tandy 640x200 4 color (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
2023-07-23 16:58:57.910 | COMPOSITE: State is auto
2023-07-23 16:58:58.124 | COMPOSITE: State is on
2023-07-23 16:58:58.176 | DISPLAY: CGA 1280x400 composite (mode 09h) at 59.923 Hz CFR, scaled to 1440x540 with 1.2 pixel aspect ratio
```

**Comment by arrowgent** [comment] 2023-07-24 00:02
ah, i found something


`machine = tandy`
produces the F12 issue,
by default the developers suggested and made availible (the game is designed for a tandy)

where
`machine = svga_s3` and running the game `gorgon -ega`
F12 does nothing as it should do nothing unless enabled

**Comment by johnnovak** [comment] 2023-07-24 01:00
I think you got yourself a bit confused:

- Composite emulation only works with the `pcjr`, `tandy`, and `cga` machine types.
- The default key to toggle composite mode is `F12` and this can be freely remapped, or the mapping can be completely removed. There is _no_ hardcoded defaulting to `F12` that cannot be unmapped.
- Finally, `composite = off` does _not_ disable any composite mode related key mappings. We do not state that anywhere; this setting only controls the _starting mode_ of the composite emulation. This is what the description of the setting says: 

```
composite: Enable composite mode on start ('auto' by default). 'auto' lets the program decide.
```

Let me know if you still think there's an issue. Also, I won't go and buy this game on Steam, so please try to reproduce the issue with some free game demos, or a game from the eXoDOS v5 collection.

Related: I've recently done a quite extensive regression testing session of _all_ composite modes supported by Staging, see this page for details. Maybe pick a game from there and try to reproduce your problem.

https://github.com/dosbox-staging/dosbox-staging/wiki/Composite-mode-test-cases

**Comment by johnnovak** [comment] 2023-07-24 02:10
> the game's dosbox-staging pressing F12 cycles the CGA composite modes
> my dosbox-staging does also, if however i run my dosbox-staging from outside of the game folder (./local/games/dosbox-staging/) it does not have the cga composite color cycling

Btw, I think you're probably having problems with loading your mapperfile too. By default, the mapperfile has a release-specific name. E.g. this is what I've got in the current dev build by default:

```
mapperfile          = mapper-sdl2-0.81.0-alpha.map
```

If the mapperfile can be found in the working directory, you get this in the logs (probably you can use absolute paths too if you really want to do that):

```
2023-07-24 12:05:21.206 | MAPPER: Loaded 152 key bindings from 'mapper-sdl2-0.81.0-alpha.map'
```

If if cannot be found, you get an error:

<img width="1152" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/62d59215-e51e-402d-b164-aeebba1634bc">

The current working directory is the directory you started DOSBox Staging from, unless you override it with the `-working-dir` command line option.

So make sure when you remap the F12 key, your mappings get saved and loaded correctly. The name of the mapper file might be different between the DOSBox version bundled with Steam and your other version, but you can fix this by setting the `mapperfile` setting to a name of your choosing.

**Comment by johnnovak** [comment] 2023-07-27 02:29
Can you reflect on the above @arrowgent? It would be good to know if this helped you resolve the issue, or if you still thing something is wrong.

**Comment by johnnovak** [comment] 2023-07-28 21:44
Closing as cannot reproduce and the OP does not provide accurate repro details (linking to paid Steam games does not count).

I think the feature works as it should; the complications come from not understanding the feature and perhaphs from the Steam client overriding some keymappings or something.

Will reopen if OP can prove with an example I can reproduce that something is wrong.

**Closed by johnnovak** 2023-07-28 21:44 UTC
Labels: notabug
