### ISSUE TITLE
Windows 3.11 with S3 Trio64V 1.70.04 1024x768 64k LF failed to render text

### ISSUE THREAD

**Issue by runlevel5** [dosbox-staging/dosbox-staging#2846] opened 2023-09-08 09:05 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

Linux ppc64le and `core=dynamic`

### Relevant hardware info

Raptor Computing System Blackbird Workstation, IBM POWER9 Sforza 8core (02CY649)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Windows 3.11 does not render and text. This issue only occur with S3 Trio64V driver.

This issue ONLY impact `core=dynamic`. The `core=normal` works fine

### Steps to reproduce the behaviour.

Explain how to reproduce

1. `dosbox --set core=dynamic --noprimaryconf`
2. Install Windows 3.11
3. Install S3 Trio64V 1.70.04 driver
4. Restart Windows 3.11

![Screenshot from 2023-09-08 18-59-11](https://github.com/dosbox-staging/dosbox-staging/assets/135605/da9bfb6b-b9b2-45bd-890b-50b3715f6a01)

### Your configuration

```ini
core=dynamic
```

### Provide a Log

```text
023-09-08 18:58:59.150 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1067x800 with 1:1.35 (20:27) pixel aspect ratio
2023-09-08 18:59:00.194 | RENDER: Auto-switched to shader 'interpolation/sharp'
2023-09-08 18:59:00.194 | VGA: Forcing single-scanning of double-scanned VGA video modes
2023-09-08 18:59:00.194 | VGA: Forcing no pixel-doubling
2023-09-08 18:59:00.200 | DISPLAY: VESA 1024x768 16-bit high colour graphics mode 117h at 69.392 Hz throttled VFR, scaled to 1067x800 with 1:1 (1:1) pixel aspect ratio
2023-09-08 18:59:00.286 | XGA: Unhandled multifunction command 0xffffa
2023-09-08 18:59:00.494 | XGA: Unhandled multifunction command 0xffffa
2023-09-08 18:59:00.494 | XGA: Unhandled multifunction command 0xffffa
2023-09-08 18:59:00.495 | XGA: Unhandled multifunction command 0xffffa
2023-09-08 18:59:00.499 | XGA: Unhandled multifunction command 0xffffa
2023-09-08 18:59:00.500 | XGA: unsupported drawwait operation
2023-09-08 18:59:00.500 | XGA: unsupported drawwait operation
...
```
```


### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2023-09-08 09:17
Do you specifically need the S3 Trio64V for some program? Win 3.11 works perfectly fine with the S3 Vision 964 drivers. Technically, if we have a single driver that works with all apps and games that sufficient.

See further details here:
https://github.com/dosbox-staging/dosbox-staging/wiki/Windows-3.1x

This could be an endianness bug, though. Maybe you could the Vision 964 driver as well. 

Possible duplicate of https://github.com/dosbox-staging/dosbox-staging/issues/2767

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/36767b15-eba8-4d95-8257-ea9a66087366">

**Comment by runlevel5** [comment] 2023-09-08 11:50
@johnnovak the S3 964 driver also yield same issue

![Screenshot from 2023-09-08 21-48-39](https://github.com/dosbox-staging/dosbox-staging/assets/135605/12203a85-5cb6-4838-8a18-4aa6414611a5)

**Comment by runlevel5** [comment] 2023-09-08 11:50
> @johnnovak This could be an endianness bug

Could you please further details on this bug? Many thanks

**Comment by johnnovak** [comment] 2023-09-08 12:35
> > @johnnovak This could be an endianness bug
> 
> Could you please further details on this bug? Many thanks

I mean, something could be broken on big endian that the VGA code path on Win 3.x uses. I'm not aware of anything more specific, but quite likely it's because you're running on a PPC.

**Comment by rderooy** [comment] 2023-09-08 12:54
DOSBox Staging (current git) running WFW 3.11 with S3 Trio64V 1.70.04 drivers on Linux x86_64:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/e8967da1-a1b9-434d-9847-ec872d785821)

**Comment by runlevel5** [comment] 2023-09-08 13:24
> I mean, something could be broken on big endian that the VGA code path on Win 3.x uses. I'm not aware of anything more
@johnnovak I am running PowerPC64 Little Endian which is pretty much the same to that of x86 so I don't think it is of endianess

@rderooy thanks for the verification, I guess this bug might only happen with Linux ppc64le then

**Comment by kcgen** [comment] 2023-09-08 16:14
@runlevel5 : can you confirm you're running S3 Trio64V 1.70.04 ?

**Comment by kcgen** [comment] 2023-09-08 16:21
@runlevel5 , can you try this self-contained pack to double-check?

[wfw-base-800x600.tar.gz :file_folder: ](https://github.com/dosbox-staging/dosbox-staging/files/12561876/wfw-base-800x600.tar.gz)

``` shell
cd wfw-base-800x600
/path/to/dosbox-staging-executable --noprimaryconf
```

**Comment by runlevel5** [comment] 2023-09-08 23:15
@kcgen same results unfortunately

**Comment by kcgen** [comment] 2023-09-09 00:03
Same thing with the normal core?

**Comment by johnnovak** [comment] 2023-09-09 01:36
Given how few people are on PPC, don't hold your breah @runlevel5 ... but patches are always welcome 😄

**Comment by runlevel5** [comment] 2023-09-09 01:37
@classilla wondering if you could help verify if this issue also occurs on your machine? Many thanks

**Comment by kcgen** [comment] 2023-09-09 01:49
@classilla : the thread to pull on is revealed in @runlevel5's logs:

```
XGA: Unhandled multifunction command 0xffffa
```

The DOS instruction stream is fed through the dyncore and become actions for the DOSBox to process, some of which we can see become XGA I/O port writes.

The XGA calls are (emulated) line drawing routines to draw fonts, which is exact what is missing. 

WIth the normal core, you won't these 'unknown command's warnings logged. So my guess is something is slightly off in the dynamic core leading to some garbage content being part of the XGA writes.

The src/hardware/vga_xga.cpp has a command trace feature, if you set:

```c++
#define XGA_SHOW_COMMAND_TRACE 0
```

Suggest turning that on and compare the normal and dynrec cores. 

Maybe some memory isn't being zeroed out? Or 16 or 32bit IO call values are off-by-one (or something like that).

Good luck!

**Comment by johnnovak** [comment] 2023-09-09 01:54
That's some nice extra info @kcgen 🎉 If you can figure this out @runlevel5 , maybe it would increase the overall robustness of the dynamic core even for LE platforms.

**Comment by classilla** [comment] 2023-09-09 04:49
If there's an image around with this I can just "try," it would be helpful (otherwise I need to sit down and install WfW which is not something I usually do in DOSBox).

**Comment by kcgen** [comment] 2023-09-09 05:12
Yup, I provided one a handful of comments before this on; Ctrl+F for `gz` to find it.

**Comment by classilla** [comment] 2023-09-09 16:37
It looked like a sign extension bug and it was, in the code loading 16-bit immediates. This also affects the 32-bit PPC version and the fix is probably the same. PR coming up.

![Screenshot_20230909_093634](https://github.com/dosbox-staging/dosbox-staging/assets/12717725/b4d8a1f4-8fd1-4bdf-9798-9724535c70c4)

**Comment by casey-ac** [comment] 2023-12-22 21:12
Could you please apply this revert to /src/cpu/core_dynrec/risc_ppc.h as well? I verified the same text rendering issue occurs with big endian PowerPC, and applying the revert to risc_ppc.h fixes the issue.

**Comment by kcgen** [comment] 2023-12-22 21:28
@casey-ac , can you attach your proven-good risc_ppc.h reverted file here?

**Comment by Grounded0** [comment] 2024-01-01 03:17
Reopening until fixed for `PPC64` target.

**Comment by Grounded0** [comment] 2024-01-03 22:05
@casey-ac 

Can you attach your proven-good risc_ppc.h reverted file here?

**Comment by kcgen** [comment] 2024-01-03 22:35
Tagging w/ 0.81 backports (this only touches the 32-bit PPC dynrec core, and we definitely want win3.1 fonts rendering correctly on this platform).

**Comment by kcgen** [comment] 2024-01-03 23:27
@casey-ac , @classilla : I see the original PPCle64 commit https://github.com/dosbox-staging/dosbox-staging/pull/2850/commits/126adf0cb8b14731b7cc40cf7d1a143282b1b96a which was reverted: https://github.com/dosbox-staging/dosbox-staging/commit/1d301ebaf2d693c88f1a893cd79767ee9fafadb8

This commit was never applied to the 32-bit PPC core in the first place, so there's no need to revert it.  You can see the current version here: https://raw.githubusercontent.com/dosbox-staging/dosbox-staging/main/src/cpu/core_dynrec/risc_ppc.h

Where you can see the function:
```c++
// move a 16bit constant value into dest_reg
// the upper 16bit of the destination register may be destroyed
static void gen_mov_word_to_reg_imm(HostReg dest_reg,uint16_t imm)
{
        IMM_OP(14, dest_reg, 0, imm); // li dest,imm
}
```

@casey-ac - can you double check that `main` currently works OK without any changes (or reverts) on your 32-bit PPC? Thanks!

**Comment by classilla** [comment] 2024-01-03 23:42
Why was it reverted? That tested good on ppc64le, and wouldn't affect anything else.

**Comment by kcgen** [comment] 2024-01-03 23:59
> Why was it reverted? That tested good on ppc64le, and wouldn't affect anything else.

Good news; I was wrong and this wasn't reverted on `main`; it was only reverted on a branch: https://github.com/dosbox-staging/dosbox-staging/compare/jn/adaptive-shader-fixes

So I suspect what @casey-ac wan'ts is your sign extension also applied to 32-bit PPC :smile:

**Comment by classilla** [comment] 2024-01-04 00:28
Whew, OK. The exact same change should be right for ppc32 but I'd like confirmation from someone running that build; I don't have easy access to a Power Mac at the moment.

**Comment by Grounded0** [comment] 2024-01-04 00:44
Closing once confirmed by @kcgen to work on PowerBook G4 correctly.

**Closed** 2024-01-04 01:29 UTC
Labels: bug, backport, non-x86, video, Windows 3.x

**Comment by casey-ac** [comment] 2024-01-05 01:54
Apologies for the delay, I've been away for the holidays. I've attached the risc_ppc.h file that corrected the font issue for me (appended ".txt" so I could upload) but it appears the commit was made yesterday, so it appears to all be worked out. I'll build main again to validate. Thanks! 
[risc_ppc.h.txt](https://github.com/dosbox-staging/dosbox-staging/files/13837011/risc_ppc.h.txt)
