### ISSUE TITLE
Host refresh framerate

### ISSUE THREAD

**Issue by vanfanel** [dosbox-staging/dosbox-staging#953] opened 2021-03-21 16:16 UTC
**Is your feature request related to a problem? Please describe.**
In DOS games that are ~60Hz (Mode-X games like Jazz JackRabbit, SuperFrog, Pinball Dreams, etc) there's a framerate hiccup every few seconds due to the missmatch between the emulated VGA framerate and the host framerate.

**Describe the solution you'd like**
A config parameter to specify the refresh rate of the emulated VGA graphics. It could simply be called `"refresh_rate ="`, setting it to "auto" would use the default refresh rate and setting it to "host" would use the host's refresh rate.
The host refresh rate can be detected by https://wiki.libsdl.org/SDL_GetCurrentDisplayMode (but it could be a little off, RetroArch for example uses a framerate detection routine based on sampling vblank periods).

**Additional context**
As an additional clue, I do my own builds where I set my own refresh rate in `src/hardware/vga_draw.cpp` by changing:
`fps=(double)clock/(vtotal*htotal);`
to:
`fps=<refresh rate for my default video mode>;`

This would also vastly improve demos, etc.
And this is exactly the kind of improvement that would fit into dosbox-staging scope, I believe :)

**Comment by kcgen** [comment] 2021-03-22 03:45
> In DOS games that are ~60Hz (Mode-X games like Jazz JackRabbit, SuperFrog, Pinball Dreams, etc) there's a framerate hiccup  every few seconds

Is there an objective or "mechanical" way to detect this?

On my 60 Hz host display, Jazz JackRabbit _appears_ to have zero frame judder. That is, I can run to the left and right, and get, what I perceive to be, perfectly fluid scrolling including the full background scene.

My understanding is that `src/hardware/vga_draw.cpp` emulates the DOS-side video mode's refresh rate (which was assumed to drive an analog CRT), which some games use to pace the game time.  

This is separate from the rendering out to the host via SDL2, which takes place up in the `Normal_Loop` in `src/dosbox.cpp` when `GFX_Events` is called:

```
static Bitu Normal_Loop(void) {
        while (1) { ... 
                        if (!GFX_Events())
```

Let's say you  - what if you have a DOS game that sets a 60 Hz "VGA" mode, but the host's display is running at 144 Hz (G-sync). Would setting `fps=144` in the `vga_draw.cpp` code produce acceptable results?

Perhaps we should pace `GFX_Events()` against the host's refresh rate, and leave emulated DOS-side refresh rate as-is?  Maybe making them 1:1 (or 2:1 or 1:2) is preferable to avoid partial frames?

**Comment by kcgen** [comment] 2021-03-22 04:58
All of that to say.. I think we need some measurements of gaming timing and frame hickups, with and without this change, to understand if it's a pure win-win or if there's some win-lose trade-offs. 

We could then run these measurements on Windows, macOS, and Linux with the various rendering backends and further see how it plays out.

**Comment by dreamer** [comment] 2021-03-22 14:52
I think we cannot provide an option giving users the ability to override emulated VGA refresh rate this way - it will mess up the games themselves, and overriding this timing will definitely break demoscene productions (they tend to switch between resolutions and refresh rates frequently). *But it's only my opinion and it's not set in stone* ;) - there might be very good reasons for implementing this (thinking of problem with Big Red Racing right now: #521).

Personally I would throw this issue into a big pile of reasons why we need to rewrite the GFX pipeline, together with some OpenGL issues, OpenGLES support, multithreaded window events, VSYNC issues and a bunch of other problems - they all have the same root cause: code in `sdlmain.cpp` was not designed properly, it just grew and grew over the years.

**Comment by kcgen** [comment] 2021-03-22 15:19
Couldn't agree more on your last paragraph @dreamer.

Currently the `while(1) .. GFX_Events()` loop can firehose SDL with a frame every 1ms, leaving SDL or the video driver to deal with the excess.

It will be ideal if we can let the emulated DOS back-end operate at its prescribed cycle-rate (and expected mode/Hz rate), keeping a queue full of roughly the latest two frames, while SDL runs in a thread paced on the hosts vsync rate - and peels off frames from the queue. 

Maybe by then, we'll have 1st-class Vulkan support across the platforms too (MoltenVK on macOS).

**Comment by kcgen** [comment] 2021-09-20 04:12
VESA refresh rates greater than 70hz are now updated to match the host. Refresh rates below 70 hz did not help (even on the Pi, and when matched to the host video rate - such as 60 hz).  Rates below 60 Hz caused flickering in some games. Closing this for now.

**Comment by vanfanel** [comment] 2021-09-20 08:00
@kcgen I don't fully understand. Are you saying that refresh rates over 70Hz are now forced into host refresh rate? (which is an AWESOME thing to do if that's the case! great idea!)

And what happens with DOS video modes near-60Hz? Why can't you also force them into host refresh rate?

**Comment by kcgen** [comment] 2021-09-20 14:27
> refresh rates over 70Hz are now forced into host refresh rate? (which is an AWESOME thing to do if that's the case! great idea!)

Sorry for the lack of detail; it's a bit of the opposite - however, I believe the end-goal is achieve. 

VESA was unique in that its refresh rate could be customized (versus other video modes that /tell/ the CRT to operate at a given rate).  We default to using a 70 Hz VESA rate - however if SDL tells us the host display is operating at a rate greater than 70, then we "upgrade" the VESA rate to match the host. 

Non-VESA modes are left as-is.

A version did have a version that allowed either DOS or the host to fully drive the refresh rates.  For example, in dos-priority mode, it's refresh rate is requested in SDL when going to fullscreen. Where as host-priority mode took the display's rate and forced that inbound as the VESA rate as well as the clock and FPS rates for non-VESA modes.

Back-and-fourth tests on all platforms (Windows, macOS laptop, macOS + HDMI display, Linux x64 desktop w/ 4k and 1080p displays, Linux + Pi and HDMI displays) didn't turn up any cases were things improved - tearing was not changed, perceived smoothness didn't change, .. so it was scrapped. 

> And what happens with DOS video modes near-60Hz? Why can't you also force them into host refresh rate?

Indeed I noticed these operate at usually inexact values (59.x, 60.x, ..) but never perfect integers that SDL2 prefers to operate at.  Add logic that "snaps" the internal DOS clock and FPS to the host-rate (if they're within a thin-percent of eachother) is certainly doable. 

I know you've been doing this a while. Which games and conf settings show an obvious before/after benefit? - so others can do some side by side comparisons?

**Comment by kcgen** [comment] 2021-09-22 02:13
@vanfanel , when you have a chance to answer that last question above, it will help me test/compare before and after. Thank you 👍

**Comment by vanfanel** [comment] 2021-09-22 07:55
@kcgen Yes, sorry for taking so long.

To get perfect scrolling in these cases, both refresh rates must match to some decimals: for example, if the host refresh rate is 60.01862, the internal VGA refresh rate must be exactly 60.01862 too.

I have a couple of games I used to test for correct scrolling in near-60Hz emulated video modes:

-SuperFrog (Team17): Find a large scrolling area where you can move the character for a long time left/right on an horizontal surface, and pay attention to hiccups. If the internal (emulated) refresh rate and the host refresh rate match exactly, there won't be any hiccups.
This game doesn't need anything special con the .conf file, but give it a fixed 15000 cycles CPU.

-Jack Jazzrabbit: in-game it runs at near-60Hz video mode (the same that SuperFrog uses) but it needs 20000 cycles to get perfect scrolling when refresh rates match.
It can be tested on the same way: you need to find an area with a large scrolling space.

I hope it helps. I used to modify the DOSBOX sources so it allowed me to manually specify a refresh rate, so I know it's perfectly possible.

**Comment by vanfanel** [comment] 2021-09-24 10:43
@kcgen Needless to say, I will be building and testing any commits related to this, since I am VERY sensitive to emulated/physical refresh rate discrepancies.

Also having a DOSBOX version with refresh rate control so emulated/physical refresh rates can optionally be forced to match, has been a dream of mine for years.

**Comment by vanfanel** [comment] 2021-12-03 15:34
@kcgen Are there any news on this? You seemed interesting on information about this.
Maybe you implemented a similar solution to the host/emulated refresh rate mismatch problem?

**Comment by kcgen** [comment] 2021-12-03 15:40
Yes, I've been working on something to address this on a branch (under the GTA issue and branch), butI'm  clearing out some long standing work in the near term. I want to get this resolved before 0.78 goes out, to prevent that work from eventually being lost to time and overrun with the problem-de-jour.

**Comment by vanfanel** [comment] 2021-12-03 15:47
Which branch should I build to test this? There are several GTA-related branches.

**Comment by kcgen** [comment] 2021-12-03 15:50
Thanks @vanfanel - nothing worth testing or working right now - but when it's ready, I will let you know!

**Comment by vanfanel** [comment] 2021-12-03 15:55
Ok! I will be ready! :)

**Closed** 2022-03-30 07:10 UTC
Labels: enhancement
