### ISSUE TITLE
[BUG] ANSI Text Not Displaying Correctly in Latest Dev Build

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3027] opened 2023-10-18 18:59 UTC
Here's what I get in the latest dev build v0.81.0-alpha-1793:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/e1c1c9f8-328f-429a-b6c3-e063945aa8e5)

Here's what I get in 0.80.1 (how it's supposed to look): 
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/842bb883-5098-4930-9541-eae6ef5cd402)

Here's my config files, `dosboxTR.conf` for settings, `dosboxTR_single.conf` for the ANSI menu:
[TR ANSI BUG CONF.zip](https://github.com/dosbox-staging/dosbox-staging/files/13032780/TR.ANSI.BUG.CONF.zip)

**Comment by FeralChild64** [comment] 2023-10-18 19:44
I don’t have access to my PC at the moment, but most likely your configuration file is encoded as codepage 437, while DOSBox Staging now expects UTF-8.

**Comment by OpenRift412** [comment] 2023-10-18 19:50
> I don’t have access to my PC at the moment, but most likely your configuration file is encoded as codepage 437, while DOSBox Staging now expects UTF-8.

Well that creates a big problem for anyone who wants to update the version of DOSBox included with their GOG games, because a LOT of them use that style of menu for selecting options.

Also converting `dosboxTR_single.conf` from ANSI to UTF-8 via Notepad++ just does this:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/98fb73b3-4822-4db2-9f50-c88666e62c21)

**Comment by FeralChild64** [comment] 2023-10-18 20:09
Do you have any suggestions?

Having the configuration file in DOS codepage is very problematic, as we do not have information which codepage it is encoded with, as a result we do not really know how to display it within DOSBox. Moreover, modern text editors usually do not support various encodings like Mazovia (popular in Poland in the 80s), Kamenický (used in Czechia or Slovakia), MIK encoding (was a standard one in Bulgaria), ABNT (was often used in Brazil or Portugal), CWI-2 (was used in Hungary), etc.

Does Notepad++ at least display the configuration file properly?

**Comment by weirddan455** [comment] 2023-10-18 20:14
I can confirm it's an encoding issue.

```
$ file dosboxTR_single.conf 
dosboxTR_single.conf: ISO-8859 text, with CRLF line terminators, with escape sequences
```

Dosbox logs the following:

```
2023-10-18 15:00:59.009 | UNICODE: No fallback mapping for code point 0x0240
2023-10-18 15:00:59.009 | UNICODE: No fallback mapping for code point 0x037b
2023-10-18 15:00:59.009 | UNICODE: No fallback mapping for code point 0x0200
2023-10-18 15:00:59.009 | UNICODE: No fallback mapping for code point 0x037c
```

Kwrite displays it mostly correctly, though it doesn't quite know what to do with the non-printable characters:

![encoding](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/8a5f1c7c-9553-4a5c-ba53-893bce078a83)

**Comment by OpenRift412** [comment] 2023-10-18 20:40
> Do you have any suggestions?
I don't really know what changed to make this happen, so I can't really say, sadly.

> Does Notepad++ at least display the configuration file properly?
It displays it exactly how it does for @weirddan455.

**Comment by johnnovak** [comment] 2023-10-18 20:54
This is a hard choice, but I'd rather break the GOG batch files and put the onus to move to UTF-8 on them. That's the only forward-looking solution.

Or maybe some weird hack to detect GOG menus... ugh 😩

**Comment by OpenRift412** [comment] 2023-10-18 21:06
> This is a hard choice, but I'd rather break the GOG batch files and put the onus to move to UTF-8 on them. That's the only forward-looking solution.
> 
> Or maybe some weird hack to detect GOG menus... ugh 😩

Honestly I would implore you to reconsider, because when you think about the userbase of DOSBox Staging, most of them are people that get their DOS games from GOG. I think at that point you have to consider the importance of legacy support, because this also seems to break special characters in batch files, as well, as you can see here:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/e75a4b9c-a0fc-406c-8924-198f63178613)

**Comment by johnnovak** [comment] 2023-10-18 21:21
We could introduce an option for this, of coursr; problem is, GOG will only fix this on their side if they get some heat from the users. I fully get your frustration though; I'm just thinking more strategically 😄 I don't wanna cause problems for the existing userbase, but I'd prefer to improve things going forward too. The thing is, if we defaulted to whatever encoding GOG is using, that will guarantee they will never update their configs with UTF-8 encodings...

I guess one acceptable solution would be to introduce and option to set the codepage of batch files that you could manually set for GOG games to work correctly. But be aware that would break every other use case...

**Comment by johnnovak** [comment] 2023-10-18 21:27
On the other hand, and I'm playing the devil's advocate now: this is a minor aesthetic glitch, the games and the launcher menu are still perfectly usable. Hardly a deal-breaker. Then GOG can choose to use Staging and/or improve the appearance of their menus due to user pressure if they feel like to.

**Comment by weirddan455** [comment] 2023-10-18 21:27
Trying to run this as a batch file gives lots of errors like this in the log:

```
Encountered non-standard character: Dec 4294967245 and Hex 0xffffffcd
```

I would like to see specific examples of broken config files from GOG or broken .bat files from real DOS games though.  That would be what would impact most users and I would like a concrete example of a compatibility break there.  I assume this config file you presented is something you wrote yourself @OpenRift412 

As far as .bat files go, I assume we do need compatibility with codepage 427 as unicode was not a thing back in DOS days.

I don't know, I am not all that familiar with text encoding.  `git blame` shows that @FeralChild64 wrote the entire `src/misc/unicode.cpp` file so maybe you can enlighten us on what exactly changed when you introduced Unicode support?  Or link to the PR?

**Comment by Kappa971** [comment] 2023-10-18 21:35
I think you can use translator tools and edit normalize.bat/sh scripts to convert gog .conf files from 437 to UTF-8.

**Comment by OpenRift412** [comment] 2023-10-18 21:38
> I would like to see specific examples of broken config files from GOG or broken .bat files from real DOS games though. That would be what would impact most users and I would like a concrete example of a compatibility break there. I assume this config file you presented is something you wrote yourself @OpenRift412

The one I customized for Tomb Raider was based on the ones GOG typically includes.

Here's an unmodified conf file from the GOG version of Hocus Pocus (inside the ZIP): [dosbox_hp_single.zip](https://github.com/dosbox-staging/dosbox-staging/files/13034303/dosbox_hp_single.zip)
Same result:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/9bf59e46-c428-4149-95fc-11b998da6acc)

> As far as .bat files go, I assume we do need compatibility with code page 437 as Unicode was not a thing back in DOS days.

Agreed, 100%.

**Comment by OpenRift412** [comment] 2023-10-18 21:42
> On the other hand, and I'm playing the devil's advocate now: this is a minor aesthetic glitch, the games and the launcher menu are still perfectly usable. Hardly a deal-breaker. Then GOG can choose to use Staging and/or improve the appearance of their menus due to user pressure if they feel like to.

I'm highly doubtful that they'll do that because they just expect people to use the use the decade old version of DOSBox that they package with their games. Not to mention having to possible require publisher approval for such things.

**Comment by OpenRift412** [comment] 2023-10-18 21:44
> I guess one acceptable solution would be to introduce and option to set the codepage of conf files that you could manually set for GOG games to work correctly. But be aware that would break every other use case...

What other user cases would require conf files to be in UTF-8 format? Like what does it offer over ANSI/Code page 437?

**Comment by FeralChild64** [comment] 2023-10-18 21:46
If DOS *.BAT files are interpreted as Unicode, that this is clearly a bug. The Z:\AUTOEXEC.BAT file should always be the same encoding as set by the internal KEYB command - it is being converted automatically.

The unicode.cpp is a general purpose Unicode (currently only UTF-8) <-> DOS code page converter, written by me to support all the 100 code pages FreeDOS CPI files (used by DOSBox for screen fonts) support. The most important use case is handling UTF-8 translation files, so that no matter what code page is set (some languages have two or more incompatible encodings), but there are others:
- displaying host mouse device names when mapping the mice
- generating Z:\AUTOEXEC.BAT file from [autoexec] sections
- writing translated dosbox-staging.conf configuration files
- (in my work-in-progress EDIT.COM replacement) for clipboard sharing with host OS
Hopefully someday it will allow to implement national character support in file names.

The implementation was done across many pull requests, changes were done in many places.

**Comment by johnnovak** [comment] 2023-10-18 21:49
> > I guess one acceptable solution would be to introduce and option to set the codepage of conf files that you could manually set for GOG games to work correctly. But be aware that would break every other use case...
> 
> What other user cases would require conf files to be in UTF-8 format? Like what does it offer over ANSI/Code page 437?

Code page 437 is ONE possible DOS era encoding. There are dozens of others. We simply cannot assume CP 437 in a correct implementation.

**Comment by johnnovak** [comment] 2023-10-18 21:54
> > On the other hand, and I'm playing the devil's advocate now: this is a minor aesthetic glitch, the games and the launcher menu are still perfectly usable. Hardly a deal-breaker. Then GOG can choose to use Staging and/or improve the appearance of their menus due to user pressure if they feel like to.
> 
> I'm highly doubtful that they'll do that because they just expect people to use the use the decade old version of DOSBox that they package with their games. Not to mention having to possibly require publisher approval for such things.

No, they push updates all the time. They probably already have the publisher's approval to modify the games as they see fit, besides, changing the DOSBox config has nothing to do with changing the game executable or data. Completely separate issues

**Comment by johnnovak** [comment] 2023-10-18 21:56
> Here's an unmodified conf file from the GOG version of Hocus Pocus (inside the ZIP): [dosbox_hp_single.zip](https://github.com/dosbox-staging/dosbox-staging/files/13034303/dosbox_hp_single.zip)

Perfectly readable and usable too 😄

**Comment by weirddan455** [comment] 2023-10-18 22:00
>  What other user cases would require conf files to be in UTF-8 format? Like what does it offer over ANSI/Code page 437?

I know enough to answer that question.  The dosbox.conf file links to file paths on the host system.  The paths can contain characters that are not representable in ANSI (mostly for non-English language users) since modern operating systems use Unicode.  Everyone except Windows uses UTF-8.  Windows uses UTF-16 but UTF-8 -> UTF-16 is a fairly easy conversion on the back end if needed.

If we stuck with ANSI and someone wants to (for example) set their MT32 ROM folder to `/home/<insert European accent or Asian character>/mt32`, they would be out of luck.

**Comment by johnnovak** [comment] 2023-10-18 22:03
My memory is hazy, but I think that was one of the main driving forces behind this, to be able to handle all host paths correctly. If the worst thing that can happen here is indeed just the wrong table drawing chars appearing in some fancy DOS menus, correct path handling trumps this aesthetic glitch.

**Comment by OpenRift412** [comment] 2023-10-18 22:13
> > What other user cases would require conf files to be in UTF-8 format? Like what does it offer over ANSI/Code page 437?
> 
> I know enough to answer that question. The dosbox.conf file links to file paths on the host system. The paths can contain characters that are not representable in ANSI (mostly for non-English language users) since modern operating systems use Unicode. Everyone except Windows uses UTF-8. Windows uses UTF-16 but UTF-8 -> UTF-16 is a fairly easy conversion on the back end if needed.
> 
> If we stuck with ANSI and someone wants to (for example) set their MT32 ROM folder to `/home/<insert European accent or Asian character>/mt32`, they would be out of luck.

So this was done for compatibility with other languages and platforms then?

Actually, this does give me an idea. Maybe we could have it so Staging could check the system language and determine how the formats are read based on that? Not entirely sure how doable that would be, but I think that could be a decent enough solution.

**Comment by weirddan455** [comment] 2023-10-18 22:18
Well, the easiest way would be to just scan the .conf file before parsing it and determine what encoding is.  @FeralChild64 indicated this may be problematic with certain encodings:

>  Having the configuration file in DOS codepage is very problematic, as we do not have information which codepage it is encoded with, as a result we do not really know how to display it within DOSBox. Moreover, modern text editors usually do not support various encodings like Mazovia (popular in Poland in the 80s), Kamenický (used in Czechia or Slovakia), MIK encoding (was a standard one in Bulgaria), ABNT (was often used in Brazil or Portugal), CWI-2 (was used in Hungary), etc.

Maybe we don't need to support all those different encodings those.  Just English ANSI for backwards comparability and UTF-8.  I don't know how much of a maintenance burden this would be or if anyone on the team is willing to do this.  Just throwing out ideas.

**Comment by Kappa971** [comment] 2023-10-18 22:18
Even converting GOG configuration files from 437 to UTF-8, the characters **╔ ═ ║ ╗ ╚ ╝** are not displayed.

**Comment by FeralChild64** [comment] 2023-10-18 22:30
@OpenRift412 

1. You mean host language, or guest (DOSBox) language?
2. In case of languages with more than one encoding, which one should we assume?
3. How about people who want to keep DOS in English, but supporting their national characters and using their national number format- because this is what they remember from their childhood?

etc.

Keep in mind, that point 2. is very common:
- in the early days of PCs, enthusiasts / educational institutions / government organization developed a standard to store national characters; sometimes there were few competing standards
- such a standard was in widespread use, could even get accepted as a formal standard
- after few years Microsoft provided their own standard (like 852), totally incompatible with the one already in use
- sometimes the standard from Microsoft was accepted quickly (like in Poland, where it replaced Mazovia), sometimes not (like in Czech Republic, where Kamenicky encoding survived for a really long time)

There is no simple and reliable way to guess the encoding.

**Comment by weirddan455** [comment] 2023-10-18 22:37
@Kappa971 That is a good observation.  Those glyphs also are not printing when I was running that menu as a .bat file.  At least part of the issue may be unrelated to Unicode.  I'll do a bisect later and see if there's anything in batch file handling (unrelated to the UTF-8 conf file change) that regressed since 0.80.1.

**Comment by OpenRift412** [comment] 2023-10-18 22:52
> 1. You mean host language, or guest (DOSBox) language?

I was thinking the host/OS language. 

> 2. In case of languages with more than one encoding, which one should we assume?
> 3. How about people who want to keep DOS in English, but supporting their national characters and using their national number format- because this is what they remember from their childhood?

What I'm suggesting is that for users that have their OS set to English or languages that work within ANSI will use that standard, and then languages that don't will use UTF-8. Would that be feasible?

**Comment by FeralChild64** [comment] 2023-10-18 22:57
@OpenRift412 What is a “language that works within ANSI”?

BTW, I would prefer the configuration files to be interchangeable between systems with different language set :)

**Comment by Kappa971** [comment] 2023-10-18 23:01
@OpenRift412, you can use my batch file to convert all your GOG .conf files from 437 to UTF-8 in one click (copy all your files to convert to the folder where the .bat file is located and run the .bat file) .
Wait for someone to fix the DOSBox Staging bug (I think it's a bug) described by me above.

**Comment by OpenRift412** [comment] 2023-10-18 23:19
> @OpenRift412 What is a “language that works within ANSI”?

I mean like a language that is entirely made up of characters that are compatible with the 437 code page (apologies, I didn't know there was a difference between that and ANSI).

> BTW, I would prefer the configuration files to be interchangeable between systems with different language set :)

What we could do is have it so there's a configuration option that allows the user to either have it determine the format automatically or specify a specific way to interpret .conf files, perhaps?

**Comment by johnnovak** [comment] 2023-10-18 23:58
There's a lot ideas flying around here, so here's my summary of the issue to maintain the dev team's focus on the important things:

1. DOSBox config files now use UTF-8 encoding. This is a necessary and welcome change done by @FeralChild64; this is the only way to ensure correct path handling on all our supported OSes that use non-English characters in path names. **This is a must-have improvement.**
2. The handling of batch files within the emulated environment is _not_ affected in any way. Whatever encoding the batch file uses, the usual DOS codepage handling rules apply. **We don't have regressions in that area.***
3. There is an edge case scenario with the GOG installers for instance when they echo high ASCII characters to the DOS console from the `dosbox.conf` config file. Because the config file provided by GOG uses CP 437 encoding, echoing the high ASCII characters result in visual glitches. However, this _does not affect_ legacy config files in any other way because other DOS commands in the `[autoexec]` section must use low ASCII chars anyway for path names for the host filesystem interactions. **This is a low priority edge case that only causes minor visual degradation.**

Please correct me if any of the above points are factually incorrect.

Unless there is an easy workaround to improve the (3) situation, we most certainly _not_ want to coerce @FeralChild64 into coming up with an expensive to maintain and potentially fragile workaround for the minor visual glitches. Again, not against a robust workaround or solution, but I'm not seeing any.

Overall, let's keep the big picture in mind — this is a _minor_ issue that does not affect functionality.

The GOG-user Staging community can always come up with a script that converts all `*.conf` files recursively to UTF-8, so maybe you can direct your energies towards that @OpenRift412 is the team decides introducing complicated workarounds for this minor issue is not worth the hassle (I assume that's the case, but @FeralChild64 has the final word on this).

**Comment by weirddan455** [comment] 2023-10-19 00:00
>  The handling of batch files within the emulated environment is not affected in any way. Whatever encoding the batch file uses, the usual DOS codepage handling rules apply. We don't have regressions in that area.*

We do have a regression here.  I'm doing the bisect now.

**Comment by johnnovak** [comment] 2023-10-19 00:01
> > The handling of batch files within the emulated environment is not affected in any way. Whatever encoding the batch file uses, the usual DOS codepage handling rules apply. We don't have regressions in that area.*
> 
> We do have a regression here. I'm doing the bisect now.

Thanks for confirming and looking into it. I just want to look at this methodically, and treating issues at their appropriate priorities according to their impact and importance.

**Comment by johnnovak** [comment] 2023-10-19 00:07
> What we could do is have it so there's a configuration option that allows the user to either have it determine the format automatically or specify a specific way to interpret .conf files, perhaps?

That's certainly a possibility, we just want to minimise the number of config files in general. But yeah, people who use stuff from GOG 99% of the time could just set this _once_ in their global config so the files get interpreted as CP 437. The question is, how much trouble would that cause to @FeralChild64 who has gone to great lengths to make our config handling UTF-8 all the way through.

**Comment by kcgen** [comment] 2023-10-19 00:17
The conf file needs to stay UTF-8, because it's at the host-layer, modified by users of modern editors and on their modern operating system.

UTF-8 is the best format for this, by definition: "Universal Coded Character Set"

`[autoexec]` can be thought of as the pivot point to perform DOS commands.

This is where GOG should simply execute an bona-fide MS-DOS 6.22 complaint batch file.

For example:

```ini
[autoexec]
imgmount ...
mount c: .
c:
call GOGMENU.BAT
```

Where `GOGMENU.BAT` could in theory run on a real DOS PC.

**Comment by OpenRift412** [comment] 2023-10-19 00:17
> Even converting GOG configuration files from 437 to UTF-8, the characters **╔ ═ ║ ╗ ╚ ╝** are not displayed. ![immagine](https://user-images.githubusercontent.com/62349018/276418683-c37a09d7-e1c1-40ec-bfc8-d77bd7ee6132.png) ![immagine](https://user-images.githubusercontent.com/62349018/276418736-c3f1e95e-2bcd-4471-bbdf-55e6b4d89219.png)
> 
> ![immagine](https://user-images.githubusercontent.com/62349018/276418542-ddaa7da7-9560-475e-a651-307e1516ac85.png) ![immagine](https://user-images.githubusercontent.com/62349018/276418614-dc799b43-dde6-41ed-9215-9e1c402111a9.png)
> 
> EDIT This is a simple batch to do the conversion (or you can use Notepad++): [GOG437toUTF-8.zip](https://github.com/dosbox-staging/dosbox-staging/files/13034590/GOG437toUTF-8.zip) but DOSBox Staging still won't display the characters above

@Kappa971 this could prove to be very helpful, thanks. @johnnovak, should we open a separate issue for this non-config batch problem?

**Comment by weirddan455** [comment] 2023-10-19 00:23
Bisect complete.  I copied the echo commands from the above screenshot into a .bat file to find the regression for those glyphs not being shown.

First bad commit:  039532b95b04da2538a9ff806d9bef7193c1c14f

**Comment by johnnovak** [comment] 2023-10-19 00:33
> @Kappa971 this could prove to be very helpful, thanks. @johnnovak, should we open a separate issue for this non-config batch problem?

Let's see what @weirddan455 finds. I think he'll create an issue ticket and/or a PR if there's an issue, so hold off on that.

But the best solution is what @kcgen just proposed a few posts above: make a copy of the GOG provided .conf file, then only keep the autoexec section of your copy. That will keep the encoding of the file, hopefully (unless you're text editor does some conversion...). Then you modify your original .conf file to call that batch file from the `[autoexec]` section. This way you don't need to convert anything.

**Comment by OpenRift412** [comment] 2023-10-19 00:50
> > @Kappa971 this could prove to be very helpful, thanks. @johnnovak, should we open a separate issue for this non-config batch problem?
> 
> Let's see what @weirddan455 finds. I think he'll create an issue ticket and/or a PR if there's an issue, so hold off on that.
> 
> But the best solution is what @kcgen just proposed a few posts above: make a copy of the GOG provided .conf file as `GOGMENU.BAT`, then only keep the autoexec section in the copy. That will keep the encoding of the file, hopefully (unless you're text editor does some conversion...). Then you modify your original .conf file to call `GOGMENU.BAT` from the `[autoexec]` section. This way you don't need to convert anything. That's a very clean solution.

It is a good solution, we'll just need to figure out how to automate that process.

**Comment by Grounded0** [comment] 2023-10-19 10:51
Are GOG stupid enough to directly dump CP437 into their .conf files? I have to double check this because its so stupid i have do double confirm i'm understanding this right.

**Comment by Kappa971** [comment] 2023-10-19 11:24
> Are GOG stupid enough to directly dump CP437 into their .conf files? I have to double check this because its so stupid i have to double confirm i'm understanding this issue right.

Older versions of DOSBox wrote configuration files with cp437 (or perhaps in other code pages depending on the language code passed by the keyb command, but I'm not sure about this). 

Rather I'm surprised every time by the folly of the 80s and 90s of not having created a standard instead of using all these character sets...

**Comment by Grounded0** [comment] 2023-10-19 11:29
``ajp@milla:~/Desktop/TR.ANSI.BUG.CONF $ iconv -f cp437 -t utf-8 dosboxTR_single.conf > test.conf
ajp@milla:~/Desktop/TR.ANSI.BUG.CONF $ emacs test.conf``

Yeah its CP437.

**Comment by rderooy** [comment] 2023-10-19 13:26
> Rather I'm surprised every time by the folly of the 80s and 90s of not having created a standard instead of using all these character sets...

Unicode has a cost, and especially in the 80's, this cost would have been significant in terms or memory, storage and CPU cycles. Back in the day (on western PCs) a character could be encoded in 8 bits or 1 byte. National character set support via codepages was considered a necessary evil.

- UTF-8, first presented in 1993, for most ASCII files has the same storage requirements as ASCII, but more complex processing as you need to figure out for each character if it is Unicode or not.
- UTF-16 was not released until 1996, and requires double the storage space and more complex processing. This encoding has been abandoned for the most part (apart from Windows and Java).
- UTF-32 from 2001, requires 4x the storage, but processing is easier. Support for it is rare, although it may be used internally in programs after decoding UTF-8 or UTF-16.

Yes there have been other encodings to try to deal with this. For instance DBCS (double-byte character set), which required 2 bytes and was becoming common in the late 80's in Asian countries. But at a substantial cost at the time. But even this limited you to 65k characters which is not enough.

**Comment by OpenRift412** [comment] 2023-10-19 18:07
> GOG can convert their CP437 files to UTF-8 or make `.conf` files to run `.BAT` batch files with CP437 to address this. If those irredeemable set of wankers don't know how to do this they can hire us for a consultancy fee in order to fix their mess:

It's less about if they know how to do it and more if they'd even be _willing_ to do it at all. If the game still works on modern systems they won't bother changing it.

**Comment by weirddan455** [comment] 2023-10-19 21:13
There's a lot of noise (and some confusion) here so I want to summarize.

 **The .conf file is now expected to be in UTF-8 encoding.**  There is very good reason for this change, mostly so users can provide filesystem paths with non-ASCII characters.  UTF-8 also has the nice property in that it is backwards compatible with ASCII.  If your config file only contains characters 0-127 in this table (https://www.asciitable.com/), it just works.  No changes needed.  So most users will not even notice this change and non English users will notice a benefit.

**The issue raised here occurs when the config file contains characters not in standard ASCII, specifically the box drawing characters.**  For that there are two workarounds.  I've tested that both work.

1. Convert the .conf file to UTF-8.  GOG appears to be shipping .conf files encoded in the code page 437 format.  @rderooy wrote a Python script that I confirmed works for these .conf files:  https://github.com/dosbox-staging/dosbox-staging/pull/3028#issuecomment-1771312108
2. Rename the local .conf file containing the menu to a .bat file.  This works because .bat files work with DOS encodings, not UTF-8.  @kcgen wrote some excellent instructions on how to do this complete with screenshots here:  https://github.com/dosbox-staging/dosbox-staging/pull/3028#issuecomment-1771691896

**Comment by Kappa971** [comment] 2023-10-19 21:37
I confirm that it works now, thanks @weirddan455
![immagine](https://github.com/dosbox-staging/dosbox-staging/assets/62349018/3d63381c-0a79-43e3-84ef-6db6bd491221)

@OpenRift412, You can use my package (some comments above) which contains a batch file and `uconv` tool (downloaded from official site https://github.com/unicode-org/icu so no viruses), works only on Windows. 
Simply copy all your cp437 configuration files into the same folder as the .bat file, and run the .bat file (it should convert all your files to UTF-8).
Or you can follow @weirddan455's advice, you have several choices.

**Comment by Grounded0** [comment] 2023-10-20 09:54
Can we close this since the majority agrees that .conf files should be ASCII or its superset UTF-8?

**Comment by Grounded0** [comment] 2023-10-20 10:53
Closing this as community effort is underway for conversion tools to easily convert legacy DOS codepage .conf files to UTF-8.

**Closed** 2023-10-20 10:54 UTC
