### ISSUE TITLE
PC Tools installer does not work

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#657] opened 2020-10-10 11:57 UTC
**Describe the bug**
Installation of "PC Tools" utilitiy software written by Central Point. fails with
![Screenshot from 2020-10-10 13-42-47](https://user-images.githubusercontent.com/3967/95654180-8e483580-0afe-11eb-8733-e1d009fbe612.png)

**To Reproduce**
Testing PC Tools distributed on 5  3½ floppies - PC Tools 8.0a.

Imgmount the floppies, switch to A:, run `install.exe`.

**Notes**
This is productivity software, so it's a low priority bug, but the worrying part is that *installer does not work* - we should investigate why exactly, as this might mean some games installers experience a similar issue.

Original report on [/r/dosbox](https://www.reddit.com/r/dosbox/comments/j7yfrl/help_cannot_find_any_floppy_drives_in_your_system/) (user ignores our pleas for creating bug in bug tracker).

This problem seems to be shared by all dosbox versions, but @Wengier confirmed that installer works correctly in DOSBox-X when booting MS-DOS.

PCCONFIG program distributed on the floppy (without installation) seems to work:
![Screenshot from 2020-10-10 13-48-21](https://user-images.githubusercontent.com/3967/95654291-5f7e8f00-0aff-11eb-9e91-51386e0539ab.png)

**Comment by kcgen** [comment] 2020-10-10 16:47
## Installation

For PC Tools 9, 8, and 7:

1. The installer _will work_ when launched from a booted HDD image:
    1. Create a bootable FAT HDD image (ie: with installed MS-DOS 5.x or 6.x)
    1. Extract and copy the floppies' contents into a single directory in the HDD image (need ~15 MB free space after copying)
    1. Boot the HDD image, for example:
         `imgmount c harddisk.img -size 512,32,2,640 -fs fat`
         `boot -l c`
    1. Install PC Tools

![2020-10-10_08-12](https://user-images.githubusercontent.com/1557255/95660287-a9557e00-0adb-11eb-981c-771f5e6a574a.png)

After installing, you can liberate the installed `c:\pctools` out of HDD image and used it in dosbox like any other directory of files.

PC Tools 6.x can be installed simply by `imgmount`ing the floppies in dosbox, without the bootable HDD image wrapper process.

## Discussion for PC Tools 7, 8, and 9

Given the installer works from a directory (and doesn't care about the floppies or their disk labels), this says the installer is making IO-related calls that dosbox natively doesn't emulate; but that do become available when MS-DOS's `io.sys` is loaded via the boot process.

When run outside of the HDD image, the `pcshell.exe` file-browser will be empty, presumably because it's using the same IO-related calls that dosbox isn't emulating. 

## Differences between dosbox-staging and DOSBox-X

For PC Tools 6.x:

**Dosbox-staging** runs `desktop.exe` without issue:

![2020-10-10_08-58](https://user-images.githubusercontent.com/1557255/95660402-7790e700-0adc-11eb-9eb1-d94aa6382aff.png)

**DOSBox-X** mentions its corrupt (latter I confirmed that `loadfix` allows it to work):

![2020-10-10_09-31_1](https://user-images.githubusercontent.com/1557255/95660413-9becc380-0adc-11eb-9409-7ca97a75c256.png)

For PC Tools 9.x:

**dosbox-staging** runs `pcshell.exe` (albiet with an empty directory listing), however its many tools can be launched using the shell:

![2020-10-10_09-07](https://user-images.githubusercontent.com/1557255/95660384-4adccf80-0adc-11eb-8a53-ad01dd7d7138.png)

![2020-10-10_09-01](https://user-images.githubusercontent.com/1557255/95660452-e0785f00-0adc-11eb-9e7a-f6593f7c1bc9.png)

**DOSBox-X** running `pcshell.exe` results in an error that cannot be bypassed and the shell closes:

![2020-10-10_09-31](https://user-images.githubusercontent.com/1557255/95660473-0867c280-0add-11eb-84e7-0f804adafba3.png)

Perhaps armed with a debugger, more headway can be made to satisfy `pcshell`'s IO calls which in turn can fix the remaining games that are similarly impacted by this.

**Comment by dreamer** [comment] 2020-10-10 17:09
@kcgen great investigation! Huh, I presumed we are emulating io.sys to some extent already…

**Comment by kcgen** [comment] 2020-10-10 17:30
Yes; PC-Tools could be a great way to figure out the remaining missing pieces. 

The System Information `si.exe` tool can test many aspects of the emulated system; perhaps fixing its flagged failures (such as the reported issues with the emulated DMA controller, keyboard controller, and interrupt handler), maybe also fix more corner-case issues.

**Comment by Wengier** [comment] 2020-10-10 17:46
@kcgen I see that you were using DOSBox-X version 0.83.2 for testing. DOSBox-X since version 0.83.3  will do LOADFIX automatically, so running PC Tools 6's desktop.exe in recent versions of DOSBox-X has no issue at all.

Also, running PC Tools 9's pcshell.exe in current DOSBox-X also seems to be fine here:

![image](https://user-images.githubusercontent.com/8216923/95661633-d2d3d100-0afe-11eb-9c70-f3540b91c069.png)

**Comment by dreamer** [comment] 2020-10-10 17:52
@Wengier thanks for chiming in - any suspicion what might be causing installer failures for PC Tools 7, 8, 9 in our built-in shells?

**Comment by Wengier** [comment] 2020-10-10 18:01
@dreamer I have not got the time to dig into this particular issue so far, but I highly suspect the reason is the missing implementation of DOS IOCTL calls. Apparently DOSBox (and forks) do not implement DOS IOCTL calls completely, which are useful for DOS disk utilities but not generally useful for DOS gaming. DOSBox-X already implemented a few more DOS IOCTL functions in recent months to allow for example DOS's FORMAT and SCANDISK tools to work, but there are apparently still DOS IOCTL calls not yet implemented properly.

**Comment by kcgen** [comment] 2020-10-10 18:32
Wow; thanks Wengier! Will update my post.

This is great to see that more complete IO emulation noe exists in DOSBox-X; with some work we should be able to bisect down and find the commits that added it. 

Can you run the PC Tools System Information tests, and see if -X does better there too?

**Comment by Wengier** [comment] 2020-10-10 18:53
@kcgen I have tried the PC Tools System Information in current DOSBox-X, and the result is like this:

![image](https://user-images.githubusercontent.com/8216923/95662694-ceabb180-0b06-11eb-877e-b3e72632ac1e.png)

As for IOCTL functions, sure they can be added for -staging as well, but I also want to mention that since DOSBox-X also adds support for FAT32 drives (disk images), many IOCTL functions as currently implemented may be related to FAT32 support. I wonder if you'd like it to be supported in dosbox-staging as well (right now its FAT12/16 only as in vanilla DOSBox). If FAT32 will be supported in -staging also, then code sharing between -X and -staging will be much easier.

**Comment by kcgen** [comment] 2020-10-10 19:54
Very valuable information @Wengier, thank you for all of this insight.

Indeed, the big question is how much these IOCTL's involve code / complexity / maintenance-wise, and how that translates to benefit in gaming, like you said (and perhaps the case gets stronger if we include include Windows 3.1 and 95/98/ME as well). 

@dreamer - thanks for opening this bug; it's given us something to work toward (and an external black-box tester using SI as well), when staging's bigger pieces are in place!

**Comment by Wengier** [comment] 2020-10-10 21:23
@kcgen I think FAT32 support is useful for DOS gaming when users want more capacity on the disk images. But we also need to keep in mind that some programs (especially older DOS disk utilities) may not handle FAT32 drives well even if these drives are accessible from DOS. There is generally no solution for this unless there is a updated version of the software available which adds better combability with FAT32 drives.

**Comment by dreamer** [comment] 2020-10-13 22:12
**ripsaw8080** just pushed a commit for fixing PC Tools 9; I don't know if it addresses installer problem, haven't tested it yet: 67ae6ada145b23198b1f453780f50cd081a2b557 (merged to master with fb638fb7edc8bcd204c761f5f3877e7f32b939c0).

**Comment by Wengier** [comment] 2020-10-13 22:52
@dreamer Yes, I think it just tries to fix some DMA test issue, not the installer one. But nevertheless should be a positive improvement for PC Tools compatibility.

**Comment by Wengier** [comment] 2020-10-13 22:54
@dreamer The fix for the installer problem will likely be in the dos files.

**Comment by kcgen** [comment] 2020-10-13 23:34
Motherboard DMA tests now passing! 
**:beers: @ripsaw8080!**

![2020-10-13_16-33](https://user-images.githubusercontent.com/1557255/95926760-e5097580-0d71-11eb-9d17-0c6614e85d28.png)

**Comment by kcgen** [comment] 2021-09-20 03:15
Closing, as work-arounds and progress was made. Thanks to all involved!

**Closed by kcgen** 2021-09-20 03:15 UTC
Labels: bug
