### ISSUE TITLE
MacOS/Win3.1 - int33 mouse driver fails when NE2000 initialized

### ISSUE THREAD

**Issue by aroenai** [dosbox-staging/dosbox-staging#2765] opened 2023-08-16 17:38 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

Mac OS

### If Other OS, please describe

macOS Ventura

### Relevant hardware info

Arm (M2 Pro)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Following the wiki guide for installing Windows For Workgroups 3.11, the VBMouse int33 absolute mouse driver fails to function once the NE2000 driver is initialized. When NETSTART.BAT is not run, the issue does not occur. Regular Windows 3.11 works as expected (but does not have network capabilities).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Follow wiki guide for WfW311 installation 
2. Install VBMouse driver and NE2000 drivers
3. Run win.com after initializing the network with NETSTART.BAT
4. Mouse will move for a second and freeze indefinitely 

### Download URL of affected game or software

https://github.com/dosbox-staging/dosbox-staging/wiki/Windows-3.1x

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment] 2023-08-16 18:45
The Wiki guide was actually updated yesterday to discourage using this driver...

**Comment by aroenai** [comment] 2023-08-17 02:57
nicirq = 3

It was just left at the default value, the only other sections I changed were:

output              = texturenb
texture_renderer    = metal
mouse_capture             = seamless
mididevice      = coreaudio

**Comment by aroenai** [comment] 2023-08-21 04:23
@FeralChild64 any way this can be tested with the Microsoft Network Client 3.0 for MS-DOS ( https://ftpmirror.your.org/pub/misc/ftp.microsoft.com/bussys/Clients/MSCLIENT/ and https://www.legroom.net/howto/msdos ) in conjunction with the regular Windows 3.11 setup to rule out it being something specific to WFW? I can't seem to figure out how to initialize the NE2000 far enough to get to the Windows setup steps though.

nicirq = 10 results in the same behavior, just for reference.

**Comment by FeralChild64** [comment] 2023-08-21 20:12
@aroenai To be honest, I have no idea how to setup Microsoft Network Client 3.0 for DOS, I have never tried. I was not able to reproduce the problem yet - I am running Windows 3.11 without the network, and trying to set it up with the network led me only to an error:

![error](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/87cc540c-749a-4bc3-9d5e-7d1124f18d5a)

**Comment by FeralChild64** [comment] 2023-08-21 21:04
@aroenai Could you try to run the `VBMOUSE.EXE` from the VBADOS driver package before starting Windows? Does it help for your issue?

I have found an incompatibility between our internal mouse driver and the Windows driver by Javis Pedro - if you use the PIF editor to set the MS-DOS prompt to be run in a window, the driver stops working as soon as you open the DOS prompt from within Windows. It seems our functions 0x00 / 0x21 aren't behaving as they should; but fixing it might be too risky to go into 0.81.0, we'll see.

**Comment by Grounded0** [comment] 2024-01-01 05:59
I have zero problems using these both so i wonder what the issue might be here.

**Comment by Grounded0** [comment] 2024-01-01 06:21
Have you tried running with our 0.81 RC release?

**Comment by aroenai** [comment] 2024-01-01 19:33
> Have you tried running with our 0.81 RC release? There's a lot of bug fixes in this release related to the mouse driver.

Same results with the mouse cursor freezing in place on the login screen after running NETSTART.BAT before Windows on dosbox-staging-macOS-v0.81.0-rc1.dmg

**Comment by Grounded0** [comment] 2024-01-01 19:39
Have you tried disabling the INT33 driver before initialising the NE2000? Maybe you need to initialise the NE2000 before you add the INT33 driver.

**Comment by aroenai** [comment] 2024-01-01 19:59
> Have you tried disabling the INT33 driver before initialising the NE2000? Maybe you need to initialise the NE2000 before you enable the INT33 driver.

Disable how, 'config -set "virtualbox_mouse=false"'?

The NETSTART.BAT file is run before Windows is started, not sure what you mean if it needs to initialize first if Windows isn't even loaded yet for the mouse driver. Works perfectly if I don't initialize the network before loading win.

**Comment by Grounded0** [comment] 2024-01-01 20:13
Try this:

1. Don't run NETSTART.BAT and go into Windows Setup and change Mouse driver to:

<img width="730" alt="Screenshot 2024-01-01 at 22 10 18" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/e4fb03bf-84a6-43f4-8ff5-3d06d5016e82">

2. Go through the network configuration steps and verify you have a working network connection by running NETSTART.BAT and trying to establish a network connection to an FTP like that.

3. Change mouse driver back to INT33

**Comment by aroenai** [comment] 2024-01-01 21:24
> Try this:
> 
> 1. Don't run `NETSTART.BAT` and go into Windows Setup and change Mouse driver to:
> 
> <img alt="Screenshot 2024-01-01 at 22 10 18" width="730" src="https://private-user-images.githubusercontent.com/48192273/293605455-e4fb03bf-84a6-43f4-8ff5-3d06d5016e82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDQyNzAsIm5iZiI6MTcwNDE0Mzk3MCwicGF0aCI6Ii80ODE5MjI3My8yOTM2MDU0NTUtZTRmYjAzYmYtODRhNi00M2Y0LThmZjUtM2QwNmQ1MDE2ZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MjU3NWMyMDg4ZjYwNmQwODBkMWRmZDk0MDhmY2Y2MzBhZGJiMjY3YWMyM2M5NmIxODhlOWUwZDA5ZDkwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nh7gIVHVtHWg9RG5SucEklt3uQTJXaLSm6ar9aK7rN8">
> 2. Reboot and go through the network configuration steps and verify you have a working network connection by running `NETSTART.BAT` and trying to establish a network connection to an FTP like `ftp.funet.fi`
> 3. Change mouse driver back to INT33

Was the point of this just to validate that the network works? The virtual NE2000 and int33 mouse driver work independently but not together, as soon as Windows is restarted to start using the int33 driver the same behavior recurs - cursor freezes on the login screen after a few seconds.

**Comment by Grounded0** [comment] 2024-01-01 22:01
Are you using network card driver: NE2000 Compatible [NDIS2/NDIS3]?

**Comment by aroenai** [comment] 2024-01-01 22:46
> Are you using network card driver: NE2000 Compatible [NDIS2/NDIS3]?

Yes, the driver included on the Windows for Workgroups 3.11 setup disks.

**Comment by Grounded0** [comment] 2024-01-01 22:58
@kcgen what we should do with this as we both can run INT33 mouse driver and Windows network stack at the same time?

**Comment by aroenai** [comment] 2024-01-02 01:14
> @kcgen
> 
> What should we do with this as we both can run INT33 mouse driver and Windows for Workgroups 3.11 network stack at the same time? If you haven't yet, install the INT33 driver and use the Windows setup i provided you a long ago:
> 
> https://git.javispedro.com/cgit/vbados.git/about/

To confirm, I am not running any other commands before launching Windows. This is only the INT33 implementation in DOSBox Staging and the javispedro Windows driver, the positioning is correct only when the NE2000 driver is not loaded.

**Comment by Grounded0** [comment] 2024-01-02 01:41
Isn't this ticket about INT33 driver and Windows network stack not being able to run at the same time? That's what the title says. I have zero tracking issues with both loaded at the same time.

**Comment by aroenai** [comment] 2024-01-02 01:46
> Isn't this ticket about INT33 driver and Windows network stack not being able to run at the same time? That's what the title says. I have zero tracking issues with both loaded at the same time.

Yes, it is. I have not tried any of this on a PC though, I'm just clarifying that I'm only using the Windows 3.1 driver component on my Macbook since using the vbmouse.exe driver was suggested previously.

**Comment by Grounded0** [comment] 2024-01-02 01:54
VBMOUSE.EXE component currently only matters if you run MS-DOS Prompt inside Windows 3.1x. Otherwise you can disregard it for now:

- #3298

**Comment by aroenai** [comment] 2024-01-02 02:19
That issue is also referencing an Intel Mac, I only get movement for a few seconds before it freezes in place as Windows loads on my M2. With VBMOUSE INSTALL I can move the mouse normally, but I'm noticing it seems to get confused on the absolute position sometimes and changes to a "scaled" movement with faster speed.

**Comment by Grounded0** [comment] 2024-01-02 02:23
Well it could be a non-x86 issue. @kcgen or someone else probably has to check that out too.

**Comment by FeralChild64** [comment] 2024-01-02 18:28
Might be related to this problem: https://github.com/joncampbell123/dosbox-x/issues/3384#issuecomment-1873968945

It seems I need to improve our internal, simulated DOS mouse driver - otherwise the seamless INT33 Windows mouse driver by @javispedro might exhibit issues in various situations.

**Comment by kcgen** [comment] 2024-01-02 20:16
With a basic TCP network configuration, it seems to work OK (suggest expanding to fullscreen):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/cbb65f20-f99d-444a-84b0-9c70601f0175

Here's a reproduction pack, if you want to inspect the configuration closer:

- [wfw-1024-768-gus-ethernet-vbmouse.7z.001 :file_folder: ](https://github.com/dosbox-staging/dosbox-staging/files/13813496/wfw-1024-768-gus-ethernet-vbmouse.7z.001.txt)

- [wfw-1024-768-gus-ethernet-vbmouse.7z.002 :file_folder:](https://github.com/dosbox-staging/dosbox-staging/files/13813497/wfw-1024-768-gus-ethernet-vbmouse.7z.002.txt)

To try it:
1. download both of the above
1. rename them without the `.txt` extensions
1. extract with 7zip or the CLI tool `7za x /path/to/archive.7z.001`, it will automatically find the second archive.
1. open a console and `cd wfw-1024-768-gus-ethernet-vbmouse`, then run `/path/to/your/dosbox-staging/dosbox`

**Comment by kcgen** [comment] 2024-01-02 22:07
Working OK on the mac mini M1 (using the above repro pack as-is):

<img width="2560" alt="Screen Shot 2024-01-02 at 2 04 17 PM" src="https://github.com/dosbox-staging/dosbox-staging/assets/1557255/5a53d8a8-3fbd-409d-88d8-30620b213897">

**Comment by aroenai** [comment] 2024-01-02 23:07
Still at work, so can't test yet but from the file name I'm guessing you're using Gravis Ultrasound instead of Soundblaster which I haven't tried. Any other obvious IRQ settings changed? I've only tried 3 and 10 for the NE2000, with the appropriate COM ports disabled, etc.

**Comment by kcgen** [comment] 2024-01-02 23:09
@classilla :arrow_up: I stumbled up `gopher://floodgap.com`, which is looking nice a readable from WS Gopher. Very nice! :-)

**Comment by kcgen** [comment] 2024-01-02 23:12
> Still at work, so can't test yet but from the file name I'm guessing you're using Gravis Ultrasound instead of Soundblaster which I haven't tried. Any other obvious IRQ settings changed? I've only tried 3 and 10 for the NE2000, with the appropriate COM ports disabled, etc.

Just defaults, and I've disabled COM2 through 4, but don't think it was necessary.

Using GUS because it was easy to install and test, but probably not as robust as a full SB16 driver + MIDI passthrough install; so that could be swapped out. No reason to  use GUS versus SB, other than I didn't want to mess with it much more.

**Comment by Grounded0** [comment] 2024-01-02 23:39
I'm using a full SB16 Windows setup with the installed driver and an MPU-401 passthrough through the Windows 3.11 driver and everything works like @kcgen.

**Comment by johnnovak** [comment] 2024-01-03 00:59
FROG FIND! So cool! 😎 Look how content that little chap is! 😆 

<img width="810" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/ec8baade-d9bd-47c6-a9af-031cf6467919">

**Comment by Grounded0** [comment] 2024-01-03 16:28
Closing since we cannot reproduce this issue.

**Closed by Grounded0** 2024-01-03 16:28 UTC
Labels: bug, Windows 3.x
