### ISSUE TITLE
Wizardry: Bane of the Cosmic Forge (1990) audio click and pop issues

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3642] opened 2024-04-30 21:27 UTC
This game is listed as having a game specific build:

- #1671 

Check if the game is working with the latest release of DOSBox Staging and have the core issues mentioned in the details been addressed and report back the results.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-04-30 21:52
I'm interested in this as it's a most prestigious RPG, plus it's closely related to other DC offset induced click and pop issues I'm intending to look into anyway.

Related discussion:

https://github.com/dosbox-staging/dosbox-staging/issues/963#issuecomment-812088248

Related issue:

- https://github.com/dosbox-staging/dosbox-staging/issues/3486

**Comment by vol-2** [comment] 2024-04-30 22:11
IIRC, BOTCF always had crappy digital sound and it has no music. Just fyi it might behoove you to double check the issue isn't also present on original hardware. Though maybe you have a fix for that?

**Comment by johnnovak** [comment] 2024-04-30 22:26
> IIRC, BOTCF always had crappy digital sound and it has no music. Just fyi it might behoove you to double check the issue isn't also present on original hardware. Though maybe you have a fix for that?

Yeah, I'll test on hardware. And yes, we're aiming to fix sound issues at the emulator level if it's not intrusive and practical to do so.

**Comment by Grounded0** [comment] 2024-05-01 10:30
@Python-Exoproject has flagged this as good for DOSBox Staging with approval pending from eXo. Since this is a legendary AAA title we'll probably want to do our own investigation that we're happy with the way the game works before closing this.

**Comment by johnnovak** [comment] 2024-05-01 22:27
> @Python-Exoproject has flagged this as good for DOSBox Staging with approval pending from eXo. Since this is a legendary AAA title we'll probably want to do our own investigation that we're happy with the way the game works before closing this.

Yeah I agree.

**Comment by johnnovak** [comment] 2024-05-06 00:35
@Python-Exoproject

The default `pcspeaker = discrete` setting results in horrible clicks at the start and end of every audio sample. With the improved PC Speaker emualtion, however, the clicks are gone and I think we're getting the same results as in the hacked DOSBox with GC support.

```ini
[speaker]
pcspeaker = impulse
```

That should be enough to migrate this over to Staging in eXoDOS.

Also note that our OPL emulation has been improved in the last few years, so yo can configure the game for AdLib/OPL and you'll get digital sound via OPL which is also click free. The sounds are a bit different, and there's more grunge to the sound, so you might wanna offer it as an alternative sound option.

Related: I think I will make `pcspeaker = impulse` the default later.

**Comment by interloper98** [comment] 2024-05-06 01:06
It's click city on a real DOS PC speaker:  https://m.youtube.com/watch?v=v38XPp-wokc&t=7m09s (7m 9s mark shows real PC speaker routed through the SB input line).

Nice to see dosbox's speaker is accurate (painfully so, in this case)!

**Comment by johnnovak** [comment] 2024-05-06 01:11
> It's click city on a real DOS PC speaker: https://m.youtube.com/watch?v=v38XPp-wokc&t=7m09s (7m 9s mark shows real PC speaker routed through the SB input line).
> 
> Nice to see dosbox's speaker is accurate (painfully so, in this case)!

Haven't tested on real hardware yet, but I think impulse is closer while discrete is too exaggerated as it's simplistic digital emulation only.

I will introduce some more advanced general declicker anyway.

**Comment by Burrito78** [comment] 2024-05-06 13:34
https://github.com/dosbox-staging/dosbox-staging/assets/61995128/d60f4c42-ba18-42f4-82c7-244a969f595d

It sounds normal, but its very annoying. :)

**Comment by johnnovak** [comment] 2024-05-06 13:55
@Burrito78 That's through a real PC Speaker? Pretty annoying yeah... then my guess was wrong.

Well, `pcspeaker = impulse` sounds already better than that, which is good.

**Comment by Grounded0** [comment] 2024-05-06 19:20
I understood the best sound option for this game is Adlib/OPL2. People should use the best available sound option.

**Comment by MasterO2** [comment] 2024-05-06 19:22
Unless PC Speaker is the only sound option that a DOS game supports (such as Commander Keen 1 through 3), don't use PC Speaker for any DOS game **at all**.

**Comment by johnnovak** [comment] 2024-05-07 04:35
> Unless PC Speaker is the only sound option that a DOS game supports (such as Commander Keen 1 through 3), don't use PC Speaker for any DOS game **at all**.

PC Speaker and OPL are the only options for Wizardry IV.

> I understood the best sound option for this game is AdLib/OPL2. People should use the best available sound option.

This game uses both the PC Speaker and the OPL as primitive DACs to output digital audio samples using some clever hacks, so the usual advice that OPL is better doesn't apply.

I found the digital audio via the PC Speaker to be better quality in this game, _except_ for the clicking. But that's almost gone with `pcspeaker = impulse`.

The digital audio via OPL option sounds lower quality (lower sample rate and more distorted), and not just that, there appear to be fewer sounds and some sounds are slightly different.

**Comment by Grounded0** [comment] 2024-06-06 18:32
Adding https://github.com/dosbox-staging/dosbox-staging/labels/eXoDOS%2FWin3x as this is inherited from eXoDOS game specific builds megaticket.

**Comment by Grounded0** [comment] 2024-08-23 06:23
Labelling this bug isn't helpful. We aspire to ameliorate the situation caused by the game.

**Comment by Grounded0** [comment] 2024-08-23 06:32
Labelling this https://github.com/dosbox-staging/dosbox-staging/labels/game%20compatibility isn't helpful. We aspire to ameliorate the issue caused by the game.

**Comment by Grounded0** [comment] 2024-08-23 11:57
Removing https://github.com/dosbox-staging/dosbox-staging/labels/bug and https://github.com/dosbox-staging/dosbox-staging/labels/game%20compatibility. We aspire to ameliorate the issue caused by the game.

**Comment by johnnovak** [comment] 2024-09-29 22:10
Fixed by the new `pcspeaker = impulse` default which yields less clicks than on real hardware. Using the OPL driver is also an option which is not clicky.

**Closed by johnnovak** 2024-09-29 22:10 UTC
Labels: audio, test on hardware, eXoDOS/Win3x
