### ISSUE TITLE
"Illegal read from" errors in Ignition

### ISSUE THREAD

**Issue by not-a-user** [dosbox-staging/dosbox-staging#495] opened 2020-07-12 21:49 UTC
Happens in **Ignition** some minutes of game play. The game freezes completely.

dosbox-staging 0.75.0 on Fedora 32.

Not observed with 0.74.3-5.fc32.

[log.txt](https://github.com/dosbox-staging/dosbox-staging/files/4909606/log.txt)

[dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4909613/dosbox.conf.txt)

**Comment by kcgen** [comment] 2020-07-12 22:58
Confirmed with the latest main branch, as well: 

``` text
Illegal read from 6767676e, CS:IP      160:  1c8814
Illegal read from 6767676f, CS:IP      160:  1c8814
Illegal read from 67676770, CS:IP      160:  1c8814
Illegal read from 67676771, CS:IP      160:  1c8814
Illegal read from 67676766, CS:IP      160:  1c8814
Illegal read from 67676767, CS:IP      160:  1c8814
Illegal read from 67676768, CS:IP      160:  1c8814
Illegal read from 67676769, CS:IP      160:  1c8814
Illegal read from ffffffff, CS:IP      160:  1c8c20
Illegal read from 7000f4f4, CS:IP      160:  1c8c24
Illegal read from 7000f4f5, CS:IP      160:  1c8c24
Illegal read from 7000f4f6, CS:IP      160:  1c8c24
```

**Comment by kcgen** [comment] 2020-07-12 22:59
Also happens with Zone 66 soon after getting the game underway, however you can carry on (however I suppose it might eventually lock up):

``` text
Illegal read from ef04ef02, CS:IP        8:    c997
Illegal read from ef04eefe, CS:IP        8:    c99b
Illegal read from ef04eeff, CS:IP        8:    c99b
Illegal read from ef04ef00, CS:IP        8:    c99b
Illegal read from ef04ef01, CS:IP        8:    c99b
Illegal read from ef04ef11, CS:IP        8:    c997
Illegal read from ef04ef0d, CS:IP        8:    c99b
Illegal read from ef04ef0e, CS:IP        8:    c99b
Illegal read from ef04ef0f, CS:IP        8:    c99b
Illegal read from ef04ef10, CS:IP        8:    c99b
Illegal read from ef04ef20, CS:IP        8:    c997
Illegal read from ef04ef1c, CS:IP        8:    c99b
Illegal read from ef04ef1d, CS:IP        8:    c99b
Illegal read from ef04ef1e, CS:IP        8:    c99b
Illegal read from ef04ef1f, CS:IP        8:    c99b
Illegal read from ef04ef2f, CS:IP        8:    c997
```

**Comment by kcgen** [comment] 2020-07-13 00:25
@not-a-user, given this issues comes from upstream, it would be valuable to [report this on DOSBox's SourceForge issue tracker](https://sourceforge.net/p/dosbox/bugs/new/), to ensure it's the authors see it.

If you can build DOSBox SVN, it should crash for you (just like it is for me), and you can report this as a regression versus 0.74.3 - which should get some attention (nobody wants regressions!).

(Shout if you need any tips building SVN; happy to write up the steps!)

**Comment by dreamer** [comment] 2020-07-13 11:37
@not-a-user does the problem happen when you set `machine = vesa_nolfb`? Also, is the problem resolved if you run `loadfix` before starting the game? Does it disappear when you set a bit more emulated RAM (e.g. `memsize = 24`)?

This log line indicates, that an unrecognized memory page was accessed. Recognized memory page handlers are: handler for physical memory (RAM), handlers for LFB, and handler for memory-mapped I/O. If memory access does not fall into a recognized page handler, then read prints this log and return 0xff byte.

OK, so these logs might indicate one of the following situations (AFAIK):

- stack corruption - either resulting from a bug in the game (perhaps programming error, perhaps a corrupted exe file, perhaps a bug introduced by game crack, etc), but also can indicate a bug in CPU emulation (if the problem happens with both normal and dynamic core, then bug in the game executable is more likely)
- bad programming on purpose - some DOS programmers looked up random memory locations - e.g. as an easy way to obtain value for seeding RNG; `loadfix` should take care of many of such issues.
- software trying to access memory-mapped I/O for some hardware unsupported by DOSBox (maybe some special math coprocessors?)
- and yeah, they might indicate a bug in core as well

@kcgen out of this list, I think we can safely discard reports from before 2007 and reports using DOSBox 0.72 or older - DOSBox was missing MMIO handler back then.

I'll investigate further, but in the meantime I'm very interested in reports from testing with `vesa_nolfb`.

**Comment by kcgen** [comment] 2020-07-13 18:45
> @not-a-user does the problem happen when you set `machine = vesa_nolfb`? 

I recall running nolfb in both my tests; but will double check. 

Also, is the problem resolved if you run `loadfix` before starting the game?

Interesting.. this seams like a second use for loadfix, besides just eating up some low memory. 
(I guess the eaten up ram then gets accounted for in one of the buckets you mentioned below?)

> Does it disappear when you set a bit more emulated RAM (e.g. `memsize = 24`)?

Will check that too.

> This log line indicates, that an unrecognized memory page was accessed. Recognized memory page handlers are: handler for physical memory (RAM), handlers for LFB, and handler for memory-mapped I/O. If memory access does not fall into a recognized page handler, then read prints this log and return 0xff byte.
> 

Given DOS didn't have a virtual memory partitions around processes, I'm guessing this should be allowed? And I suppose these messages are just informations.. but perhaps harbingers of things possiblity going off the rails.  

Maybe we can improve the message to this effect, and use actual human quantities instead going full greek with 8-digit hex numbers :-)

Something like: '_zone66.exe attempted to read 6 bytes at the 9643 KB mark, which has not yet been mapped'._ 

If the user's only allocated 8MB, then this would be an immediate tip-off to give the game a bit more memory. 

I also wonder if returning 255 is the right approach? We might have better luck returning zero.


> OK, so these logs might indicate one of the following situations (AFAIK):
> 
> * stack corruption - either resulting from a bug in the game (perhaps programming error, perhaps a corrupted exe file, perhaps a bug introduced by game crack, etc), but also can indicate a bug in CPU emulation (if the problem happens with both normal and dynamic core, then bug in the game executable is more likely)

In some of those reports, ripsaw recommends using the 386 core type. I will try this too. 

> 
> @kcgen out of this list, I think we can safely discard reports from before 2007 and reports using DOSBox 0.72 or older - DOSBox was missing MMIO handler back then.

Will separate these out; thanks for figuring out this cutoff!

**Comment by not-a-user** [comment] 2020-07-13 22:56
Confirmed with https://svn.code.sf.net/p/dosbox/code-0/dosbox/trunk@4356.

**Comment by kcgen** [comment] 2020-07-13 23:44
Alas.. DOS4/GW strikes again.  Swapping in DOS32/A solved it - 

![2020-07-13_16-38](https://user-images.githubusercontent.com/1557255/87364024-5ba29700-c527-11ea-934b-f18cc84c2579.png)

@nemo93 's has **Ignition** listed on our [DOS32/A wiki page](https://github.com/dosbox-staging/dosbox-staging/wiki/DOS-32A-compatibility-list), as an alternate name for **Fun Tracks**.

So this is win win; because we now know there's definitely something broken in dosbox, because the publisher would have never released this if it hard-locked after 20 seconds of play, 100% of the time, on real DOS hardware.

**Comment by kcgen** [comment] 2020-07-17 15:39
Suggest we close this, now that DOS32/A "resolves" it for Ignition.
That said, we can always search the closed set if/when we need more examples of to Illegal read instances.

**Closed by kcgen** 2020-07-17 15:39 UTC
Labels: bug, external, game compatibility
