### ISSUE TITLE
Blackthorne freezes on startup if Sound Blaster / Sound Blaster Pro is selected for digitized sounds

### ISSUE THREAD

**Issue by TiBeN** [dosbox-staging/dosbox-staging#3685] opened 2024-05-20 07:22 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game "Blackthorne" does not launch (freeze on startup) if the sound card is setup with soundblaster or soundblaster pro for digitized sounds (in the setup.exe of the game). Using no sound the game launches correctly.

On the logs, there is this message:

```
[...]
2024-05-20 09:12:24.748 | FAT: Mounted ../../var/dosbox/blackthorne/Blackthorne (World)(Disk 2).ima as FAT12 volume with 2847 clusters
2024-05-20 09:12:24.748 | Drive A: disk 1 of 2 now active
2024-05-20 09:12:24.748 | UNICODE: No fallback mapping for code point 0x2665
2024-05-20 09:12:40.538 | SB16: DSP was reset
2024-05-20 09:12:55.977 | SB16: DSP was reset
```

Here is the config file (pretty pristine, just some rendering adjustments):
[dosbox-staging.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/15373925/dosbox-staging.conf.txt)

Below is a capture where the game is frozen:
![bthorne-dosbox-staging](https://github.com/dosbox-staging/dosbox-staging/assets/910115/d913f071-4319-4994-b873-2b9b7073f52a)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install the game blackthorne
2. Run setup.exe to configure the soundcard (set soundblaster, ad 220, irq 7, dma 1)
3. Save and run the game with "bthorne.exe"

### Download URL of affected game or software

https://archive.org/download/grubys-ibm-pc-compatibles-floppy-images/Gruby%27s%20IBM%20PC%20Compatibles%20-%20Floppy%20Images.zip/Gruby%27s%20IBM%20PC%20Compatibles%20-%20Floppy%20Images%2FGames%2FIMA%2FBlackthorne%20%28World%29%282%20Disks%29.zip

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment] 2024-05-20 08:09
@TiBeN Is this a regression compared to 0.80.1 or 0.81.0, could you please test? Thanks.

**Comment by johnnovak** [comment] 2024-05-20 08:18
Okay, looks like a known issue. Try these settings:

https://www.pcgamingwiki.com/wiki/Blackthorne#Run_in_DOSBox

**Comment by TiBeN** [comment] 2024-05-20 08:23
Yeah, it works now with `cycles=fixed 13000`. Thank you for your quick feedback.

Not sure if its a fixable issue or not so i let you close the issue.

**Comment by johnnovak** [comment] 2024-05-20 08:27
> Yeah, it works now with `cycles=fixed 13000`. Thank you for your quick feedback.
> 
> Not sure if its a fixable issue or not so i let you close the issue.

It's a really old known issue, see here:
https://www.dosbox.com/comp_list.php?showID=3747&letter=B

Probably this is how the game behaves on real hardware too if the CPU is too fast, so closing.

**Closed** 2024-05-20 08:28 UTC
Labels: not a bug
