### ISSUE TITLE
'config -wc' doesn't work in current installer version of dev build.

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3035] opened 2023-10-21 20:26 UTC
Wanted to delve further into testing the dev build so I downloaded the installer version of it but after I installed it on top of 0.80.1 and launched for the first time, I got this error:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/29780788/478c8b5a-21bb-4c99-b2a2-a37d136b2fca)

How to reproduce:
1. Install release build of Staging via setup, update config
2. Install latest dev build of Staging via setup, it will attempt to update the config on first launch.
3. It will attempt to update the config with `config -wc` on startup instead of `config -wcd`.

I tested the portable ZIP version and it doesn't seem to have that problem.

I'm on Windows 11 btw.

**Comment by kcgen** [comment] 2023-10-21 20:44
Z:\> is a virtual drive that has no writable host-mounted storage behind it. 

`config -wcd` => write config _default_ (ie, to your home directory)
`config -wd` => write config (local `dosbox.conf`)

**Comment by OpenRift412** [comment] 2023-10-21 20:54
> `Z:\>` is a virtual drive that has no writable host-mounted storage behind it.
> 
> * `config -wcd` => write config _default_ (ie, to your home directory)
> * `config -wd` => write config (local `dosbox.conf`)

Thanks for the info. It did this command when I first installed it, so you may want to fix that part, I think.

**Comment by kcgen** [comment] 2023-10-21 21:01
Oh, you mean it automatically ran that command on startup, and failed? 

Can you list step by step how to reproduce, including any deleting or clean-out of existing conf files. Then it can be fixed if needed.

@johnnovak updated the config write feature, and can assess when he's back from vacation.

**Comment by OpenRift412** [comment] 2023-10-21 21:02
> Oh, you mean it automatically ran that command on startup, and failed?
> 
> Can you list step by step how to reproduce, including any deleting or clean-out of existing conf files. Then it can be fixed if needed.
> 
> @johnnovak updated the config write feature, and can assess when he's back from vacation.

My bad, I misphrased that. It ran `config -wc` on startup instead of `config -wcd`.

**Comment by kcgen** [comment] 2023-10-21 21:04
Ok, so every time you launch the windows-installer build, it automatically runs `config -wc` without you doing anything, and it fails?

And this repeats every time you launch it?

**Comment by OpenRift412** [comment] 2023-10-21 21:11
> Ok, so every time you launch the windows-installer build, it automatically runs `config -wc` without you doing anything, and it fails?
> 
> And this repeats every time you launch it?

Not every time I launch it, but the first time it launches after it is installed (presumably attempting to update the existing config)

**Comment by kcgen** [comment] 2023-10-21 21:23
Can you edit your original wording to clarify all this?

Because it's no obvious from the existing wording if you typed those commands manually, likewise it's not obvious if (to reproduce this) we need to clear out our existing config files or not. 

This is why I've had to ask so many questions, and why the issue form has a step by step list to describe how to reproduce the issue.

**Comment by OpenRift412** [comment] 2023-10-21 21:33
> Can you edit your original wording to clarify all this?
> 
> Because it's not obvious from the existing wording if you typed those commands manually, likewise it's not obvious if (to reproduce this) we need to clear out our existing config files or not.
> 
> This is why I've had to ask so many questions, and why the issue form has a step by step list to describe how to reproduce the issue.
> 
> Thanks, @OpenRift412

Sorry, updated the main post, does this help?

**Comment by kcgen** [comment] 2023-10-21 21:42
> Sorry, updated the main post, does this help?

Helps a lot! Thanks, @OpenRift412.

Also, thanks for helping test the dev build. ❤️

**Comment by johnnovak** [comment] 2023-10-24 22:27
Should we remove this misguided feature of the Windows installer version altogether @kcgen? I don't like it at all and only the Win installer is affected, no other platform and install method. A very questionable feature.

My point: not everybody using the installer would like this command to be autoexecuted. Following the upgrade process in the release notes is much preferable.

**Comment by kcgen** [comment] 2023-10-24 23:41
Yup; I'd rather users manually perform this step (and have it behave consistently across the board).  Otherwise our release docs will have to say, _"Except for users on Windows running the installer..."_ and even then, it might have generated some kind of error.

**Comment by johnnovak** [comment] 2023-10-25 00:14
> Yup; I'd rather users manually perform this step (and have it behave consistently across the board). Otherwise our release docs will have to say, _"Except for users on Windows running the installer..."_ and even then, it might have generated some kind of error.

100% my thoughts, @kcgen. Another one for the chopping board 😆 🔪 🪓

**Comment by Grounded0** [comment] 2024-01-01 03:58
`config -wcd` works. Should be mentioned in the release notes as working. Closing.

**Closed by Grounded0** 2024-01-01 03:58 UTC
Labels: bug

**Comment by johnnovak** [comment] 2024-01-01 04:07
> `config -wcd` works. Should be mentioned in the release notes as working when upgrading from 0.80.1. Closing.

I have revised the instructions for upgrading as `config -wcd` is not a good approach. Please see the notes.

**Comment by Grounded0** [comment] 2024-01-01 04:14
Closing as unresolved.

**Comment by johnnovak** [comment] 2024-01-01 04:28
> Closing as unresolved.

No, it's actually fixed as the originally reported issue is fixed; I removed the autoexecustion of the `config -wc` command from the Windows installer at the first launch.
