### ISSUE TITLE
Recent build change harms Homebrew availability

### ISSUE THREAD

**Issue by unjello** [dosbox-staging/dosbox-staging#3443] opened 2024-02-23 18:40 UTC
There was a change made recently https://github.com/dosbox-staging/dosbox-staging/commit/e1dd3e283572d54b051f438caecf450c281e0130 to hardcode and force-build all dependencies on your own.

I have tried to bump dosbox-staging's Formulae in Homebrew but apparently their maintainers are very strict on not having hardcoded bundled dependencies. See discussion here: https://github.com/Homebrew/homebrew-core/pull/163169

Is that strategy change up for discussion?

**Comment by johnnovak** [comment] 2024-02-23 19:33
> Is that strategy change up for discussion?

Not really. We've made a decision to pin our dependencies per release as that's the only practical way to guarantee reproduible builds and to avoid weird random bugs and regressions inherent to rolling libraries.

The official way to run Staging on macOS is via the app bundles published on our website. If our build approach conflicts with the Homebrew philosophy, then so be it; we're not concerned about Homebrew dropping support. We absolutely want exact library version per each release, so app bundles are perfect for that

**Comment by Grounded0** [comment] 2024-02-23 21:25
MacPorts is perfectly fine about using bundled dependencies so anyone wishing to use a package manager on macOS to get DOSBox Staging should be shifting to MacPorts.

**Comment by weirddan455** [comment] 2024-02-23 21:49
It is kind of unfortunate the way the Meson wrap is hardcoded there.  This was done in the final days leading to v0.81 where we were trying to get our ducks in a row for producing our binary distribution.

Long term, I believe the plan is to switch to vcpkg for managing our dependencies.  Theoretically this should both let us pin our versions while also allowing downstream packagers to link to system libraries if they so choose (downstream can choose not to run the vcpkg step).

Short term, Homebrew should be able to do a quick patch to our Meson script to dynamically link (maybe as simple as reverting the commit you linked).  I know Linux distros aren't shy about patching upstream code to fit their build systems.

**Comment by johnnovak** [comment] 2024-02-23 21:57
> Long term, I believe the plan is to switch to vcpkg for managing our dependencies.

Well yeah, that's the other thing, we want to fully move to vcpkg eventually.

Ultimately, we can only gurantee tested functionality with our pinned library versions. If people repackage our stuff with different library versions, all bets are off.

**Comment by kklobe** [comment] 2024-03-07 20:26
I'm willing to take a quick look at this. There's a `wraps_disabled` option in `meson.build` that I should be able to easily apply as an additional test for the SDL wraps I forced; it should be an easy change to tweak the brew formula to pass that option for the build.

**Comment by Grounded0** [comment] 2024-06-17 11:56
Homebrew seems to be tracking our releases. Closing.

**Closed by Grounded0** 2024-06-17 11:56 UTC
Labels: build system
