### ISSUE TITLE
`fullresolution = desktop` does not respect Retina screen resolution on macOS

### ISSUE THREAD

**Issue by tobx** [dosbox-staging/dosbox-staging#1616] opened 2022-04-04 02:43 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Relevant hardware info

MacBook with Retina screen and external 2160p display

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

With the following setting

```ini
[sdl]
fullresolution = desktop
output = opengl
```

on a Retina screen the resolution is only set to 50% and then scaled up.

E.g. I have a 2160p screen and setting `fullresolution = desktop` looks exacty like `fullresolution = 1920x1080` while setting it to `3840x2160` looks crisp and sharp:

Screen section with setting `fullresolution = desktop`:

![desktop](https://user-images.githubusercontent.com/6427718/161464859-fc3405b8-129b-439c-a7b7-abe8c48ed8c3.png)

Screen section with setting `fullresolution = 3840x2160`:

![3840x2160](https://user-images.githubusercontent.com/6427718/161464861-7f4db516-75d4-41f8-a367-3e28e9b6717b.png)

Same effect on the internal screen of the MacBook.

### Steps to reproduce the behaviour.

2. Set `fullresolution = desktop`
3. Start dosbox and switch to full screen

### Your configuration

```ini
# see description
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by tobx** [comment] 2022-04-04 03:23
This is probably a duplicate of #759. At least the WIP build from [here](https://github.com/dosbox-staging/dosbox-staging/actions/runs/2084304617) solves the issue for me.

**Comment by GranMinigun** [comment] 2022-06-26 13:32
Closing as a duplicate of #1611.

**Closed by GranMinigun** 2022-06-26 13:32 UTC
Labels: bug
