### ISSUE TITLE
Might and Magic World of Xeen MT-32 Crashes

### ISSUE THREAD

**Issue by citrixscu** [dosbox-staging/dosbox-staging#422] opened 2020-06-11 03:32 UTC
Game compatibility issue here.

Game: Might and Magic 4-5 (World of Xeen) GOG Version
OS: Windows 10 v1909
dosbox-staging version: 0.75.0
Issue: Play game using MT-32 music (either via MUNT or a VST host and MidiPlayer5. Walk around for a bit. Music will hang, game will hang, or force quit.

**Comment by GranMinigun** [comment] 2020-06-11 04:29
Anything in status window? You can launch DOSBox through `cmd.exe` to not lose logs.

**Comment by citrixscu** [comment] 2020-06-11 04:59
Nothing relevant, unfortunately.

**Comment by kcgen** [comment] 2020-06-12 16:09
@citrixscu, made several attempts (walked around for a long time, killing random green blobs in the town), and couldn't get it to crash.  That said, my CD game doesn't play MT32 music despite being configured to do so.  I only have sound effects.

I do notice that when I hard-quit it via `Ctrl+F9`, it leaves in some kind of invalid or broken state with dosbox reporting (various) glitches in it's core; so this might indicate that something has already gone off the rails internally prior to me pushing Ctrl+F9, but it just hasn't manifested yet.

**Comment by citrixscu** [comment] 2020-06-13 02:42
@kcgen thanks for trying to duplicate the issue. I'm going to try playing it under Linux with mt32d and see if it still crashes.

**Comment by kcgen** [comment] 2020-06-13 03:32
I'm running it at 10500 cycles; anything below that and I get a horizontal graphical tear when moving.

Does the game run without issue with DOSBox-SVN swapped in place; leaving everything else the same?

**Comment by kcgen** [comment] 2020-06-13 03:48
Just rounding up some references:
- _"it just gets stuck at the title screen (with the dragon) right before sound starts"_, [2003, Vogons](https://www.vogons.org/viewtopic.php?t=2034)
- _"device driver fix for reset, faults, wrong controller values (includes Xeen)"_ - [2013, Vogons](https://www.vogons.org/viewtopic.php?t=35811)
- _"but as soon as I go to leave... where it should return me to the 'game world' the game locks up. The music keeps playing, but the game itself (and the mouse) just sits there locked and I can't do anything other than kill the DOSBox window."_, [2004 Vogons](https://www.vogons.org/viewtopic.php?p=34640#p34640)
- _"I enter towns and all that just fine, the problem is that the game will either lock-up on or drop back to the command prompt with the message "error drawing sprite in window"_, [2007, Vogons](https://www.vogons.org/viewtopic.php?p=106511#p106511)
- _"I downloaded World of Xeen and have tried running it in both DOSbox and VDM sound, but either way I get the same problem---the game freezes"_, [Abandonia, 2005](http://www.abandonia.com/vbullet/showthread.php?t=4797)
- Various reports of success and failure (but most using SB or Disney for music), [DOSBox.com, 2003-2014](https://www.dosbox.com/comp_list.php?showID=107&letter=M)

My guess is Xeen has some bugs :-) But perhaps they only manifest badly when using MIDI/MT-32 output.  

ScummVM 2.1.0 added support for the Xeen series (as of Oct 2019); so this might be better avenue if you're going to invest real time into the game; to avoid having a crash waste hours of gameplay. https://www.scummvm.org/news/20191013

**Comment by citrixscu** [comment] 2020-06-13 14:23
@kcgen 

I tried in ECE r4353 and reproduced a hard lock and a crash to desktop, so the issue is not limited to dosbox-staging. 

Thanks for the info re: ScummVM. Unfortunately, there was never a MIDI driver ever developed (at last I checked) for Xeen under ScummVM, so the sound is not great. Part of the magic of the game is the nostalgia using MT-32 or SC-55.

**Comment by kcgen** [comment] 2020-06-15 04:58
@citrixscu , suggest we close this for now because it's very likely due to game bugs and not specific to the delta-code added 9r modified by dosbox-staging.  

If a general fix of improvement is discovered that happen to fix this game (and possibly other issues), we will certainly be interested! Till then, lets backburner this.  We will reopen if new info or investigation surfaces.

**Comment by citrixscu** [comment] 2020-06-18 05:20
Sounds reasonable. Thanks for looking into this.

**Closed** 2020-06-18 05:21 UTC
Labels: game compatibility

**Comment by johnnovak** [comment] 2022-01-19 12:45
For anyone who reads this: play the Macintosh version (available at a certain "garden"...) It has full voiceover while the DOS version has only very minimal, higher resolution graphics, and the music plays from audio files recorded from a Roland MT-32 (a bit noisy, and sometimes a little distorted, but hey, that's still better than the Adlib driver, the only one that's working reliably under DOSBox).

**Comment by GranMinigun** [comment] 2022-01-19 12:50
If you mean voices of quest givers, then they are present in CD version of World of Xeen.

**Comment by Grounded0** [comment] 2022-01-19 13:11
"This is the original CD version, not the GoG version. The GoG version contains issues that were not present in this original version. For example spells in the GoG version have been mixed up, cleric spells only available to the ranger and knight, but not the cleric. The GoG version does not even match up with the supplied PDF manual."

Looks like original CD version for DOS is good also.

**Comment by johnnovak** [comment] 2022-01-19 22:34
> If you mean voices of quest givers, then they are present in CD version of World of Xeen.

There's *way* more voiceovers in the Mac version. I just played the opening area a little bit yesterday to compare, and in the Mac version pretty much every text spoken by every single NPC is voiced, while in the DOS original only a few "important" sentences are voiced, and many NPC interactions have only text. Check out a few youtube videos of the Mac World of Xeen and you'll see!

I read that this is because of the superior compression scheme used in the Mac version. The Mac port uses compression for the audio files, hence managed to packed a lot more content into a single CD than the 2 CD DOS original.

**Comment by finalpatch** [comment] 2026-06-14 00:35
I know this issue is closed (and you are absolutely right this is a game bug). But in case anyone is interested, I recently tracked this problem down and made a fix  https://finalpatch.github.io/xeen/index.html

**Comment by johnnovak** [comment] 2026-06-14 00:54
> I know this issue is closed (and you are absolutely right this is a game bug). But in case anyone is interested, I recently tracked this problem down and made a fix https://finalpatch.github.io/xeen/index.html

Wow, just wow! 😎 

> This was a thirty-year-old bug hiding behind an audio option almost nobody chose, in a code path that only misfires when an interrupt catches the CPU holding the wrong value. It crashed real hardware in 1993 and it crashes emulators today, for the same reason.
> If you want to play World of Xeen the way the composers intended — on an MT-32 or with Munt — you no longer have to choose between the good soundtrack and a stable game.

That's excellent, stand-out work @finalpatch 💯 We should document this on our game issues wiki by all means! Feel free to do that if you feel like it, or one our volunteers can do it.

@Python-Exoproject I think you'll want to include this in eXoDOS if you haven't already done so.

**Comment by MasterO2** [comment] 2026-06-14 01:02
Now documented at https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#fixing-the-games-mt-32-driver-crashing.

**Comment by johnnovak** [comment] 2026-06-14 01:16
Thank you very much @MasterO2 🔥 😎 🤘🏻
