### ISSUE TITLE
I Cannot boot the operating system using the command "boot -l c"

### ISSUE THREAD

**Issue by dogos1** [dosbox-staging/dosbox-staging#522] opened 2020-07-28 05:30 UTC
I tried to boot from hard drive image which I have created several years ago using dosbox 0.74 . 
I insert below code into dosbox-staging.conf at the bottom.
```
imgmount c harddisk.img -size 512,32,2,640 -fs fat
boot -l c

```
but  when I run dosbox-staging, it said that "Unable to boot off of drive C"
I also tried this code in the "Dosbox-x 0.83.3" and It succeed to boot "harddisk.img" file of hard drive image.

You can also try out by download below google drive link.
[hard drive image I created before](https://drive.google.com/file/d/1TQU9ifLpz-6gN52wvolQPiJLG_PEuFus/view?usp=sharing)
Is there any workaround to boot off of hard drive image which I created before in dosbox-staging?

**Comment by dreamer** [comment] 2020-07-28 19:36
@dogos1 - thank you for raising this issue;

Can reproduce - this is a regression compared to both current SVN and 0.74-3 (I can boot this hdd image in both versions). I'll investigate further and try to find out which change caused the regression, stay tuned.

**Comment by dogos1** [comment] 2020-07-29 03:31
Thank you very much for considering fixing this problem in the next update!
Frankly speaking,My origianl intention is to use CD-ROM drive after successfully booting MS-DOS in DOSBox-staging.
I heard from vogons community that "mounting a CD while booting requires the IDE emulation".

https://www.vogons.org/viewtopic.php?t=47076

Does current version of DOSBox-staging supports IDE emulation?

**Comment by kcgen** [comment] 2020-08-07 20:47
@dogos1 ,

Besides the issue and regression, can you share what you're trying to play from CDROM?  

From what I understand, only handful of known games need to be loaded from HD image (instead of simply a flat directory tree on the host OS).

These are:
- European Racers (1993)
- Operation AirStorm (1994)
- Pilgrim Quest (1991)
- Backroad Racers (1993)

These will actually load and play with sound effects without using a HDD image; however audio embedded in their movie clips will be mute during playback sequences.. so it's quite a subtle issue. 

 Unless you're trying to play one of those, we might be able to avoid this complexity and get you up and running asap.

**Comment by dogos1** [comment] 2020-08-12 13:18
@kcgen
Thank you very much for your reply and your interest.
Frankly speaking,I tried to play localized version(korean) of japanese dos/v game(power dolls series),and It is very extremely tricky to enable to play sound effect and midi music in gameplay.in order to play midi and sound effect in power dolls2,"CTSB16.SYS" or any sb16 device file must be loaded into 640K Conventional Memory in dos,and sb16.cfg file must contains below line.
`SYNTH:2 MAP:G MODE:1 A220 I7 D1 H5 P330 T6`
I narrowly have succeed to play midi music of power dolls2,But it is impossible for me to play midi music of power dolls2 dash

[You can download this link which contains harddisk image of power dolls2]
(https://drive.google.com/file/d/14SWVNFr41KbZv_fMKWNkK5RCT6G80C19/view)
you must insert below line into dosbox-staging.conf
```
imgmount c harddisk.img -size 512,32,2,640 -fs fat
boot -l c
```
I have created a youtube videoclip which demonstrate how you execute and play power dolls2 with this harddisk image.
https://www.youtube.com/watch?v=QqBS7v33Q34&t=315s

I also have  localized version of dos/v power dolls2 dash which is cd image file(iso). But So far,It was impossible for me to play midi music in dosbox. I want to experiment with it in the boot mode as power dolls2.As far as I know, IDE emulation is essential,If you want to mount any cd-rom image of games in the boot mode..
[You can download this link which contains harddisk image and CD image of power dolls2 dash](https://drive.google.com/file/d/17HbLuTqqIdE2NNlRyfSuhsx4mRNq0C2f/view?usp=sharing)
It would be necessary to insert below line into dosbox-staging.conf

```
imgmount 2 "image40.img"-size 512,63,2,650 -t hdd -fs none 
imgmount d "P2DASH.iso" -t iso
```

**Comment by kcgen** [comment] 2020-08-12 17:59
@dogos1 , indeed - those are two tricky games!

I was able to make some small adjustments to avoid using images, and still get MIDI output in Power Dolls 2. 
- Extract [:folder: power_dolls_2.zip [4.5MB]](205.250.146.105:8001/staging/power_dolls_2.zip
- Change directories into `power_dolls_2`
- Inside the directory, run `start.bat` with your dosbox-staging executable.
- I've included a local `dosbox.conf`, which will be used automatically.
- Note that I've configured the `[midi]` section for Linux - so you might have to change that to fit your midi player.

For Power Doll 2 Dash, I was also able to avoid the HDD image as well a CDROM image (the ISO turned out to be a mode2/2352 type binary image). Unfortunately though the game does not appear to have MIDI output.  The synth audio loader programs, `synups2.com` and `synups7.com` both only load OPL3 content.

- Extract [:folder: power_dolls_2_dash.zip [37MB]](205.250.146.105:8001/staging/power_dolls_2_dash.zip)
- Same steps as above, and same note about the `[midi]` section in the included `dosbox.conf`.

A bit more insight about the synups program is here:

https://m.blog.naver.com/PostView.nhn?blogId=mokomoji&logNo=220987421544

This different program is invoked with:

``` text
syn388 > nul
synplay > nul
g4x
synplay > nul
synups > nul


The syn388 might indicate it's a MIDI port, as opposed to an Adlib/SB port (220/230/240/..).

And further down, we see a file listing:

``` text
1996-01-09  오후 11:14            15,403 SYN210.COM
1996-01-09  오후 11:12            15,406 SYN388.COM
```

So this is a bit more evidence that this "syn" software comes with an OPL/FM loader, and a MIDI loader.

**Comment by dogos1** [comment] 2020-08-13 10:51
Thank you very much for your reply!
I forgot to mention that It is impossible to enable sound effect in Power Dolls2 without Sound Blaster 16 emulation.
25 years ago,I played it for the first time,At that time I have 486 DX PC and a Sound Card which is compatible with Sound Blaster Pro1, So I could not hear any sound effect but only FM music during gameplay..In order to enable sound effect in Power Dolls2,You must modify "sbtype" to "sb16" in dosbox.conf file.

I read this page which you referred to. It is just reference for successfully running Localized DOS/V version of Legend of the Galactic Heroes 4 EX in dosbox. He just show all the setting of dosbox.conf and whole files in order to verify all files' size.
I tested  Localized DOS/V version of Legend of the Galactic Heroes 4 EX in dosbox-staging, tried all of syn* audio tools but only synups.com is successfully enable GS midi Sound.
As you can see from below videoclip when you execute "enu4.bat" it would be enable GS midi Sound.

https://www.dropbox.com/s/0q6ep8scpo5cbmp/bandicam%202020-08-13%2013-57-41-859.avi?dl=0

contents of enu4.bat
```
@echo off
mouse > nul
ginsysf -f:ginfont.fnt -tj > nul
synups > nul
synplay > nul
g4x
synplay > nul
synups > nul
ginsysf -r > nul
```
in order to enable midi Sound in Legend of the Galactic Heroes 4 EX, You must set "oplmode" to "opl3" or "opl3gold" in dosbox-staging.conf



[You can download this link which contains DOS/V version of Legend of the Galactic Heroes 4 EX](http://cfile255.uf.daum.net/attach/2639533D581EBDC52C573B)

[It is floppy disk image(eight disk).You should install it on harddrive in order to play.and It has manual lookup copy protection.I think G4X.EXE is a crack file which is located on eun4ex.zip](https://drive.google.com/file/d/1jmsN3GCPNtSQPVqUhxzpTs9zG5Rg1e0z/view?usp=sharing)

I renamed synups.com from eun4ex.zip to synups2.com and copied(overwrite) it to folder in which Power Dolls2 Dash installed.But It seems  that this synups audio tool is older version.So there was no sound when I play Power Dolls2 Dash...
I look into files of  Power Dolls2 Dash and there is a file  named midigm.cfg. it consists of below files
```
PD2_08GM.MMM
PD2_09GM.MMM
PD2_06GM.MMM
....
```
Which is surely General MIDI file.I confirmed that Power Dolls2 also has this format of files and when I play Power dolls2, It display GM Sound Module Mode in my Sound Canvas VA.
I think Power Dolls 2 Dash intend to supports GM MIDI Sound,If there is someone  who is able to manipulate exe file then It would be possible to change FM output to MIDI like Power dolls2.

**Comment by kcgen** [comment] 2020-08-13 18:59
Do you know what I can do to confirm sound effects are working in PD2? (I can't read the text, so can't get very far).

In the meantime, if you set  `sbtype=sb16` in the conf, and then use the following - does that give you sound effects?

``` text
@echo off
p2\pdsysf -f:p2\pdfont.fnt -tj
ddloader.com p2\ctsb16.sys /UNIT=0 /BLASTER=A:220 I:5 D:1 H:5 P:330 T:6
ddloader.com p2\ctmmsys.sys
config -set "sblaster sbtype=sbpro2"
cd p2
gogo %1 %2
pdsysf -r
exit
```

The idea is that maybe 'gogo.exe' can still interface with the loaded ctsb16.sys driver, while under the hood we've swapped it w/ the sbpro2 (which still is largely compatible). 

None the less - It's very baffling why (or how) sb16 can work properly when using IDE images; there must be a small bug somewhere.

Very interesting regarding your tests.  I don't have anything else I can think to try on the game-side of things. 

> I think Power Dolls 2 Dash intend to supports GM MIDI Sound,If there is someone who is able to manipulate exe file then It would be possible to change FM output to MIDI like Power dolls2.

Do you know if PD2 Dash generates MIDI output on real DOS hardware?

**Comment by dogos1** [comment] 2020-08-14 05:46
PD2 is Basically same with PD1 which have been sold by Megatech Software in 1995. It largely has two part in each mission. First part is organizing equipment and selecting Strategy plan. Second part is controlling all of mechanized robot in turn-based strategy game style.
All of sound effects in PD2 is working in Second part.
When you start PD2 in dosbox and select "Data load" from first screen, there is several savedata which beginning with "campaign xx(name of mission in korean) , past time in game or organizing(first part) ,   year/month/date, hours"

You would noticed that there is many savedata which contains "편성" in their names. 편성 means organizing in korean, Thus 
It is First part of game. You must exclude all of savedata which contains "편성" and select a savedata which has second part of game, in order to confirm sound effects in PD2.

I created a videoclip which demonstrate how to confirm whether sound effects are working or not in PD2.

[I replaced "start.bat" with  your modified script and execute "start.bat" in dosbox-stating ,then record this videoclip, As you can see, It doesn't work any sound effects in PD2 play.](https://www.dropbox.com/s/6qifmrrnizs9xaq/bandicam%202020-08-14%2012-43-08-597.avi?dl=0)
[It was recorded in dosbox-ECE,because It supports boot mode and sb16 emulation,As you can see,You can hear machine gun sound 0:44-0:54  1:40-1:42](https://www.dropbox.com/s/6qvgc7pzuvzo732/bandicam%202020-08-14%2012-27-45-993.avi?dl=0)

**Comment by kcgen** [comment] 2020-08-14 09:22
Thanks for the background and detailed instructions to test sound effects; I was able to repeat your steps and confirm on my side. 

Not much progress, but did manage to get midi working with SB16 in both games (including dash) however they need to launched via Windows 3.11.

- Extract  [:file_folder: power_dolls_2_win_midi.zip [65MB]](http://205.250.146.105:8001/staging/power_dolls_2_win_midi.zip).

There's a common `dosbox.conf` (with Linux MIDI config), along with both games having their own launch batch file.

You can also edit the `windows\common.bat` and knock out the ddloader lines, and MIDI will still work; but I couldn't figure out any combinations to get the sfx working. Maybe you'll have better luck! :-)

**Comment by dogos1** [comment] 2020-08-14 16:23
Thank you very much for your reply.
I extracted "power_dolls_2_win_midi.zip" file and launched pd2dash.bat in Dosbox-staging,But It seems that It is impossible to enable MIDI music in PD2 DASH..

[You can confirm the result as shown on this videoclip](https://www.dropbox.com/s/b1r0q65mfesjstn/bandicam%202020-08-15%2000-39-05-763.avi?dl=0)
However,MIDI music is working in PD2, by launching pd2.bat in Dosbox-staging.

By the way,I just have noticed that I have another dos/v game(Ryuuki Denshou) which make use of audio tools of synups2.com.
Audio tool(synups2,com) from Ryuuki Denshou is the same with tool from PD2DASH. They both has exactly the same hash value.
But It is also impossible to enable MIDI Music in Ryuuki Denshou..I even changed sound option of FM to MPU MIDI or RS MIDI in startup menu.
[First,You must launch "play.bat" and Select "환경설정(configuration)"- "음원선택(Setup Sound)"-"MPU" or "RS MIDI" one by one in drop down menu,Then select 모험 이어서(continue gameplay)]
.But It only works FM Music whenever I select any sound option..

[DOS/V version of Ryuuki Denshou](https://www.dropbox.com/s/q7yg1ehd7zzwljc/dragoon.rar?dl=0)

I strongly suspect that audio tool of "synups2.com" has serious bug in its executable code which prevent from enabling MIDI music.

**Comment by kcgen** [comment] 2020-08-14 18:14
Argh :-) I was fooled by the quite nice sounding FM OPL3 music!  Thank you @dogos1 for catching that via your GUI midi player. Very interesting regarding Ryuuki Denshou as well.  

> I strongly suspect that audio tool of "synups2.com" has serious bug in its executable code which prevent from enabling MIDI music.

Indeed.  Reading about DOS/V, in theory it should have maintained compatibility with "standard" DOS hardware (like the SB and MIDI), but I suppose there might be deeper differences. 

I could only find one reference to DOS/V on Vogon's, and **wd** (a DOSBox developer) mentions that disk images might be needed:

https://www.vogons.org/viewtopic.php?t=16508

Which is correct per your findings as well. 

I'm still not sure why **wd** would suggest disk images.. could this be merely that DOSBox's will parse and load `config.sys` and `autoexec.bat` (presumably that could be offered using flat files without the image though); so maybe there is other magic at play as part of the "boot" sequence?

@dreamer, @Wengier , @joncampbell123 - I'm in the dark here; curious if you can shed light into what other magic happens when DOSBox "boots" a FAT16 boot disk -- beyond the loading `config.sys` and `autoexec.bat`.  Given the EXO project also needs HDD images for some games (for this same reason), it would be very nice to separate the **boot** functionality from the need to have everything stuff in an opaque HDD image.

(hey.. you can tell I'm not a fan of HDD images :rofl: )

**Comment by joncampbell123** [comment] 2020-08-14 19:00
From my experience with MS-DOS at least, MS-DOS 6.22 and higher have some built-in drivers in IO.SYS, then devices are loaded from CONFIG.SYS and then AUTOEXEC.BAT is run.

However MS-DOS 6.22 will also load DBLSPACE.BIN and HIMEM.SYS automatically at boot as well. You *can* prevent that by hitting F8 and using the boot menu to "confirm"  each boot entry, where the prompts do make it obvious it's doing that.

COMMAND.COM for Windows 95 and higher will automatically run WIN.COM after AUTOEXEC.BAT unless the INI settings in MSDOS.SYS list BootGui=0

**Comment by kcgen** [comment] 2020-08-14 20:00
Thanks for these details @joncampbell123; Indeed I had mostly forgot about IO.SYS and MSDOS.SYS after having last used them in ~80s and 90s on real hardware.

Reading https://en.wikipedia.org/wiki/IO.SYS:

> The first sector of the boot disk is loaded into memory and executed. If this is the DOS boot sector, it loads the first three sectors of IO.SYS into memory and transfers control to it. IO.SYS then loads the rest of itself into memory. Initializes each default device driver in turn (console, disk, serial port, etc..). At this point, the default devices are available. It then loads the DOS kernel is stored in MSDOS.SYS. At this point, "normal" file access is available.

I supposed we can conclude that DOSBox emulates almost all what IO.SYS and MSDOS.SYS provides, because 99.9% of games can run with no additional help. 

For the games that do need a HDD image, DOSBox is able to run and represent the conditions IO.SYS and MSDOS.SYS leave behind such that these games then work properly. 

So we've already got the HDD-image approach to get these games working. Another two options I see would be to invoke the DOS "boot load sequence" more directly using IO.SYS and MSDOS.SYS just as flat files; and the gold standard would be figuring out what conditions/states these leave behind - and emulate them directly in DOSBox.

**Comment by Wengier** [comment] 2020-08-15 03:49
@kcgen GRUB for DOS (GRUB4DOS) can load MS-DOS’s IO.SYS file directly as a flat file. I used it previously in a real DOS system for faster boot of DOS (and other operating systems):

https://sites.google.com/site/grubdos/

**Comment by kcgen** [comment] 2020-08-15 04:14
This is brilliant@Weinger; thank you! Will give this a go tomorrow.

**Comment by kcgen** [comment] 2020-08-29 20:29
@dogos1 , @Wengier ,

I was hoping GRUB would let us use a generic "sidecar" image (consisting of io.sys + msdos.sys + command.com) that we could place along side any flat directory of game files, for those games that require the'full DOS kernel.

The goal would be to avoid needing an entire HDD C:\ image for each of these games, and instead just use the sidecar image - and the game files could sit in a flat directory.

Prior to starting GRUB, I mounted the game directory to C: (`mount c .`) and the sidecar DOS boot-floppy to A: (`imgmount a dosboot.img`). With C: and A: now in dosbox, I chain-loaded A: (or `fd0` in grub-parlance) using GRUB, which works: DOS boots like on a hardware PC, leaving you at A: with command.com loaded.  However it no longer sees the C:\ I had previously mounted.

So even though the plan failed - this proved that dosbox atleast can boot a floppy image.  Next step is to figure out why it can't boot a HDD image.

**Comment by Wengier** [comment] 2020-08-29 20:45
@kcgen GRUB for DOS does support and can boot from a HDD image (which I have confirmed myself). But the HD drive must have been mounted with IMGMOUNT, not MOUNT (same for floppy drive A:). The reason for this is that DOS IO.SYS can only recognize FAT drives (FAT12/16/32), but (unlike IMGMOUNT command) the drive mounted by MOUNT command is not backed by a filesystem, so IO.SYS can not see it. One possible solution is to add the ability to MOUNT command to emulate a FAT filesystem, similar to QEMU's Virtual FAT filesystem (VVFAT) feature. Then GRUB for DOS should be able to boot from mounted local drives too, in addition to disk images mounted with IMGMOUNT.

**Comment by kcgen** [comment] 2020-08-29 21:01
Thanks for all the extra detail @Wengier .   Sounds like @dogos1 might be able to use dosbox-staing + GRUB to boot their existing PD2 HDD image as an immediate work-around for this issues.

QEMU's [VVFAT](https://github.com/qemu/qemu/blob/master/block/vvfat.c) "FAT-on-files" translation layer is impressive!

Looking at the set of includes:

``` text

#include "qemu/osdep.h"
#include <dirent.h>
#include "qapi/error.h"
#include "block/block_int.h"
#include "block/qdict.h"
#include "qemu/module.h"
#include "qemu/option.h"
#include "qemu/bswap.h"
#include "migration/blocker.h"
#include "qapi/qmp/qdict.h"
#include "qapi/qmp/qstring.h"
#include "qemu/ctype.h"
#include "qemu/cutils.h"
#include "qemu/error-report.h"
```

It would require quite a bit of code to be pulled in.

My understanding is the small number of HDD-image-needing games depend on some aspect of the MS DOS kernel currently not emulated by dosbox - and so their dependence on FAT is merely indirectly as a means to boot the kernel.  

If we could figure out the kernel bits they need, we could emulate that directly and avoid FAT all-together; atleast as a runtime-requirement for these games.

**Comment by Wengier** [comment] 2020-08-29 21:39
@dogos1 I believe IDE emulation is only supported by DOSBox-X (and its derivatives). Neither DOSBox or dosbox-staging supports it at this time.

By the way, in DOSBox-X the commands you typed can be simplified as follows:

```
imgmount 2 image40.img
imgmount d P2DASH.iso
boot c:
```

DOSBox-X tries to make things easier for normal users to get started and use it. Perhaps dosbox-staging can do something like this in the future too.

**Comment by dreamer** [comment] 2020-08-31 15:20
With @Wengier's fix I am able to successfully imgmount example drive image and run the game inside (although the sound was missing - but I presume we'll need a new bug report if it's a bug - I can't say).

Closing; @dogos1 if the issue is still happening for you (test [development builds](https://dosbox-staging.github.io/downloads/devel/), please) - then feel free to reopen this issue.

**Closed by dreamer** 2020-08-31 15:20 UTC
Labels: bug

**Comment by dogos1** [comment] 2020-09-17 12:47
Thank you very much for fix this bug of not able to boot off.
I tested the latest development builds of dosbox-staging, and As you can see from below videoclip, It sound both of sound effect of gunfire and MIDI music very well.
https://www.dropbox.com/s/9y8pwro85bgr8yv/bandicam%202020-09-17%2021-36-51-199.avi?dl=0
