### ISSUE TITLE
Mouse non-functional in 3dfx version of DESCENT 2

### ISSUE THREAD

**Issue by x73rmin8r** [dosbox-staging/dosbox-staging#3891] opened 2024-08-23 03:30 UTC
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

84963 dev build and RC1 0.82.0

### What Operating System are you using?

Windows 11

### Relevant hardware info

r5 5600x, 7900xt 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There is no mouse input when D2VOODOO.EXE is run, either movement or clicks (the game itself runs with 3d acceleration as expected though. keyboard works). Mouse works properly when normal DESCENT2.EXE is run during the same instance of DOSBOX. As far as I can tell the two executables use the same settings configuration.

I looked around for general mouse issues involving D2VOODOO on real hardware but wasn't able to find anything. It's possible that I've just got something set up wrong, but I haven't seen mouse issues with any other games I've tried. I don't think I have any other 3dfx capable DOS games to test.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Descent 2 CDs are version 1.0, GOG release is 1.1
2. patch Descent 2 to version 1.2 (https://archive.org/details/D2PATCH)
3. copy 3dfx patch files into game directory (https://archive.org/details/D2VOODOO)
4. run D2VOODOO.EXE, verify no mouse input

### Download URL of affected game or software

https://archive.org/details/descent-2.iso

### Your configuration

```ini
https://gist.github.com/x73rmin8r/9dc9d454a74c7f15cf8c9915771286a7.js
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment] 2024-08-23 03:49
Doesn't happen with Carmageddon while in 3dfx mode so probably game specific if its our bug. Tested with 0.82.0 RC1.

**Comment by FeralChild64** [comment] 2024-08-23 04:49
Does it work if you start CtMouse driver before running the game (this could be a possible workaround)?
Another option you can try to workaround the problem is to use the original Microsoft mouse driver - but  it requires `dos_mouse_driver = false` in the DOSBox config file.

**Comment by Grounded0** [comment] 2024-08-23 05:10
First step is to grab a copy from eXoDOS and see does it work. We've spent so much time chasing ghosts here when the game was just set up poorly.

**Comment by FeralChild64** [comment] 2024-08-23 14:34
@Grounded0 I don't use eXoDOS or similar packages, I prefer to install everything by myself.

@x73rmin8r I confirm the problem.

Workaround, if you want to play with mouse:
- `dos_mouse_driver = false` in the DOSBox config file
- start the original `mouse.com` (Microsoft mouse driver, checked version 8.20; CuteMouse does not work)
- start the game

A very interesting bug, thank you :)

**Comment by x73rmin8r** [comment] 2024-08-23 18:16
Thanks everybody!

Can confirm that loading MOUSE.COM  8.2 fixes it. Don't envy you guys in untangling exactly what's going on here.

**Comment by FeralChild64** [comment] 2024-08-23 18:52
I’ll try to investigate this, so please keep this ticket open for now.

**Comment by FeralChild64** [comment] 2024-08-23 22:00
I did some more testing, the game just calls two mouse functions of DOSBox - 0x00 (reset driver, read status) and 0x20 (enable the driver). That's it, no more mouse driver communication.

The game seems to be VERY picky regarding the mouse driver it accepts. It seems to require Microsoft mouse driver v7.x or later. Earlier Microsoft driver do not work. A4Tech, Genius, Mouse Systems, Caldera - these drivers does not work with Descent II Voodoo. Same with VBADOS and CtMouse.

**Comment by johnnovak** [comment] 2024-08-23 22:04
@FeralChild64 If making this would would  overly complicate the mouse code and potentially introduce regressions, maybe just document it on our game issues page and call it a day 😄

**Comment by FeralChild64** [comment] 2024-08-23 22:10
Right now the problem is, I don't have many ideas about what might be going wrong - most likely the game does something VERY fishy.

It seems the Descent II source code is now available, we'll see - maybe I'll find some clues there.

**Comment by FeralChild64** [comment] 2024-08-23 22:27
OK, from the published game source code:

```C
	// Enable mouse driver
	memset( &inregs, 0, sizeof(inregs) );
	inregs.w.ax = 0x0020;
	int386(0x33, &inregs, &outregs);
	if (outregs.w.ax != 0xffff )  // <---- WHAAAAAAAAAT???
		return 0;
```

Function `0x20` shouldn't return anything, according to the documentation I have. Putting `reg_ax = 0xffff;` at the end of `case 0x20:` (in the `int33_handler` function) indeed seems to fix the problem. And I can see most mouse drivers leave the `AX` alone - except for the Microsoft driver 7.04 or above...

**Comment by Grounded0** [comment] 2024-08-23 23:06
Microsoft Mouse driver v7.04 was released in 1990 and that was the most popular mouse driver for DOS so seems like a fix that should go in:

https://winworldpc.com/product/microsoft-mouse/7x

**Comment by johnnovak** [comment] 2024-08-23 23:10
> OK, from the published game source code:
> 
> ```c
> 	// Enable mouse driver
> 	memset( &inregs, 0, sizeof(inregs) );
> 	inregs.w.ax = 0x0020;
> 	int386(0x33, &inregs, &outregs);
> 	if (outregs.w.ax != 0xffff )                                 // <----  WHAAAAAAAAAT???
> 		return 0;
> ```
> 
> Function `0x20` shouldn't return anything, according to the documentation I have. Putting `reg_ax = 0xffff;` at the end of `case 0x20:` (in the `int33_handler` function) indeed seems to fix the problem. And I can see most mouse drivers leave the `AX` alone - except for the Microsoft driver 7.04 or above...

That was easy, great outcome! 🎉

**Comment by Grounded0** [comment] 2024-08-25 07:11
Workaround has been posted on Game issues until we figure out what to do with this:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#descent-1-and-2

**Comment by Grounded0** [comment] 2024-08-27 00:27
Updated Game issues wiki with the final fix:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#descent-1-and-2

**Comment by Grounded0** [comment] 2024-08-28 08:48
This game will be close to unplayable with v1.2 patch release so download links to an unofficial 3dfx patch has been posted on Game issues wiki:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#descent-1-and-2

**Comment by johnnovak** [comment] 2024-09-20 04:17
The conclusion was this game is an outlier when it comes to this weird mouse issue, so the fix was reverted:

- https://github.com/dosbox-staging/dosbox-staging/pull/3903

The solution is to use the unofficial patch as described in our wiki. The fact that we have mouse problems with the last official patch is quite academic as it has many other problems; the unofficial patch is needed to make the game playable.

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#descent-1-and-2

**Closed by johnnovak** 2024-09-20 04:17 UTC
Labels: bug, game compatibility, input handling
